### ISSUE TITLE
Add the verticalAlignment function to QMUILabel

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#1000]
like TTTAttributedLabel's TTTAttributedLabelVerticalAlignment

**Comment by codingiran** [comment]
@MoLice 恰好第1000个 issue 不如满足 @tospery 😋

**Comment by tospery** [comment]
除了TTTAttributedLabel的verticalAlignment属性，sizeThatFitsAttributedString:withConstraints:limitedToNumberOfLines方法也特别常用

**Comment by MoLice** [comment]
> 除了TTTAttributedLabel的verticalAlignment属性，sizeThatFitsAttributedString:withConstraints:limitedToNumberOfLines方法也特别常用

这个建议自行在业务代码里实现
