### ISSUE TITLE
Mac Catalyst版本调用[UIImage qmui_imageWithThemeProvider]会掉入死循环

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1001]
**Bug 表现**
Mac Catalyst版本调用[UIImage qmui_imageWithThemeProvider]会掉入死循环

**截图**
<img width="1042" alt="图片" src="https://user-images.githubusercontent.com/22904757/82791453-62eee200-9ea0-11ea-9fd9-b86a2fa2192d.png">
<img width="344" alt="图片" src="https://user-images.githubusercontent.com/22904757/82791472-6c784a00-9ea0-11ea-8aae-9cfc0e05554b.png">

**如何重现**
[QMUITestDemo.zip](https://github.com/Tencent/QMUI_iOS/files/4675956/QMUITestDemo.zip)
使用`My Mac`设备运行Demo即可复现

**预期的表现**

**其他信息**
 - 设备: iMac
 - iOS 版本: 无
 - Mac 版本:  10.15.4
 - Xcode 版本: Xcode 11.4.1
 - QMUI 版本: 4.1.3

**Comment by jiasongs** [comment]
找到原因了，如下：
QMUIThemeImage在`initialize`中遍历UIImage的方法列表，将QMUIThemeImage未实现的方法添加进去，我对比了iOS和Mac转制版的UIImage的方法列表，mac转制版比iOS多了21个方法，其中有一个方法`forwardingTargetForSelector`也添加到QMUIThemeImage中了，导致了循环调用，暂未找到解决方案，只能先屏蔽

**Comment by jiasongs** [comment]
将如下代码添加到QMUIThemeImage中，Mac转制版可以正常使用了，切换主题也是生效的。
<img width="462" alt="图片" src="https://user-images.githubusercontent.com/22904757/82809630-1f57a080-9ebf-11ea-86e3-23d7f2f47296.png">
目前不清楚有没有什么副作用

**Comment by MoLice** [comment]
已发布 [4.2.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.0) 修复该问题。
