### ISSUE TITLE
alertConvertValueWithView

### ISSUE THREAD

**Issue by wq469775163** [Tencent/QMUI_iOS#1003]
报错这个提示可能出现的情况？

   QMUILog(@"UIView (QMUI)", @"进行坐标系转换运算的 %@ 和 %@ 不存在共同的父 view，可能导致运算结果不准确（特别是在横竖屏旋转时，如果两个 view 处于不同的 window，由于 window 旋转有先后顺序，可能转换时两个 window 的方向不一致，坐标就会错乱）", self, view);

**Comment by MoLice** [comment]
这个报错信息里已经明确写了，只有两个 view 存在共同父 view 时才可能进行坐标转换，否则坐标转换的计算结果是不准确的，如果你得到一个看起来是正确的数值，也只是刚好跟你预期一致而已，计算本身依然是不精准的。

**Comment by wq469775163** [comment]
嗯呢，我明白你表达的意思。我遇到这个警告信息的场景：从tabbar根页面push到二级界面就会报这个警告信息，导致我二级界面计算不精致，我尝试了挺多修改，但是没找到具体原因。能大致帮我分析一下原因吗？感谢！

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/83056294-ba02db80-a087-11ea-824c-fb664d53ecc4.png)

这个原因是在 UIViewController+QMUI 内处理 tabBar 一些 bug 时不严谨导致的，你可以将本地的 QMUI 的那段代码改为截图红框所示即可，这个场景不会引发任何 bug，只是多了一条提醒。

至于你说的“导致我二级界面计算不精致”，具体是什么计算不准确的问题？
