### ISSUE TITLE
文本框获取焦点后,弹出键盘, 此时切换到后台,然后程序切换到前台. 键盘颜色发生改变.

### ISSUE THREAD

**Issue by javaoraspx** [Tencent/QMUI_iOS#1004]
**Bug 表现**
文本框获取焦点后,弹出键盘, 此时切换到后台,在程序切换到前台. 键盘颜色发生改变.

**截图**

**如何重现**
1. 运行最新demo程序.
2. 选择 QMUITextField 示例
3. 文本框中获取焦点,弹出键盘
4. 进入后台
5. 重新进入程序前台
6.键盘颜色被更换

**预期的表现**
主题未发生改变时. 键盘的主题颜色不应该被更改

**其他信息**
 - 设备: 模拟器,iPhone 7P
 - iOS 版本: [iOS 13.4.1]
 - Xcode 版本: Version 11.4.1 (11E503a)
 - QMUI 版本: [4.1.3]

版本 4.0.3 未复现
 - 设备: iPhone11
 - iOS 版本: [iOS 13.4.1]
 - QMUI 版本: [4.0.3]

**Comment by javaoraspx** [comment]
暂时解决方法
各个主题的config文件中
- applyConfigurationTemplate  
注释掉以下键盘相关代码
QMUICMI.keyboardAppearance = UIKeyboardAppearance* 

测试结果:夜间模式键盘也能自动更改

**Comment by jiasongs** [comment]
Duplicate of #997
