### ISSUE TITLE
QMUIModalPresentationViewController 概率性崩溃

### ISSUE THREAD

**Issue by JellyHell** [Tencent/QMUI_iOS#1008]
**Bug 表现**
线上产品概率性崩溃
bugly日志
![image](https://user-images.githubusercontent.com/4350951/83398608-44559180-a432-11ea-9313-abcd7968f77c.png)
![image](https://user-images.githubusercontent.com/4350951/83398634-4d466300-a432-11ea-8926-091dace69226.png)

**代码如下**
![image](https://user-images.githubusercontent.com/4350951/83399012-0a38bf80-a433-11ea-8c16-80e7df2a14a9.png)

**其他信息**
 - 设备: iPhone
 - iOS 版本: [iOS 10.x - 13.x]
 - Xcode 版本: [Xcode 11.4]
 - QMUI 版本: [4.1.3]

**Comment by MoLice** [comment]
提供的信息无法诊断，没有具体的出现场景和出错语句、原因，建议先排查如何复现问题。
