### ISSUE TITLE
修改 UITabBarItem 图片

### ISSUE THREAD

**Issue by Mandyhold** [Tencent/QMUI_iOS#1009]
我一直在使用QMUI_IOS 咨询一个问题QMUINavigationController的tabBarItem怎么设置网络图片，之前我一直使用的是如下的方法
  [[SDWebImageManager sharedManager] loadImageWithURL:url options:SDWebImageHighPriority progress:nil completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
        
        if (image && finished) {
            self.image = [image  imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
        } else {
            self.image = [placeholder imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
        }
    }];

现在设置不了了，请问QMUINavigationController有没有提供什么更加有效的方法

**Comment by MoLice** [comment]
测试过并没有问题？直接用 QMUI Demo，在 AppDelegate.m `generateWindowRootViewController` 方法里增加以下测试代码，可以观察到启动后一段时间第三个 tab 的图片被修改为红色。

```objc
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    labNavController.tabBarItem.image = [[UIImageMake(@"icon_tabbar_lab") qmui_imageWithTintColor:UIColorRed] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
});
```

![image](https://user-images.githubusercontent.com/1190261/83547461-d2b23c00-a534-11ea-9fbb-98bd25838ebb.png)
