### ISSUE TITLE
QMUIImagePickerViewController 使用presentViewController：调起后，页面一片空白，只有至地下的预览和发送按钮

### ISSUE THREAD

**Issue by DZflycat** [Tencent/QMUI_iOS#1010]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
该 issue 因提供的信息不全面而被关闭。
