### ISSUE TITLE
QMUITips

### ISSUE THREAD

**Issue by J8rry** [Tencent/QMUI_iOS#1011]
在使用QMUITips的时候, 显示Loding的时候, 无法左侧右滑, 也没办法点击当前页面view的其他控件

难道是因为集成了GKNavigationBar 一些全屏手势冲突?

**Comment by MoLice** [comment]
QMUITips 显示的时候会在它的 superview 里撑满，盖住其他 view，导致其他 view 不可点击，这是合理的做法，如果你不希望这样，那你选择一个合适的 superview 去显示，或者把整个 QMUITips 通过 `userInteractionEnabled` 设为不可点击即可。

**Comment by jiasongs** [comment]
也可以用qmui_hitTestBlock

**Comment by xlsd** [comment]
> QMUITips 显示的时候会在它的 superview 里撑满，盖住其他 view，导致其他 view 不可点击，这是合理的做法，如果你不希望这样，那你选择一个合适的 superview 去显示，或者把整个 QMUITips 通过 `userInteractionEnabled` 设为不可点击即可。

是的

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭，如有问题可以补充后重新开启。
