### ISSUE TITLE
不存在共同的父 view，可能导致运算结果不准确

### ISSUE THREAD

**Issue by bpdnd** [Tencent/QMUI_iOS#1013]
**Bug 表现**
1、我自己创建两个继承QMUITextField的textfield，第一个输入文字，点击第二输入框，控制台就会打印 ‘不存在共同的父 view，可能导致运算结果不准确’。
2、我尝试在QMUI demo下的QMUITextField下，再添加一个输入框，还是提示‘不存在共同的父 view，可能导致运算结果不准确’

**截图**
[这是我修改的官方demo的位置](http://bpdnd.gitee.io/picturebed/1.png)
[这是真机的界面显示](http://bpdnd.gitee.io/picturebed/3.PNG)
[这是Xcode控制台](http://bpdnd.gitee.io/picturebed/2.png)

**如何重现**
1. 在第一个输入框随意输入文字
2. 点击第二个输入框，Xcode就会有提示

**其他信息**
 - 设备: [iPhone6sPlus]
 - iOS 版本: [iOS 13.4.1]
 - Xcode 版本: [Xcode 11.5 (11E608c)]  
 - QMUI 版本: [4.1.3]

**Comment by MoLice** [comment]
按你提供的代码和操作，没出现你说的提示，以下是操作录屏：
[convertrect.mov.zip](https://github.com/Tencent/QMUI_iOS/files/4989727/convertrect.mov.zip)

如有需要请补充更多信息再重新打开 issue。

**Comment by MoLice** [comment]
另外新版本将会屏蔽系统的 UIFieldEditor 的提示，无需理会即可。
