### ISSUE TITLE
关于从隐藏导航栏push到非隐藏导航栏的疑问

### ISSUE THREAD

**Issue by friendsheeps** [Tencent/QMUI_iOS#1014]
QMUI 已经提供了**详尽的注释文档**，以及**完整的示例项目 [QMUI Demo](https://github.com/QMUI/QMUI_iOS_Demo)**，当你遇到某些功能不知道怎么使用，或者想知道 QMUI 是否有提供某些功能时，请先查看注释文档或者 Demo，找不到了再提 issue。若提的 issue 已有明确注释或示例的，**可能会被直接关闭或得不到及时的回复**，请知悉。

在配置表里automaticCustomNavigationBarTransitionStyle设置为YES，QMUICMI.navBarBackgroundImage 一开始设置为 nil ，QMUICMI.navBarBarTintColor = UIColorWhite，当从一个隐藏导航栏的 页面A Push到一个带导航栏的 页面B 时，页面B 的导航栏会有一点闪动，会先变成一个很浅的灰色，然后再变为白色，从 页面B pop 到 页面A 时，也会先变成浅灰色。
当把 QMUICMI.navBarBackgroundImage 设置为 [UIImage imageWithColor:UIColorWhite] 时这个问题就没有了。
我想咨询几个问题
1、配置表中QMUICMI.navBarBackgroundImage 设置为nil和 [UIImage imageWithColor:UIColorWhite] 会有什么影响，项目中一个页面用到了QMUINavigationBarScrollingAnimator，同事说QMUICMI.navBarBackgroundImage有值的话会影响导航栏渐变效果（我运行代码并没有发现问题）;
2、如果 QMUICMI.navBarBackgroundImage = nil，push的时候那个浅灰色是怎么出现的，可以修改么？
🙏🙏🙏

**Comment by MoLice** [comment]
> 1、配置表中QMUICMI.navBarBackgroundImage 设置为nil和 [UIImage imageWithColor:UIColorWhite] 会有什么影响

设置了背景图就没有磨砂。


> 项目中一个页面用到了QMUINavigationBarScrollingAnimator，同事说QMUICMI.navBarBackgroundImage有值的话会影响导航栏渐变效果（我运行代码并没有发现问题）

QMUINavigationBarScrollingAnimator 会根据滚动位置修改导航栏的样式，修改前和修改后的值都是在 viewController 的 `-(void)navigationBarBackgroundImage` 里决定的，他说的设置配置表的值会有影响只不过是因为没有在使用了 QMUINavigationBarScrollingAnimator 的地方重写 `-(void)navigationBarBackgroundImage` 并设置正确的值而已，具体直接查看 QMUI Demo 里对 QMUINavigationBarScrollingAnimator 的示例代码即可。


> 如果 QMUICMI.navBarBackgroundImage = nil，push的时候那个浅灰色是怎么出现的，可以修改么？

请提供截图。

**Comment by friendsheeps** [comment]
![WechatIMG471](https://user-images.githubusercontent.com/13128046/84560626-6925ff00-ad78-11ea-9486-ddb37ebd6b2b.jpeg)
push和pop时都会先出现浅灰色，导航栏颜色设置为的纯白色

**Comment by MoLice** [comment]
> ![WechatIMG471](https://user-images.githubusercontent.com/13128046/84560626-6925ff00-ad78-11ea-9486-ddb37ebd6b2b.jpeg)
> push和pop时都会先出现浅灰色，导航栏颜色设置为的纯白色

如果你设置背景图为nil，bsr就会是磨砂，磨砂的bar背后如果有内容，肉眼看上去就不会是你预期中的纯白色，如果你希望一直都是纯白色，你应该设置一张纯白色的背景图才对？

**Comment by friendsheeps** [comment]
已经设置了，谢谢耐心回答。
