### ISSUE TITLE
app边缘手势在iOS13.4系统上失效问题

### ISSUE THREAD

**Issue by xiwuxisheng** [Tencent/QMUI_iOS#1016]
问题：使用4.1.0以上版本时，由于UINavigationController+QMUI中关于边缘手势加入了一下代码：
// iOS 13.4 开始会优先询问该方法，只有返回 YES 后才会继续后续的逻辑
- (BOOL)_gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveEvent:(UIEvent *)event {
    if (gestureRecognizer == self.interactivePopGestureRecognizer) {
        NSObject <UIGestureRecognizerDelegate> *originGestureDelegate = self.qmui_interactivePopGestureRecognizerDelegate;
        if ([originGestureDelegate respondsToSelector:_cmd]) {
            BOOL originalValue = YES;
            [originGestureDelegate qmui_performSelector:_cmd withPrimitiveReturnValue:&originalValue arguments:&gestureRecognizer, &event, nil];
            if (!originalValue && [self shouldForceEnableInteractivePopGestureRecognizer]) {
                return YES;
            }
            return originalValue;
        }
    }
    return YES;
}
本身逻辑没有问题，其中shouldForceEnableInteractivePopGestureRecognizer方法的判断存在问题：
- (BOOL)shouldForceEnableInteractivePopGestureRecognizer {
    UIViewController *viewController = [self topViewController];
    return self.viewControllers.count > 1 && self.interactivePopGestureRecognizer.enabled && [viewController respondsToSelector:@selector(forceEnableInteractivePopGestureRecognizer)] && [viewController forceEnableInteractivePopGestureRecognizer];
}
可以看到这里强制要求在导航控制栈中的UIViewController实现forceEnableInteractivePopGestureRecognizer并且返回为YES,也就是必须实现UINavigationControllerBackButtonHandlerProtocol协议。

造成结果：iOS13.4以上的系统使用app时，会存在边缘手势失效问题。

原因：UIViewController控制器并没有实现UINavigationControllerBackButtonHandlerProtocol协议，一旦更改，为了实现该协议整体动手术代价太大。

测试：
1.qmuikit 4.1.1 iOS13.4(不包含)以下测试边缘手势结果正常；
2.qmuikit 4.1.0(不包含)以下版本边缘手势正常；
3.qmuikit 4.1.1直接屏蔽上述手势方法，在13.4系统正常；

结论：使用方式上需要优化或者这里的手势判断是否可以去掉，不看源码，边缘手势出现问题很难定位和解决

**Comment by MoLice** [comment]
forceEnableInteractivePopGestureRecognizer 并不是“要实现了才能返回，不实现就不能返回”，而是“当前情况下系统不允许你返回，但你在 forceEnableInteractivePopGestureRecognizer 里返回 YES 就可以强制开启手势返回”。

所以当你涉及到 forceEnableInteractivePopGestureRecognizer 时，必定意味着系统默认的实现里，认为你当前是不可以手势返回的，系统先屏蔽掉，所以才会轮到 QMUI 询问。

应该先检查为什么当前状态，系统不允许你的手势返回，例如是否隐藏了 navigationBar，或者隐藏了系统的返回按钮？
