### ISSUE TITLE
目前项目有一个需求就是在项目里面 window的根控制器是QDTabBarViewController继承自 QMUITabBarViewController ，执行某个操作后push到ShopTabBarViewController : QMUITabBarViewController

### ISSUE THREAD

**Issue by Dacilia** [Tencent/QMUI_iOS#1017]
场景：目前项目有一个需求就是在项目里面 window的根控制器是QDTabBarViewController继承自 QMUITabBarViewController ，执行某个操作后push到ShopTabBarViewController : QMUITabBarViewController   
QDTabBarViewController和ShopTabBarViewController有选中的时候 title需要显示不同的颜色 然而我重新设置 QMUICMI.tabBarItemTitleColorSelected=UIColorThemeMainColor 不起作用

**Comment by MoLice** [comment]
配置表都是通过 UIAppearance 去实现的，意味着它并不会区分不同的 tabBar。你这种情况，在想要差异化的 tabBarController 里设置自己的样式就行了。
