### ISSUE TITLE
您好，QMUIAlertController自定义view时，想让点击确定时满足某条件才能hide，不满足时弹出框提示，不hide

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#1018]
您好，QMUIAlertController自定义view时，想让点击确定时满足某条件才能hide，不满足时弹出框提示，不hide。比如，我想让用户必须勾选自定义view里面的内容。如果不勾选，点击确定的时候提示必须勾选，且QMUIAlertController不能消失。目前已经通过- (BOOL)shouldHideAlertController:(QMUIAlertController *)alertController代理方法实现了判断，但是点击取消按钮也没法hide了，请问是怎么处理呢

**Comment by LYluyu** [comment]
已实现，判断逻辑在代理方法`- (BOOL)shouldHideAlertController:(QMUIAlertController *)alertController`实现

**Comment by MoLice** [comment]
可以换个思路，默认把 `QMUIAlertAction.enabled = NO`，当勾选符合条件后，再把 `enabled = YES`。就不需要用到 shouldHideAlertController。
