### ISSUE TITLE
QMUIConfiguration 里面模板存在hard code

### ISSUE THREAD

**Issue by TMTBO** [Tencent/QMUI_iOS#1019]
在 QMUIConfiguration.m 文件第98行, 有下面这段代码, 里面对 主题模板类名是 hard code 的, 这里也没有说明, 不知是否存在优化空间?
```Objc
if ([NSStringFromClass(class) containsString:@"QMUIConfigurationTemplate"] && [class conformsToProtocol:protocol])
```

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/blob/master/QMUIConfigurationTemplate/QMUIConfigurationTemplate.h

上面链接所示的配置表模板注释已经有写明规则了。你指出的这段代码块上方的注释也附带了制定这些策略时的考虑：
    // 自动寻找并应用模板
    // Automatically look for templates and apply them
    // @see https://github.com/Tencent/QMUI_iOS/issues/264

所以应该不是“没有说明”。

**Comment by MoLice** [comment]
该issue因不活跃而被关闭。
