### ISSUE TITLE
能否在计算navigation title view的时候 考虑让title view始终居中?

### ISSUE THREAD

**Issue by archerx3** [Tencent/QMUI_iOS#1022]
_<强迫症晚期>_
在是用`QMUINavigationTitleView`时,期望它能够自己计算保持始终居中,而不是需要,我们来再次纠正它的frame,或者是约束.

比如:
1. 在navigation bar上,只有backBarItem或者leftBarItem,这时候title很长,有时候对title是否居中没什么要求.不过,有时候,可能出于美观 _<强迫症>_ 的目的,希望它保持居中.
2. 如果左右都有BarItem,不过它们的宽度不一,很多时候也能看出title不居中.

**Comment by MoLice** [comment]
titleView被如何布局，是系统navigationBar在管，不是QMUI控制的，你说的那种不居中的现象，是系统在那种情况下的默认行为，目前QMUI也没有计划去干预它，有需要的场景需要业务自行处理。
