### ISSUE TITLE
请问下，导航栏的返回按钮怎么设置它距离边缘的距离？（这个问题虽然很低级，不过真的是不懂啊，求教）

### ISSUE THREAD

**Issue by zhangBoy** [Tencent/QMUI_iOS#1024]
请问下，导航栏的返回按钮怎么设置它距离边缘的距离？（这个问题虽然很低级，不过真的是不懂啊，求教）

**Comment by fanyuecheng** [comment]
有个奇技淫巧   
```  
UIImage *image = [UIImageMake(@"nav_back") qmui_imageWithSpacingExtensionInsets:UIEdgeInsetsMake(0, 7, 0, 0)];  
QMUICMI.navBarBackIndicatorImage = image;  
```  
借由增加图片的左右内距，来使得backBarButtonItem、leftBarButtonItem、rightBarButtonItem改变了距屏幕边缘的距离

**Comment by zhangBoy** [comment]
> 有个奇技淫巧
> 
> ```
> UIImage *image = [UIImageMake(@"nav_back") qmui_imageWithSpacingExtensionInsets:UIEdgeInsetsMake(0, 7, 0, 0)];  
> QMUICMI.navBarBackIndicatorImage = image;  
> ```
> 
> 借由增加图片的左右内距，来使得backBarButtonItem、leftBarButtonItem、rightBarButtonItem改变了距屏幕边缘的距离

谢了，这个方法可以，同时要把sizeNavBarBackIndicatorImageAutomatically属性设置为NO
