### ISSUE TITLE
进入后台的时候UITraitCollection+QMUI.h中的方法出问题导致要刷新主题

### ISSUE THREAD

**Issue by kingstarwmx** [Tencent/QMUI_iOS#1025]
```objectivec
if (selfObject == firstValidatedWindow) {
	if (qmui_lastNotifiedUserInterfaceStyle != traitCollection.userInterfaceStyle) {
	 qmui_lastNotifiedUserInterfaceStyle = traitCollection.userInterfaceStyle;
	 [[NSNotificationCenter defaultCenter] postNotificationName:QMUIUserInterfaceStyleWillChangeNotification object:traitCollection];
	}
}
```
开暗黑模式以后qmui_lastNotifiedUserInterfaceStyle和traitCollection.userInterfaceStyle不相等，导致要发送QMUIUserInterfaceStyleWillChangeNotification这个通知去刷主题，但是当进入app后台的时候应该不会改变主题呀。

**Comment by MoLice** [comment]
你可以[阅读文档](https://github.com/Tencent/QMUI_iOS/wiki/%E4%BD%BF%E7%94%A8-QMUITheme-%E5%AE%9E%E7%8E%B0%E6%8D%A2%E8%82%A4%E5%B9%B6%E9%80%82%E9%85%8D-iOS-13-Dark-Mode)

![image](https://user-images.githubusercontent.com/1190261/84742159-a8f01f00-afe2-11ea-9936-bf4946a91bbf.png)

App 进入后台时会切换一次主题，本身就是系统的行为。
