### ISSUE TITLE
后台切换 iOS 13 Dark Mode 后主题不变

### ISSUE THREAD

**Issue by wjiuxing** [Tencent/QMUI_iOS#1027]
**Bug 表现**
我跑了一下 [QMUI/QMUIDemo_iOS](https://github.com/QMUI/QMUIDemo_iOS)，通过系统设置切换 Dark Mode 后进入 App，主题不变

**如何重现**
1. run [QMUI/QMUIDemo_iOS](https://github.com/QMUI/QMUIDemo_iOS) 项目；
2. 到系统设置中，Developer 选项页，切换 Dark Appearance；
3. 再次进入 [QMUI/QMUIDemo_iOS](https://github.com/QMUI/QMUIDemo_iOS) app

**预期的表现**
显示重现步骤中 #2 所设置的主题

**其他信息**
 - 设备: 模拟器 iPhone SE(2nd generation)
 - iOS 版本: [iOS 13.4.1]
 - Xcode 版本: [Xcode 11.4.1]
 - QMUI 版本: [4.1.3]

**Comment by MoLice** [comment]
无法重现。

QMUI Demo 默认在 iOS 13 下会自动响应系统的 Dark Mode 切换，当 QMUI Demo 处于后台时，系统 Dark Mode 切换了状态，此时唤醒 QMUI Demo，会触发当前 QMUIThemeManager 的 [identifierForTrait](https://github.com/QMUI/QMUIDemo_iOS/blob/master/qmuidemo/AppDelegate.m#L66-L74) block，从而刷新 App 的主题。
