### ISSUE TITLE
QMUIZoomImageView如何获取最后显示的rect,用于裁剪图片

### ISSUE THREAD

**Issue by R1n0-w** [Tencent/QMUI_iOS#1028]
QMUIZoomImageView如何获取最后显示的rect,用于裁剪图片

**Comment by MoLice** [comment]
获取 `QMUIZoomImageView.imageView.frame`，将该 CGRect 转换到 `QMUIZoomImageView` 本身的坐标系内，然后与 `QMUIZoomImageView.bounds` 做一下 `CGRectIntersection` 运算获取交集即可。
