### ISSUE TITLE
Controller继承QMUICommonViewController，点击切换tab，navigation标题会变为蓝色

### ISSUE THREAD

**Issue by D-james** [Tencent/QMUI_iOS#1029]
**Bug 表现**
Controller继承QMUICommonViewController，没有设置标题颜色，默认导航条标题黑色。点击切换tab，navigation标题会变为蓝色，需要在控制器重新指定颜色才不变色
self.navigationItem.titleView.tintColor = UIColor.blackColor;

**预期的表现**
不需要重新指定颜色，点击tab切换，nav 标题颜色不变

**其他信息**
 - 设备: [模拟器、iPhone11 pro max]
 - iOS 版本: [iOS 13.5]
 - Xcode 版本: [Xcode 11.5]
 - QMUI 版本: 'QMUIKit','4.1.3'

**Comment by MoLice** [comment]
QMUICommonViewController 对 titleView 颜色的控制源码可以查看 [UINavigationController+NavigationBarTransition.m:372-385 ](https://github.com/Tencent/QMUI_iOS/blob/master/QMUIKit/QMUIComponents/NavigationBarTransition/UINavigationController%2BNavigationBarTransition.m#L372-L385)。

这里有几种方式可以控制，设计功能时，优先级的预期是：
1. 由 vc 实现 `titleViewTintColor` 来控制颜色。
2. 使用配置表并通过 `NavBarTitleColor` 来控制颜色。
3. 不修改，由 tintColor 指定，而由于 `QMUINavigationTitleView` 默认 `tintColor` 为 nil，所以它会使用 `UINavigationBar` 的 `tintColor` 去展示内容，也即系统默认的蓝色。

如果你命中了第3种，同时也不希望按照前两种方案来控制颜色，那么你可以选择将 `QMUINavigationTitleView.appearance.adjustsSubviewsTintColorAutomatically` 置为 `NO` 来取消 `tintColor` 的控制效果。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
