### ISSUE TITLE
扫描官网demo下载二维码跳转到appstore提示“在当前地区没有销售”

### ISSUE THREAD

**Issue by BackWorld** [Tencent/QMUI_iOS#1035]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
在 QMUI Demo 的 GitHub README 里有相关说明：
![image](https://user-images.githubusercontent.com/1190261/86097434-3c4b4900-bae7-11ea-9e4f-afc00c5d3f96.png)

官网的二维码近期会去掉。

**Comment by BackWorld** [comment]
那从哪里下载安装包呢？

**Comment by MoLice** [comment]
截图里已经说明了没有提供下载啊，自己 clone 代码跑起来。

**Comment by BackWorld** [comment]
github截图加载失败[再见]

**Comment by MoLice** [comment]
> github截图加载失败[再见]

可能是你的网络问题，其他人查看是正常的。

**Comment by BackWorld** [comment]
好的，看到了
