### ISSUE TITLE
QMUIToastContentView类中detailTextLabelText属性的setter方法没有setNeedsLayout

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1037]
**Bug 表现**
QMUIToastContentView类中detailTextLabelText属性的setter方法没有setNeedsLayout, 导致动态设置detailTextLabel会出现显示问题

**截图**
无需截图

**如何重现**
动态设置detailTextLabel即可重现

**预期的表现**
添加上setNeedsLayout即可

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.1.3]

**Comment by jiasongs** [comment]
<img width="587" alt="图片" src="https://user-images.githubusercontent.com/22904757/86195117-c85e7e80-bb82-11ea-9bb1-87ef715b8534.png">
最好能够加上`[self.superview setNeedsLayout];`, 因为text变动往往会引起QMUIToastView的Size变动

**Comment by MoLice** [comment]
已发布 [4.2.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.0) 修复该问题。
