### ISSUE TITLE
建议方法交换之类的会影响全局的东西，默认不要开启，并按需加载

### ISSUE THREAD

**Issue by WHDevLab** [Tencent/QMUI_iOS#1040]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。

**Comment by MoLice** [comment]
> 现存问题或期望目标
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。

Suggest 类型的 issue 请按照模板里的提示写清楚缘由，不然无法讨论。补充完整后 reopen 即可。
