### ISSUE TITLE
导航栏的相关设置有些情况下会被配置表的设置覆盖

### ISSUE THREAD

**Issue by DLsunset** [Tencent/QMUI_iOS#1041]
**Bug 表现**
问题的具体描述
例如demo中 QMUINavigationController -> 方便控制界面导航栏样式 中，当切换到暗色或者浅色navBar样式时，如果将app退回后台，再重新打开，navBar的样式就会被配置表中的设置重置。
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
按照问题描述中即可重现

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.5]
 - Xcode 版本: [Xcode 11.5]
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
与 #839 重复。
