### ISSUE TITLE
QMUIModalPresentationViewController调 hideWithAnimated 不能隐藏

### ISSUE THREAD

**Issue by zp18862956943** [Tencent/QMUI_iOS#1043]
**Bug 表现**
showWithAnimated 动画为YES的时候，如果此时外界原因需要立即关闭弹窗。比如接口返回错误 （网络断开的情况 ，速度很快）此时调hideWithAnimated方法，可是 被 visible 字段 return掉了，方法无法继续执行 。
visible  在 viewWillAppear 和 viewWillDisappear 赋值 ，然而因为此时 还未 走 viewWillAppear ，先走了 hideWithAnimated 导致无法关闭

 - QMUI 版本: [4.1.3]

**Comment by MoLice** [comment]
重复 issue #983

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
