### ISSUE TITLE
搜狗输入法键盘偶尔卡主线程

### ISSUE THREAD

**Issue by sensencoder** [Tencent/QMUI_iOS#1045]
**Bug 表现**
搜狗输入法下偶尔卡主线程
-[UIWindow traitCollection] must be used from main thread only
**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14]
 - Xcode 版本: [Xcode 11.5]
 - QMUI 版本: [4.1.3]

**Comment by mengxinyizhui** [comment]
不一定是是如法的原因，可能是iOS14的bug,是个输入法就不行

**Comment by qcasxy** [comment]
系统键盘也一样

**Comment by qcasxy** [comment]
问题依然存在
![image](https://user-images.githubusercontent.com/14816550/89632692-2d6d6880-d8d5-11ea-8eca-7c855ce43952.png)

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 优化该问题。
