### ISSUE TITLE
导航标题切换主题后，颜色不会立马生效，需要切换页面后才生效

### ISSUE THREAD

**Issue by DeadAndLife** [Tencent/QMUI_iOS#1047]
QMUI 已经提供了**详尽的注释文档**，以及**完整的示例项目 [QMUI Demo](https://github.com/QMUI/QMUI_iOS_Demo)**，当你遇到某些功能不知道怎么使用，或者想知道 QMUI 是否有提供某些功能时，请先查看注释文档或者 Demo，找不到了再提 issue。若提的 issue 已有明确注释或示例的，**可能会被直接关闭或得不到及时的回复**，请知悉。

我在demo上也尝试修改了QMUIConfigurationTemplateDark的navBarTitleColor颜色。但是发现从系统中切换深色模式后，demo中其他颜色均正常切换，只有导航标题不变，但是切换一个界面或者退出界面等操作后正常，请问是我使用方法有问题还是这里存在bug

**Comment by MoLice** [comment]
建议在 Default 配置表里给 `NavBarTitleColor` 设置一个 QMUIThemeColor 动态颜色，在 block 里区分不同的主题用不同色值，而不是在 Default 里设置一个固定值颜色，再在 Dark 里设置另一个固定值颜色。
