### ISSUE TITLE
QMUIButton 以 Autolayout 方式布局时可能出现文字布局错误

### ISSUE THREAD

**Issue by iBinbro** [Tencent/QMUI_iOS#1051]
**Bug 表现**
QMUIButton使用自动布局时，在有设置图片的情况下，额外添加一层view作为button的父视图会导致titleframe计算错误，从而无法显示完整的文字,现在临时解决方案就是每次在给button设置title后手动调用一次```[sender sizeToFit];```

**截图**
![WeChat6ec6b42f73f41730cd822b81fbfeed44](https://user-images.githubusercontent.com/15324447/87751520-c35f2780-c830-11ea-8275-8eb156066a0c.png)
![WeChat87f5acb7d4c06197040260777cde194a](https://user-images.githubusercontent.com/15324447/87751527-c4905480-c830-11ea-858c-c289b030b89e.png)

**如何重现**
附上代码：
```
- (void)viewDidLoad {
    [super viewDidLoad];    
    self.view.backgroundColor = [UIColor redColor];
    
    UIView *binContentView = [[UIView alloc] init];
    binContentView.backgroundColor = [UIColor whiteColor];
    [self.view addSubview:binContentView];
    [binContentView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.offset(100);
        make.left.offset(10);
        make.right.equalTo(self.view);
        make.height.equalTo(@100);
    }];
    
    QMUIButton *_skuBtn = [[QMUIButton alloc] init];
    _skuBtn.backgroundColor = [UIColor yellowColor];
    
    [_skuBtn setImage:[UIImage qmui_imageWithColor:[UIColor greenColor]] forState:UIControlStateNormal];
    
    [binContentView addSubview:_skuBtn];
    
    [_skuBtn mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(binContentView);
        make.right.lessThanOrEqualTo(binContentView);
        make.top.equalTo(binContentView.mas_top).offset(6);
    }];
    
    [_skuBtn setTitle:@"笑脸印花 M码" forState:UIControlStateNormal];
    [_skuBtn addTarget:self action:@selector(btnClick:) forControlEvents:UIControlEventTouchUpInside];
}

- (void)btnClick:(QMUIButton *)sender{
    [sender setTitle:@"服不服表情包印花 Max码 o(￣▽￣)ｄ" forState:UIControlStateNormal];
}
```

**预期的表现**
![WeChatfe1f5e02751eaeb3deaa1656df0c3960](https://user-images.githubusercontent.com/15324447/87751537-c9ed9f00-c830-11ea-9013-7548ca3119f2.png)

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
这里先解释这个问题的直接原因。
按照 issue 里提供的示例代码，关键有这几处：
1. 使用 QMUIButton。
2. QMUIButton 被放在一个 UIView 容器上。
3. QMUIButton 使用 Autolayout 布局。
4. 在某些时机 QMUIButton 的文字长度发生变化。

只要按照以上步骤操作，就会出现 issue 描述的现象。经过 debug 发现问题关键在于 `QMUIButton` 重写了 `layoutSubviews`，在 `layoutSubviews` 内访问了 `self.imageView`，而访问 `self.imageView` 又会触发 layout。以上面的场景为例：
1. 在上文第4步，button 内容发生变化，于是触发 layoutSubviews，此时 button 还是短文字时的 size。
2. 在 QMUIButton layoutSubviews 开头用一些 CGRect 变量保存了 subviews（例如 self.titleLabel）的 frame，这些 frame 的值还是基于短文字 size 下计算出来的值。
3. layout 过程中访问了 `self.imageView`，触发了新的 layout。
4. 此时 button 更新为长文字的 size。
5. 新 layout 里根据新的长文字的 size 计算了新的、正确的 subview frame，并设置给 subviews。
6. 新 layout 执行结束后，回到旧 layout，继续刚刚被打断的逻辑，注意此时的上下文里，第2步那些 CGRect 变量记录的值仍然是旧的短文本 size 下的值。
7. 这些旧值的 CGRect 最终被设置给 subviews，导致新 layout 里计算正确的 frame 又被覆盖了。
8. 于是表现出 issue 描述的现象。

根据这个原理，以下测试项目是能重现 bug 的最小代码，不含 QMUIKit：
[TestPod.zip](https://github.com/Tencent/QMUI_iOS/files/4988861/TestPod.zip)

![image](https://user-images.githubusercontent.com/1190261/88679820-6b72cb80-d122-11ea-9bfe-949d83b8cde2.png)

这个问题下个版本会修复。

**Comment by MoLice** [comment]
已发布 [4.2.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.0) 修复该问题。
