### ISSUE TITLE
ios13.6加入导航控制器就崩溃

### ISSUE THREAD

**Issue by coderDeviCheng** [Tencent/QMUI_iOS#1054]
**Bug 表现**
在SceneDelegate中初始化widow 
    UIWindowScene *windowScene = (UIWindowScene *)scene;
    self.window = [[UIWindow alloc] initWithWindowScene:windowScene];
设置根控制器
    YQLLoginAndRegistViewController *login = [[YQLLoginAndRegistViewController alloc]init];
    UINavigationController *naivLogin = [[UINavigationController alloc]initWithRootViewController:login];
    self.window.rootViewController = naivLogin;
当根控制器为导航控制器UINavigationController时必定崩溃 为UIViewController时正常
模拟器环境 
崩溃信息为：
 Assertion failure in -[_UINavigationBarContentView setDirectionalLayoutMargins:], /Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3920.31.102/_UINavigationBarContentView.m:658
2020-07-20 18:39:25.940628+0800 YueQiLai[14949:371977] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Client error attempting to change layout margins of a private view'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e3dbe8 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff258d6bd2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff4898e35f -[_UINavigationBarContentView setDirectionalLayoutMargins:] + 203
	5   YueQiLai                            0x0000000100915c3c __45+[UINavigationBar(QMUINavigationButton) load]_block_invoke_6 + 380
	6   YueQiLai                            0x00000001009167dd __ExtendImplementationOfVoidMethodWithoutArguments_block_invoke_2 + 157
	7   YueQiLai                            0x000000010091abe4 -[UINavigationBar(TitleView) titleView_navigationBarLayoutSubviews] + 1700
	8   UIKitCore                           0x00007fff4982d5f4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
	9   YueQiLai                            0x000000010084ca32 -[UIView(QMUI_CornerRadius) QMUICornerRadius_layoutSublayersOfLayer:] + 66
	10  YueQiLai                            0x00000001009a2152 -[UIView(QMUI_Border) QMUIBorder_layoutSublayersOfLayer:] + 66
	11  UIKitCore                           0x00007fff4895dcf1 -[UINavigationBar layoutSublayersOfLayer:] + 248
	12  QuartzCore                          0x00007fff2b4e9260 -[CALayer layoutSublayers] + 255
	13  QuartzCore                          0x00007fff2b4ef3eb _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 523
	14  UIKitCore                           0x00007fff49818674 -[UIView(Hierarchy) layoutBelowIfNeeded] + 573
	15  UIKitCore                           0x00007fff48bccc85 -[UINavigationController _positionNavigationBarHidden:edge:initialOffset:] + 880
	16  UIKitCore                           0x00007fff48bccf0f -[UINavigationController _positionNavigationBarHidden:edge:] + 394
	17  UIKitCore                           0x00007fff48bd7480 -[UINavigationController _updateBarsForCurrentInterfaceOrientationAndForceBarLayout:] + 145
	18  UIKitCore                           0x00007fff48c8220c -[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:] + 218
	19  UIKitCore                           0x00007fff48bd43da -[UINavigationController viewDidMoveToWindow:shouldAppearOrDisappear:] + 69
	20  UIKitCore                           0x00007fff49823c1a -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1410
	21  UIKitCore                           0x00007fff49823968 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 720
	22  UIKitCore                           0x00007fff49817295 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 130
	23  UIKitCore                           0x00007fff4981719a -[UIView(Hierarchy) _postMovedFromSuperview:] + 800
	24  UIKitCore                           0x00007fff49826730 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1718
	25  YueQiLai                            0x00000001009a07c6 -[UIView(QMUI) qmuiview_addSubview:] + 406
	26  UIKitCore                           0x00007fff48ca15a1 -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 3682
	27  UIKitCore                           0x00007fff48ca93e2 ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 59
	28  UIKitCore                           0x00007fff48dcbf53 +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] + 99
	29  UIKitCore                           0x00007fff48ca9371 ___UIViewControllerTransitioningRunCustomTransition_block_invoke.645 + 180
	30  UIKitCore                           0x00007fff4981f37f +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 175
	31  UIKitCore                           0x00007fff48ca91f7 _UIViewControllerTransitioningRunCustomTransition + 553
	32  UIKitCore                           0x00007fff48b8ba83 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.465 + 2598
	33  UIKitCore                           0x00007fff48b91435 +[UIPresentationController _scheduleTransition:] + 79
	34  UIKitCore                           0x00007fff48b8adf2 -[UIPresentationController runTransitionForCurrentState] + 1702
	35  UIKitCore                           0x00007fff48b87f24 -[UIPresentationController _presentWithAnimationController:interactionController:target:didEndSelector:] + 1033
	36  UIKitCore                           0x00007fff4935e3ce -[UIWindow addRootViewControllerViewIfPossible] + 571
	37  UIKitCore                           0x00007fff4935d902 -[UIWindow _updateLayerOrderingAndSetLayerHidden:actionBlock:] + 219
	38  UIKitCore                           0x00007fff4935e98d -[UIWindow _setHidden:forced:] + 362
	39  UIKitCore                           0x00007fff49371dc9 -[UIWindow _mainQueue_makeKeyAndVisible] + 42
	40  YueQiLai                            0x00000001007daf6d -[SceneDelegate JL_SetUpMainVc] + 269
	41  YueQiLai                            0x00000001007dacc5 -[SceneDelegate scene:willConnectToSession:options:] + 213
	42  UIKitCore                           0x00007fff48881c0b +[UIScene _sceneForFBSScene:create:withSession:connectionOptions:] + 1304
	43  UIKitCore                           0x00007fff49321ca9 -[UIApplication _connectUISceneFromFBSScene:transitionContext:] + 1019
	44  UIKitCore                           0x00007fff49321fe0 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 291
	45  UIKitCore                           0x00007fff48e747bc -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	46  FrontBoardServices                  0x00007fff36d37d2e -[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 419
	47  FrontBoardServices                  0x00007fff36d5ddc1 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
	48  FrontBoardServices                  0x00007fff36d42757 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
	49  FrontBoardServices                  0x00007fff36d5da52 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
	50  libdispatch.dylib                   0x000000010108ee8e _dispatch_client_callout + 8
	51  libdispatch.dylib                   0x0000000101091da2 _dispatch_block_invoke_direct + 300
	52  FrontBoardServices                  0x00007fff36d836e9 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	53  FrontBoardServices                  0x00007fff36d833d7 -[FBSSerialQueue _queue_performNextIfPossible] + 441
	54  FrontBoardServices                  0x00007fff36d838e6 -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	55  CoreFoundation                      0x00007fff23da1c91 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	56  CoreFoundation                      0x00007fff23da1bbc __CFRunLoopDoSource0 + 76
	57  CoreFoundation                      0x00007fff23da13ec __CFRunLoopDoSources0 + 268
	58  CoreFoundation                      0x00007fff23d9bf8e __CFRunLoopRun + 974
	59  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	60  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	61  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	62  YueQiLai                            0x00000001007da452 main + 114
	63  libdyld.dylib                       0x00007fff520ce1fd start + 1
	64  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by MoLice** [comment]
请先根据你已有的信息查看是否有 issue，例如 #628 。

![image](https://user-images.githubusercontent.com/1190261/87929876-b7d26180-cab9-11ea-9b81-423cca870a2f.png)

![image](https://user-images.githubusercontent.com/1190261/87929771-878ac300-cab9-11ea-8fde-63a57f928d76.png)
