### ISSUE TITLE
QMUI自身的convert调用造成提示警告信息

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#1060]
![Snip20200726_3](https://user-images.githubusercontent.com/3716286/88473321-e8e5e280-cf4e-11ea-8622-a1ccae2e3c46.png)
![Snip20200726_4](https://user-images.githubusercontent.com/3716286/88473322-eb483c80-cf4e-11ea-84f8-509eb1543332.png)

**Comment by MoLice** [comment]
这个需要描述一下此时正在进行什么操作，例如正在切换界面？手势返回？当时的 viewController 层级结构又是怎样的。然后才能界定此时的警告是否有必要。

**Comment by MoLice** [comment]
近期将会发版本，如果希望该问题得到解决，建议尽早补充信息，或者提供可复现的代码片段、Demo 项目后重新打开 issue。
