### ISSUE TITLE
请将Photos的framework引用移动到相关的子模块中

### ISSUE THREAD

**Issue by jjyy1008** [Tencent/QMUI_iOS#1061]
我的项目中引用了QMUIKit基础的子模块QMUICore，但并没有用户相册的添加或查看功能，但被苹果拒绝要求添加使用相册的描述，问题是我就根本引用这些功能，排查到最后我认为是QMUI引用的Photos.framework导致的。
`s.frameworks  =  'Foundation', 'UIKit', 'CoreGraphics', 'Photos'`
能否将Photos的引用放到相应的子模块中呢

**Comment by MoLice** [comment]
确实不合理，下个版本会修复这个问题。

**Comment by MoLice** [comment]
已发布 [4.2.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.0) 修复该问题。
