### ISSUE TITLE
QMUIPieProgressView 绘制环形时报警告 CGContextClosePath: no current point.

### ISSUE THREAD

**Issue by fabcz** [Tencent/QMUI_iOS#1065]
- 复现步骤：

    在 QMUIDemo 中 QDPieProgressViewController 初始化 progressView1 时改一下 shape 为环形
`    
self.progressView1.shape = QMUIPieProgressViewShapeRing;
self.progressView1.lineWidth = 6.f;`

- 出现警告：

    跑起来后进入界面控制台会出现警告
`[Unknown process name] CGContextClosePath: no current point.`

- 猜测原因：

    绘制环形的源码如下：
`            // 绘制环形进度区域
            
            radius -= self.lineWidth;
            CGContextSetLineWidth(context, self.lineWidth);
            CGContextSetStrokeColorWithColor(context, self.strokeColor.CGColor);
            CGContextAddArc(context, center.x, center.y, radius, startAngle, endAngle, 0);
            CGContextStrokePath(context);
            CGContextClosePath(context);`
    执行 CGContextStrokePath 后会将当前点置空，导致后续 CGContextClosePath 没有可用点了
类似会置空点的方法还有绘制扇形的源码中的 CGContextFillPath，但上面绘制扇形时将 CGContextClosePath 放在了 CGContextFillPath 前面，因此就不会有警告了
- 解决方案：
    绘制环形最后无需执行 CGContextClosePath 也能实现对应的效果，因此删掉 CGContextClosePath 即可

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
