### ISSUE TITLE
导入QMUI后，tabbar title字体大小自动变化，位置也向下偏移了

### ISSUE THREAD

**Issue by dulifu** [Tencent/QMUI_iOS#1067]

**Comment by MoLice** [comment]
有没有使用配置表？

**Comment by dulifu** [comment]
> 有没有使用配置表？

首先是直接cocoaPod导入项目，然后就发现tabbar title异常了，然后我试着导入配置表，配置了发现还是不行  
 QMUICMI.tabBarItemTitleFont = UIFontMake(15);  然后我搜索tabbar相关的类，全部干掉了还是不行，我不想做太多的全局配置工作，只是想使用里面几个控件,有没有什么办法直接把这个tabbar的配置干掉呢，影响有点大

**Comment by MoLice** [comment]
不使用配置表是不会影响业务项目原本的 tabBar 样式的。业务项目原本是怎样去设置 tabBarItem font？请贴出相关代码或者提供一份 Demo，包括设置的方式和时机。

**Comment by dulifu** [comment]
> 不使用配置表是不会影响业务项目原本的 tabBar 样式的。业务项目原本是怎样去设置 tabBarItem font？请贴出相关代码或者提供一份 Demo，包括设置的方式和时机。

//MARK: -初始化根控制器
    func initRootViewController() {
        let tabbarController = DBTabBarController()
        window?.rootViewController = tabbarController
    }
具体的DBTabBarController内部代码见附件,这个真的是pod QMUI后tabbar就自动变化了，我代码写的18号，但是一导入cocoapod就变成了很小的字体，没有增加配置表文件QMUIConfigurationTemplate的
<img width="1100" alt="F525ED6B-E9E6-453B-9EA6-FD9D254A344A" src="https://user-images.githubusercontent.com/17981102/89247219-72786d00-d63f-11ea-9a48-15a579095262.png">

**Comment by MoLice** [comment]
猜测也是 https://github.com/Tencent/QMUI_iOS/issues/840#issuecomment-560267141 这个系统限制，需要区分 iOS 13 和非 iOS 13 不同设置方式。

以下是 QMUI Demo 把配置表去除后修改 tabBarItem 样式的代码和效果截图。
<img src="https://user-images.githubusercontent.com/1190261/89270194-95217a80-d66d-11ea-82c9-91b72fe4297d.png" width="640" />

<img src="https://user-images.githubusercontent.com/1190261/89270204-9a7ec500-d66d-11ea-9700-76ec59c66c68.png" width="320" />

**Comment by dulifu** [comment]
@MoLice 可以啦，谢谢
