### ISSUE TITLE
ios13.5 swift项目 使用配置表 不能改变tabBarItemTitleColorSelected和tabBarItemTitleColor的颜色

### ISSUE THREAD

**Issue by coderDeviCheng** [Tencent/QMUI_iOS#1068]
swift项目，原来是通过这样设置的         `discoverNavi.tabBarItem.setTitleTextAttributes([NSAttributedString.Key.foregroundColor:RGB0X(hexValue: 0x2ca572),NSAttributedString.Key.font:10], for: .highlighted)       discoverNavi.tabBarItem.setTitleTextAttributes([NSAttributedString.Key.foregroundColor:RGB0X(hexValue: 0xaaaaaa)], for: .normal)`
导入QMUI之后 这样设置没有效果，在配置表中配置了`QMUICMI.tabBarItemTitleColorSelected = UIColorMake(44, 165, 144);QMUICMI.tabBarItemTitleColor = UIColor.redColor;  `    依然无效，打断点配置表是执行了这段代码的
![1596512542365](https://user-images.githubusercontent.com/34669007/89250567-9f308280-d647-11ea-81e0-d949be89e259.jpg)

**Comment by MoLice** [comment]
这里有两个问题，两个问题都与 Swift/OC 无关。

一个是你原本的设置方式用的是 iOS 12 及以前的方式，而引入 QMUI 后，应该在 iOS 13 用新接口，iOS 12 及以前才用旧接口，否则会发现 iOS 12 及以前没问题，但 iOS 13 及以后都无效。详细情况可以从 https://github.com/Tencent/QMUI_iOS/issues/840#issuecomment-560267141 了解。
<img src="https://user-images.githubusercontent.com/1190261/89265690-702a0900-d667-11ea-86bc-26db05ec3af1.png" width="640" />
<img src="https://user-images.githubusercontent.com/1190261/89265718-7c15cb00-d667-11ea-9794-355a91165050.png" width="320" />
这是系统的限制，没办法，你可以自行封装一层以减少代码量。

第二个问题，无法重现，请提供 Demo 以供测试。注意既然用配置表控制 tabBar 样式了，就应该把业务自己修改 UITabBarItem 样式的代码去掉，否则会以业务代码为准，配置表优先级是最低的。
<img src="https://user-images.githubusercontent.com/1190261/89266007-f1819b80-d667-11ea-855a-811e8a25477d.png" width="640" />

**Comment by coderDeviCheng** [comment]
找到问题了，我设置了tintcolor，导致配置表里面没有生效
`self.tabBar.tintColor = UIColor.black` 去掉这段代码就正常了
谢谢
