### ISSUE TITLE
UIImageView(QMUI).qmui_smoothAnimation = YES 时修改 contentMode 无效

### ISSUE THREAD

**Issue by xiaopindev** [Tencent/QMUI_iOS#1071]
**Bug 表现**
在没有集成QMUIKit之前，我的UI界面图片显示正常，集成以后，图片设置的Fit模式无效，图片被拉伸了

ConnectionViewCell 是 xib写的，图片是Kingfisher的 AnimatedImageView 对象，加载的是gif动图

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
集成前：
![IMG_6139](https://user-images.githubusercontent.com/2084285/89706537-2b6cdd80-d999-11ea-94c0-422a0c03c3c1.PNG)

集成后：
![IMG_6138](https://user-images.githubusercontent.com/2084285/89706545-3fb0da80-d999-11ea-9fc0-0304a0ac6775.PNG)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 13.5]
 - Xcode 版本: [Xcode 11.6]
 - QMUI 版本: [4.2.0]

**Comment by MoLice** [comment]
下个版本会修复，在此之前你可以将那些 UIImageView 的 `qmui_smoothAnimation` 属性改为 `NO`。

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
