### ISSUE TITLE
Navbar颜色在不和主题navbar颜色一致页面bug

### ISSUE THREAD

**Issue by Libogold** [Tencent/QMUI_iOS#1075]
**Bug 表现**
使用demo
1 进入QMUINavigationController.   (QMUIKit 首页)
2选择  cell 2 （方便控制界面导航栏样式）
3选择cell  1或2（暗色navBar样式 或 浅色navBar样式）
4锁屏，再开屏。
观察navBar颜色变了
**预期的表现**
预期颜色应该不变0.0

**Comment by MoLice** [comment]
重复 issue #839
