### ISSUE TITLE
您好，主题只能先新建配置表类吗？是否可以通过后台网络请求返回的一个颜色值去动态修改主题色？

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#1076]
您好，主题只能先新建配置表类吗？是否可以通过后台网络请求返回的一个颜色值去动态修改主题色？

**Comment by MoLice** [comment]
主题和配置表是两个独立的功能。
主题里的动态色，是可以网络请求拿到色表后再应用的。
