### ISSUE TITLE
window不存在引起的crash

### ISSUE THREAD

**Issue by devYoungyang** [Tencent/QMUI_iOS#1077]
**Bug 表现**
通过cocoapods安装了QMUIKit，引起的crash

**截图**
![image](https://user-images.githubusercontent.com/17973681/90710266-98a13c80-e2d0-11ea-8e8c-79541a629a03.png)

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.6]
 - Xcode 版本: [Xcode 11.6]
 - QMUI 版本: [4.1.3]

**Comment by MoLice** [comment]
QMUI 暂不兼容 UIWindowScene，使用 `UIWindowScene` 的项目不建议使用 QMUI。后续会支持，请关注 [Release](https://github.com/Tencent/QMUI_iOS/releases) 进展。
