### ISSUE TITLE
友盟统计Crash统计记录 NSException (QMUI_KVC) load 方法  有偶发闪退现象。

### ISSUE THREAD

**Issue by BzHuang** [Tencent/QMUI_iOS#1078]
**Bug 表现**
线上App，友盟统计Crash统计 NSException (QMUI_KVC) load 方法  有偶发闪退现象。

**截图**

Application received signal SIGABRT
(null)
((
	0   CoreFoundation                      0x00000001aab3aa5c 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 1227356
	1   libobjc.A.dylib                     0x00000001aa861fa4 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001aaa301c0 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 135616
	**3  LineTalk!__29+[NSException(QMUI_KVC) load]_block_invoke_3 [NSObject+QMUI.m : 0]
	4  LineTalk!UmengSignalHandler**
	5   libsystem_platform.dylib            0x00000001aa848884 F77366E7-EF17-3E34-A4BA-F938756212C2 + 34948
	6   libsystem_pthread.dylib             0x00000001aa851724 1FF7A2FB-9F28-37B7-AF39-344206A322BD + 26404
	7   libsystem_c.dylib                   0x00000001aa7a1844 abort + 100
	8   libc++abi.dylib                     0x00000001aa8fa7d4 __cxa_bad_cast + 0
	9   libc++abi.dylib                     0x00000001aa907324 295D93E6-AC06-384A-A469-2DF327F697FC + 58148
	10  libc++abi.dylib                     0x00000001aa906c58 __cxa_get_exception_ptr + 0
	11  libc++abi.dylib                     0x00000001aa906c18 295D93E6-AC06-384A-A469-2DF327F697FC + 56344
	12  libobjc.A.dylib                     0x00000001aa8620d0 A697479D-4C5C-391E-B117-85B894AB94C6 + 24784
	13  CoreFoundation                      0x00000001aaa301c0 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 135616
	14 LineTalk!__29+[NSException(QMUI_KVC) load]_block_invoke_3 [NSObject+QMUI.m : 0]
	15  WebKit                              0x00000001b221c2c0 CC6D4AA0-0E70-3D8D-A0A0-BAC8A1D6682C + 1372864
	16  WebKit                              0x00000001b229b69c CC6D4AA0-0E70-3D8D-A0A0-BAC8A1D6682C + 1894044
	17  WebKit                              0x00000001b22fcafc CC6D4AA0-0E70-3D8D-A0A0-BAC8A1D6682C + 2292476
	18  libsystem_blocks.dylib              0x00000001aa72da48 _Block_release + 152
	19  libsystem_blocks.dylib              0x00000001aa72da48 _Block_release + 152
	20  UIKitCore                           0x00000001ae213038 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 352312
	21  UIKitCore                           0x00000001ae2111cc D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 344524
	22  libobjc.A.dylib                     0x00000001aa87d6d0 A697479D-4C5C-391E-B117-85B894AB94C6 + 136912
	23  libobjc.A.dylib                     0x00000001aa87d5c8 objc_autoreleasePoolPop + 224
	24  JavaScriptCore                      0x00000001b98579f4 _ZN3WTF15AutodrainedPoolD1Ev + 24
	25  JavaScriptCore                      0x00000001b9883cc4 C87FA51E-B103-3902-A963-FAAEDB228C86 + 224452
	26  CoreFoundation                      0x00000001aaab8a00 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 694784
	27  CoreFoundation                      0x00000001aaab8958 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 694616
	28  CoreFoundation                      0x00000001aaab80f0 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 692464
	29  CoreFoundation                      0x00000001aaab323c 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 672316
	30  CoreFoundation                      0x00000001aaab2adc CFRunLoopRunSpecific + 464
	31  GraphicsServices                    0x00000001b4a53328 GSEventRunModal + 104
	32  UIKitCore                           0x00000001aebc063c UIApplicationMain + 1936
	**33 LineTalk!main [main.m : 14]**
	34  libdyld.dylib                       0x00000001aa93c360 7B531A15-3E73-3185-90E2-B88D9476DA5E + 4960
)

dSYM UUID: CFF5ABA9-B8B2-3D6A-8764-DC2D162B9B84
CPU Type: arm64
Slide Address: 0x0000000100000000
**Binary Image: LineTalk**
Base Address: 0x0000000104324000

**如何重现**
已上线App，崩溃日志发现，偶发现象，无法必定重现

**预期的表现**

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 10-13]
 - Xcode 版本: [Xcode 11.4]
 - QMUI 版本: [4.1.3]

**Comment by liumengdi666** [comment]
你好可以问下怎么解决的吗？

**Comment by xianrenzhuimeng** [comment]
遇见了相同的问题，你是怎么解决的啊
