### ISSUE TITLE
调用相机拍摄照片，会触发非主线程卡顿

### ISSUE THREAD

**Issue by biqinglin** [Tencent/QMUI_iOS#1079]
**Bug 表现**
调用相机拍摄照片，点击“使用照片”后，触发系统回调函数：func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any])，然后就触发QMUI库的两个类，指出它们没有在主线程执行的bug

**截图**
![截屏2020-08-22 上午11 47 34](https://user-images.githubusercontent.com/12489764/90948048-6842d500-e46d-11ea-9650-a76be87ce53f.png)
![截屏2020-08-22 上午11 47 39](https://user-images.githubusercontent.com/12489764/90948051-6aa52f00-e46d-11ea-8a9f-83b25c27b54b.png)
![截屏2020-08-22 上午11 47 46](https://user-images.githubusercontent.com/12489764/90948052-6c6ef280-e46d-11ea-8977-95f8e36f027c.png)
**如何重现**
1. 使用UIImagePickerController进行拍摄照片
2. 点击“使用照片”，即触发

**预期的表现**
卡顿

**其他信息**
 - 设备: iPhone
 - iOS 版本: iOS 13.6
 - Xcode 版本: Xcode 11.6
 - QMUI 版本: 4.2.0

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
