### ISSUE TITLE
[UIWindow(QMUIUserInterfaceStyleWillChangeNotification) load]_block_invoke

### ISSUE THREAD

**Issue by XcodeMinG** [Tencent/QMUI_iOS#1080]
**Bug 表现**
问题的具体描述
Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]
PID: 6005, TID: 89186, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   QMUIKit                             0x000000011232aa00 __62+[UIWindow(QMUIUserInterfaceStyleWillChangeNotification) load]_block_invoke_3 + 96
5   UIKitCore                           0x000000011a508672 +[UIKeyboardCache enabled] + 53
6   UIKitCore                           0x000000011a508996 -[UIKeyboardCache cachedImageForKey:fromLayout:] + 44
7   UIKitCore                           0x000000011a4c72e0 __37-[UIKBKeyplaneView prepareForDisplay]_block_invoke + 273
8   libdispatch.dylib                   0x000000011646b8ac _dispatch_call_block_and_release + 12
9   libdispatch.dylib                   0x000000011646ca88 _dispatch_client_callout + 8
10  libdispatch.dylib                   0x000000011647e792 _dispatch_root_queue_drain + 827
11  libdispatch.dylib                   0x000000011647ef1b _dispatch_worker_thread2 + 135
12  libsystem_pthread.dylib             0x00000001168ac9f7 _pthread_wqthread + 220
13  libsystem_pthread.dylib             0x00000001168abb77 start_wqthread + 15
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

*如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

*
![image](https://user-images.githubusercontent.com/18474293/91118470-a0dbec00-e6c3-11ea-8eb7-927f6fc1a9a0.png)
*其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 优化该问题。
