### ISSUE TITLE
iOS 14 Beta 6 开启 customNavigationBarTransitionKey 的情况下转场效果错误

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#1081]
**Bug 表现**
<img src="https://user-images.githubusercontent.com/1190261/91534158-a21b4c00-e943-11ea-8110-4bfbea2dbf18.png" width="320" />

**预期的表现**
<img src="https://user-images.githubusercontent.com/1190261/91534757-ad22ac00-e944-11ea-9a7e-6a3ce0a9503f.png" width="320" />

**Bug 原因**
<img src="https://user-images.githubusercontent.com/1190261/91534863-dcd1b400-e944-11ea-808f-ad024601cfd8.png" width="600" />
——by tibbers

iOS 14 Beta 6 开始，UINavigationBar 无法直接初始化后使用，必须关联在某个 UINavigationController 里，否则内部的 subviews 不会被创建出来，而 QMUI customNavigationBarTransitionKey 的工作方式就是在转场时把原来的 bar 的背景去除，再创建两条假 bar 模拟前后两个界面的样式，由于这两条假 bar 没有关联的 UINavigationController，所以内部 subviews 为空，所以转场时可以看到整个顶部导航栏的背景都是空的。

暂时的修复方式是重写假 bar 的 `_accessibility_navigationController` 方法，返回原始 bar 的同名方法的值，这样系统就会认为假 bar 存在关联的 UINavigationController，表现就正常了。

**其他信息**
 - 设备: [All]
 - iOS 版本: [iOS 14.0 Beta 6]
 - Xcode 版本: [Xcode 12 Beta 6]
 - QMUI 版本: [4.2.0]

**Comment by GUIYIVIEW-Maybe** [comment]
你好，请问`_accessibility_navigationController`这个代表是哪个方法？

**Comment by Liaoworking** [comment]
> 你好，请问`_accessibility_navigationController`这个代表是哪个方法？

UINavigationBar的一个系统私有方法

**Comment by GUIYIVIEW-Maybe** [comment]
> > 你好，请问`_accessibility_navigationController`这个代表是哪个方法？
> 
> UINavigationBar的一个系统私有方法

感谢！！！

**Comment by ZFBest** [comment]
感恩！

**Comment by MoLice** [comment]
在 4.2.1 发布前，如需要，可将以下方法添加到 `@implementation _QMUITransitionNavigationBar` 里，来修复这个 issue。
```objc
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        // iOS 14 开启 customNavigationBarTransitionKey 的情况下转场效果错误
        // https://github.com/Tencent/QMUI_iOS/issues/1081
        if (@available(iOS 14.0, *)) {
            OverrideImplementation([_QMUITransitionNavigationBar class], NSSelectorFromString([NSString stringWithFormat:@"_%@_%@", @"accessibility", @"navigationController"]), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void)) {
                return ^UINavigationController *(_QMUITransitionNavigationBar *selfObject) {
                    if (selfObject.originalNavigationBar) {
                        BeginIgnorePerformSelectorLeaksWarning
                        return [selfObject.originalNavigationBar performSelector:originCMD];
                        EndIgnorePerformSelectorLeaksWarning
                    }
                    
                    // call super
                    UINavigationController *(*originSelectorIMP)(id, SEL);
                    originSelectorIMP = (UINavigationController *(*)(id, SEL))originalIMPProvider();
                    UINavigationController *result = originSelectorIMP(selfObject, originCMD);
                    return result;
                };
            });
        }
    });
}
```

**Comment by SwiftBMan** [comment]
4.2.0 最好各个版本测试一下，弹一闪😿

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。

**Comment by allen8300** [comment]
> > > 你好，请问`_accessibility_navigationController`这个代表是哪个方法？
> > 
> > 
> > UINavigationBar的一个系统私有方法
> 
> 感谢！！！

请教一下，这个私有方法带上审核安全吗？不会有被拒的风险吗？急急急，辛苦👍

**Comment by Liaoworking** [comment]
> > > > 你好，请问`_accessibility_navigationController`这个代表是哪个方法？
> > > 
> > > 
> > > UINavigationBar的一个系统私有方法
> > 
> > 
> > 感谢！！！
> 
> @MoLice @Liaoworking
> 请教一下，这个私有方法带上审核安全吗？不会有被拒的风险吗？急急急，辛苦👍

我们后来用的其他方法解决的导航栏显示异常的问题， 这个库用的人很多，有问题应该有人会说，勇敢点~
