### ISSUE TITLE
使用配置表设置QMUICMI.tabBarItemTitleColorSelected  在13.6的8上无效 显示的仍是系统的蓝色

### ISSUE THREAD

**Issue by coderDeviCheng** [Tencent/QMUI_iOS#1082]
系统13.6不正常  12.0的系统显示正常  同时 13.6测试的其他机型 如x xsmax正常
![7821598616352_ pic_hd](https://user-images.githubusercontent.com/34669007/91559809-5381a800-e96b-11ea-83ae-011df48cd73c.jpg)

**Comment by MoLice** [comment]
请按规范提交 issue，提 issue 时已经有给模板，补充好 QMUI 版本。

**Comment by coderDeviCheng** [comment]
版本是 4.2.0 找到问题了 我自定义了tabbar    [self setValue:[[NIMyTabbar alloc]init] forKey:@"tabBar"]; 那么问题来了  怎么使用自定义的tabbar的同时修改颜色呢

**Comment by MoLice** [comment]
按系统的方式做，只不过做在你自己的 NIMyTabBar 内。或者用 [NIMyTabBar appearance]。
