### ISSUE TITLE
QMUIMultipleDelegates removeDelegate not work

### ISSUE THREAD

**Issue by lexiaoyao20** [Tencent/QMUI_iOS#1086]
**Bug 表现**
我在qmuidemo 的 `QDAboutViewController` 类中添加了如下代码：

```
@interface QDAboutViewController ()

//其他代码省略..

@property(nonatomic, strong) QMUIMultipleDelegates *delegates;

@end

@implementation QDAboutViewController

- (void)dealloc
{
    [self.delegates removeDelegate:self];
}

- (void)didInitialize {
    [super didInitialize];
    
    [self.delegates addDelegate:self];

    //others...
}

- (QMUIMultipleDelegates *)delegates {
    if (!_delegates) {
        _delegates = [QMUIMultipleDelegates weakDelegates];
    }
    return _delegates;
}

//Ohters...
@end
```

**截图**
<img width="525" alt="97277027-0964-4366-A781-F094CC1B9F01" src="https://user-images.githubusercontent.com/3021017/92377889-706e6600-f137-11ea-85c9-9b11d333fca7.png">

**如何重现**
进入About页面，然后退出Abount页面，在 `removeDelegate` 那里打上断点，实际上并没有进入移除的逻辑。
不知道这算不算是Bug，还是我的写法有问题？

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.2.0]

**Comment by MoLice** [comment]
你创建的是 weakDelegates，所以对 self 的引用是一个 weak 引用，在 dealloc 时这个 weak 引用已经被清空，实际上此时 _delegates 里的 pointer[0] 已经是 nil 了，自然就无法移除任何 pointer（因为此时已经不存在任何 pointer)。
你既然用 weakDelegates 就不需要在 dealloc 里去 remove，这就是 weak 的意义。

**Comment by lexiaoyao20** [comment]
了解了，多谢大佬解答~
