### ISSUE TITLE
cocoapods方式集成的库里面没有UIKitExtensions

### ISSUE THREAD

**Issue by FantasticSkyBaby** [Tencent/QMUI_iOS#1093]
如题，在demo工程中有这个分类，演示界面中也存在相关联代码，使用cocoapods集成4.2.0后没有发现UIKitExtensions相关分类

**Comment by FantasticSkyBaby** [comment]
![image](https://user-images.githubusercontent.com/14800057/92986466-9f952680-f4ed-11ea-8426-7aa284a42409.png)
demo中UITableViewCell+QMUI里有UIEdgeInsets相关设置属性，cocoapods集成的库里没有

**Comment by MoLice** [comment]
先贴出Podfile的写法

**Comment by FantasticSkyBaby** [comment]
source 'https://cdn.cocoapods.org/'

install! 'cocoapods', generate_multiple_pod_projects: true
post_install do |installer|
  installer.pod_target_subprojects.flat_map { |p| p.targets }.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

target "ios" do
  
  inhibit_all_warnings!
  
  platform :ios, '9.0'
  pod 'QMUIKit'
end

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.0
4.2.0 版本说明里第一句话就有说了最低版本到10.0，所以你引入的是旧版，符合预期。
