### ISSUE TITLE
某些场景下 UINavigationController(QMUI).qmui_isPushing 可能遇到数组越界

### ISSUE THREAD

**Issue by JerryDream007** [Tencent/QMUI_iOS#1094]
**Bug 表现**
问题的具体描述
push到某个控制器时，self.childViewControllers发生了数组越界

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/15311758/93062587-bbdcc300-f6a7-11ea-93d7-588b52ec6e74.png)

**如何重现**
1. 将导航栏改成RTRootNavigationController后，就会出现

**预期的表现**
正常情况下，应该正常push

**其他信息**
 - 设备: iPhone 7P
 - iOS 版本: [iOS 13.2.2]
 - Xcode 版本: [Xcode 11.0]
 - QMUI 版本: [4.2.0]

**Comment by MoLice** [comment]
这里 if 内部用 `childViewControllers` 没什么特别含义，应该统一都用 `viewControllers` 来避免这种问题，你可以先本地统一改为 `viewControllers`，新版本将会修复这个问题。

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
