### ISSUE TITLE
QMUINavigationButton的alignmentRectInsets方法会造成循环调用

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1095]
**Bug 表现**
QMUINavigationButton的alignmentRectInsets方法会造成循环调用

**截图**
<img width="388" alt="图片" src="https://user-images.githubusercontent.com/22904757/93285186-dd07f580-f806-11ea-9b9d-15d8a185e109.png">
<img width="1583" alt="图片" src="https://user-images.githubusercontent.com/22904757/93285214-eee99880-f806-11ea-87f5-fcf4c3ffacd8.png">

**如何重现**
1. 使用此方法初始化 `[[QMUINavigationButton alloc]initWithFrame:CGRectMake(0, 0, 22, 22)];` 即可重现
`self.titleLabel`调用时又触发了当前button的`alignmentRectInsets`

**预期的表现**
不会出现循环调用

**其他信息**
 - 设备: 模拟器 13.4.1
 - iOS 版本: iOS 13.4
 - Xcode 版本: Xcode 11.4.1
 - QMUI 版本: 4.2.0

**Comment by MoLice** [comment]
你在 iOS 13.4 下能走到 `alignmentRectInsets`？只有 iOS 10 及以下才可以哦。我在 iOS 10-13 里测试，均未出现 issue 说的死循环，请确认重现的具体条件。

![image](https://user-images.githubusercontent.com/1190261/93608054-c2976d00-f9fc-11ea-8d91-d5c8c3969078.png)

**Comment by jiasongs** [comment]
> 你在 iOS 13.4 下能走到 `alignmentRectInsets`？只有 iOS 10 及以下才可以哦。我在 iOS 10-13 里测试，均未出现 issue 说的死循环，请确认重现的具体条件。
> 
> ![image](https://user-images.githubusercontent.com/1190261/93608054-c2976d00-f9fc-11ea-8d91-d5c8c3969078.png)

奇怪，目前我也复现不了了。我先关闭此issue，等我找到复现的方式再开启
