### ISSUE TITLE
4.2.0   QMUIBadge 当 qmui_badgeInteger 是以1开头两位数未读数，未读数显示可能不是正圆

### ISSUE THREAD

**Issue by ZXCheng** [Tencent/QMUI_iOS#1096]
**现存问题或期望目标**
建议将 UIView+QMUIBadge.m 文件 中方法 - (CGSize)sizeThatFits:(CGSize)size {}  修改为

- (CGSize)sizeThatFits:(CGSize)size {
    CGSize result = [super sizeThatFits:size];
    if (result.width < result.height) {
        result = CGSizeMake(result.height, result.height);
    }
    return result;
}

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/93350654-749f2f80-f86b-11ea-9166-b5ddf6047407.png)
![image](https://user-images.githubusercontent.com/1190261/93350863-a57f6480-f86b-11ea-813e-ca3f54362226.png)

你是说这样？这是符合预期的表现。
这种 issue 请贴截图，否则沟通成本太高，可能不予处理。

**Comment by ZXCheng** [comment]
![截屏2020-09-17 下午12 51 27](https://user-images.githubusercontent.com/17699101/93421764-d780dd00-f8e4-11ea-82a1-0a084d23d0af.png)
![截屏2020-09-17 下午12 51 41](https://user-images.githubusercontent.com/17699101/93421772-dd76be00-f8e4-11ea-9895-49d85c2f0429.png)

view.qmui_badgeContentEdgeInsets = UIEdgeInsets.init(top: 2, left: 4, bottom: 2, right: 4)

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
