### ISSUE TITLE
iOS14中_QMUITransitionNavigationBar 无法正常生效

### ISSUE THREAD

**Issue by xixisplit** [Tencent/QMUI_iOS#1097]
**Bug 表现**
问题的具体描述
在 A->B 的 viewcontroller 中,如果启用自动管理导航条过度动画,在 14 和 14测试版本中.都有这个问题
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
目前 iOS 14 中. _QMUITransitionNavigationBar 的所有子视图全部没有.以下为 lookin 软件中展示出的视图结构和 iOS14手机中的样式
<img width="392" alt="image" src="https://user-images.githubusercontent.com/17351286/93425119-ecad3a00-f8eb-11ea-8ad3-23367d4386ee.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/17351286/93425132-f040c100-f8eb-11ea-87db-67feac11cb26.png">

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，过度动画应该是以下
<img width="398" alt="image" src="https://user-images.githubusercontent.com/17351286/93424954-b079d980-f8eb-11ea-9547-03ffa605e7ba.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/17351286/93424989-bc659b80-f8eb-11ea-99ed-2a0be4c4a4ae.png">

**其他信息**
 - 设备: [iPhone se2]
 - iOS 版本: [iOS 14.0]
 - Xcode 版本: [Xcode 11.6]
 - QMUI 版本: [4.2.0]

**Comment by MoLice** [comment]
#1081
