### ISSUE TITLE
4.2.1版本何时发布呢

### ISSUE THREAD

**Issue by lijiajunios** [Tencent/QMUI_iOS#1098]
ios14 自定义导航栏出现灰色闪动的改动
4.2.1版本何时发布呢

**Comment by Gavin123** [comment]
同问，正式版的的ios14已经发布，现在好多反馈导航栏闪动的bug。

**Comment by SouthSnow** [comment]
> 同问，正式版的的ios14已经发布，现在好多反馈导航栏闪动的bug。

已经剥离出来修复了，暂时本地维护，坐等4.2.1出来

**Comment by lijiajunios** [comment]
能不能先把修改方式发出来，我们先进行手动替换等发布了，在pod更新 这个问题很影响体验啊，本来昨天晚上应该发包的，然后14一正式发布更新，无法上线了

**Comment by lijiajunios** [comment]
> > 同问，正式版的的ios14已经发布，现在好多反馈导航栏闪动的bug。
> 
> 已经剥离出来修复了，暂时本地维护，坐等4.2.1出来

能不能先把修改方式发出来，我们先进行手动替换等发布了，在pod更新 这个问题很影响体验啊，本来昨天晚上应该发包的，然后14一正式发布更新，无法上线了

**Comment by lijiajunios** [comment]
> 同问，正式版的的ios14已经发布，现在好多反馈导航栏闪动的bug。

昨天提包，然后产品更新了系统，果断的死翘翘~：~

**Comment by SouthSnow** [comment]
> > > 同问，正式版的的ios14已经发布，现在好多反馈导航栏闪动的bug。
> > 
> > 
> > 已经剥离出来修复了，暂时本地维护，坐等4.2.1出来
> 
> 能不能先把修改方式发出来，我们先进行手动替换等发布了，在pod更新 这个问题很影响体验啊，本来昨天晚上应该发包的，然后14一正式发布更新，无法上线了



> > > 同问，正式版的的ios14已经发布，现在好多反馈导航栏闪动的bug。
> > 
> > 
> > 已经剥离出来修复了，暂时本地维护，坐等4.2.1出来
> 
> 能不能先把修改方式发出来，我们先进行手动替换等发布了，在pod更新 这个问题很影响体验啊，本来昨天晚上应该发包的，然后14一正式发布更新，无法上线了

![176AA484-3FCD-43A0-A57B-8AED5F5F8183](https://user-images.githubusercontent.com/12111862/93585135-e5b02580-f9d8-11ea-9cc5-38f9382b074e.jpg)
![3FD0438F-4D08-42EF-B6B5-6BD23241000F](https://user-images.githubusercontent.com/12111862/93585141-e8127f80-f9d8-11ea-869c-93e52a2578fa.jpg)
参考这个https://github.com/MoZhouqi/KMNavigationBarTransition

**Comment by SouthSnow** [comment]
> > > > 同问，正式版的的ios14已经发布，现在好多反馈导航栏闪动的bug。
> > > 
> > > 
> > > 已经剥离出来修复了，暂时本地维护，坐等4.2.1出来
> > 
> > 
> > 能不能先把修改方式发出来，我们先进行手动替换等发布了，在pod更新 这个问题很影响体验啊，本来昨天晚上应该发包的，然后14一正式发布更新，无法上线了
> 
> > > > 同问，正式版的的ios14已经发布，现在好多反馈导航栏闪动的bug。
> > > 
> > > 
> > > 已经剥离出来修复了，暂时本地维护，坐等4.2.1出来
> > 
> > 
> > 能不能先把修改方式发出来，我们先进行手动替换等发布了，在pod更新 这个问题很影响体验啊，本来昨天晚上应该发包的，然后14一正式发布更新，无法上线了
> 
> ![176AA484-3FCD-43A0-A57B-8AED5F5F8183](https://user-images.githubusercontent.com/12111862/93585135-e5b02580-f9d8-11ea-9cc5-38f9382b074e.jpg)
> ![3FD0438F-4D08-42EF-B6B5-6BD23241000F](https://user-images.githubusercontent.com/12111862/93585141-e8127f80-f9d8-11ea-869c-93e52a2578fa.jpg)
> 参考这个https://github.com/MoZhouqi/KMNavigationBarTransition

1、引入图二的接个文件，2、修改QMUIKit中的代码，见红框，即可

**Comment by xixisplit** [comment]
如果只是修复这个问题的话.KMNavigationBarTransition 中 目前是给 nav 的 items 赋值了 item
    if (@available(iOS 14, *)) {
        customBar.items = @[[UINavigationItem new]]; // fix Apple's bug in iOS 14
    }
在customBar 初始化之后.加上这句就可以了,目前试了一下.貌似没问题.

**Comment by MoLice** [comment]
如果需要优先修复导航栏的问题，请参考 https://github.com/Tencent/QMUI_iOS/issues/1081#issuecomment-694881636 的方式，在本地先行修复，本 issue 不再跟踪导航栏问题。

**Comment by lijiajunios** [comment]
> 如果需要优先修复导航栏的问题，请参考 [#1081 (comment)](https://github.com/Tencent/QMUI_iOS/issues/1081#issuecomment-694881636) 的方式，在本地先行修复，本 issue 不再跟踪导航栏问题。

说的所有解决方案都不行
1、addTransitionNavigationBarIfNeeded  这个有些方法不知哪来的 km_fakecontroller
2、load添加后不加载

**Comment by Gavin123** [comment]
> > 如果需要优先修复导航栏的问题，请参考 [#1081 (comment)](https://github.com/Tencent/QMUI_iOS/issues/1081#issuecomment-694881636) 的方式，在本地先行修复，本 issue 不再跟踪导航栏问题。
> 
> 说的所有解决方案都不行
> 1、addTransitionNavigationBarIfNeeded 这个有些方法不知哪来的 km_fakecontroller
> 2、load添加后不加载

参考 #1081 (comment) 是有效的。  你看看你代码是不是copy错了。

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 。
