### ISSUE TITLE
iOS14

### ISSUE THREAD

**Issue by Y-HLiang** [Tencent/QMUI_iOS#1099]
iOS14选择照片搜索框背景透明，希望能告知如何调整

**Comment by MoLice** [comment]
这个问题…应该没人看得懂是什么意思吧

**Comment by Y-HLiang** [comment]
没事了，我的模板（QMUIConfigurationTemplate）本太老了，更新了一下。原来的是修改searchBar的背景颜色，现在是设置图片了searchBarTextFieldBackgroundImage。没有设置就会背景透明。还在加班吗？哈哈哈。。。
