### ISSUE TITLE
[UIKit Bug] iOS 14 pop 到一个 hidesBottomBarWhenPushed = NO 的界面后 UITabBar 无法正确显示出来

### ISSUE THREAD

**Issue by Y-HLiang** [Tencent/QMUI_iOS#1100]
iOS 14，考虑以下的 viewController 结构：
```
UITabBarController
|- UINavigationController
    |- UIViewController1.hidesBottomBarWhenPushed = NO
    |- UIViewController2.hidesBottomBarWhenPushed = YES
    |- UIViewController3.hidesBottomBarWhenPushed = YES
    |- ...
```
当从 UIViewController3 执行以下几个方法回到首页，会发现 `UITabBar` 丢失：
- `[self.navigationController popToRootViewControllerAnimated:YES]`
- `[self.navigationController popToViewController:self.navigationController.viewControllers.firstObject animated:YES]`
- `[self.navigationController setViewControllers:@[self.navigationController.viewControllers.firstObject] animated:YES]`

注意 `animated` 需为 `YES` 才有问题，`NO` 是正常的。

<img src="https://user-images.githubusercontent.com/1190261/93775707-5499b280-fc55-11ea-89e4-e092b3ac366a.png" width="200" /><img src="https://user-images.githubusercontent.com/1190261/93775744-60857480-fc55-11ea-9be5-1e7821b64c13.png" width="200" /><img src="https://user-images.githubusercontent.com/1190261/93775767-68451900-fc55-11ea-9d2e-9bab38ad9327.png" width="200" />

该 bug 仅在 iOS 14 下出现，iOS 13 没问题。

以下是测试 Demo，**并附带了修复代码**（修复代码在项目中的 UITabBar+Test.m，`+load` 方法内），QMUI 已修复该问题，将跟随 4.2.1 版本发布，在此之前你可以将修复代码添加到业务项目中自行使用。
[TestTabBarInIOS14.zip](https://github.com/Tencent/QMUI_iOS/files/5288462/TestTabBarInIOS14.zip)

**Comment by XingChengY** [comment]
这个问题解决了？

**Comment by Y-HLiang** [comment]
> 这个问题解决了？
头疼的问题
在首页的控制器viewDidAppear中手动将tabBar.isHidden设置成false。是能解决这个问题，但是再次push就不消失了😭

**Comment by MoLice** [comment]
> 这个问题解决了？

解决了，修复代码跟随 4.2.1 发布，同时也已经贴到 issue 的测试 Demo 内。

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。

**Comment by Wakever** [comment]
> > 这个问题解决了？
> 
> 解决了，修复代码跟随 4.2.1 发布，在此之前也可自行添加到业务项目中临时修复。
> 
> ```objc
> // iOS 14.0 如果 pop 到一个 hidesBottomBarWhenPushed = NO 的 vc，tabBar 无法正确显示出来
> // https://github.com/Tencent/QMUI_iOS/issues/1100
> if (@available(iOS 14.0, *)) {
>     OverrideImplementation([UINavigationController class], @selector(popToViewController:animated:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void)) {
>         return ^NSArray<UIViewController *> *(UINavigationController *selfObject, UIViewController *viewController, BOOL animated) {
>             
>             // 系统的逻辑就是，在 push N 个 vc 的过程中，只要其中出现任意一个 vc.hidesBottomBarWhenPushed = YES，则 tabBar 不会再出现（不管后续有没有 vc.hidesBottomBarWhenPushed = NO），所以在 pop 回去的时候也要遵循这个规则
>             if (animated && selfObject.tabBarController && !viewController.hidesBottomBarWhenPushed) {
>                 BOOL systemShouldHideTabBar = NO;
>                 NSArray<UIViewController *> *viewControllers = [selfObject.viewControllers subarrayWithRange:NSMakeRange(0, [selfObject.viewControllers indexOfObject:viewController] + 1)];
>                 for (UIViewController *vc in viewControllers) {
>                     if (vc.hidesBottomBarWhenPushed) {
>                         systemShouldHideTabBar = YES;
>                     }
>                 }
>                 if (!systemShouldHideTabBar) {
>                     [selfObject qmui_bindBOOL:YES forKey:kShouldCheckTabBarHiddenKey];
>                 }
>             }
>             
>             // call super
>             NSArray<UIViewController *> *(*originSelectorIMP)(id, SEL, UIViewController *, BOOL);
>             originSelectorIMP = (NSArray<UIViewController *> * (*)(id, SEL, UIViewController *, BOOL))originalIMPProvider();
>             NSArray<UIViewController *> *result = originSelectorIMP(selfObject, originCMD, viewController, animated);
>             
>             [selfObject qmui_bindBOOL:NO forKey:kShouldCheckTabBarHiddenKey];
>             
>             return result;
>         };
>     });
>     
>     OverrideImplementation([UINavigationController class], @selector(popToRootViewControllerAnimated:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void)) {
>         return ^NSArray<UIViewController *> *(UINavigationController *selfObject, BOOL animated) {
>             
>             // 相邻两个界面的 pop 是没问题的，要超过2个才需要处理
>             if (animated && selfObject.tabBarController && !selfObject.viewControllers.firstObject.hidesBottomBarWhenPushed && selfObject.viewControllers.count > 2) {
>                 [selfObject qmui_bindBOOL:YES forKey:kShouldCheckTabBarHiddenKey];
>             }
>             // call super
>             NSArray<UIViewController *> *(*originSelectorIMP)(id, SEL, BOOL);
>             originSelectorIMP = (NSArray<UIViewController *> *(*)(id, SEL, BOOL))originalIMPProvider();
>             NSArray<UIViewController *> *result = originSelectorIMP(selfObject, originCMD, animated);
>             
>             [selfObject qmui_bindBOOL:NO forKey:kShouldCheckTabBarHiddenKey];
>             
>             return result;
>         };
>     });
>     
>     OverrideImplementation([UINavigationController class], @selector(setViewControllers:animated:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void)) {
>         return ^(UINavigationController *selfObject, NSArray<UIViewController *> *viewControllers, BOOL animated) {
>             
>             // 系统的逻辑就是，在 push N 个 vc 的过程中，只要其中出现任意一个 vc.hidesBottomBarWhenPushed = YES，则 tabBar 不会再出现（不管后续有没有 vc.hidesBottomBarWhenPushed = NO），所以在 pop 回去的时候也要遵循这个规则
>             UIViewController *viewController = viewControllers.lastObject;
>             if (animated && selfObject.tabBarController && !viewController.hidesBottomBarWhenPushed) {
>                 BOOL systemShouldHideTabBar = NO;
>                 for (UIViewController *vc in viewControllers) {
>                     if (vc.hidesBottomBarWhenPushed) {
>                         systemShouldHideTabBar = YES;
>                     }
>                 }
>                 if (!systemShouldHideTabBar) {
>                     [selfObject qmui_bindBOOL:YES forKey:kShouldCheckTabBarHiddenKey];
>                 }
>             }
>             
>             // call super
>             void (*originSelectorIMP)(id, SEL, NSArray<UIViewController *> *, BOOL);
>             originSelectorIMP = (void (*)(id, SEL, NSArray<UIViewController *> *, BOOL))originalIMPProvider();
>             originSelectorIMP(selfObject, originCMD, viewControllers, animated);
>             
>             [selfObject qmui_bindBOOL:NO forKey:kShouldCheckTabBarHiddenKey];
>         };
>     });
>     
>     OverrideImplementation([UINavigationController class], NSSelectorFromString(@"_shouldBottomBarBeHidden"), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void)) {
>         return ^BOOL(UINavigationController *selfObject) {
>             // call super
>             BOOL (*originSelectorIMP)(id, SEL);
>             originSelectorIMP = (BOOL (*)(id, SEL))originalIMPProvider();
>             BOOL result = originSelectorIMP(selfObject, originCMD);
>             
>             if ([selfObject qmui_getBoundBOOLForKey:kShouldCheckTabBarHiddenKey]) {
>                 result = NO;
>             }
>             return result;
>         };
>     });
> }
> ```

请问是怎么找到问题的根本 “_shouldBottomBarBeHidden” 这个方法的？

**Comment by Wakever** [comment]
请问是怎么找到问题的根本 “_shouldBottomBarBeHidden” 这个方法的？
想学习下是如何定位这种问题的。。

**Comment by FranzWang666** [comment]
iOS 14.2 已修复此bug

**Comment by MoLice** [comment]
> iOS 14.2 已修复此bug

已验证属实，新版本将会屏蔽 iOS 14.2 及以上版本的修复代码。

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) ，对 iOS 14.2 及以后的版本屏蔽相关代码。
