### ISSUE TITLE
Demo中的转场动画会闪一下

### ISSUE THREAD

**Issue by ChinaJackSion** [Tencent/QMUI_iOS#1101]
**Bug 表现**
问题的具体描述
Demo运行，在优化导航栏在转成时的样式，会闪一下，再改变颜色

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: ios14
 - Xcode 版本: xcode12
 - QMUI 版本: 4.2.0

**Comment by MoLice** [comment]
重复 #1081
