### ISSUE TITLE
UIView (QMUI_CornerRadius)出现bug

### ISSUE THREAD

**Issue by KYangLei** [Tencent/QMUI_iOS#1104]
**Bug 表现**
使用腾讯SuperPlayerView播放视频时调试状态会崩溃,非调试状态下正常播放。
问题的具体描述
-[MTLDebugBuffer newTextureWithDescriptor:offset:bytesPerRow:]:326: failed assertion `resourceOptions (0x0) must match backing buffer resource options (0x20).'
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="644" alt="image" src="https://user-images.githubusercontent.com/34836706/94111464-ad946100-fe76-11ea-8f01-80af1d4f08e7.png">

**如何重现**
1. 使用腾讯SuperPlayerView播放视频时候崩溃
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/94116161-4037fe80-fe7d-11ea-96ed-aaf798cb8805.png)
你的报错信息不是已经明确告诉你原因了？这个跟 QMUI 没有任何关系，你看到出现 QMUI 的堆栈是因为 method swizzling，你可以注释掉那些 QMUI 代码再验证一次，依然会有你贴的问题。

**Comment by Cc-1993** [comment]
> **Bug 表现**
> 使用腾讯SuperPlayerView播放视频时调试状态会崩溃,非调试状态下正常播放。
> 问题的具体描述
> -[MTLDebugBuffer newTextureWithDescriptor:offset:bytesPerRow:]:326: failed assertion `resourceOptions (0x0) must match backing buffer resource options (0x20).'
> **截图**
> Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
> <img alt="image" width="644" src="https://user-images.githubusercontent.com/34836706/94111464-ad946100-fe76-11ea-8f01-80af1d4f08e7.png">
> 
> **如何重现**
> 
> 1. 使用腾讯SuperPlayerView播放视频时候崩溃
> 2. ...
> 
> **预期的表现**
> 正常情况下，应该是什么表现
> 
> **其他信息**
> 
> * 设备: [例如模拟器、iPhone、iPad]
> * iOS 版本: [iOS 13.x]
> * Xcode 版本: [Xcode 11.x]
> * QMUI 版本: [4.x.x]

朋友，你发现是什么原因导致的吗？解决了吗？
