### ISSUE TITLE
QMUITextView粘贴文字后，如果字数超过最大限制，则本次粘贴失效

### ISSUE THREAD

**Issue by YJPizazz** [Tencent/QMUI_iOS#1105]
**Bug 表现**
问题的具体描述
QMUITextView粘贴文字后，如果字数超过最大限制，则本次粘贴失效。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![Snipaste_2020-09-25_15-43-02](https://user-images.githubusercontent.com/16317734/94240730-48a83c00-ff46-11ea-9c6f-de50a1476c4f.png)

尝试修改源码后，可以生效，修改如下图：
![Snipaste_2020-09-25_15-45-02](https://user-images.githubusercontent.com/16317734/94240808-64134700-ff46-11ea-9fc3-0b9221e4af80.png)

**如何重现**
1、字数限制50个
2、目前字数45个
3、粘贴一段长度为10的文字
4、输入框没有任何变化（粘贴失效）
5、（若目前字数只有35个，则可以粘贴成功）

**预期的表现**
正常情况下，应该是什么表现
粘贴成功。

**其他信息**
 - 设备: [iPhone XR]
 - iOS 版本: [iOS 13.5]
 - Xcode 版本: [Xcode 12.0]
 - QMUI 版本: [4.1.2]

**Comment by MoLice** [comment]
在这种情况下应该在 `textView:didPreventTextChangeInRange:replacementText:` 里自行裁剪文字并通过 `textView.text = xxx` 去更新输入框文字。QMUI 无法帮你自动裁剪，因为遇到某些特殊字符（例如 emoji 那种 CharacterSequences），一个字符占的 length > 1，此时如果直接在 `maximumTextLength` 的位置强制裁剪，会出现乱码，所以这个必须由业务自行处理，QMUI 怎么做都是不正确的。

**Comment by YJPizazz** [comment]
QMUI已经做了裁剪的，我截图部分的代码就是用于裁剪的，只是没有生效而已，你可以看一下这几行的代码逻辑

**Comment by MoLice** [comment]
这是 `QMUITextView` 的 bug。

如 issue 所示，在文字超出限制的时候，会在 `textView:shouldChangeTextInRange:replacementText:` 内将 `replacementText`裁剪后拼接到当前的 `textView.text` 上（也即以下截图所示的代码）。
![image](https://user-images.githubusercontent.com/1190261/94364294-c1e89000-00fa-11eb-8ad8-568e0b015b03.png)

这里的本意是希望直接替换输入框内的当前文字，但由于 `-[QMUITextView setText:]` 内在 `shouldResponseToProgrammaticallyTextChanges = YES` 时也会主动询问 `textView:shouldChangeTextInRange:replacementText:`，导致循环调用。而这里的 `QMUITextView.delegate` 是 `QMUIMultipleDelegates`，刚好 `QMUIMultipleDelegate` 在 QMUI 4.1.2 版本里修复了 #970 这个 bug，就是为了避免循环调用：
![image](https://user-images.githubusercontent.com/1190261/94364401-826e7380-00fb-11eb-8738-857db2e9de5e.png)

这会导致 `setText:` 里误以为 `textView:shouldChangeTextInRange:replacementText:` 的返回值为 `NO`，所以这次 `setText:` 无效，表现出来就是 issue 描述的“粘贴失效”。

究其原因，关键还是在于 `textView:shouldChangeTextInRange:replacementText:` 里裁剪文字后替换 `textView.text` 时，本次的 text 变化并不需要再次询问 delegate（因为这里已经保证了 set 进去的 text 已经是合法的了）。新版本将会屏蔽这里对 delegate 的询问，从而修复这个 bug，在此之前你可以用 [QMUITextView.m.zip](https://github.com/Tencent/QMUI_iOS/files/5288251/QMUITextView.m.zip) 替换本地文件临时修复。

感谢反馈！

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
