### ISSUE TITLE
QMUINavigationController和Hero框架冲突

### ISSUE THREAD

**Issue by iBinbro** [Tencent/QMUI_iOS#1106]
项目开发中使用了```QMUINavigationController```来解决```NavigationBar```过渡问题，现在新增了一个转场框架```Hero```来实现转场动画，现在```QMUINavigationController```和```Hero```均需要设置```NavigationController```的```delegate```,有没有什么好的解决办法既能保留```QMUINavigationController```保证```NavigationBar```过渡然后又能通过```Hero```实现转场效果？

**Comment by iBinbro** [comment]
在```UINavigationController+NavigationBarTransition```中是否加入仿真的navBar有如下判断
```
if (selfObject.navigationController.delegate && ![selfObject.navigationController.delegate respondsToSelector:@selector(navigationController:animationControllerForOperation:fromViewController:toViewController:)]) {
......
```
因为```Hero```转场会实现```(navigationController:animationControllerForOperation:fromViewController:toViewController:)```
就会导致过渡效果失效，也就是说现在如果我要自定义转场动画实现了```(navigationController:animationControllerForOperation:fromViewController:toViewController:)```方法，那么过渡效果就会失效么？有没有能够使其并存的方式 求解~

**Comment by ziecho** [comment]
对于采用自定义转场就无法享受 QMUI 过渡的问题下个版本会解决，请关注近期更新

**Comment by iBinbro** [comment]
> 对于采用自定义转场就无法享受 QMUI 过渡的问题下个版本会解决，请关注近期更新

期待中....

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 优化该问题。
