### ISSUE TITLE
QMUICMI.automaticCustomNavigationBarTransitionStyle = YES;导航差异，在iOS14中有问题

### ISSUE THREAD

**Issue by youeri3** [Tencent/QMUI_iOS#1107]
在iOS14正式版本中，当前控制器A的导航栏是蓝色，B控制器的导航是红色 ，A->push->B,的过程中  A的导航栏会变透明 ， 在B控制器中点击返回，或者手势返回，A控制器的导航栏也是透明，等返回成功后才会变成本来的蓝色

在最新的官方  QMUIDemo_iOS   项目中也是如此

环境
xcode 12.0
模拟器、真机  14.0

**Comment by MoLice** [comment]
#1081

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
