### ISSUE TITLE
1.present到系统页面(比如系统通讯录之类的) 导航栏的颜色能自定义不?

### ISSUE THREAD

**Issue by YY873267521** [Tencent/QMUI_iOS#1108]
QMUI 已经提供了**详尽的注释文档**，以及**完整的示例项目 [QMUI Demo](https://github.com/QMUI/QMUI_iOS_Demo)**，当你遇到某些功能不知道怎么使用，或者想知道 QMUI 是否有提供某些功能时，请先查看注释文档或者 Demo，找不到了再提 issue。若提的 issue 已有明确注释或示例的，**可能会被直接关闭或得不到及时的回复**，请知悉。

**Comment by MoLice** [comment]
使用 [UINavigationBar appearanceWhenContainedInInstancesOfClasses:]，传入你希望的通讯录的 class 即可。

如果你是因为 QMUI 配置表影响了系统通讯录而提的这个 issue，类似 #1113，那么：
目前的 QMUI 如果在配置表设置了 navigationBar 的样式，这些会通过 [UINavigationBar appearance] 影响到系统的 viewController（例如相册、通讯录等），有时候这并不是业务所希望的，所以新版本 QMUI 在配置表里提供了开关允许你指定哪些 class 里的 UINavigationBar 才会应用配置表的设置，就可以区分业务和系统的导航栏样式，请关注后续版本发布。

**Comment by YY873267521** [comment]
谢谢您的回复。4.2.1这个版本有配置表里边有吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MoLice"<notifications@github.com&gt;; 
发送时间: 2020年10月16日(星期五) 晚上8:54
收件人: "Tencent/QMUI_iOS"<QMUI_iOS@noreply.github.com&gt;; 
抄送: "ゝ      Miss  Q ゜"<873267521@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/QMUI_iOS] 1.present到系统页面(比如系统通讯录之类的) 导航栏的颜色能自定义不? (#1108)



使用 [UINavigationBar appearanceWhenContainedInInstancesOfClasses:]，传入你希望的通讯录的 class 即可。
 如果你是因为 QMUI 配置表影响了系统通讯录而提的这个 issue，类似 #1113，那么：
 目前的 QMUI 如果在配置表设置了 navigationBar 的样式，这些会通过 [UINavigationBar appearance] 影响到系统的 viewController（例如相册、通讯录等），有时候这并不是业务所希望的，所以新版本 QMUI 在配置表里提供了开关允许你指定哪些 class 里的 UINavigationBar 才会应用配置表的设置，就可以区分业务和系统的导航栏样式，请关注后续版本发布。

**Comment by MoLice** [comment]
没有，尚未发布

**Comment by YY873267521** [comment]
好的。谢谢您。期待新版本的发布。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/QMUI_iOS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 下午4:22
收件人:&nbsp;"Tencent/QMUI_iOS"<QMUI_iOS@noreply.github.com&gt;;
抄送:&nbsp;"ゝ      Miss  Q ゜"<873267521@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/QMUI_iOS] 1.present到系统页面(比如系统通讯录之类的) 导航栏的颜色能自定义不? (#1108)



 没有，尚未发布

**Comment by Y-HLiang** [comment]
> 没有，尚未发布
请问啥时候可以发布4.2.2啊

**Comment by MoLice** [comment]
[4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 已发布，该 issue 的解决方案请查看 Release Note 相关说明。
