### ISSUE TITLE
UIViewController+QMUI

### ISSUE THREAD

**Issue by PinkJoker** [Tencent/QMUI_iOS#1109]
![image](https://user-images.githubusercontent.com/17840935/94359788-acb03900-00db-11eb-8f1a-983143b8550f.png)
新导入的QMUI 在iOS13及以上，由于获取window的方式变更 导致项目运行直接崩溃

**Comment by MoLice** [comment]
重复 issue #766 。
使用 UIScene 的项目暂时不能使用 QMUI，另外，UIScene 是可以选择用或者不用的，如果项目本身并不需要用到 UIScene，只是因为 Xcode 新建项目默认开启 UIScene，请自行关闭。

**Comment by PinkJoker** [comment]
好的好的。
