### ISSUE TITLE
[UIKit Bug] iOS 14 修改 UITabBarAppearance.inlineLayoutAppearance.normal.titleTextAttributes[NSForegroundColorAttributeName] 会导致 UITabBarItem 文字无法完整展示

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#1110]
**截图**
修改颜色后文字展示不完整：
<img src="https://user-images.githubusercontent.com/1190261/94445029-8ffa2b00-01d9-11eb-8adc-91efbb7b892a.png" width="400" />

不修改颜色则没问题：
<img src="https://user-images.githubusercontent.com/1190261/94445106-a43e2800-01d9-11eb-8299-a1145ab5fc01.png" width="400" />

**如何重现**
```objc
UITabBarAppearance *appearance = tabBarController.tabBar.standardAppearance;
appearance.inlineLayoutAppearance.normal.titleTextAttributes = @{NSForegroundColorAttributeName: UIColor.redColor};
tabBarController.tabBar.standardAppearance = appearance;
```
**测试 Demo**
(内附修复代码，在 UITabBar+Test.m 内，默认注释了)
[TestTabBarAppearance.zip](https://github.com/Tencent/QMUI_iOS/files/5293298/TestTabBarAppearance.zip)

**预期的表现**
UITabBarItem 文字完整展示。

**其他信息**
 - 设备: iPad、iPhone 横屏，反正只要是 UITabBarItem 图片和文字水平布局就会
 - iOS 版本: [iOS 14.0]
 - Xcode 版本: [Xcode 12.0]

**Comment by MoLice** [comment]
直接原因是 iPad 下会使用 `UITabBar.standardAppearance.inlineLayoutAppearance`，此时默认的 title font 类型为“UICTFontTextStyleFootnote”。当 `UITabBarButtonLabel` 使用这种 font 时，`sizeThatFits:` 会返回错误的值，如果换成 `UILabel`，或者换其他 font，则没这种问题。
所以业务也可以通过手动指定一个普通的 UIFont 来避免这种情况。

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。

**Comment by horsley** [comment]
![image](https://user-images.githubusercontent.com/1982676/119294065-3671cf80-bc86-11eb-854e-1ec990216229.png)

设备型号 iPad Pro 12.9 第二代 （MQDD2ZP/A） iOS 14.0.1 依然出现这个问题，这里fontFamily 是system-ui所以没有应用到这个fix，需要一个pr么？ @MoLice mo

**Comment by MoLice** [comment]
@horsley 可以

**Comment by MoLice** [comment]
> ![image](https://user-images.githubusercontent.com/1982676/119294065-3671cf80-bc86-11eb-854e-1ec990216229.png)
> 
> 设备型号 iPad Pro 12.9 第二代 （MQDD2ZP/A） iOS 14.0.1 依然出现这个问题，这里fontFamily 是system-ui所以没有应用到这个fix，需要一个pr么？ @MoLice mo

@horsley  不再采用判断 fontFamily 的方式，具体请查看 #1285
