### ISSUE TITLE
4.1.1版本，侧滑手势异常，容易出现卡顿，退回桌面后再次进入app，页面异常，push/pop/侧滑返回 交互异常

### ISSUE THREAD

**Issue by wuhuanlong** [Tencent/QMUI_iOS#1111]
**Bug 表现**
问题的具体描述
pod 'QMUIKit', '~>4.1.1'
页面侧滑返回时，偶尔卡住
 

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/15623113/94449650-e74eca00-01de-11eb-87ea-9c257916c3cd.png)
![image](https://user-images.githubusercontent.com/15623113/94449820-16fdd200-01df-11eb-82a0-a3f862c0e0e0.png)

**如何重现**
复现步骤：A->B,在B中侧滑返回，多次侧滑返回

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: iPhone6s plus / iPhone6s
 - iOS 版本: [iOS 13.6]
 - Xcode 版本: [Xcode 11.5]
 - QMUI 版本: [4.1.1]

**Comment by wuhuanlong** [comment]
qmuidemo同样也有这样的问题

**Comment by MoLice** [comment]
> qmuidemo同样也有这样的问题

QMUI Demo 中具体做什么操作后，会出现异常的表现？请详细描述操作步骤，或者录屏后压缩为 *.zip 丢到 GitHub 评论里。

**Comment by wuhuanlong** [comment]
> > qmuidemo同样也有这样的问题
> 
> QMUI Demo 中具体做什么操作后，会出现异常的表现？请详细描述操作步骤，或者录屏后压缩为 *.zip 丢到 GitHub 评论里，并且说明具体的 QMUI Demo 版本、QMUIKit 版本、iOS 系统版本。
> 
> 另，描述 issue 注意个人隐私，截图里带有真实姓名和组织架构信息可能不太恰当。
--------------------------------------------------------------------------------------------------------

QMUI Demo 中具体做什么操作后，会出现异常的表现？请详细描述操作步骤，或者录屏后压缩为 *.zip 丢到 GitHub 评论里，并且说明具体的 QMUI Demo 版本、QMUIKit 版本、iOS 系统版本。
> A页面push到B页面，B页面侧滑返回
> 出现卡死，退回桌面后再打开App，UINavigationBar上的组件消失，push、pop和侧滑返回都会有黑底，且动画异常

> QMUI Demo版本：4.0.4 build:17

我们使用的
> QMUI Kit版本：4.1.1
> iOS 系统版本：iOS13.6

录屏zip：
[IMG20200929100235.zip](https://github.com/Tencent/QMUI_iOS/files/5295914/IMG20200929100235.zip)
操作：每次pop都是侧滑返回

**Comment by MoLice** [comment]
4.1.1 在 iOS 13.6 下，用 QMUI Demo 测试，不断手势返回无法重现你描述的问题哦，是否还有其他条件？

**Comment by wuhuanlong** [comment]
> 4.1.1 在 iOS 13.6 下，用 QMUI Demo 测试，不断手势返回无法重现你描述的问题哦，是否还有其他条件？

我录制了一个操作视频给你，在实际生产中使用过程中，产生的概率不会像我操作的那样概率，有个别用户反馈，一开始也是摸不着头脑。
有几次我们自己出现过，然后我们抓住了规律，在测划返回时概率很大，按照视频上操作，iPhone6s，或iPhone6s plus上基本操作20秒内都能复现，有时候第一下侧滑返回就会出现。iPhoneXR等性能好一点的手机出现概率相对小一些。

附上视频地址：
优酷地址：https://v.youku.com/v_show/id_XNDg4MzI5MTM1Mg==.html

**Comment by MoLice** [comment]
是否方便使用 4.2.0 或者 4.2.1 的 QMUI Demo 在该测试机上尝试？可能中间版本存在一些问题。

**Comment by wuhuanlong** [comment]
> 是否方便使用 4.2.0 或者 4.2.1 的 QMUI Demo 在该测试机上尝试？可能中间版本存在一些问题。

最新版本4.2.1确实没复现了。

**Comment by MoLice** [comment]
嗯嗯，手势、UINavigationController 相关改动很多，建议直接升级到最新版。此 issue 先关闭，后续有需要再补充后打开。

**Comment by wuhuanlong** [comment]
> 嗯嗯，手势、UINavigationController 相关改动很多，建议直接升级到最新版。此 issue 先关闭，后续有需要再补充后打开。

我们升级到了QMUIIKit 4.2.1版本，还是可以出现黑屏现象，只不过概率降低了很多。在4.2.1的官方demo中，基本上复线不了，我这边实在是排查不出原因。如果可以麻烦您帮忙在4.1.1版本的官方demo上排查。

**Comment by wuhuanlong** [comment]
我在微信读书app上也测试出tong同样的问题
[IMG20201023154623.zip](https://github.com/Tencent/QMUI_iOS/files/5428032/IMG20201023154623.zip)
