### ISSUE TITLE
部分图片选择，导航条颜色问题

### ISSUE THREAD

**Issue by Y-HLiang** [Tencent/QMUI_iOS#1113]
在4.2.1的版本中选择照片，选择部分照片，体统弹出的选择照片页面的导航条颜色和项目设置的导航条背景颜色一致，但是导航条上按钮和文字的颜色是系统默认的颜色，这样看起来非常不协调。这个问题再4.2.0中没有存在。
具体的可以
![IMG_3441](https://user-images.githubusercontent.com/19301132/95161522-f54fac80-07d5-11eb-9890-54e4c5eed300.PNG)
![IMG_3442](https://user-images.githubusercontent.com/19301132/95161529-faacf700-07d5-11eb-8556-bb0fb8f8c38c.PNG)

**Comment by Y-HLiang** [comment]
相同的问题也出现在4.2.1的Demo中。QMUIPickingImage
![IMG_0052](https://user-images.githubusercontent.com/19301132/95161977-195fbd80-07d7-11eb-84c3-d98bdd53af7f.PNG)

**Comment by MoLice** [comment]
[4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 已发布，该 issue 的解决方案请查看 Release Note 相关说明。
