### ISSUE TITLE
线程问题

### ISSUE THREAD

**Issue by ZClee128** [Tencent/QMUI_iOS#1114]
![image](https://user-images.githubusercontent.com/18162711/95555856-fcc8bd00-0a44-11eb-9d9a-53610be96ff1.png)
这个地方的方法应该在主线程中执行，这里导致我这里报警告了

**Comment by ZClee128** [comment]
![image](https://user-images.githubusercontent.com/18162711/95556159-72cd2400-0a45-11eb-95b7-296e02044c13.png)

**Comment by MoLice** [comment]
4.2.1版本说明里的“会带来 QMUI 新旧版本兼容问题的更新”第1点已有说明。
