### ISSUE TITLE
打开Xcode主线程检测开关下，在分线程里面调用 -[UIViewController description]会报非主线刷UI相关警告，导致UI刷新卡顿

### ISSUE THREAD

**Issue by SupermanChao** [Tencent/QMUI_iOS#1115]
**Bug 表现**
Xcode调试，在分线程调用`-[UIViewController description]`控制台会输出非主线程刷新UI相关警告，并卡顿界面UI刷新相关

**截图**
Xcode打开主线程检测情况下

![0](https://user-images.githubusercontent.com/18051214/95566703-8469f800-0a54-11eb-864f-ab30e30656d9.png)

![1](https://user-images.githubusercontent.com/18051214/95566757-99df2200-0a54-11eb-962e-ae66a1880d0c.png)

![2](https://user-images.githubusercontent.com/18051214/95566773-9f3c6c80-0a54-11eb-9b84-d776bee40643.png)

![3](https://user-images.githubusercontent.com/18051214/95566787-a2cff380-0a54-11eb-92c6-70c3bb3f4bf1.png)

**如何重现**
1. 集成QMUI
2. 在分线程调用任意一个`UIViewController`的`description`方法

**预期的表现**
UI刷新顺利，控制台没有相关警告信息

**其他信息**
 - 设备: [iPhone、iPad]
 - iOS 版本: [iOS 13.4.1]
 - Xcode 版本: [Xcode 11.3]
 - QMUI 版本: [4.2.1]

**建议**
在重写了系统方法之后，需要确保相关方法调用的线程安全问题

![4](https://user-images.githubusercontent.com/18051214/95567242-3d303700-0a55-11eb-9163-396349401a90.png)

**Comment by xt-input** [comment]
[UIImageView image] must be used from main thread only

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
