### ISSUE TITLE
您好，请问静态cell中，是否可以添加一个arrowImage属性用于修改cell右边箭头的图标呢

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#1116]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。

**Comment by MoLice** [comment]
请用自己的accessoryView去实现，或者统一修改配置表里的cell箭头图片。
