### ISSUE TITLE
pod install

### ISSUE THREAD

**Issue by ZClee128** [Tencent/QMUI_iOS#1118]
4.2.1pod search可以找到，但是pod install不了

**Comment by ZClee128** [comment]
![image](https://user-images.githubusercontent.com/18162711/95702939-62ed5400-0c80-11eb-9460-864f03856c20.png)

**Comment by ZClee128** [comment]
![image](https://user-images.githubusercontent.com/18162711/95703163-0e96a400-0c81-11eb-97d3-4b740e7bdd98.png)
这个系统定的有点高了吧，不适配ios9了吗

**Comment by MoLice** [comment]
更新版本前请自行查阅更新日志：
![image](https://user-images.githubusercontent.com/1190261/95809660-e622ae80-0d41-11eb-8e6f-a9f5eecb4cc0.png)
![image](https://user-images.githubusercontent.com/1190261/95809713-0e121200-0d42-11eb-86f0-eedaade1c7d8.png)
