### ISSUE TITLE
QMUITextView 点击候选词，超过字符数限制，高度变化的回调`newHeightAfterTextChanged `不会调用

### ISSUE THREAD

**Issue by CheckRan** [Tencent/QMUI_iOS#1120]
**Bug 表现**
点击的候选词正好处于 换行 且 超出了限制字体大小，会导致高度变化的回调 
`- (void)textView:(QMUITextView *)textView newHeightAfterTextChanged:(CGFloat)height` 不调用

**截图**
我点击候选词 “ 微信”，但是不会调用高度变化回调
![image](https://user-images.githubusercontent.com/14838025/95731571-466a0f80-0cb2-11eb-94ea-79459150927f.png)

**如何重现**
视频：https://github.com/CheckRan/QMUIDemo_iOS/blob/master/候选词点击问题.mov

**预期的表现**
正常情况下，应该是调用高度变化

**其他信息**
 - 设备: [例如模拟器]
 - iOS 版本: [iOS 12]
 - Xcode 版本: [Xcode 12]
 - QMUI 版本: [master]

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
