### ISSUE TITLE
iPadOS，开启悬浮键盘的情况下,  与IQKeyboardManager结合使用时会导致App卡死

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1121]
**Bug 表现**
iPadOS，开启悬浮键盘的情况下,  与IQKeyboardManager结合使用时会导致App卡死，卡死的原因在于循环调用如下图所示的方法。

**截图**
<img width="1459" alt="图片" src="https://user-images.githubusercontent.com/22904757/95943753-3c165580-0e19-11eb-9b69-bb2e4019d832.png">

**如何重现**
重现的前提条件如下：
1、 iPad开启悬浮键盘
2、在`applyConfigurationTemplate`方法中实现`[IQKeyboardManager sharedManager];`
3、实现`self.textView.inputAccessoryView = UIView.new;`
注意，前提条件缺一不可。
步骤：开启悬浮键盘，进入Demo后，点击`QMUITextView示例`，进入页面后再点击输入框就会卡死。
以下是Demo,  我改动的地方加了`/// MARK: 标记`,  全局搜索进行查看
[_QMUIDemo_iOS.zip](https://github.com/Tencent/QMUI_iOS/files/5375628/_QMUIDemo_iOS.zip)

**预期的表现**
正常使用

**其他信息**
 - 设备: iPad
 - iOS 版本: iOS 14.0
 - Xcode 版本: Xcode 12.0
 - QMUI 版本: 4.2.1

**Comment by KALIANS** [comment]
请问这个问题解决了吗

**Comment by jiasongs** [comment]
> 请问这个问题解决了吗

https://github.com/Tencent/QMUI_iOS/issues/1247，QMUI里的解决了，但如果你的代码或者其他人的代码也有相关的hook，还会出问题
