### ISSUE TITLE
QMUITheme 在切换主题时无法刷新 UITabBarItem.selectedImage

### ISSUE THREAD

**Issue by DeadAndLife** [Tencent/QMUI_iOS#1122]
考虑以下伪代码：
```objc
tabBarItem = [UITabBarItem image:[UIImage qmui_imageWithThemeProvider:^{
    if (主题A) {
        return Image1;
    } else {
        return Image2;
    }
}] selectedImage:[UIImage qmui_imageWithThemeProvider:^{
    if (主题A) {
        return Image3;
    } else {
        return Image4;
    }
}]];
```
在主题A的情况下，预期 UITabBarItem 默认是 Image1，选中时 Image2。当切换到其他主题时，预期默认 Image3，选中 Image4。
基于 QMUI 4.2.1 实测，切换到其他主题时，Image4 依然显示为 Image2，无法得到刷新，其他 Image 正常。

**Comment by MoLice** [comment]
请提供一份 Demo

**Comment by DeadAndLife** [comment]
https://github.com/DeadAndLife/testQMUI

**Comment by DeadAndLife** [comment]
测试手机iPhone 6s plus，系统13.7

**Comment by MoLice** [comment]
简单看了一下是 UITabBarItem 内部的 `UITabBarSwappableImageView` 在主题切换时，`setImage:` 有被重新 perform，但控制选中图片的 selector 没重新 perform，待查证。

**Comment by DeadAndLife** [comment]
你好，关于这个问题，现在有解决吗？我们项目就差这里了，如果一直不解决，那重新自己定义就太费时间了。

发自我的iPhone

**Comment by MoLice** [comment]
`UITabBarItem` 通过 `image`、`selectedImage` 两个属性来获取 normal/selected 时的图片。对于 `image` 属性，它会直接返回你赋值给它的 image 对象，而 `selectedImage` 属性返回的是你一开始赋值给它的图片经过处理后的新 image 对象，所以如果你将一个 `QMUIThemeImage` 赋值给 `selectedImage`，那么最终 `UITabBarItem` 读取出来的是你的 `QMUIThemeImage` 的 `rawImage`，也即丢失了动态特性，成为一张普通的图。这就是为什么主题切换时 `selectedImage` 无法被刷新的原因。

另外 iOS 12 及以下，系统无法指定非选中状态的 `UITabBarItem` 的图片颜色，为了让这个颜色能在配置表里控制，QMUI 在 QMUIConfiguration.m 内有一个 `qmui_updateTintColorForiOS12AndEarlier` 的方法，会对 UITabBarItem.image/selectedImage 做一些处理，这段代码也会导致上述说的“动态图片被强制转成静态图片”的问题。经过衡量，我们决定在 iOS 12 下不处理 `QMUIThemeImage`，优先保证 `UITabBarItem` 能正常响应主题变化，至于非选中状态的图片色值，请业务自行在 `QMUIThemeImage` provider block 里给图片设置颜色并将 renderingMode 设置为 AlwaysOriginal。（由于这个变化，如果项目之前就有将 `QMUIThemeImage` 作为 `UITabBarItem` 的 image，那么更新 QMUI 新版后，tabBarItem 的图片颜色可能有误，需要业务手动修改，届时请关注正式发布后的 Release Note）。

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
