### ISSUE TITLE
请问在老项目里加入QMUI，有没有可能会对项目造成一些未知影响？

### ISSUE THREAD

**Issue by DLsunset** [Tencent/QMUI_iOS#1128]
因为看到QMUI中在很多load方法里做了很多操作。也使用了很多交换方法。不知道直接加到老项目里有没有可能会对老项目有未知的影响呢？

**Comment by zp0708** [comment]
我也有些困惑，优化启动时间竭力的移除load，QMUI里却到处都是<狗头>

**Comment by DreamForStar** [comment]
自定义的tabbar点击跳转的时候闪退了 不知道怎么解决

**Comment by MoLice** [comment]
> 因为看到QMUI中在很多load方法里做了很多操作。也使用了很多交换方法。不知道直接加到老项目里有没有可能会对老项目有未知的影响呢？

QMUI 是个不小的项目，影响无法一一说明，请自行测试。

**Comment by MoLice** [comment]
> 我也有些困惑，优化启动时间竭力的移除load，QMUI里却到处都是<狗头>

load 方法对启动时间的影响是存在的，但也是有限的。
后续版本将会逐渐移除 load 方法，将其改为在用到对应功能时才进行 method swizzlling，请关注后续版本的 Release Note。

**Comment by MoLice** [comment]
> 自定义的tabbar点击跳转的时候闪退了 不知道怎么解决

信息不全无法跟进，请自行开启新 issue 补充完整。
