### ISSUE TITLE
QMUICommonTableViewController页面崩溃

### ISSUE THREAD

**Issue by ddkcainiao** [Tencent/QMUI_iOS#1133]
**Bug 表现**
问题的具体描述
继承使用QMUICommonTableViewController，点击到这个页面，crash出现在178行的[self.view addSubview:_tableView];出现EXC_BAD_ACCESS崩溃.

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![21531604377097_ pic_hd](https://user-images.githubusercontent.com/17842340/97949514-d0e3f180-1dce-11eb-953c-e760c6da6dc9.jpg)
**如何重现**
1. 继承使用QMUI 4.2.1版本里的QMUICommonTableViewController类；
2. 点击到这个页面，就crash掉了.

**预期的表现**
正常情况下，应该不会崩溃啊，老版本不会崩溃

**其他信息**
 - 设备: [模拟器、iPhone]上都会崩溃
 - iOS 版本: [iOS 14.0和14.1]
 - Xcode 版本: [Xcode 12.1]
 - QMUI 版本: [4.2.1]

**Comment by MoLice** [comment]
请提供一份 Demo，或者贴出这个 ViewController 的 .h/.m 文件

**Comment by ddkcainiao** [comment]
是在Swift 5上面运行的

**Comment by MoLice** [comment]
该 issue 因提供的信息不足被关闭，请补充必要信息后再重新打开。
