### ISSUE TITLE
QMUIMoreOperationController 遮罩

### ISSUE THREAD

**Issue by shuiliang** [Tencent/QMUI_iOS#1134]
在使用 QMUIMoreOperationController的时候，怎么拿到遮罩层啊，我想设置当用户点击遮罩层的时候，moreOperationController不消失，想改变遮罩的颜色，甚至加一个自定义的视图在红色框的地方

![image](https://user-images.githubusercontent.com/17922774/97957780-d5b49f80-1de6-11eb-871f-267f6555bd88.png)

**Comment by MoLice** [comment]
QMUIMoreOperationController 是基于 QMUIModalPresentationViewController 实现的弹出浮层组件，所以你可以通过 `moreOperationController.qmui_modalPresentationViewController.dimmingView` 获取到遮罩的引用。

至于点击遮罩不想隐藏浮层，通过查看 `QMUIModalPresentationViewController` 的头文件可知，修改 `modal = NO` 即可。如果在点击遮罩时还要做其他事情，建议你可以自己添加 tap 手势到 dimmingView 上，或者直接将一个 UIControl 作为 dimmingView 设置给 QMUIModalPresentationViewController，然后用 addTarget:action: 的方式添加事件到 UIControl 上。
