### ISSUE TITLE
感觉好久没更新了，有没有开发Swift版计划？

### ISSUE THREAD

**Issue by SmallMX** [Tencent/QMUI_iOS#1135]
希望在README.md中加入版本更新计划。

**Comment by MoLice** [comment]
版本列表在 https://github.com/Tencent/QMUI_iOS/releases
版本更新计划在 https://github.com/Tencent/QMUI_iOS/projects
这些都是 GitHub 已经提供的标准入口，所以 README 里不会加这些内容。
