### ISSUE TITLE
大量的接口实现写在h文件了，建议将实现迁移到m文件

### ISSUE THREAD

**Issue by jingliancui** [Tencent/QMUI_iOS#1136]
如题，大量的接口实现写在h文件了，建议将实现迁移到m文件，代码可以重构的更好。

**Comment by MoLice** [comment]
这个建议其实没有实际意义，因为具体的代码都没有列出来，请补充详细细节。

**Comment by jingliancui** [comment]
@MoLice 
[QMUIEasings.h](https://github.com/Tencent/QMUI_iOS/blob/852826c63a99f8aff40bd80fe8942c1cc9600129/QMUIKit/QMUIComponents/QMUIAnimation/QMUIEasings.h)
[QMUICommonDefines.h](https://github.com/Tencent/QMUI_iOS/blob/59eb35e44df547166e366f28d1c57e6d63a79e84/QMUIKit/QMUICore/QMUICommonDefines.h)
[QMUIRuntime.h](https://github.com/Tencent/QMUI_iOS/blob/852826c63a99f8aff40bd80fe8942c1cc9600129/QMUIKit/QMUICore/QMUIRuntime.h)

**Comment by MoLice** [comment]
你关注的应该是里面类似 `CGRectSetX` 之类的函数吧，因为它们是内联函数，所以必须把声明和实现写在一起，这是编译器的要求。
至于为什么要以内联函数的方式来定义这些函数，是遵循系统的方式，你可以查看 CGGeometry.h，系统的 `CGRectMake` 之类的函数，也是用内联函数的方式，这可以加快程序运行效率。
目前来看这样的实现方式对项目组织结构、代码可读性这些并没有什么太大的负面作用，“代码可以重构的更好”的说法可能略有偏颇。
