### ISSUE TITLE
求教QMUIModalPresentation弹出的视图中的状态栏隐藏问题

### ISSUE THREAD

**Issue by eric0815** [Tencent/QMUI_iOS#1137]
您好，我在使用的时候碰到了一点问题，就是在QMUIModalPresentationViewController弹出的窗口中打开的视图窗口里的状态栏无法隐藏，详细看了Demo，也试了多种方法，还是不得其法，我做了一个Demo，烦请帮忙看看，谢谢。

[TestStatusBarDemo项目](https://wwa.lanzous.com/iphNHi7u73a)

    ModalViewController *modal = [self.storyboard instantiateViewControllerWithIdentifier:@"ModalViewController"];

    UIView *v = [[UIView alloc] init];
    v.backgroundColor = [UIColor lightGrayColor];

    QMUIModalPresentationViewController *modalViewController = [[QMUIModalPresentationViewController alloc] init];
    modalViewController.dimmingView = v;
    modalViewController.contentViewController = modal;
    modalViewController.contentViewMargins = UIEdgeInsetsMake(100, 0, 100, 0);

    modalViewController.animationStyle = QMUIModalPresentationAnimationStylePopup;
    [modalViewController showWithAnimated:YES completion:nil];

**Comment by MoLice** [comment]
你的 QMUI 用的是旧版的 4.0.4，提 issue 请注明使用的版本，不然很浪费时间调试。

当你用 QMUIModalPresentationViewController 去展示界面时，有3种使用方法（自行查看头文件说明），你使用的是以 window 的形式去显示，此时状态栏的控制权会交给 QMUIModalPresentationViewController，因为它是 window 的 rootViewController。

所以解决方法是在需要切换状态栏显隐时，去切换 QMUIModalPresentationViewController 而不是你的业务 viewController。但这样不太方便，所以有状态栏控制需求时，建议用 present 的方式去使用 modal 而不是以 window 的方式。

另外，你在 DetailViewController 里切换状态栏显隐的操作本身就有问题，修改了 prefersStatusBarHidden 的返回值后，应该调用 setNeedsStatusBarAppearanceUpdate 去通知系统刷新状态栏，这是系统文档里明确的要求，但你没有这样做，虽然看起来正确，但只是因为你同时也切换了 navigationBar 的显隐，由 navigationBar 触发了 statusBar 的刷新。你可以试试把 DetailViewController 里的 setNavigationBarHidden 注释掉，会发现直接打开的 detail 也无法切换 statusBar 显隐。
