### ISSUE TITLE
iOS 11下 导航栏后退按钮大小不正常 变成固定 100,44,如果导航栏的titleview用UISearchbar显得尤为明显

### ISSUE THREAD

**Issue by iBinbro** [Tencent/QMUI_iOS#1138]
**Bug 表现**
iOS 11下 导航栏后退按钮大小不正常 变成固定 100,44,如果导航栏的titleview用UISearchbar显得尤为明显，导致UISearchbar被挤到了右边

**截图**
<img width="759" alt="WeChated78e1eb4b42989f33c04c99887d4e1c" src="https://user-images.githubusercontent.com/15324447/98527144-99d17c80-22b5-11eb-862c-38d939a000a5.png">

**如何重现**
1. 
```
    UISearchBar *searchBar = [[UISearchBar alloc] init];
    searchBar.placeholder = @"123456789";
    self.navigationItem.titleView = searchBar;
```
2. 使用的官方demo，只要```titleView```是```UISearchbar```问题即可重现

**预期的表现**
正常情况下，返回按钮的大小应该和自身设置的图片和标题自适应，不应该把```UISearchbar```挤走

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 11.0.1]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.2.1]

**Comment by MoLice** [comment]
好像没发现你说的问题？
![image](https://user-images.githubusercontent.com/1190261/98679079-703e5100-239a-11eb-954b-9ae0701df036.png)

**Comment by iBinbro** [comment]
> 好像没发现你说的问题？
> <img alt="" width="400" src="https://user-images.githubusercontent.com/1190261/98679079-703e5100-239a-11eb-954b-9ae0701df036.png">
> 
> 使用更低版本的 iOS 10 也没发现你说的问题。
> <img alt="" width="400" src="https://user-images.githubusercontent.com/1190261/98680399-51d95500-239c-11eb-9773-5ee27d7d4839.png">

那可能只是11.0.1版有问题 更低版本的话确实是没问题的

**Comment by MoLice** [comment]
暂不处理
