### ISSUE TITLE
UIMenuController+QMUI windowForFirstResponder 引起的闪退

### ISSUE THREAD

**Issue by pomin** [Tencent/QMUI_iOS#1139]
**Bug 表现**
问题的具体描述

QMUITextField 在键盘弹起的情况下再点击，处理UIMenuController相关业务的时候，会通过 UIApplication.sharedApplication.delegate.window 查找当前的window，如果AppDelegate 里面没有window属性，应用就会闪退。

**如何重现**
1. 创建一个全新的项目，AppDelegate不做任何处理。
2. 在项目中使用 QMUITextField，点击唤起键盘，再次点击TextField，就会复现。

**Comment by MoLice** [comment]
重复 #766
