### ISSUE TITLE
侧滑手势导致导航栏变颜色

### ISSUE THREAD

**Issue by TMMMMMS** [Tencent/QMUI_iOS#1140]
项目刚更新QMUIKit库，更新完后发现一个问题：
当前页面导航栏的背景色默认是设置为透明色，当使用侧滑手势时，该页面的导航栏立即变为base controller里设置的白色，查看demo并没有出现此问题。希望作者能给我一个排错的思路，找不到问题点是出在哪里。

![IMG_0298](https://user-images.githubusercontent.com/18571410/98801169-65dc8f80-244c-11eb-92ab-ded21a961d39.jpg)

------------------------------------------------- 分割线 -------------------------------------------------

![IMG_0299](https://user-images.githubusercontent.com/18571410/98801181-6c6b0700-244c-11eb-8d4c-823324cb1c04.jpg)

**Comment by MoLice** [comment]
可以将配置表的 AutomaticCustomNavigationBarTransitionStyle 置为 YES，或者使用 QMUICustomNavigationBarTransitionDelegate 里的 customNavigationBarTransitionKey，具体请看注释及 Demo。
<img src="https://user-images.githubusercontent.com/1190261/98825310-4b67dd80-246f-11eb-80d5-76469db4e753.png" width="420" />

**Comment by TMMMMMS** [comment]
解决了，谢谢
