### ISSUE TITLE
是否能通过设置QMUI中的属性来实现Tabbar的磨砂效果

### ISSUE THREAD

**Issue by TMMMMMS** [Tencent/QMUI_iOS#1141]
![IMG_0300](https://user-images.githubusercontent.com/18571410/99023837-65eda400-25a0-11eb-917d-dafbb840f6ae.jpg)

如何实现图中描述的这种tabbar效果，demo里看到一个tabBarBarTintColor属性，项目中设置该属性带透明度的颜色或者非透明度颜色都没有得到期望效果。

设置的参数
![1605236937867](https://user-images.githubusercontent.com/18571410/99023975-ac430300-25a0-11eb-816c-04ba7e407195.jpg)

**Comment by fanyuecheng** [comment]
大概QMUI缺少个接口来设置    
tabbar.standardAppearance.backgroundEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleLight] //iOS 13

**Comment by MoLice** [comment]
用半透明的 barTintColor 即可出现磨砂效果。但磨砂程度根据半透明的值、backgroundEffect 的类型不同而不同，配置表里确实没有提供 backgroundEffect 设置项，因为对 iOS 版本有要求，建议自行设置。
