### ISSUE TITLE
QMUISearchController 非全面屏崩溃

### ISSUE THREAD

**Issue by ganweiming** [Tencent/QMUI_iOS#1144]
**Bug 表现**
在iphone6 上会点击SearchBar会导致崩溃, 全面屏机型可正常使用

**截图**
<img width="801" alt="企业微信截图_ce292de7-7277-4e87-b59c-1bd301832397" src="https://user-images.githubusercontent.com/18005096/99363879-3ddba900-28f0-11eb-8286-f2010dfa117e.png">

**其他信息**
 - 设备: [iPhone 6 (Plus)]
 - iOS 版本: [iOS 12.4.8]
 - Xcode 版本: [Xcode 12.2]
 - QMUI 版本: [4.2.1]

错误日志:
2020-11-17 16:03:42.371678+0800 DeClub[1269:53378476] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[DeClub.HotelSearchController _searchController]: unrecognized selector sent to instance 0x105492480'
*** First throw call stack:
(0x1f3fcf180 0x1f31a79f8 0x1f3eeb9bc 0x2207e8220 0x1f3fd49c8 0x1f3fd665c 0x220048b90 0x2207e967c 0x2207e74c8 0x1033b3c54 0x220c3e87c 0x220aa3434 0x220a604bc 0x220a4e96c 0x2203e5ac4 0x2203edccc 0x2203eb670 0x2203eab9c 0x2203dec78 0x2203de3a8 0x2203de188 0x2207f67d0 0x2207d685c 0x22089c9d4 0x22089f100 0x220898330 0x1f3f60f1c 0x1f3f60e9c 0x1f3f60784 0x1f3f5b6c0 0x1f3f5afb4 0x1f615c79c 0x2207bcc38 0x100b7e8c0 0x1f3a1e8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[DeClub.HotelSearchController _searchController]: unrecognized selector sent to instance 0x105492480'
terminating with uncaught exception of type NSException

**Comment by ganweiming** [comment]
2020-11-17 16:03:42.371678+0800 DeClub[1269:53378476] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[DeClub.HotelSearchController _searchController]: unrecognized selector sent to instance 0x105492480'
*** First throw call stack:
(0x1f3fcf180 0x1f31a79f8 0x1f3eeb9bc 0x2207e8220 0x1f3fd49c8 0x1f3fd665c 0x220048b90 0x2207e967c 0x2207e74c8 0x1033b3c54 0x220c3e87c 0x220aa3434 0x220a604bc 0x220a4e96c 0x2203e5ac4 0x2203edccc 0x2203eb670 0x2203eab9c 0x2203dec78 0x2203de3a8 0x2203de188 0x2207f67d0 0x2207d685c 0x22089c9d4 0x22089f100 0x220898330 0x1f3f60f1c 0x1f3f60e9c 0x1f3f60784 0x1f3f5b6c0 0x1f3f5afb4 0x1f615c79c 0x2207bcc38 0x100b7e8c0 0x1f3a1e8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[DeClub.HotelSearchController _searchController]: unrecognized selector sent to instance 0x105492480'
terminating with uncaught exception of type NSException

**Comment by MoLice** [comment]
无法重现。
<img src="https://user-images.githubusercontent.com/1190261/99897146-02ffb980-2cd2-11eb-9c11-c15f3b606c53.png" width="320"/>
