### ISSUE TITLE
QMUIEmptyView的sizeThatContentViewFits计算高度有误

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#1148]
**Bug 表现**
若`textLabelInsets` 或者 `detailTextLabelInsets` 设置了左右值，虽然`layoutSubviews`的时候 label的最大宽是`CGRectGetWidth(self.contentView.bounds) - UIEdgeInsetsGetHorizontalValue(self.textLabelInsets)`，但是在`sizeThatContentViewFits`方法里label的最大宽却少减了LabelInsets的左右值，导致label高度计算错误。

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
