### ISSUE TITLE
QMUIImagePreviewViewController 视频播放尺寸计算错误的问题

### ISSUE THREAD

**Issue by codingiran** [Tencent/QMUI_iOS#1149]
**Bug 表现**

如果在给 ```QMUIImagePreviewView``` 设置 ```videoPlayerItem ```之前，首先设置 ```image ```作为其封面图，则可能导致视频播放视图 ```QMUIZoomImageVideoPlayerView```  ```frame``` 计算错误，如下图：

**截图**
![image](https://user-images.githubusercontent.com/11780294/99770682-d2d5e080-2b42-11eb-9ac0-663f0eca4e1f.png)

**如何重现**

[Demo 复现 密码: m7w8 ](https://pan.baidu.com/s/1huAazZXSIb58uso2BXOtsQ)

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 14.2]
 - Xcode 版本: [Xcode 12.2]
 - QMUI 版本: [4.2.1]

**Comment by MoLice** [comment]
QMUIZoomImageView 在 image/livePhoto/videoPlayerItem 三种内容之间切换时没有清空其他内容，导致缩放错误。
已修复，请等待新版本发布。在此之前可以在 set videoPlayerItem 之前手动 set image = nil。

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
