### ISSUE TITLE
QMUIAlertController 无法显示

### ISSUE THREAD

**Issue by chenfengfeng** [Tencent/QMUI_iOS#1151]
**Bug 表现**
我们的app最低版本为13，启用了SceneDelegate，使用QMUIAlertController的showWithAnimated方法会导致无法弹出

**截图**
```
        let sheet = QMUIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        let uid = viewModel.videoList[self.currentIndex].ownerId
        sheet.addAction(QMUIAlertAction(title: "Report", style: .destructive, handler: { (_, _) in
                
         }))
        sheet.addAction(QMUIAlertAction(title: "Cancel", style: .cancel, handler: nil))
        sheet.showWith(animated: true)
```

**如何重现**
每次都可以重现

**预期的表现**
正常情况下，应该是直接弹出

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 14.2]
 - Xcode 版本: [Xcode 12.2]
 - QMUI 版本: [4.2.1]

**Comment by MoLice** [comment]
重复 issue：https://github.com/Tencent/QMUI_iOS/issues/766

如非必要，请不要使用 SceneDelegate。
如果一定需要使用 SceneDelegate，目前 QMUI 与 UIWindow 有关的组件、方法均无法使用，涉及到的接口修改较多，目前尚未安排到版本计划里。
