### ISSUE TITLE
点击QMUITextView卡顿-Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]

### ISSUE THREAD

**Issue by pengjinning** [Tencent/QMUI_iOS#1152]
**Bug 表现**
点击QMUITextView卡顿
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]
PID: 98323, TID: 21836141, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   QMUIKit                             0x00000001030fc12c __70+[UITraitCollection(QMUI) _qmui_overrideTraitCollectionMethodIfNeeded]_block_invoke_3 + 140
5   UIKitCore                           0x000000019487ab20 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8698656
6   UIKitCore                           0x000000019487ae5c 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8699484
7   UIKitCore                           0x0000000194844488 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8475784
8   libdispatch.dylib                   0x000000010347bdb8 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x000000010347d5fc _dispatch_client_callout + 16
10  libdispatch.dylib                   0x000000010348f2bc _dispatch_root_queue_drain + 788
11  libdispatch.dylib                   0x000000010348fa48 _dispatch_worker_thread2 + 152
12  libsystem_pthread.dylib             0x00000001d7b64568 _pthread_wqthread + 212
13  libsystem_pthread.dylib             0x00000001d7b67874 start_wqthread + 8
2020-11-26 14:46:55.908216+0800 qmuidemo[98323:21836141] [reports] Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]
PID: 98323, TID: 21836141, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   QMUIKit                             0x00000001030fc12c __70+[UITraitCollection(QMUI) _qmui_overrideTraitCollectionMethodIfNeeded]_block_invoke_3 + 140
5   UIKitCore                           0x000000019487ab20 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8698656
6   UIKitCore                           0x000000019487ae5c 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8699484
7   UIKitCore                           0x0000000194844488 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8475784
8   libdispatch.dylib                   0x000000010347bdb8 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x000000010347d5fc _dispatch_client_callout + 16
10  libdispatch.dylib                   0x000000010348f2bc _dispatch_root_queue_drain + 788
11  libdispatch.dylib                   0x000000010348fa48 _dispatch_worker_thread2 + 152
12  libsystem_pthread.dylib             0x00000001d7b64568 _pthread_wqthread + 212
13  libsystem_pthread.dylib             0x00000001d7b67874 start_wqthread + 8
2020-11-26 14:47:09.564786+0800 qmuidemo[98323:21836242] XPC connection interrupted
2020-11-26 14:47:18.989588+0800 qmuidemo[98323:21835640] -[QMUINavigationController handleInteractivePopGestureRecognizer:]:396 | QMUILogLevelDefault | QDNavigationController | 执行手势返回

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/1288209/100316959-710bef80-2ff6-11eb-9af1-84ef78f97b6f.png)

**如何重现**
1. 运行Demo
2. 点击进入QMUITextView
3. 点击Textview

**预期的表现**
界面流畅

**其他信息**
 - 设备: [真机]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.0]
 - QMUI 版本: [4.2.1]

**Comment by pengjinning** [comment]
直接运行 QMUIDemo

**Comment by wangbinji** [comment]
同样遇到了这个问题

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/100341109-1931b080-3017-11eb-8019-15e349865e59.png)

![image](https://user-images.githubusercontent.com/1190261/100341148-26e73600-3017-11eb-93b7-dfed4be0b14e.png)

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 优化该问题。
