### ISSUE TITLE
QMUITableViewCell 修改detaiTextLabel的宽度没有变化

### ISSUE THREAD

**Issue by nouslove** [Tencent/QMUI_iOS#1153]
**Bug 表现**
问题的具体描述
使用QMUITableViewCell作为cell的样式，style为UITableViewCellStyleValue1， 修改detaiTextLabel的宽度为200，最后呈现出来的效果是detaiTextLabel的宽度为字体长度
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

代码如下：
CGRect rect = cell.detailTextLabel.frame;
rect.size.width = 200.f;
cell.detailTextLabel.frame = rect;

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现
cell.detailTextLabel 的宽度应该为200
**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by fanyuecheng** [comment]
。。。肯定的啊，`layoutSubviews`就是这么写的

**Comment by nouslove** [comment]
> 。。。肯定的啊，`layoutSubviews`就是这么写的

那是否可以修改detailtextlabel的宽度

**Comment by fanyuecheng** [comment]
要么自定义 要么继承它 重写layoutSubviews

**Comment by nouslove** [comment]
> 要么自定义 要么继承它 重写layoutSubviews
好的谢谢
