### ISSUE TITLE
QMUIAlertController的bug

### ISSUE THREAD

**Issue by firenessZX** [Tencent/QMUI_iOS#1154]
**Bug 表现**

在使用父子控制器嵌套时，在子视图控制器中使用QMUIAlertController，present出来的是纯白的页面。
**截图**

![IMG_0236](https://user-images.githubusercontent.com/15721984/100833186-6513a800-34a4-11eb-98c3-e526cfb28d39.PNG)
**其他信息**
 - 设备: iPhone6s
 - iOS 版本: iOS11.4
 - Xcode 版本: Xcode12.2
 - QMUI 版本: 4.2.0

**Comment by MoLice** [comment]
无法重现，请提供详细信息再 reopen issue。
