### ISSUE TITLE
继承QMUICommonTableViewController配合Storyboard使用,4.2.1崩溃

### ISSUE THREAD

**Issue by hootigger** [Tencent/QMUI_iOS#1156]
**Bug 表现**
问题的具体描述
bug现象和 #1133  一样.

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. 先使用4.2 之前版本,创建一个继承QMUICommonTableViewController类,并在Sb中拖入tableView控件,设置类QMUITableView,并连线.
2. 更新到4.2.1便可复现
可以稳定复现.
在Podfile使用4.13正常,切换4.21出现该bug
[demo地址](https://github.com/hootigger/QMUIKit-TableView-Case.git)

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by hootigger** [comment]
暂时解决办法.
在sb连线属性tv,并在initTableView中赋值.
ps: 之前是可以直接连线到 QMUICommonTableViewController的 tableView属性的
```
@IBOutlet weak var tv: QMUITableView!

override func initTableView() {
        self.tableView = tv
}
```

**Comment by MoLice** [comment]
使用 Storyboard 的情况，系统在 loadView 里会主动调用 setTableView: 去给 tableView 赋值，此时正处于 loadView 过程中，而 setTableView: 内部又会调用 self.view 重新触发 loadView，导致死循环。

已修复该问题，请等待新版本发布，在此之前你可以将以下代码替换本地的 QMUICommonTableViewController 同名方法：
```objc
- (void)setTableView:(__kindof QMUITableView *)tableView {
    if (_tableView != tableView) {
        if (_tableView) {
            // 这里不用移除 delegate、dataSource，因为原本的值也不一定是指向 self，而且可能是个 QMUIMultipleDelegate，反正这两个属性都是 weak 的
            if (self.isViewLoaded && _tableView.superview == self.view) {
                [_tableView removeFromSuperview];
            }
            if (self._qmuiTableViewObserver) {
                [_tableView removeObserver:self._qmuiTableViewObserver forKeyPath:@"contentInset"];
            }
        }
        
        _tableView = tableView;
        [_tableView registerClass:[QMUITableViewHeaderFooterView class] forHeaderFooterViewReuseIdentifier:QMUICommonTableViewControllerSectionHeaderIdentifier];
        [_tableView registerClass:[QMUITableViewHeaderFooterView class] forHeaderFooterViewReuseIdentifier:QMUICommonTableViewControllerSectionFooterIdentifier];
        
        if (@available(iOS 11, *)) {
        } else {
            /**
             *  监听 contentInset 的变化以及时更新 emptyView 的布局，详见 layoutEmptyView 方法的注释。
             *  iOS 11 之前用一个对象来处理，避免把 observeValueForKeyPath:ofObject:change:context: 实现在 viewController 里，子类重写时容易遗漏调用 super。
             *  iOS 11 及之后使用 UIScrollViewDelegate 的 scrollViewDidChangeAdjustedContentInset: 来监听。
             */
            if (!self._qmuiTableViewObserver) {
                self._qmuiTableViewObserver = [[_QMUITableViewObserver alloc] init];
                self._qmuiTableViewObserver.viewController = self;
            }
            [_tableView addObserver:self._qmuiTableViewObserver forKeyPath:@"contentInset" options:NSKeyValueObservingOptionOld context:nil];
        }
        
        // 从 nib 初始化的界面，loadView 里 tableView 已经被加到 self.view 上了，但此时 loadView 尚未结束，所以 isViewLoaded 为 NO。这种场景不需要自己 addSubview，也不应该去调用 self.view 触发 loadView
        // https://github.com/Tencent/QMUI_iOS/issues/1156
        if (tableView.superview && self.nibName && !self.isViewLoaded) {
        } else {
            // 触发 loadView
            [self.view addSubview:_tableView];
        }
    }
}
```

**Comment by hootigger** [comment]
@MoLice 好的,谢谢,现在可以正常工作了.
另外还有一个问题想问下.
```
@property(nonatomic, strong, null_resettable) IBOutlet __kindof QMUITableView *tableView;
```
这个`__kindof`貌似和`IBOutlet`不兼容,加完这个`__kindof`导致Storyboard中无法;连线了.
![连线](https://user-images.githubusercontent.com/23418191/102057389-cc2c4780-3e28-11eb-9591-a94c93a4ac32.png)
若是新版需要配合Storyboard开发,暂时删除 __kindof  ,就可以在Storyboard中连线.
![未删除__kindof](https://user-images.githubusercontent.com/23418191/102057973-c125e700-3e29-11eb-84ad-6dd6a8f36eb4.png)
![删除__kindof](https://user-images.githubusercontent.com/23418191/102058009-d00c9980-3e29-11eb-9280-d39c5f17e163.png)
不知道有什么好的解决办法没?

**Comment by MoLice** [comment]
IBOutlet 与 __kindof 搭配使用带来的问题本应是 Xcode 要去解决的问题，QMUI 在下个版本会对此做一些简单优化，但不保证后续所有这种场景也会相应优化。

**Comment by hootigger** [comment]
ok,再次感谢,问题已解决.

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
