### ISSUE TITLE
4.2.1版本在iOS14.0系统仍然存在Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]

### ISSUE THREAD

**Issue by hoonblood** [Tencent/QMUI_iOS#1159]
<img width="1299" alt="企业微信截图_c734f3ef-fefd-4cb3-87c7-15574a9b088b" src="https://user-images.githubusercontent.com/26473436/101139083-fd985c80-364b-11eb-818c-5d3d092bbc17.png">

**Comment by hoonblood** [comment]
从代码上分析也还是存在UITraitCollection *traitCollection = originSelectorIMP(selfObject, originCMD);在子线程中访问的：
<img width="1395" alt="企业微信截图_508d3146-b92e-425e-bfe4-27e04dc5df1a" src="https://user-images.githubusercontent.com/26473436/101139234-35070900-364c-11eb-954e-c046c21cc6b3.png">

**Comment by hoonblood** [comment]
经过自测，建议修改如下：
<img width="752" alt="企业微信截图_ada994f1-f9b0-4b82-be05-5026aa11ec2d" src="https://user-images.githubusercontent.com/26473436/101139526-a1820800-364c-11eb-8ea6-d2a83553b812.png">

**Comment by MoLice** [comment]
这样修改对 QMUI 自身逻辑没影响，但可能影响系统在子线程访问 UIWindow.traitCollection 的逻辑，暂不采纳。

**Comment by hoonblood** [comment]
> 这样修改对 QMUI 自身逻辑没影响，但可能影响系统在子线程访问 UIWindow.traitCollection 的逻辑，暂不采纳。

能不能具体讨论一下呢，因为我只是在子线程dispatch_sync一个任务到主线程拿到UIWindow.traitCollection就可以了呀。

**Comment by ziecho** [comment]
> > 这样修改对 QMUI 自身逻辑没影响，但可能影响系统在子线程访问 UIWindow.traitCollection 的逻辑，暂不采纳。
> 
> 能不能具体讨论一下呢，因为我只是在子线程dispatch_sync一个任务到主线程拿到UIWindow.traitCollection就可以了呀。

这种改法会导致本来在子线程可以做完的时候，需要暂时卡准线程，等待  Main Thread Runloop 结束后，才可以继续，这可能会影响系统的一些时机，举个例子，系统发了一个通知，要求 app 从 dark 变成 light，此时主线程收到通知后会把 app 的样式更新为 light，也就是 curStyle = light，但是子线程如果比主线程先收到了，之后后他会去做一个判断，if curStyle == A  then，那么 sync 后他就会拿到不一样的结果。

说回告警本身问题，Main Thread Checker 的原理是在启动的时候替换相关方法的实现为 Main Thread Checker 自身的 trampoline，触发相关方法时会先在 trampoline 中实现线程检测逻辑并告警，所以这里唯一可行的屏蔽方法就是获取原始的 IMP 实现，并直接调用从而绕过 Main Thread Checker, 但是 QMUI 在 +load 到时候已经晚于这个时机，无法很方便地获取原始的实现方法，所以一直没有解决该问题，不过我们目前已经找到了解决该问题的方法，请关注近期更新。

**Comment by codingiran** [comment]
升级到 QMUI 4.2.3 又出现了 -[UIWindow traitCollection] must be used from main thread only 的问题
4.2.2 没有此问题 @ziezheng @ziecho

**Comment by MoLice** [comment]
> 升级到 QMUI 4.2.3 又出现了输入框第一次输入时出现 -[UIWindow traitCollection] must be used from main thread only 警告
> 4.2.2 没有此问题 @ziezheng @ziecho
> 
> ![image](https://user-images.githubusercontent.com/11780294/115544561-52740100-a2d5-11eb-832a-6c4d985d7444.png)

@codingiran 已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 优化该问题。
