### ISSUE TITLE
QMUIPieProgressView使用约束布局时与预期不一致

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1163]
**Bug 表现**
QMUIPieProgressLayer只重写了`- (void)setFrame:(CGRect)frame`来设置圆角，但是QMUIPieProgressView使用约束布局时，调用`- (void)setFrame:(CGRect)frame`方法时宽高不一定是最终的宽高，而调用`- (void)setBounds:(CGRect)bounds`时会得到正确的宽高，所以会导致与预期不一致的问题

**截图**
<img width="494" alt="图片" src="https://user-images.githubusercontent.com/22904757/102029389-4d63ea00-3de9-11eb-90c4-4eeafba99e76.png">

**如何重现**
1. QMUIPieProgressView使用约束布局来设置宽高，初始化时不设置宽高

**预期的表现**
使用约束布局时需要符合预期

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 14.1]
 - Xcode 版本: [Xcode 12.1]
 - QMUI 版本: [4.2.1]

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
