### ISSUE TITLE
关于tabbar透明的问题

### ISSUE THREAD

**Issue by JeankyWang** [Tencent/QMUI_iOS#1164]
**Bug 表现**
问题的具体描述
导入QMUI_iOS后，设置tabbar的背景图为透明背景，但是不起作用，tabar的背景依然是系统默认的。
代码如下：
UIImage *img = [UIImage qmui_imageWithColor:[UIColor qmui_colorWithHexString:@"#FF7076"]
                                           size:CGSizeMake(Screen_Width, TabBarHeight) cornerRadiusArray:@[@36, @0, @0, @36]];
    UITabBar *bar = [UITabBar appearance];
    [bar setTranslucent:YES];
//    [bar setBarStyle:UIBarStyleBlack];
    [bar setBackgroundImage: img];
    [bar setShadowImage:[UIImage qmui_imageWithColor:UIColor.clearColor]];
    
    UITabBarController *tab = [[UITabBarController alloc] init];
    UIViewController *vc = [UIViewController new];
    vc.view.backgroundColor = UIColor.orangeColor;
    vc.title = @"abc";
    tab.viewControllers = @[vc];
    self.window.rootViewController = tab;
如果设置背景图为一个圆角图片，圆角处背景依然是系统默认色而不是透明色；我改如何设置才会出现透明背景的tabar？
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/7403509/102294289-f0e90200-3f83-11eb-8662-0ca8ae5a9dbe.png)
<img width="638" alt="WeChat94f7bc9ff95d23b98f3b442d90891007" src="https://user-images.githubusercontent.com/7403509/102294445-48876d80-3f84-11eb-875b-4d6dd14837f1.png">

**Comment by MoLice** [comment]
你确定不导入 QMUI 就是正常的？

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/pull/1165#issuecomment-745936358
