### ISSUE TITLE
QMUIConsole 在展示大量 log 时性能较低

### ISSUE THREAD

**Issue by fabcz** [Tencent/QMUI_iOS#1166]
**Bug 表现**
问题的具体描述
如题，最终定位到的原因是 UITextView 频繁设置超长文本导致 CPU 暴涨而卡顿

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
注释掉 QMUIConsole 293 行  self.textView.attributedText = string; 就不卡了

**如何重现**
1. 在 QDTableViewHeaderFooterViewController 的 scrollViewDidScroll 加一行打印，（为什么是这里？因为 demo 只有这里有实现 scrollViewDidScroll）
`[QMUIConsole log:@"文本长一点不用划得那么累"];`
2. 来回频繁滑动列表 10 秒以上（log 文本长一点不用划那么久），会发现列表开始有明显卡顿（FPS 开始低于 50），而且越来越卡（因为 logString 越来越长）
3. 项目有个 FPS 文本监测到掉帧，简易集成代码如下
[QDTableViewHeaderFooterViewController.m.zip](https://github.com/Tencent/QMUI_iOS/files/5701316/QDTableViewHeaderFooterViewController.m.zip)
![image](https://user-images.githubusercontent.com/18094291/102323506-8784e580-3fbb-11eb-99cd-7f0b7c19498f.png)

**定位问题**
1. 经排查定位到导致掉帧的代码是 QMUIConsole 293 行 self.textView.attributedText = string;
2. 经尝试多种设置方案均无改善，所以这算是 UITextView 设置超长文本性能问题？
3. 将 TextView 替换成 TableView 就回归如丝般顺滑了，简易替换代码如下，并无处理 search、highlight 等状态
[QMUIConsoleViewController.m.zip](https://github.com/Tencent/QMUI_iOS/files/5701321/QMUIConsoleViewController.m.zip)
![image](https://user-images.githubusercontent.com/18094291/102323444-74721580-3fbb-11eb-86c4-f80002d23db3.png)

**预期的表现**
正常情况下，应该是什么表现
看是否有更好的方式解决频繁 log 的问题

**其他信息**
 - 设备: [iPhone XR]
 - iOS 版本: [iOS 14.2]
 - Xcode 版本: [Xcode 12]
 - QMUI 版本: [4.2.1]

**Comment by MoLice** [comment]
已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 优化该问题，改为用 `UITableView` 实现，如仍有性能问题，请新开 issue 反馈，谢谢。
