### ISSUE TITLE
QMUIConsole对使用SceneDelegate项目的适配

### ISSUE THREAD

**Issue by BB-fat** [Tencent/QMUI_iOS#1167]
**现存问题或期望目标**
在使用`SceneDelegate`的项目中无法使用`QMUIConsole`相关功能，因为`AppDelegate`不再持有`window`对象。
建议修改`QMUIConsole`使其可以设置显示`ConsoleWindow`的`UIScene`。

**Comment by MoLice** [comment]
UIScene 问题由 #766 统一跟进。
