### ISSUE TITLE
iPad上 QMUIConsole 其他window无法点击

### ISSUE THREAD

**Issue by JzwOnly** [Tencent/QMUI_iOS#1169]
**Bug 表现**
iPad上 QMUIConsole 遮挡整个视图其他内容无法点击 
iPhone上正常

**截图**
QMUIConsole.m-188 qmui_hitTestBlock iPad上 originalView和weakSelf.consoleWindow对象不一致
--------------------------------------------------------------------------------------
iPad
(lldb) po weakSelf.consoleWindow
<UIWindow: 0x10781fc50; frame = (0 0; 1024 1366); gestureRecognizers = <NSArray: 0x280e4cde0>; layer = <UIWindowLayer: 0x2800e67e0>>

(lldb) po originalView
<UIView: 0x1054af2f0; frame = (0 0; 1024 1366); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x28000bdc0>>
--------------------------------------------------------------------------------------
iPhone
(lldb) po weakSelf.consoleWindow
<UIWindow: 0x154b0f420; frame = (0 0; 375 812); gestureRecognizers = <NSArray: 0x281a7bba0>; layer = <UIWindowLayer: 0x28148b860>>

(lldb) po originalView
<UIWindow: 0x154b0f420; frame = (0 0; 375 812); gestureRecognizers = <NSArray: 0x281a7bba0>; layer = <UIWindowLayer: 0x28148b860>> 
--------------------------------------------------------------------------------------

**如何重现**
1. 使用iPad 进入Components->QMUIConsole -> 打印一条日志
2. 页面无法返回 页面按钮不响应

**预期的表现**

**其他信息**
 - 设备: iPad Pro 
 - iOS 版本: iOS 13.5.1
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.2.1]

**Comment by MoLice** [comment]
无法重现，以下是录屏：

https://user-images.githubusercontent.com/1190261/102864162-9e6d8100-446e-11eb-9b74-ab6d87909bcc.mov

**Comment by MoLice** [comment]
当显示 QMUIConsole 时，点击空白区域，consoleViewController hitTest 会 return nil，从而将事件传递给 window，再由 window hitTest return  nil 来把事件传递给 UIApplication.delegate.window。但在 iPad 12-inch 里，当 consoleViewController hitTest return nil 后，事件会错误地传递给 consoleViewController.view.superview（而不是 consoleWindow），不清楚原因，暂时做一下保护。内部版本已修复，请等待新版本发布，在此之前你可以用以下代码替换本地 QMUI 同名方法：
```objc
- (void)initConsoleWindowIfNeeded {
    if (!self.consoleWindow) {
        self.consoleWindow = [[UIWindow alloc] init];
        self.consoleWindow.backgroundColor = nil;
        if (QMUICMIActivated) {
            self.consoleWindow.windowLevel = UIWindowLevelQMUIConsole;
        } else {
            self.consoleWindow.windowLevel = 1;
        }
        self.consoleWindow.qmui_capturesStatusBarAppearance = NO;
        __weak __typeof(self)weakSelf = self;
        self.consoleWindow.qmui_hitTestBlock = ^__kindof UIView * _Nonnull(CGPoint point, UIEvent * _Nonnull event, __kindof UIView * _Nonnull originalView) {
            // 当显示 QMUIConsole 时，点击空白区域，consoleViewController hitTest 会 return nil，从而将事件传递给 window，再由 window hitTest return  nil 来把事件传递给 UIApplication.delegate.window。但在 iPad 12-inch 里，当 consoleViewController hitTest return nil 后，事件会错误地传递给 consoleViewController.view.superview（而不是 consoleWindow），不清楚原因，暂时做一下保护
            // https://github.com/Tencent/QMUI_iOS/issues/1169
            return originalView == weakSelf.consoleWindow || originalView == weakSelf.consoleViewController.view.superview ? nil : originalView;
        };
        
        self.consoleViewController = [[QMUIConsoleViewController alloc] init];
        self.consoleWindow.rootViewController = self.consoleViewController;
    }
}
```

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
