### ISSUE TITLE
输入框 QMUITextField / QMUITextView 字数限制导致的 crash

### ISSUE THREAD

**Issue by YJPizazz** [Tencent/QMUI_iOS#1170]
**Bug 表现**
类似这个bug：https://github.com/Tencent/QMUI_iOS/issues/377
但操作不一样，导致这个issues/377的修复没有覆盖到

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

崩溃的视频如下：

https://user-images.githubusercontent.com/16317734/103328493-0ede5880-4a94-11eb-9eed-94df74f5b69f.mov

**如何重现**
1、复制一串长文字。
2、输入框输入最大字数的文字。
3、长按选中最后三个文字。
4、点击粘贴。
5、摇一摇，显示撤回弹窗。
6、点击撤回，崩溃。

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone7]（应该所有设备都会）
 - iOS 版本: [iOS 14.0]（应该所有系统都会）
 - Xcode 版本: [Xcode 12.0.1]
 - QMUI 版本: [4.2.1]

修复方式：
修改QMUITextField和QMUITextView的源码，修改截图如下
![WX20201230-114547](https://user-images.githubusercontent.com/16317734/103328647-95933580-4a94-11eb-86b2-ff0b651a96e3.png)
![WX20201230-114711](https://user-images.githubusercontent.com/16317734/103328683-c5dad400-4a94-11eb-8368-81022cbfb9d3.png)
如截图所示，注释掉相关代码即可。

修复后仍然有问题，如下：
虽然如上注释掉相关代码，即可修复，但还是会有问题，如下：
1、由于QMUI的delegate是一对多的。
2、如果我自己的控制器代码也实现了输入框的代理方法：shouldChangeCharactersInRange
![WX20201230-115133](https://user-images.githubusercontent.com/16317734/103328867-6a5d1600-4a95-11eb-95e3-c0b9919b9001.png)

3、这时，通过“如何重现”的步骤，同样也会崩溃。
4、所以，自己实现的代理方法里面，也是加防护才行，代码如下：
![WX20201230-115322](https://user-images.githubusercontent.com/16317734/103328935-a4c6b300-4a95-11eb-89e5-638129580f47.png)

**Comment by ziecho** [comment]
感谢反馈，下个版本将对该场景做保护

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
