### ISSUE TITLE
侧滑手势导致的崩溃

### ISSUE THREAD

**Issue by gaoruiqing187** [Tencent/QMUI_iOS#1171]
id target = self.interactivePopGestureRecognizer.delegate;

    // 创建全屏滑动手势，调用系统自带滑动手势的target的action方法
    UIPanGestureRecognizer *pan = [[UIPanGestureRecognizer alloc] initWithTarget:target action:@selector(handleNavigationTransition:)];

    // 设置手势代理，拦截手势触发
    pan.delegate = self;

    // 给导航控制器的view添加全屏滑动手势
    [self.view addGestureRecognizer:pan];
    // 禁止使用系统自带的滑动手势
    self.interactivePopGestureRecognizer.enabled = NO;
[我在自定义的导航控制器中写了这些代码,侧滑的时候就会崩溃]

<img width="658" alt="image" src="https://user-images.githubusercontent.com/14845602/103392273-fe8fb180-4b57-11eb-9453-9cb46b0e5dc2.png">

**Comment by gaoruiqing187** [comment]
2020-12-31 11:03:58.458348+0800 CallTheOwner[5454:129271] -[_QMUINavigationInteractiveGestureDelegator handleNavigationTransition:]: unrecognized selector sent to instance 0x6000035fc830
2020-12-31 11:03:58.466567+0800 CallTheOwner[5454:129271] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_QMUINavigationInteractiveGestureDelegator handleNavigationTransition:]: unrecognized selector sent to instance 0x6000035fc830'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c91fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	5   UIKitCore                           0x00007fff47c3a347 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 44
	6   UIKitCore                           0x00007fff47c4333d _UIGestureRecognizerSendTargetActions + 109
	7   UIKitCore                           0x00007fff47c409ea _UIGestureRecognizerSendActions + 298
	8   UIKitCore                           0x00007fff47c3fd17 -[UIGestureRecognizer _updateGestureForActiveEvents] + 757
	9   UIKitCore                           0x00007fff47c31eda _UIGestureEnvironmentUpdate + 2706
	10  UIKitCore                           0x00007fff47c3140a -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 467
	11  UIKitCore                           0x00007fff47c3117f -[UIGestureEnvironment _updateForEvent:window:] + 200
	12  UIKitCore                           0x00007fff480d04b0 -[UIWindow sendEvent:] + 4574
	13  UIKitCore                           0x00007fff480ab53b -[UIApplication sendEvent:] + 356
	14  UIKitCore                           0x00007fff4812c71a __dispatchPreprocessedEventFromEventQueue + 6847
	15  UIKitCore                           0x00007fff4812f1e0 __handleEventQueueInternal + 5980
	16  CoreFoundation                      0x00007fff23bd4471 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	17  CoreFoundation                      0x00007fff23bd439c __CFRunLoopDoSource0 + 76
	18  CoreFoundation                      0x00007fff23bd3b74 __CFRunLoopDoSources0 + 180
	19  CoreFoundation                      0x00007fff23bce87f __CFRunLoopRun + 1263
	20  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	21  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	22  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	23  CallTheOwner                        0x00000001055d472d main + 125
	24  libdyld.dylib                       0x00007fff5227ec25 start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by jiasongs** [comment]
target应该用self.qmui_interactivePopGestureRecognizerDelegate
