### ISSUE TITLE
官网经常打不开

### ISSUE THREAD

**Issue by rzshuo** [Tencent/QMUI_iOS#1172]
官网经常打不开，翻墙也不行。现在部署在境外服务器么，挪到腾讯云，搞个国内站吧！一个公司的不会还收费吧。

**Comment by codingiran** [comment]
> 官网经常打不开，翻墙也不行。现在部署在境外服务器么，挪到腾讯云，搞个国内站吧！一个公司的不会还收费吧。

"一个公司的不会还收费吧"
恭喜你答对了！

**Comment by MoLice** [comment]
现在应该不会了，充钱充到位了
