### ISSUE TITLE
QMUIKeyboardManager.handleKeyboardNotification 回调出错

### ISSUE THREAD

**Issue by dujj** [Tencent/QMUI_iOS#1173]
**Bug 表现**
iOS14 在设置->辅助功能->动态效果->减弱动态效果->首选交叉淡出过渡效果打开
QMUIKeyboardManager.handleKeyboardNotification ，这个方法，会回调出错，把hiden的事件，调用show

**截图**
https://user-images.githubusercontent.com/9443889/103602973-59564e00-4f48-11eb-8046-802a1c501af2.MP4

**如何重现**
1. QMUI例子工程， components , QMUIKeyboardManager
2. 按视频步骤操作，即可复现

**预期的表现**
键盘收起正常

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 14.0]
 - Xcode 版本: [Xcode 12.0]
 - QMUI 版本: [4.2.1]

**Comment by MoLice** [comment]
之前没兼容这种辅助功能，感谢指出。内部已修复，请等待新版发布，在此之前你可以先修改本地的 QMUIKeyboardManager.m，将如下代码替换同名方法：
```objc
+ (CGFloat)visibleKeyboardHeight {
    UIView *keyboardView = [self keyboardView];
    UIWindow *keyboardWindow = keyboardView.window;
    if (!keyboardView || !keyboardWindow) {
        return 0;
    } else {
        // 开启了系统的“设置→辅助功能→动态效果→减弱动态效果→首选交叉淡出过渡效果”后，键盘动画不再是 slide，而是 fade，此时应该用 alpha 来判断
        // https://github.com/Tencent/QMUI_iOS/issues/1173
        if (keyboardView.alpha <= 0) {
            return 0;
        }
        
        CGRect visibleRect = CGRectIntersection(CGRectFlatted(keyboardWindow.bounds), CGRectFlatted(keyboardView.frame));
        if (CGRectIsValidated(visibleRect)) {
            return CGRectGetHeight(visibleRect);
        }
        return 0;
    }
}
```

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
