### ISSUE TITLE
您好,有考虑出一版Swift的使用教程吗?

### ISSUE THREAD

**Issue by AndersonCodeArt** [Tencent/QMUI_iOS#1174]
很喜欢QMUI,但是新手未接触过OC的情况下,使用Swift来集成QMUI遇到很多问题.希望能有Swift的相关教程可供学习,谢谢

**Comment by MoLice** [comment]
暂不考虑，这种问题应该和 QMUI 无关，社区对于 Swift 项目接入 OC 框架应该有很多资料可以查找。
