### ISSUE TITLE
QMUIHelper.safeAreaInsetsForDeviceWithNotch在Mac Catalyst上不准确

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1175]
**Bug 表现**
`QMUIHelper.safeAreaInsetsForDeviceWithNotch`在Mac Catalyst上不准确，Mac Catalyst上有个“tool bar”

<img width="961" alt="图片" src="https://user-images.githubusercontent.com/22904757/103862819-bbef4b80-50fa-11eb-9887-4b10a720e215.png">
通过`keyWindow.safeAreaInsets`拿到的结果是
<img width="545" alt="图片" src="https://user-images.githubusercontent.com/22904757/103862443-1805a000-50fa-11eb-9a84-6c7dea88f872.png">

**截图**
如上图

**如何重现**
run in Mac Catalyst

**预期的表现**
QMUIHelper.safeAreaInsetsForDeviceWithNotch在其他平台上也能得到正确的结果

**其他信息**
 - 设备: Mac
 - iOS 版本: [iOS 14.2]
 - Xcode 版本: [Xcode 12.2]
 - QMUI 版本: [4.2.2]

**Comment by MoLice** [comment]
mac 上的 toolbar 也是可以隐藏的，QMUIHelper.safeAreaInsetsForDeviceWithNotch 的设计本意更希望用于“无法动态获取 safeAreaInsets 时不得已才用”的方法，更希望用来表达硬件层面的 safeAreaInsets 信息，所以该方法不修改。

**Comment by lwl-blazer** [comment]
此函数下的UIApplication.sharedApplication.statusBarOrientation
