### ISSUE TITLE
开启 MainThreadChecker 后使用了QMUITheme 可能会导致 directTraitCollectionIMP  EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ziecho** [Tencent/QMUI_iOS#1176]
该问题仅会在 Debug 下，开启 MainThreadChecker 出现，复现步骤如下：
1. 使用 QMUITheme 相关功能
2. 在主窗口创建完毕后，使用 QMUITheme 相关功能，之后创建再一个新的 window，会发现递归调用，最终 crash
QMUI 版本: 4.2.2

![image](https://user-images.githubusercontent.com/16473618/103891476-dfc78700-5124-11eb-9bc6-47a761d0d57c.png)

**Comment by ziecho** [comment]
我们将在下个版本解决改问题，出现这个问题的话，可以先用压缩包内的 UITraitCollection+QMUI.m 覆盖 pod 文件
[UITraitCollection+QMUI.m.zip](https://github.com/Tencent/QMUI_iOS/files/5781518/UITraitCollection%2BQMUI.m.zip)

**Comment by stonetabletsproject** [comment]
info.dli_sname 获取到的是 "<redacted>"，尽管Xcode左侧面板中看到的是 "-[UIWindow traitCollection]"

**Comment by MoLice** [comment]
已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 修复该问题。
