### ISSUE TITLE
UINavigationController 不可见的情况下进行 pop 操作会命中 UINavigationController+QMUI.m 内的 NSAssert

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#1180]
**Bug 表现**
考虑以下伪代码：
```objc
UITabBarController *tabBarController;
tabBarController.viewControllers = @[nav1, nav2, nav3];
tabBarController.selectedIndex = 1;// 当前处于第二个 tab
[nav2 pushViewController:xxx];
[nav2 pushViewController:xxx];
...
// nav2 有若干个 vc
tabBarController.selectedIndex = 0;// tabBar 切到第一个 tab，此时 nav2 不可见
nav2 popToRootViewController;// 这里会命中 NSAssert
```

![image](https://user-images.githubusercontent.com/1190261/104360632-5e209080-554c-11eb-803b-66aea79356d2.png)

popToRootViewController、popToViewController 有问题，popViewControllerAnimated 没这个问题。
且仅有 iOS 13 及以下版本的系统有问题，iOS 14 没问题。

该问题的原因是系统在 nav 不可见的时候（**不管是 issue 里的切 tab 场景，或是在 nav 之上又 present 了个新 vc 盖住 nav**）进行这两个 pop 操作，都无法正确 return 被 pop 掉的 viewController，但系统文档里对这一点并没有加以说明，且 iOS 14 没问题，因此暂且视为是旧版本系统的 bug。

出于谨慎考虑，我们不修改系统的这个行为，而是在利用到 return 值的地方自行保护。

**其他信息**
 - iOS 版本: < iOS 14.0
 - QMUI 版本: 4.2.2

**Comment by BinBear** [comment]
现在项目就出现这个问题了，请问一下什么时候能解决呢，项目马上要上线了

**Comment by MoLice** [comment]
不影响上线，NSAssert 本来就只会在 Debug 下生效，这个只是提醒而已。

**Comment by PZXforXcode** [comment]
同遇到这个问题了，求大佬解决下 目前我市屏蔽了NSAssert代码

**Comment by lp380490944** [comment]
臣附议

**Comment by kingstarwmx** [comment]
我这里是present了一个NavigationController A盖在主页面的，然后A再push一个vc B，从B手势返回的时候有时候就到了
NSAssert(result && disappearingViewControllers && disappearingViewControllers.firstObject == result, @"QMUI 认为 popViewController 会成功，但实际上失败了");

**Comment by MoLice** [comment]
@kingstarwmx 按你的描述无法重现，请提供可复现的 Demo。
录屏如下：
https://user-images.githubusercontent.com/1190261/110785836-5d834c80-82a6-11eb-8757-f62660d34a59.mov

**Comment by kingstarwmx** [comment]
> @kingstarwmx 按你的描述无法重现，请提供可复现的 Demo。
> 录屏如下：
> https://user-images.githubusercontent.com/1190261/110785836-5d834c80-82a6-11eb-8757-f62660d34a59.mov

下午专门准备了的，https://github.com/Tencent/QMUI_iOS/issues/1206

**Comment by MoLice** [comment]
已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 修复该问题。

**Comment by TML007** [comment]
> 已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 修复该问题。

iOS14.3还是会命中NSAssert(result && disappearingViewControllers && disappearingViewControllers.firstObject == result, @"QMUI 认为 popViewController 会成功，但实际上失败了");

**Comment by MoLice** [comment]
> > 已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 修复该问题。
> 
> iOS14.3还是会命中NSAssert(result && disappearingViewControllers && disappearingViewControllers.firstObject == result, @"QMUI 认为 popViewController 会成功，但实际上失败了");

请提供 Demo 或案例

**Comment by BinBear** [comment]
iOS14.4 也还是会命中NSAssert(result && disappearingViewControllers && disappearingViewControllers.firstObject == result, @"QMUI 认为 popViewController 会成功，但实际上失败了");
还是没修复成功

**Comment by BinBear** [comment]
侧滑返回的时候就会这样，代码pop或者点击back按钮pop则不会

**Comment by MoLice** [comment]
> 侧滑返回的时候就会这样，代码pop或者点击back按钮pop则不会

你是整个 App 都是这样的表现？

**Comment by BinBear** [comment]
不是，少数几个页面

**Comment by MoLice** [comment]
@BinBear 那你不说明具体的场景是什么、关键代码是什么，这个问题怎么能有人查得出来...

**Comment by BinBear** [comment]
之后我整理一个能复现的demo

**Comment by Wi** [comment]
4.2.3 还是有问题，ios12.1.2

demo ： https://github.com/Wi/QmuiCrashDemo

**Comment by MoLice** [comment]
> 4.2.3 还是有问题，ios12.1.2
> 
> demo ： https://github.com/Wi/QmuiCrashDemo
> 
> https://github.com/Wi/QmuiCrashDemo/blob/main/ScreenRecording_06-11-2021%2014-33-00.MP4
> 
> 重现步骤：
> 
> 1、点击按钮push到新页面（DetailViewController）；
> 2、快速点击DetailViewController左上角返回按钮；
> 3、必现此问题；

@Wi 
该 Demo 的关键是：
1. 使用自定义的返回按钮
2. 转场过程用 animated:NO 无动画显示导航栏

假设导航栏一直显示，此时就算你使用自定义返回按钮，返回按钮的也会在 push 完成后才可以点击。
或者一开始隐藏导航栏，在进入 Detail 时以 animated:YES 的方式显示导航栏，也会在 push 动画完成后，才可以点击自定义的返回按钮。
但由于 1、2同时存在，刚好导致 push 动画尚未结束时，就可以点击到返回按钮。而系统的特性是“前一个转场动画尚未结束时就 pop，则会忽略此次 pop，等转场动画结束后，再重新执行一次 pop”，这就导致命中了 UINavigationController(QMUI) 的 NSAssert。
有两个解决方法：
1. 将 UINavigationController 改为使用 QMUINavigationController，后者会保护这种情况。
2. 将以下代码临时替换你本地的 UINavigationController+QMUI.m 里，hook popViewControllerAnimated: 的相关代码：
    ```objc
    QMUINavigationAction action = selfObject.qmui_navigationAction;
    BOOL willPopActually = selfObject.viewControllers.count > 1 && action == QMUINavigationActionUnknow;// 系统文档里说 rootViewController 是不能被 pop 的，当只剩下 rootViewController 时当前方法什么事都不会做
    ```

**Comment by Wi** [comment]
> > 4.2.3 还是有问题，ios12.1.2
> > demo ： https://github.com/Wi/QmuiCrashDemo
> > https://github.com/Wi/QmuiCrashDemo/blob/main/ScreenRecording_06-11-2021%2014-33-00.MP4
> > 重现步骤：
> > 1、点击按钮push到新页面（DetailViewController）；
> > 2、快速点击DetailViewController左上角返回按钮；
> > 3、必现此问题；
> 
> @Wi
> 该 Demo 的关键是：
> 
> 1. 使用自定义的返回按钮
> 2. 转场过程用 animated:NO 无动画显示导航栏
> 
> 假设导航栏一直显示，此时就算你使用自定义返回按钮，返回按钮的也会在 push 完成后才可以点击。
> 或者一开始隐藏导航栏，在进入 Detail 时以 animated:YES 的方式显示导航栏，也会在 push 动画完成后，才可以点击自定义的返回按钮。
> 但由于 1、2同时存在，刚好导致 push 动画尚未结束时，就可以点击到返回按钮。而系统的特性是“前一个转场动画尚未结束时就 pop，则会忽略此次 pop，等转场动画结束后，再重新执行一次 pop”，这就导致命中了 UINavigationController(QMUI) 的 NSAssert。
> 有两个解决方法：
> 
> 1. 将 UINavigationController 改为使用 QMUINavigationController，后者会保护这种情况。
> 2. 将以下代码临时替换你本地的 UINavigationController+QMUI.m 里，hook popViewControllerAnimated: 的相关代码：
>    ```objc
>    QMUINavigationAction action = selfObject.qmui_navigationAction;
>    BOOL willPopActually = selfObject.viewControllers.count > 1 && action == QMUINavigationActionUnknow;// 系统文档里说 rootViewController 是不能被 pop 的，当只剩下 rootViewController 时当前方法什么事都不会做
>    ```

1、第一种方式目前项目中导航栏是自定义的，不太好直接改成QMUINavigationController；
2、第二种方式，因为我们是用pod管理，所以本地改也不太合适。

-----

1、你们什么时候出新的版本，修复这个问题？
2、按你的第二种将willPopActually相关代码替换后，会击中另外一个断言：
```
NSAssert(!(selfObject.isViewLoaded && selfObject.view.window) || [result isEqualToArray:disappearingViewControllers], @"QMUI 计算得到的 popToViewController 结果和系统的不一致");
```

**Comment by MoLice** [comment]
> > > 4.2.3 还是有问题，ios12.1.2
> > > demo ： https://github.com/Wi/QmuiCrashDemo
> > > https://github.com/Wi/QmuiCrashDemo/blob/main/ScreenRecording_06-11-2021%2014-33-00.MP4
> > > 重现步骤：
> > > 1、点击按钮push到新页面（DetailViewController）；
> > > 2、快速点击DetailViewController左上角返回按钮；
> > > 3、必现此问题；
> > 
> > 
> > @Wi
> > 该 Demo 的关键是：
> > 
> > 1. 使用自定义的返回按钮
> > 2. 转场过程用 animated:NO 无动画显示导航栏
> > 
> > 假设导航栏一直显示，此时就算你使用自定义返回按钮，返回按钮的也会在 push 完成后才可以点击。
> > 或者一开始隐藏导航栏，在进入 Detail 时以 animated:YES 的方式显示导航栏，也会在 push 动画完成后，才可以点击自定义的返回按钮。
> > 但由于 1、2同时存在，刚好导致 push 动画尚未结束时，就可以点击到返回按钮。而系统的特性是“前一个转场动画尚未结束时就 pop，则会忽略此次 pop，等转场动画结束后，再重新执行一次 pop”，这就导致命中了 UINavigationController(QMUI) 的 NSAssert。
> > 有两个解决方法：
> > 
> > 1. 将 UINavigationController 改为使用 QMUINavigationController，后者会保护这种情况。
> > 2. 将以下代码临时替换你本地的 UINavigationController+QMUI.m 里，hook popViewControllerAnimated: 的相关代码：
> >    ```objc
> >    QMUINavigationAction action = selfObject.qmui_navigationAction;
> >    BOOL willPopActually = selfObject.viewControllers.count > 1 && action == QMUINavigationActionUnknow;// 系统文档里说 rootViewController 是不能被 pop 的，当只剩下 rootViewController 时当前方法什么事都不会做
> >    ```
> 
> 1、第一种方式目前项目中导航栏是自定义的，不太好直接改成QMUINavigationController；
> 2、第二种方式，因为我们是用pod管理，所以本地改也不太合适。
> 
> 1、你们什么时候出新的版本，修复这个问题？
> 2、按你的第二种将willPopActually相关代码替换后，会击中另外一个断言：
> 
> ```
> NSAssert(!(selfObject.isViewLoaded && selfObject.view.window) || [result isEqualToArray:disappearingViewControllers], @"QMUI 计算得到的 popToViewController 结果和系统的不一致");
> ```

@Wi 第2点在你提供的 Demo 里并没有问题？我是基于你的 Demo 来修复的。

**Comment by Wi** [comment]
因实际项目中场景更为复杂，我看看能否在demo中完全还原或者复现。

**Comment by Wi** [comment]
你好，什么时候更新版本呢？
我看到3个月没更新东西了，这个库以后还会继续维护吗？

**Comment by MoLice** [comment]
> 你好，什么时候更新版本呢？
> 我看到3个月没更新东西了，这个库以后还会继续维护吗？

老哥，打工赚钱养家第一，开源第二，体谅体谅

**Comment by MoShenGuo** [comment]
> ```objc
> && action == QMUINavigationActionUnknow;
> ```

你好  按照你的第二方法解决 是没有效果的 还是崩溃

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 修复该问题。

**Comment by HeXiuLian** [comment]
RN  goBack  会命中NSAssert，  但实际是可以pop成功的  QMUI(4.7.0),  RN （0.72.5） 怎么修改？
