### ISSUE TITLE
QMUITextView 在placeholder有值的时候sizeThatFits应考虑到

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#1181]
现版本` QMUITextView` 的` sizeThatFits` 方法只考虑了` maximumHeight` ，应把`placeholder`也考虑在内。
```  
- (CGSize)sizeThatFits:(CGSize)size {
    CGSize result = [super sizeThatFits:size];
    CGFloat placeholderBottom = 0;
    if (self.placeholder && !self.text.length) {
        //计算 placeholderLabel 的 frame，给placeholderBottom赋值
        placeholderBottom = ...
    }
    result.height = MIN(MAX(result.height, placeholderBottom), self.maximumHeight);
    return result;
} 
```

**Comment by MoLice** [comment]
<img src="https://user-images.githubusercontent.com/1190261/112731302-5bd9aa00-8f71-11eb-9f82-ad3de5543725.png" width="300" />

已优化，下个版本 placeholder 将会拥有和 text 一样的宽高。

**Comment by MoLice** [comment]
已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 修复该问题。
