### ISSUE TITLE
希望QMUIDialogViewController能增加改变底部按钮字体、颜色的属性

### ISSUE THREAD

**Issue by Mag1cPanda** [Tencent/QMUI_iOS#1182]
当前版本的QMUIDialogViewController底部按钮的颜色和字体无法自定义，只能设置背景颜色，建议增加buttonTitleColor、buttonHighlightedColor、buttonFont三个属性

**Comment by MoLice** [comment]
你可以获取到 button 的引用，直接像普通 UIButton 一样去改它就行了

**Comment by Mag1cPanda** [comment]
试过了，没有用，不过发现了有buttonTitleAttributes这个属性，设置这个就行。
