### ISSUE TITLE
单独定义导航栏颜色在退出APP（非关闭）再进入会失效。

### ISSUE THREAD

**Issue by MathewChen** [Tencent/QMUI_iOS#1185]
**Bug 表现**
当首页的界面单独设置navigationBarBackgroundImage为红色时，home返回界面再回来，导航栏变为了默认的背景色。

**截图**
![正确的颜色](https://user-images.githubusercontent.com/13374278/104979361-0f3c9480-5a3f-11eb-8e62-a5ed57903660.png)
![错误的颜色](https://user-images.githubusercontent.com/13374278/104979365-14014880-5a3f-11eb-9755-e160a006a129.png)
![相关代码1](https://user-images.githubusercontent.com/13374278/104979396-28454580-5a3f-11eb-8b12-cf5f680c8ae9.png)
![相关代码2](https://user-images.githubusercontent.com/13374278/104979413-3004ea00-5a3f-11eb-8fba-9162ef8789f2.png)
![相关代码3](https://user-images.githubusercontent.com/13374278/104979436-3a26e880-5a3f-11eb-926d-6d82ae81f049.png)

**如何重现**
1. 启动APP，导航栏标签正常
2. 返回到手机home界面（不是退出APP，而是按home按钮），然后再返回到APP，导航栏颜色更改。

**预期的表现**
导航栏颜色还是我预先设置的的红色。

**其他信息**
 - 设备: [例如模拟器、iPhone]
 - iOS 版本: [iOS 14.1]
 - Xcode 版本: [Xcode 12.1]
 - QMUI 版本: [4.2.2]

**Comment by MoLice** [comment]
请查看 #839
