### ISSUE TITLE
iOS 12 及以下，在 rootViewController、以 animated:NO 进行的 push/pop 界面，titleViewTintColor 无效

### ISSUE THREAD

**Issue by renyufei8023** [Tencent/QMUI_iOS#1190]
**Bug 表现**
`QMUINavigationControllerDelegate` 里的 `titleViewTintColor` 在 iOS 12 下如果应用于 rootViewController、被 animated:NO push/pop 出来的界面里会失效。
不管是 QMUINavigationTitleView 或系统 title 都会。

**其他信息**
 - 设备: All
 - iOS 版本: iOS 12 及以下
 - QMUI 版本: 4.2.2

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/111277737-bb7fad80-8673-11eb-8917-2b8736587495.png)

按照 issue 提供的信息，无法重现该问题。如有需要，请验证 issue 描述的准确度，补充必要信息后重新 open。

**Comment by MoLice** [comment]
对于 iOS 12，在 QMUI 里 `viewWillAppear:` 时会调用 `renderNavigationTitleStyleAnimated` 来更新 titleView 的样式，需要满足条件：
<img src="https://user-images.githubusercontent.com/1190261/111810753-521cca80-8911-11eb-8be2-631aaab222cb.png" width="600" />

但对于 rootViewController，或者被以 animated:NO 方式 push/pop 过去的界面，他们的 push/pop 动作会立即完成，然后才开始走到 viewWillAppear:，这意味着截图里的 navigationAction 在此时是 Unknow（因为 push/pop completed 之后就会转为 Unknow），由于不满足条件，所以无法执行 `renderNavigationTitleStyleAnimated`。

新版本将会修复该问题，在此之前你可以将本地代码的 `qmui_navigationAction >= QMUINavigationActionWillPush` 改为 `qmui_navigationAction >= QMUINavigationActionUnknow`。

**Comment by MoLice** [comment]
已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 修复该问题。
