### ISSUE TITLE
UIView+QMUIBorder的方法交换在子线程操作UI的crash

### ISSUE THREAD

**Issue by Jude2719502607** [Tencent/QMUI_iOS#1191]
**Bug 表现**
问题的具体描述
全局断点崩溃在UIView+QMUIBorder.m的load方法里，控制台提示子线程操作UI，堆栈最后崩溃在方法交换里。
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![截屏2021-01-26 12 19 22](https://user-images.githubusercontent.com/34996712/105802874-129fc500-5fd7-11eb-850e-157ca264093b.png)
![截屏2021-01-26 12 21 45](https://user-images.githubusercontent.com/34996712/105802877-15021f00-5fd7-11eb-9110-6f0ad8012b2e.png)

**如何重现**
1. ...[self showEmptyViewWithImage:UIImageMake(@"erro_img") text:@"" detailText:@"咦，网络断片了～" buttonTitle:@"刷新" buttonAction:@selector(reload:)];

2. ...点击事件触发selector

**预期的表现**
正常情况下，应该是什么表现:正常执行reload方法
尝试在这里回到主线程进行方法交换，问题解决：
![截屏2021-01-26 12 25 36](https://user-images.githubusercontent.com/34996712/105800407-9bb3fd80-5fd1-11eb-940c-3e3f683e6e5d.png)

修改后代码如下：
OverrideImplementation([UIView class], @selector(layoutSublayersOfLayer:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void)) {
            return ^(UIView *selfObject, CALayer *firstArgv) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    // call super
                    void (*originSelectorIMP)(id, SEL, CALayer *);
                    originSelectorIMP = (void (*)(id, SEL, CALayer *))originalIMPProvider();
                    originSelectorIMP(selfObject, originCMD, firstArgv);
                    ...
                    selfObject.qmui_borderLayer.path = path.CGPath;
                });

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]：iPhone 11
 - iOS 版本: [iOS 14.x] iOS13.7
 - Xcode 版本: [Xcode 12.x] Xcode 12.3
 - QMUI 版本: [4.x.x] 4.2.0

**Comment by MoLice** [comment]
你可以试试把 QMUI 那些代码注释掉，我猜应该也是一样的问题。是不是你的业务代码本身就没在主线程操作？
