### ISSUE TITLE
iPhone 12 / 12 Pro横屏时导航栏高度是32不是44

### ISSUE THREAD

**Issue by QuintGao** [Tencent/QMUI_iOS#1198]
**Bug 表现**
在iPhone 12/12 Pro模型器下，在控制器中输出self.navigationController.navigationBar.frame发现横屏时导航栏高度是32
而QMUI中的NavigationBarHeight输出高度是44

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [模拟器]
 - iOS 版本: [iOS 14.4]
 - Xcode 版本: [Xcode 12.4]
 - QMUI 版本: [4.2.2]

**Comment by MoLice** [comment]
新版本将会调整，在此之前可以将以下代码替换 QMUIHelper.m 的同名方法：
```objc
+ (BOOL)isRegularScreen {
    return [self isIPad] || (!IS_ZOOMEDMODE && ([self is67InchScreen] || [self is65InchScreen] || [self is61InchScreen] || [self is55InchScreen]));
}
```

另外如果你处于 UIViewController 的上下文里，那应该用 `vc.qmui_navigationBarMaxYInViewCoordinator` 来获取导航栏的布局，而不是用写死的宏，任何时候宏都只是一个保底方案。

**Comment by MoLice** [comment]
已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 修复该问题。
