### ISSUE TITLE
UITextField选中内容crash，pod删除QMUIKit的话就不会crash(xcode11之后在SceneDelegate中管理了window，appdelegate取不到window)

### ISSUE THREAD

**Issue by faber0709** [Tencent/QMUI_iOS#1199]
**Bug 表现**
UITextField *text = [[UITextField alloc] initWithFrame:CGRectMake((self.view.frame.size.width-400)/2, 200, 400, 50)];
    text.backgroundColor = [UIColor lightGrayColor];
    [self.view addSubview:text];
双击输入框，试图全选的时候会crash

**截图**
2021-02-25 15:45:38.322415+0800 DPF-Demo[57003:2059847] -[AppDelegate window]: unrecognized selector sent to instance 0x6000010dc3a0
2021-02-25 15:45:38.330711+0800 DPF-Demo[57003:2059847] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate window]: unrecognized selector sent to instance 0x6000010dc3a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   UIKitCore                           0x00007fff246cba43 -[UIResponder doesNotRecognizeSelector:] + 292
	4   CoreFoundation                      0x00007fff20425dc0 ___forwarding___ + 859
	5   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	6   QMUIKit                             0x000000010090777e __49-[UIMenuController(QMUI) windowForFirstResponder]_block_invoke + 158
	7   CoreFoundation                      0x00007fff2039339f __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	8   CoreFoundation                      0x00007fff2031fa34 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 224
	9   QMUIKit                             0x0000000100907590 -[UIMenuController(QMUI) windowForFirstResponder] + 320
	10  QMUIKit                             0x0000000100906b2e -[UIMenuController(QMUI) handleMenuWillShowNotification:] + 94
	11  CoreFoundation                      0x00007fff20362f12 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	12  CoreFoundation                      0x00007fff20362ee1 ___CFXRegistrationPost_block_invoke + 49
	13  CoreFoundation                      0x00007fff203625ff _CFXRegistrationPost + 454
	14  CoreFoundation                      0x00007fff20361f6d _CFXNotificationPost + 796
	15  Foundation                          0x00007fff207e598a -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	16  UIKitCore                           0x00007fff2456d4a9 -[UIMenuController(UICalloutBarDelegateConformance) calloutBar:willStartAnimation:] + 317
	17  UIKitCore                           0x00007fff2419800b -[UICalloutBar appear] + 382
	18  UIKitCore                           0x00007fff2499b9e3 -[UITextSelectionView _showCommandsWithReplacements:isForContextMenu:forDictation:rectsToEvade:] + 2198
	19  UIKitCore                           0x00007fff2499b110 __77-[UITextSelectionView _showCommandsWithReplacements:forDictation:afterDelay:]_block_invoke + 260
	20  libdispatch.dylib                   0x0000000100cd39c8 _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x0000000100cd6316 _dispatch_continuation_pop + 557
	22  libdispatch.dylib                   0x0000000100ce9e8b _dispatch_source_invoke + 2205
	23  libdispatch.dylib                   0x0000000100ce1ca4 _dispatch_main_queue_callback_4CF + 687
	24  CoreFoundation                      0x00007fff2038fdbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	25  CoreFoundation                      0x00007fff2038a63e __CFRunLoopRun + 2685
	26  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	27  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	28  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	29  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	30  DPF-Demo                            0x0000000100405dea main + 122
	31  libdyld.dylib                       0x00007fff2025a3e9 start + 1
	32  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate window]: unrecognized selector sent to instance 0x6000010dc3a0'
CoreSimulator 732.18.6 - Device: iPhone 12 Pro Max (75CA09E3-6A01-4CEB-AE86-1990D2AFDB44) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12 Pro Max
terminating with uncaught exception of type NSException

**如何重现**
1. 输入文本
2. 双击文本选中，就crash

**预期的表现**

**其他信息**
 - 设备: 模拟器iPhone 12 Pro Max
 - iOS 版本: iOS 14.4 
 - Xcode 版本: [Xcode 12.4]
 - QMUI 版本: QMUIKit (4.2.2)

**Comment by MoLice** [comment]
使用 SceneDelegate 的项目无法使用 QMUI，该 issue 提的问题只是其中的一个，还会有很多其他问题。建议移除 QMUI，或不要使用 SceneDelegate。
参考：https://github.com/Tencent/QMUI_iOS/issues/766#issuecomment-738624458
