### ISSUE TITLE
pod Install 的版本不对

### ISSUE THREAD

**Issue by MasterWen** [Tencent/QMUI_iOS#1201]
当使用 pod install ‘QMUIKit’市下载下来的版本是2.9.4，之前项目使用的都是4.1.0

**Comment by MoLice** [comment]
先确认是否本地 pod 没更新，用 pod update。
如果不是，请检查项目支持的最低 iOS 版本，有写在 README 里：
![image](https://user-images.githubusercontent.com/1190261/109267439-89cdb080-7844-11eb-84f8-2d9872505b90.png)
