### ISSUE TITLE
UINavigationBar 能不能加上这个沉浸式的效果 类似的组件有WRNavigationBar 但是该项目已经很多年不维护了

### ISSUE THREAD

**Issue by lilin87788** [Tencent/QMUI_iOS#1202]
![qq空间](https://user-images.githubusercontent.com/1483811/109267719-fcd72700-7844-11eb-8660-d15bec571d1b.gif)n
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。
WRNavigationBar :https://github.com/Xianlau/WRNavigationBar

**Comment by MoLice** [comment]
![Uploading image.png…]()

**Comment by lilin87788** [comment]
@MoLice 看起来不是很像，我瞧一瞧

**Comment by lilin87788** [comment]
已经实现，非常感谢

**Comment by lilin87788** [comment]
我实现的时候几个细节问题
1、   self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        self.automaticallyAdjustsScrollViewInsets = NO;
2、    //当这个值为NO 你点击IDMPhotoBrowser 的时候 顶部会出现黑色的navigationBar 设置为YES就ok 了
    self.extendedLayoutIncludesOpaqueBars = YES;
3、离开页面的时候，没有找到很好的恢复navigationBar的办法。
4、QMUICommonDefines 里面的很多宏能不能加上QMUI的前缀，比如SCREEN_WIDTH就和原项目定义的宏重复定义了。

**Comment by lilin87788** [comment]
@MoLice  第四点作者觉得有必要，希望解决下，要不然好多警告
