### ISSUE TITLE
(重大bug)引入QMUI以后，present一个UINavigationController以后，再push到另一个vc，滑动返回会卡死

### ISSUE THREAD

**Issue by kingstarwmx** [Tencent/QMUI_iOS#1206]
**Bug 表现**
1.引入QMUI以后，present一个UINavigationController以后，再push到另一个vc，操作几下，滑动返回会卡死(见gif),控制台打印
`2021-03-11 14:29:53.403146+0800 NaviPopTest[1275:78586] *** Assertion failure in +[UINavigationController load], UINavigationController+QMUI.m:265
2021-03-11 14:29:53.406146+0800 NaviPopTest[1275:78586] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'QMUI 认为 popViewController 会成功，但实际上失败了'
*** First throw call stack:
(0x186d5c878 0x19b2b2c50 0x186c62000 0x187ff391c 0x104ed2724 0x18902aaac 0x189029498 0x189250e54 0x18925a7b8 0x1892573f4 0x18925696c 0x18924aa98 0x189249e44 0x1897511b4 0x18972a4ec 0x1897b4488 0x1897b7440 0x1897ae8ec 0x186cd876c 0x186cd8668 0x186cd7960 0x186cd1a8c 0x186cd121c 0x19dd50784 0x18970a200 0x18970fa74 0x1049e5ea4 0x1869916c0)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'QMUI 认为 popViewController 会成功，但实际上失败了'
terminating with uncaught exception of type NSException`
2.如果用一样的代码不引入QMUI，按照gif那样操作是不会崩溃的，完全正常，我上传了两份完全一样的代码（[Test.zip](https://github.com/Tencent/QMUI_iOS/files/6120925/Test.zip)），区别就是一个用cocoapods安装了QMUI(代码甚至不用导入qmui框架，啥都不做)，另一份不引入，不引入的那个表现完全正常，pod安装的那个很容易就崩溃
3.我猜测是QMUI在hook系统方法的时候出了问题，以前就有这种预感，大量hook系统的方法好不安全

**截图**
如图所示，左右动两下， 上下动两下，就会崩溃，后面静止是因为已经崩了
![2021-03-11 143122](https://user-images.githubusercontent.com/13830979/110746922-8a206f80-8278-11eb-99cc-15a63d5f26b5.gif)

**如何重现**
如gif截图所示

**预期的表现**
正常情况下，不应该崩溃

**其他信息**
 - 设备: iPhone XS Max
 - iOS 版本: [iOS 14.2]
 - Xcode 版本: [Xcode 12.4]
 - QMUI 版本: [4.2.2]

**Comment by MoLice** [comment]
按 issue 的描述操作也没问题，是否有其他触发条件？
https://user-images.githubusercontent.com/1190261/110798914-94ad2a00-82b5-11eb-8d62-945e49226fe2.mov

**Comment by kingstarwmx** [comment]
你需要真机来调试，而且不是每次必现，要多试几次，你这样试不出来的

> 按 issue 的描述操作也没问题，是否有其他触发条件？
> https://user-images.githubusercontent.com/1190261/110798914-94ad2a00-82b5-11eb-8d62-945e49226fe2.mov

**Comment by MoLice** [comment]
下次请备注详细，节省时间。

**Comment by kingstarwmx** [comment]
> 下次请备注详细，节省时间。

好的大佬，你复现了么

**Comment by kingstarwmx** [comment]
> 下次请备注详细，节省时间。

大佬，你复现找到问题所在了么？

**Comment by wangxuewen** [comment]
> > 下次请备注详细，节省时间。
> 
> 大佬，你复现找到问题所在了么？

这个问题怎么处理的？

**Comment by kingstarwmx** [comment]
> > > 下次请备注详细，节省时间。
> > 
> > 
> > 大佬，你复现找到问题所在了么？
> 
> 这个问题怎么处理的？

这个好像是系统的问题，系统会卡死，qmui只是把异常抛出让程序崩溃

**Comment by wangxuewen** [comment]
> 这个好像是系统的问题，系统会卡死，qmui只是把异常抛出让程序崩溃

我这边复现的场景时push到一个新页面，在新页面viewDidLoad方法里直接pop出去走到断言这里里，release环境没问题。

**Comment by kingstarwmx** [comment]
嗯 问题搞明白了，是在debug环境下iOS有这个bug，但是release是没问题的，QMUI把release的异常抛出了，而不用QMUI的情况下，界面会直接卡死
