### ISSUE TITLE
能否实现QMUIPopupContainerView指定位置，就算位置不够

### ISSUE THREAD

**Issue by chenfengfeng** [Tencent/QMUI_iOS#1208]
/// 计算布局时期望的默认位置，默认为QMUIPopupContainerViewLayoutDirectionAbove，也即在目标的上方
@property(nonatomic, assign) QMUIPopupContainerViewLayoutDirection preferLayoutDirection UI_APPEARANCE_SELECTOR;

/// 最终的布局方向（preferLayoutDirection只是期望的方向，但有可能那个方向已经没有剩余空间可摆放控件了，所以会自动变换）
@property(nonatomic, assign, readonly) QMUIPopupContainerViewLayoutDirection currentLayoutDirection;

有两个属性，但是只能设置preferLayoutDirection，我希望能够给一个强制的方向，而不是自动变化，可以设置吗？我找了一圈没找到。。。

**Comment by MoLice** [comment]
QMUIPopupContainerView 的剩余空间计算由 `superview` 的大小和 `safetyMarginsOfSuperview` 安全边距决定。
既然你改变不了 `superview` 的大小，那你可以把 `safetyMarginsOfSuperview` 设置为负无穷大，这样就等价于任意方向都能放得下你的 popup 浮层。
所以：
<img src="https://user-images.githubusercontent.com/1190261/111072094-0d112680-8514-11eb-94bc-4efc62dde33d.png" width="400" />

例如截图里的浮层，代码里期望是在目标下方显示，但明显下方的空间不足，此时只要把 `safetyMarginsOfSuperview` 设置为足够小的负数，就能视为下方的空间足够，于是最终浮层就会显示在目标下方。

**Comment by chenfengfeng** [comment]
@MoLice 非常感谢～～
