### ISSUE TITLE
[广州|成都] 企业微信/微信读书/王者营地长期接收 iOS 客户端社招、实习生简历

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#1209]
长期内推简历，当天处理。

## 企业微信 iOS 跨平台框架研发

<img src="https://user-images.githubusercontent.com/1190261/111151139-05ac5480-85ca-11eb-82f4-7dbefd86c3d7.png" width="66" />

长期招。
社招、实习生均可。
成都、广州。
社招简历投递：molicechen@tencent.com
实习生请微信扫码：
<img src="https://user-images.githubusercontent.com/1190261/111154257-fc24eb80-85cd-11eb-96d3-709af493b4d9.png" width="80" />

## 微信读书 iOS 客户端开发

<img src="https://user-images.githubusercontent.com/1190261/111151225-22488c80-85ca-11eb-9290-bd6eefacc7eb.png" width="60" />

长期招。
社招、实习生均可。
广州。
社招简历投递：ziezheng@tencent.com
实习生请微信扫码：
<img src="https://user-images.githubusercontent.com/1190261/111154447-31313e00-85ce-11eb-9b35-baad168f59dd.png" width="80" />

## 王者营地 App 研发基地 iOS 开发

<img src="https://user-images.githubusercontent.com/1190261/111151305-3d1b0100-85ca-11eb-8f32-78c409bdd2fc.png" width="60" />

长期招。
社招。
成都。
简历投递：ronhu@tencent.com

**Comment by heisall** [comment]
QMUISearchController 现在需要点击搜索框才能进入后面的历史搜索，如何直接调起历史搜素页？
![Simulator Screen Shot - iPhone 12 - 2021-08-25 at 16 06 37](https://user-images.githubusercontent.com/6358612/130752620-d04c81b6-16c7-4fef-b958-2043d803ce1d.png)

![Simulator Screen Shot - iPhone 12 - 2021-08-25 at 16 06 20](https://user-images.githubusercontent.com/6358612/130752582-ad48c517-6a17-4cb8-8a77-83a7982792a8.png)

**Comment by MoLice** [comment]
@heisall 请勿发表与 issue 无关的内容，该评论将会删除。
