### ISSUE TITLE
Ambiguous use of 'cornerRadius'

### ISSUE THREAD

**Issue by ganweiming** [Tencent/QMUI_iOS#1221]
4.2.3版本中QMUIButton加入cornerRadius属性. 与SwifterSwift 中的UIView拓展方法命名冲突. 请问有什么较好的方式处理

**Comment by jiasongs** [comment]
SwifterSwift中增加的Extension没有加前缀也没有类似RxSwift中的`rx.code`写法，很大概率会导致命名冲突，我们项目参考了`rx.code`写法，fork了SwifterSwift的代码，然后根据需要自己改进一下

**Comment by ganweiming** [comment]
@jiasongs 所以SwifterSwift使用固定版本. 使QMUI保持cocoapod最新版本来做吗?

**Comment by jiasongs** [comment]
@ganweiming 不是，fork SwifterSwift的代码，然后项目组自己改进。假设你们接苹果登陆的时候，也会与ASAuthorizationAppleIDButton冲突

**Comment by MoLice** [comment]
@ganweiming 就是你们自己去改 SwifterSwift 的代码，给它加前缀或者什么的，都行，自行决定。因为这个问题是由 SwifterSwift 引发的，它会与众多东西冲突，QMUI 只是其中一个被冲突的框架。
