### ISSUE TITLE
QMUIKeyboardManager 后台线程调用导致Crash

### ISSUE THREAD

**Issue by Arthas-cn** [Tencent/QMUI_iOS#1227]
**Bug 表现**
启动APP点击输入框就会报错，键盘第一次出来 非常慢，被卡顿了4-5秒

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![82021ED1-7C70-4297-8703-0E491C19FAB1](https://user-images.githubusercontent.com/46341476/114813065-e03a8280-9de3-11eb-8e9d-55eab64d320a.png)
2021-04-15 11:59:56.615144+0800 app[11124:4468335] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitTruffle-NumberPad; using 25901_PortraitTruffle_iPhone-Simple-Pad_Default
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]
PID: 11124, TID: 4468522, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   app                               0x0000000102b610ec __70+[UITraitCollection(QMUI) _qmui_overrideTraitCollectionMethodIfNeeded]_block_invoke_3 + 148
5   UIKitCore                           0x000000019ca12b20 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8698656
6   UIKitCore                           0x000000019ca12e5c 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8699484
7   UIKitCore                           0x000000019c9dc488 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8475784
8   libdispatch.dylib                   0x0000000112423db8 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x00000001124255fc _dispatch_client_callout + 16
10  libdispatch.dylib                   0x00000001124372bc _dispatch_root_queue_drain + 788
11  libdispatch.dylib                   0x0000000112437a48 _dispatch_worker_thread2 + 152
12  libsystem_pthread.dylib             0x00000001dfd8c568 _pthread_wqthread + 212
13  libsystem_pthread.dylib             0x00000001dfd8f874 start_wqthread + 8
2021-04-15 11:59:56.623427+0800 app[11124:4468522] [reports] Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]
PID: 11124, TID: 4468522, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   app                               0x0000000102b610ec __70+[UITraitCollection(QMUI) _qmui_overrideTraitCollectionMethodIfNeeded]_block_invoke_3 + 148
5   UIKitCore                           0x000000019ca12b20 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8698656
6   UIKitCore                           0x000000019ca12e5c 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8699484
7   UIKitCore                           0x000000019c9dc488 00EA1426-38F7-3FD2-BE01-04EBD44ECA35 + 8475784
8   libdispatch.dylib                   0x0000000112423db8 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x00000001124255fc _dispatch_client_callout + 16
10  libdispatch.dylib                   0x00000001124372bc _dispatch_root_queue_drain + 788
11  libdispatch.dylib                   0x0000000112437a48 _dispatch_worker_thread2 + 152
12  libsystem_pthread.dylib             0x00000001dfd8c568 _pthread_wqthread + 212
13  libsystem_pthread.dylib             0x00000001dfd8f874 start_wqthread + 8
**如何重现**
1. 启动APP
2. 点击输入框

**预期的表现**
不要报错

**其他信息**
 - 设备: 真机 iPhone 8p 、xr
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: Version 12.4 (12D4e)
 - QMUI 版本: QMUIKit/QMUICore (4.2.3)

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 优化该问题。
