### ISSUE TITLE
QMUITableViewStyleInsetGrouped 能否支持设置投影tableViewInsetGroupedShadowColor

### ISSUE THREAD

**Issue by Snail-hash** [Tencent/QMUI_iOS#1228]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。

**Comment by MoLice** [comment]
建议用 collectionView 实现。insetGrouped 的 cell 由于需要做 cornerRadius，会被 clip，clip 后就无法显示 shadow 了。
