### ISSUE TITLE
4.2.3版本上传包检查出非公开API

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#1231]
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/QMUIKit.framework/QMUIKit: navigationBarBackgroundImage, navigationBarStyle, navigationBarTintColor. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by MoLice** [comment]
与群友确认了，已有若干项目正常提交没问题，这个只是提醒而已。暂不处理。

**Comment by TML007** [comment]
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/QMUIKit.framework/QMUIKit: navigationBarBackgroundImage, navigationBarStyle, navigationBarTintColor. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

不移除，包都提交不了。版本也构建不了。

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 修复该问题，业务需要跟着新版本重命名。
