### ISSUE TITLE
UISearchBar(QMUI).qmui_alwaysEnableCancelButton 可能出现 crash

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#1232]
**问题描述**
<img src="https://user-images.githubusercontent.com/1190261/115680338-1056c800-a386-11eb-8083-1cf69b0c59f8.png"  width="500" />

QMUI 4.2.3 里 UISearchBar(QMUI) 新增了属性 qmui_alwaysEnableCancelButton，该属性 hook 了 `UINavigationButton` 的 `setEnabled:` 方法，在里面试图获取 `UISearchBar` 的引用然后处理一些逻辑。但在 iOS 里，不仅是搜索框的取消按钮是 `UINavigationButton` 类型，在 iOS 10 的 `UIToolbar` 里也存在 `UINavigationButton`，而 QMUI 的逻辑里没有判断获取到的 searchBar 是否真的是 `UISearchBar`，导致会对非 `UISearchBar` 调用不存在的方法，从而引发 crash。

<img src="https://user-images.githubusercontent.com/1190261/115680115-db4a7580-a385-11eb-923d-4d6d0f989dc1.png" width="500" />

**其他信息**
 - 设备: All
 - iOS 版本: iOS 10.x
 - QMUI 版本: 4.2.3

**Comment by MoLice** [comment]
@lilin87788  将以下代码替换你本地的 UISearchBar+QMUI.m 里的相关代码。

```objc
OverrideImplementation(NSClassFromString(@"UINavigationButton"), @selector(setEnabled:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void)) {
    return ^(UIButton *selfObject, BOOL firstArgv) {
        
        UISearchBar *searchBar = nil;
        if (@available(iOS 13.0, *)) {
            searchBar = (UISearchBar *)selfObject.superview.superview.superview;
        } else {
            searchBar = (UISearchBar *)selfObject.superview.superview;
        }
        
        if ([searchBar isKindOfClass:UISearchBar.class] && searchBar.qmui_alwaysEnableCancelButton && !searchBar.qmui_searchController) {
            firstArgv = YES;
        }
        
        // call super
        void (*originSelectorIMP)(id, SEL, BOOL);
        originSelectorIMP = (void (*)(id, SEL, BOOL))originalIMPProvider();
        originSelectorIMP(selfObject, originCMD, firstArgv);
    };
});
```

**Comment by lilin87788** [comment]
您好：我使用pod 集成的如何修改啊

**Comment by lilin87788** [comment]
![image](https://user-images.githubusercontent.com/1483811/117777709-7345cb80-b26f-11eb-868b-16ffd21640ee.png)
现在我这边出现了大量的这个错误导致的闪退

**Comment by lilin87788** [comment]
您好：希望判断ios10的版本提交一个新的tag4.2.4 来解决这个问题，非常感谢

**Comment by lilin87788** [comment]
用fork的办法已经解决 谢谢

**Comment by pagesvr** [comment]
是的,这个BUG我在iOS10的版本上也遇到了,我也是这样改的

**Comment by lilin87788** [comment]
![Uploading image.png…]()
改了以后好像还是报了这个错误

**Comment by MoShenGuo** [comment]
你好 这个hook是干嘛的 你这是hook UISearchBar中UINavigationButton对象setEnabled：方法吧？如果我没有对setEnabled方法调用也会被影响吗？或者没有调用UISearchBar 中UINavigationButton对象方法setEnabled 道理是不会走到你的hook方法的 不知道我理解对不

**Comment by MoLice** [comment]
> 你好 这个hook是干嘛的 你这是hook UISearchBar中UINavigationButton对象setEnabled：方法吧？如果我没有对setEnabled方法调用也会被影响吗？或者没有调用UISearchBar 中UINavigationButton对象方法setEnabled 道理是不会走到你的hook方法的 不知道我理解对不

系统也会调用的，不一定是你的业务代码主动触发。

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 修复该问题。
