### ISSUE TITLE
customNavigationBarTransitionKey 无效

### ISSUE THREAD

**Issue by renshaojuncool** [Tencent/QMUI_iOS#1233]
系统版本：iOS14.4.2
语言：Swift
QMUI版本：4.2.3

APP未使用配置表。配置 customNavigationBarTransitionKey 后，在4.2.2中，前后NavBar颜色不一致，会有QMUI的过渡动画，升级4.2.3后，NavBar的过渡动画不起作用。

**Comment by MoLice** [comment]
请提供 Demo。

**Comment by codingiran** [comment]
遇到这个问题+1
