### ISSUE TITLE
切换主题时，渐变颜色的没有跟随主题一块变化

### ISSUE THREAD

**Issue by tfy87happy** [Tencent/QMUI_iOS#1234]
切换主题时，如果是CAGradientLayer setStartPoint:这种渐变颜色的，并没有隋主题一起变化，希望能优化下，QMUI确实很强大，支持！

**Comment by MoLice** [comment]
无法复现，为节省双方时间，请提供 Demo，或者提 issue 时至少贴一下相关代码。

<video src="https://user-images.githubusercontent.com/1190261/115774031-a240ee00-a3e3-11eb-828c-b0d91c57a7d3.mov" />
