### ISSUE TITLE
上传ipa出现问题

### ISSUE THREAD

**Issue by kj-huang** [Tencent/QMUI_iOS#1238]
**Bug 表现**
上传审核出现问题

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/17734586/118133014-e3507f00-b432-11eb-9ea6-49dd6a15ec78.png)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.5]
 - QMUI 版本: [4.2.3]

**Comment by SlinceDog** [comment]
我也出现了这个问题！如何解决？

**Comment by kj-huang** [comment]
> 我也出现了这个问题！如何解决？

我是给降级使用4.2.2版本就可以了。等待QMUI更新

**Comment by fanyuecheng** [comment]
同 https://github.com/Tencent/QMUI_iOS/issues/1231

**Comment by kj-huang** [comment]
> 同 #1231

问题是收到这样的邮件后，AppStoreConnect中上传的ipa就自动消失了。。

**Comment by ajunjunandtmac** [comment]
我也遇到同样的问题，希望能够早日解决。

**Comment by MoLice** [comment]
#1231
