### ISSUE TITLE
关于options:QMUIViewAnimationOptionsCurveOut如何生效

### ISSUE THREAD

**Issue by liuzhaozhen** [Tencent/QMUI_iOS#1240]
示例代码：[UIView animateWithDuration:.15 delay:0.9 options:QMUIViewAnimationOptionsCurveOut animations:^{..];

在上述代码中使用到了QMUIViewAnimationOptionsCurveOut （7<<16）,我个人不太明白QMUIViewAnimationOptionsCurveOut是如何工作的。

demo中并没有重写animateWithDuration，然后系统为何能识别QMUIViewAnimationOptionsCurveOut这个值呢。
非常感谢。

**Comment by MoLice** [comment]
这是系统的私有 API，效果不是由 QMUI 实现的，是系统自己实现，内部会用 Spring Animation，所以 duration 此时是无效的，不管你填 0.15 还是 1.5，实际都是 0.25。
