### ISSUE TITLE
QMUIConsole logWithLevel没有背景颜色看不到log

### ISSUE THREAD

**Issue by QionglinFu1024** [Tencent/QMUI_iOS#1248]
**Bug 表现**
问题的具体描述
直接调用[QMUIConsole logWithLevel....展示的页面没有背景颜色了

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/26901908/119448579-1e707d80-bd64-11eb-94cf-be6c98aaffae.png)

**如何重现**
1. 直接调用[QMUIConsole logWithLevel....看不到log。没有默认配置的黑色了

**预期的表现**
希望跟之前的版本一样，有默认配置的黑色，不然还需要单独去维护一套log的配置太麻烦了
现在还需要这样去配置一套颜色才可以看到
[QMUIConsole appearance].backgroundColor = [UIColor redColor];
    [QMUIConsole appearance].textAttributes = @{
        NSForegroundColorAttributeName: [UIColor darkGrayColor]
    };

**其他信息**
 - 设备: iPhone11 
 - iOS 版本: 14.2
 - Xcode 版本: 12.5
 - QMUI 版本: 4.2.3

**Comment by MoLice** [comment]
QMUIConsole 里默认就有赋值，QMUI Demo 也没有自己修改 appearance，但 QMUI Demo 也是可以正常显示的，是不是你的业务代码在哪里改掉了默认样式了？
![image](https://user-images.githubusercontent.com/1190261/119480092-e5480580-bd83-11eb-82e0-7dfc3ff6a6d8.png)

**Comment by MoLice** [comment]
已发布 [4.5.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.5.0) 修复该问题。
