### ISSUE TITLE
QMUIAlertController弹框无法显示

### ISSUE THREAD

**Issue by xtxh** [Tencent/QMUI_iOS#1252]
**Bug 表现**
问题的具体描述
Swift 使用QMUIAlertController弹不出来

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/15848988/119793777-785e7800-bf09-11eb-8ca0-a71017b7825f.png)

**如何重现**
1. Xcode 12.5，swift 5，按照Demo示例正常使用就会出现
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.5.1]
 - Xcode 版本: [Xcode 12.5]
 - QMUI 版本: [4.2.3]

**Comment by xtxh** [comment]
替换成UIAlertController就可以正常弹出来

**Comment by Gluckyiyi** [comment]
一样的问题

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/119815713-6affb880-bf1e-11eb-951c-0aad60795a90.png)
issue 这里为啥不填呢？

**Comment by xtxh** [comment]
同样的问题在QMUIPopupContainerView上也有出现，即使用Swift开发在正常调用QMUIPopupContainerView实例对象的显示方法- (void)showWithAnimated:(BOOL)animated后，弹框无法出现

**Comment by MoLice** [comment]
#766
