### ISSUE TITLE
Plus机型横屏模式下启动，方向异常（Bug）

### ISSUE THREAD

**Issue by dwjgkp** [Tencent/QMUI_iOS#1257]
**Bug 表现**
iPhone7/8Plus机型，在横屏模式下，启动一个竖屏应用，启动后会造成界面方向异常。

**如何重现**
1. 导入QMUI
2. Device Orientation 只选择Portrait
3. 直接在Plus机型的横屏模式下启动

**问题代码**
QMUIHelper类的
**+ (BOOL)isNotchedScreen**方法，
在启动时设置新的rootViewController
UIViewController *viewController = [UIViewController new];
window.rootViewController = viewController;
会造成启动方向异常的问题

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.5]
 - QMUI 版本: [4.1.3]

**Comment by jiasongs** [comment]
same issue https://github.com/Tencent/QMUI_iOS/issues/1263

**Comment by MoLice** [comment]
由 #1263 跟进

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 修复该问题。
