### ISSUE TITLE
iOS14 默认主题下状态栏颜色问题

### ISSUE THREAD

**Issue by Snail-hash** [Tencent/QMUI_iOS#1260]
默认主题下QMUICMI.statusbarStyleLightInitially = NO;
暗黑主题下QMUICMI.statusbarStyleLightInitially = YES;
QMUIThemeManagerCenter.defaultThemeManager.respondsSystemStyleAutomatically = YES的情况下状态栏都正常
QMUIThemeManagerCenter.defaultThemeManager.respondsSystemStyleAutomatically = NO的情况下手机主题暗黑模式，页面预期状态栏黑色，实际为白色

Demo修改QMUIConfigurationTemplate文件QMUICMI.statusbarStyleLightInitially = NO; 然后关闭自动响应iOS13系统样式能重现

**Comment by MoLice** [comment]
4.4.0 里已修复
