### ISSUE TITLE
设置透明导航栏转场效果有bug

### ISSUE THREAD

**Issue by MoDaBao** [Tencent/QMUI_iOS#1261]
**Bug 表现**
配置表中automaticCustomNavigationBarTransitionStyle设置为YES
控制器中 self.navigationController.navigationBar.translucent 设置为YES 这个属性不设置为YES透明背景就无效
并且实现了QMUINavigationControllerDelegate中返回背景图片的代理方法  转场效果有bug

**截图**

https://user-images.githubusercontent.com/16697955/123508420-eed5cd80-d6a1-11eb-85de-a2d07081d081.MP4

**其他信息**
 - 设备: iphone6 Plus
 - iOS 版本: [iOS 12.5.3]
 - Xcode 版本: [Xcode 12.4]
 - QMUI 版本: [4.2.3]

**Comment by MoLice** [comment]
无法重现：
https://user-images.githubusercontent.com/1190261/123539230-42601e00-d76b-11eb-9eb7-c02546f27f05.mp4

代码：
![image](https://user-images.githubusercontent.com/1190261/123539252-5c016580-d76b-11eb-8ffc-d68905fd0e54.png)
![image](https://user-images.githubusercontent.com/1190261/123539265-64f23700-d76b-11eb-9105-2ddc9c7fad82.png)

**Comment by MoDaBao** [comment]
找到原因了 因为我在代码其他地方调用了[UINavigationBar appearance]设置导航栏的样式
