### ISSUE TITLE
QMUIAlertController显示问题

### ISSUE THREAD

**Issue by heisall** [Tencent/QMUI_iOS#1262]
调用代码没有弹出，什么原因呢？
    QMUIAlertController *alertController = [[QMUIAlertController alloc] initWithTitle:@"确定删除？" message:@"删除后将无法恢复，请慎重考虑" preferredStyle:QMUIAlertControllerStyleAlert];
    [alertController showWithAnimated:YES];

**Comment by MoLice** [comment]
提供的信息太少，如果是你，你面对这个信息怎么入手...至少贴一下使用场景或者 Xcode 控制台输出的相关信息。

**Comment by heisall** [comment]
场景是想在tableview cell选中的时候弹出一个选择框，仿照demo中的水平对齐方式弹窗那段写法，但是没有弹出，就想用一个最简单的提示测试一下，也不弹出，以下是调用代码
-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
    
    QMUIAlertController *alertController = [[QMUIAlertController alloc] initWithTitle:@"确定删除？" message:@"删除后将无法恢复，请慎重考虑" preferredStyle:QMUIAlertControllerStyleAlert];
    [alertController showWithAnimated:YES];
}

**Comment by heisall** [comment]
场景是想在tableview cell选中的时候弹出一个选择框，仿照demo中的水平对齐方式弹窗那段写法，但是没有弹出，就想用一个最简单的提示测试一下，也不弹出，以下是调用代码
-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
    
    QMUIAlertController *alertController = [[QMUIAlertController alloc] initWithTitle:@"确定删除？" message:@"删除后将无法恢复，请慎重考虑" preferredStyle:QMUIAlertControllerStyleAlert];
    [alertController showWithAnimated:YES];
}

**Comment by MoLice** [comment]
#1252
