### ISSUE TITLE
非全面屏的 Regular 设备，仅支持竖屏的 App 在横屏启动时界面错乱

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1263]
**Bug 表现**
手机横屏启动的情况下，进入首页后UI会显示异常，如录屏所示，「导航栏和Tabbar」的高度都变小了，状态栏消失不见。

**截图**
以下录屏为「横屏启动」：
https://user-images.githubusercontent.com/22904757/123778914-322f7680-d904-11eb-9547-92fb3508cb20.mp4

**如何重现**
0、使用iPhone7，iPhoneSE等「非全面屏且桌面不支持横屏」的设备稳定复现
1、info.plist只勾选Portrait
<img width="264" alt="图片" src="https://user-images.githubusercontent.com/22904757/123779830-28f2d980-d905-11eb-94bf-9de1bcc7e67b.png">
2、AppDeleagte里实现
<img width="1215" alt="图片" src="https://user-images.githubusercontent.com/22904757/123779966-47f16b80-d905-11eb-879f-5f5af42720be.png">
3、设置`QMUICMI.supportedOrientationMask = UIInterfaceOrientationMaskPortrait;`
4、横屏启动QMUIDemo

可复现的Demo，全局搜索语句"QMUI_iOS/issues/1263" 查看改动的地方
[QMUIDemo.zip](https://github.com/Tencent/QMUI_iOS/files/6732595/QMUIDemo.zip)

**预期的表现**
手机横屏启动的情况下，进入首页后也会正常显示

**其他信息**
 - 设备: iPhone7，iPhoneSE等「非全面屏」
 - iOS 版本: [iOS 14.5]
 - Xcode 版本: [Xcode 12.5]
 - QMUI 版本: [4.2.3]

**Comment by jiasongs** [comment]
<img width="1133" alt="图片" src="https://user-images.githubusercontent.com/22904757/123781436-d2869a80-d906-11eb-9535-9632beafa180.png">
是上图所示的红圈代码导致的，系统先访问了viewController的supportedOrientationMask得到的是UIInterfaceOrientationMaskAll，所以才会有这个问题，去掉这段代码就正常了。

**Comment by MainByElse** [comment]
same issue

**Comment by jiasongs** [comment]
same issue https://github.com/Tencent/QMUI_iOS/issues/1257

**Comment by MoLice** [comment]
提供的 Demo 运行起来是这样？
<img src="https://user-images.githubusercontent.com/1190261/125166216-2463d600-e1cd-11eb-97b9-3392c78acc99.png" width="600" />

**Comment by jiasongs** [comment]
> 提供的 Demo 运行起来是这样？
> <img alt="" width="600" src="https://user-images.githubusercontent.com/1190261/125166216-2463d600-e1cd-11eb-97b9-3392c78acc99.png">

「iPhone 8 Plus」机型看起来不明显，但还是有问题，横屏后「状态栏没有了」，但是首页并没有隐藏状态栏的代码。

下图是「iPhone 7」的效果，问题就非常明显了。
<img width="889" alt="图片" src="https://user-images.githubusercontent.com/22904757/125215047-bdd5d980-e2ec-11eb-8879-4dd85b9550a2.png">

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 修复该问题。
