### ISSUE TITLE
动态字体适配TableView的问题

### ISSUE THREAD

**Issue by Snail-hash** [Tencent/QMUI_iOS#1264]
QDCellHeightCacheViewController：
- (void)contentSizeCategoryDidChanged:(NSNotification *)notification {
    [super contentSizeCategoryDidChanged:notification];
    [self.tableView qmui_invalidateAllHeight];
    [self.tableView reloadData];
}
QDDynamicHeightTableViewCell：
_nameLabel = [[UILabel alloc] qmui_initWithFont:UIDynamicFontBoldMake(16) textColor:UIColor.qd_mainTextColor];
    [self.contentView addSubview:self.nameLabel];
    
    _contentLabel = [[UILabel alloc] qmui_initWithFont:UIDynamicFontMake(17) textColor:UIColor.qd_mainTextColor];
    self.contentLabel.numberOfLines = 0;
    [self.contentView addSubview:self.contentLabel];
    
    _timeLabel = [[UILabel alloc] qmui_initWithFont:UIDynamicFontMake(13) textColor:UIColor.qd_descriptionTextColor];
    [self.contentView addSubview:self.timeLabel];

修改系统字体大小之后字体跟着一起变了，但是cell的高度没跟着变

**Comment by MoLice** [comment]
你的 cell 里的 font 是 在 label init 时才设置的，你有在字体变化后重新设置 font 吗？

**Comment by Snail-hash** [comment]
懂了，建议在QDFontViewController 里面加一下备注

**Comment by MoLice** [comment]
必要性不大，这种操作方式是系统的，与是否使用 QMUI 无关。
