### ISSUE TITLE
请教，iOS 15下QMUINavigationController背景图片设置的问题

### ISSUE THREAD

**Issue by eric0815** [Tencent/QMUI_iOS#1265]
大神，您好，非常感谢提供这么好的开源项目。请问有兼容iOS 15的计划吗，iOS 15下QMUINavigationController背景图片设置有点问题。相关讨论见下面的帖子，
[https://developer.apple.com/forums/thread/683265](https://developer.apple.com/forums/thread/683265)

iOS 15 下运行qmuidemo的效果如图

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-06 at 19 43 08](https://user-images.githubusercontent.com/1378812/124595177-47bc1780-de93-11eb-9162-f6bde3da4dfc.png)

非常感谢。

**Comment by WOHANGO** [comment]
@MoLice 你好，请问有没有临时解决方法，iOS15 9月21日推出，到时候用户一更新就会出现问题

**Comment by darvintang** [comment]
@MoLice 你好，目前Xcode13上打包会出现该问题，Xcode12打包正常。

**Comment by darvintang** [comment]
> @MoLice 你好，请问有没有临时解决方法，iOS15 9月21日推出，到时候用户一更新就会出现问题

用Xcode12打包就正常了

**Comment by HaQiuqiu** [comment]
if #available(iOS 15, *) {
            let app = UINavigationBarAppearance()
            app.configureWithOpaqueBackground()
            let image = UIImage.qmui_image(with: UNIColors.navbar, size: CGSize(width: 4, height: 4), cornerRadius: 0)
            app.backgroundImage = image
            self.navigationController?.navigationBar.scrollEdgeAppearance = app
            self.navigationController?.navigationBar.standardAppearance = app
        }
就可以了

**Comment by MoLice** [comment]
请关注 QMUI 后续的新版本更新。

**Comment by Arthas-cn** [comment]
关注

**Comment by WOHANGO** [comment]
@MoLice 还有tabbar，应该也是同样问题，滚动到底部变透明（xcode13 + ios15）

**Comment by hydyy** [comment]
@MoLice 请问4.4预计发布时间？

**Comment by MoLice** [comment]
> @MoLice 请问4.4预计发布时间？

本周一定，本周一定

**Comment by eric0815** [comment]
上次重新定义了本月，这次的本周不知道会怎么样了23333

**Comment by passol1988** [comment]
> 

离本周结束还有四天

**Comment by lcl2539** [comment]
周四啦，催更

**Comment by xiafb** [comment]
周五啦，在线蹲一个更新

**Comment by lsircode** [comment]
> 周五啦，在线蹲一个更新

别急 应该在打包了

**Comment by JFPURE** [comment]
我也蹲一个~

**Comment by hydyy** [comment]
请看我头像

**Comment by yaobiao131** [comment]
本周看来是更不了了

**Comment by eric0815** [comment]
> 本周看来是更不了了

不一定，美国还是早上

**Comment by MoLice** [comment]
已发布 [4.4.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.0) 适配该问题。

**Comment by evanzhou89** [comment]
iOS 11 以下的用户很是蛋疼

**Comment by JFPURE** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，来信已收到。无法及时回复您的邮件，深感歉意。

**Comment by MoLice** [comment]
> iOS 11 以下的用户很是蛋疼

把被去掉的 iOS 10 的代码自己加回来也不是很多。

**Comment by evanzhou89** [comment]
> > iOS 11 以下的用户很是蛋疼
> 
> @evanzhou89 把被去掉的 iOS 10 的代码自己加回来也不是很多。

嗯，也只能 fork 一份了。之前看了这部分代码，的确不是很多，所以有点好奇为什么不继续支持 iOS 10。

**Comment by MoLice** [comment]
> > > iOS 11 以下的用户很是蛋疼
> > 
> > 
> > @evanzhou89 把被去掉的 iOS 10 的代码自己加回来也不是很多。
> 
> 嗯，也只能 fork 一份了。之前看了这部分代码，的确不是很多，所以有点好奇为什么不继续支持 iOS 10。

国内的移动环境下，微信最低版本的支持情况，代表了绝大部分用户的场景。目前对 iOS 10 的投入性价比过低，精力有限的项目是不会支持的。
