### ISSUE TITLE
浪费性能

### ISSUE THREAD

**Issue by TellyHD** [Tencent/QMUI_iOS#1268]
一上来就hook很多方法，没有核心+插架的架构，造成了很多不必要的浪费和安全漏洞，感觉就是KPI项目，没啥实际作用。

**Comment by MoLice** [comment]
谢谢你的建议，我们会继续努力改善，目前可以考虑暂时不要使用。

**Comment by codingiran** [comment]
> 一上来就hook很多方法，没有核心+插架的架构，造成了很多不必要的浪费和安全漏洞，感觉就是KPI项目，没啥实际作用。

好想看看“有核心”“不浪费”“没有安全漏洞”的“插件架构”项目，求求你了！

**Comment by KiyoCao** [comment]
> 一上来就hook很多方法，没有核心+插架的架构，造成了很多不必要的浪费和安全漏洞，感觉就是KPI项目，没啥实际作用。

你可以不用，但是不要张嘴就来。脑子是个好东西，希望你敲键盘的时候能带上。

**Comment by TellyHD** [comment]
都是UI工具人啊，啥也不懂

**Comment by TellyHD** [comment]
> > 一上来就hook很多方法，没有核心+插架的架构，造成了很多不必要的浪费和安全漏洞，感觉就是KPI项目，没啥实际作用。
> 
> 好想看看“有核心”“不浪费”“没有安全漏洞”的“插件架构”项目，求求你了！

FFmpeg玩过没？

**Comment by TellyHD** [comment]
> > 一上来就hook很多方法，没有核心+插架的架构，造成了很多不必要的浪费和安全漏洞，感觉就是KPI项目，没啥实际作用。
> 
> 你可以不用，但是不要张嘴就来。脑子是个好东西，希望你敲键盘的时候能带上。

UI工具人，你懂啥，你知道分类、类实现load后的底层逻辑么，还张口就来。

**Comment by TellyHD** [comment]
> 谢谢你的建议，我们会继续努力改善，目前可以考虑暂时不要使用。

嗯，好的，是移除了再来评论的，我不配

**Comment by KiyoCao** [comment]
> > > 一上来就hook很多方法，没有核心+插架的架构，造成了很多不必要的浪费和安全漏洞，感觉就是KPI项目，没啥实际作用。
> > 
> > 
> > 你可以不用，但是不要张嘴就来。脑子是个好东西，希望你敲键盘的时候能带上。
> 
> UI工具人，你懂啥，你知道分类、类实现load后的底层逻辑么，还张口就来。

哇哦，好牛逼哦，张口就是分类、底层。你那么牛逼还找什么轮子呢？自己撸啊。
