### ISSUE TITLE
项目中同时引入QMUI 和 GrowingIO，运行闪退

### ISSUE THREAD

**Issue by lccxxq** [Tencent/QMUI_iOS#1271]
**Bug 表现**
项目中同时引入QMUI 和 GrowingIO，运行闪退

**崩溃具体见下面的图片链接，可以看见堆栈信息**
[https://static.iskytrip.com/app/QMUI_error.png](url)
**其他信息**
 - 设备: [iPhone11]
 - iOS 版本: [iOS 14.6]
 - Xcode 版本: [Xcode 12.5]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
#174
