### ISSUE TITLE
你好 使用框架版本4.2.3在iOS10.3.3版本出现闪退

### ISSUE THREAD

**Issue by MoShenGuo** [Tencent/QMUI_iOS#1272]
**Bug 表现**
问题的具体描述

**截图**
![图片](https://user-images.githubusercontent.com/21171688/126485646-0d61f9c8-2e63-47e1-b712-c699f072d76b.png)
![图片](https://user-images.githubusercontent.com/21171688/126485734-583132cc-8d44-4392-86e4-65c098f2ef3a.png)
![图片](https://user-images.githubusercontent.com/21171688/126485752-0bbc9db8-33f5-475c-9521-5001de54acb3.png)

**如何重现**
1. ...
2. ...

**其他信息**
 - 设备:iPhone
 - iOS 版本: [iOS 10.3.3]
 - Xcode 版本: [Xcode 12.5]
 - QMUI 版本: [4.2.3]

**Comment by MoLice** [comment]
#1232
