### ISSUE TITLE
QMUIConsole在iOS14上背景白色问题

### ISSUE THREAD

**Issue by Jude5201** [Tencent/QMUI_iOS#1274]
**Bug 表现**
问题的具体描述
QMUIConsole在更换tableView后未适配iOS14，默认会显示背景视图的白色，而不是显示自身背景颜色。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![IMG_0079](https://user-images.githubusercontent.com/34996712/126737534-73f289a7-18dc-43d6-8544-bc006b929862.PNG)

**如何重现**
iOS14必现

**预期的表现**
正常情况下，应该是什么表现
背景显示alpha=0.8的黑色

只需在tableViewCell里加上如下代码即可恢复正常显示：
`if (@available(iOS 14, *)) {
        self.backgroundConfiguration = [UIBackgroundConfiguration clearConfiguration];
}`

**其他信息**
 - 设备: [iPhone XS Max]
 - iOS 版本: [iOS 14.7]
 - Xcode 版本: [Xcode 12.5.1]
 - QMUI 版本: [4.2.3]

**Comment by MoLice** [comment]
无法重现，请提供可复现的 Demo。
<img src="https://user-images.githubusercontent.com/1190261/131372562-76f147bc-477c-48e1-a11a-b844f460d1ba.png" width="300"/>

**Comment by mojimomo** [comment]
> 无法重现，请提供可复现的 Demo。
> <img alt="" width="300" src="https://user-images.githubusercontent.com/1190261/131372562-76f147bc-477c-48e1-a11a-b844f460d1ba.png">

这个问题我也遇到了,然后我修改了QMUIConsoleLogItemCell中的self.backgroundColor = nil;让他变成clearColor就正常了。可能self.backgroundColor = nil之后就默认变成白色了

**Comment by MoLice** [comment]
已发布 [4.5.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.5.0) 修复该问题。

**Comment by mojimomo** [comment]
Thank you for your message, which has been added to a queuing system. You are currently in 352nd place, and can expect to receive a reply in approximately 19 weeks。
