### ISSUE TITLE
点击输入框线程问题

### ISSUE THREAD

**Issue by zhuzhongshen** [Tencent/QMUI_iOS#1278]
**Bug 表现**

=================================================================
Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]
PID: 1382, TID: 558894, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   HomeIOT                             0x0000000100fd85e4 __70+[UITraitCollection(QMUI) _qmui_overrideTraitCollectionMethodIfNeeded]_block_invoke_3 + 148
5   UIKitCore                           0x00000001aa7abc08 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 8739848
6   UIKitCore                           0x00000001aa7abf44 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 8740676
7   UIKitCore                           0x00000001aa7753ec CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 8516588
8   libdispatch.dylib                   0x0000000101affce4 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x0000000101b01528 _dispatch_client_callout + 16
10  libdispatch.dylib                   0x0000000101b131e4 _dispatch_root_queue_drain + 788
11  libdispatch.dylib                   0x0000000101b13970 _dispatch_worker_thread2 + 152
12  libsystem_pthread.dylib             0x00000001f09a9568 _pthread_wqthread + 212
13  libsystem_pthread.dylib             0x00000001f09ac874 start_wqthread + 8
2021-08-03 13:21:03.869301+0800 HomeIOT[1382:558894] [reports] Main Thread Checker: UI API called on a background thread: -[UIWindow traitCollection]
PID: 1382, TID: 558894, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   HomeIOT                             0x0000000100fd85e4 __70+[UITraitCollection(QMUI) _qmui_overrideTraitCollectionMethodIfNeeded]_block_invoke_3 + 148
5   UIKitCore                           0x00000001aa7abc08 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 8739848
6   UIKitCore                           0x00000001aa7abf44 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 8740676
7   UIKitCore                           0x00000001aa7753ec CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 8516588
8   libdispatch.dylib                   0x0000000101affce4 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x0000000101b01528 _dispatch_client_callout + 16
10  libdispatch.dylib                   0x0000000101b131e4 _dispatch_root_queue_drain + 788
11  libdispatch.dylib                   0x0000000101b13970 _dispatch_worker_thread2 + 152
12  libsystem_pthread.dylib             0x00000001f09a9568 _pthread_wqthread + 212
13  libsystem_pthread.dylib             0x00000001f09ac874 start_wqthread + 8
2021-08-03 13:21:18.492305+0800 HomeIOT[1382:559031] XPC connection interrupted
2021-08-03 13:21:18.548731+0800 HomeIOT[1382:559032] [tcp] tcp_input [C2.1:3] flags=[R] seq=1327334496, ack=0, win=0 state=LAST_ACK rcv_nxt=1327334496, snd_una=1601459094
2021-08-03 13:21:18.548904+0800 HomeIOT[1382:559032] [tcp] tcp_input [C2.1:3] flags=[R] seq=1327334496, ack=0, win=0 state=CLOSED rcv_nxt=1327334496, snd_una=1601459094
2021-08-03 13:21:18.634340+0800 HomeIOT[1382:559031] [TPNS MTA] retcode is 0

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ... 
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 14.4]
 - Xcode 版本: [Xcode 12.4]
 - QMUI 版本: [4.2.3]

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 优化该问题。
