### ISSUE TITLE
ios 15 导航栏显示异常 bug

### ISSUE THREAD

**Issue by lijiajunios** [Tencent/QMUI_iOS#1279]
**Bug 表现**
 导航栏需要滑动一下才能正常显示颜色

**截图**
官方 demo 也异常

**如何重现**
1. 下载官网的demo 运行就会复现
2.正常情况下设置了 蓝色的导航栏，进入界面就应该显示蓝色，现在需要滑动一下才会显示蓝色

**预期的表现**
正常情况下设置了 蓝牙的导航栏，进入界面就应该显示蓝色

**其他信息**
 - 设备: iPhone
 - iOS 版本: [iOS 15.0]
 - Xcode 版本: [Xcode 13.0]
 - QMUI 版本: [4.2.3]

**Comment by MoLice** [comment]
#1265
