### ISSUE TITLE
iOS14.5，iPad状态栏、tabbar、navibar高度不正确

### ISSUE THREAD

**Issue by BorisDuan** [Tencent/QMUI_iOS#1280]
这是我用系统方法获取的iOS14.5，iPad Pro，12.9英寸，模拟器
NSLog(@"%f",[UIApplication sharedApplication].windows.firstObject.windowScene.statusBarManager.statusBarFrame.size.height);
    NSLog(@"%f",self.navigationController.navigationBar.bounds.size.height);
    NSLog(@"%f",self.tabBarController.tabBar.bounds.size.height);
这是QMUI宏定义方法
    NSLog(@"%f",StatusBarHeight);
    NSLog(@"%f",NavigationBarHeight);
    NSLog(@"%f",TabBarHeight);
-------------------------------------------
这是输出信息，前三个是系统方法获取到，后三个是QMUI宏定义获取到的
--->24.000000
--->50.000000
--->65.000000
--->24.000000
--->0.000000
--->50.000000
    

**其他信息**
 - 设备: [例如模拟器iPad Pro 12.9 inch]
 - iOS 版本: [iOS 14.5]
 - Xcode 版本: [Xcode 12.5.1]
 - QMUI 版本: [4.2.3]

**Comment by MoLice** [comment]
无法复现：

![image](https://user-images.githubusercontent.com/1190261/145951990-8f666924-ebec-4c5a-a540-460fdc58ff09.png)


![image](https://user-images.githubusercontent.com/1190261/145951859-4a05c349-4c99-4095-ad44-fc2affc9a6df.png)
