### ISSUE TITLE
[UIKit Bug] App 处于后台时修改 UIAppearance 里 UIImage 类型的属性很大几率导致第三方键盘 crash

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#1281]
**Bug 表现**
1. 系统设置里只保留一个键盘，且为第三方键盘，如搜狗、百度（这一步非必须，只是为了便于观察现象）。
2. 在使用 QMUI 的 App 里（例如 QMUI Demo、微信读书、企业微信等大型应用）唤起该第三方键盘。
3. 在另一个没使用 QMUI 的 App 里（例如系统的 App）唤起该第三方键盘。
4. 不断重复在两个 App 之间切换，过一会即可看到第三方键盘无法显示，被一个系统默认键盘代替（意味着此时第三方键盘被杀掉，且系统尝试重新创建它时无法在足够快的时间内完成，于是用系统默认键盘代替），如以下录屏所示：
<video src="https://user-images.githubusercontent.com/1190261/128603925-c122f0a1-634a-468c-9a59-f6aabaceeb78.mov"></video>

**预期的表现**
不管进行多少次 App 间的切换，都不应该导致第三方输入法频繁被杀掉。

**其他信息**
 - 设备: All
 - iOS 版本: All
 - Xcode 版本: All

**Comment by jiasongs** [comment]
我也遇到了这个问题，我屏蔽了［在后台切换主题］的代码之后就没有用户反馈过了。不知是不是同样的问题。

**Comment by MoLice** [comment]
连接真机，通过系统控制台可得知在出现 bug 现象时，第三方输入法会收到内存警告，在没使用 QMUI 的 App 之间互相切换不会引起这个内存警告，证明是 QMUI 里的某些代码引起该问题。
<img width="800" src="https://user-images.githubusercontent.com/1190261/128604177-f513b4df-2d5b-48bb-b36f-26577d8583d5.png">

自己创建一个 Custom Keyboard Extension，按照 issue 的重现步骤操作后，我们的输入法确实遇到了系统内存限制的报错（上限 66MB，不同的 iOS 版本、iPhone 设备，该上限不同，所以老旧机器更容易触发该现象）。
<img src="https://user-images.githubusercontent.com/1190261/128604308-da0e17aa-969e-406c-a95a-6496537b2324.png" width="800" />

在不断重复的测试过程中可看到，宿主应用（Host App，也即当前正在使用键盘的 App）更新 UIAppearance 的行为会通信给第三方键盘：
<img width="800" src="https://user-images.githubusercontent.com/1190261/128604436-e2a1bba1-8a94-4e94-8c02-81e923a3fb77.png">

进而对 UIAppearance 中 UIImage 类型的对象进行反序列化：
<img src="https://user-images.githubusercontent.com/1190261/128604693-0fda8003-e607-48a0-8fcc-f007bc406eed.png" width="400" />

通过在第三方键盘 Target 里 hook `-[UIImage initWithCoder:]` 可知在 Host App 退到后台时，第三方键盘里进行了上千次的图片生成操作，而且每次都比上一次的次数要翻很多倍。
<img width="800" src="https://user-images.githubusercontent.com/1190261/128606024-081072fa-045e-44b8-a843-35f11b631e7a.png">

<img width="800" src="https://user-images.githubusercontent.com/1190261/128606411-67b0c262-5b53-4710-9948-5b1562e23ca6.png">

而且按地址过滤后可看到其中有大量重复的 image 操作，这现象明显是异常的。
<img width="600" src="https://user-images.githubusercontent.com/1190261/128606459-5660dff7-6347-4a89-8105-6a12665d60a7.png">

以 QMUI Demo 为例，通过这些图片的 `size`（width = 4, height = 88） 可知是 `UINavigationBar` 的 `backgroundImage`、`shadowImage` 等图片，也即业务 App 自己设置的图片。而 QMUI Demo 里是在配置表里设置这些图片的，当系统的 DarkMode 发生切换时，会重新应用配置表，将图片设置到 UINavigationBar.appearance 的同时，遍历当前界面里的所有 UINavigationBar 实例，修改它们的样式。
<img src="https://user-images.githubusercontent.com/1190261/128607111-e22c83d2-865a-48af-8400-ef4886db9576.png" width="800" />

结合上述的 crash 堆栈，尝试将上面截图里的①注释掉，发现问题得到解决。

将 backgroundImage 以 UINavigationBar.appearance 的方式使用是一个常规的操作，本身应该没问题，而问题出现在切换 App 时，此时 QMUI 会重新应用配置表，再走一次 UIAppearance 的更新，猜测可能是时机问题引起的。于是新建一个空项目，在 `- [UIViewController traitCollectionDidChange:]` 里设置 `UIAppearance`，当切换 App 时，系统会将 App 快速切换到 Light、Dark，分别对 App 截两张图，此时会触发 `traitCollectionDidChange:`，进而触发 `UIAppearance` 的更新，然后成功重现该问题。[点击下载测试 Demo](https://github.com/Tencent/QMUI_iOS/files/6949426/TestKeyboardHostApp.zip)
<img src="https://user-images.githubusercontent.com/1190261/128607544-33be933d-4fcb-4202-8164-4af9332bf960.png" width="800" />

到这里该 Bug 可以定性为系统 Bug：在 App 处于后台时修改 UIAppearance 里的 UIImage 类型的属性，会导致第三方键盘在短时间内异常进行大量 UIImage 的反序列化操作，最终触达系统对输入法分配的内存上限，输入法 crash。

进一步测试可知几个信息点：
1. 通过 UIAppearance 设置的任意 image 都会在第三方输入法的第二次及后续的启动时反序列化（-[UIImage initWithCoder:]），设置多少次 appearance 的 image 就会调用多少次 initWithCoder。即便对同一个 UIAppearance 设置相同属性的 image，也不是覆盖性质，而是增加，每设置一次都会产生一次 initWithCoder:。
2. 第一次显示键盘不会触发，第二次开始及后续都会触发。如果键盘正在显示时切换 App（也即把之前的 App 推到后台），那么重新唤醒该 App 时，键盘视为一次新的显示。
3. 正常情况下使用 UIAppearance 也会触发第三方键盘调用 initWithCoder:，但设置多少次就会调用多少次，这通常不会导致 OOM，也不会像 issue 里描述的那样以几倍的规模扩大，且倍数还越来越大。

至此该系统 Bug 的解决方式就很清晰了：在设置 UIAppearance 前判断当前 UIApplication.sharedApplication.applicationState != UIApplicationStateActive 则不设置。
由于该问题没有合适的统一修复的方法，因此 QMUI 仅修复自身的场景，不提供通用的方案。业务项目里非 QMUI 的代码如果也有这种操作，也需自行判断 applicationState。

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 修复该问题。
