### ISSUE TITLE
今天上架被拒了，请问一下这个应该怎么处理？

### ISSUE THREAD

**Issue by MrChen-Git** [Tencent/QMUI_iOS#1284]
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/QMUIKit.framework/QMUIKit: navigationBarBackgroundImage, navigationBarStyle, navigationBarTintColor. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by MoLice** [comment]
暂时可以自行重命名 QMUI 里的这些方法。

**Comment by MoLice** [comment]
已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 修复该问题，业务需要跟着新版本重命名。
