### ISSUE TITLE
在iOS10.2.1系统，searchBar.qmui_alwaysEnableCancelButton 方法可能会引起崩溃

### ISSUE THREAD

**Issue by BzHuang** [Tencent/QMUI_iOS#1287]
**Bug 表现**
在iOS10.2.1系统，searchBar.qmui_alwaysEnableCancelButton 方法可能会引起崩溃

**截图**
![20210823-112153](https://user-images.githubusercontent.com/13215355/130385733-63a40c13-c292-42a0-b891-93a9c45a7d77.png)

**如何重现**
线上监控到崩溃，如何重现

**预期的表现**

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 10.2.1]
 - Xcode 版本: [Xcode 12.5]
 - QMUI 版本: [4.2.3]

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/1232
