### ISSUE TITLE
自定义专场动画如何隐藏导航栏？

### ISSUE THREAD

**Issue by iOkay** [Tencent/QMUI_iOS#1292]
version：4.3.0
自定义Push、Pop的转场动画，导航栏有渐隐渐显动画。如何修改渐隐渐显动画或者如何隐藏？
![WX20210906-155505](https://user-images.githubusercontent.com/2063427/132181523-f346e380-46a9-4a76-9fae-3aafc6b050f2.png)

**Comment by MoLice** [comment]
提供的信息太少，无从下手
