### ISSUE TITLE
通过图片设置导航栏背景尺寸适配问题

### ISSUE THREAD

**Issue by xtinput** [Tencent/QMUI_iOS#1293]
目前刘海屏机型导航栏有多个尺寸，设置背景图片的时候会存在图片尺寸不够宽或高而平铺，或者是被严重裁剪。希望能做个图片尺寸适配。

**Comment by MoLice** [comment]
查看 Apple 文档：https://developer.apple.com/documentation/uikit/uiimage/1624102-resizableimagewithcapinsets
