### ISSUE TITLE
使用QMUITextView，实现代理 - (BOOL)textViewShouldReturn:(QMUITextView *)textView ，会与RAC冲突，造成死循环

### ISSUE THREAD

**Issue by BinBear** [Tencent/QMUI_iOS#1298]
**Bug 表现**
问题的具体描述
使用QMUITextView，实现代理 - (BOOL)textViewShouldReturn:(QMUITextView *)textView ，会与RAC冲突，造成死循环

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

Trapped uncaught exception 'NSInvalidArgumentException', reason: '-[RACDelegateProxy textViewShouldReturn:]: unrecognized selector sent to instance 0x280ba2400' 
(
	0   CoreFoundation                      0x00000001a8b55880 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1202304
	1   libobjc.A.dylib                     0x00000001bdb71c50 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a8a5c95c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 182620
	3   CoreFoundation                      0x00000001a8b58438 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1213496
	4   CoreFoundation                      0x00000001a8b5a740 _CF_forwarding_prep_0 + 96
	5   CoreFoundation                      0x00000001a8b5a8f4 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1222900
	6   CoreFoundation                      0x00000001a8a31df8 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 7672
	7   CoreFoundation                      0x00000001a8a323cc 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 9164
	8   QMUIKit                             0x0000000104f5808c -[QMUIMultipleDelegates forwardInvocation:] + 720
	9   CoreFoundation                      0x00000001a8b58174 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1212788
	10  CoreFoundation                      0x00000001a8b5a740 _CF_forwarding_prep_0 + 96
	11  QMUIKit                             0x0000000104f9aa80 -[_QMUITextViewDelegator textView:shouldChangeTextInRange:replacementText:] + 892
	12  CoreFoundation                      0x00000001a8b5a8f4 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1222900
	13  CoreFoundation                      0x00000001a8a31df8 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 7672
	14  CoreFoundation                      0x00000001a8a323cc 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 9164
	15  QMUIKit                             0x0000000104f5808c -[QMUIMultipleDelegates forwardInvocation:] + 720
	16  CoreFoundation                      0x00000001a8b58174 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1212788
	17  CoreFoundation                      0x00000001a8b5a740 _CF_forwarding_prep_0 + 96
	18  UIKitCore                           0x00000001ab88d40c 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 16036876
	19  UIKitCore                           0x00000001ab2d6058 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10043480
	20  UIKitCore                           0x00000001ab2eccbc 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10136764
	21  UIKitCore                           0x00000001ab2eab70 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10128240
	22  UIKitCore                           0x00000001ab315b04 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10304260
	23  UIKitCore                           0x00000001ab2eab2c 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10128172
	24  UIKitCore                           0x00000001ab300528 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10216744
	25  UIKitCore                           0x00000001ab2c984c 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 9992268
	26  UIKitCore                           0x00000001ab2ffe90 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10215056
	27  UIKitCore                           0x00000001ab2ff068 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10211432
	28  UIKitCore                           0x00000001ab23468c 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 9381516
	29  UIKitCore                           0x00000001ab30a108 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10256648
	30  UIKitCore                           0x00000001ab30a3bc 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10257340
	31  UIKitCore                           0x00000001ab3177dc 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10311644
	32  UIKitCore                           0x00000001ab316210 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10306064
	33  UIKitCore                           0x00000001ab30a318 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10257176
	34  UIKitCore                           0x00000001ab309e18 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 10255896
	35  UIKitCore                           0x00000001ab5504e4 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 12641508
	36  UIKitCore                           0x00000001ab551e4c 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 12648012
	37  UIKitCore                           0x00000001ab52b1d4 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 12489172
	38  UIKitCore                           0x00000001ab5b50ec 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 13054188
	39  UIKitCore                           0x00000001ab5b80a4 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 13066404
	40  UIKitCore                           0x00000001ab5af550 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 13030736
	41  CoreFoundation                      0x00000001a8ad176c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 661356
	42  CoreFoundation                      0x00000001a8ad1668 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 661096
	43  CoreFoundation                      0x00000001a8ad0960 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 657760
	44  CoreFoundation                      0x00000001a8acaa8c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 633484
	45  CoreFoundation                      0x00000001a8aca21c CFRunLoopRunSpecific + 600
	46  GraphicsServices                    0x00000001c0697784 GSEventRunModal + 164
	47  UIKitCore                           0x00000001ab50aee8 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 12357352
	48  UIKitCore                           0x00000001ab51075c UIApplicationMain + 168
	49  HotCoin                             0x0000000100f40fc0 main + 132
	50  libdyld.dylib                       0x00000001a878a6b0 21B19919-1334-38BC-B233-896E929945E0 + 5808
)

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 14.4.1]
 - Xcode 版本: [Xcode 12.5]
 - QMUI 版本: [4.3.0]

**Comment by MoLice** [comment]
请提供具体的代码写法，我按照 #970 的代码没有问题。
