### ISSUE TITLE
iOS15导航栏颜色设置

### ISSUE THREAD

**Issue by wiilsliang** [Tencent/QMUI_iOS#1304]
sdk什么时候更新？在iOS15设置导航栏颜色旧方法不起作用了

**Comment by xixisplit** [comment]
临时解决方法.将下方代码.
`    if (@available(iOS 15.0, *)) {
        UINavigationBarAppearance *appearance = [UINavigationBarAppearance new];
        [appearance configureWithDefaultBackground];
        appearance.backgroundImage = [navigationBar backgroundImageForBarMetrics:(UIBarMetricsDefault)];
        appearance.shadowImage = [navigationBar shadowImage];
        navigationBar.scrollEdgeAppearance = appearance;
        navigationBar.standardAppearance = appearance;
    }`

放到 @implementation QMUICommonViewController (QMUINavigationController)  270行.
和 UINavigationController+NavigationBarTransition.m  505 行.
暂时没有测出其他问题.如果有其他问题.自行调试

**Comment by MoLice** [comment]
#1265

**Comment by wiilsliang** [comment]
> #1265

大哥，pod导的。。。
