### ISSUE TITLE
iOS15后UINavigationBar默认黑色,，麻烦更新一下哇，谢谢！

### ISSUE THREAD

**Issue by ysfox** [Tencent/QMUI_iOS#1307]
iOS15后UINavigationBar默认黑色,，麻烦更新一下哇，谢谢！

**Comment by MoLice** [comment]
#1265 
恳求大家提 issue 前先搜一下，这个问题已经置顶了，重复提100个也没有意义。
![image](https://user-images.githubusercontent.com/1190261/135053849-72bc1155-5497-4dc6-ac44-e96759fed95c.png)
