### ISSUE TITLE
Crash at "在手势进行过程中把手势禁用，可能让界面状态出现错乱"

### ISSUE THREAD

**Issue by Mrkinpa** [Tencent/QMUI_iOS#1308]
**截图**
https://s3.bmp.ovh/imgs/2021/09/e5340cd5cbf281b3.png

**如何重现**
不定时随处可触发

**预期的表现**
正常使用app

**其他信息**
 - 设备: iPhone 11 Pro Max、iPhone X
 - iOS 版本: [iOS 14.6]
 - Xcode 版本: [Xcode 13]
 - QMUI 版本: 最新

**Comment by PreSwift** [comment]
我也遇到同样的问题，在QMUITextField中试图移动光标时一定会出现此问题。

**Comment by MoLice** [comment]
已发布 [4.4.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.0) 修复该问题。
