### ISSUE TITLE
iphone13 应用进入后台状态栏变成白色，进入前台后不会恢复

### ISSUE THREAD

**Issue by Z-hui** [Tencent/QMUI_iOS#1311]
iphone13 应用进入后台状态栏变成白色，进入前台后不会恢复，调用update状态栏也无法修复正确

**Comment by appll** [comment]
这个问题我也遇到了，请问有解决方案吗？

**Comment by SmallMX** [comment]
我也遇到了，支付宝支付很大概率会遇到这个问题，是QMUI的Bug吗？

**Comment by JxJPu9bD** [comment]
主要是因为 iOS15 对导航栏做了处理, 目前的默认实现无法解决问题, 可以先修改源码

**Comment by SmallMX** [comment]
> JxJPu9bD

这里说的是状态栏，iOS14我就遇到了。。。。

**Comment by MoLice** [comment]
> > JxJPu9bD
> 
> 这里说的是状态栏，iOS14我就遇到了。。。。

@SmallMX 排查过确定了非业务的问题了？

**Comment by MoLice** [comment]
QMUI 4.3.0 及以前的版本，配置表里设置 statusBar 样式的开关为 BOOL 类型的 `StatusbarStyleLightInitially`，该开关在设置为 `YES` 时对应的值为 `UIStatusBarStyleLightContent`，表达上没有歧义，不管如何固定都是白色。

但在设置为 `NO` 时，对应的值为 `UIStatusBarStyleDefault`，由于 iOS 13 增加了 Dark Mode，因此 `UIStatusBarStyleDefault` 在 iOS 12 及以前可以表达固定黑色，但 iOS 13 及以后会自动根据当前 App 是否为 Dark Mode 来展示不同的颜色，这就导致如果业务项目希望 statusBar 呈现为固定的黑色，就无法做到——因为你设置为 NO 时，Dark Mode 下也会自动变为白色。

这属于 QMUI 配置表的开关设计没有跟上 iOS 版本迭代引起的问题，因此 4.4.0 开始，我们将配置表的 `StatusbarStyleLightInitially` 删除并替换为新的 `DefaultStatusBarStyle`，类型为 `UIStatusBarStyle`，所以你可以精准控制你的 App 默认样式，就不会出现该问题了。

**Comment by MoLice** [comment]
已发布 [4.4.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.0) 优化该问题。
