### ISSUE TITLE
配置表 qmui_getProjectClassList 获取项目类数量为0

### ISSUE THREAD

**Issue by FKV587** [Tencent/QMUI_iOS#1312]
设备：iPhone 8
 系统：iOS 14.1
 Xcode 版本：13.0
 QMUI iOS 版本：4.3.0
 qmui_getProjectClassList 获取类数量为0
 objc_getClassList 系统获取类数量为36939
![image](https://user-images.githubusercontent.com/8774976/139395633-d14e1cd0-843f-47df-8bb2-376daf311a82.png)

**Comment by MoLice** [comment]
注意，XCTest 运行时无法加载配置表，且 `getProjectImageHeader()` 得到的也为 nil，也会命中 QMUIConfiguration.m 里的检测，所以 QMUIConfiguration.m applyInitialTemplate 方法会屏蔽 XCTest 的场景。

测试过以 .a 形式（CocoaPods 里屏蔽掉 `use_frameworks!`）引入的 QMUI，也能正常获取 classes。

**Comment by MoLice** [comment]
已发布 [4.4.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.0) 修复该问题。

**Comment by moshiwu** [comment]
<img width="1917" alt="image" src="https://github.com/Tencent/QMUI_iOS/assets/15337294/1519658e-be9c-40d6-b83b-25888743fed0">

iOS18会触发这行断言，查找对比后发现DEBUG模式下，二进制不包含__objc_classlist，而会在另一产物xxxx.debug.dylib里

**Comment by moshiwu** [comment]
https://github.com/Tencent/QMUI_iOS/pull/1555/commits/b81a43407489c07e06e2861fae338a51e9c22dd4
可通过这段代码解决
