### ISSUE TITLE
框架交换了description，导致利用self做key的字典拿不到对象

### ISSUE THREAD

**Issue by darvintang** [Tencent/QMUI_iOS#1314]
利用"\(self)"做key存储控制器，然后设置控制器标题后再从字典里拿不到控制器

能不能不要过分的hook？

**Comment by MoLice** [comment]
理解你的场景，综合考虑，我依然认为 hook description 得到的收益远比保持你的这种场景下正常使用要利大于弊。
你的这种情况，有很多更稳定合理的其他方式可以选择，例如直接拿 self 的指针。description 就算不 hook，很多时候也会不断变化，例如涉及到 tableView 的地方，系统会输出当前的 contentOffset，相信这应该不符合你作为 key 的诉求。

建议还是更换业务的实现方式，即便不引入 QMUI，这个做法对业务本身也是有好处的。
