### ISSUE TITLE
QMUIKit太重了，通过Hook改变了很多系统的API行为

### ISSUE THREAD

**Issue by darvintang** [Tencent/QMUI_iOS#1315]
**现存问题或期望目标**
框架过度使用hook，影响系统的api行为，更是导致很多莫名其妙的日志和崩溃。框架太过臃肿

**Comment by MoLice** [comment]
综合以往的 crash issue，当一个业务项目引入 QMUI 后产生的 crash，绝大部分是以下两种情况：

**Comment by darvintang** [comment]
是否可以考虑不在+load里面hook，而是开发者自行调用方法开启相关行为

**Comment by MoLice** [comment]
> 是否可以考虑不在+load里面hook，而是开发者自行调用方法开启相关行为

这是出于易用性的考虑，如果按你说的方式做，换来的负面影响是每一个功能都要开发者手动做一些配置、写一些代码，然后才能用。而 QMUI 的功能特别多，其中拓展系统控件的功能，绝大部分都基于 hook 实现的，这对使用者的体验是一种灾难。综合考虑我们选择了易用性而不是准确可控。某些确实有较大风险的，在配置表里也有现成的开关控制。如果你认为哪些 hook 风险较大，应该提供对应的开关，可以提 issue 对具体的个案来讨论。

**Comment by darvintang** [comment]
目前我遇到的WKNavigationDelegate几个代理方法在swift下会崩溃，原因是WKNavigationDelegate的几个接口在swift下同名多态了

**Comment by MoLice** [comment]
> 目前我遇到的WKNavigationDelegate几个代理方法在swift下会崩溃，原因是WKNavigationDelegate的几个接口在swift下同名多态了

说一下具体的场景？或者提供一个 Demo？`WKNavigationDelegate` + Swift，应该有几百几千的使用 QMUI 的项目也是存在这种代码的，但是并没有收到他们提出的反馈。

**Comment by darvintang** [comment]
例如在同时实现：webView:decidePolicyForNavigationResponse:decisionHandler:和webView:decidePolicyForNavigationAction:decisionHandler:两个接口的时候

**Comment by MoLice** [comment]
> 例如在同时实现：webView:decidePolicyForNavigationResponse:decisionHandler:和webView:decidePolicyForNavigationAction:decisionHandler:两个接口的时候

你是怎么确信这个问题是由 QMUI 引起的？

**Comment by darvintang** [comment]
webView:decidePolicyForNavigationResponse:decisionHandler:和webView:decidePolicyForNavigationAction:decisionHandler:在swift下都是webView(_:decidePolicyFor:decisionHandler:)

**Comment by darvintang** [comment]
> > 例如在同时实现：webView:decidePolicyForNavigationResponse:decisionHandler:和webView:decidePolicyForNavigationAction:decisionHandler:两个接口的时候
> 
> 你是怎么确信这个问题是由 QMUI 引起的？

在未接入qmuikit的时候没有崩溃，接入后就崩溃了

**Comment by MoLice** [comment]
建议还是提供 Demo，单纯靠你目前提供的信息，是无法区分出来到底是不是 QMUI 的问题的（可以参考上面第2条评论里说的两种场景）。
