### ISSUE TITLE
如何去除QMUI对UIGestureRecognizer的依赖

### ISSUE THREAD

**Issue by Mrkinpa** [Tencent/QMUI_iOS#1316]
频繁出现一下的奔溃
QMUIAssert(NO, @"UIGestureRecognizer (QMUI)", @"在手势进行过程中把手势禁用，可能让界面状态出现错乱！");

复现:
在输入框移动光标时

目标:
如何去除

**Comment by MoLice** [comment]
先本地注释掉这行代码即可，等新版发布。

**Comment by MoLice** [comment]
已发布 [4.4.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.0) 修复该问题。
