### ISSUE TITLE
UITraitCollection (QMUI)中的load方法可能引发崩溃

### ISSUE THREAD

**Issue by chen-shuang-lin** [Tencent/QMUI_iOS#1318]
**Bug 表现**
项目集成了zoom会议SDK，真机在进入会议时崩溃，模拟器正常。经排查发现最终问题是由UITraitCollection (QMUI)中的load方法导致的。
` info.dli_sname` 有可能为NULL，而` [NSString stringWithUTF8String:info.dli_sname]` 未做保护引发崩溃

**截图**
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/24601327/140877350-6d5879e2-1cba-4378-945d-e3556f9ddb16.png">

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/24601327/140876932-579bb276-1feb-4acd-991d-a04e25892656.png">

**如何重现**
1. 集成zoom会议SDK，调用加入会议，引发崩溃

**预期的表现**
正常情况下，应该不崩溃

**其他信息**
 - 设备: iPhone7
 - iOS 版本: iOS 15.0.2
 - Xcode 版本: Xcode 12.5
 - QMUI 版本: 4.3.0

**Comment by MoLice** [comment]
已发布 [4.4.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.0) 修复该问题。
