### ISSUE TITLE
QMUITableViewCell 初始化方法在swift中导致内存问题

### ISSUE THREAD

**Issue by ziruozimi** [Tencent/QMUI_iOS#1320]
**Bug 表现**
QMUITableViewCell 初始化方法
```oc
- (instancetype)initForTableView:(UITableView *)tableView withStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier {
    self.initByTableView = YES;
    if (self = [self initWithStyle:style reuseIdentifier:reuseIdentifier]) {
        self.parentTableView = tableView;
        [self didInitializeWithStyle:style];// 因为设置了 parentTableView，样式可能都需要变，所以这里重新执行一次 didInitializeWithStyle: 里的 qmui_styledAsQMUITableViewCell
    }
    return self;
}
```
在swift中
```swift
final class DemoTableViewCell: QMUITableViewCell {
    let label = DemoLabel()
}
```
label会被初始化两次，当退出页面时还有一个label存在于内存中

**截图**
![image](https://user-images.githubusercontent.com/15374531/141936716-c1269f0c-58fb-4d4f-8ae1-ed42f8ab0984.png)
![image](https://user-images.githubusercontent.com/15374531/141936926-54e58ad7-0bc2-453a-9264-2dc9a353863f.png)
![image](https://user-images.githubusercontent.com/15374531/141936995-600ca123-ce28-4f29-aec9-16571ebf74aa.png)

**如何重现**
[Demo.zip](https://github.com/Tencent/QMUI_iOS/files/7544039/Demo.zip)

**预期的表现**
如果调用super则表现正常
```oc
- (instancetype)initForTableView:(UITableView *)tableView withStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier {
    self.initByTableView = YES;
    if (self = [super initWithStyle:style reuseIdentifier:reuseIdentifier]) {
        self.parentTableView = tableView;
        [self didInitializeWithStyle:style];// 因为设置了 parentTableView，样式可能都需要变，所以这里重新执行一次 didInitializeWithStyle: 里的 qmui_styledAsQMUITableViewCell
    }
    return self;
}
```

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 14.6]
 - Xcode 版本: [Xcode 12.5.1]
 - QMUI 版本: [4.3.0]

**Comment by MoLice** [comment]
已发布 [4.4.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.0) 修复该问题。

**Comment by MoLice** [comment]
发现 4.4.0 的修改方式会导致以下问题：

业务某个 cell 继承自 `QMUITableViewCell`。当业务要重写 init 方法时，他沿用系统默认的思路，去重写 `initWithStyle:reuseIdentifier:` 方法，然后在业务 vc 里使用这个 cell 时又是用 QMUI 提供的 `initForTableView:withStyle:` 系列方法去初始化。

如果这种场景，在升级到 4.4.0 后就会发现 initForTableView 调用时无法触发 cell 内部重写的 initWithStyle:。

**Comment by MoLice** [comment]
@ziruozimi  方便的话可以加微信沟通一下这个 issue 的细节：
![image](https://user-images.githubusercontent.com/1190261/145174925-94df9896-8563-4ae5-846a-dbe7cdea017f.png)

**Comment by MoLice** [comment]
已发布 [4.4.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.1)，回退该修改，这种情况目前暂无合适的建议，可以考虑业务换个写法。
