### ISSUE TITLE
求问QMUI新版本发布前，发布APP用哪个版本的Xcode编译比较好

### ISSUE THREAD

**Issue by eric0815** [Tencent/QMUI_iOS#1321]
本来想等QMUI新版本发布后再用Xcode13打包发布的，但是目前看还需要一段时间，用户催的紧，只能先发布一个版本解决iOS15的兼容性问题。
请问这种情况下，推荐用哪个版本的Xcode编译比较好。
谢谢谢谢。

**Comment by codingiran** [comment]
<= 12.5.1
