### ISSUE TITLE
QMUIDialogSelectionViewController  content 背景颜色无法修改

### ISSUE THREAD

**Issue by MrDomin** [Tencent/QMUI_iOS#1323]
setContentViewBackgroundColor
tableView.setBackgroundColor都无效

**Comment by MoLice** [comment]
无法重现：
![image](https://user-images.githubusercontent.com/1190261/142414923-b770e96f-24ed-4797-911b-71a64758b7ae.png)

**Comment by MrDomin** [comment]
我使用cocos creator创建的iOS工程，这边是复现的demo，麻烦帮忙看一下
https://xyx-1253482990.cos.ap-guangzhou.myqcloud.com/TEST/ios.zip

**Comment by MrDomin** [comment]
> 无法重现： ![image](https://user-images.githubusercontent.com/1190261/142414923-b770e96f-24ed-4797-911b-71a64758b7ae.png)

我使用cocos creator创建的iOS工程，这边是复现的demo，麻烦帮忙看一下
https://xyx-1253482990.cos.ap-guangzhou.myqcloud.com/TEST/ios.zip

**Comment by MoLice** [comment]
Demo 无法运行。
![image](https://user-images.githubusercontent.com/1190261/142577325-71569638-00c0-499c-bd5e-f5d7c4ed94ec.png)

**Comment by MrDomin** [comment]
> Demo 无法运行。 ![image](https://user-images.githubusercontent.com/1190261/142577325-71569638-00c0-499c-bd5e-f5d7c4ed94ec.png)

抱歉，我忘了这个要依赖cocos creator的引擎运行，我这边主要是想禁用深色模式，深色模式下，tableview的背景变成了深色，但是标题和底部按钮的背景色并没有变成深色，这边使用了自定义主题，且手动设置了主题，但是还是会受深色模式影响
