### ISSUE TITLE
iOS 15，当状态栏隐藏时，StatusBarHeightConstant 在 12 mini 和 13 mini 下的返回值不准确

### ISSUE THREAD

**Issue by nevsee** [Tencent/QMUI_iOS#1326]
12mini和13mini高度为50

**Comment by MoLice** [comment]
并没有错？50是哪里测到的？
![image](https://user-images.githubusercontent.com/1190261/145949208-7355693c-b62f-4986-b476-e6fe899a22a4.png)

**Comment by nevsee** [comment]
![企业微信截图_377b5285-1ef8-4fdb-903f-1ad5cd480086](https://user-images.githubusercontent.com/42122949/145960474-6ddf4da5-1cbf-461d-90cc-007016e7e6d9.png)

难道是iOS15 才会这样？

**Comment by MoLice** [comment]
以 iPhone 12 mini 为例。

在 iOS 14 里，这几个的值为：
```
StatusBarHeight = 44;
StatusBarHeightConstant = 44;
CGRectGetHeight(UIApplication.sharedApplication.statusBarFrame) = 44;
navigationBar.minY = 50; // 关键在这里，statusBar 底部是44，navigationBar 顶部却是 50，意味着中间有6的空隙
navigationBar.maxY = 94;// 对业务的内容布局无影响，不管 iOS 14、15 都是94
```

在 iOS 15 里，这几个的值为：
```
StatusBarHeight = 50;
StatusBarHeightConstant = 50;
CGRectGetHeight(UIApplication.sharedApplication.statusBarFrame) = 50;
navigationBar.minY = 50;// iOS 15 里两个 bar 从 frame 的角度来看是紧贴在一起的
navigationBar.maxY = 94;// 对业务的内容布局无影响，不管 iOS 14、15 都是94
```

不清楚系统在 iOS 14 下为什么会有一个44一个50的区别，由于 QMUI 的宏的值与系统动态获取的值是一致的，且只要业务布局统一都以 `UIViewController.qmui_navigationBarMaxYInViewCoordinator` 为参考标准，就不会表现出这种差异，所以 QMUI 不对这个情况进行处理。

**Comment by MoLice** [comment]
issue 里提的场景应该有个前提，就是 statusBarHidden = YES，issue 当初并没有明确指出，新版本将会重新修复这个问题。

**Comment by MoLice** [comment]
已发布 [4.5.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.5.0) 修复该问题。
