### ISSUE TITLE
NavBarRemoveBackgroundEffectAutomatically 在开启了 AutomaticCustomNavigationBarTransitionStyle 时可能对假 bar 无效

### ISSUE THREAD

**Issue by dongq0916** [Tencent/QMUI_iOS#1330]
**Bug 表现**
iOS 15返回的导航动画上一个界面会有白色透明的遮罩，返回完成时消失
iOS 14以下正常

**截图**

https://user-images.githubusercontent.com/12602855/144188140-179bd2cc-652f-46d9-8a65-fb7dc88d7840.mov

**如何重现**
1. A界面设置导航透明 push到导航不透明的B界面
2. 返回时（包括手势返回）A界面导航上会有白色透明遮罩

**预期的表现**
返回时（包括手势返回）A界面导航上无白色透明遮罩

**其他信息**
 - 设备: iPhone 13 Pro Max
 - iOS 版本: [iOS 15.1]
 - Xcode 版本: [Xcode 13.1]
 - QMUI 版本: [4.4.0]

**Comment by MoLice** [comment]
录屏好像没内容？

**Comment by dongq0916** [comment]
不好意思  这边直接上传好像有问题  
我直接给录屏链接了
https://ewhj.oss-cn-shanghai.aliyuncs.com/RPReplay_Final1638342477.mov

**Comment by MoLice** [comment]
使用 4.4.0 是否有打开这个开关？
![image](https://user-images.githubusercontent.com/1190261/144191094-3ea0b1e6-0754-4d53-9c5e-462b37cb0177.png)

**Comment by dongq0916** [comment]
开了
![image](https://user-images.githubusercontent.com/12602855/144191495-d214c6f8-f5d3-488c-9ad5-7613b58b162a.png)

**Comment by MoLice** [comment]
使用最新 QMUI Demo 测试，未发现该问题。

配置表打开 AutomaticCustomNavigationBarTransitionStyle 的录屏，切换界面时导航栏分成左右两段，互不干扰。
<video src="https://user-images.githubusercontent.com/1190261/144232648-7f778aea-89a1-43b0-9fb0-5bf7a6ba1a02.mov" />


配置表关闭 AutomaticCustomNavigationBarTransitionStyle 的录屏，切换界面瞬间，导航栏会变成新界面的样式，系统默认行为如此。
<video src="https://user-images.githubusercontent.com/1190261/144232830-ac6f7c19-69c9-4ff3-92fe-2167433ec855.mov" />

请继续排查业务代码，或者提供一份 Demo。

**Comment by dongq0916** [comment]
这边简单写个了demo  还是能够复现这个问题
[QMUIDemo.zip](https://github.com/Tencent/QMUI_iOS/files/7638223/QMUIDemo.zip)

**Comment by MoLice** [comment]
该问题是因为 `NavBarRemoveBackgroundEffectAutomatically` 开关对于转场动画过程中的 `_QMUITransitionNavigationBar`，会命中 `UINavigationBar+QMUI.m` 228 行的 `if (!selfObject.superview) return;`，然后后续也没人再触发 `- [_UIBarBackground updateBackground]` 了，导致 `_QMUITransitionNavigationBar` 的 `NavBarRemoveBackgroundEffectAutomatically` 开关无效。在 QMUI 修复该问题之前，请在本地的 @implementation _QMUITransitionNavigationBar 里添加如下代码：

```objc
- (void)didAddSubview:(UIView *)subview {
    [super didAddSubview:subview];
    if (subview == self.qmui_backgroundView) {
        [subview qmui_performSelector:NSSelectorFromString(@"updateBackground") withArguments:nil];
    }
}
```

**Comment by Snail-hash** [comment]
在4.4.0Demo中修改QMUICMI.automaticCustomNavigationBarTransitionStyle = YES;

@implementation _QMUITransitionNavigationBar 中添加
- (void)didAddSubview:(UIView *)subview {
    [super didAddSubview:subview];
    if (subview == self.qmui_backgroundView) {
        [subview qmui_performSelector:NSSelectorFromString(@"updateBackground") withArguments:nil];
    }
}
并未修复导航栏隐藏页面跳转自定义导航栏背景页面的问题

[QMUIDemo_iOS-master.zip](https://github.com/Tencent/QMUI_iOS/files/7708549/QMUIDemo_iOS-master.zip)

入口：Lab标签 -> NavBarHidden

**Comment by MoLice** [comment]
@Snail-hash 你说的是另一个问题，查看 #1335

**Comment by MoLice** [comment]
已发布 [4.4.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.1) 修复该问题。

**Comment by MoLice** [comment]
> 已发布 [4.4.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.1) 修复该问题。

不好意思，这个代码忘了带上 4.4.1，近期会再发个 4.4.2 补上

**Comment by MoLice** [comment]
已发布 [4.4.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.2) 修复该问题。
