### ISSUE TITLE
导航栏动画问题

### ISSUE THREAD

**Issue by ZXCheng** [Tencent/QMUI_iOS#1332]
**Bug 表现**
手势返回动画没有预期的效果

https://user-images.githubusercontent.com/17699101/144346711-a8e7351d-8a38-432b-a01a-4ae31abec181.mp4

**截图**
我的设置

![截屏2021-12-02 上午10 31 09](https://user-images.githubusercontent.com/17699101/144346640-468b491c-463c-4df9-a439-6ef558135e32.png)
![截屏2021-12-02 上午10 31 29](https://user-images.githubusercontent.com/17699101/144346669-06e9b387-42c0-4b9d-9e3a-263c36e3518d.png)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 15.0.2]
 - Xcode 版本: [Xcode 13.0]
 - QMUI 版本: [4.4.0]

**Comment by MoLice** [comment]
看起来好像没有符合 Release Note 的要求？
![image](https://user-images.githubusercontent.com/1190261/144449949-215ee73f-0f68-42c2-945a-3d1ebea40cd7.png)

**Comment by ZXCheng** [comment]
> 看起来好像没有符合 Release Note 的要求？
> ![image](https://user-images.githubusercontent.com/1190261/144449949-215ee73f-0f68-42c2-945a-3d1ebea40cd7.png)
![截屏2021-12-03 上午11 48 38](https://user-images.githubusercontent.com/17699101/144542139-64dff17c-99ec-4af8-983f-66e88e2e1459.png)
还是如视频中一样

**Comment by MoLice** [comment]
麻烦提供一个 Demo

**Comment by MoLice** [comment]
#1330

**Comment by ZXCheng** [comment]
> #1330
![截屏2021-12-06 上午9 28 36](https://user-images.githubusercontent.com/17699101/144773260-7b36c0af-114d-45b4-a35e-adb97c716632.png)

我将截图中选中的代码注释掉，动画效果就正常了

**Comment by MoLice** [comment]
> #1330

#1330 已经给出解决方法，如果用了解决方法依然有问题，或者明确与 #1330 不是同个问题，则请再提供一个 Demo，否则视为同一个 issue 处理。
