### ISSUE TITLE
'_RoundedIntegerFromCGFloat' has different definitions in different modules; definition in module 'QMUIKit.QMUICommonDefines' first difference is function body

### ISSUE THREAD

**Issue by jiangxiaoya** [Tencent/QMUI_iOS#1333]
**Bug 表现**
报错如题

**截图**
![image](https://user-images.githubusercontent.com/12946829/144409511-6e724945-4ed9-4b07-be93-8d188baa03b3.png)

**如何重现**
pod install 后编译就报错

**预期的表现**
不报错

**其他信息**
 - 设备: iPhone X
 - iOS 版本: [iOS 14.8.1, iOS13.5.1]
 - Xcode 版本: [Xcode 13.1]
 - QMUI 版本: [4.2.3]
 - Mac OS 版本：[12.0.1]

**Comment by MoLice** [comment]
搜一下你业务项目用到的所有第三方框架，是否有重复的定义

**Comment by jiangxiaoya** [comment]
> 搜一下你业务项目用到的所有第三方框架，是否有重复的定义

已经搜过了，没有，所以很奇怪

**Comment by MoLice** [comment]
也可以提供一个 Demo 看看

**Comment by jiangxiaoya** [comment]
> 也可以提供一个 Demo 看看

现在项目没报错了，我修改了一下这个报错地方的代码，编译通过后，然后代码在复原就没问题了，从修改到复原期间没有新增任何第三方库，也不知道是哪里出了问题

**Comment by MoLice** [comment]
Xcode 抽风吧
