### ISSUE TITLE
导航动画问题

### ISSUE THREAD

**Issue by dongq0916** [Tencent/QMUI_iOS#1334]
**Bug 表现**
#1330 
写了个demo还是能够复现这个问题
[QMUIDemo.zip](https://github.com/Tencent/QMUI_iOS/files/7646190/QMUIDemo.zip)

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 15.0]
 - Xcode 版本: [Xcode 13.1]
 - QMUI 版本: [4.4.0]

**Comment by MoLice** [comment]
#1330
