### ISSUE TITLE
AutomaticCustomNavigationBarTransitionStyle 在前后两个导航栏的显隐状态不一致时会有问题

### ISSUE THREAD

**Issue by dongq0916** [Tencent/QMUI_iOS#1335]
**Bug 表现**
已用 #1330 临时解决方案
有导航（颜色和配置文件设置的中不同）的A界面push到无导航的B界面 返回时A界面导航暂时显示的是配置文件的颜色
返回完成后显示A界面导航配置应有的颜色

**Demo**
[QMUIDemo.zip](https://github.com/Tencent/QMUI_iOS/files/7674906/QMUIDemo.zip)

**预期的表现**
返回时A界面显示应有的颜色效果

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 15.0]
 - Xcode 版本: [Xcode 13.1]
 - QMUI 版本: [4.4.0]

**Comment by MoLice** [comment]
<img src="https://user-images.githubusercontent.com/1190261/145809104-78bae25c-1f08-4aa4-bdc1-7e69afaba6e4.png" width="600"/>

<img src="https://user-images.githubusercontent.com/1190261/145809406-c30b7dab-5697-482f-929d-fa370ce7f987.png" width="600" />

① 开始切换界面(push/pop)，给左右两个 vc 加上假 bar。
② 把系统 navigationBar 和即将显示的 vc 的假 bar 绑定在一起，系统 bar 的样式更新时都同步到假 bar 上。

如果前后导航栏都是显示的，则到这里就完成导航栏动画了，一切以符合预期的方式运转。
如果前后导航栏显隐状态不一样，在①里并不会给 vc 加上假 bar，而是跳过，等到③里才会判断是否要添加假 bar。而在③的实现里:
<img src="https://user-images.githubusercontent.com/1190261/145810051-47ba78a3-f644-4b46-b9f1-9106f84b6480.png" width="600" />

在④时，为了将当前的系统 bar 样式同步给创建出来的假 bar，会立即做一次“关联又取消关联”的操作，这里“取消关联”会覆盖掉上文②，导致后续系统 bar 的样式变化不会再同步给假 bar，从而出现 issue 里描述的现象。

新版本会修复该问题，在此之前可以将以下文件替换本地的 QMUI 来临时修复：
[UINavigationController+NavigationBarTransition.m.zip](https://github.com/Tencent/QMUI_iOS/files/7703627/UINavigationController%2BNavigationBarTransition.m.zip)

**Comment by MoLice** [comment]
已发布 [4.4.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.1) 修复该问题。
