### ISSUE TITLE
QMUIPopupContainerView与SwiftSwift库冲突

### ISSUE THREAD

**Issue by YHObject** [Tencent/QMUI_iOS#1336]
QMUIPopupContainerView与SwiftSwift库中的borderColor冲突

**Comment by MoLice** [comment]
这个 issue 提得太没效率了...例如 SwiftSwift 是什么库，至少贴个 url...而且 QMUIPopupContainerView 里的 borderColor 属性是 QMUIPopupContainerView 自己的，不是 Category 的形式，所以有冲突也不是 QMUI 的问题，不会处理的。
