### ISSUE TITLE
Swift项目中调用闭包问题

### ISSUE THREAD

**Issue by KellyCoder** [Tencent/QMUI_iOS#1338]
Swift项目中调用以下闭包
QMUIThemeManagerCenter.defaultThemeManager.identifierForTrait = { (trait) -> (NSObject<NSObjectProtocol>) in
                    
                    return "" as NSObject
                }
会包此错误
Cannot assign value of type '(UITraitCollection) -> (NSObject)' to type '((UITraitCollection) -> NSCopying & NSObjectProtocol)?'
怎么调用方式才是正确的呢？

**Comment by jiasongs** [comment]
错误提示很明显 返回一个 `NSCopying & NSObjectProtocol)`
即：
QMUIThemeManagerCenter.defaultThemeManager.identifierForTrait = { (trait) -> (NSCopying & NSObjectProtocol) in
       return "" as NSString
}

**Comment by sunimp** [comment]
```
return "" as NSString
```
