### ISSUE TITLE
4.4.0版本 隐藏导航栏页面跳转自定义导航栏页面 导航栏等页面push完成才展示出来

### ISSUE THREAD

**Issue by Snail-hash** [Tencent/QMUI_iOS#1339]
1、A隐藏导航栏 
2、B实现- (UIImage *)qmui_navigationBarBackgroundImage 重新设置导航栏背景
3、A push B

**Comment by MoLice** [comment]
在 #1335 跟进

**Comment by MoLice** [comment]
已发布 [4.4.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.1) 修复该问题。
