### ISSUE TITLE
与RAC冲突，导致闪退

### ISSUE THREAD

**Issue by BinBear** [Tencent/QMUI_iOS#1341]
**Bug 表现**
问题的具体描述

与RAC冲突，导致闪退

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

![image](https://user-images.githubusercontent.com/13587915/145844086-b0a63e86-5664-4b31-8596-aeb14e33f334.png)

**其他信息**
 - 设备: iPhone
 - iOS 版本: iOS 14.3
 - Xcode 版本: Xcode 13.1
 -  - QMUI 版本: 4.4.0

**Comment by MoLice** [comment]
#1298
