### ISSUE TITLE
swift配置navBarBarTintColor和tabBarBarTintColor不生效，背景色依旧是透明的

### ISSUE THREAD

**Issue by KellyCoder** [Tencent/QMUI_iOS#1342]
![image](https://user-images.githubusercontent.com/42005138/145961872-6cfb265a-10ee-4079-9612-0dbc0ded5ada.png)
![image](https://user-images.githubusercontent.com/42005138/145961927-99d6e70d-f67c-4f3d-b086-a339dcfa55bf.png)

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.0

NavBarUsesStandardAppearanceOnly
