### ISSUE TITLE
导航栏动画问题

### ISSUE THREAD

**Issue by renyufei8023** [Tencent/QMUI_iOS#1346]
**Bug 表现**
问题的具体描述
从一个透明的VC跳转到非透明的VC，pop出来的时候透明VC的导航栏会有一个白色的闪烁

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. 第一个VC导航栏透明
2. 第二个VC导航不透明

**预期的表现**
正常情况下，应该是什么表现
正常情况下应该是透明的，不应该有白色的闪烁

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 15.2]
 - Xcode 版本: [Xcode 12.1]
 - QMUI 版本: [4.4.1]

**Comment by renyufei8023** [comment]
[demo.zip](https://github.com/Tencent/QMUI_iOS/files/7717788/demo.zip)

**Comment by MoLice** [comment]
#1330 的代码忘了带上了，先继续按 1330 评论的写法自己加上，近期再发个小版本处理。

**Comment by MoLice** [comment]
已发布 [4.4.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.2) 修复该问题。
