### ISSUE TITLE
转场存在导航栏主题色闪屏，导致4.4.0这个版本完全无法使用

### ISSUE THREAD

**Issue by Arthas-cn** [Tencent/QMUI_iOS#1347]
**Bug 表现**
转场存在导航栏主题色闪屏

**截图**
![Simulator Screen Shot - iPhone 13 Pro Max - 2021-12-16 at 09 31 07](https://user-images.githubusercontent.com/46341476/146291384-ebbd36ba-89e0-4b9a-b8f0-d75151dd9658.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2021-12-16 at 09 31 08](https://user-images.githubusercontent.com/46341476/146291390-4515f88b-183d-478f-8b75-936905a229b5.png)

**如何重现**
在官方Demo上必定重现。在我自己项目集成中使用也必定重现。
![image](https://user-images.githubusercontent.com/46341476/146290787-fee3e8c5-5989-4054-bda6-98663e40e9b0.png)
![image](https://user-images.githubusercontent.com/46341476/146291083-ab680787-9259-4994-b5c1-52312913d54e.png)
![image](https://user-images.githubusercontent.com/46341476/146291146-aa022d89-07a5-4888-9327-78e872410cad.png)

**预期的表现**
应当是没有主题色过渡。

**其他信息**
 - 设备: 模拟器、iPhone13
 - iOS 版本: iOS 15.0 15.1
 - Xcode 版本: [Xcode 13.1]
 - QMUI 版本: [4.4.0]

**Comment by Arthas-cn** [comment]
如果Button页面，再push一个页面，再pop回到Button页面，也会存在相应的问题

**Comment by MoLice** [comment]
用 4.4.1 的 QMUI Demo 测试没有发现该问题，录屏如下：
<video src="https://user-images.githubusercontent.com/1190261/146322845-f945bf8a-587e-4e3d-a99c-fefea200c169.mov" />

![image](https://user-images.githubusercontent.com/1190261/146323106-23ea70f6-50a8-4240-b35c-037d086d1e88.png)

**Comment by Arthas-cn** [comment]
@MoLice 基于你视频，你在Button界面再点进下一个界面，再回到Button界面,你会发现的。
