### ISSUE TITLE
使用QMUINavigationBarScrollingSnapAnimator并将continuous设置为YES时引发崩溃

### ISSUE THREAD

**Issue by firenessZX** [Tencent/QMUI_iOS#1349]
**Bug 表现**
使用QMUINavigationBarScrollingSnapAnimator对导航栏进行显隐设置并有sectionHeader进行悬停操作引发的崩溃。

**截图**
![image](https://user-images.githubusercontent.com/15721984/146474334-e013d6fe-e115-42f8-b8f1-e8f522c6ed5a.png)

**如何重现**
 #进入QDNavigationBarScrollingSnapAnimatorViewController控制器滚动tableView即可重现。

**预期的表现**
导航栏能够正确显示和隐藏不崩溃，sectionHeader悬停在状态栏下面。

**其他信息**
 - 设备:iPhone X
 - iOS 版本: iOS 15.2
 - Xcode 版本: Xcode 13.2
 - QMUI 版本: 4.4.1
 - demo:
[QMUIDemo_iOS-master.zip](https://github.com/Tencent/QMUI_iOS/files/7731482/QMUIDemo_iOS-master.zip)

**Comment by MoLice** [comment]
1. QMUI Demo 里已经有注释说明需要关闭系统的 contentInset 自适应，否则会和 navigationBar 的显隐冲突，但你去掉了这部分代码，那出了问题也是符合预期的。
![image](https://user-images.githubusercontent.com/1190261/146501754-0359e0f9-7305-4804-9e81-219bd4a74e1c.png)

2. 提 issue 如果是基于 QMUI Demo 改的，请说明清楚你修改的内容，否则我只能凭肉眼一一对比，看你到底改了什么，从而引发了问题。例如这个 issue，你只说 `continuous` 和 `sectionHeaderView`，并没有提及你去掉了本应该存在的 contentInset 的代码，这浪费了我半个小时去 debug，我想是很不应该的？

**Comment by firenessZX** [comment]
那请问如何让导航栏在列表滚动过程中隐藏的同时sectionHeader能悬停在状态栏下方？

**Comment by MoLice** [comment]
> 那请问如何让导航栏在列表滚动过程中隐藏的同时sectionHeader能悬停在状态栏下方？

修改你的 contentInset 到你想要的位置就行了
