### ISSUE TITLE
4.4.1 导航栏返回具有白色半透明的遮罩

### ISSUE THREAD

**Issue by Arthas-cn** [Tencent/QMUI_iOS#1350]
**Bug 表现**
一级界面是隐藏导航栏的，二级界面是导航栏样式改透明图片，3级正常样式。从3级页面退回到2级页面时，导航栏异常，具体看视频。

**截图**

https://user-images.githubusercontent.com/46341476/146482944-188ecd2a-1898-46b9-830f-c8b8d33bf82c.mov

**如何重现**
配置文件，是完全拷贝Demo过来的。
![image](https://user-images.githubusercontent.com/46341476/146483128-b34b1066-0169-4c14-b802-c69b8c48c9f3.png)
![image](https://user-images.githubusercontent.com/46341476/146483193-2bb95e34-0514-4dd0-864f-1234718ab7e9.png)
三级就默认，什么都没有添加

**预期的表现**

**其他信息**
 - 设备: [模拟器、iPhone13]
 - iOS 版本: [iOS 15.0]
 - Xcode 版本: [Xcode 13.1]
 - QMUI 版本: [4.4.1]

**Comment by Arthas-cn** [comment]
@MoLice 大佬能看看是什么问题吗？

**Comment by MoLice** [comment]
#1330
