### ISSUE TITLE
QMUINavigationBarScrollingAnimator 在 scrollView 所在的 viewController 已经被推出 UINavigationController 时，滚动器依然能对 UINavigationBar 产生影响

### ISSUE THREAD

**Issue by WOHANGO** [Tencent/QMUI_iOS#1351]
**Bug 表现**
QDNavigationBarScrollingAnimatorViewController.m中，当 tableView.contentSize.height 小于 self.view.frame.size.height 时，页面上滑几遍后手势返回，NavigationBar的样式有误。暂未想到解决方法

**截图**
https://user-images.githubusercontent.com/20496270/146634904-dcb318c8-6af1-445f-a841-26bb98eca485.mp4

**其他信息**
 - 设备: iPhone
 - iOS 版本: [iOS 15.0.2]
 - Xcode 版本: [Xcode 13.1]
 - QMUI 版本: [4.4.1]

**Comment by MoLice** [comment]
已发布 [4.4.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.4.2) 修复该问题。
