### ISSUE TITLE
4.4.1更新到4.4.2导致程序崩溃

### ISSUE THREAD

**Issue by iosyejingtao** [Tencent/QMUI_iOS#1354]
**Bug 表现**
*** Assertion failure in +[QMUIStringPrivate qmuisafety_NSString], QMUIStringPrivate.m:166
Printing description of logString:
substringFromIndex: 传入了一个超过字符串长度的 index: 24，原字符串为: 2021-11-26T14:30:00.000Z(24)

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.x]
 - QMUI 版本: [4.x.x]

**Comment by BinBear** [comment]
你应该是引入了极光的SDK吧，
QMUI对 substringFromIndex 方法做了hook保护，但是极光的：[JCOREUtilities transformStrToDate:]  方法中用了 substringFromIndex，没有做容错处理，就造成这个问题了

**Comment by BinBear** [comment]
现在的解决方法：
1、将QMUI降回4.4.1
2、等待极光那边修复，但是感觉遥遥无期
3、QMUI提供关闭此hook的方法
4、虽然是断言，但是不可能不在debug下开发，所以弃用QMUI或极光吧

**Comment by MoLice** [comment]
重新更新一下 4.4.2 版本，这个问题下午有重新发布 pod 了

**Comment by iosyejingtao** [comment]
> 现在的解决方法：
> 1、将QMUI降回4.4.1
> 2、等待极光那边修复，但是感觉遥遥无期
> 3、QMUI提供关闭此hook的方法
> 4、虽然是断言，但是不可能不在debug下开发，所以弃用QMUI或极光吧

好的，谢谢作者的解答。
