### ISSUE TITLE
4.2.2 Demo 使用QMUITextView时，点击表情崩溃

### ISSUE THREAD

**Issue by Syrena94** [Tencent/QMUI_iOS#1360]
![64771640832428_ pic](https://user-images.githubusercontent.com/54347987/147717605-71168f12-57e0-4de2-900c-53c66029576c.jpg)

**Comment by MoLice** [comment]
麻烦再说清楚一点吧大兄弟，无法操作出来：
https://user-images.githubusercontent.com/1190261/147724253-a82777b1-4283-43db-98e7-642a24c01b2b.mov

**Comment by Syrena94** [comment]
抱歉，不好意思，我问题没有描述清楚。
我重新下载了最新的demo

https://user-images.githubusercontent.com/54347987/147800942-28ad407e-3bc6-4aa8-af7f-f8ff0e86f285.MP4

报错：
![image](https://user-images.githubusercontent.com/54347987/147800953-a74a6dc1-16e2-4f9c-82f0-fc878037f263.png)

**Comment by MoLice** [comment]
系统的调用，无法区分出来。4.4.3 里改为用 log 了，可以更新一下就不会被 assert 中断。

**Comment by Syrena94** [comment]
麻烦了。非常感谢
