### ISSUE TITLE
iOS 15 Xcode 13 设置导航栏透明，push 出来的页面 头部总是有个半透明毛玻璃效果，没办法透明

### ISSUE THREAD

**Issue by Unrealplace** [Tencent/QMUI_iOS#1361]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.x]
 - QMUI 版本: [4.x.x]

**Comment by Unrealplace** [comment]
<img width="935" alt="截屏2021-12-30 下午5 44 51" src="https://user-images.githubusercontent.com/16250045/147740384-ec5e9648-5863-4ce2-b905-2ff73618255c.png">
这个load 方法会先执行，但是QMUI没有active，block 不生效

**Comment by MoLice** [comment]
因为你没有用配置表，也没打开相对应的开关...
