### ISSUE TITLE
可否继续支持qmui_badgeBorderWidth跟qmui_badgeBorderColor属性

### ISSUE THREAD

**Issue by zcw46229412** [Tencent/QMUI_iOS#1362]
以前的老版本是有这两个属性，设置badge的时候，添加边框颜色
更新了4.4版本，发现这没有这属性了，可否继续支持
感谢!

**Comment by MoLice** [comment]
QMUI 历史上有过这两个属性吗？我搜了 log 并没有发现。你这是从多久远的版本直接更新到 4.4 的？

你说的边框的能力，都在 `QMUIBadgeProtocol` 里，它提供属性 `qmui_badgeLabel`、`qmui_updatesIndicatorView` 让你可以直接拿到 UIView 引用。拿到 view 后你想做什么都可以，不只是加边框。

**Comment by zcw46229412** [comment]
@MoLice  谢谢回复，我是从4.2.3 升的，回头用qmui_badgeLabel搞一下。
