### ISSUE TITLE
home键退出后再进导航变成上级导航颜色

### ISSUE THREAD

**Issue by Snail-hash** [Tencent/QMUI_iOS#1363]
**Bug 表现**
问题的具体描述

**截图**
![image](https://user-images.githubusercontent.com/29391046/148351763-78d5c287-1534-4dd4-969b-c8fda66aecdb.png)

**如何重现**
1. QMUIDEMO项目 QMUIKit -> QMUINavigationController -> 方便控制界面导航栏样式 -> 深色 -> home键退出 -> 再打开App

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [模拟器]
 - iOS 版本: [iOS 15.0]
 - Xcode 版本: [Xcode 13.0]
 - QMUI 版本: [4.4.2]

**Comment by MoLice** [comment]
4.4.3 无法重现。

https://user-images.githubusercontent.com/1190261/148358096-268a5fb2-d8c7-4132-9d10-4e684ec553b5.mov
