### ISSUE TITLE
返回按钮长按会出现一个导航栈的菜单，怎么去除这个手势

### ISSUE THREAD

**Issue by McGonagall666** [Tencent/QMUI_iOS#1376]
![image](https://user-images.githubusercontent.com/61775376/157849517-0594a806-94e5-43d9-a239-760c73cbfbcf.png)

**Comment by MoLice** [comment]
iOS 14 系统的新属性。hook 一下 setter 固定改为 nil 即可。
<img width="954" alt="image" src="https://user-images.githubusercontent.com/1190261/157872029-f1339b06-9e56-4b33-9cae-aacb8295ad3a.png">
