### ISSUE TITLE
QMUIConsole 在没使用配置表或者配置表里没设置 TableViewCellBackgroundColor 的情况下，打印出来的日志背景是白色的，看不见文字

### ISSUE THREAD

**Issue by z7z** [Tencent/QMUI_iOS#1377]
```
xcode 12.5
qmui 4.4.3
```
没有配置文件
直接使用 
`[QMUIConsole log:@"Begin"];`
文字的**颜色**和**背景**都为**白色**
直接复制Demo里的 QMUIConfigurationTemplate ，QMUIConsole 输出的文字和背景仍然都是**白色**
是我哪里么用对么

**Comment by helloWotu** [comment]
me too,我的也是，而且日志这边还总是崩溃，或者卡死主页面

**Comment by MoLice** [comment]
> me too,我的也是，而且日志这边还总是崩溃，或者卡死主页面

请提供 Demo。

**Comment by z7z** [comment]
> me too,我的也是，而且日志这边还总是崩溃，或者卡死主页面

哈哈，然后一堆警告，UI经常卡主线程里

**Comment by MoLice** [comment]
@z7z  不提供 Demo 等更详细的信息，你们这些反馈其实没任何意义...如果是必现的，早就已经发现了。

**Comment by z7z** [comment]
@MoLice 
1. 都需要什么
2.下面是 Cell内嵌Field
<img width="1335" alt="截屏2022-07-26 下午2 38 39" src="https://user-images.githubusercontent.com/7941245/180940450-73a80459-29df-4329-a272-b4a2f950b528.png">
<img width="1059" alt="截屏2022-07-26 下午2 39 51" src="https://user-images.githubusercontent.com/7941245/180940510-35076ffe-db77-45a6-b356-e554e3d87baa.png">

**Comment by z7z** [comment]
@MoLice 
1.Pod后直接引用，无配置文件
<img width="1500" alt="截屏2022-07-26 下午3 08 48" src="https://user-images.githubusercontent.com/7941245/180947186-9b640e8e-b786-4e21-94ef-72d934e7c46f.png">
2.拖拽Pod里的配置文件到项目
<img width="1488" alt="截屏2022-07-26 下午3 09 36" src="https://user-images.githubusercontent.com/7941245/180947271-d0bb9c37-4cf6-4ac4-969d-af7f920d7e55.png">
3.拖拽Demo里的配置文件到项目
<img width="1268" alt="截屏2022-07-26 下午3 17 46" src="https://user-images.githubusercontent.com/7941245/180947342-f69de250-2725-4367-a6f9-6e0946c9987d.png">

**Comment by z7z** [comment]
@MoLice 
```
xCode  - 12.5
QMUI    - 4.4.3
模拟器  - 14.5
```

**Comment by MoLice** [comment]
> @MoLice 1.Pod后直接引用，无配置文件 <img alt="截屏2022-07-26 下午3 08 48" width="1500" src="https://user-images.githubusercontent.com/7941245/180947186-9b640e8e-b786-4e21-94ef-72d934e7c46f.png">
> 
> 2.拖拽Pod里的配置文件到项目 <img alt="截屏2022-07-26 下午3 09 36" width="1488" src="https://user-images.githubusercontent.com/7941245/180947271-d0bb9c37-4cf6-4ac4-969d-af7f920d7e55.png">
> 
> 3.拖拽Demo里的配置文件到项目 <img alt="截屏2022-07-26 下午3 17 46" width="1268" src="https://user-images.githubusercontent.com/7941245/180947342-f69de250-2725-4367-a6f9-6e0946c9987d.png">

@z7z 根据这个提供的操作方式，确定 QMUIConsole 面板里的颜色错误是 QMUIConsole  的 bug，新版本会修复，在此之前可以修改本地的 `- [QMUIConsoleLogItemCell didInitializeWithStyle:]`，把里面的 `self.backgroundColor = nil;` 改为 `self.backgroundColor = UIColor.clearColor;`。

**Comment by MoLice** [comment]
> @MoLice
> 
> 1. 都需要什么
>    2.下面是 Cell内嵌TextField
> 
> <img alt="截屏2022-07-26 下午2 38 39" width="1335" src="https://user-images.githubusercontent.com/7941245/180940450-73a80459-29df-4329-a272-b4a2f950b528.png">
> 
> <img alt="截屏2022-07-26 下午2 39 51" width="1059" src="https://user-images.githubusercontent.com/7941245/180940510-35076ffe-db77-45a6-b356-e554e3d87baa.png">

按照 issue 的描述无法重现。该问题若不提供 Demo，后续不再跟进，排查的效率太低。
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/1190261/181261303-b0eb85cb-40d5-4680-b0c8-10b3b63bd762.png">

**Comment by MoLice** [comment]
已发布 [4.5.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.5.0) 修复该问题。
