### ISSUE TITLE
Mac Catalyst 编译问题 QMUIAsset 涉及 <CoreServices/UTCoreTypes.h>

### ISSUE THREAD

**Issue by JzwOnly** [Tencent/QMUI_iOS#1378]
建议用宏屏蔽一下相关代码，Mac编译不通过

**Comment by JzwOnly** [comment]
建议修改适配 Mac Catalyst
```
#if IS_MAC
#import <CoreServices/CoreServices.h>
#else
#import <CoreServices/UTCoreTypes.h>
#endif
```

**Comment by JzwOnly** [comment]
@MoLice 麻烦适配一下

**Comment by MoLice** [comment]
是这样吗：
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1190261/205927426-4691151f-50d6-4bf3-8936-f76546267ab8.png">

为啥我可以正常跑起来？

**Comment by MoLice** [comment]
新版本会兼容

**Comment by MoLice** [comment]
已修复该问题，请根据 iOS 版本支持情况选择升级到 [4.6.0(iOS 11-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.0) 或 [4.6.1(iOS 13-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.1)。
