### ISSUE TITLE
macOS Monterey 12.3移除Python2后，"Create Umbrella Header File"脚本不能正常执行

### ISSUE THREAD

**Issue by lzlsl** [Tencent/QMUI_iOS#1379]
**Bug 表现**
在macOS Monterey 12.3上编译项目，"Create Umbrella Header File"脚本不能正常执行

**其他信息**
 - 设备: 模拟器
 - Xcode 版本: Xcode 13.2.1

**Comment by lzk000007** [comment]
build phases 修改为 /usr/biin/python3

**Comment by lzlsl** [comment]
> build phases 修改为 /usr/biin/python3

脚本是基于Python2写的，用Python3执行会报错

**Comment by lzk000007** [comment]
可以贴一下错误截图吗？

**Comment by lzlsl** [comment]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/1830064/158495998-b703997b-2e62-46f1-8f93-a9626688a552.png">

**Comment by lzk000007** [comment]
我修改完没出现这个问题，文件中是否有错误

**Comment by lzlsl** [comment]
更新到最新版本后，脚本执行成功
