### ISSUE TITLE
OSX12.3及Xcode13.3报错/usr/bin/python: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by songxing10000** [Tencent/QMUI_iOS#1382]
![image](https://user-images.githubusercontent.com/10040131/158978963-c8eefa06-f4c5-43f3-87a7-93d562506e49.png)

解决方案如下图
![image](https://user-images.githubusercontent.com/10040131/158979144-43696f86-d063-4498-bae9-8a701533fa26.png)

**Comment by codingiran** [comment]
Mac Os 12.3移除了py2，参考下方链接进行修改即可：
https://github.com/QMUI/QMUIDemo_iOS/issues/73
