### ISSUE TITLE
iOS 15.4设置导航栏背景透明，但是导航栏变黑

### ISSUE THREAD

**Issue by KellyCoder** [Tencent/QMUI_iOS#1387]
**Bug 表现**
使用QMUINavigationControllerDelegate修改导航栏背景透明，但是会变黑

**截图**
<img width="945" alt="image" src="https://user-images.githubusercontent.com/42005138/160290347-53ea8982-b329-430f-baf6-8390cc651059.png">

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
UIImage() → UIImage qmui_imageWithColor:UIColorClear

**Comment by JxJPu9bD** [comment]
我这里设置白色背景, 方法也会调用到, 但是背景却是透明的 不知道是什么原因

`
- (UIImage *)qmui_navigationBarBackgroundImage {
    return [UIImage qmui_imageWithColor:UIColor.whiteColor];
}

- (UIColor *)qmui_titleViewTintColor {
    return [UIColor colorNamed:@"color-text-default"];
}
`

下面第二个方法都是有效的

**Comment by JxJPu9bD** [comment]
`- (UIImage *)qmui_navigationBarBackgroundImage {
    return [UIImage qmui_imageWithColor:UIColor.whiteColor];
}

- (UIColor *)qmui_titleViewTintColor {
    return [UIColor colorNamed:@"color-text-default"];
}`

**Comment by JxJPu9bD** [comment]
> 

已经解决, 需要打开 navBarUsesStandardAppearanceOnly

**Comment by json1994** [comment]
> 

我设置这个 没有效果 o(╥﹏╥)o

**Comment by developerjet** [comment]
> navBarUsesStandardAppearanceOnly

你好，请问Swift如何设置navBarUsesStandardAppearanceOnly属性呢，通过QMUICMI访问不到navBarUsesStandardAppearanceOnly这个属性；
