### ISSUE TITLE
ExtendImplementationOfVoidMethodWithoutArguments引发的crash

### ISSUE THREAD

**Issue by Lazyloadingg** [Tencent/QMUI_iOS#1388]
**Bug 表现**
确切说我并不百分之百确定就是QMUI引起的，只不过从日志看，几次crash都显示了QMUI的`ExtendImplementationOfVoidMethodWithoutArguments`方法，

**截图**
![](https://gitee.com/trybelieve/image-service/raw/master/img/202203291100627.png)

**如何重现**
我身边的设备并未出现，是线上日志显示的问题，我希望能在这里得到帮助,感谢

**预期的表现**
正常运行

**其他信息**
 - 设备: [iPhone X、iPhone11、iPhone6SP]
 - iOS 版本: [iOS 13.6、iOS 14.0、iOS 13.1.2]
 - Xcode 版本: [Xcode 13.2.1]
 - QMUI 版本: [4.3.0]

**Comment by MoLice** [comment]
与 QMUI 无关，只是 hook 了那个方法所以出现在堆栈里而已。请检查你代码里与 UIAlertController 相关的逻辑。
