### ISSUE TITLE
qmui_queryItems 返回值类型错误会导致swift中调用崩溃

### ISSUE THREAD

**Issue by xixisplit** [Tencent/QMUI_iOS#1391]
**Bug 表现**
问题的具体描述
NSURL (QMUI) 文件中
qmui_queryItems 参数的指定返回值类型为  (NSDictionary<NSString *, NSString *> *)
但是.30行的 [params setObject:obj.value ?: [NSNull null] forKey:obj.name] 中.obj.value 如果为空.则会赋值 NSNull
会触发swift 中对参数类型的强制校验.引发崩溃.
控制台提示:
Could not cast value of type 'NSNull' (0x2076dbeb8) to 'NSString' (0x2076d8e30).

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
**如何重现**
let url = NSURL.init(string: "https://www.baidu.com?key")
debugPrint(url?.qmui_queryItems)
swift 项目 直接调用以上代码即可

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone SE2]
 - iOS 版本: [iOS 15.4.1]
 - Xcode 版本: [Xcode 13.2.1]
 - QMUI 版本: [4.4.0]

**Comment by MoLice** [comment]
感谢指出，下个版本会修复，在此之前请将本地代码改为：
```objc
[params setObject:obj.value ?: @"" forKey:obj.name];
```

**Comment by BinBear** [comment]
下个版本有发布计划吗

**Comment by MoLice** [comment]
近期暂无大版本，小版本如果需要的话可以两周内发一个。

**Comment by MoLice** [comment]
已发布 [4.5.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.5.0) 修复该问题。
