### ISSUE TITLE
qmui_getProjectClassList获取的类只获取到工程的，无法获取到引入库的

### ISSUE THREAD

**Issue by tfy87happy** [Tencent/QMUI_iOS#1392]
qmui_getProjectClassList获取的类只获取到工程的，无法获取到引入库的，从而导致[template applyConfigurationTemplate];方法不会被调用，请问如何解决这个问题呢，我们项目是主工程引入库的方式的

**Comment by MoLice** [comment]
主工程引入库是什么意思呢？只要你业务的配置表在主工程里应该就可以
