### ISSUE TITLE
debug模式下，在textfield输入emoji会进入assert

### ISSUE THREAD

**Issue by Creolophus** [Tencent/QMUI_iOS#1393]
**Bug 表现**
debug模式下，在textfield输入emoji会进入assert

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '试图在 ComposedCharacterSequence 中间用 substringFromIndex: 裁剪字符串，可能导致乱码、crash。原字符串为“🐮”(2)，index 为 1，命中的 ComposedCharacterSequence range 为 {0, 2}'
**截图**
![CleanShot 2022-04-16 at 20 20 05@2x](https://user-images.githubusercontent.com/7787790/163674737-4b0acd49-92e4-495a-be1b-8d8eb1aafb34.png)

**如何重现**
1. debug模式安装的包
2. 在textfield中输入emoji

**预期的表现**
不会进入assert

**其他信息**
 - 设备: [iPhone、iPad]
 - iOS 版本: [iOS 15.x]
 - Xcode 版本: [Xcode 13.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
更新一下版本，这里改为 log 提示了。暂无需理会，后续看看怎么跳过系统的 substring。

**Comment by shmilyQin** [comment]
> 更新一下版本，这里改为 log 提示了。暂无需理会，后续看看怎么跳过系统的 substring。

请问这个有更新吗， 我看现在4.7.0的版本也是Assert. debug还是会闪退

**Comment by MoLice** [comment]
#1511

**Comment by QifengYan** [comment]
4.8.0 版本 还会这样 请问 有什么处理方案吗?

**Comment by MoLice** [comment]
@QifengYan  iOS 18  系统一些私有方法改了，导致之前的代码失效，可以先用这份文件替换本地的。

[QMUIStringPrivate.m.zip](https://github.com/user-attachments/files/19226349/QMUIStringPrivate.m.zip)
