### ISSUE TITLE
The certificate for this server is invalid. You might be connecting to a server that is pretending to be “qmuiteam.com” which could put your confidential information at risk.

### ISSUE THREAD

**Issue by nouslove** [Tencent/QMUI_iOS#1396]
Task <4289798A-C390-4BB8-986C-DEC0317B6157>.<1> finished with error [-1202] Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “qmuiteam.com” which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x116047800) s: qmuiteam.com i: R3>",
    "<cert(0x116048000) s: R3 i: ISRG Root X1>",
    "<cert(0x116048800) s: ISRG Root X1 i: DST Root CA X3>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://qmuiteam.com/analytics/usageReport, NSErrorFailingURLStringKey=https://qmuiteam.com/analytics/usageReport, NSUnderlyingError=0x283c1eac0 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x2803714a0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9814, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9814, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x116047800) s: qmuiteam.com i: R3>",
    "<cert(0x116048000) s: R3 i: ISRG Root X1>",
    "<cert(0x116048800) s: ISRG Root X1 i: DST Root CA X3>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <4289798A-C390-4BB8-986C-DEC0317B6157>.<1>"
), _kCFStreamErrorCodeKey=-9814, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <4289798A-C390-4BB8-986C-DEC0317B6157>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x2803714a0>, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “qmuiteam.com” which could put your confidential information at risk.}

使用cocoaPods 方式导入，使用出现以上的问题

**Comment by nouslove** [comment]
sendAnalyticsToQMUITeam 设为NO

**Comment by MoLice** [comment]
官网证书过期，近期会更新。

**Comment by nouslove** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
