### ISSUE TITLE
导航栏的背景颜色设置无效

### ISSUE THREAD

**Issue by nouslove** [Tencent/QMUI_iOS#1397]
我下载了最新版本的QMUI，在配置表中将navBarBarTintColor设置为红色，结果并没有生效！

**Comment by MoLice** [comment]
可以先自己查一下，实在不明白再提 issue，不然会有过多冗余的 issue 产生。

**Comment by nouslove** [comment]
> 可以先自己查一下，实在不明白再提 issue，不然会有过多冗余的 issue 产生。

好的 下次注意  不好意思哈

**Comment by nouslove** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
