### ISSUE TITLE
qmui_navigationBarBarTintColor

### ISSUE THREAD

**Issue by lhf19900402** [Tencent/QMUI_iOS#1403]
qmui_navigationBarBarTintColor 这个方法是设置导航栏的背景色吗？  为什么我设置了没有反应？  系统是iOS15.4

**Comment by lhf19900402** [comment]
我测试过  在iOS14系统下qmui_navigationBarBarTintColor 这个方法是好的

**Comment by MoLice** [comment]
提供一下可重现的 Demo 我看看

**Comment by lhf19900402** [comment]
> 提供一下可重现的 Demo 我看看
[归档.zip](https://github.com/Tencent/QMUI_iOS/files/8746076/default.zip)

**Comment by MoLice** [comment]
因为你没用配置表，所以一切行为都是 iOS 15 系统默认的。iOS 15 默认的行为就是导航栏在滚动前是一种样式，滚动后是另一种样式。你不用配置表，默认设置的都是滚动后的样式，所以你的 Demo 里没 scrollView 时看到的都是滚动前的，就会觉得和代码不符合。

例如你加一个 UIScrollView 进去，滚一下，就能看到你的样式了。

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/1190261/169684536-c69b939c-8d9a-4f26-897a-8e31a5ca37e1.png">

具体自行了解相关知识。QMUI 配置表相关开关可以搜索 `TabBarUsesStandardAppearanceOnly`。
