### ISSUE TITLE
UINavigationController (QMUI)", @"QMUI 认为 popViewController 会成功，但实际上失败了，result = %@, disappearingViewControllers = %@

### ISSUE THREAD

**Issue by huhaharui** [Tencent/QMUI_iOS#1405]
整个项目的ViewController继承于QMUICommonViewController，NavigationController继承于QMUINavigationController,
在跳入其他第三方NavigationController，返回项目时就会崩溃
错误提示：UINavigationController (QMUI)", @"QMUI 认为 popViewController 会成功，但实际上失败了，result = %@, disappearingViewControllers = %@

**Comment by MoLice** [comment]
请提供可重现的 demo 以供测试
