### ISSUE TITLE
有没有办法在还需要支持iOS 9的情况下解决在iOS 15上导航栏配合scrollview的显示问题问题？

### ISSUE THREAD

**Issue by QianNangong** [Tencent/QMUI_iOS#1406]
现在是只要页面偏移量是0就不显示导航栏背景。
这个在4.4.0里面可以通过一个开关来解决这个问题的，然而最后支持iOS 9的是没有这个开关的，有没有什么办法可以解决？

**Comment by MoLice** [comment]
官方不提供，需自行处理。
