### ISSUE TITLE
QMUITextView 输入表情符号导致项目崩溃

### ISSUE THREAD

**Issue by a13377766460** [Tencent/QMUI_iOS#1409]
**Bug 表现**
QMUITextView 输入表情符号导致项目崩溃
1. 切换输入法   简体拼音
2. 点击表情
3. 选择任意表情符
Xcode控制台输出
+[QMUIStringPrivate(Safety) qmuisafety_NSString]_block_invoke_2:178 | QMUILogLevelWarn | QMUIStringSafety | 试图在 ComposedCharacterSequence 中间用 substringFromIndex: 裁剪字符串，可能导致乱码、crash。原字符串为“😞”(2)，index 为 1，命中的 ComposedCharacterSequence range 为 {0, 2}
**截图**
<img width="1242" alt="截屏2022-06-17 17 38 41" src="https://user-images.githubusercontent.com/40753970/174272430-832bd44a-dc99-4cc1-a94d-4a357bd2eff2.png">

**如何重现**
1. 切换输入法   简体拼音（九宫格）
![IMG_2963](https://user-images.githubusercontent.com/40753970/174273065-f9c0f673-64f1-4c8d-98f9-a013793792c1.jpg)

2. 点击表情
![IMG_2962](https://user-images.githubusercontent.com/40753970/174274692-ab2d74a2-a858-43c6-81f8-0c0b6a988117.jpg)

3. 选择任意表情符
![IMG_2964](https://user-images.githubusercontent.com/40753970/174273322-30e6b66f-1bdc-4a7f-b4ad-9024dcb4921e.PNG)

**预期的表现**
能正常输入表情符

**其他信息**
 - 设备: iphone X
 - iOS 版本: [iOS 15.4]
 - Xcode 版本: [Xcode 13.3.1]
 - QMUI 版本: [4.4.3]

**Comment by MoLice** [comment]
那是一个 QMUIAssert，不影响正式发布的 Release 包，只是在 Debug 里做个提示。如果不想影响 Debug，可以考虑把配置表里的 shouldPrintQMUIWarnLogToConsole = YES。

另外，系统输入法输入过程确实会触发这种告警，后续我们再考虑如何屏蔽系统场景。

**Comment by YEEBING** [comment]
shouldPrintQMUIWarnLogToConsole = YES 这个设置能YES，输入框就不能输入系统自带的emoji了，怎么样才能输入系统自带的表情符号呢？

**Comment by cd-chen** [comment]
> 那是一个QMUIAssert，不影响正式发布的Release包，只是在Debug里做一个提示。如果不想影响Debug，可以考虑把配置表里的shouldPrintQMUIWarnLogToConsole = YES。
> 
> 另外，系统输入法输入过程序确实会发出这种警告，之后我们再考虑如何显示系统现场情况。

最新版本shouldPrintQMUIWarnLogToConsole = YES在Debug里还是会崩溃

**Comment by rgmyyw** [comment]
+1

**Comment by Liuyoungs** [comment]
+1
