### ISSUE TITLE
Command CompileAssetCatalog failed with a nonzero exit code

### ISSUE THREAD

**Issue by XQBoy** [Tencent/QMUI_iOS#1414]
**其他信息**
 - 设备: iPhone  6s
 - iOS 版本: [iOS 15.1]
 - Xcode 版本: [Xcode 13.4.1]
 - QMUI 版本: [4.4.3]

**错误信息**

Showing Recent Errors Only
CompileAssetCatalog /Users/hwj/Library/Developer/Xcode/DerivedData/HWJO2O-hknsvmohvggktjdwpjbqregokold/Build/Products/Debug-iphoneos/QMUIKit/QMUIResources.bundle /Users/hwj/Documents/项目代码/App项目//xxx/Pods/QMUIKit/QMUIKit/QMUIResources/Images.xcassets (in target 'QMUIKit-QMUIResources' from project 'Pods')
    cd /Users/hwj/Documents/项目代码/App项目/xxx/Pods
    /Applications/Xcode.app/Contents/Developer/usr/bin/actool --output-format human-readable-text --notices --warnings --export-dependency-info /Users/hwj/Library/Developer/Xcode/DerivedData/HWJO2O-hknsvmohvggktjdwpjbqregokold/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/QMUIKit-QMUIResources.build/assetcatalog_dependencies --output-partial-info-plist /Users/hwj/Library/Developer/Xcode/DerivedData/HWJO2O-hknsvmohvggktjdwpjbqregokold/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/QMUIKit-QMUIResources.build/assetcatalog_generated_info.plist --compress-pngs --enable-on-demand-resources NO --filter-for-device-model iPhone8,1 --filter-for-device-os-version 15.1 --development-region en --target-device iphone --target-device ipad --minimum-deployment-target 11.0 --platform iphoneos --compile /Users/hwj/Library/Developer/Xcode/DerivedData/HWJO2O-hknsvmohvggktjdwpjbqregokold/Build/Products/Debug-iphoneos/QMUIKit/QMUIResources.bundle /Users/hwj/Documents/项目代码/App项目/xxx/Pods/QMUIKit/QMUIKit/QMUIResources/Images.xcassets

2022-06-23 15:47:46.372 ibtoold[96517:5303933] DEBUG: Added to environment: {
    TMPDIR = "/var/folders/17/v0h274jn33s6357d9d0y8_mc0000gn/T/DC03ABAB-B780-4F94-94D9-96554F95F465";
}
2022-06-23 15:47:48.270 ibtoold[96517:5303933] *** Terminating app due to uncaught exception 'IBPlatformToolFailureException', reason: 'The tool closed the connection (AssetCatalogSimulatorAgent)

Last command:
_ON_QUEUE_sendMessage:toChannelReturningError:during:

Backtrace of last command:
  0   -[IBAbstractPlatformToolProxy _ON_QUEUE_sendMessage:toChannelReturningError:during:] (in IDEInterfaceBuilderKit)
  1   __74-[IBAbstractPlatformToolProxy sendMessage:toChannelReturningError:during:]_block_invoke (in IDEInterfaceBuilderKit)
  2   _dispatch_client_callout (in libdispatch.dylib)
  3   _dispatch_lane_barrier_sync_invoke_and_complete (in libdispatch.dylib)
  4   DVTDispatchSync (in DVTFoundation)
  5   -[IBAbstractPlatformToolProxy sendMessage:toChannelReturningError:during:] (in IDEInterfaceBuilderKit)
  6   -[AssetCatalogSimulatorAgentProxy compileItemsWithCatalogRelativeIdentifierPaths:tagSolutionSpace:andStickerPacksWithCatalogRelativeIdentifierPaths:options:] (in IDEInterfaceBuilderCocoaTouchIntegration)
  7   -[IBICSimulatorToolCARCompiler compileCARItems:tagSolutionSpace:options:queue:completionHandler:] (in AssetCatalogCocoaTouchKit)
  8   -[IBICAbstractPlatformAdapter compileCARItems:tagSolutionSpace:options:queue:completionHandler:] (in AssetCatalogFoundation)
  9   __84-[IBICAbstractPlatformAdapter compileSelectedItems:options:queue:completionHandler:]_block_invoke (in AssetCatalogFoundation)
 10   __93-[IBICAbstractPlatformAdapter compileStandaloneCatalogItems:options:queue:completionHandler:]_block_invoke (in AssetCatalogFoundation)
 11   __DVT_CALLING_CLIENT_BLOCK__ (in DVTFoundation)
 12   __DVTDispatchAsync_block_invoke (in DVTFoundation)
 13   _dispatch_call_block_and_release (in libdispatch.dylib)
 14   _dispatch_client_callout (in libdispatch.dylib)
 15   _dispatch_main_queue_drain (in libdispatch.dylib)
 16   _dispatch_main_queue_callback_4CF (in libdispatch.dylib)
 17   __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ (in CoreFoundation)
 18   __CFRunLoopRun (in CoreFoundation)
 19   CFRunLoopRunSpecific (in CoreFoundation)
 20   -[NSRunLoop(DVTNSRunLoopAdditions) dvt_spinRunLoopInMode:whileQueue:executesAsynchronously:] (in DVTFoundation)
 21   -[NSRunLoop(DVTNSRunLoopAdditions) dvt_spinRunLoopInMode:whileBlockExecutesConcurrently:] (in DVTFoundation)
 22   -[NSRunLoop(DVTNSRunLoopAdditions) dvt_spinRunLoopInMode:waitingForSemaphore:] (in DVTFoundation)
 23   -[IBCLIImageCatalogToolPersona compileCatalogCollection:withPlatformAdapter:arguments:outputDictionary:] (in ibtoold)
 24   -[IBCLIImageCatalogToolPersona invokeArguments:outputDictionary:] (in ibtoold)
 25   -[IBCLIImageCatalogToolPersona runSingleInvocation:outputtingToFileHandle:andVerifyingEnvironment:] (in ibtoold)
 26   IBCLIServerRunSingleInvocation (in ibtoold)
 27   __IBCLIServerRunSingleInvocationWithIODirectedAtPipesAndUnlinkOnSuccess_block_invoke_2 (in ibtoold)
 28   __IBCLIServerRunSingleInvocationWithIODirectedAtPipesAndUnlinkOnSuccess_block_invoke (in ibtoold)
 29   -[IBCLIErrorForwarder forwardErrorOutputToDescriptor:whileInvokingBlock:] (in ibtoold)
 30   IBCLIServerRunSingleInvocationWithIODirectedAtPipesAndUnlinkOnSuccess (in ibtoold)
 31   main (in ibtoold)
 32   start (in dyld)

Execution Context:
<IBSimulatorToolCoreSimulatorCLIExecutionContext: 0x7fdc67391a70 busyCount=0, Idle for 0.0 secs, lifeTime=1.9 secs>, device=IBSimDeviceTypeiPad2x (30AF896A-6EF9-4E53-98AD-68633F8539F7, iOS 15.5, Shutdown), idiom=<IBIPhoneIdiom: 0x7fdc67b9ed50>

'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8025917b3 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff8022f1bc3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8025ba066 -[NSException raise] + 9
	3   IDEInterfaceBuilderKit              0x000000010a0d6111 -[IBAbstractPlatformToolProxy _errorByAddingAdditionalCrashInformationToError:orRaiseIfNeededOnFailure:shouldRaiseOnFailures:waitForCrashLog:] + 1664
	4   IDEInterfaceBuilderKit              0x000000010a0d5a67 -[IBAbstractPlatformToolProxy errorByAddingAdditionalCrashInformationToError:orRaiseIfNeededOnFailure:] + 94
	5   IDEInterfaceBuilderKit              0x000000010a0d7a53 -[IBAbstractPlatformToolProxy _ON_QUEUE_sendMessage:toChannelReturningError:during:] + 210
	6   IDEInterfaceBuilderKit              0x000000010a0d7949 __74-[IBAbstractPlatformToolProxy sendMessage:toChannelReturningError:during:]_block_invoke + 38
	7   libdispatch.dylib                   0x00007ff802298317 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007ff8022a57ee _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x000000010905e32a DVTDispatchSync + 183
	10  IDEInterfaceBuilderKit              0x000000010a0d786e -[IBAbstractPlatformToolProxy sendMessage:toChannelReturningError:during:] + 228
	11  IDEInterfaceBuilderCocoaTouchIntegr 0x000000011450ffc3 -[AssetCatalogSimulatorAgentProxy compileItemsWithCatalogRelativeIdentifierPaths:tagSolutionSpace:andStickerPacksWithCatalogRelativeIdentifierPaths:options:] + 213
	12  AssetCatalogCocoaTouchKit           0x0000000110706957 -[IBICSimulatorToolCARCompiler compileCARItems:tagSolutionSpace:options:queue:completionHandler:] + 1038
	13  AssetCatalogFoundation              0x0000000108c42acf -[IBICAbstractPlatformAdapter compileCARItems:tagSolutionSpace:options:queue:completionHandler:] + 487
	14  AssetCatalogFoundation              0x0000000108c41f01 __84-[IBICAbstractPlatformAdapter compileSelectedItems:options:queue:completionHandler:]_block_invoke + 237
	15  AssetCatalogFoundation              0x0000000108c4637f __93-[IBICAbstractPlatformAdapter compileStandaloneCatalogItems:options:queue:completionHandler:]_block_invoke + 18
	16  DVTFoundation                       0x000000010905d3d4 __DVT_CALLING_CLIENT_BLOCK__ + 7
	17  DVTFoundation                       0x000000010905e3c4 __DVTDispatchAsync_block_invoke + 124
	18  libdispatch.dylib                   0x00007ff8022970cc _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x00007ff802298317 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x00007ff8022a4c78 _dispatch_main_queue_drain + 943
	21  libdispatch.dylib                   0x00007ff8022a48bb _dispatch_main_queue_callback_4CF + 31
	22  CoreFoundation                      0x00007ff802553f07 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	23  CoreFoundation                      0x00007ff802514fef __CFRunLoopRun + 2771
	24  CoreFoundation                      0x00007ff802513e5c CFRunLoopRunSpecific + 562
	25  DVTFoundation                       0x0000000108efb69e -[NSRunLoop(DVTNSRunLoopAdditions) dvt_spinRunLoopInMode:whileQueue:executesAsynchronously:] + 437
	26  DVTFoundation                       0x0000000108efb90d -[NSRunLoop(DVTNSRunLoopAdditions) dvt_spinRunLoopInMode:whileBlockExecutesConcurrently:] + 87
	27  DVTFoundation                       0x0000000108efba77 -[NSRunLoop(DVTNSRunLoopAdditions) dvt_spinRunLoopInMode:waitingForSemaphore:] + 119
	28  ibtoold                             0x00000001084f0c2e -[IBCLIImageCatalogToolPersona compileCatalogCollection:withPlatformAdapter:arguments:outputDictionary:] + 1578
	29  ibtoold                             0x00000001084f273b -[IBCLIImageCatalogToolPersona invokeArguments:outputDictionary:] + 2333
	30  ibtoold                             0x00000001084f2c5e -[IBCLIImageCatalogToolPersona runSingleInvocation:outputtingToFileHandle:andVerifyingEnvironment:] + 574
	31  ibtoold                             0x0000000108500789 IBCLIServerRunSingleInvocation + 506
	32  ibtoold                             0x0000000108500da6 __IBCLIServerRunSingleInvocationWithIODirectedAtPipesAndUnlinkOnSuccess_block_invoke_2 + 34
	33  ibtoold                             0x0000000108500c76 __IBCLIServerRunSingleInvocationWithIODirectedAtPipesAndUnlinkOnSuccess_block_invoke + 840
	34  ibtoold                             0x00000001084ef6c6 -[IBCLIErrorForwarder forwardErrorOutputToDescriptor:whileInvokingBlock:] + 97
	35  ibtoold                             0x00000001085003d1 IBCLCommand CompileAssetCatalog failed with a nonzero exit code

**Comment by XQBoy** [comment]
问题已解决。

**Comment by waley518** [comment]
你好，我更新xcode到13.4.1也报这个问题，请问是哪里配置错了？

**Comment by waley518** [comment]
问题已解决。

**Comment by TomZid** [comment]
怎么解决的，有经验分享么，或是参考链接？

**Comment by stoneioslife** [comment]
> 问题已解决。

如何解决的？
