### ISSUE TITLE
闪退 - (void)textView:(QMUITextView *)textView newHeightAfterTextChanged:(CGFloat)height

### ISSUE THREAD

**Issue by 19aneng** [Tencent/QMUI_iOS#1417]
**Bug 表现**
问题的具体描述
- (void)textView:(QMUITextView *)textView newHeightAfterTextChanged:(CGFloat)height
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/22389902/177294092-fb97bee3-440d-4046-a1f0-9b32cc6abeb0.png)

**如何重现**
1. 使用UItableviewcell,XIB
2. 
![image](https://user-images.githubusercontent.com/22389902/177294284-7113f7f4-3be6-4494-baeb-15231cdf3b23.png)
3. ...
![image](https://user-images.githubusercontent.com/22389902/177294345-d1ca856e-d8c3-47a1-af6c-35f96aeba190.png)
![image](https://user-images.githubusercontent.com/22389902/177294565-7f421f34-d661-486c-8950-117fd0da847f.png)

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.x]
 - QMUI 版本: [4.x.x]

**Comment by 19aneng** [comment]
我试试代码创建,可能是xib修改高度和内部冲突

**Comment by MoLice** [comment]
直接提供 Demo
