### ISSUE TITLE
UIImageView、UIButton 配合 template image 使用时无法通过 tintColor 来修改图片的颜色

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1418]
**Bug 表现**
UIButton.tintColor、UIImageView.tintColor为QMUIThemeColor，Image为UIImageRenderingModeAlwaysTemplate，「手动」切换主题后不生效，**但是系统的主题切换是生效的**

**截图**
<img width="475" alt="图片" src="https://user-images.githubusercontent.com/22904757/177438856-aed9a09f-d110-4fec-8396-44b40ab83e9f.png">

**如何重现**
1.<img width="1403" alt="图片" src="https://user-images.githubusercontent.com/22904757/177438941-49624cfa-1b77-4d31-bc96-eff6cb2134eb.png">
2.在QDThemeViewController.m中点击按钮切换主题

Demo:
[QMUIDemo_iOS.zip](https://github.com/Tencent/QMUI_iOS/files/9050528/QMUIDemo_iOS.zip)

**预期的表现**
UIButton.tintColor、UIImageView.tintColor为QMUIThemeColor也可以正常生效

**其他信息**
 - 设备: iPhone
 - iOS 版本: iOS 15.x
 - Xcode 版本: Xcode 13.4
 - QMUI 版本: 4.4.3

**Comment by jiasongs** [comment]
暂时解决方案：
`UIView+QMUITheme.m`
<img width="914" alt="图片" src="https://user-images.githubusercontent.com/22904757/177484366-870cb17a-56d6-4bb9-bd1c-5d4e355cd4ff.png">

**Comment by MoLice** [comment]
经测试，iOS 13-15 都有这个问题，iOS 12 及以下没问题是因为我们在 QMUIThemePrivate 里对 iOS 12 及以下的版本 hook 了 `-[UIView setTintColor:]`，主动对 QMUIThemeColor 做一次 copy 从而触发系统的自动刷新。iOS 13 及以上没做这个处理，在手动切换 theme 时就出问题了。

UIImageView 系统没重写 setTintColor:。UIButton 重写了但有调用 super，所以统一在 `-[UIView setTintColor:]` 内处理即可。

**Comment by MoLice** [comment]
已发布 [4.5.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.5.0) 修复该问题。
