### ISSUE TITLE
模拟器 iOS 15.5 设置当前控制器的导航栏颜色无效，请问是什么原因呢？

### ISSUE THREAD

**Issue by developerjet** [Tencent/QMUI_iOS#1419]
QMUI 已经提供了**详尽的注释文档**，以及**完整的示例项目 [QMUI Demo](https://github.com/QMUI/QMUI_iOS_Demo)**，当你遇到某些功能不知道怎么使用，或者想知道 QMUI 是否有提供某些功能时，请先查看注释文档或者 Demo，找不到了再提 issue。若提的 issue 已有明确注释或示例的，**可能会被直接关闭或得不到及时的回复**，请知悉。

extension STUserCenterViewController {
    
    override func qmui_navigationBarBackgroundImage() -> UIImage? {
        return UIImage.qmui_image(with: .appThemeColor)
    }
}

**Comment by MoLice** [comment]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/1190261/178264464-d260d7f7-122a-49f2-adaa-b26b6490c531.png">

**Comment by developerjet** [comment]
> <img alt="image" width="1124" src="https://user-images.githubusercontent.com/1190261/178264464-d260d7f7-122a-49f2-adaa-b26b6490c531.png">

你好，请问Swift如何设置呢，无法获取相应的属性。

**Comment by guojiahying** [comment]
请问下这个事怎么解决的那 求帮助一下
