### ISSUE TITLE
设置屏幕方向无效果

### ISSUE THREAD

**Issue by cwenqing** [Tencent/QMUI_iOS#1422]
**Bug 表现**
两个VC都继承QMUICommonViewController，A页面
SecondViewController *vc = [[SecondViewController alloc]init];
vc.supportedOrientationMask = UIInterfaceOrientationMaskLandscapeLeft;
[self.navigationController pushViewController:vc animated:YES];
屏幕方向依旧为竖屏

**截图**

**如何重现**
1. ...
2. ...

**预期的表现**
SecondViewController强制为横屏

**其他信息**
 - 设备: 模拟器
 - iOS 版本: iOS15
 - Xcode 版本: Xcode 12
 - QMUI 版本: 4.3.0

**Comment by xiaoyao20084321** [comment]
老哥，我也遇到这种情况了。。你是怎么解决的啊
