### ISSUE TITLE
QMUITextField使用RxSwift监听text时，无效

### ISSUE THREAD

**Issue by Wolfgang89** [Tencent/QMUI_iOS#1424]
**Bug 表现**
继承于QMUITextField的子类对象，在使用Observable.combineLatest或者subscribe多个QMUITextField时，无法监听生效。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是可以使用RxSwift监听text的输入值的。

**其他信息**
 - 设备: [模拟器、iPhone]
 - iOS 版本: [iOS 15以上]
 - Xcode 版本: [Xcode 12.x]
 - QMUI 版本: [4.4.3]

**Comment by MoLice** [comment]
提供 demo
