### ISSUE TITLE
QMUISearchController 的tableViewStyle 样式

### ISSUE THREAD

**Issue by 276523923** [Tencent/QMUI_iOS#1425]
QMUICommonTableViewController 使用search controller 的时候

使用的是默认的初始化方法：
  self.searchController = [[QMUISearchController alloc] initWithContentsViewController:self];

能否改成 
self.searchController = [[QMUISearchController alloc] initWithContentsViewController:self resultsTableViewStyle:self.tableView.style];

想让search controller 跟 自己的tableViewController 的样式一致。或者提供个选项自己决定样式。

**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。

**Comment by MoLice** [comment]
是有这个不便，我们考虑一下。

**Comment by MoLice** [comment]
已发布 [4.5.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.5.0) 修复该问题。
