### ISSUE TITLE
UINavigationBar Dark Mode 使用疑问

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#1428]
app情况：
1 仅适配iOS13+
2 使用系统方法 并没使用QMUITheme
3 使用配置表并设置了`QMUICMI.navBarBackgroundImage = 动态图片`

当iOS15下，因为使用了UINavigationBarAppearance，所以切换UserInterfaceStyle并没有问题。
当<iOS15，导航栏背景图不会自动响应darkmode。
这种情况该怎么做呢？`QMUIConfiguration`里凡是用到`UINavigationBarAppearance`都做了系统判断，难道要把相关的`if (@available(iOS 15.0, *))`都改为`if (@available(iOS 13.0, *))`吗？这么做会有问题吗？

**Comment by MoLice** [comment]
请提供 demo

**Comment by fanyuecheng** [comment]
使用iOS15以下的模拟器或者真机
[Demo.zip](https://github.com/Tencent/QMUI_iOS/files/9305605/Demo.zip)

**Comment by MoLice** [comment]
系统的动态 image 如果要在 UINavigationBar backgroundImage 上自动跟随 Light/Dark 切换，要求必须使用 UINavigationBarAppearance。

而 QMUI 只在 iOS 15+ 才使用 UINavigationBarAppearance，所以如果你在 iOS 14 及以下的系统里将系统的动态 image 用于 UINavigationBar，就会失效。

这个暂时没办法处理，对 QMUI 来说改动太大，也会影响其他使用 QMUI 的项目。只能由业务项目自己处理 backgroundImage 了，无法用配置表。
