### ISSUE TITLE
delegate.window  crash

### ISSUE THREAD

**Issue by cherishloveyou** [Tencent/QMUI_iOS#1429]
**Bug 表现**
问题的具体描述

[AppDelegate window]: unrecognized selector sent to instance
应该是没有适配SceneDelegate

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/1764796/183881727-f6232645-8f83-4c9f-a82d-8340d553bc3b.png)

**如何重现**
SceneDelegate Project

**预期的表现**
正常情况下，应该是什么表现
适配SceneDelegate工程获取window

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 15.5]
 - Xcode 版本: [Xcode 14.x]
 - QMUI 版本: [4.4.3]

**Comment by MoLice** [comment]
工作量大，暂不适配。
