### ISSUE TITLE
更新4.5.0版本之后编译报错，缺少文件

### ISSUE THREAD

**Issue by BinBear** [Tencent/QMUI_iOS#1430]
**Bug 表现**
更新4.5.0版本之后编译报错，缺少文件
![image](https://user-images.githubusercontent.com/13587915/183925175-77d2426a-84f7-4a15-ae37-99ccb595f4f1.png)

![image](https://user-images.githubusercontent.com/13587915/183924084-c69e6384-368f-4202-aeec-7a6f455940ea.png)
是因为QMUIBarProtocol相关的类在 UIKitExtensions/QMUIBarProtocol 的路径下
![image](https://user-images.githubusercontent.com/13587915/183924464-7c54f7bc-872e-4d8c-b467-a68f7b9d5e4c.png)
但是 podspec 中 指定的 source_files  是 QMUIKit/UIKitExtensions
![image](https://user-images.githubusercontent.com/13587915/183924769-41f8231d-278c-495c-a329-3eb78c89d62e.png)
所以需要把 UIKitExtensions/QMUIBarProtocol  文件夹下的文件移到上一层目录

**Comment by BinBear** [comment]
目前就只有fork一份，然后修改路径，指定 pod 'QMUIKit', :git => ' xxxxx‘ 了，或者使用之前的版本。希望作者能快些时候发个版本解决一下

**Comment by MoLice** [comment]
已重新发布
