### ISSUE TITLE
开启 AutomaticCustomNavigationBarTransitionStyle 的情况下，从界面 B pop 回界面 A 的过程，如果 A 的导航栏效果与全局默认效果不同，则在 pop 过程中 A 的导航栏样式错误

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#1432]
**Bug 表现**
_QMUITransitionNavigationBar 样式错误

**截图**
![Aug-12-2022 14-37-36](https://user-images.githubusercontent.com/34535969/184298590-3b7c71b1-340f-4ee7-8e46-dcbe4264cecb.gif)

**如何重现**
QMUIDemo “优化导航栏在转场时的样式 ”
多次点击不同样式跳转后，返回会发现 从 “默认”到“深色”的过程中，“深色”vc的假导航栏是“默认”的蓝色，pop完成后，“深色”vc的假导航栏移除，显示了原本的灰色。

**预期的表现**
正常情况下，深色vc的假导航栏应该是灰色

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 14.5]
 - Xcode 版本: [Xcode 12 13.4.1]
 - QMUI 版本: [4.5.0]

**Comment by fanyuecheng** [comment]
好想是pop时，
`addTransitionNavigationBarAndBindNavigationBar:` ->
`[self.view addSubview:customBar]` -> 
`[UINavigationBar _didMoveFromWindow:toWindow:]` -> 
`setBackgroundImage:forBarPosition:barMetrics:`。
UINavigationBar+QMUI 中重写了 `setBackgroundImage:forBarPosition:barMetrics:` 并在其中为 `appearance.backgroundImage` 赋值，同时将该 `appearance` 赋值给navigationBar。
这个`image`一直是[UIImage qmui_imageWithThemeManagerName:QMUIThemeManagerNameDefault provider:provider]

**Comment by MoLice** [comment]
已发布 [4.5.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.5.1) 修复该问题。
