### ISSUE TITLE
QMUIPopupContainerView将sourceView设置为nil时会造成EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1438]
**Bug 表现**
QMUIPopupContainerView将sourceView设置为nil时会造成EXC_BAD_ACCESS

**截图**
<img width="1574" alt="图片" src="https://user-images.githubusercontent.com/22904757/190588631-f868d6fc-1f7f-468c-b682-f0538674425e.png">

**如何重现**
`QDPopupContainerViewController.m`

<img width="674" alt="图片" src="https://user-images.githubusercontent.com/22904757/190588219-bcb718d0-008e-47a1-9ad9-d1e6565a62d2.png">

**预期的表现**
正常情况下，sourceView为nil不应该去调用qmui_frameDidChangeBlock

**其他信息**
 - 设备: iPhone
 - iOS 版本: iOS 15.5
 - Xcode 版本: Xcode 13.4
 - QMUI 版本: 4.5.1

**Comment by MoLice** [comment]
已修复该 bug，请根据 iOS 版本支持情况选择升级到 [4.6.0(iOS 11-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.0) 或 [4.6.1(iOS 13-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.1)。
