### ISSUE TITLE
UIView.qmui_hitTestBlock的返回值应该标记下_Nullable

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1439]
**现存问题或期望目标**
`UIView.qmui_hitTestBlock`的返回值应该标记下`_Nullable`，以对齐系统的`@selector(hitTest:withEvent:)`

**Comment by MoLice** [comment]
已修复该 bug，请根据 iOS 版本支持情况选择升级到 [4.6.0(iOS 11-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.0) 或 [4.6.1(iOS 13-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.1)。
