### ISSUE TITLE
iOS 15 设置导航栏透明 跳转下一个页面，跳转回来颜色错乱

### ISSUE THREAD

**Issue by cd-chen** [Tencent/QMUI_iOS#1440]
当前页面导航栏透明，跳转到下一个页面，再返回第一个页面过程中，导航栏会出现一半透明色，一半第二个页面的颜色
navBarUsesStandardAppearanceOnly
navBarRemoveBackgroundEffectAutomatically
都同时打开了

**Comment by MoLice** [comment]
截表现的图，以及代码的图
