### ISSUE TITLE
UIView+QMUI Crash 

### ISSUE THREAD

**Issue by StevenFJW** [Tencent/QMUI_iOS#1441]
**Bug 表现**
bugly 收集到  [UIView(QMUI_Layout) load]_block_invoke_2.512 (UIView+QMUI.m:461)  crash

**截图**
![截屏2022-09-19 上午10 38 42](https://user-images.githubusercontent.com/15072579/190942192-0aa9cc97-aba5-4d12-af1f-7e095ca36866.png)

![截屏2022-09-19 上午10 41 25](https://user-images.githubusercontent.com/15072579/190942198-8e8b3ae7-cab2-497e-a568-004b21392cc7.png)

**如何重现**
暂时不清楚

**预期的表现**
不崩溃

**其他信息**
 - 设备: iPhone 12以上
 - iOS 版本: [iOS 15.x]
 - Xcode 版本: [Xcode 13.x]
 - QMUI 版本: [4.5.1]

**Comment by MoLice** [comment]
这个说明不了什么，它只是 hook 了所以在调用堆栈里出现 QMUI 字样而已。
