### ISSUE TITLE
Xcode14下Controller点击页面回收键盘失败

### ISSUE THREAD

**Issue by HHiOS** [Tencent/QMUI_iOS#1447]
**Bug 表现**
Xcode14下Controller点击页面回收键盘失败

**代码问题所在**
UIApplication.sharedApplication.windows中不包含UIRemoteKeyboardWindow，故无法获取到keyboardView，最终导致键盘回收失败。

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 16.0]
 - Xcode 版本: [Xcode 14.0]
 - QMUI 版本: [4.5.1]

**Comment by MoLice** [comment]
已修复该问题，请根据 iOS 版本支持情况选择升级到 [4.6.0(iOS 11-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.0) 或 [4.6.1(iOS 13-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.1)。

另外屏幕方向的控制可查看 Wiki：[《适用于 iOS 16 及以下版本的屏幕方向控制方式》](https://github.com/Tencent/QMUI_iOS/wiki/%E9%80%82%E7%94%A8%E4%BA%8E-iOS-16-%E5%8F%8A%E4%BB%A5%E4%B8%8B%E7%89%88%E6%9C%AC%E7%9A%84%E5%B1%8F%E5%B9%95%E6%96%B9%E5%90%91%E6%8E%A7%E5%88%B6%E6%96%B9%E5%BC%8F)。
