### ISSUE TITLE
iOS 16 iPad QMUIKeyboardManager 键盘获取高度异常

### ISSUE THREAD

**Issue by pcccccc** [Tencent/QMUI_iOS#1450]
**Bug 表现**
点击QMUIDemo中QMUIKeyboardManager的发表想法或发表评论

**截图**
<img width="1436" alt="QQ20221008-172816@2x" src="https://user-images.githubusercontent.com/13974510/194700579-e2b7dbca-e045-46b5-8a86-558d72998c0b.png">

console截图:

<img width="612" alt="QQ20221008-172903@2x" src="https://user-images.githubusercontent.com/13974510/194700632-43b1719a-1702-4bd1-a75e-eb3b3137482b.png">

除了等于0 还会出现等于SCREEN_HEIGHT的问题。

**如何重现**
如上。

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: iPad
 - iOS 版本: iOS 16.0
 - Xcode 版本: Xcode 14.0
 - QMUI 版本: 最新版本

**Comment by MoLice** [comment]
已修复该问题，请根据 iOS 版本支持情况选择升级到 [4.6.0(iOS 11-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.0) 或 [4.6.1(iOS 13-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.1)。
