### ISSUE TITLE
iOS 16.0，iPadOS 16.1，QMUIKeyboardManager.keyboardView始终为nil，导致输入框被遮挡

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1453]
**Bug 表现**
iOS 16.0，iPadOS 16.1，QMUIKeyboardManager.keyboardView始终为nil，原因是getKeyboardViewFromWindow找不到UIRemoteKeyboardWindow

**截图**
<img width="749" alt="图片" src="https://user-images.githubusercontent.com/22904757/196867797-bb313966-2a85-4205-b44b-b78bb7d401e3.png">

<img width="979" alt="图片" src="https://user-images.githubusercontent.com/22904757/196867761-1d70d515-ca11-4da0-b862-f83f42ee58c0.png">

<img width="397" alt="图片" src="https://user-images.githubusercontent.com/22904757/196867720-d9ae5f5a-0b48-489a-96ec-42674ab4015d.png">

**如何重现**
1. 进入QMUIDemo的QDKeyboardViewController中点击「发表评论」按钮即可重现

**预期的表现**
QMUIKeyboardManager能找到keyboardView

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 16.0，iPadOS 16.1]
 - Xcode 版本: [Xcode 14.1]
 - QMUI 版本: [4.5.1]

**Comment by MoLice** [comment]
已修复该问题，请根据 iOS 版本支持情况选择升级到 [4.6.0(iOS 11-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.0) 或 [4.6.1(iOS 13-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.1)。
