### ISSUE TITLE
签署 "QMUIKit-QMUIResources" 需要开发团队

### ISSUE THREAD

**Issue by liam-i** [Tencent/QMUI_iOS#1456]
**Bug 表现**
Product->Archive 之后，报一下错误：

Signing for "QMUIKit-QMUIResources" requires a development team. Select a development team in the Signing & Capabilities editor.

**截图**
<img width="1512" alt="截屏2022-10-26 01 00 00" src="https://user-images.githubusercontent.com/24681179/197838707-cedb7783-5538-4da1-accf-9531832ae961.png">

**其他信息**
 - Xcode 版本: Xcode 14.1 RC2
 - QMUI 版本: 4.3.0

**Comment by monomichael** [comment]
建议在 `Podfile` 里添加

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
end
```

来源：https://stackoverflow.com/questions/72561696/xcode-14-needs-selected-development-team-for-pod-bundles
