### ISSUE TITLE
App在前台且被系统视图遮盖的情况下，修改UITextInputTraits.keyboardAppearance会引起键盘消失

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#1459]
**Bug 表现**
App在前台且被系统视图遮盖的情况下，修改UITextInputTraits.keyboardAppearance会引起键盘消失

**视频**
https://user-images.githubusercontent.com/22904757/200457951-bdfd4418-2aca-48bb-8ef1-a1d741cf1644.mp4

**如何重现**
在QMUIDemo里按照上方视频中的步骤操作

前提条件：App在前台且被系统视图遮盖

**预期的表现**
修改UITextInputTraits.keyboardAppearance键盘应正常显示

**其他信息**
 - 设备: iPhone XS MAX
 - iOS 版本: iOS 16.1
 - Xcode 版本: Xcode 14.1
 - QMUI 版本: 4.5.1

**Comment by jiasongs** [comment]
<img width="1256" alt="图片" src="https://user-images.githubusercontent.com/22904757/200458070-b30f5dd3-b38f-417b-b45d-a9408dd67880.png">
在后台时调用`[selfObject reloadInputViews]`键盘出现异常

**Comment by MoLice** [comment]
模拟器才会的问题，真机没问题。这行代码如果去掉，键盘外观就无法刷新了。
