### ISSUE TITLE
[QMUIKeyboardManager isKeyboardVisible]在iOS 15以上异常

### ISSUE THREAD

**Issue by shmchen** [Tencent/QMUI_iOS#1460]
**Bug 表现**
问题的具体描述
使用QMUITips发现弹窗被键盘遮挡，跟踪代码发现键盘弹出后，这个方法仍然[QMUIKeyboardManager isKeyboardVisible]判断会FALSE；
iOS 15以上的环境，键盘弹出的类名已经不同了，所以判断要修改下

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/13509756/201814714-acfc7ced-05a1-426c-b77d-52029d4bdaff.png)

**如何重现**
1. iOS 15以上模拟器中就可以测试出来

**Comment by MoLice** [comment]
已修复该问题，请根据 iOS 版本支持情况选择升级到 [4.6.0(iOS 11-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.0) 或 [4.6.1(iOS 13-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.1)。
