### ISSUE TITLE
将 UIView.backgroundColor 设置为 QMUIThemeColor 后再设置为另一个与 QMUIThemeColor 当前色值相同的颜色时，后者无效

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#1463]
**如何重现**

```objc
UIView *view = UIView.new;
view.backgroundColor = [UIColor qmui_colorWithThemeProvider:^UIColor * _Nonnull(__kindof QMUIThemeManager * _Nonnull manager, __kindof NSObject<NSCopying> * _Nullable identifier, __kindof NSObject * _Nullable theme) {
    if ([identifier isEqual:QDThemeIdentifierDark]) {
        return UIColorRed; // ①
    }
    return UIColorGreen; // ②
}];
view.backgroundColor = UIColorGreen; // ③
```

以上代码预期在 Light/Dark 切换时 view.backgroundColor 固定显示③的绿色，但实际运行后会发现切换 Light/Dark 时，view.backgroundColor 在①②里变化，③无效了。

关键在于②③必须是相同的颜色。

**其他信息**
 - iOS 版本: 仅测试了 iOS 12-16都有问题
 - Xcode 版本: Xcode 14.1
 - QMUI 版本: 4.5.1

**Comment by MoLice** [comment]
已修复该问题，请根据 iOS 版本支持情况选择升级到 [4.6.0(iOS 11-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.0) 或 [4.6.1(iOS 13-16)](https://github.com/Tencent/QMUI_iOS/releases/tag/4.6.1)。

**Comment by sugerGDev** [comment]
@MoLice  版本4.6.0中，
代码如下：
 CGColorRef cgColor = CGColorCreate(CGColorSpaceCreateDeviceRGB(), (CGFloat[]){rawColor.qmui_red, rawColor.qmui_green, rawColor.qmui_blue, rawColor.qmui_alpha});

用 CGColorCreate创建出来的色彩空间放到QMUICGColorOriginalColorBindKey中，但是会造成到处内存leak哇，因为 CGColorCreate要对应CGColorRelease 啊，这遵守MRC的。我从leak 跟踪到，如果没有用这个功能估计要屏蔽掉或者其他方式，我初级没什么方案，希望大佬修复～，请尽快修复。不然造成库不稳定问题～。

**Comment by MoLice** [comment]
@sugerGDev 2022-12 已修复该泄露。

**Comment by sugerGDev** [comment]
@MoLice 哦哦哦，我看到最新版本修复了。我之前没有看应用版本限制，没升级到最新。用leak在QMUI找了一会儿发现了，收获很多，哈哈哈
