### ISSUE TITLE
点击系统表情键盘切换表情键盘的按钮会崩溃

### ISSUE THREAD

**Issue by xiaowangqinghui** [Tencent/QMUI_iOS#1464]
你好，能稍微指导下吗？虽然没有用到你们的QMUI，但是却出现了和你们一样的问题，而且很难复现，有些用户是必现的，但是都拿不到用户的手机调试，自己周围所有的手机都复现不了，机型 型号什么的都试过了 就是复现不了，但有几个用户的手机就是必现的，试着看了你们的解决方法去改了下 也没效果，所以想问还有什么原因会导致闪退吗？我们项目就用了IQKeyBoard以及YYKit

**Comment by MoLice** [comment]
但你没有提供任何与崩溃相关的信息，例如堆栈、报错日志。

**Comment by xiaowangqinghui** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/15713276/203502922-637a1671-ca0e-486d-af6a-51730809351b.png">
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/15713276/203503071-3266c241-d548-4c5c-9200-cdb45de801c8.png">
谢谢

**Comment by xiaowangqinghui** [comment]
你好，有什么建议吗
