### ISSUE TITLE
可能是适配的问题？

### ISSUE THREAD

**Issue by caraHello** [Tencent/QMUI_iOS#1476]
**Bug 表现**
特定情况下出现闪退现象

问题的具体描述

针对iOS 16+的系统
QMUIKit 单独使用没啥问题，CocoaDebug （一个开源的看测试数据的框架，用的人也比较多）框架单独使用也没啥问题，但是当两个一起使用的时候就会出现闪退。

点击 CocoaDebug 框架 的小球，就出现闪退。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![WechatIMG15438](https://user-images.githubusercontent.com/91578643/211560693-2aec6ecf-fa36-48fe-b4cf-fa0ace3c696d.jpeg)

**如何重现**
1. 通过cocapods 导入两个框架
  pod 'CocoaDebug', :configurations => ['Debug']
  pod 'QMUIKit'

2. 点击 CocoaDebug 自带的小球
![screenshot-20230110-211310](https://user-images.githubusercontent.com/91578643/211561114-7c8e0c50-f96f-48a6-b954-f6c521bf31a8.png)

3.闪退

**预期的表现**
正常情况下，应该是什么表现:
正常情况下应该是弹出CocoaDebug的debug页面
![screenshot-20230110-211541](https://user-images.githubusercontent.com/91578643/211561511-803895be-b4dc-42db-b930-b2da0a5ef9a3.png)

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 16.2]
 - Xcode 版本: [Xcode 14.2]
 - QMUI 版本: [4.6.3]

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/1469
