### ISSUE TITLE
在导航栏不可见时也会根据机型返回导航栏的固定高度？

### ISSUE THREAD

**Issue by Cpt-MacTavish** [Tencent/QMUI_iOS#1478]
无意间看api的时候发现这个小小的注释问题，这应该想表达的是顶部状态栏的高度吧

/**
 静态的导航栏高度，在导航栏不可见时也会根据机型返回导航栏的固定高度
 */
@property(class, nonatomic, readonly) CGFloat statusBarHeightConstant;

**Comment by MoLice** [comment]
已改正
