### ISSUE TITLE
QMUIPopupContainerView

### ISSUE THREAD

**Issue by JC-Passerby** [Tencent/QMUI_iOS#1483]
**Bug 表现**
QMUIPopupMenuView 切换页面以后不再展示；

**Comment by MoLice** [comment]
大佬，你这描述如此简单，谁能给你查...

**Comment by JC-Passerby** [comment]
> 大佬，你这描述如此简单，谁能给你查...

目前测试发现这个问题的出现是在iOS16的系统上，操作流程是我在A页面弹出QMUIPopupMenuView，然后关闭A页面再次重新打开A页面，此时再次调用QMUIPopupMenuView创建以后，QMUIPopupMenuView的背景蒙版是显示的，但是item的不显示，您看一下是否重现~

**Comment by MoLice** [comment]
你换位思考一下如果是按你提供的信息，你来查，足不足够...

起码你弹出 pop 是怎么弹出的，代码怎么写的，得贴一下吧...

**Comment by JC-Passerby** [comment]
> 你换位思考一下如果是按你提供的信息，你来查，足不足够...
> 
> 起码你弹出 pop 是怎么弹出的，代码怎么写的，得贴一下吧...

QMUIPopupMenuView *popupMenuView = [[QMUIPopupMenuView alloc] init];
    popupMenuView.padding = UIEdgeInsetsMake(0, 21, 0, 21);
    popupMenuView.minimumWidth = 103;
    popupMenuView.itemHeight = 36;
    popupMenuView.backgroundColor = [UIColor color_494949];
    popupMenuView.automaticallyHidesWhenUserTap = YES;
    popupMenuView.maskViewBackgroundColor = [UIColor clearColor];
    popupMenuView.arrowImage = [UIImage new];
    popupMenuView.preferLayoutDirection = QMUIPopupContainerViewLayoutDirectionBelow;
    popupMenuView.shouldShowItemSeparator = YES;
    popupMenuView.itemSeparatorColor = [UIColor color_545353];
    popupMenuView.itemSeparatorInset = UIEdgeInsetsMake(0, -12, 0, -12);
    popupMenuView.itemTitleColor = [UIColor color_FFFFFF];
    popupMenuView.itemTitleFont = [UIFont systemFontOfSize:12];
    popupMenuView.cornerRadius = 5;
    popupMenuView.borderColor = [UIColor color_525151];
    popupMenuView.itemConfigurationHandler = ^(QMUIPopupMenuView *aMenuView, QMUIPopupMenuButtonItem *aItem, NSInteger section, NSInteger index) {
        aItem.button.highlightedBackgroundColor = [UIColor color_494949];
    };
    popupMenuView.items = @[
    [QMUIPopupMenuButtonItem itemWithImage:nil title:@"移至等候区" handler:^(QMUIPopupMenuButtonItem *aItem) {
        [aItem.menuView hideWithAnimated:YES];
      
    }],
    [QMUIPopupMenuButtonItem itemWithImage:nil title:@"设为主持人" handler:^(QMUIPopupMenuButtonItem *aItem) {
        [aItem.menuView hideWithAnimated:YES];
        
    }]];
   
    popupMenuView.sourceView = button;
    [popupMenuView showWithAnimated:YES];
