### ISSUE TITLE
qmui_navigationBarBackgroundImage没起作用

### ISSUE THREAD

**Issue by Lazyloadingg** [Tencent/QMUI_iOS#1493]
我在我的swift项目中使用了QMUI，导航栏使用`QMUINavigationController`，控制器基类使用`QMUICommonViewController`，我想在不同页面设置导航栏背景色，于是我重写了`qmui_navigationBarBackgroundImage `方法并返回了背景图片，但是并没有生效，我单独在每个页面设置`UINavigationBarAppearance`这样是生效的，但是这样很麻烦，

我下载了QMUIDemo 发现demo中虽然也使用了`qmui_navigationBarBackgroundImage `方法，但是注释说也会在主题配置文件中查找，不使用主题配置文件的话就无法使用`qmui_navigationBarBackgroundImage `吗？同协议下其他方法生效，比如`qmui_titleViewTintColor`，只有这个无效`qmui_navigationBarBackgroundImage `

我重新创建了个空的OC项目，直接使用`QMUINavigationController `搭配，`QMUICommonViewController `然后在`qmui_navigationBarBackgroundImage `中返回背景图，依然无效

是我使用的不对吗？

- swift项目最低支持版本：iOS13  ，模拟器：14pro
- oc项目最低版本16.4，模拟器：14pro

**Comment by MoLice** [comment]
请关注配置表中的 `navBarUsesStandardAppearanceOnly` 相关说明。
