### ISSUE TITLE
想单独拿出来一个控件太难了

### ISSUE THREAD

**Issue by yangguanghei** [Tencent/QMUI_iOS#1494]
想单独拿出来一个控件太难了

**Comment by MoLice** [comment]
比如说哪个控件？

**Comment by yangguanghei** [comment]
比如说：QMUITextView

**Comment by MoLice** [comment]
以下截图表示 QMUITextView 依赖了哪些其他组件。
<img width="590" alt="image" src="https://github.com/Tencent/QMUI_iOS/assets/1190261/157fbdde-ac72-4bac-ba9d-8f80b1e1360e">

在保持 QMUITextView 功能不变的情况下，要么复制一份其他组件的代码到 QMUITextView 里，要么就保持目前的依赖关系。

如果保持依赖关系，那你单独拿 QMUITextView 出去用时就要同时把这些组件也一起拿出去，这就是所谓的依赖。

这是必然的吧，不然还有什么别的方法？

**Comment by yangguanghei** [comment]
只是感觉依赖的有点多，而且依赖的类同样依赖了很多东西，所以感觉不好单独拿出来。
顺便问下，把QMUI里的的东西都弄懂，都能实现，能拿100K吗？

**Comment by MoLice** [comment]
> 所以感觉不好单独拿出来

是的，本来 QMUI 设计的时候也是整体一起使用，并不将某个组件单独使用作为设计考虑因素。

> 都能实现，能拿100K吗？

这个不了解。
