### ISSUE TITLE
QDBlurEffectViewController页中的UIVisualEffectView显示灰色

### ISSUE THREAD

**Issue by yangguanghei** [Tencent/QMUI_iOS#1503]
**Bug 表现**
QDBlurEffectViewController页中的UIVisualEffectView显示灰色

**截图**
![image](https://github.com/Tencent/QMUI_iOS/assets/15519768/111ac32b-36d7-4bf2-b1b5-e49b60142b00)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 15.4.1]
 - Xcode 版本: [Xcode 14.2]
 - QMUI 版本: [4.6.3]

**Comment by MoLice** [comment]
确保你没改过代码，直接跑 QMUI Demo 是你截图的样子？正常应该是这样：
![image](https://github.com/Tencent/QMUI_iOS/assets/1190261/c2c37da1-98b6-4f4c-b274-a7e147a81088)

**Comment by yangguanghei** [comment]
没改过代码，在模拟器上跑是没问题的，很奇怪

**Comment by MoLice** [comment]
我在真机上也正常，只能你自测了

**Comment by caicaicaich** [comment]
真机iphone 7,iOS版本  15.7.3 复现,也是显示灰的
真机iphone13,iOS版本 15.0 无此问题

**Comment by MoLice** [comment]
> 真机iphone 7,iOS版本 15.7.3 复现,也是显示灰的 真机iphone13,iOS版本 15.0 无此问题

我只能在我手头有限的设备里去测试，iOS 15.5 没发现该问题，暂无法处理。
