### ISSUE TITLE
QMUITextView粘贴失效

### ISSUE THREAD

**Issue by cd-chen** [Tencent/QMUI_iOS#1504]
当在其应用复制之后进入App 粘贴的时候为空，或者在App内部复制的时候在QMUITextView粘贴也为空，这种情况不是必现，但是出现的概率比较高

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 16.2]
 - Xcode 版本: [Xcode 14.3]
 - QMUI 版本: [4.6.3]

**Comment by MoLice** [comment]
你可以同时构造一个 UITextView 和一个 QMUITextView 在你的 App 里，然后当你频繁出现这种现象的时候，观察 UITextView 是不是也有相同问题，是的话，大概率是 HandOff 的问题。

你也可以直接把手机的 Settings > General > Handoff 给关闭，再尝试是否出现你说的情况。

**Comment by cd-chen** [comment]
出现这种情况UITextField是可以正常粘贴的，当QMUITextView 不能粘贴的时候Settings > General > Handoff 给关闭打开都不能粘贴，但是当搜狗输入法出现粘贴权限并且同意之后就可以粘贴了。我猜测是App内部没有同意粘贴权限导致的。代码层面怎么去监听粘贴权限，并且手动弹出权限框
![1](https://upload-images.jianshu.io/upload_images/28013539-023fd17c524dc276.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![2](https://upload-images.jianshu.io/upload_images/28013539-31041d8888cd1ecc.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by cd-chen** [comment]
> 可以在你的App里同时构造一个UITextView和一个QMUITextView，然后当你反复出现这种现象的时候，观察UITextView是不是也有相同的问题，是的话，很大概率是Handoff你的问题。
> 
> 你也可以直接把手机的设置>通用>切换给关闭，再尝试是否出现你说的情况。



> 可以在你的App里同时构造一个UITextView和一个QMUITextView，然后当你反复出现这种现象的时候，观察UITextView是不是也有相同的问题，是的话，很大概率是Handoff你的问题。
> 
> 你也可以直接把手机的设置>通用>切换给关闭，再尝试是否出现你说的情况。

出现这种情况UITextField是可以正常粘贴的，当QMUITextView 不能粘贴的时候Settings > General > Handoff 给关闭打开都不能粘贴，但是当搜狗输入法出现粘贴权限并且同意之后就可以粘贴了。我猜测是App内部没有同意粘贴权限导致的。代码层面怎么去监听粘贴权限，并且手动弹出权限框
![1](https://upload-images.jianshu.io/upload_images/28013539-023fd17c524dc276.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![2](https://upload-images.jianshu.io/upload_images/28013539-31041d8888cd1ecc.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by cd-chen** [comment]
@MoLice 

测试了不是粘贴权限弹窗的问题，把QMUITextView换成UITextView就没有问题了
