### ISSUE TITLE
https://qmuiteam.com/analytics/usageReport请求超时

### ISSUE THREAD

**Issue by qinge5043** [Tencent/QMUI_iOS#1515]
https://qmuiteam.com/analytics/usageReport请求超时，请问是不是证书签名过期了还是什么原因
<img width="433" alt="截屏2023-08-15 10 50 58" src="https://github.com/Tencent/QMUI_iOS/assets/22783690/09c74e24-3aa2-4ce6-9086-838d820ce48d">

**Comment by MoLice** [comment]
官网停止维护了，详情请看 4.7.0 版本更新说明：https://github.com/Tencent/QMUI_iOS/releases/tag/4.7.0
