### ISSUE TITLE
引入 QMUIKit  hook 引爆了线上 crash，有没有计划推出无 hook 版本的？

### ISSUE THREAD

**Issue by make1a** [Tencent/QMUI_iOS#1523]
项目是十二年的祖传代码， 想使用 QMUI,  在第一版小部分集成：  `dependency 'QMUIKit/QMUIComponents/QMUIPopupMenuView', '4.7.0'`
QMUI  里面的 hook 引爆了许多的祖传代码隐患，  咨询/建议 一下有没有无hook 版本的 QMUI UI 组件使用。
![image](https://github.com/Tencent/QMUI_iOS/assets/17469549/20702fde-edc8-406d-90a3-a8582b0712ea)

**Comment by MoLice** [comment]
性价比低，不会提供
