### ISSUE TITLE
QMUIButton的bug

### ISSUE THREAD

**Issue by huhangatzz** [Tencent/QMUI_iOS#1524]
**Bug 表现**
在给按钮设置背景后中间只展示一个图标时,这个图标无法放在背景的中心位置,会往右偏移.

**截图**
![image](https://github.com/Tencent/QMUI_iOS/assets/16912918/50f4f71a-c16e-436d-ab7b-bc72bce0a27a)

**如何重现**
QMUIButton *button = [QMUIButton buttonWithType:UIButtonTypeCustom];
            button.titleLabel.font = FontScale_14;
            button.layer.cornerRadius = 15*ScreenScale;
            button.layer.masksToBounds = YES;
            [button setBackgroundImage:LQImageColor(LQRGBColor(0, 0, 0, 0.4)) forState:UIControlStateNormal];
            button.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
            [button setImage:LQImage(defaultImgStr) forState:UIControlStateNormal];
            [button addTarget:self action:@selector(clickButtonAction:) forControlEvents:(UIControlEventTouchUpInside)];
            [self addSubview:button];

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
都有

**Comment by MoLice** [comment]
无法复现，可考虑你的 icon 图是不是有问题。
<img width="1243" alt="image" src="https://github.com/Tencent/QMUI_iOS/assets/1190261/0c4b2787-f562-49a4-a1ef-4ce6a7d5e142">
