### ISSUE TITLE
去除零宽字符崩溃

### ISSUE THREAD

**Issue by happy201993** [Tencent/QMUI_iOS#1542]
**Bug 表现**
崩溃

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://github.com/Tencent/QMUI_iOS/assets/10241217/1cd30b67-3aff-487d-a736-632270a3a8f5)

**如何重现**
运行下面的代码，崩溃
 NSString *text = @"18‍22";
 [text qmui_stringByReplacingPattern:@"[\u200b-\u200f\uFEFF\u202a-\u202e]" withString:@""];

**预期的表现**
不崩溃，并且能替换掉零宽字符

**其他信息**
 - 设备: 模拟器
 - iOS 版本: 所有版本
 - Xcode 版本: Xcode 15
 - QMUI 版本: [4.7.0]

**Comment by MoLice** [comment]
请先用以下文件替换你本地的同名文件，后续会修复。
[QMUIStringPrivate.m.zip](https://github.com/Tencent/QMUI_iOS/files/14278805/QMUIStringPrivate.m.zip)

**Comment by happy201993** [comment]
您好，我已收到您的邮件，会尽快给您回复。

**Comment by MoLice** [comment]
已发布 [4.8.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.8.0) 修复该问题。

**Comment by happy201993** [comment]
您好，我已收到您的邮件，会尽快给您回复。
