### ISSUE TITLE
增加UITableView和UICollectionView 的分区、cell圆角 

### ISSUE THREAD

**Issue by lijiajunios** [Tencent/QMUI_iOS#1544]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。
增加UITableView和UICollectionView 的分区、cell圆角

**Comment by MoLice** [comment]
collectionView 自己做很容易。

**Comment by MoLice** [comment]
collectionView 自己做很容易。
