### ISSUE TITLE
大哥，给个文档啊，光demo看的太难受了

### ISSUE THREAD

**Issue by 66pig** [Tencent/QMUI_iOS#1548]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。

**Comment by 66pig** [comment]
我想用你们那个QMUINavigation，不知道怎么用，我直接使用QMUINavigation这个，但是我的navigationBar上面的文字颜色和图标还是系统原本的，不是和你们的一样

**Comment by MoLice** [comment]
Demo 和注释已经够清楚了，这还不够，还要写文档的话，那是另外的价格了。
