### ISSUE TITLE
想问一下，QMUI还会有更新吗？

### ISSUE THREAD

**Issue by Creolophus** [Tencent/QMUI_iOS#1554]
很喜欢这个库，但看release一年多没更新了，希望能继续更新～

**Comment by MoLice** [comment]
会的，内网一直在更新，就是懒得发布

**Comment by lcl2539** [comment]
会跟随iOS 18发布新版本么？

**Comment by MoLice** [comment]
> 会跟随iOS 18发布新版本么？

应该会，iOS 18 有一些需要适配的改动。

**Comment by Creolophus** [comment]
> 会的，内网一直在更新，就是懒得发布

想问下内网一直在更新是指啥？

**Comment by MoLice** [comment]
> TX内部吗

是的

**Comment by Creolophus** [comment]
> > TX内部吗
> 
> 是的

坐等大佬更新！👍👍

**Comment by Creolophus** [comment]
大佬，有没有计划大概什么时候能更新tag？

**Comment by MoLice** [comment]
已发布 [4.8.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.8.0) 。
