### ISSUE TITLE
Xcode 16 运行时闪退

### ISSUE THREAD

**Issue by JosephPoplar** [Tencent/QMUI_iOS#1556]
**Bug 表现**
运行时闪退

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="1146" alt="image" src="https://github.com/Tencent/QMUI_iOS/assets/13551410/6675e7be-ccb6-4385-bf4e-1031b33ff2b4">
<img width="1157" alt="image" src="https://github.com/Tencent/QMUI_iOS/assets/13551410/af62bc5b-6ba7-4b77-8ef4-946862047857">

**如何重现**
1. 使用Xcode 16 beta(16A5171c)
2. 集成QMUI

**预期的表现**
没有这个提示

**其他信息**
 - 设备: iPhone 11
 - iOS 版本:iOS 18 beta
 - Xcode 版本: Xcode 16 beta
 - QMUI 版本: 4.6.0

**Comment by MoLice** [comment]
建议本地先按这个改 https://github.com/Tencent/QMUI_iOS/pull/1555

**Comment by MoLice** [comment]
已发布 [4.8.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.8.0) 修复该问题。

**Comment by RWzmy** [comment]
同样遇到这个问题，Xcode 16.2
