### ISSUE TITLE
可以单独使用某个功能吗？

### ISSUE THREAD

**Issue by wdq123550** [Tencent/QMUI_iOS#1560]
比如UIlabel的跑马灯效果，我可以直接拖入跑马灯那个label的.h和.m之类的，而不必pod整个工程？

**Comment by MoLice** [comment]
pod 'QMUIComponents/QMUIMarqueeLabel'

**Comment by wdq123550** [comment]
good

**Comment by wdq123550** [comment]
not good
![image](https://github.com/user-attachments/assets/a638183e-1651-41ee-9015-9f6cd4b7348d)

**Comment by MoLice** [comment]
pod 'QMUIKit/QMUIComponents/QMUIMarqueeLabel'
