### ISSUE TITLE
qmui_imageWithView 方法使用问题，

### ISSUE THREAD

**Issue by Lee0820** [Tencent/QMUI_iOS#1561]
您好，请问下 qmui_imageWithView 这个方法，我当前的view上 有一个
    UIBlurEffect *effect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleDark];
    UIVisualEffectView *effectView = [[UIVisualEffectView alloc] initWithEffect:effect];
高斯模糊，覆盖在图片上即
UIView -> UIImageView -> UIVisualEffectView
使用这个方法生成image的时候，发现模糊效果没了，这种情况应该怎么处理呢，请问下？

**Comment by MoLice** [comment]
尝试用系统方法 `- [UIView snapshotViewAfterScreenUpdates:]`，若无效，没办法。
