### ISSUE TITLE
QMUIModalPresentationViewController 内存严重泄露

### ISSUE THREAD

**Issue by helloWotu** [Tencent/QMUI_iOS#1564]
**Bug 表现**
QMUIModalPresentationViewController 内存泄露严重，压根不释放

**截图**
<img width="1547" alt="image" src="https://github.com/user-attachments/assets/17d0621a-ad27-4deb-805f-c8d27ba0476f">

/// 屏幕宽度，会根据横竖屏的变化而变化
public let ScreenWidth = UIScreen.main.bounds.size.width

/// 屏幕高度，会根据横竖屏的变化而变化
public let ScreenHeight = UIScreen.main.bounds.size.height

class QMUIAlertView: UIView {
    
    
    override init(frame: CGRect) {
        super.init(frame: CGRectMake(0, 0, ScreenWidth, ScreenHeight))
        initSubViews()
    }
    
    deinit {
        print("QMUIAlertView 释放了")
    }
    
    private func initSubViews() {
        
        addSubview(bgButton)
        bgButton.snp.makeConstraints { make in
            make.center.equalToSuperview()
            make.size.equalTo(80)
        }
        
    }
 
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    public func show() {
        if let window = UIApplication.shared.keyWindow {
            modal.show(in: window, animated: true)
        }
    }
    
    @objc public func hide() {
        if let window = UIApplication.shared.keyWindow {
            modal.hide(in: window, animated: true)
        }
    }
    
    private lazy var modal: QMUIModalPresentationViewController = {
        let modal = QMUIModalPresentationViewController()
        modal.isModal = false
        modal.animationStyle = .slide
        modal.contentViewMargins = UIEdgeInsets.zero
        modal.contentView = self
        return modal
    }()

    private lazy var bgButton: UIButton = {
        let button = UIButton()
        button.addTarget(self, action: #selector(hide), for: .touchUpInside)
        button.backgroundColor = .cyan
        return button
    }()
}

调用：
  let qmuiAlert = QMUIAlertView()
   qmuiAlert.show()

**如何重现**
demo 弹出alert后，deinit 不会走，内存中就会存在一份，释放不了

**预期的表现**
deinit 会走，内存中释放

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.x]
 - QMUI 版本: QMUIKit (4.7.0)

**Comment by jiasongs** [comment]
跟QMUI没关系，你的QMUIAlertView持有modal，modal又持有contentView（QMUIAlertView），相互引用自然不会释放

**Comment by helloWotu** [comment]
> 跟QMUI没关系，你的QMUIAlertView持有modal，modal又持有contentView（QMUIAlertView），相互引用自然不会释放

大佬，你说的很对，那如何解决呢？ 
 @objc public func hide() {
        if let window = UIApplication.shared.keyWindow {
            modal?.hide(in: window, animated: true)
        }
        **modal?.contentView = nil**
    }
置空操作又没有啥用，把modal = nil，在某些机型上又会出现重复释放的的崩溃。大佬是如何使用的
