### ISSUE TITLE
APP启动的时候报错了

### ISSUE THREAD

**Issue by hyperkits** [Tencent/QMUI_iOS#1565]
**Bug 表现**
升级IOS 18后报错
'NSInternalInconsistencyException', reason: '如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。'
*** First throw call stack:
(0x19f68508c 0x19c9872e4 0x19ea5615c 0x1095cb8d4 0x1096f9b44 0x10800e71c 0x1080102a0 0x1096f9370 0x19c974820 0x1c4dffc90 0x1c4e38630 0x1c4e385dc 0x1c4e385dc 0x1c4e39ff0 0x1c4e05b80 0x1c4df526c 0x1c4e09c90 0x1c4e2e7a8 0x1c4e27b1c)
libc++abi: terminating due to uncaught exception of type NSException

**截图**

**如何重现**
1. ...
2. ...

**预期的表现**
正常打开应用

**其他信息**
 - 设备:  iphone 13 pro
 - iOS 版本:  18
 - Xcode 版本: Version 16.0
 - QMUI 版本: [4.x.x]

**Comment by wanglongshan** [comment]
同样遇到+1

**Comment by xiaoer-M** [comment]
同样的问题，Xcode16.0，debug模式下启动报错，release模式下可以正常运行

**Comment by xiaoer-M** [comment]
建议本地先按这个改https://github.com/Tencent/QMUI_iOS/pull/1555

**Comment by xiaoer-M** [comment]
建议本地先按这个改https://github.com/Tencent/QMUI_iOS/pull/1555，感谢作者大大给的解决方式

**Comment by xiaoer-M** [comment]
感谢作者大大给的解决方式，建议本地先按这个改 https://github.com/Tencent/QMUI_iOS/pull/1555

**Comment by MoLice** [comment]
已发布 [4.8.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.8.0) 修复该问题。
