### ISSUE TITLE
QMUIToastView吐司报错了

### ISSUE THREAD

**Issue by yuhang5455** [Tencent/QMUI_iOS#1566]
**Bug 表现**
闪退

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
Trapped uncaught exception 'NSInternalInconsistencyException', reason: 'Set `maskView` (<UIView: 0x146096140; frame = (0 0; 0 0); backgroundColor = UIExtendedSRGBColorSpace 1 1 1 0, RGBA(255, 255, 255, 0.00), #00ffffff; layer = <CALayer: 0x30130e6e0>>) to `nil` before adding it as a subview of <QMUITips: 0x136ee3c00; frame = (0 0; 334 187.333); alpha = 0; opaque = NO; tintColor = UIExtendedSRGBColorSpace 1 1 1 1, RGBA(255, 255, 255, 1.00), #ffffffff; backgroundColor = UIExtendedSRGBColorSpace 1 1 1 0, RGBA(255, 255, 255, 0.00), #00ffffff; layer = <CALayer: 0x3014f9e40>>

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone12]
 - iOS 版本: [iOS 18]
 - Xcode 版本: [Xcode 16.0]
 - QMUI 版本: [4.4.0]

**Comment by yuhang5455** [comment]
没有人能回答吗?QMUITips这个直接崩溃该怎么解决

**Comment by MoLice** [comment]
可先本地把 maskView 属性重命名为其他名字，因为它和系统自带的 maskView 同名，冲突了。QMUI 内部版本已经处理过，等发布后更新即可。

**Comment by BinBear** [comment]
QMUI新版本有发布计划吗

**Comment by lookingforfanyunfei** [comment]
> QMUI新版本有发布计划吗

同问

**Comment by ly415925488** [comment]
iOS 18 对 UIView的maskView 增加了断言，导致如果业务代码里有同名属性可能导致触发该断言。

**Comment by MoLice** [comment]
已发布 [4.8.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.8.0) 修复该问题。
