### ISSUE TITLE
DEBUG启动的时候报错

### ISSUE THREAD

**Issue by amoylong** [Tencent/QMUI_iOS#1567]
**Bug 表现**
断句在【QMUILogWarn(@"QMUIConfiguration", @"如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况");】

**截图**
![QQ_1726647953068](https://github.com/user-attachments/assets/a099e3ac-41da-49dc-89b4-f4852599b245)

**如何重现**
DEBUG模式下编译

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 18.0]
 - Xcode 版本: [Xcode 16.0]
 - QMUI 版本: [4.3.0]

**Comment by amoylong** [comment]
注释掉断句正常编译

**Comment by hootigger** [comment]
看代码应该是获取配置类的 如果注释,确实不报错了,但是明显不应该获取不到 配置表, 这样注释虽然能run, 但是配置表这些就没有生效吧?

**Comment by Riven-tang** [comment]
看了配置表之后呢，要做些什么修改吗？

**Comment by MoLice** [comment]
已发布 [4.8.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.8.0) 修复该问题。
