### ISSUE TITLE
iOS 18.1 beta版本crash

### ISSUE THREAD

**Issue by Retouch001** [Tencent/QMUI_iOS#1568]
**Bug 表现**
iOS 18.1 beta版本crash

**截图**
<img width="1333" alt="企业微信截图_b5281f6c-590f-48ed-9f9e-ab1b475c34b0" src="https://github.com/user-attachments/assets/ae3ae88a-bd4d-4c29-9bdf-d79d6b46f9d9">

崩溃具体错误信息如下：
NSInternalInconsistencyException
Inconsistency in UITabBar items and view controllers detected. No view controller matches the UITabBarItem '<UITabBarItem: 0x120bc0180> title='IT Services' image=<UIImage:0x300124120 named(main: tab_default) {25, 25} renderingMode=automatic(original)>, scale = 3 selected'.
 75-[UIControl(QMUI) setQmui_automaticallyAdjustTouchHighlightedInScrollView:]_block_invoke_4.16(UIControl+QMUI.m:)
UIKitCore + 660844
UIKitCore + 664800
CoreFoundation + 356856

**Comment by MoLice** [comment]
尝试更新 4.8.0 试试

**Comment by Retouch001** [comment]
好的，新版本可以修复，谢谢

**Comment by Retouch001** [comment]
最新版本没有类似问题
