### ISSUE TITLE
[UIKit Bug] iOS 11 及以后，带 UITabBar 的界面，某些情况下 safeAreaInsets.bottom 无法正确适配

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#218]
#### 问题表现

界面里的 `UIScrollView` 滚到底部后被 `UITabBar` 挡住了一部分，且从下一级界面 pop 回来后可看到 `UIScrollView` 位置发生跳动。

#### 相关截图（断点的堆栈、控制台的 log）

可看到滚动条底部被 `UITabBar` 盖住。
<img src="https://user-images.githubusercontent.com/1190261/61581836-25ba1500-ab56-11e9-82ef-c2d190a7d84c.png" width="400" /> 

#### 相关 Issue

[#934 全面屏设备下，带 TabBar 的界面在 push/pop 后，UIScrollView 的滚动位置可能发生变化](https://github.com/Tencent/QMUI_iOS/issues/934)

#### 重现条件
1. 创建一个 `UINavigationController`，里面放一个 `UIViewController`，且后者的 `extendedLayoutIncludesOpaqueBars = YES`。
1. 将 `UINavigationController` 放到 `UITabBarController` 内。
1. 在第2步的 `UIViewController` 内放一个 `UIScrollView` 并设置较大的 `contentSize.height` 以使其可滚动，并将其滚到底部。
    1. 如果 **`tabBar.translucent = YES`**（不要设置 `tabBar.backroundImage`，或者设置一张半透明的背景图，此时的 `tabBar.translucent` 即为 `YES`），则在 iOS 13.4 及以后均不会出现上文提到的问题，但 iOS 13.4 以前的版本依然有问题。
    1. 如果 **`tabBar.translucent = NO`**（设置 `tabBar.backgroundImage` 为一张不透明的图片，或者直接修改 `translucent = NO`），则在所有 iOS 版本均会出现上文提到的问题。

#### 测试 Demo

[TestTabBar.zip](https://github.com/Tencent/QMUI_iOS/files/4559647/TestTabBar.zip)

#### 运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.0 及以上`
- [x] Xcode 版本：`11.4.1`

**Comment by pptk** [comment]
你好。请问iOS 11的兼容预计什么时候做好。

**Comment by MoLice** [comment]
2.1.0 已兼容。

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。
