### ISSUE TITLE
iOS 11 searchBar 在某些情况下表现异常

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#223]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.0`
- [x] Xcode 版本：`9.0`
- [x] QMUI iOS 版本：`2.0.0`

### 请描述具体问题
界面 A 和 B 均使用 iOS 11 新接口显示 searchBar：
```Objective-C
self.navigationItem.searchController = xxx;
```
以下几种操作路径都会有问题：
1. 在界面 A 下拉，把 searchBar 显示出来，再 push 到界面 B，会看到界面 B 顶部先出现一条空白的东西，很快又消失。（换句话说，从有 searchBar 切换到没 searchBar 的界面，都会有这个问题）
![image](https://user-images.githubusercontent.com/1190261/31421504-542cb62e-ae0d-11e7-95ca-8012e927d629.png)
2. 界面 A 的 searchBar 不可见的情况下  push 到界面 B，下拉，把 searchBar 显示出来，手势返回但中途取消，停留在界面 B，会看到界面 B 的 searchBar 丢失了。

**Comment by wxlpp** [comment]
iOS11下self.navigationItem.titleView = searchController.searchBar后searchBar 的高度不正常

**Comment by SuperY** [comment]
@wxlpp 暂时暴力处理，但是聚焦后UI还会有偏移，继续研究中。。
`    
   if #available(iOS 11.0, *) {
            qmSearchController?.searchBar.heightAnchor.constraint(equalToConstant: 44).isActive = true
        }
`

**Comment by iTofu** [comment]
这是 iOS 系统原生 bug？
