### ISSUE TITLE
QMUIImagePreviewViewController在TableView中使用的个别崩溃情况

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#365]
### 请填写运行环境

- [x] 设备：`iPhone 6s`/ `模拟器`
- [x] 系统：`iOS 11.4`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.7.1`

### 请描述具体问题
具体崩溃条件：
通过tableView:didSelectRowAtIndexPath:方法获取cell中imageView，并且用startPreviewFromRectInScreen:方法打开QMUIImagePreviewViewController，这时QMUIImagePreviewViewController的viewDidAppear:方法中，zoomImageView为nil，触发断点："第 %@ 个 zoomImageView 不存在，可能当前还处于非可视区域"。

如果使用startPreviewFading方法，或者延迟执行startPreviewFromRectInScreen:方法，或者用点击cell.imageView来触发预览而不是用tableView:didSelectRowAtIndexPath:代理方法触发预览，都不会有问题。

#### 相关截图（断点的堆栈、控制台的 log）
![2018-07-10 11 08 03](https://user-images.githubusercontent.com/34535969/42487025-9a7c7fc4-8431-11e8-925e-551da940c28e.png)

**Comment by MoLice** [comment]
确实很神奇，我们查一下是怎么回事。

**Comment by passerbyloo** [comment]
因为`self.imagePreviewViewController.imagePreviewView.currentImageIndex = indexPath.row;`, 里面有叫`collectionView reloadData`, 而reloadData这个函数是异步的，还没来得及调用collection view的delegate和datasource方法，就紧接着调用`[self.imagePreviewViewController startPreviewFromRectInScreenCoordinate:[cell.imageView.superview convertRect:cell.imageView.frame toView:nil]];`，导致`viewDidAppear 
 里的startPreviewByTransformFromRect`函数里面的`zoomImageViewAtIndex`返回**nil**(因为里面的cell都没有创建)。而`startPreviewFading`和延迟执行`startPreviewFromRectInScreen `，都会有一点延迟而刚好使得`reloadData`函数调用完毕。

**Comment by MoLice** [comment]
[2.9.3](https://github.com/Tencent/QMUI_iOS/releases/tag/2.9.3) 重构了 `QMUIImagePreviewViewController`，并且在 `viewWillAppear:` 的 `reloadData` 后加上了 `layoutIfNeeded` 以触发立即刷新，从而解决这个问题，具体代码可点击查看 [QMUIImagePreviewViewController.m:119-120](https://github.com/Tencent/QMUI_iOS/blob/master/QMUIKit/QMUIComponents/QMUIImagePreviewView/QMUIImagePreviewViewController.m#L119-L120)

感谢 @passerbyloo 的提示。
