### ISSUE TITLE
使用 `IQKeyboardManager` 组件的 `IQKeyboardReturnKeyHandler` 功能时，`QMUIMultipleDelegates` 中出现崩溃

### ISSUE THREAD

**Issue by yuhanle** [Tencent/QMUI_iOS#374]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 11.1`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.7.4`

页面加载后，点击输入框，激活键盘即复现

### 请描述具体问题

在使用 `IQKeyboardManager` 组件的 `IQKeyboardReturnKeyHandler` 功能时，`QMUIMultipleDelegates` 中出现崩溃的问题，大概是 `forwardInvocation` 了 `textFieldShouldBeginEditing` 方法，造成了循环调用。

#### 相关截图（断点的堆栈、控制台的 log）

![image](https://user-images.githubusercontent.com/10498756/43399094-8709c102-943c-11e8-9509-d370b0224b13.png)

**Comment by MoLice** [comment]
请贴一下你使用 `QMUITextField` 和 `IQKeyboardReturnKeyHandler` 的相关代码。

**Comment by yuhanle** [comment]
@MoLice 你好，复现步骤上少提了一段，点击输入框，激活键盘的时候，就出现这个问题

附相关代码

```
#import "ViewController.h"
#import <IQKeyboardManager/IQKeyboardManager.h>
#import <QMUIKit/QMUIKit.h>

@interface ViewController ()

@property (nonatomic, strong) IQKeyboardReturnKeyHandler *returnHandler;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    [[IQKeyboardManager sharedManager] setEnable:YES];
    
    QMUITextField *textField = [[QMUITextField alloc] init];
    textField.backgroundColor = [UIColor orangeColor];
    [self.view addSubview:textField];
    
    textField.frame = CGRectMake(20, 300, self.view.frame.size.width - 40, 50);
    
    self.returnHandler = [[IQKeyboardReturnKeyHandler alloc] initWithViewController:self];
    [self.returnHandler setLastTextFieldReturnKeyType:UIReturnKeyDone];
}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end
```

**Comment by MoLice** [comment]
这里的问题在于，`IQKeyboardReturnKeyHandler` 会把 `QMUITextField.delegate` 改为自己，而因为 `QMUITextField` 打开了 `QMUIMultipleDelegates` 功能，所以它 setDelegate 的动作并不是“替换 delegate”，而是“增加 delegate”。

这属于 `QMUIMultipleDelegates` 的设计问题，短期内无法解决，建议在混用 `QMUITextField/QMUITextView` 和 `IQKeyboardManager` 时，把输入框的 `qmui_multipleDelegatesEnabled` 置为 `NO` 以关闭 `QMUIMultipleDelegates` 特性。

**Comment by yuhanle** [comment]
@MoLice 好的~  感谢

**Comment by shuiliang** [comment]
QMUIKeyboardManager 能完全代替 IQKeyboardManager吗，安全起见 在引入了 QMUIKit 后，我是不是可以删掉 IQKeyboardManager了？

**Comment by MoLice** [comment]
@shuiliang 取决于你使用 IQKeyboardManager 是为了什么功能，如果是键盘的事件监听，是可以用 QMUIKeyboardManager 取代的，如果是其他功能，例如自动调整 contentOffset 避免键盘挡住输入框，这些 QMUI 是没有的，需要手动调整。

**Comment by MoLice** [comment]
更新到 4.1.2 及以上的版本应该可以解决这个问题了。
