### ISSUE TITLE
QMUIAlbumViewController 是否支持单张图片点击后进入自己的裁剪页面，而不是非要走QMUIImagePickerPreviewViewController

### ISSUE THREAD

**Issue by OpenFeyn** [Tencent/QMUI_iOS#438]
选中一张图后需要进行裁剪。但接口一定要要返回一个QMUIImagePickerPreviewViewController对象。能否直接选中一张图后跳到自己的控制器，不使用预览功能

**Comment by MoLice** [comment]
暂时没有，这种需求目前你可以重写 didSelect 自己处理
