### ISSUE TITLE
QMUIButton在UITableView中遇到的布局问题

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#439]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.2`

### 请描述具体问题
autolayout和frame布局均会出现。
QMUIKit/QMUIComponents/QMUIButton/QMUIButton.m文件：
当[cell.contentView addSubview:aQMUIButton];
sizeThatFits:中：
self.imageView.image 为空，而 self.currentImage 非空，导致布局计算错误。
可否改为：
CGSize imageSize = self.imageView.image ? [self.imageView sizeThatFits:CGSizeMax] : self.currentImage.size;

#### 相关截图（断点的堆栈、控制台的 log）
![2018-11-22 5 36 12](https://user-images.githubusercontent.com/34535969/48894341-81c08280-ee7d-11e8-9733-ea2484d1e2bc.png)

**Comment by fanyuecheng** [comment]
找到原因了，因为我在初始化button的时候使用到了button.imageView，比如更改了button.imageView.backgroundColor 或者 button.imageView.contentMode，此时将会出现这种问题。

**Comment by targetkiller** [comment]
我这边按照你之前在另一处的截图和这里的截图的代码全部模拟了，发觉也不会有问题，哪怕改了 imageView 的各种属性。所以，可以麻烦你发一下代码到邮箱吗？

**Comment by fanyuecheng** [comment]
邪门了 难道是我写代码的姿势不对吗==！
Demo已发送。

**Comment by MoLice** [comment]
该问题是系统自身问题，QMUIButton 已在 [2.9.3](https://github.com/Tencent/QMUI_iOS/releases/tag/2.9.3) 版本里修复该 bug。
