### ISSUE TITLE
QMUIImagePreviewViewController在横屏时exitPreview的问题

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#445]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.2`

### 请描述具体问题
当控制器仅支持竖屏，但QMUIImagePreviewViewController支持各种方向时，在横屏时退出QMUIImagePreviewViewController，此时状态栏消失了。

**Comment by TheLittleBoy** [comment]
确实是，屏幕没有旋转过来，状态栏消失了。

**Comment by MoLice** [comment]
[2.9.3](https://github.com/Tencent/QMUI_iOS/releases/tag/2.9.3) 已重构 `QMUIImagePreviewViewController` 并修复该问题，请查看 Release Note。
