### ISSUE TITLE
storyboard 里面提供的label属性不生效

### ISSUE THREAD

**Issue by shuiliang** [Tencent/QMUI_iOS#455]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.1`

### 请描述具体问题

（UITableViewController）storyboard创建的cell, 里面提供的label属性设置后不生效

#### 相关截图（断点的堆栈、控制台的 log）

![1544665049821](https://user-images.githubusercontent.com/17922774/49909654-bba00a00-feba-11e8-912e-de8a799bdb3e.jpg)

**Comment by MoLice** [comment]
@TheLittleBoy 正解，需要在代码里手动设置 `qmui_borderPosition`，Interface Builder 不支持自定义的 enum。

**Comment by shuiliang** [comment]
好的,谢谢
