### ISSUE TITLE
为什么集成进去之后，影响了原项目的导航侧滑返回呢？我只想用一些控件的类，并不想使用vc相关的类

### ISSUE THREAD

**Issue by WanMeg** [Tencent/QMUI_iOS#457]
### 请填写运行环境

- [x] 

- 设备： `iPhone`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`最新版本`

### 请描述具体问题
将QMUIpod集成到项目里面后，没有在任何地方引用相关的文件，影响了原有项目的侧滑返回，
有看到说 “当自定义了`leftBarButtonItem`按钮之后，系统的手势返回就失效了。”,我在集成之前侧滑都是没有问题的，集成进来之后可能是哪里冲突了，帮忙解答一下吧谢谢
#### 相关截图（断点的堆栈、控制台的 log）

**Comment by MoLice** [comment]
> 当自定义了leftBarButtonItem按钮之后，系统的手势返回就失效了

这句话描述的是系统行为，不是 QMUI 使之。

你提供的信息过于模糊，例如我无法得知你原项目的手势返回是否有自定义过，或者使用其他第三方框架，建议提供一份能重现问题的最小代码 demo 发送到 contact@qmuiteam.com。

**Comment by WanMeg** [comment]
嗯嗯明白了，非常感谢您的详细解答。

**Comment by MoLice** [comment]
不客气
