### ISSUE TITLE
想请教一下为什么算圆角的时候，不是直接高度除以2？

### ISSUE THREAD

**Issue by passerbyloo** [Tencent/QMUI_iOS#458]
代码还有flat这一步操作。

**Comment by MoLice** [comment]
这里没有特别的考虑，只是一个习惯性操作，传一个像素对齐的值给它。实际效果肉眼是看不出差异的。

**Comment by passerbyloo** [comment]
那这个操作是会更加准确绘制圆角，还是反而会导致误差？（毕竟增加了一点计算量，如果反而是更不准确就更不好了）。

如果高是45的话，用flat算出来是22.666666，直接除以2是22.5

**Comment by MoLice** [comment]
经过 flat 处理的数值基本都与原值是不相符的，换句话说，理论上都是错的，唯一精准表达原值的方式就是直接使用原值，例如 22.5 在 3x 的屏幕上绘制会产生像素不对齐的模糊，但不能说这是错的，因为 22.5 本来就代表这样的效果，只不过我们普遍认为绘制时像素不对齐的现象一般都是不希望出现的，所以才在所有的布局、绘制场景下都加上 flat 的额外处理。

但在圆角这个场景下，不管如何处理，曲线必定意味着像素不对齐的存在，在这种情况下对 cornerRadius 使用 flat 并不会带来明显收益，但却可能导致圆角值偏大或偏小（误差浮动范围在 1px 内），得不偿失，所以下个版本我们将会去掉 cornerRadius 场景下的 flat 操作，感谢提出这个问题。

**Comment by passerbyloo** [comment]
謝謝你的解答。
另外听完你的解答，是说flat（不仅仅cornerRadius）的作用主要是为了解决像素不对齐的问题？，但是flat完之后的像素也都是小数，好像也没有解决绘制的问题。

而且有些计算frame的code都在重复flat。

例如
`_imageView.frame = CGRectSetXY(_imageView.frame, self.imageEdgeInsets.left, flat(CGFloatGetCenter(CGRectGetHeight(self.contentView.bounds), CGRectGetHeight(_imageView.frame)) + self.imageEdgeInsets.top));`

`CGRectSetXY ` 函数里面又对x,y做了flat

**Comment by passerbyloo** [comment]
謝謝，明白了。

另外`flatSpecificScale` function里面， scale求值写成`scale = scale ?: ScreenScale;`好像清楚点

**Comment by MoLice** [comment]
嗯可以
