### ISSUE TITLE
出现大量警告，Duplicate definition of category 还有两个报错信息，这是重复导入还是宏文件配置的错误？

### ISSUE THREAD

**Issue by 592424188** [Tencent/QMUI_iOS#461]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.0`
- [x] QMUI iOS 版本：`最新`

#### 相关截图（断点的堆栈、控制台的 log）
![wx20181221-164011](https://user-images.githubusercontent.com/22266959/50333531-a3765d80-0540-11e9-8654-7e7b94250d2e.png)
![wx20181221-164030](https://user-images.githubusercontent.com/22266959/50333537-a5402100-0540-11e9-9095-4b1b8359c027.png)

**Comment by 592424188** [comment]
![wx20181221-164100](https://user-images.githubusercontent.com/22266959/50333583-c56fe000-0540-11e9-8aed-a2e96e141c17.png)

**Comment by 592424188** [comment]
我注释掉报错的可以正常运行，可多出来这么多警告是什么意思呢？
![wx20181221-175430](https://user-images.githubusercontent.com/22266959/50336690-b80b2380-0549-11e9-8cb3-437d6514cfba.png)
![wx20181221-175446](https://user-images.githubusercontent.com/22266959/50336695-b9d4e700-0549-11e9-8ce7-94efe183b93a.png)
都是QMUIKit 相关的，我在本地其它项目中也用到了QMUIKit，都这样。求解决方法

**Comment by MoLice** [comment]
你是怎么引入 QMUI 的？

**Comment by 592424188** [comment]
pod的方式




| |
余韶彬
邮箱：yushaobin2610@163.com
|

签名由 网易邮箱大师 定制

在2018年12月21日 19:34，MoLice 写道：

你是怎么引入 QMUI 的？

**Comment by MoLice** [comment]
贴一下你的 pod 写法？

**Comment by 592424188** [comment]
![default](https://user-images.githubusercontent.com/22266959/50347801-dedd5000-0571-11e9-855b-b26b75efb6cd.PNG)

**Comment by MoLice** [comment]
按你的 Podfile 测试，空项目引入 QMUIKit，编译是成功的，截图所示也仅有一个业务项目自身的 warning，并没有出现你说的情况，建议自行排查。

![image](https://user-images.githubusercontent.com/1190261/50348824-e3efce80-0574-11e9-91c2-9751c276927a.png)

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
