### ISSUE TITLE
iOS 10，UITextFeild 切换搜狗输入法引发死循环

### ISSUE THREAD

**Issue by FantasticSkyBaby** [Tencent/QMUI_iOS#471]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：`iOS 10.0.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.3`

### 请描述具体问题
运行QMUI_Demo，进入QMUITextFiled,点击输入框（选中搜狗输入法）---->闪退

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/14800057/50478914-bf7d7180-0a0e-11e9-9878-26ccd424e36b.png)

**Comment by MoLice** [comment]
稍等哈，半小时后排到这个问题。

**Comment by MoLice** [comment]
是否只有 iOS 10 的系统才会？iOS 9 或者 11、12 呢？

**Comment by MoLice** [comment]
QMUI 2.9.3，Xcode 10.1，iOS 10.3.2 的真机上按 issue 所述操作，没有重现该问题。输入过程中切换任意输入法也不会出现 crash。附上录屏：
[操作录屏.zip](https://github.com/Tencent/QMUI_iOS/files/2714982/default.zip)

是否有其他条件？

**Comment by FantasticSkyBaby** [comment]
其余的系统好像都不会，10.3.3以及11都正常，只有10.0.2crash ，我拿手机录给你看下

**Comment by FantasticSkyBaby** [comment]
是的 手机没有越狱，我在项目上发现这个问题后直接运行的QMUI_Demo也是一点输入框就Crash，具体的视频可能要上班在给你去了哈

**Comment by FantasticSkyBaby** [comment]
[10.0.2 Crash.zip](https://github.com/Tencent/QMUI_iOS/files/2719781/10.0.2.Crash.zip)
![wechatimg15](https://user-images.githubusercontent.com/14800057/50578465-a3962780-0e75-11e9-987a-95d675af0295.jpeg)
@MoLice

**Comment by MoLice** [comment]
看起来像是死循环。你在左边调用堆栈那，拉到最底部，点击第一次出现循环时的调用关系我看看？

**Comment by FantasticSkyBaby** [comment]
![image](https://user-images.githubusercontent.com/14800057/50581783-ec5ed800-0e97-11e9-96db-fd1673cc8618.png)

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/50581825-4bbce800-0e98-11e9-97ed-763bbd37bd74.png)

取消这两个的选中，看看堆栈是否有多出来什么东西？

**Comment by FantasticSkyBaby** [comment]
![image](https://user-images.githubusercontent.com/14800057/50581961-7e1b1500-0e99-11e9-9a22-71a76520c6b8.png)

**Comment by MoLice** [comment]
好的我们查一下，在此之前你可以在 `UIView+QMUI.m` 里把 `qmuiview_viewDidLoad` 替换为以下代码，应该可以临时避免这个问题。
```Objective-C
- (void)qmuiview_viewDidLoad {
    [self qmuiview_viewDidLoad];
    if (@available(iOS 11.0, *)) {
        self.view.qmui_viewController = self;
    } else {
        ((UIView *)[self valueForKey:@"_view"]).qmui_viewController = self;
    }
}
```

**Comment by FantasticSkyBaby** [comment]
好的👌

**Comment by MoLice** [comment]
> AppDelegate的window如果用懒加载，也是会死循环的吧
> 
> ```
> - (UIWindow *)window {
>     if (!_window) {
>         _window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
>     }
>     return _window;
> }
> ```

@fanyuecheng 这是另一个问题，下个版本将会修复。

**Comment by MoLice** [comment]
[3.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.0) 已修复这个问题。

**Comment by MoLice** [comment]
@fanyuecheng 提的 UIWindow 的问题也已在 [3.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.0) 里修复。
