### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by jyyjkt** [Tencent/QMUI_iOS#473]
### iOS12

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`2.x.x`

#### 相关截图（断点的堆栈、控制台的 log）
<img width="1013" alt="2019-01-02 3 05 48" src="https://user-images.githubusercontent.com/13562566/50582785-ec62d600-0e9f-11e9-8692-7fcc9a26e6a4.png">
<img width="1013" alt="2019-01-02 3 05 48" src="https://user-images.githubusercontent.com/13562566/50582797-03a1c380-0ea0-11e9-8588-5def9bd1166f.png">

**Comment by MoLice** [comment]
这里具体是在 init 什么对象？截图中这个方法是 swizzle 重写，所以走到这里来不一定意味着 QMUI 有内存泄漏，可能只是其他 object 在 init 时有内存泄漏，所以提示到这里来而已。

**Comment by jyyjkt** [comment]
嗯我试试 直接初始化
