### ISSUE TITLE
TabBarHeight 宏返回高度不正确

### ISSUE THREAD

**Issue by xierwanasi** [Tencent/QMUI_iOS#475]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.3`

### 请描述具体问题
#define TabBarHeight (IS_IPAD ? (IS_NOTCHED_SCREEN ? 65 : 50) : PreferredValueForNotchedDevice(IS_LANDSCAPE ? 32 : 49, 49) + SafeAreaInsetsConstantForDeviceWithNotch.bottom)

#### 相关截图（断点的堆栈、控制台的 log）
![91546413316_ pic](https://user-images.githubusercontent.com/20069322/50582957-3ef0c200-0ea1-11e9-8909-53d97daf95b8.jpg)

**Comment by MoLice** [comment]
请更新到 3.0.0 即可，参考 #463

**Comment by xierwanasi** [comment]
感谢
