### ISSUE TITLE
QMUIModalPresentationViewController处理带键盘的弹出视图时， 在iOS10上keyboardHeight = 0

### ISSUE THREAD

**Issue by PreSwift** [Tencent/QMUI_iOS#476]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：iOS 10.3.3
- [x] Xcode 版本：10.1
- [x] QMUI iOS 版本：3.0.0

### 请描述具体问题
QMUIModalPresentationViewController处理带键盘的弹出视图时，layoutBlock，showAnimation，hideAnimation等方法中携带的keyboardHeight = 0，并且视图位置错误，如下图所示：
#### 相关截图

![img_1273](https://user-images.githubusercontent.com/11828021/50628390-e2f66e00-0f72-11e9-9f90-73fc9521d121.PNG)

**Comment by MoLice** [comment]
[3.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.0) 已修复该问题。
