### ISSUE TITLE
QMUIAlertController 某些属性的声明对 Swift 兼容不友好

### ISSUE THREAD

**Issue by provswin** [Tencent/QMUI_iOS#477]
### 请填写运行环境

- [x] 设备：`All`
- [x] 系统：`iOS 12.1.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.2`

### 请描述具体问题
我现在在使用Swift 4.2版本，发现现在使用QMUIAlertController时，里面有大量NSAttributedString相关的代码，在Swift中使用无法编译通过，例如：
```
// 在Swift中想调整sheetTitleAttributes
var titleAttributs = alertController.sheetTitleAttributes

// 尝试设置foregroundColor
titleAttributs![NSAttributedString.Key.foregroundColor] = UIColor.init(red: 53, green: 53, blue: 71, alpha: 0.5)
```

这样会出现报错提示：
Cannot subscript a value of type '[String : Any]' with an index of type 'NSAttributedStringKey'

整体QMUI中应该还有很多这样的内容，是否考虑升级一下相关的代码？

#### 相关截图（断点的堆栈、控制台的 log）

**Comment by MoLice** [comment]
下个版本会改过来

**Comment by provswin** [comment]
good

**Comment by MoLice** [comment]
[3.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.0) 已经改好。
