### ISSUE TITLE
导航设置透明，就变黑色。

### ISSUE THREAD

**Issue by FlyingNoob** [Tencent/QMUI_iOS#478]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.3`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.0`

### 请描述具体问题
设置导航颜色为透明，整个导航条就变黑色了

继承 qmuinavgationcontroller

**Comment by MoLice** [comment]
请贴出具体代码和具体表现的截图，不然这样的 issue 很难猜测。

**Comment by MoLice** [comment]
因不活跃而关闭
