### ISSUE TITLE
3.0.0 isNotchedScreen判断全面屏不准确

### ISSUE THREAD

**Issue by FantasticSkyBaby** [Tencent/QMUI_iOS#482]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：`iOS 12.0`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.0.0`

### 请描述具体问题
iPhone XS真机 isNotchedScreen始终返回NO
#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/14800057/51360677-9b8de700-1b07-11e9-8a63-d3a5ead48ed9.png)

**Comment by FantasticSkyBaby** [comment]
模拟器也是一样

**Comment by MoLice** [comment]
按你 issue 里提供的版本信息和设备信息试了一下没问题。你可以对比我的截图看看左边调用的堆栈是否一致吗？

![image](https://user-images.githubusercontent.com/1190261/51370342-c7be5d80-1b31-11e9-96f6-17131281d583.png)

**Comment by FantasticSkyBaby** [comment]
我在QMUIConfigurationTemplate里写了一个判断宏 把这个宏注释掉进去判断正常，我看我写个demo能不能复现

**Comment by FantasticSkyBaby** [comment]
![image](https://user-images.githubusercontent.com/14800057/51449947-82847080-1d69-11e9-900c-c2d0194d19b9.png)

**Comment by FantasticSkyBaby** [comment]
[QMUITestDemo.zip](https://github.com/Tencent/QMUI_iOS/files/2777421/QMUITestDemo.zip)
直接运行在上图那断点可复现，初步估计是跟IQKeyboardManager有关

**Comment by MoLice** [comment]
麻烦请用以下代码替换你本地的版本，再测试是否有问题？
注意，需要在 QMUIHelper.m 内增加 `#import "NSObject+QMUI.h"`

```Objective-C
+ (BOOL)isNotchedScreen {
    if (@available(iOS 11, *)) {
        if (isNotchedScreen < 0) {
            SEL peripheryInsetsSelector = NSSelectorFromString([NSString stringWithFormat:@"_%@%@", @"periphery", @"Insets"]);
            UIEdgeInsets peripheryInsets = UIEdgeInsetsZero;
            [[UIScreen mainScreen] qmui_performSelector:peripheryInsetsSelector withReturnValue:&peripheryInsets];
            if (peripheryInsets.bottom <= 0) {
                UIWindow *window = [[UIWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];
                peripheryInsets = window.safeAreaInsets;
                if (peripheryInsets.bottom <= 0) {
                    UIViewController *viewController = [UIViewController new];
                    [viewController loadViewIfNeeded];
                    window.rootViewController = viewController;
                    if (CGRectGetMinY(viewController.view.frame) > 20) {
                        peripheryInsets.bottom = 1;
                    }
                }
            }
            isNotchedScreen = peripheryInsets.bottom > 0 ? 1 : 0;
        }
    } else {
        isNotchedScreen = 0;
    }

    return isNotchedScreen > 0;
}
```

**Comment by FantasticSkyBaby** [comment]
没问题了 ，我项目中暂时改成这样会有问题么
#define IS_SCREEN_PHONE IS_65INCH_SCREEN || IS_61INCH_SCREEN || IS_58INCH_SCREEN

**Comment by MoLice** [comment]
已发布 3.1.1 修复该问题。
