### ISSUE TITLE
pop之后，不能再重新push

### ISSUE THREAD

**Issue by KaoUserName** [Tencent/QMUI_iOS#484]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`不同系统都一样`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.3`

### 请描述具体问题

正常的使用UINavigationController, 最近突然在pop之后，不能再重新push。具体也不知道做了什么操作产生的。
<QMUINavigationControllerTransitionDelegate> 的didPopInNavigationControllerWithAnimated有执行。

有什么可能会产生动画未完结的情况了

#### 相关截图（断点的堆栈、控制台的 log）

-[QMUINavigationController pushViewController:animated:]:333 | QMUILogLevelWarn | JWBaseNavigationController | JWBaseNavigationController, 上一次界面切换的动画尚未结束就试图进行新的 push 操作，为了避免产生 bug，拦截了这次 push。

**Comment by MoLice** [comment]
是否能继续 pop 由标志位 `isViewControllerTransiting` 的值来决定，建议按照截图的方式搜索，排查是哪一次 `isViewControllerTransiting = NO` 没有正确执行，导致一直认为动画尚未结束。

![image](https://user-images.githubusercontent.com/1190261/51423829-9d87a100-1c00-11e9-84ca-831e0cfd11a2.png)

**Comment by KaoUserName** [comment]
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/42034681/51426328-1fd58c80-1c24-11e9-9d81-82a689cf9883.png">
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/42034681/51426332-2fed6c00-1c24-11e9-99d6-397a4fd5b54b.png">
这两个方法都没有执行

**Comment by MoLice** [comment]
猜测是不是你的 viewController 的 viewWillAppear、viewDidAppear 忘了调用 super？

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。

**Comment by adampei** [comment]
我的是因为这俩方法忘记调用super了
```
- (void)viewDidAppear:(BOOL)animated
- (void)viewDidDisappear:(BOOL)animated
```
