### ISSUE TITLE
QMUIAsset获取缩略图失败

### ISSUE THREAD

**Issue by ZhangTonghai** [Tencent/QMUI_iOS#485]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：iOS 12.1
- [x] Xcode 版本：10.1
- [x] QMUI iOS 版本：3.0.0

### 请描述具体问题
使用QMUIAsset的- (NSInteger)requestOriginImageWithCompletion:(void (^)(UIImage *result, NSDictionary<NSString *, id> *info))completion withProgressHandler:(PHAssetImageProgressHandler)phProgressHandler;方法去获取缩略图，手机相册的照片都在iCloud，部分缩略图获取失败。
使用demo调试发现，获取缩略图这个方法没有没有将networkAccessAllowed这个属性设置为YES，个人猜测这个原因导致了无法获取云上的照片缩略图。
目前我个人的解决方案是如果在回调中没有获取到到图片并且info中的PHImageResultIsInCloudKey为true的话，重新设置option的networkAccessAllowed=YES再次请求。

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/6335614/51451024-3982eb00-1d6e-11e9-92a0-2a298177c9cc.png)

![image](https://user-images.githubusercontent.com/6335614/51450960-ef9a0500-1d6d-11e9-9765-6b46faa5a08f.png)

**Comment by MoLice** [comment]
先跟你确认一下，你 issue 正文里贴的方法名是 `requestOriginImageWithCompletion:`，而截图里的方法是 `requestThumbnailImageWithSize:`，你应该是在说后者是吧？

**Comment by kayo5994** [comment]
@ZhangTonghai 嗯，确实如果图片资源需要从 iCloud 下载，那么 `options` 都应该设置 `networkAccessAllowed  = YES`，目前在最新代码中已经进行了修改。

**Comment by MoLice** [comment]
已发布 3.1.1 修复该问题。
