### ISSUE TITLE
QMUIAlertController的富文本属性问题

### ISSUE THREAD

**Issue by peterios2016** [Tencent/QMUI_iOS#487]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

#### 相关截图（断点的堆栈、控制台的 log）
因为业务需要，弹窗的Message文字有部分是不同的颜色，比如“恭喜你抽到红包30元”中的“30”的颜色和其他文字不同。
但是你们提供的属性alertMessageAttributes是一个字典，无法对局部的文字进行修改，我不知道要如何设置range。

**Comment by MoLice** [comment]
目前是不支持的，对应的 messageLabel 也是在 .m 里，没开放出来。建议这种场景可用 customView 去实现，自由度更高。

**Comment by peterios2016** [comment]
> 目前是不支持的，对应的 messageLabel 也是在 .m 里，没开放出来。建议这种场景可用 customView 去实现，自由度更高。

已经通过KVC获取messageLabel了，不过还是希望后续版本可以加上NSAttributedString的属性~
