### ISSUE TITLE
关于QMUIDialogTextFieldViewController中textFieldTitleLabels属性

### ISSUE THREAD

**Issue by provswin** [Tencent/QMUI_iOS#489]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.1.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.2`

### 请描述具体问题
关于QMUIDialogTextFieldViewController中textFieldTitleLabels属性的get方法，是有意使用```NSMutableArray<QMUITextField *>```返回还是存在缺陷？
```
- (NSArray<QMUILabel *> *)textFieldTitleLabels {
    return self.mutableTextFields.copy;
}
```

**Comment by MoLice** [comment]
返回的是 copy，而不是 mutableTextFields 本身，没问题的。

**Comment by provswin** [comment]
不是，我发现textFieldTitleLabels和textFields返回一样的去了？
NSMutableArray<QMUITextField *> *mutableTextFields;声明是NSMutableArray<QMUITextField *>类型，而textFieldTitleLabels返回又声明是(NSArray<QMUILabel *> *)类型。
```
- (NSArray<QMUILabel *> *)textFieldTitleLabels {
    return self.mutableTextFields.copy;
}

- (NSArray<QMUITextField *> *)textFields {
    return self.mutableTextFields.copy;
}
```

**Comment by MoLice** [comment]
...
万万没想到，一级线上事故，最近会发小版本修复

**Comment by MoLice** [comment]
已发布 3.1.1 修复该问题
