### ISSUE TITLE
ViewController设置不同backgroundImage，在push及pop时出现黑色

### ISSUE THREAD

**Issue by Juice007** [Tencent/QMUI_iOS#491]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.1.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.0`

### 请描述具体问题
首先说下情况，在配置表里设置了`automaticCustomNavigationBarTransitionStyle`为YES，且TableViewController继承自`QMUICommonTableViewController`的话，push及pop是没有任何问题的。

但是我项目中的UITableViewController是静态的，所以就用的storyboard布局，因此就无法继承自`QMUICommonTableViewController`了。我的做法是新建了一个`StaticTableViewController`继承自`UITableViewController`，然后将`QMUICommonViewController`中的那些空视图啊，键盘管理这些方法复制到我的`StaticTableViewController`以达到静态的tableView也能用上QMUI的目的。

但是现在我的tableView继承自`StaticTableViewController`在push时就会出现黑色，自己在这个文件中`UINavigationController+NavigationBarTransition.m`断点调了很久，发现和继承自`QMUICommonTableViewController`比起来，好像该调用的方法也都调了的，实在没发现是哪里的问题

#### 相关截图（断点的堆栈、控制台的 log）
![20190123_194716](https://user-images.githubusercontent.com/16225027/51604483-e6649000-1f47-11e9-8456-57e9d396e31d.GIF)

**Comment by Juice007** [comment]
方便起见  再配个demo吧
[QMUIDemo.zip](https://github.com/Tencent/QMUI_iOS/files/2787106/QMUIDemo.zip)

**Comment by Juice007** [comment]
发现问题可以简化一下：vc直接继承自`UITableViewController`，再遵守`<QMUINavigationControllerDelegate>`的话，push&pop也是会有黑色出现的

**Comment by TheLittleBoy** [comment]
storyboard布局也是可以修改继承的父类哦~

**Comment by MoLice** [comment]
上文提到的 QMUIConsole 引发的 bug 已在 3.1.1 中修复。
