### ISSUE TITLE
QMUIButton 图片可显示在文字位置

### ISSUE THREAD

**Issue by WingCH** [Tencent/QMUI_iOS#492]
https://qmuiteam.com/ios/documents/
支持调整按钮里图片和文字的相对位置，图片可显示在文字的上、下、左、右（UIButton 只支持图片显示在文字左边）。

可以在storyboard設定嗎？

另外有詳細的説明檔？

**Comment by MoLice** [comment]
使用组件请直接阅读该组件的头文件，复杂功能也有 QMUI Demo 提供实际代码，官网仅供快速检索。
