### ISSUE TITLE
qmui_badgeString设置不生效问题

### ISSUE THREAD

**Issue by Jonas-o** [Tencent/QMUI_iOS#493]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.1.0`

### 请描述具体问题
UIBarItem (QMUIBadge)  设置qmui_badgeString对于使用CustomView创建的UIBarButtonItem支持有问题，比如使用QMUINavigationButton创建的UIBarButtonItem设置qmui_badgeString不生效

**Comment by Jonas-o** [comment]
另外，如果用常规的创建方式比如截图那样的，能出现效果但是控制台会有个LayoutConstraints警告
![Uploading 屏幕快照 2019-01-25 上午9.28.30.png…]()

**Comment by Jonas-o** [comment]
<img width="1272" alt="2019-01-25 9 28 30" src="https://user-images.githubusercontent.com/31504742/51720447-99d49e00-2088-11e9-870f-a15b8d3c00c8.png">
截图在此

**Comment by MoLice** [comment]
这个问题是因为 `UIButton` 的 `layoutSubviews` 内没有调用 super，导致 `qmui_layoutSubviewsBlock` 对 `UIButton` 无效，从而引发 badge 无法被布局的 bug。

下个版本修复。

**Comment by MoLice** [comment]
已发布 [3.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.2) 修复该问题。
