### ISSUE TITLE
QMUINavigationController类中qmuiNav_viewDidAppear方法未被调用

### ISSUE THREAD

**Issue by skystroll** [Tencent/QMUI_iOS#494]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.1`

### 请描述具体问题
项目抛出异常`上一次界面切换的动画尚未结束就试图进行新的 push 操作，为了避免产生 bug，拦截了这次 push。`
经过定位发现`QMUINavigationController`类中`- (void)qmuiNav_viewDidAppear:(BOOL)animated;`方法未执行。导致`isViewControllerTransiting`参数未能被正常赋值。发现较大可能是`load`方法中`ExchangeImplementations(class, @selector(viewDidAppear:), @selector(qmuiNav_viewDidAppear:));`出现问题，极有可能是其他三方库同样对`viewDidAppear`使用了方法交换。挨个排查禁用，发现是友盟统计。不知作者能否对此做相对应的适配，以及降低框架被外界影响的概率。另感谢作者开源！

**Comment by MoLice** [comment]
多个地方对同个方法进行 swizzle 理论上并不会有问题。建议发个出问题的 Demo 看看。

**Comment by skystroll** [comment]
> 多个地方对同个方法进行 swizzle 理论上并不会有问题。建议发个出问题的 Demo 看看。

Demo很简单，就是用了QMUI的VC基类和NAV基类，然后初始化了友盟服务。https://github.com/skystroll/SwizzleDemo.git

**Comment by MoLice** [comment]
友盟闭源，无法确认内部是如何实现的。QMUI 在这一点上的代码并没有问题，所以无法做到“对此作相应的适配”。

**Comment by davieds** [comment]
同样的出现了此问题，现有解决的办法吗？
