### ISSUE TITLE
作为 UINavigationController.rootViewController 的 QMUICommonViewController 在 viewDidLoad 时通过 becomeFirstResponder 升起键盘后，无法通过 shouldHideKeyboardWhenTouchInView 实现点击空白区域降下键盘的功能

### ISSUE THREAD

**Issue by jhchenchong** [Tencent/QMUI_iOS#495]
### 请填写运行环境

- [x] 设备： `模拟器`
- [x] 系统：`iOS 12.1.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.1`

### 请描述具体问题
初始化一个QMUITextField并且调用```[textField becomeFirstResponder]```点击空白处收起键盘失效 官方demo在QDTextFieldViewController的initSubviews添加```[self.textField becomeFirstResponder]```可以复现

**Comment by MoLice** [comment]
`QDTextFieldViewController` 里并没有“点击空白处收起键盘”的功能，我按你说的在 `initSubviews` 里调用 `becomeFirstResponder` 并且在 `QDTextFieldViewController` 里实现 `shouldHideKeyboardWhenTouchInView:` 后，经测试可以正常点击空白收起键盘。

如果还有问题，请把有问题的代码打包一份 Demo 发来看看。

**Comment by jhchenchong** [comment]
不好意思 是我这边的自己的问题

**Comment by jhchenchong** [comment]
@MoLice 如果当前控制器是根控制器，存在上述的问题。[Demo](https://github.com/jhchenchong/QMUITestDemo.git)

**Comment by MoLice** [comment]
点击空白降下键盘的功能，依赖于 `QMUICommonViewController.hideKeyboardManager` 的 `keyboardWillShow` 事件里去开启 tap 手势的 `enabled`，但如果是第二张截图那种，初始化完就 `becomeFirstResponder` 的写法，那么键盘的事件会被屏蔽掉，所以走不到那个改变 `enabled` 的地方，所以表现出来就是点击空白无法降下键盘。

这个我们再看如何修改，在此之间可以尝试更换 becomeFirstResponder 的调用时机，例如放到 viewWillAppear。

**Comment by MoLice** [comment]
已发布 [3.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.2) 修复该问题。
