### ISSUE TITLE
使用QMUIImagePreviewView在iOS9滑动图片到最左/最右后可以继续滑动

### ISSUE THREAD

**Issue by tgcasce** [Tencent/QMUI_iOS#499]
### 运行环境

- [x] 设备：iPhone
- [x] 系统：iOS 9.3.1
- [x] Xcode 版本：10.1
- [x] QMUI iOS 版本：3.1.1

### 具体问题
QMUIImagePreviewView第一张图时往左滑动或最后一张图往右滑动，松开。图片无法回复到边缘，一直停留在滑动的位置。

问题应该出在QMUICollectionViewPagingLayout的targetContentOffsetForProposedContentOffset:withScrollingVelocity:方法

在该方法中UICollectionViewScrollDirectionHorizontal的情况下，最左/最右时返回的CGPoint为collectionView的contentOffset，显然，在iOS9(iOS10及以上均不会)上无法恢复到正确位置

#### 相关截图（断点的堆栈、控制台的 log）
![iphone 6](https://user-images.githubusercontent.com/9710553/52162147-76ee5d80-270a-11e9-9504-9fea36edf263.png)

**Comment by MoLice** [comment]
已发布 [3.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.2) 修复该问题。

**Comment by wanhmr** [comment]
@MoLice 应该还没有修复，建议使用 floor 把 proposedContentOffset 的值修正一下，经实际测试来看，如果不是用 floor，依然会导致返回的 proposedContentOffset 不生效。

**Comment by wanhmr** [comment]
[demo.mp4.zip](https://github.com/Tencent/QMUI_iOS/files/3211555/demo.mp4.zip)
