### ISSUE TITLE
Storyboard上的崩溃bug，在故事板上放一个按钮，拖线push到另一个控制器，必崩！！！

### ISSUE THREAD

**Issue by xavierXing** [Tencent/QMUI_iOS#500]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

### 请描述具体问题
Storyboard上的崩溃bug，在故事板上放一个按钮，拖线push到另一个控制器，必崩！！！

传不了截图，不过这个bug是必现的，

#### 相关截图（断点的堆栈、控制台的 log）
[

](url)

**Comment by xavierXing** [comment]
现在又发现一个新问题，这个库不能与RAC一起使用，信号发送时，也是必崩！！！ - 限制太多了  -

**Comment by xavierXing** [comment]
建议只做UI层面即可，不要随意更换拦截系统事件～～～，否则会有意向不到的冲突；

**Comment by MoLice** [comment]
> 现在又发现一个新问题，这个库不能与RAC一起使用，信号发送时，也是必崩！！！ - 限制太多了 -

我们的项目里 RAC 与 QMUI 共用已经两年，并没有出现问题。建议贴出崩溃时的 log 和堆栈信息以供判断。

**Comment by xavierXing** [comment]
你可以做一个试试，RACCommand 创建点击命令，self.btn.command = 你设置的RACCommand

**Comment by MoLice** [comment]
> Storyboard上的崩溃bug，在故事板上放一个按钮，拖线push到另一个控制器，必崩！！！
没有发现这个问题，请提供录屏或者 Demo。

**Comment by passerbyloo** [comment]
may be u create a wrong `RACSignal`  for RACCommand init

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
