### ISSUE TITLE
iOS 9 下弹出 UIAlertController 会 crash

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#502]
### 请填写运行环境

- [x] 设备：`All`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.0`

### 请描述具体问题

弹出 `UIAlertController` 时会报 `UIAlertController:supportedInterfaceOrientations was invoked recursively!` 的错误。

**Comment by passerbyloo** [comment]
Have made a pr to fix the bug

**Comment by MoLice** [comment]
已发布 [3.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.2) 修复该问题。
