### ISSUE TITLE
确认下是否有代码更新或者更新按钮的功能。

### ISSUE THREAD

**Issue by yumengbdw** [Tencent/QMUI_iOS#503]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

### 请描述具体问题
App Store 被拒，项目中引入如下模块pod 'QMUIKit/QMUIComponents/QMUIDialogViewController'
确认下是是否有下载更新代码功能，或者更新按钮功能。谢谢了。
Guideline 2.5.2 - Performance - Software Requirements

During review, your app installed or launched executable code, which is not permitted on the App Store. Specifically, your app uses the itms-services URL scheme to install an app.

Please note that while educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code, such code may not be used for other purposes and such apps must make the source code completely viewable and editable by the user.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Software Requirements section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program. 
- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.

Guideline 4.0 - Design

Your app includes an update button or alerts the user to update the app, but the update button or alert does not link directly to the app’s page on the App Store.

Next Steps

To resolve this issue, please ensure that tapping the update button takes the user directly to the app’s page on the App Store to update the app.

**Comment by MoLice** [comment]
没有，请自行排查其他问题
