### ISSUE TITLE
部分页面想禁用侧滑返回手势，无效

### ISSUE THREAD

**Issue by lijunW** [Tencent/QMUI_iOS#505]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.0`

### 请描述具体问题
用QMUINav和QMUICommvc作为basevc,
部分页面想禁用侧滑返回手势，设置 self.navigationController.interactivePopGestureRecognizer.enabled = NO;后依然可以手势返回，请问下如何禁用部分页面侧滑返回手势

**Comment by MoLice** [comment]
经测试并没有发现这个问题，建议检查你执行那句代码时，`self.navigationController.interactivePopGestureRecognizer` 引用是否为 `nil`。

如果不为 nil 但依然失效，请打包一个可重现的 Demo 来看看。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。

**Comment by xiaomage1478** [comment]
> ### 请填写运行环境
> * [x]  设备：`All` / `iPhone` / `iPad` / `模拟器`
> * [x]  系统：`iOS 12.x`
> * [x]  Xcode 版本：`10.1`
> * [x]  QMUI iOS 版本：`3.1.0`
> 
> ### 请描述具体问题
> 用QMUINav和QMUICommvc作为basevc,
> 部分页面想禁用侧滑返回手势，设置 self.navigationController.interactivePopGestureRecognizer.enabled = NO;后依然可以手势返回，请问下如何禁用部分页面侧滑返回手势

请问你这个问题解决了么，我也遇到了这个问题
