### ISSUE TITLE
QMUINavigationTitleView 不支持 contentVerticalAlignment 的切换

### ISSUE THREAD

**Issue by shenguanjiejie** [Tencent/QMUI_iOS#506]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：iOS 12.1
- [x] Xcode 版本：10.1
- [x] QMUI iOS 版本：3.1.1

### 请描述具体问题
QMUINavigationTitleView默认状态下的titleLabel垂直方向没有居中,我将QMUINavigationTitleView.m第374行中的 '<' 号改为了 '<=' 后才能正常居中,请查看一下这里是不是应该是 '<=' .

ps:我没有用navigationBar,而是将一个view当做navigationBar使用,感觉这个应该没有影响吧.

```
CGFloat shouldTitleLabelCenterVertically = self.titleLabelSize.height + UIEdgeInsetsGetVerticalValue(titleEdgeInsets) <= contentSize.height;
```

**Comment by MoLice** [comment]
这是因为 QMUINavigationTitleView 没有良好支持 `contentVerticalAlignment` 导致的，下个版本会修复。

另外，你提的那个大于小于的判断符号不是用于这种情况下的，请关注后续的版本更新。

**Comment by MoLice** [comment]
已发布 [3.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.2) 修复该问题。
