### ISSUE TITLE
关于 UINavigationController+QMUI.m 提醒

### ISSUE THREAD

**Issue by HebeTienCoder** [Tencent/QMUI_iOS#507]
看见你们在该类目最后的`gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:`方法中说
`// 不知道为什么，系统竟然没有实现这个delegate，那么它是怎么处理返回手势和其他手势的优先级的`

其实系统实现了一个`_gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:`方法来代替，多了个下划线😂

**Comment by MoLice** [comment]
原来如此，多谢提示！

**Comment by zhoon** [comment]
@HebeTienCoder  原来如此，但是他是怎么调用这个下划线的方法呢？

**Comment by HebeTienCoder** [comment]
下划线方法`_gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:`是在

**Comment by HebeTienCoder** [comment]
> @HebeTienCoder 原来如此，但是他是怎么调用这个下划线的方法呢？

下划线方法`_gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:`是在

**Comment by HebeTienCoder** [comment]
> @HebeTienCoder 原来如此，但是他是怎么调用这个下划线的方法呢？

下划线方法`_gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:`是在
`@protocol UIGestureRecognizerDelegatePrivate<UIGestureRecognizerDelegate>`中的

`UIGestureRecognizer`默认对`UIGestureRecognizerDelegatePrivate `提供了支持
应该是以如下这种形式支持的
`// in UIGestureRecognizer.m
    BOOL result;
    if ([gestureRecognizer.delegate respondsToSelector:@selector(gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:)]) {
        result = [gestureRecognizer.delegate gestureRecognizer:gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:otherGestureRecognizer];
    }
    if (!result && [gestureRecognizer.delegate respondsToSelector:@selector(_gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:)]) {
        [(id<UIGestureRecognizerDelegatePrivate>)gestureRecognizer.delegate _gestureRecognizer:gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:otherGestureRecognizer];
    }`

**Comment by HebeTienCoder** [comment]
> @HebeTienCoder 原来如此，但是他是怎么调用这个下划线的方法呢？

@zhoon

下划线方法`_gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:`是在
`@protocol UIGestureRecognizerDelegatePrivate<UIGestureRecognizerDelegate>`中的

`UIGestureRecognizer`默认对`UIGestureRecognizerDelegatePrivate `提供了支持
应该是以如下这种形式支持的
`// in UIGestureRecognizer.m`
`BOOL result;`
`if ([self.delegate respondsToSelector:@selector(gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:)]) {`
`result = [self.delegate gestureRecognizer:self shouldBeRequiredToFailByGestureRecognizer:otherGestureRecognizer];`
`}`
`if (!result && [self.delegate respondsToSelector:@selector(_gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:)]) {`
`result = [(id<UIGestureRecognizerDelegatePrivate>)self.delegate _gestureRecognizer:self shouldBeRequiredToFailByGestureRecognizer:otherGestureRecognizer];`
`}`
`if (result) {`
`// to be continued`
`}`

**Comment by zhoon** [comment]
@HebeTienCoder 原来是还有个私有 delegate，有意思，多谢提示。

**Comment by HebeTienCoder** [comment]
> @HebeTienCoder 原来是还有个私有 delegate，有意思，多谢提示。

@zhoon 
啊哈哈，原来你已经回复了，我在留言板编辑代码的，edit了太多次就删了重发了😆
