### ISSUE TITLE
苹果出Swift5之后，大佬们有没有准备出Swift版本的打算呢

### ISSUE THREAD

**Issue by a714857512** [Tencent/QMUI_iOS#508]
苹果团队说Swift5，将会ABI稳定、同时也会有Swift版本的runtime。
最近在Swift中使用该框架，发现前期接入很麻烦，加上OC中的宏在Swift中都无法使用，更加的麻烦。

**Comment by MoLice** [comment]
短期内（一年）不会有 Swift 版本发布，但不排除内部会开始转换编码语言的可能。
