### ISSUE TITLE
UIImageView 开启了 qmui_smoothAnimation 后，sizeToFit 得到 CGSizeZero 的错误大小

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#509]
### 请填写运行环境
iOS 12.1.2
- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

### 请描述具体问题

        _gifView = [[UIImageView alloc] init];
        _gifView.qmui_smoothAnimation = YES;
        NSData* imageData = [NSData dataWithContentsOfFile:[BZMRefreshFooter pathForResource:@"loadmore" type:@"gif"]];
        _gifView.image = [UIImage sd_imageWithGIFData:imageData];
        [_gifView sizeToFit]; // sizToFit后会size为空，将qmui_smoothAnimation = NO后会解决。

**Comment by MoLice** [comment]
这是因为 `UIImageView (QMUI)` 没有重写 `sizeThatFits`，导致默认的 `sizeThatFits:` 实现里认为当前的 imageView 不存在 image，所以 `sizeToFit` 后得到 `CGSizeZero` 的大小。

下一个版本将会修复这个问题，在此之前有两种解决方式可供选择：
1. 使用 `_gifView.frame = CGRectSetSize(_gifView.image.size)` 来代替 `[_gifView sizeToFit]`。
2. 在 `UIImageView+QMUI.m` 内自行重写 `sizeThatFits:`，判断当存在 `self.qimgv_animatedImage` 时 `return self.qimgv_animatedImage.size`。

**Comment by MoLice** [comment]
[3.1.3](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.3) 已修复
