### ISSUE TITLE
双击第一个和第三个控制器的tabitem没有响应

### ISSUE THREAD

**Issue by BzHuang** [Tencent/QMUI_iOS#510]
### 请填写运行环境

- [x] 设备：iPhone 6ps、iPhone 6
- [x] 系统：iOS 10.2、iOS 11.2
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.0`

### 请描述具体问题
双击第一个和第三个控制器的tabitem没有响应

#### 相关截图（断点的堆栈、控制台的 log）
- (void)viewDidLoad {
    [super viewDidLoad];
    NSArray *array = @[
                       @{
                           @"title" : @"111",
                           @"VCClassName" : @"VYSessionListViewController",
                           @"norImageName" : @"tab_message_n",
                           @"selImageName" : @"tab_message_s",
                           },
                       
                       @{
                           @"title" : @"222",
                           @"VCClassName" : @"WorkbenchMainVC",
                           @"norImageName" : @"tab_work_n",
                           @"selImageName" : @"tab_work_s",
                           },
                       
                       @{
                           @"title" : @"333",
                           @"VCClassName" : @"MaillisMainVC",
                           @"norImageName" : @"tab_contacts_n",
                           @"selImageName" : @"tab_contacts_s",
                           },
                       
                       @{
                           @"title" : @"444",
                           @"VCClassName" : @"InformationListVC",
                           @"norImageName" : @"tab_market_n",
                           @"selImageName" : @"tab_market_s",
                           },
                       
                       @{
                           @"title" : @"555",
                           @"VCClassName" : @"MyMainVC",
                           @"norImageName" : @"tab_me_n",
                           @"selImageName" : @"tab_me_s",
                           },
                       ];
    NSArray *modelList = [TabBarItemConfig objectArrayWithArray:array];
    NSMutableArray *contrllerArray = [[NSMutableArray array]init];
    for (int i = 0; i < array.count; i++) {
        TabBarItemConfig *config = [modelList objectAtIndex:i];
        UIViewController *controller = [[NSClassFromString(config.VCClassName) alloc]init];
        controller.title = config.title;
        UINavigationController *nvc = [[QFBaseNavigationController alloc]initWithRootViewController:controller];
        [contrllerArray addObject:nvc];
        //
        UITabBarItem *item = [[UITabBarItem alloc]init];
        item.title = config.title;
        item.image = [[UIImage imageNamed:config.norImageName] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
        item.selectedImage = [[UIImage imageNamed:config.selImageName] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
        [item setTitleTextAttributes:@{NSForegroundColorAttributeName : RGB_NP(14.0, 174.0, 232.0)} forState:UIControlStateSelected];
        [item setTitleTextAttributes:@{NSForegroundColorAttributeName : RGB_NP(127.0, 127.0, 127.0)} forState:UIControlStateNormal];
        item.titlePositionAdjustment = UIOffsetMake(0.0, -4.0);
        item.tag = i;
        controller.tabBarItem = item;
    }
    self.viewControllers = contrllerArray;
    
    //
    UIImage *backgroundImage = [UIImage np_imageWithColor:RGB_NP(251.0, 251.0, 251.0) size:CGSizeMake(self.tabBar.width_np, self.tabBar.height_np)];
    self.tabBar.backgroundImage =  backgroundImage;
    
    UIImage *shadowmnBackgroundImage = [UIImage np_imageWithColor:RGB_NP(242.0, 242.0, 242.0) size:CGSizeMake(self.tabBar.width_np, 0.5)];
    self.tabBar.shadowImage = shadowmnBackgroundImage;
    // 双击 tabBarItem 的回调
    __weak __typeof(self)weakSelf = self;
    void (^tabBarItemDoubleTapBlock)(UITabBarItem *tabBarItem, NSInteger index) = ^(UITabBarItem *tabBarItem, NSInteger index) {
        
    };
    for (UITabBarItem *item in self.tabBar.items) {
        item.qmui_doubleTapBlock = tabBarItemDoubleTapBlock;
    }
}

**Comment by TheLittleBoy** [comment]
QMUI demo里有双击TabBarItem的例子，你再检查一下代码？

**Comment by MoLice** [comment]
没发现有问题，建议提供可重现的 Demo。
