### ISSUE TITLE
自动cell高度计算错误

### ISSUE THREAD

**Issue by shenguanjiejie** [Tencent/QMUI_iOS#515]
### 请填写运行环境

- [x] 设备： `iPhone`
- [x] 系统：`iOS 12.1.4`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题
同样的一个用autoLayout布局的cell,使用UITableView+FDTemplateLayoutCell.h可以正确计算cell高度,使用QMUIKit却返回的全部是45的高度
#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/9425605/53558287-aca82a00-3b82-11e9-841e-19fb84467657.png)
![image](https://user-images.githubusercontent.com/9425605/53558320-c0ec2700-3b82-11e9-80cd-8a3b6cfc935b.png)
主观上我不想使用UITableView+FDTemplateLayoutCell.h, 因为已经有一年多没有维护了,我希望能使用QMUI解决cell高度缓存的问题.

**Comment by shenguanjiejie** [comment]
刚简单看了一下源码,好像跟UITableView+FDTemplateLayoutCell中所做的处理差挺多的步骤,是不是没有对autoLayout的布局做太多适配啊

**Comment by zhoon** [comment]
QMUI 确实没有专门针对 AutoLayout 进行优化，Cell 自动计算高度这个后面会考虑支持。

**Comment by shenguanjiejie** [comment]
期待后续完善~

**Comment by TheLittleBoy** [comment]
@shenguanjiejie 我使用Masonry写cell很长时间了，QMUI可以自动计算高度啊，再配合使用缓存，效果很理想啊~

**Comment by shenguanjiejie** [comment]
@TheLittleBoy  也许你的cell不够复杂吧,我确实是这种情况

**Comment by zhoon** [comment]
@shenguanjiejie 可以把相关代码打包发出来看看吗，方便调试看看是哪里的问题

**Comment by shenguanjiejie** [comment]
等有空了我搞个demo吧

**Comment by MoLice** [comment]
这个属于 `QMUICellHeightCache` 控件，它目前对 Autolayout 的 cell 确实不支持，后续会再补充。

但我们更建议使用 `QMUICellHeightKeyCache` 组件搭配 `estimatedRowHeight` 使用，语法更简洁，具体请看 Demo 里的 `QDCellHeightKeyCacheViewController.m`。

![image](https://user-images.githubusercontent.com/1190261/55407336-5f0f4a80-5590-11e9-85b7-14945e026bcd.png)

**Comment by shenguanjiejie** [comment]
@MoLice  嗯嗯 好的 我有用到QMUICellHeightKeyCache 组件搭配 estimatedRowHeight 使用,这方面用起来体验挺好的.最近事情有点多,可能不会第一时间回复,抱歉.

**Comment by MoLice** [comment]
好的，遇到什么问题随时贴出来
