### ISSUE TITLE
pod update无法下载到最新版本

### ISSUE THREAD

**Issue by peterios2016** [Tencent/QMUI_iOS#517]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

### 请描述具体问题
已经把pod升级到最新的1.7.1beta，也执行了rm -rf ~/.cocoapods和pod setup，用pod search可以查到最新的3.1.2，但是使用pod update只能到2.9.3

**Comment by fanyuecheng** [comment]
pod 'QMUIKit', '~> 3.1.2' 这样不行吗

**Comment by peterios2016** [comment]
> pod 'QMUIKit', '~> 3.1.2' 这样不行吗
报错了，其实我是自己制作的库引用了QMUI，今天想更新一下版本发现只有2.9.3。报错信息如下
CocoaPods could not find compatible versions for pod "QMUIKit":
  In Podfile:
    FriendCircle (from `/Users/peter/Desktop/FriendCircle`) was resolved to 1.0.3, which depends on
      QMUIKit (~> 3.1.2)

Specs satisfying the `QMUIKit (~> 3.1.2)` dependency were found, but they required a higher minimum deployment target.

**Comment by peterios2016** [comment]
知道问题所在了，原来我的库最低支持版本是iOS8，不是9所以update不到最新版本

**Comment by Gayle448** [comment]
Specs satisfying the `QMUIKit (~> 3.1.2)` dependency were found, but they required a higher minimum deployment target.
请问3.1.2的版本是最低支持到iOS9吗？我设置成9还是报这个错。

**Comment by peterios2016** [comment]
> Specs satisfying the `QMUIKit (~> 3.1.2)` dependency were found, but they required a higher minimum deployment target.
> 请问3.1.2的版本是最低支持到iOS9吗？我设置成9还是报这个错。

你要把podfile里面的8也改成9哦

**Comment by Gayle448** [comment]
是的，忘记改podfile了，谢谢啊~
