### ISSUE TITLE
QMUIImagePreviewViewController打开一张小图时有问题

### ISSUE THREAD

**Issue by HebeTienCoder** [Tencent/QMUI_iOS#519]
### 请填写运行环境

- [x] 设备：All
- [x] 系统：iOS 12.x
- [x] Xcode 版本：10.x
- [x] QMUI iOS 版本：最新

QMUIImagePreviewViewController打开一张小图，测试size为{113, 70}, 会无法通过下拉手势触发dismiss。但是左右拉动是可以触发的。然后当我双击或pinch改变过zoomScale时，它就可以通过下拉手势触发dismiss，即使zoomScale恢复成1也会触发。很神奇的可能是系统引起的bug

**Comment by TheLittleBoy** [comment]
并没有复现你所说的问题哦。

**Comment by MoLice** [comment]
并没有重现你说的问题，代码截图和实际运行录屏如下：

![image](https://user-images.githubusercontent.com/1190261/55390651-3a07e100-556a-11e9-8578-2e3cdb1a1acd.png)

[small image.mov.zip](https://github.com/Tencent/QMUI_iOS/files/3033126/small.image.mov.zip)

如果仍有问题，请提供可重现的完整代码或者 Demo 项目并重新打开 issue。
