### ISSUE TITLE
6.1和6.5英寸的屏幕点数错误

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#520]
运行iPhone XS或者XS Max模拟器时：
if(IS_58INCH_SCREEN) {
// 进入这里
}
if(IS_61INCH_SCREEN){
// 不走这里
}
if(IS_65INCH_SCREEN){
// 不走这里
}
调试发现：[UIScreen mainScreen].bounds为375x812，因此：
+ (CGSize)screenSizeFor65Inch {
    return CGSizeMake(414, 896);
}

+ (CGSize)screenSizeFor61Inch {
    return CGSizeMake(414, 896);
}
是不是有问题，它们的值是不是应该都是375x812？
如果是这样，那么is61InchScreen和is65InchScreen判断方式是否有误？

**Comment by tospery** [comment]
貌似模拟器是无法判断出设备的英寸大小

**Comment by TheLittleBoy** [comment]
代码是没问题的哦。所有屏幕尺寸汇总——>[传送门](https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions) 
另外，由于 iPhone XS Max 和 iPhone XR 的屏幕宽高是一致的，我们通过机器 Identifier 加以区别。但是，对于模拟器就无法区分了哦。

**Comment by tospery** [comment]
我这里没有Max真机，模拟器的[UIScreen mainScreen].bounds为375x812，跟文档不一致呢

**Comment by tospery** [comment]
我认为QMUI不应该通过英寸来对屏幕分类，比如对于5.5英寸的plus设备，通过screenSizeFor55Inch方法来获取屏幕点的时候，返回414x736。这在放大模式下（设置->显示->视图）不是对的，放大模式下应该是375x667。

**Comment by tospery** [comment]
pull request的时候加入腾讯协议，没有agress按钮。建议修改：
1. 解决Plus手机的放大模式判断失败
/// 是否放大模式（iPhone 6及以上的设备支持放大模式）
#define IS_ZOOMEDMODE ((DEVICE_HEIGHT == [QMUIHelper screenSizeFor40Inch].height && ScreenNativeScale > ScreenScale) || (DEVICE_HEIGHT == [QMUIHelper screenSizeFor47Inch].height && ScreenNativeScale < ScreenScale))
2. 解决放大模式的英寸判断错误的问题
static NSInteger is55InchScreen = -1;
+ (BOOL)is55InchScreen {
    if (is55InchScreen < 0) {
        if (IS_ZOOMEDMODE) {
            is55InchScreen = (DEVICE_WIDTH == self.screenSizeFor47Inch.width && DEVICE_HEIGHT == self.screenSizeFor47Inch.height) ? 1 : 0;
        }else {
            is55InchScreen = (DEVICE_WIDTH == self.screenSizeFor55Inch.width && DEVICE_HEIGHT == self.screenSizeFor55Inch.height) ? 1 : 0;
        }
    }
    return is55InchScreen > 0;
}

static NSInteger is47InchScreen = -1;
+ (BOOL)is47InchScreen {
    if (is47InchScreen < 0) {
        if (IS_ZOOMEDMODE) {
            is47InchScreen = (DEVICE_WIDTH == self.screenSizeFor40Inch.width && DEVICE_HEIGHT == self.screenSizeFor40Inch.height) ? 1 : 0;
        }else {
            is47InchScreen = (DEVICE_WIDTH == self.screenSizeFor47Inch.width && DEVICE_HEIGHT == self.screenSizeFor47Inch.height) ? 1 : 0;
        }
    }
    return is47InchScreen > 0;
}

**Comment by zhoon** [comment]
> 我这里没有Max真机，模拟器的[UIScreen mainScreen].bounds为375x812，跟文档不一致呢

模拟器并不会出现你说的这个问题，还是会返回 size = (width = 414, height = 896)，怀疑是不是你的启动页没有是配 Max 设备导致的。至于放大模式，那就是另外的问题了。

**Comment by MoLice** [comment]
> 我认为QMUI不应该通过英寸来对屏幕分类，比如对于5.5英寸的plus设备，通过screenSizeFor55Inch方法来获取屏幕点的时候，返回414x736。这在放大模式下（设置->显示->视图）是不对的，放大模式下应该是375x667。建议：通过屏幕点来对分类，因为同一个英寸的设备可以有不同屏幕点。

在 UI 布局的层面，当 55inch 的设备处于放大模式时，本来就不再希望以 55inch 来识别了，而是当成更小尺寸的屏幕来对待，所以 QMUI 的实现是合理的。

按你的说法，你需要的应该是物理设备的区分方法，而不是 UI 布局层面的屏幕大小区分方法。那是另外的需求，需要增加另外的方法去满足它。只不过从 UI 布局层面，这种需求暂不存在，所以 QMUI 里没有提供这方面的代码。
