### ISSUE TITLE
QMUIDialogTextFieldViewController 键盘遮挡问题

### ISSUE THREAD

**Issue by ThisSummerCold** [Tencent/QMUI_iOS#523]
### 请填写运行环境

- [x] 设备：`iphoneX`
- [x] 系统：`iOS 12.1.4`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.1`

### 请描述具体问题
键盘遮挡到了输入框
#### 相关截图（断点的堆栈、控制台的 log）
![WechatIMG1](https://user-images.githubusercontent.com/10990980/54429174-bde45f80-475a-11e9-984c-96b6de51982a.jpeg)
![WechatIMG2](https://user-images.githubusercontent.com/10990980/54429187-c472d700-475a-11e9-8f1a-5c0ca91bd07c.jpeg)

**Comment by ziecho** [comment]
从键盘上加的那个 toolbar 看起来应该是你使用了 IQKeyboardManager 导致，
IQKeyboardManager 会在 TextField 激活时，自动调整布局使得键盘距离 TextField 10pt，
 IQKeyboardManager 提供了一个方法针对某个 viewController 禁用自动调整的方法
比如，你可以尝试在初始化 IQKeyboardManager 时添加以下代码解决
 [[IQKeyboardManager sharedManager].disabledDistanceHandlingClasses addObject:[QMUIDialogViewController class]];
