### ISSUE TITLE
QMUIImagePickerViewController属性minimumImageWidth在 iPhone X 上问题

### ISSUE THREAD

**Issue by JanXu-Dev** [Tencent/QMUI_iOS#524]
### 请填写运行环境

- [x] 设备：iPhone X
- [x] 系统：iOS 12.x
- [x] Xcode 版本：10.x
- [x] QMUI iOS 版本：3.x.x

### 请描述具体问题
在 iPhone X 上, 设置 minimumImageWidth 的值, 无论怎么设置都无法使之3列显示, 要么4/4+, 要么2列中间留空, 设置 screen 的比例不行, 设置具体的值也不行, 设为92显示4列, 设置为93显示为2列, XR, Plus 系列正常, 其他设备未验证, 但是 iPhone X 就是这个情况.

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/7987282/54528570-54fa2300-49b8-11e9-9178-c7e45e84a75b.png)

**Comment by ziecho** [comment]
设置 3 列可以如下设置
```objc
imagePickerViewController.minimumImageWidth = SCREEN_WIDTH / 3.0;
```
但是实际上是 2 列
导致这个问题是因为 QMUI 内部默认加上了间隙

https://github.com/Tencent/QMUI_iOS/blob/c18b96018417aea22bf74d7e554781eca8355d89/QMUIKit/QMUIComponents/ImagePickerLibrary/QMUIImagePickerViewController.m#L99-L102

导致你计算出来的 宽度 * 列数 再加上间距超过了屏幕宽度，被变成两列：
https://github.com/Tencent/QMUI_iOS/blob/c18b96018417aea22bf74d7e554781eca8355d89/QMUIKit/QMUIComponents/ImagePickerLibrary/QMUIImagePickerViewController.m#L292-L294

所以，应该这么写
```objc
    NSUInteger columnCount = 3;
    CGFloat spacing = UIEdgeInsetsGetHorizontalValue(imagePickerViewController.collectionViewLayout.sectionInset) + (columnCount - 1) * imagePickerViewController.collectionViewLayout.minimumInteritemSpacing;
    imagePickerViewController.minimumImageWidth = (SCREEN_WIDTH - spacing) / columnCount;
```
但是这仍然不生效，进一步调试发现，QMUI 最终返回的大小会重新计算一次
https://github.com/Tencent/QMUI_iOS/blob/c18b96018417aea22bf74d7e554781eca8355d89/QMUIKit/QMUIComponents/ImagePickerLibrary/QMUIImagePickerViewController.m#L296-L297

在此时返回了一个有小数点的宽度，如果对这个宽度向下取整则可完美显示 3 列
```objc
    referenceImageWidth = floor(referenceImageWidth);
    return CGSizeMake(referenceImageWidth, referenceImageWidth);
```

建议：
1、如果修改源码，可暂时添加上上述向下取整代码，并采用上面的计算宽度
2、如果你不需要间隙可进行如下设置：

```objc
    imagePickerViewController.collectionViewLayout.sectionInset = UIEdgeInsetsZero;
    imagePickerViewController.collectionViewLayout.minimumInteritemSpacing = 0;
    imagePickerViewController.collectionViewLayout.minimumLineSpacing = 0;
    imagePickerViewController.minimumImageWidth = SCREEN_WIDTH / 3;
```

**Comment by zhoon** [comment]
@JanXu-Dev @ziecho 新版版将会添加一些注释说明并且做保护，请等待新版本

**Comment by MoLice** [comment]
[3.1.3](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.3) 已修复
