### ISSUE TITLE
Plus手机放大模式判断失败，以及放大模式下英寸判断错误的问题

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#526]
pull request的时候加入腾讯协议，没有agress按钮。建议修改：
1. 解决Plus手机的放大模式判断失败
/// 是否放大模式（iPhone 6及以上的设备支持放大模式）
#define IS_ZOOMEDMODE ((DEVICE_HEIGHT == [QMUIHelper screenSizeFor40Inch].height && ScreenNativeScale > ScreenScale) || (DEVICE_HEIGHT == [QMUIHelper screenSizeFor47Inch].height && ScreenNativeScale < ScreenScale))
2. 解决放大模式的英寸判断错误的问题
static NSInteger is55InchScreen = -1;
+ (BOOL)is55InchScreen {
    if (is55InchScreen < 0) {
        if (IS_ZOOMEDMODE) {
            is55InchScreen = (DEVICE_WIDTH == self.screenSizeFor47Inch.width && DEVICE_HEIGHT == self.screenSizeFor47Inch.height) ? 1 : 0;
        }else {
            is55InchScreen = (DEVICE_WIDTH == self.screenSizeFor55Inch.width && DEVICE_HEIGHT == self.screenSizeFor55Inch.height) ? 1 : 0;
        }
    }
    return is55InchScreen > 0;
}

static NSInteger is47InchScreen = -1;
+ (BOOL)is47InchScreen {
    if (is47InchScreen < 0) {
        if (IS_ZOOMEDMODE) {
            is47InchScreen = (DEVICE_WIDTH == self.screenSizeFor40Inch.width && DEVICE_HEIGHT == self.screenSizeFor40Inch.height) ? 1 : 0;
        }else {
            is47InchScreen = (DEVICE_WIDTH == self.screenSizeFor47Inch.width && DEVICE_HEIGHT == self.screenSizeFor47Inch.height) ? 1 : 0;
        }
    }
    return is47InchScreen > 0;
}

**Comment by zhoon** [comment]
其实我们这里的返回是对的，即使是55英寸的屏幕，如果是放大模式导致返回NO，那就认为你不是55屏幕，可能命名会有些疑惑。这些宏并不是判断某个硬件的屏幕，而是判断软件层面的。

**Comment by MoLice** [comment]
请参考 https://github.com/Tencent/QMUI_iOS/issues/520#issuecomment-475556640
