### ISSUE TITLE
语法错误：QMUICellHeightCache

### ISSUE THREAD

**Issue by Simon-Zeng** [Tencent/QMUI_iOS#527]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.1.4`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题
在QMUICellHeightCache.m文件里，有一处语法错误："akey" 应更正为"aKey"
方法: -[UITableView qmuiTableCache_deleteRowsAtIndexPaths: withRowAnimation:]
原文：
`
            [mutableIndexSetsToRemove enumerateKeysAndObjectsUsingBlock:^(NSNumber *aKey, NSIndexSet *indexSet, BOOL *stop) {
                NSMutableArray<NSNumber *> *heightsInSection = obj.cachedHeights[akey.integerValue];
                [heightsInSection removeObjectsAtIndexes:indexSet];
            }];
`

BTW, QMUI_iOS在项目中存在大量如下警告，能否更新代码消除以下警告？：
Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

谢谢

**Comment by zhoon** [comment]
不是 akey 而是 key 吧？这个我们已经发现并且修改了，后面版本会更新，多谢提醒。
另外警告的问题应该是你混合使用了 swift 使用才会？后面会消除。

**Comment by MoLice** [comment]
已更正
