### ISSUE TITLE
侧滑返回失效问题

### ISSUE THREAD

**Issue by ChengLuffy** [Tencent/QMUI_iOS#528]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.1.4`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题

当 `viewController` 的 `preferredNavigationBarHidden` 设定返回值为 `YES` 时，侧滑返回失效

**Comment by ziecho** [comment]
隐藏了导航栏后，系统原生是不支持手势返回的，QMUI 默认不会干预这个行为，如果你需要在隐藏导航栏仍然支持手势返回，可以在 viewController 里写上：

```objc
- (BOOL)forceEnableInteractivePopGestureRecognizer {
    return YES;
}
```

**Comment by zhoon** [comment]
@ziecho 正解
