### ISSUE TITLE
QMUILabel 的 contentEdgeInsets 在设置 lineBreakMode 的时候有问题

### ISSUE THREAD

**Issue by Joan-m** [Tencent/QMUI_iOS#529]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题

Label.contentEdgeInsets = UIEdgeInsetsMake(10, 0, 10, 0);
Label.lineBreakMode = NSLineBreakByWordWrapping;

在设置 lineBreakMode 后会出现 padding 全部加到了 bottom 的问题

#### 相关截图（断点的堆栈、控制台的 log）
![259031553135896_ pic](https://user-images.githubusercontent.com/24819039/54731906-d249b180-4bcb-11e9-8b6a-64496c4595b3.jpg)

**Comment by zhoon** [comment]
不需要设置 lineBreakMode 或者设置 nunberOfLines = 0 即可。
至于为什么 NSLineBreakByWordWrapping 会有问题，猜测是命中了系统内部的一些判断，导致 drawTextInRect: 重置 rect 失效。

**Comment by ziecho** [comment]
这个问题需要满足 3 个条件才会出现
1. label.lineBreakMode  为`NSLineBreakByWordWrapping` 或 `NSLineBreakByCharWrapping`
2. label.numberOfLines == 1
3. label.contentEdgeInsets.top > 0

通过简单调试猜测，UILabel 符合上述条件时，会忽略 `- (void)drawTextInRect:(CGRect)rect` 这个方法中 rect 的 y 值进行绘制，内容始终从上面开始，绘制单行，且 centerX = rect.height / 2 (内容居中于高度)

根据上述绘制原理，这里提供一种简单的修复方法
```objc
- (void)drawTextInRect:(CGRect)rect {
    CGRect drawInRect = UIEdgeInsetsInsetRect(rect, self.contentEdgeInsets);
    if ((self.lineBreakMode == NSLineBreakByWordWrapping || self.lineBreakMode == NSLineBreakByCharWrapping) && self.numberOfLines == 1 && self.contentEdgeInsets.top > 0) {
        CGSize size = [super sizeThatFits:CGSizeZero];
        drawInRect.size.height = self.contentEdgeInsets.top * 2 + size.height;
    }
    [super drawTextInRect:drawInRect];
}
```

**Comment by zhoon** [comment]
一行 label 基本不会设置 NSLineBreakByWordWrapping 这种属性，不过我按照 @ziecho 说的还是做个保护吧

**Comment by MoLice** [comment]
[3.1.3](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.3) 已修复
