### ISSUE TITLE
IS_ZOOMMODE判断失败

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#530]
iPhone 7 Plus在放大模式下调用该宏，判断失败

**Comment by ziecho** [comment]
在 iPhone 6/7/8 Plus 的设备下，渲染的像素是 1242 × 2208，而设备真实的物理像素是 1080 × 1920
导致这个问题的原因是，[[UIScreen mainScreen] nativeScale] 拿到的 scale = 物理像素 / mainScreen Width 

在标准模式下 nativeScale = 1080 / 414 = 2.60
而在放大模式下 nativeScale = 1080 / 375 = 2.88
在没有处理这种情况下直接用 ScreenNativeScale > ScreenScale 是无法得到正确的结果。

目前渲染像素和物理像素，这有这个系列的机型，所以可以简单判断，针对此情况的 scale 进行修正即可判断正确

```objc
- (BOOL)isZoomedMode {
    // iPhone 6/7/8 Plus 的物理像素
    CGSize specificNativeSize = CGSizeMake(1080, 1920);
    CGFloat scale = [UIScreen mainScreen].scale;
    if (CGSizeEqualToSize([UIScreen mainScreen].nativeBounds.size, specificNativeSize)) {
        // 这个像素的设备实际上是以 1.15 倍显示的， 而 [UIScreen mainScreen].scale 是渲染层面的 scale，这里除以 1.15 转换为物理像素对应的 scale
        scale = scale / 1.15;
    }
    return (ScreenNativeScale > scale);
}

```

**Comment by tospery** [comment]
测试通过！谢谢，建议下个版本修复下IS_ZOOMEDMODE宏定义呢。

**Comment by tospery** [comment]
建议修复方式：
#define IS_ZOOMEDMODE ((CGSizeEqualToSize(ScreenNativeBoundsSize, CGSizeMake(1080, 1920)) || CGSizeEqualToSize(ScreenNativeBoundsSize, CGSizeMake(1920, 1080))) ? (ScreenNativeScale > (ScreenScale / 1.15)) : (ScreenNativeScale > ScreenScale))

**Comment by ziecho** [comment]
@tospery 👍
不过 nativeBounds 的 width 和 height 是不受屏幕旋转影响的，所以不用判断宽高倒过来的情况
> This rectangle is based on the device in a portrait-up orientation. This value does not change as the device rotates.

**Comment by MoLice** [comment]
https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions

Plus 系列的 iPhone 实际物理像素低于渲染像素，所以会出现单纯判断 nativeScale > scale 不准确的问题，通过 1.15 的系数换算后再去比较才是正确的，下个版本会修复这个问题。

附上全设备测试结果备忘。
![image](https://user-images.githubusercontent.com/1190261/55223336-ee42f800-5248-11e9-86b4-4fdfda5ad2f9.png)

**Comment by MoLice** [comment]
[3.1.3](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.3) 已修复
