### ISSUE TITLE
建议：QMUIViewBorderPosition 增加 all的枚举值

### ISSUE THREAD

**Issue by gongqiuwei** [Tencent/QMUI_iOS#531]
QMUIViewBorderPosition，如果使用qmui的boder，必须的一个一个设置，建议增加一个all 的情况，这个比较常用。。

**Comment by zhoon** [comment]
需要设置所有边可以用系统 layer 默认的 border，QMUI border 是为了单独设置某几条边才做的

**Comment by gongqiuwei** [comment]
// 设定圆角 & 边框
    private func setupInpuViewBoder(_ view: UIView) {
        view.layer.cornerRadius = 16
        view.layer.qmui_maskedCorners = [.layerMaxXMinYCorner, .layerMaxXMaxYCorner, .layerMinXMaxYCorner]
        view.qmui_borderColor = UIColor.white
        view.qmui_borderWidth = 2
        view.qmui_borderLocation = .outside
        view.qmui_borderPosition = [.left, .right, .top, .bottom]
    }

这个是我用到的一个情况，即需要border, 又需要圆角，如果根据qmui_maskedCorners的提示，如果增加border的话使用系统的会被切掉。。。。所以需要用到qmui的，

**Comment by gongqiuwei** [comment]
/**
 *  设置四个角是否支持圆角的，iOS11 及以上会调用系统的接口，否则 QMUI 额外实现
 *  @warning 如果对应的 layer 有圆角，则请使用 QMUI_Border，否则系统的 border 会被 clip 掉
 *  @warning 使用 qmui 方法，则超出 layer 范围内的内容都会被 clip 掉，系统的则不会
 *  @warning 如果使用这个接口设置圆角，那么需要获取圆角的值需要用 qmui_originCornerRadius，否则 iOS 11 以下获取到的都是 0
 */
@property(nonatomic, assign) QMUICornerMask qmui_maskedCorners;

**Comment by MoLice** [comment]
```Objective-C
view.layer.cornerRadius = 16;
view.layer.borderWidth = 1;
view.layer.borderColor = UIColor.white;
```

这样设置并无问题，应该也是符合你的需求的。四条边都需要 border 的情况直接用系统提供的接口满足是最优解，没必要用 QMUI 的。
