### ISSUE TITLE
Nav转场动画问题

### ISSUE THREAD

**Issue by Jack-Ving** [Tencent/QMUI_iOS#532]
当实现了 - (NSString *)customNavigationBarTransitionKey；后，
业务需要 隐藏和显示 导航条，即调用了         
[self.navigationController setNavigationBarHidden:YES animated:YES];
导致nav上面有白色的NavigationBarTransitionView。
建议针对调用[self.navigationController setNavigationBarHidden:YES animated:YES];
时，对NavigationBarTransitionView进行优化

**Comment by MoLice** [comment]
issue 表述信息不完整，例如是在哪个 viewController 调用 `setNavigationBarHidden:`，是在什么时机调用，这些都对你描述的场景有所影响。如果从我们自己的业务代码来看，我们暂未发现这两个搭配使用有什么问题。

建议补充示例代码，最好能提供一个干净的能出现问题的 Demo 项目。

**Comment by dream5788** [comment]
到底怎么隐藏导航栏啊，标准的怎么写。

**Comment by dream5788** [comment]
我现在也是这样
-(void)viewDidLoad
{
    [super viewDidLoad];
    [self.navigationController setNavigationBarHidden:YES animated:YES];
}
没有隐藏 还回闪一下白色东西

**Comment by ziecho** [comment]
@dream5788  QMUI 会在控制器的 `- (void)viewWillAppear:(BOOL)animated` 这个时机插入代码，去配置导航栏的隐藏，你在 viewDidLoad 隐藏后会被 QMUI 的方法覆盖，建议直接用 QMUI 的方法：

```objc
- (BOOL)preferredNavigationBarHidden {
    return YES;
}
```
或者在将 `[self.navigationController setNavigationBarHidden:YES animated:YES];` 挪到 `viewWillAppear:animated` 里
