### ISSUE TITLE
命令编译失败

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#533]
通过控制台执行：
pod repo push 【仓库】 QMUIKit.podspec --allow-warnings
报错：
- ERROR | [QMUIKit/QMUIComponents,QMUIKit/QMUIComponents/QMUICellHeightCache] xcodebuild:  QMUIKit/QMUIKit/QMUIComponents/QMUICellHeightCache.m:326:82: error: use of undeclared identifier 'akey'
调查：
但是发现QMUICellHeightCache.m对应的326行，并没有使用akey变量，而且325行中的参数aKey的“k”是大写。请问怎么解决呢？
- (void)qmuiTableCache_deleteRowsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation {
    if (self.qmui_invalidateIndexPathHeightCachedAutomatically) {
        [self.qmuiTableCache_allIndexPathHeightCaches enumerateKeysAndObjectsUsingBlock:^(NSNumber * _Nonnull key, QMUICellHeightIndexPathCache * _Nonnull obj, BOOL * _Nonnull stop) {
            [obj buildCachesAtIndexPathsIfNeeded:indexPaths];
            NSMutableDictionary<NSNumber *, NSMutableIndexSet *> *mutableIndexSetsToRemove = [NSMutableDictionary dictionary];
            [indexPaths enumerateObjectsUsingBlock:^(NSIndexPath *indexPath, NSUInteger idx, BOOL *stop) {
                NSMutableIndexSet *mutableIndexSet = mutableIndexSetsToRemove[@(indexPath.section)];
                if (!mutableIndexSet) {
                    mutableIndexSet = [NSMutableIndexSet indexSet];
                    mutableIndexSetsToRemove[@(indexPath.section)] = mutableIndexSet;
                }
                [mutableIndexSet addIndex:indexPath.row];
            }];
            [mutableIndexSetsToRemove enumerateKeysAndObjectsUsingBlock:^(NSNumber *aKey, NSIndexSet *indexSet, BOOL *stop) {
                NSMutableArray<NSNumber *> *heightsInSection = obj.cachedHeights[key.integerValue]; // 第326行
                [heightsInSection removeObjectsAtIndexes:indexSet];
            }];
        }];
    }
    [self qmuiTableCache_deleteRowsAtIndexPaths:indexPaths withRowAnimation:animation];
}

**Comment by MoLice** [comment]
是 https://github.com/Tencent/QMUI_iOS/pull/514/commits/b5f989e99a34ec1d8f4a7475708ad15250c1e28e 这一次 pr 里拼写错误，尚未发版本，已经在 GitHub 的代码里改过来了。
