### ISSUE TITLE
QMUISearchController的searchBar遮挡了结果页面

### ISSUE THREAD

**Issue by hbjsgl** [Tencent/QMUI_iOS#534]
### 请填写运行环境

- [x] 设备：iPhoneSE
- [x] 系统：`iOS 12.1.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题
控制器继承于QMUICommonTableViewController，searchBar添加在一个view上，view添加在self.view上，view的需要设置y，控制器视图没有进行偏移。

#### 相关截图（断点的堆栈、控制台的 log）
![9D322CC0-844A-421C-BC48-18329DE8657C](https://user-images.githubusercontent.com/10862057/54930200-d0784900-4f51-11e9-8d52-6d0b91cbcf56.png)
![IMG_2346](https://user-images.githubusercontent.com/10862057/54930329-0e756d00-4f52-11e9-907f-36eb9e88810e.PNG)

**Comment by MoLice** [comment]
按照你的代码，并没有出现问题，以下是代码截图，录屏文件请[点击下载](https://github.com/Tencent/QMUI_iOS/files/3047211/searchBar.mov.zip)。

![image](https://user-images.githubusercontent.com/1190261/55617469-be56a000-57c6-11e9-869f-6c2feacc9a7e.png)

**Comment by MoLice** [comment]
该 issue 由于不活跃而被关闭
