### ISSUE TITLE
Returning block that lives on the local stack

### ISSUE THREAD

**Issue by lengain** [Tencent/QMUI_iOS#535]
### 运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.1.4`
- [x] Xcode 版本：`Version 10.2 (10E125)`
- [x] QMUI iOS 版本：`2.9.1`

### 请描述具体问题
我看，QMUI iOS 3点以后的版本，代码没有变。
今天升级到Xcode 10.2 (10E125)
然后就报错了。报错的文件是QMUIRuntime.h中，ExtendImplementationOfVoidMethodWithoutArguments方法。
报：Returning block that lives on the local stack
详细请看截图。
#### 相关截图（断点的堆栈、控制台的 log）
<img width="340" alt="屏幕快照 2019-03-26 上午9 57 57" src="https://user-images.githubusercontent.com/9276826/54965996-d13ec880-4fad-11e9-8dcf-32e43b5b1043.png">
<img width="933" alt="屏幕快照 2019-03-26 上午9 59 58" src="https://user-images.githubusercontent.com/9276826/54966060-0814de80-4fae-11e9-95f7-ef8a9e31dc1c.png">

**Comment by lengain** [comment]
mac os 10.14.3 (18D109)

**Comment by yongshideweiyi** [comment]
同上，刚跟新的热乎的xcode   Version 10.2 (10E125)

**Comment by yongshideweiyi** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/22723439/54968885-31863800-4fb7-11e9-875d-7c38d53378d8.png">

这个地方貌似需要把return的block copy一下

**Comment by YuanJiaShuai** [comment]
同样的问题，刚更新的Xcode 就报错了

**Comment by ParadiseGitHub** [comment]
资料解释：对于引用了外部变量的Block，如果没有对他进行copy，他的作用域只会在声明他的函数栈内（类型是__NSStackBlock__），如果想在非ARC下直接返回此类Block，Xcode会提示编译错误的，不知道是否准确，但是copy之后已经可以编译通过了

**Comment by lengain** [comment]
主要是它这个QMUI SDK什么时候更新一下~

**Comment by TheLittleBoy** [comment]
@lengain QMUIKit  3.1.2  版本并没有报错，建议升级到最新版本。  刚更新的Xcode 10.2 (10E125)。

**Comment by lengain** [comment]
> @lengain QMUIKit 3.1.2 版本并没有报错，建议升级到最新版本。 刚更新的Xcode 10.2 (10E125)。

好的。

**Comment by MoLice** [comment]
经空白项目测试，触发的条件可能是项目中存在 MRC/ARC 混编的文件，但不确定这是否是唯一可能的条件，也不确定本质原因是什么，但可以确定的是这属于 Xcode 的问题，错误地将 `QMUIRuntime.h` 以 MRC 的方式去编译，所以在 return 时没有自动为 block 添加 copy 操作。

这两天会寻找一个合适的方式规避这个问题。

在此之前也可以采用 @yongshideweiyi 的方式，显式添加 copy 操作，这在 ARC 环境下也没有问题。

**Comment by yongshideweiyi** [comment]
> > @lengain QMUIKit 3.1.2 版本并没有报错，建议升级到最新版本。 刚更新的Xcode 10.2 (10E125)。
> 
> 好的。

3.1.2的QMUIKit不支持8.0的系统了

**Comment by MoLice** [comment]
[3.1.3](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.3) 已修复
