### ISSUE TITLE
有些cell select不了

### ISSUE THREAD

**Issue by passerbyloo** [Tencent/QMUI_iOS#537]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题
使用官方demo, https://github.com/QMUI/QMUIDemo_iOS
随便点击进入一个tableview vc，然后back回到主页面，再点击进入一个tableview vc，有些cell select不了， didSelectCellWithTitle没执行（如果都可以select, 再重复几次就能复现）。

**Comment by yuhanle** [comment]
我最近在 collectionView 遇到同样的问题，不过是概率的，调试过程中没发现。看描述和这个情况类似

 - 设备：All / iPhone / iPad / 模拟器
 - 系统：iOS 12.1
 - Xcode 版本：10.1
 - QMUI iOS 版本：2.9.0

**Comment by MoLice** [comment]
使用 3.1.2 的 Demo 测试并没有发现该问题，建议提供录屏以便查看具体的操作方式。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭，请补充细节时再 reopen。
