### ISSUE TITLE
如何屏蔽控制台打印信息

### ISSUE THREAD

**Issue by yongshideweiyi** [Tencent/QMUI_iOS#538]
如下：
2019-03-26 16:52:30.411350+0800 YJXS[5127:1747312] -[QMUINavigationController popViewControllerAnimated:]:203 | QMUILogLevelDefault | NavigationItem | call popViewControllerAnimated:YES, current viewControllers = (
    "<UXinLoginViewController: 0x121e117a0>\nsuperclass:\t\t\t\tUIViewControllerExt\ntitle:\t\t\t\t\t(null)\nview:\t\t\t\t\t<UIView: 0x121e24d00; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x280e0a000>>",
    "<SelectAreaViewController: 0x121ee3330>\nsuperclass:\t\t\t\tUIViewControllerExt\ntitle:\t\t\t\t\t\U9009\U62e9\U533a\U57df\nview:\t\t\t\t\t<UIView: 0x121ee2bf0; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x28097c020>>",
    "<UXinWebViewController: 0x123b8d270>\nsuperclass:\t\t\t\tUXinWebFuncViewController\ntitle:\t\t\t\t\t(null)\nview:\t\t\t\t\t<UIView: 0x123b7c240; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x2809a02a0>>"
)

**Comment by MoLice** [comment]
触发这些 log 打印的代码在 [QMUILogger.m:58](https://github.com/Tencent/QMUI_iOS/blob/master/QMUIKit/QMUIComponents/QMUILog/QMUILogger.m#L58)，看代码即可得知，只需要将 `QMUILogger.sharedInstance.delegate` 指向某个实现了 `QMUILoggerDelegate` 协议的对象，在该对象内实现方法 `printQMUILogWithFile:line:func:logItem:defaultString:`，即可去掉默认的 `NSLog()` 输出行为，并且可由业务自行决定每个 log 要如何处理。
