### ISSUE TITLE
请教pod应该怎么写

### ISSUE THREAD

**Issue by anwent** [Tencent/QMUI_iOS#540]
因为之前用到`QMUIModalPresentationViewController`模块，所以自己fork后一直在使用，最近有新的需求我需要使用`QMUIPopupMenuView`模块，但是pod加入后报错，请指点一下pod该怎么写~
这是我的Podfile文件：
```
 pod 'QMUIKit/QMUIComponents/QMUIModalPresentationViewController', :git => 'https://github.com/anwent/QMUI_iOS.git'
  pod 'QMUIKit/QMUIComponents/QMUIPopupMenuView'
```
报错如下：
Analyzing dependencies
[!] There are multiple dependencies with different sources for `QMUIKit` in `Podfile`:

- QMUIKit/QMUIComponents/QMUIModalPresentationViewController (from `https://github.com/anwent/QMUI_iOS.git`)
- QMUIKit/QMUIComponents/QMUIPopupMenuView

**Comment by MoLice** [comment]
```ruby
pod 'QMUIKit/QMUIComponents/QMUIModalPresentationViewController', :git => 'https://github.com/anwent/QMUI_iOS.git'
pod 'QMUIKit/QMUIComponents/QMUIPopupMenuView', :git => 'https://github.com/anwent/QMUI_iOS.git'
```
