### ISSUE TITLE
QMUISearchController的UISearchBar 无法设置搜索icon和placeholder文字间距

### ISSUE THREAD

**Issue by zzqzhp** [Tencent/QMUI_iOS#541]
### 请填写运行环境

- [x] 设备：`All` / `iPhone `  / `模拟器`
- [x] 系统：`iOS 11.6`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.3`

### 请描述具体问题
在QMUIConfigurationTemplate配置文件中配置UISearchBar相关属性searchBarSearchIconImage、searchBarTextFieldBackground、searchBarPlaceholderColor后搜索icon图和placeholder文字及搜索文字UI显示上无间距。
#### 相关截图（断点的堆栈、控制台的 log）

![WechatIMG15](https://user-images.githubusercontent.com/18587026/55142930-ace31780-5178-11e9-95fa-60a6ec130e42.jpeg)

<img width="826" alt="WeChat102c34ff0260749a4670f3b2f8b18ba2" src="https://user-images.githubusercontent.com/18587026/55142502-c0da4980-5177-11e9-8313-741826592e52.png">

**Comment by MoLice** [comment]
无法重现，请提供完整代码。
![image](https://user-images.githubusercontent.com/1190261/55388624-2fe3e380-5566-11e9-9b36-4b2dfbb967ae.png)
