### ISSUE TITLE
能不能实现中间凸起TabBar

### ISSUE THREAD

**Issue by dream5788** [Tencent/QMUI_iOS#542]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

### 请描述具体问题
感谢。

**Comment by MoLice** [comment]
不具通用性的需求，请自行实现。
