### ISSUE TITLE
UIImage的扩展方法qmui_grayImage返回了原图部分区域的灰度图

### ISSUE THREAD

**Issue by ZhangTonghai** [Tencent/QMUI_iOS#543]
### 请填写运行环境

- [x] 设备：`iPhone` `模拟器`
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题
UIImage的扩展方法- (UIImage *)qmui_grayImage；返回了原图部分区域的灰度图。
在处理‘不透明’图片的时候，size前后不一致导致了

#### 相关截图（断点的堆栈、控制台的 log）
原图是这样，灰度图实际是红框部分
<img width="1394" alt="QQ20190329-143939@2x" src="https://user-images.githubusercontent.com/6335614/55214092-95676580-5230-11e9-971a-1323ff2ae1ec.png">
灰度图截图了原图的一部分
<img width="1388" alt="QQ20190329-144003@2x" src="https://user-images.githubusercontent.com/6335614/55214095-97c9bf80-5230-11e9-890d-2b65b29a4bcf.png">

**Comment by MoLice** [comment]
用 UIImage 测试并没有发现该问题，可能与 YYImage 有关。建议提供一份可重现的 Demo 项目，或者完整的代码。

**Comment by ZhangTonghai** [comment]
> 用 UIImage 测试并没有发现该问题，可能与 YYImage 有关。建议提供一份可重现的 Demo 项目，或者完整的代码。

嗯 我用UIImage测试下，的确没有复现，这个问题我也暂时用其他方式解决了，谢谢。

**Comment by MoLice** [comment]
好的
