### ISSUE TITLE
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

### ISSUE THREAD

**Issue by yongshideweiyi** [Tencent/QMUI_iOS#544]
### 请填写运行环境

- [x] 设备：`iPhone` / `模拟器`
- [x] 系统：`iOS 12.0`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`2.9.3`

### 请描述具体问题
在入口累AppDelegate中创建window，代码如下
<img width="789" alt="image" src="https://user-images.githubusercontent.com/22723439/55217642-f72ccd00-523a-11e9-953b-d1b373d0c445.png">
运行程序，直接崩溃
代码在此处无限循环
#### 相关截图（断点的堆栈、控制台的 log）
<img width="415" alt="image" src="https://user-images.githubusercontent.com/22723439/55217530-b5038b80-523a-11e9-93d0-67cd6f287426.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/22723439/55217551-c187e400-523a-11e9-89c9-3be27086c343.png">
<img width="408" alt="image" src="https://user-images.githubusercontent.com/22723439/55217582-d1072d00-523a-11e9-8bd3-8586f5926b89.png">

**Comment by yongshideweiyi** [comment]
代码在创建window的地方无限循环

**Comment by MoLice** [comment]
参考 https://github.com/Tencent/QMUI_iOS/issues/471#issuecomment-451647019，请更新 QMUI 到 3.1.0 及以上的版本。
