### ISSUE TITLE
能否适配Xcode10.2的编译检查

### ISSUE THREAD

**Issue by yingkong1987** [Tencent/QMUI_iOS#545]
### 请填写运行环境

- [x] 设备：`All`
- [x] 系统：`All `
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.x.x`

### 请描述具体问题
Xcode10.2下的拼写检查导致很多Error.  望完善返回值nullable的生命,来解决error

#### 相关截图（断点的堆栈、控制台的 log）
<img width="2556" alt="image" src="https://user-images.githubusercontent.com/2038099/55289475-d494e280-53f9-11e9-9ee6-4589121dfd61.png">

**Comment by MoLice** [comment]
3.1.3 已屏蔽所有 nullable 的检测。

**Comment by JohnYuGit** [comment]
oc xcode10.2 输入和定义还是存在检查的 warnings 能优化吗

**Comment by MoLice** [comment]
@JohnYuGit 可以，这个我们会陆续补，文件有点多，当初写的时候还没有 nullable 这种特性，哈哈哈

**Comment by MoLice** [comment]
3.1.4 已取消 warning 的屏蔽，同时补上所有的 nullable/nonnull 标志，如发现有遗漏的麻烦提出。
