### ISSUE TITLE
QMUIAlertViewController 点击菜单项后希望可以立刻回调action block，不等actionsheet收起

### ISSUE THREAD

**Issue by horsley** [Tencent/QMUI_iOS#546]
https://github.com/Tencent/QMUI_iOS/blob/0a5294bfa08a22dcd38cebc712b11904d3a33c64/QMUIKit/QMUIComponents/QMUIAlertController.m#L1172

**Comment by MoLice** [comment]
可以使用 `willHideAlertController:`

**Comment by horsley** [comment]
请问如果使用willHideAlertController，如何获知点击的是哪个菜单项呢？

**Comment by MoLice** [comment]
这个需求目前确实没有标准的实现方式，可以尝试自行为 action.button 添加事件，在 action 里做想要的事情。

```Objective-C
QMUIAlertAction *action = xxx;
[aciton.button addTarget:xxx action:xxx forControlEvents:UIControlEventTouchUpInside];
```
