### ISSUE TITLE
类之间耦合性太强了，拎一个UI类出来，带出来好几个其他类

### ISSUE THREAD

**Issue by dgyiOS** [Tencent/QMUI_iOS#547]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

**Comment by MoLice** [comment]
请细化问题的描述，例如你指的是哪个类？

**Comment by MoLice** [comment]
无详细信息补充，该 issue 被关闭
