### ISSUE TITLE
QDKeyboardViewController 页面发现bug

### ISSUE THREAD

**Issue by dgyiOS** [Tencent/QMUI_iOS#548]
### 请填写运行环境

- [x] 设备：iPhone8Plus
- [x] 系统：iOS 12.2
- [x] Xcode 版本：10.2
- [x] QMUI iOS 版本：3.1.3

在QDKeyboardViewController页，点击发表想法，弹出键盘后，退到后台，马上切回到前台，边缘平滑返回上个页面，突然中断手势再回到QDKeyboardViewController页，会黑屏，测试了几次，偶发性

**Comment by dgyiOS** [comment]
![IMG_7472](https://user-images.githubusercontent.com/37854650/55452859-02ea0c00-560c-11e9-8798-d43c4a21683b.PNG)

**Comment by MoLice** [comment]
无法重现，建议提供录屏

**Comment by dgyiOS** [comment]
复现了，下面链接带有过程

https://weibo.com/tv/v/Ho2Fu0IfH?fid=1034:4357301021431948

**Comment by ziecho** [comment]
这个问题的最小可复现步骤为：
QDKeyboardViewController 点击 「发表想法」然后在键盘弹起后点击「关闭」，此时马上去触发 pop 手势

原因分析：
Demo 中在点击「发表想法」时，会调用下面这个方法
`[self.customViewController showInParentViewController:self.navigationController];`
把 customViewController 当做 navigationController 的 childVc 添加到 navigationController.view 上，同时在 customViewController 的 `viewWillAppear:` 时禁用侧滑手势，在 viewWillDisappear 重新开启手势。
出现这个黑屏的原因是，因为 触发 `viewWillDisappear` 比 `removeFromParentViewController` 时机早，导致手势过早被开启，从而在这个过程中可以触发 pop 手势，而由于 UINavigationController 把最后添加的 childVc  错误地当成 topViewController 出现了转场动画错误。

参考修复方式：

1、直接添把当前 viewController 当做 ParentViewController 
```objc
[self.customViewController showInParentViewController:self];
```

2、把 `self.navigationController.interactivePopGestureRecognizer.enabled = NO;` 这句代码挪到下面的方法中

```objc
- (void)removeFromParentViewController {
    
    self.navigationController.interactivePopGestureRecognizer.enabled = YES;
    
    [super removeFromParentViewController];
}
```

**Comment by MoLice** [comment]
@ziecho 优秀
