### ISSUE TITLE
手势返回过程中 self.qmui_navigationBarMaxYInViewCoordinator 为 0 导致布局跳动

### ISSUE THREAD

**Issue by tryEvething** [Tencent/QMUI_iOS#549]
### 请填写运行环境

- [x] 设备：`iPhone8Plus ` / `模拟器`
- [x] 系统：`iOS 12.1.2(真机) iOS 12.1(模拟器)`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.3`

### 请描述具体问题
在QDTextViewController页，粘贴超过100字的文字,然后手势滑动返回,页面会向上移动
#### 相关截图（断点的堆栈、控制台的 log）
![](https://user-images.githubusercontent.com/18730979/55468097-3d1bd380-5635-11e9-9ab4-bd424b62868c.gif)

**Comment by MoLice** [comment]
这是手势返回的过程中，QMUITips 刚好消失了，而 QMUITips 的消失会触发当前 viewController 的 `viewDidLayoutSubviews`，整个界面的 y 是根据 `self.qmui_navigationBarMaxYInViewCoordinator` 算出来的。而在手势返回的过程中，`self.navigationController` 为空，导致顶部的 y 算出来少了一个导航栏的高度，从而看到界面往上跳动。本质原因还是“手势返回过程中 self.qmui_navigationBarMaxYInViewCoordinator 不准确”导致的，我们看看如何修复。

**Comment by MoLice** [comment]
相关 issue #268 ，下个版本会完整修复这个 bug。

**Comment by MoLice** [comment]
3.1.4 已修复该问题。
