### ISSUE TITLE
通过什么方法可以调整导航栏的返回箭头的leftPadding呢？

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#550]
通过什么方法可以调整导航栏的返回箭头的leftPadding呢？

**Comment by tospery** [comment]
有navBarBackButtonTitlePositionAdjustment这个属性可以调整“返回”文本的位置，但是没有“<”的位置调整方式

**Comment by tospery** [comment]
希望有一个调整“<”的位置和样式（粗细）的设置方式

**Comment by MoLice** [comment]
这些都可以通过修改图片来实现，例如你自己弄一张左边留着空白的 < 图，粗细也是由你图片自行决定即可，QMUI 默认也能用代码绘制一些图片，你可以参考以下代码：
```Objective-C
// 用 1px 的线宽绘制一个返回按钮的图片，然后在左边拓展出 4pt 的空白
UIImage *backIndicatorImage = [[UIImage qmui_imageWithShape:QMUIImageShapeNavBack size:CGSizeMake(12, 20) lineWidth:PixelOne tintColor:NavBarTintColor] qmui_imageWithSpacingExtensionInsets:UIEdgeInsetsMake(0, 4, 0, 0)];

// 在配置表 QMUIConfigurationTemplate.m 里将全局返回按钮图片设置为生成的图片
QMUICMI.navBarBackIndicatorImage = backIndicatorImage;
```

**Comment by tospery** [comment]
非常感谢

**Comment by yunyuchen** [comment]
// 用 1px 的线宽绘制一个返回按钮的图片，然后在左边拓展出 4pt 的空白
UIImage *backIndicatorImage = [[UIImage qmui_imageWithShape:QMUIImageShapeNavBack size:CGSizeMake(12, 20) lineWidth:PixelOne tintColor:NavBarTintColor] qmui_imageWithSpacingExtensionInsets:UIEdgeInsetsMake(0, 4, 0, 0)];

// 在配置表 QMUIConfigurationTemplate.m 里将全局返回按钮图片设置为生成的图片
QMUICMI.navBarBackIndicatorImage = backIndicatorImage;

--------------------------------
使用这个方法之后这个图片会变小，有可以不让图片变小的方法吗

**Comment by iOkay** [comment]
Setting the `sizeNavBarBackIndicatorImageAutomatically` to NO may be useful.
