### ISSUE TITLE
Add Nullability for all classes and methods

### ISSUE THREAD

**Issue by caoer** [Tencent/QMUI_iOS#551]
### 请填写运行环境

- [x] 设备：`All`
- [x] 系统：`iOS 12`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.3`

### 请描述具体问题

As a modern framework, we should have nullability annotation for better swift integration. 

I have to disable the compiler warnings for QMUI project in Cocoapods, and doing such make the confident level lower than it should. 

Much appreciate the project and strongly suggest we remove `-Wno-nullability-completeness` flag, Any plan towards it?

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/225856/55677796-e4905300-5920-11e9-9598-6e49c5ae3764.png)

**Comment by monomichael** [comment]
Thanks for the suggestion. We've added nullability annotations and removed the flag in https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.4

**Comment by caoer** [comment]
that was quick! Thanks a lot.
