### ISSUE TITLE
关于设置navBarTintColor属性

### ISSUE THREAD

**Issue by YSYou1234** [Tencent/QMUI_iOS#552]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

### 请描述具体问题
请问一下，为什么在导航栏配置里navBarTintColor没有设置appearance全局的属性，而其他相关的导航栏属性却设置了appearance全局的属性呢？。

#### 相关截图（断点的堆栈、控制台的 log）
<img width="977" alt="image" src="https://user-images.githubusercontent.com/17350370/55777783-92dbfa00-5ad3-11e9-8641-ef107b765fc9.png">

**Comment by ziecho** [comment]
UINavigationBar 的 tintColor 并不支持 UIAppearance 协议，你可以打开 UINavigationBar.h 和 barTintColor 属性对比下（少了 `UI_APPEARANCE_SELECTOR`）

```objc
@property(null_resettable, nonatomic,strong) UIColor *tintColor;
@property(nullable, nonatomic,strong) UIColor *barTintColor NS_AVAILABLE_IOS(7_0) UI_APPEARANCE_SELECTOR;  // default is nil
```

**Comment by YSYou1234** [comment]
> UINavigationBar 的 tintColor 并不支持 UIAppearance 协议，你可以打开 UINavigationBar.h 和 barTintColor 属性对比下（少了 `UI_APPEARANCE_SELECTOR`）
> 
> ```objc
> @property(null_resettable, nonatomic,strong) UIColor *tintColor;
> @property(nullable, nonatomic,strong) UIColor *barTintColor NS_AVAILABLE_IOS(7_0) UI_APPEARANCE_SELECTOR;  // default is nil
> ```
嗯，谢谢，明白了，但是奇怪的是我这边使用的[UINavigationBar appearance].tintColor来设置实际是有用的。并且如果不设置的话，appearance属性的不同会导致在唤起系统的页面如相册，分享页面时，导航栏风格就会不一致。。

**Comment by ziecho** [comment]
实测确实能够生效，这里跟 UIAppearance 的实现机制有关系，无论有没有标记 UI_APPEARANCE_SELECTOR， 只要对 UIAppearance 的实例对象调用一个方法，内部就会把这个方法以 NSInvocation 存起来，在新对象初始化的时候，把存储的 NSInvocation 逐一调用以设置外观效果。
对 tintColor 这里为什么没有标记 UI_APPEARANCE_SELECTOR，原因不明。

**Comment by MoLice** [comment]
以系统头文件的标记为准，如仍需以 UIAppearance 协议的方式去使用 UINavigationBar.tintColor，建议在业务自行处理。
