### ISSUE TITLE
http://qmuiteam.com/ios 网站上不去

### ISSUE THREAD

**Issue by JanssenZ** [Tencent/QMUI_iOS#556]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

**Comment by kayo5994** [comment]
你好，官网可以正常访问的，请使用 https 再试一次。
