### ISSUE TITLE
QMUITextView 在某些特殊宽度下右侧出现多余的线

### ISSUE THREAD

**Issue by ziecho** [Tencent/QMUI_iOS#557]
### 请填写运行环境

- [x] 设备：`All`
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.4`

### 请描述具体问题

在 QMUI Demo 的 `QDTextViewController.m` 中修改 textView 的 frame 给他指定一个有小数点的宽度，比如 200.9

```objc
- (void)viewDidLayoutSubviews {
    ...
    self.textView.frame = CGRectMake(padding.left, padding.top, 200.9, fmax(textViewSize.height, self.textViewMinimumHeight));
    ...
}
```

为了方便观察现象，注释掉边框设置代码

```objc
- (void)initSubviews {
      ...
//    self.textView.layer.borderWidth = PixelOne;
//    self.textView.layer.borderColor = UIColorSeparator.CGColor;
//    self.textView.layer.cornerRadius = 4;
      ...
}
```

#### 相关截图（断点的堆栈、控制台的 log）

![image](https://user-images.githubusercontent.com/16473618/55846565-b7d67880-5b78-11e9-9fdb-0623449594a2.png)

**Comment by ziecho** [comment]
系统的 `UITextView` 没有该问题，而 `QMUITextView` 继承了 `UITextView` 说明某些地方触发了这个问题，进一步调试发现，只要继承自 `UITextView` 并且重写了 `- drawRect:` 方法就会出现这个问题（就算 drawRect: 里什么都不干）

具体原因暂时不明，猜测是系统某些判断机制导致。

目前简单的修复方法可以对设置 frame 的宽度向上取整来解决这个问题

```objc
- (void)setFrame:(CGRect)frame {
    [super setFrame:CGRectFlatted(frame)];
}

- (void)setBounds:(CGRect)bounds {
    [super setBounds:CGRectFlatted(bounds)];
}
```

**Comment by MoLice** [comment]
暂不清楚原因，先按 @ziecho 的方式临时修复，已带上 3.1.5 里。
