### ISSUE TITLE
QMUICommonTableViewController 在 viewWillAppear 的时候自动清除列表选中态

### ISSUE THREAD

**Issue by wxlpp** [Tencent/QMUI_iOS#558]
### 请填写运行环境
设备版本无关
### 请描述具体问题
QMUICommonTableViewController 在 viewWillAppear 的时候自动清除列表选中态，且不可控。导致编辑行多选列表在侧滑后丢失选中态。并且有默认选中态的列表也要在viewWillAppear中特殊处理。
`- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self.tableView qmui_clearsSelection];
}`

**Comment by MoLice** [comment]
经测试，系统的 UITableViewController 当 `self.tableView.allowsMultipleSelection = YES;` 时，在 `viewWillAppear:` 里不会清除选中状态，而当 `allowsMultipleSelection = NO` 时，会与 QMUI 一样清除选中状态，所以这里下个版本会加上 `allowsMultipleSelection` 值的判断，在此之前你可以参照以下代码先临时修改：
```Objective-C
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    if (!self.tableView.allowsMultipleSelection) {
        [self.tableView qmui_clearsSelection];
    }
}
```

**Comment by MoLice** [comment]
已发布 3.1.5 修复该问题。
