### ISSUE TITLE
QMUIImagePreviewViewController

### ISSUE THREAD

**Issue by liuzhaozhen** [Tencent/QMUI_iOS#561]
### 请填写运行环境

- [x] 设备：`iPhone` 
- [x] 系统：`iOS 11.4.1.`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.0.0`

### 请描述具体问题
1.想在预览的图片上添加label，结果很小；
2.发现尽管视觉上没有zoom过,  结果scrollview反直觉的zoom过；
3.经过比例换算后，第一张正常了，但是第二张还是小，复用又变大了。
4.这个很好测试，预览5张图片，上面添加一个label（能跟随放大），这样就知道实现起来多么困难了！

**Comment by liuzhaozhen** [comment]
QMUIImagePreviewViewController

**Comment by MoLice** [comment]
使用 QMUI Demo 测试并没有问题，如果添加的 view 需要跟随缩放，请添加到 contentView 上（也即在 QMUIZoomImageView.m 里 `viewForZoomingInScrollView:` 返回的 view）。附上示例代码和屏幕录制视频以供参考。

![image](https://user-images.githubusercontent.com/1190261/56349761-cf0e0980-61fb-11e9-9c3e-2dfe04264db5.png)

[imagePreviewView.mov.zip](https://github.com/Tencent/QMUI_iOS/files/3093574/imagePreviewView.mov.zip)

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭
