### ISSUE TITLE
UILabel  setAttributedText 的性能问题

### ISSUE THREAD

**Issue by lexiaoyao20** [Tencent/QMUI_iOS#562]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

### 请描述具体问题

我代码里面有个地方会频繁调用 `UILabel` 的  `setAttributedText:` 方法，但是你们的 hook 了 `setAttributedText:` 这个方法，  而且会重新生成一个 `NSMutableAttributedString` ，并进行 mutableCopy 操作，以及循环添加 属性，这里会有很大的性能消耗。

不知道，你们有没有什么优化的方案呢？  
而且，你们hook这个方法，只是为了添加你们的新样式，但是很多地方是用不到你们的新样式的，这样全局随意的hook感觉还是有很大问题...

#### 相关截图（断点的堆栈、控制台的 log）

性能问题截图：
![性能问题](https://user-images.githubusercontent.com/3021017/56008771-e89ce600-5d0f-11e9-9f98-54e51275d835.png)

QMUIKit代码截图：
![代码截图](https://user-images.githubusercontent.com/3021017/56008746-ce630800-5d0f-11e9-8eda-66a4ad6cca2e.png)

**Comment by MoLice** [comment]
近期的版本会修复这个问题，在此之前你可以先按照截图的代码去修改

![image](https://user-images.githubusercontent.com/1190261/56020992-f320a500-5d3a-11e9-9462-6d3cfb5c05b5.png)

**Comment by lexiaoyao20** [comment]
OK，辛苦大佬了，我先本地改一下~

**Comment by MoLice** [comment]
已发布 3.1.5 修复该问题。
