### ISSUE TITLE
QMUIImagePickerPreviewViewController在Swift4.2中，选中不了图片

### ISSUE THREAD

**Issue by hkjin** [Tencent/QMUI_iOS#564]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.4`

### 请描述具体问题
QMUIImagePickerPreviewViewController 中 updateImagePickerPreviewView方法，在Swift4.2中，selectedImageAssetArray传递不了NSMutableArray，导致在预览时，选中不了照片 ，add不用了元素到数组中...

**Comment by ziecho** [comment]
你好，这是我的答案



class ListNode:
    def __init__(self, x):
        self.val = x
        self.next = None

class Solution1:
    def addTwoListNode(self, l1 : ListNode, l2 : ListNode):
        if not l1 and not l2:
            return
        elif not (l1 and l2):
            return l1 or l2
        else:
            if l1.val + l2.val < 10:
                l3 : ListNode = ListNode(l1.val + l2.val)
                l3.next = self.addTwoListNode(l1.next, l2.next)
            else:
                l3 : ListNode = ListNode(l1.val + l2.val - 10)
                l3.next = self.addTwoListNode(l1.next,
self.addTwoListNode(l2.next, ListNode(1)))
            return l3



a1 = ListNode(3)
a2 = ListNode(2)
a3 = ListNode(9)

a1.next = a2
a2.next = a3


b1 = ListNode(8)
b2 = ListNode(7)
b1.next = b2
# b2.next = b3
#
def printNode(node: ListNode):
    while (node):
        print(node.val)
        node = node.next


printNode(Solution1().addTwoListNode(a1, b1))

class Solution2:


    def helper(self, matrix, rows, cols, row, col,string, index, visited):
        if len(string) == index:
            return True
        hasPath = False
        s1 = row >= 0 and row < rows and col >=0 and col < cols
        if not s1: return False
        s2 = matrix[row][col] == string[index]
        if not s2: return False
        if not visited[row][col]:
            index += 1
            visited[row][col] = True
            left = self.helper(matrix,rows,cols,row,col-1,string,index,visited)
            up = self.helper(matrix,rows,cols,row - 1,col,string,index,visited)
            right = self.helper(matrix,rows,cols,row,col +
1,string,index,visited)
            down = self.helper(matrix,rows,cols,row+1,col,string,index,visited)
            hasPath = left or up or right or down
            if not hasPath:
                index -= 1
                visited[row][col] = False
        return hasPath

    def stringExist(self, matrix, string):
        rows = len(matrix)
        cols = len(matrix[0])
        if matrix == None or len(string) == 0 or rows == 0 or cols == 0:
            return False
        visited = [[0] * cols for i in range(rows)]
        for row in range(rows):
            for col in range(cols):
                if self.helper(matrix,rows,cols, row,col,string, 0, visited):
                    return True
        return False


m = [['Y','P','W','F'],
     ['A','T','A','O'],
     ['G','E','D','T'],
     ['H','O','L','D']]

r1 = Solution2().stringExist(m, 'YPWF')
r2= Solution2().stringExist(m, 'FOLD')
print('r1 =', str(r1))
print('r2 =', str(r2))


Kegem <notifications@github.com> 于2019年4月15日周一 下午8:07写道：

**Comment by MoLice** [comment]
下个版本会修复该问题，在此之前建议先手动将头文件里的参数类型声明从 NSArray 改为 NSMutableArray。

**Comment by MoLice** [comment]
已发布 3.1.5 修复该问题。
