### ISSUE TITLE
QMUIKeyboardManager 从APP后台回到前台后，快速触发 [TextView becomeFirstResponder] 时，无法监听到键盘升起

### ISSUE THREAD

**Issue by chen570075003** [Tencent/QMUI_iOS#565]
### 请填写运行环境

- [x] 设备：`All` 
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.4`

### 请描述具体问题
从APP后台回到前台后，快速触发 [TextView becomeFirstResponder] 时，无法监听到键盘升起
#### 相关截图（断点的堆栈、控制台的 log）
![KeyboardError](https://user-images.githubusercontent.com/8541399/56277440-efc05b80-6136-11e9-9693-ab5c7dede2fd.gif)

**Comment by passerbyloo** [comment]
`isAppActive` function will return `NO` for this case, so can not observer the notification.

Because `[[UIApplication sharedApplication] applicationState]`  will return `UIApplicationStateInactive`

**Comment by bluerainxty** [comment]
我也观察到同样的问题了 @MoLice

**Comment by zhoon** [comment]
系统在刚刚返回的时候一小段时间内 [[UIApplication sharedApplication] applicationState] 的状态还没有更新过来，这个时候会导致 QMUI 里面的这个 state 判断错误。

新版本 QMUIKeyboardManager 会增加一个 ignoreApplicationState 来给业务关掉这个过滤的特性。

**Comment by MoLice** [comment]
4.0.0-beta 里已修复。
