### ISSUE TITLE
QMUIModalPresentationViewController遮罩层消失问题

### ISSUE THREAD

**Issue by godYyj** [Tencent/QMUI_iOS#566]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.4`

### 请描述具体问题
QMUIModalPresentationViewController的遮罩层消失有时点两次，有时点一次

**Comment by MoLice** [comment]
请提供具体的重现操作，否则这个 issue 无能为力

**Comment by godYyj** [comment]
![share](https://user-images.githubusercontent.com/27995210/56349021-493d8e80-61fa-11e9-9355-e6cfb3be06d9.jpg)
点击黑色透明遮罩层时，手指有时点击1次遮罩层消失，有时需要点击2次遮罩层才会消失

**Comment by MoLice** [comment]
使用 QMUIDemo 并没有出现你说的情况，附上录屏如下，可看到点击操作。
建议提供操作视频，或者精准找到出现问题的条件。

[modalPrensentationController.mov.zip](https://github.com/Tencent/QMUI_iOS/files/3093548/modalPrensentationController.mov.zip)

**Comment by MoLice** [comment]
另外要注意，在动画过程中点击遮罩是无效的，此时不接受事件，请观察是否第一次点击时动画仍未结束。

**Comment by godYyj** [comment]
好的，谢谢！
