### ISSUE TITLE
UINavigationController (QMUI) 与 UIViewController (QMUI_View) 同时 swizzle 相同方法，导致以静态库方式编译时，手势返回过程中 self.qmui_navigationBarMaxYInViewCoordinator 为 0

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#567]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.2.1`
- [x] QMUI iOS 版本：`3.1.4`

### 请描述具体问题
满足条件：
1.self.window.rootViewController = tab;   // QMUITabBarViewController
2.tab.viewControllers = @[navi];              // QMUINavigationController

当QMUICMI.automaticCustomNavigationBarTransitionStyle = YES; 且前后两Controller的navigationBar样式不一致时，手势返回触发两次viewDidLayoutSubviews。
第一次 self.qmui_navigationBarMaxYInViewCoordinator = 0，因为 UIViewController+QMUI 233行方法中：
navigationController = self.view.superview.superview.qmui_viewController;
// navigationController 其实为  QMUITabBarViewController
所以这里的判断应该更充分一些

#### 相关截图（断点的堆栈、控制台的 log）
AppDelegate：
```     
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    QMUICMI.automaticCustomNavigationBarTransitionStyle = YES;
    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.backgroundColor = UIColorWhite;
    
    QMUITabBarViewController *tab = [QMUITabBarViewController new];
    
    // ViewController 继承自 QMUICommonViewController
    QMUINavigationController *navi = [[QMUINavigationController alloc] initWithRootViewController:[ViewController new]];
    
    tab.viewControllers = @[navi];
    
    self.window.rootViewController = tab;
 
    [self.window makeKeyAndVisible];
    
    return YES;
}   
``` 

ViewController:
``` 
- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    
    NSLog(@"naviTop=%f", self.qmui_navigationBarMaxYInViewCoordinator);
}

- (UIImage *)navigationBarBackgroundImage {
    return self.changeNavigationBarColor ? [UIImage qmui_imageWithColor:UIColorBlue] : [UIImage qmui_imageWithColor:UIColorRed];
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    ViewController *vc = ViewController.new;
    vc.changeNavigationBarColor = !self.changeNavigationBarColor;
    [self.navigationController pushViewController:vc animated:YES];
}
``` 
Log:
``` 
2019-04-19 17:48:56.047913+0800 Test[11868:233935] navigationController=<QMUITabBarViewController: 0x7fc346866000>
superclass:				UITabBarController
title:					(null)
view:					<UILayoutContainerView: 0x7fc346606750; frame = (0 0; 375 812); autoresize = W+H; layer = <CALayer: 0x6000009ef300>>
viewControllers(1):		(
							[0]<QMUINavigationController: 0x7fc34685e400>
						)
selectedViewController(0):	<QMUINavigationController: 0x7fc34685e400>
2019-04-19 17:48:56.048101+0800 Test[11868:233935] naviTop=0.000000
2019-04-19 17:48:56.053338+0800 Test[11868:233935] naviTop=88.000000
```

**Comment by MoLice** [comment]
已发布 3.1.5 修复该问题。

**Comment by fanyuecheng** [comment]
是不是没理解我的意思，方法返回的view的controller不是navigationController，而是tabBarController，你直接置为nil然后再返回0，这样行吗？
上面的代码写的很清楚了，要不要我再发个demo？

**Comment by ziecho** [comment]
根据你提供的代码，这边无法复现你说的通过 `self.view.superview.superview.qmui_viewController` 拿到了非 `TabBarViewController ` 的问题

`qmui_viewController` 是在 vc 的 viewDidLoad 方法里取把 self.view 和 self 作一个绑定关系，
猜测出现这个问题是这段代码没有执行到，请检查以下可能：

1、你继承了 NavigationController 并重写了 `- (void)viewDidLoad` 但是没有调用 super
2、Swizzle 导致了没有正确调用 viewDidLoad（比如友盟之前某个版本存在BUG， hook 了系统的生命周期方法，但是没有调用原来的实现）

或者，请提供一个可以复现这个问题的 Demo

**Comment by fanyuecheng** [comment]
给个邮箱 我发给你

**Comment by ziecho** [comment]
> 给个邮箱 我发给你

直接压缩成 zip，拖拽到 Comment 的输入框就可以了

**Comment by fanyuecheng** [comment]
[Test.zip](https://github.com/Tencent/QMUI_iOS/files/3102232/Test.zip)

**Comment by ziecho** [comment]
看了下，是因为 Demo 中直接引入代码和用 pod 引入在 +load 时机不一致的问题导致：
Demo 中：
![image](https://user-images.githubusercontent.com/16473618/56485405-75148900-6506-11e9-845a-ed15e52e6b77.png)

使用 pod 引入：
![image](https://user-images.githubusercontent.com/16473618/56485419-7d6cc400-6506-11e9-8639-cb40ed668966.png)

如果 `UINavigationController(QMUI)` 比 `[UIViewController(QMUI_View) load` 先执行会导致 UINavigationController 替换的 `- (void)viewDidLoad` 方法为系统的原始方法，导致在 UINavigationController viewDidLoad  时没有执行绑定的代码。

目前你可以暂时修改 pod 源码，将 延迟一个 runloop 执行来解决这个问题

```objc
@implementation UINavigationController (QMUI)

+ (void)load {
    dispatch_async(dispatch_get_main_queue(), ^{
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            SEL selectors[] = {
                @selector(viewDidLoad),
                @selector(navigationBar:shouldPopItem:)
            };
            for (NSUInteger index = 0; index < sizeof(selectors) / sizeof(SEL); index++) {
                SEL originalSelector = selectors[index];
                SEL swizzledSelector = NSSelectorFromString([@"qmuinav_" stringByAppendingString:NSStringFromSelector(originalSelector)]);
                ExchangeImplementations([self class], originalSelector, swizzledSelector);
            }
        });
    });
}

```

**Comment by fanyuecheng** [comment]
修改过后，直接点击<  pop回上一页面时，会走
```
// 无 bar pop 回有 bar 的界面时，被 pop 掉的那个无 bar 的界面
return 0;
```
你试试

**Comment by MoLice** [comment]
这个问题将会在近期的版本里修复

**Comment by MoLice** [comment]
3.1.6 已修复该问题。
