### ISSUE TITLE
_performBatchUpdates:completion: 上线被检测到私有api

### ISSUE THREAD

**Issue by iizvv** [Tencent/QMUI_iOS#569]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.1.5`

### 请描述具体问题
私有api上线被拒

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/15830996/56450916-8bcaac80-635b-11e9-9329-4eb8fe72d4b5.png)

**Comment by lexiaoyao20** [comment]
+1  遇到了同样的问题

**Comment by iizvv** [comment]
> +1 遇到了同样的问题

我是暂时退回了3.1.4

**Comment by wbcyclist** [comment]
<img width="668" alt="2019-04-25_9 29 41" src="https://user-images.githubusercontent.com/2424522/56703794-09683100-673d-11e9-9286-685c15f69f9c.png">
 +1

**Comment by Xxxda** [comment]
同遇到此问题

**Comment by tanranran** [comment]
+1

**Comment by MoLice** [comment]
3.1.6 已修复该问题，请升级版本重试。
