### ISSUE TITLE
当 UICollectionView 遇到 qmui_maskedCorners 会有意想不到的问题

### ISSUE THREAD

**Issue by Joan-m** [Tencent/QMUI_iOS#570]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.3`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题
_collectionView.layer.cornerRadius = 4;
 _collectionView.layer.qmui_maskedCorners = QMUILayerMinXMaxYCorner | QMUILayerMaxXMaxYCorner;

详细在demo
#### 相关截图（断点的堆栈、控制台的 log）

[demo.zip](https://github.com/Tencent/QMUI_iOS/files/3116202/demo.zip)

**Comment by MoLice** [comment]
3.1.7 已修复该问题
