### ISSUE TITLE
请问QMUIFloatLayoutView支持Masonry布局吗

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#571]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.4`

### 请描述具体问题
这样子布局，高度为0
`[self.floatLayoutView mas_makeConstraints:^(MASConstraintMaker *make) {
       make.top.equalTo(self.addButton.mas_bottom).offset(20);
       make.left.equalTo(self.view).offset(15);
       make.right.equalTo(self.view).offset(-15);
    }];`

**Comment by jiasongs** [comment]
已解决啦

**Comment by xhjss** [comment]
请问怎么解决的
