### ISSUE TITLE
大佬们有没有将二维码组件开放出来的打算

### ISSUE THREAD

**Issue by a714857512** [Tencent/QMUI_iOS#573]
如题，大佬们有没有将二维码组件开放出来的打算呢

**Comment by karosLi** [comment]
> 如题，大佬们有没有将二维码组件开放出来的打算呢

我也想看下二维码扫描的部分

**Comment by MoLice** [comment]
二维码扫描是个复杂且独立的功能，QMUI 作为一个 UI 框架不会包含这样的功能。

**Comment by a714857512** [comment]
好的，我把 QMUI 当成 mPaaS 框架类型的了
