### ISSUE TITLE
可否提供QMUIButton的默认字体大小和字体颜色的配置表项

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#574]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.7`

### 请描述具体问题
现在项目中使用QMUIButton，默认的字体大小和颜色是系统的，每次需要设置一遍，又不是很想继承QMUIButton和用runtime设置这些代码，如果能在配置表里设置就完美了。
#### 相关截图（断点的堆栈、控制台的 log）
无

**Comment by MoLice** [comment]
button 在常见的项目中使用频率很高，越高的频率意味着越多的差异需求，所以提供这样一个统一设置意义不大，依然有很多地方需要自定义，所以 QMUI 不会增加这样的配置项，建议从业务角度考虑如何优化这个问题，例如使用工具方法去 format 同一类型的 button 的样式。

**Comment by jiasongs** [comment]
收到！
