### ISSUE TITLE
iTouch iOS 9.2 使用cocoapod 直接闪退

### ISSUE THREAD

**Issue by jianjianhao** [Tencent/QMUI_iOS#575]
- [x] 设备：iPod touch 6 
- [x] 系统：iOS 9.2
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：最新cocoapod 版本

目测只有iTouch设备遇到,但是使用子项目导入不会闪退，具体原因不知道是什么

<img width="916" alt="6DB16A08-5D98-4315-B52F-38BCDD961930" src="https://user-images.githubusercontent.com/12797357/56944636-ad474780-6b56-11e9-8ad4-0b543e8d5b85.png">

**Comment by MoLice** [comment]
这两天会发一个版本修复这个问题，在此之前请自行在 [QMUIRuntime.h:166](https://github.com/Tencent/QMUI_iOS/blob/master/QMUIKit/QMUICore/QMUIRuntime.h#L166) 中，将参数 `__kindof NSObject *selfObject` 改为 `__unsafe_unretained __kindof NSObject *selfObject`。

**Comment by jianjianhao** [comment]
ok

**Comment by MoLice** [comment]
已发布 3.1.8 修复该问题。
