### ISSUE TITLE
上传被拒私有API 

### ISSUE THREAD

**Issue by DragonMichael** [Tencent/QMUI_iOS#576]
### 请填写运行环境

- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.5`

### 请描述具体问题
The app references non-public selectors in***: _performBatchUpdates:completion:
#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/20676401/56957217-00ca8d00-6b79-11e9-84f3-49b446c639e0.png)

**Comment by MoLice** [comment]
#569
