### ISSUE TITLE
QMUILabel设置qmui_lineHeight的问题

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#577]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.7`

### 请描述具体问题
使用QMUILabel的qmui_lineHeight设置行高，改变控件字号大小的时候，必须同时改变qmui_lineHeight和重新setText:才能生效，否则字体会被截取。

#### 相关截图（断点的堆栈、控制台的 log）
被截取的情况和代码：
![图片](https://user-images.githubusercontent.com/22904757/56976471-a3990080-6ba5-11e9-98d2-92dea0346db6.png)
<img width="137" alt="图片" src="https://user-images.githubusercontent.com/22904757/56976021-9b8c9100-6ba4-11e9-8ef7-6d9157b98cba.png">
未被截取的情况和代码：
![图片](https://user-images.githubusercontent.com/22904757/56976062-b52dd880-6ba4-11e9-9ef0-10a240092b61.png)
<img width="125" alt="图片" src="https://user-images.githubusercontent.com/22904757/56976136-d4c50100-6ba4-11e9-925f-a7b5b26c5260.png">

#### 原因分析
QMUILabel当设置了qmui_lineHeight后采用setAttributedText:方法设置行高，但是设置qmui_lineHeight后，还是使用之前的attributedText，如下图所示：
attributedString对象：
![图片](https://user-images.githubusercontent.com/22904757/56977030-dee7ff00-6ba6-11e9-94bd-fdf7abbefc10.png)
text对象：
![图片](https://user-images.githubusercontent.com/22904757/56977550-f8d61180-6ba7-11e9-86c3-fde1d932502b.png)
text对象的样式覆盖了attributedString对象的样式导致出现的问题

**Comment by MoLice** [comment]
请按 https://github.com/Tencent/QMUI_iOS/commit/e771e057ef08e7503c37fd1abe49e6da14b4e703 修改后再尝试？下个版本将会带上这个改动。

**Comment by jiasongs** [comment]
收到

**Comment by MoLice** [comment]
已发布 3.1.9 修复该问题。
