### ISSUE TITLE
QMUIAlertController的customView上添加了UIButton点击事件不响应，但是响应了按钮的高亮

### ISSUE THREAD

**Issue by 396514268** [Tencent/QMUI_iOS#578]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

**Comment by MoLice** [comment]
无法重现

![image](https://user-images.githubusercontent.com/1190261/57190604-89b54000-6f4e-11e9-97e1-5f6389b0835e.png)

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭
