### ISSUE TITLE
3.1.8版本拦截系统navBar返回按钮事件失效

### ISSUE THREAD

**Issue by Juice007** [Tencent/QMUI_iOS#579]
### 请填写运行环境

- [x] 设备：`All` 
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.2.1`
- [x] QMUI iOS 版本：`3.1.8`

### 请描述具体问题
3.1.7版本后改为采用`ExtendImplementationOfNonVoidMethodWithTwoArguments`宏的方式进行swizzle，但这个宏好像走不进block去。
点进QMUIDemo中的“拦截系统navBar返回按钮事件”，输入内容后，点击返回按钮，直接成功返回了。但是使用手势返回是能够拦截到的。
自己调试了下，发现`UINavigationController+QMUI.m`中是使用`ExtendImplementationOfNonVoidMethodWithTwoArguments`宏来替换`navigationBar:shouldPopItem:`方法的，但是替换方法没有执行。
用回原来的`ExchangeImplementations`方式测了下是可以正常替换的。

然后试了下`QMUIRuntime.h`里的另一个宏`ExtendImplementationOfNonVoidMethodWithoutArguments`发现也走不进block去，用回原来的`ExchangeImplementations`方式也是可以的。

最后试了下不用宏，直接写`OverrideImplementation`方法发现是可以成功替换的。应该是宏的写法导致不调用的，但也没看出宏哪里有问题。

**Comment by MoLice** [comment]
这是 3.1.6 版本里修改 swizzle 写法时手误，代码逻辑在修改前后不一致，引发的 bug。请先按照 commit 的修改方式在本地修改，下个版本会带上这个问题。

**Comment by MoLice** [comment]
已发布 3.1.9 修复该问题。
