### ISSUE TITLE
QMUIButton 在 setImage:forState: 的一处crash

### ISSUE THREAD

**Issue by Juice007** [Tencent/QMUI_iOS#580]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.x & iOS 11.x`
- [x] Xcode 版本：`10.2.1`
- [x] QMUI iOS 版本：`3.1.8`

### 请描述具体问题
在iOS10(测试用的10.3.1)和11(测试用的11.4)的机型上才会出现，iOS12不会出现
在`[self.testBtn setImage:[UIImage qmui_imageWithColor:UIColorGreen] forState:UIControlStateNormal];`之前调用`self.window = [UIApplication sharedApplication].keyWindow;`给window赋值就会出现crash，在之后调用就不会出现。

崩在QMUIButton的`setImage:forState:`方法的`[self imageView];`这一行

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/16225027/57211323-710e5e00-7012-11e9-808c-f8e1bf612654.png)

**Comment by Juice007** [comment]
[QMUIButtonDemo.zip](https://github.com/Tencent/QMUI_iOS/files/3146862/QMUIButtonDemo.zip)
给个我测试的Demo方便重现一下

**Comment by Juice007** [comment]
另外一个奇怪的点是 在Demo里只有给ViewController嵌入了UINavigationController才会出现这个问题，直接将ViewController设置为`is Initial View Controller`是不会出现crash的

**Comment by MoLice** [comment]
已发布 3.1.9 修复该问题。
