### ISSUE TITLE
点击导航返回按钮 UINavigationControllerBackButtonHandlerProtocol 代理拦截不到事件

### ISSUE THREAD

**Issue by DragonMichael** [Tencent/QMUI_iOS#583]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.8`

### 请描述具体问题
实现了下面的代理 只能拦截手势返回 点击返回按钮拦截不到 下面断点hook代码block截图根本不会走 测试最新QMUIDemo 有同样的问题 

    #pragma mark - UINavigationControllerBackButtonHandlerProtocol

    - (BOOL)shouldHoldBackButtonEvent {
        return YES;
    }

    - (BOOL)canPopViewController {
    // 这里不要做一些费时的操作，否则可能会卡顿。
    
    
        [self showQmui_alertViewWithTitle:@"是否返回？" message:@"返回后输入框的数据将不会自动保存" cancelTitle:@"返回" confirmTitle:@"继续编辑" confirmHandler:nil cancelHandler:^(__kindof QMUIAlertController *aAlertController, QMUIAlertAction *action) {
        [self.navigationController popViewControllerAnimated:YES];
        }];
        return NO;
    } 

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/20676401/57269491-3cee7800-70ba-11e9-999d-661c0bc9e3d3.png)

**Comment by MoLice** [comment]
参考 #579

**Comment by DragonMichael** [comment]
收到 谢谢 期待尽快下个版本修复 嘿嘿

**Comment by MoLice** [comment]
已发布 3.1.9 修复该问题。
