### ISSUE TITLE
 QMUIImagePickerViewController 的 selectedImageAssetArray 属性 去除 readonly 修饰建议

### ISSUE THREAD

**Issue by ChengLuffy** [Tencent/QMUI_iOS#584]
### 请填写运行环境

- [x] 设备： `模拟器`
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.2`
- [x] QMUI iOS 版本：`3.1.2`

### 请描述具体问题

建议将以下属性 的 readonly 修饰去掉，这样 可以很方便的实现：用户在单次多图片选择行为里多次进入图片选择控制器时，之前所选的的图片本次依然是选中状态。

https://github.com/Tencent/QMUI_iOS/blob/887b6eb071f501db25d2d4eae2fb26dbce57f44b/QMUIKit/QMUIComponents/ImagePickerLibrary/QMUIImagePickerViewController.h#L121

参考

https://github.com/Tencent/QMUI_iOS/blob/887b6eb071f501db25d2d4eae2fb26dbce57f44b/QMUIKit/QMUIComponents/AssetLibrary/QMUIAsset.h#L59

https://github.com/Tencent/QMUI_iOS/blob/887b6eb071f501db25d2d4eae2fb26dbce57f44b/QMUIKit/QMUIComponents/ImagePickerLibrary/QMUIImagePickerViewController.m#L352

**Comment by MoLice** [comment]
`selectedImageAssetArray` 是一个 `NSMutableArray`，这种场景下建议你可以直接 addObject/removeObject 即可，无需更改 `selectedImageAssetArray` 的指针。

**Comment by ChengLuffy** [comment]
明白了
