### ISSUE TITLE
iPhone5 集成 QMUI_iOS 后运行App直接崩溃

### ISSUE THREAD

**Issue by wbcyclist** [Tencent/QMUI_iOS#585]
### 运行环境
暂时只在iPhone5(设备、模拟器、iOS10)上会触发

### 场景重现
创建新项目，不添加任何代码直接集成`QMUI_iOS`，运行就会崩溃
[QMUIDemo.zip](https://github.com/Tencent/QMUI_iOS/files/3155244/QMUIDemo.zip)

#### 相关截图（断点的堆栈、控制台的 log）
<img width="1237" alt="2019-05-07" src="https://user-images.githubusercontent.com/2424522/57345893-29f1ab80-717f-11e9-8c89-f9d8aa42ed4b.png">

**Comment by wbcyclist** [comment]
已提交PR #586
很奇怪为什么 class_getInstanceMethod 返回NULL后的runtime处理，不同设备会有不一致的效果。

**Comment by Summer006** [comment]
我也遇到了，似乎是一个zombie问题，下面是instruments截图
![image](https://user-images.githubusercontent.com/8596248/57354631-8a441580-719e-11e9-9425-fb7758226323.png)

**Comment by MoLice** [comment]
与设备无关，请贴出具体的 iOS 版本号、pod 拉取到的 QMUI 版本

**Comment by wbcyclist** [comment]
QMUI > 3.1.7 问题就会重现 （先后 拉取 尝试了3.1.7、3.1.8、3.1.9）
iPhone5实机  iOS 10.3.3
iPhone5模拟器 iOS 10.3.1
问题那里有项目下载 `QMUIDemo.zip`  pod install 后就能运行。
注：问题是iPhone5设备才会重现，iPhone5s以上是没问题的。4s、5c没尝试，还有iOS9也没尝试。

**Comment by MoLice** [comment]
该问题是 `qmui_performSelector:withReturnValue:arguments:` 方法在面对对象类型的返回值时会产生野指针的 bug，而近期更新里，新的 swizzle 方式使用到了这个方法，导致 crash。

已发布 3.2.0 修复该问题。
