### ISSUE TITLE
拜托上点心

### ISSUE THREAD

**Issue by Wbqqqq** [Tencent/QMUI_iOS#590]
拜托你们上点心行不行，你们不是挂名腾讯嘛？，搞出来的东西这样子？，今天发布10.0以下全部闪退，看了issue才发现这样那样的问题，app都已经全量发放了！，公司客服电话都被打爆了！！，如果你们觉得你们做不到全面的测试，请支呼一声，我立马删库，搞什么东西啊！？

**Comment by dingliang** [comment]
兄弟，回来吧，CTO觉得开除有点太过严厉了，还是想让你回来继续996的。

**Comment by wbcyclist** [comment]
提出闪退问题，协助改进完善项目   ✘
发帖谴责                                           ✔︎

**Comment by jhchenchong** [comment]
项目闪退 不是应该是自己的问题吗？凭本事用的三方库，崩溃了喷开源？ 想不明白...有人求你用了？

**Comment by MoLice** [comment]
3.1.9版本在 32bit iOS 10 设备下确实存在启动 crash 的 bug，由于 iPhone 5 这种老机器占有率低，我们在日常测试中一般没有覆盖到，所以没有及时发现该问题，后续我们会加强对设备和 iOS 版本兼容问题的检查。

在发布3天后也即5月10日发布了新版本修复该问题，距离贵项目发布仍有2天时间，建议业务项目在引入 QMUI 的同时也要保证好自身的发布前测试，并及时关注项目使用的第三方框架的更新动态。

**Comment by Wbqqqq** [comment]
@MoLice  抱歉，当时语言过激了，因为差点被开除了

**Comment by MoLice** [comment]
🤝也确实是 QMUI 存在的问题，希望后续不会出现这种情况。

**Comment by SilenceLove** [comment]
这个框架入侵性太强

**Comment by SilenceLove** [comment]
已经提了，等待回复？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MoLice <notifications@github.com&gt;
发送时间: 2019年10月18日 17:50
收件人: Tencent/QMUI_iOS <QMUI_iOS@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[Tencent/QMUI_iOS] 拜托上点心 (#590)




@SilenceLove 请新开 issue 陈述你遇到的具体问题或者建议，这样的表达对问题的理解没有帮助。
