### ISSUE TITLE
QMUIAlertController的message可以添加rang来设置某一位置的文字吗

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#592]
### 请填写运行环境

- [x] 设备：模拟器
- [x] 系统：iOS 12.1
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.2.0`

### 请描述具体问题
比如说message是"请确定金额是：50元"，50元是标红的。
我查看源码发现`messageLabel`私有的，不能进而添加rang来设置富文本。

**Comment by MoLice** [comment]
接口需要较大改造才能支持，性价比不高，建议通过 customView 的方式实现。

**Comment by jiasongs** [comment]
好的，了解
