### ISSUE TITLE
qmui_closeItemWithTarget 图片颜色无法跟随 navigationBar.tintColor

### ISSUE THREAD

**Issue by fanfanbin** [Tencent/QMUI_iOS#593]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.2`
- [x] Xcode 版本：`10.2.1`
- [x] QMUI iOS 版本：`3.2.0`

#### 相关截图（断点的堆栈、控制台的 log）

![image](https://user-images.githubusercontent.com/50076805/57837849-2f419c80-77f6-11e9-94db-4d3ba6bf1983.png)
![image](https://user-images.githubusercontent.com/50076805/57838015-7fb8fa00-77f6-11e9-9086-c4b3dab1f03d.png)

**Comment by MoLice** [comment]
问题是？

**Comment by fanfanbin** [comment]
不好意思，提交的时候网页卡住了，
QMUIConfigurationTemplate navBarTintColor 设置了白色，
其他class里设置了navigationBarTintColor 设置了黑色
没有生效？

**Comment by MoLice** [comment]
问题排查思路：
1. 图片颜色不符合预期，那么先看按钮的图片是怎么来的：
![image](https://user-images.githubusercontent.com/1190261/57918504-79e01900-78c9-11e9-857b-c7efb267f5df.png)
2. 查看 `NavBarCloseButtonImage` 宏，可以看到是通过配置表设置的：
![image](https://user-images.githubusercontent.com/1190261/57918611-b1e75c00-78c9-11e9-9801-1b4d5f505db0.png)
3. 到配置表里搜索该图片的实际值，可以看到是通过 `UIImage qmui_imageWithShape` 生成，且生成时的颜色用了宏 `NavBarTintColor` 的颜色：
![image](https://user-images.githubusercontent.com/1190261/57918711-e6f3ae80-78c9-11e9-91de-7267fcd77fa5.png)
4. 根据 UIKit 的设定，`UIBarButtonItem` 的图片颜色要跟随 `UINavigationBar` 的 `tintColor` 的前提是该 `UIImage` 的 `renderingMode` 必须为 `UIImageRenderingModeAlwaysTemplate`，而 `UIImage.renderingMode` 默认值为 `UIImageRenderingModeAutomatic`，所以尝试修改配置表，改为 `QMUICMI.navBarCloseButtonImage = [[UIImage xxxx] imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];`。
5. 到此问题解决。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
