### ISSUE TITLE
QMUIAlbumViewController中没有看到拍摄的单元格按钮，只能单纯的选择相册里的图片或者视频么？

### ISSUE THREAD

**Issue by a714857512** [Tencent/QMUI_iOS#594]
### 请填写运行环境

- [x] 设备：`All` / `iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`3.x.x`

**Comment by a714857512** [comment]
如题：QMUIAlbumViewController中没有看到拍摄的单元格按钮，只能单纯的选择相册里的图片或者视频么？

**Comment by MoLice** [comment]
QMUI 目前暂无封装拍摄，也没提供拍摄的 item，如果需要请自行继承重写

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
