### ISSUE TITLE
发现内存泄漏

### ISSUE THREAD

**Issue by Lanhaoo** [Tencent/QMUI_iOS#595]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="1021" alt="屏幕快照 2019-05-17 上午10 50 41" src="https://user-images.githubusercontent.com/38837048/57900064-01aa3100-7892-11e9-9af1-84a3d540ac06.png">
<img width="1021" alt="屏幕快照 2019-05-17 上午10 49 53" src="https://user-images.githubusercontent.com/38837048/57900068-07077b80-7892-11e9-825d-d438bbf99a7d.png">
<img width="1022" alt="屏幕快照 2019-05-17 上午10 50 28" src="https://user-images.githubusercontent.com/38837048/57900074-0969d580-7892-11e9-91b3-aec01ffb4dba.png">

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]

**Comment by MoLice** [comment]
报错的位置均为 QMUI swizzle 了系统的方法后，对系统原有方法的调用，所以问题不在 QMUI，建议排查自身业务代码的问题。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
