### ISSUE TITLE
QMUITextView 光标高度错误

### ISSUE THREAD

**Issue by HouWan** [Tencent/QMUI_iOS#596]
**Bug 表现**
使用`QMUITextView`的`typingAttributes`设置行间距之后，当光标在多行之间定位时，光标的高度就会跟字体高度不一致。

**截图**
![IMG_0493](https://user-images.githubusercontent.com/13991710/57906611-26f86880-78ad-11e9-96d4-31fc49fa3204.PNG)

**如何重现**
设置行间距即可，比如
```
NSMutableParagraphStyle *ps = [[NSMutableParagraphStyle alloc] init];
ps.lineSpacing = 10;
ps.paragraphSpacing = 5;

self.textView.typingAttributes = @{NSFontAttributeName: UIFontMake(15),
                                   NSForegroundColorAttributeName: UIColorGray1,
                                   NSParagraphStyleAttributeName: ps};
```

**预期的表现**
正常情况下，光标应该跟字体一样高。

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]
 - 任意设备都是如此。

**Comment by MoLice** [comment]
UITextView 本身的表现如此，与 QMUITextView 无关，建议遇到此类问题前先区分是系统如此还是 QMUI 的问题哈。
