### ISSUE TITLE
QMUITextView text 置为 nil 时 newHeightAfterTextChanged 返回的 height 值错误

### ISSUE THREAD

**Issue by LiuGanQQQ** [Tencent/QMUI_iOS#597]
**Bug 表现**
在QMUITextView.text有值的情况下，赋值为nil，会导致- (void)textView:(QMUITextView *)textView newHeightAfterTextChanged:(CGFloat)height 方法返回的高度为两行内容的高度

**截图**
![1](https://user-images.githubusercontent.com/21186780/57967499-4b7a4080-7992-11e9-9295-e645d50a9b39.jpg)
![2](https://user-images.githubusercontent.com/21186780/57967500-4d440400-7992-11e9-91f1-e049d3e5a3cc.jpg)

**如何重现**
1. textView正常键盘输入字符
2.点击发送，textView.text置空

**预期的表现**
置空后- (void)textView:(QMUITextView *)textView newHeightAfterTextChanged:(CGFloat)height 方法返回一行的高度

**其他信息**
 - 设备: iPhone X
 - iOS 版本: [iOS 12.0]
 - Xcode 版本: [Xcode 10.1]
 - QMUI 版本: [3.2.0]

**Comment by MoLice** [comment]
以 QDTextViewController 为例，将其中的 `textViewMinimumHeight` 属性删掉后测试并未发现问题，录屏如下：

可以看到默认情况下输入框高度为40（也即单行文字高度+内部 padding），在输入单行文字发送后将 text 置为 nil 时，并不会触发 `textView:newHeightAfterTextChanged:` 方法（因为这个过程中输入框高度并没有发生变化），当输入两行文字后，`textView:newHeightAfterTextChanged:` 被触发了，参数 `height` 为 60（也即两行文字高度+内部 padding），然后发送，将 text 置为 nil，`textView:newHeightAfterTextChanged:` 再次被触发，此时参数 `height` 回到了 40，并没有出现 issue 所说的“两行文字高度”的现象。建议重新检查自身业务代码是否有问题，或者 issue 里提供的信息有什么不完整。

**Comment by LiuGanQQQ** [comment]
> 以 QDTextViewController 为例，将其中的 `textViewMinimumHeight` 属性删掉后测试并未发现问题，录屏如下：
> [QMUITextView.mov.zip](https://github.com/Tencent/QMUI_iOS/files/3197026/QMUITextView.mov.zip)
> 
> 可以看到默认情况下输入框高度为40（也即单行文字高度+内部 padding），在输入单行文字发送后将 text 置为 nil 时，并不会触发 `textView:newHeightAfterTextChanged:` 方法（因为这个过程中输入框高度并没有发生变化），当输入两行文字后，`textView:newHeightAfterTextChanged:` 被触发了，参数 `height` 为 60（也即两行文字高度+内部 padding），然后发送，将 text 置为 nil，`textView:newHeightAfterTextChanged:` 再次被触发，此时参数 `height` 回到了 40，并没有出现 issue 所说的“两行文字高度”的现象。建议重新检查自身业务代码是否有问题，或者 issue 里提供的信息有什么不完整。

我尝试着排查了一下，发现我的代码里面实现了-(BOOL)textViewShouldReturn:(QMUITextView *)textView这个代理，注释掉就正常了。请尝试在这个代理里面设置textView.text = nil，代码如下：
![企业微信截图_3e064137-25b9-4d6d-bfb5-daf368a9fe7e](https://user-images.githubusercontent.com/21186780/58010953-eb1b0880-7b23-11e9-80b8-89d4e596b6ba.png)
感谢您的反馈！

**Comment by LiuGanQQQ** [comment]
测试了一下，发现 textViewShouldReturn 返回 YES 即可正常返回高度，再次感谢！
