### ISSUE TITLE
QMUIConfigurationTemplate 导航栏颜色设置不了，demo中我也试过了

### ISSUE THREAD

**Issue by a714857512** [Tencent/QMUI_iOS#599]
**Bug 表现**
QMUIConfigurationTemplate 导航栏背景颜色设置不了

**截图**

**如何重现**
QMUIConfigurationTemplate 导航栏背景颜色设置不了demo中我也试过了，
具体将文件中的 274行的 themeTintColor 设置成红色或者其他颜色，以及103行的QMUICMI.navBarBarTintColor 设置成红色或者其他颜色，结果都是显示原来的蓝色，到demo中的设置主题色切换时，导航栏的背景颜色依然无法改变。

**预期的表现**
应该是可以设置成为其他颜色吧

**其他信息**
 - 设备: iPhone 7
 - iOS 版本: [iOS 12.3]
 - Xcode 版本: [Xcode 10.3]
 - QMUI 版本: [3.2.0]

**Comment by a714857512** [comment]
我刚刚有看了下，看到 QMUIConfigurationTemplate 文件中的102行设置的导航栏背景图片，正是用的 themeTintColor ，也就是274的主题色。所以感觉很奇怪，为何设置成其他颜色没有效果。

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/58006006-97a3bd00-7b19-11e9-9bd3-2565fdad5d11.png)

QMUI Demo 里的配置表文件最多只到 250 行，不存在 274 行，另外 102 行是 `tabBarBarTintColor`，并非导航栏的配置，请确认拉取的 QMUI Demo 版本是否正确。

![image](https://user-images.githubusercontent.com/1190261/58006041-adb17d80-7b19-11e9-969d-f4bb238f986f.png)

另外，`navBarBackgroundImage` 优先级高于 `navBarBarTintColor`，UIKit 设定如此，所以如果要修改 `navBarBarTintColor`，请先确认 `navBarBackgroundImage` 值为空。

**Comment by a714857512** [comment]
噢，我看的是我改成swift的配置文件。并且在修改时改错了地方，不好意思打扰了。
