### ISSUE TITLE
qmuidemo跑不起来呢 在xcode 10.2

### ISSUE THREAD

**Issue by LJW008** [Tencent/QMUI_iOS#603]
**Bug 表现**
问题的具体描述
ld: warning: directory not found for option '-F/Users/lijunwu/Desktop/Demo/综合功能demo/QMUI--/QMUIDemo_iOS-'
ld: warning: directory not found for option '-Fmaster 4/Users/lijunwu/Desktop/Demo/综合功能demo/QMUI--/QMUIDemo_iOS-master 4/qmuidemo/Frameworks'
ld: framework not found RevealServer
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [模拟器、iPhone、]
 - iOS 版本: [iOS 12.2]
 - Xcode 版本: [Xcode 10.2]
 - QMUI 版本: [3.1.8]

**Comment by ziecho** [comment]
经过测试，项目路径中有中文名确实会有这个问题，应该 Xcode  的 BUG，请把项目移动到没有中文路径的地方。
