### ISSUE TITLE
iOS11 导航栏没有大标题特性

### ISSUE THREAD

**Issue by zhangBoy** [Tencent/QMUI_iOS#604]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。

在iOS11及以上的系统，不能设置大标题特性。在视图控制器中，使用self.navigationItem.title不能给导航栏设置标题，不过可以使用设置大标题；如果设置了self.titleView.title，大标题特性会消失。如果是本人对QMUIKit的功能疏忽的话，请告知设置大标题特性。谢谢！

**Comment by ziecho** [comment]
如果开启了大标题特性 `self.navigationItem.title` 在只能设置侧的大标题（顶部导航栏中间是空的），这是系统的特性和 QMUI 无关，之所以用 `self.titleView.title` 可以在导航栏顶部中间显示标题，是因为 QMUI 在内部把 navigationItem.titleView 设置为 QMUINavigationTitleView，在这个 view 去显示 titleLabel。
你说的 「如果设置了self.titleView.title，大标题特性会消失」，经过测试暂时没有发现什么问题，请具体说明是什么特性消失，表现形式和期望的效果是怎么样的。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。

**Comment by Karthus1110** [comment]
self.navigationItem.title = @"title";
self.titleView.title = @"title";
同时写上这两个的话 小标题就一直显示，不写下面一句的话 滑动隐藏大标题之后 小标题不会显示，失去了iOS自带的大标题小标题切换特性
