### ISSUE TITLE
集成 Hero 报错

### ISSUE THREAD

**Issue by azureplus** [Tencent/QMUI_iOS#605]
**Bug 表现**
问题的具体描述
   navigationController?.heroNavigationAnimationType = .zoomOut

    navigationController?.hero.isEnabled = sender.isOn
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]

**Comment by azureplus** [comment]
- (void)forwardInvocation:(NSInvocation *)anInvocation {
    SEL selector = anInvocation.selector;
    NSPointerArray *delegates = [self.delegates copy];
    for (id delegate in delegates) {
        if ([delegate respondsToSelector:selector]) {
            [anInvocation invokeWithTarget:delegate];
        }
    }
}

**Comment by MoLice** [comment]
> Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。

**Comment by azureplus** [comment]
- (BOOL)shouldAutorotate {
    return [self.visibleViewController qmui_hasOverrideUIKitMethod:_cmd] ? [self.visibleViewController shouldAutorotate] : YES;
}

注销掉这行，强制屏幕旋转 ，当前的 vc 才能旋转
