### ISSUE TITLE
是否要考虑提供做字体的适配

### ISSUE THREAD

**Issue by YaoJuan** [Tencent/QMUI_iOS#606]
目前同样的字体在XR上会显得各位模糊，在xsmax上也会显得小。之前我看贵司的qq组和微信组也有类似的问题，不过随后做了适配。不知道qmui是否会在后续提供类似的api呢

**Comment by MoLice** [comment]
按我们的观察，并不存在“同样的字体在XR上会显得各位模糊，在xsmax上也会显得小”的情况，建议检查 App 编译的 SDK 版本是否最新、是否有配置正确的启动页。QMUI 也不会针对这种场景提供类似的 API。

**Comment by YaoJuan** [comment]
> 按我们的观察，并不存在“同样的字体在XR上会显得各位模糊，在xsmax上也会显得小”的情况，建议检查 App 编译的 SDK 版本是否最新、是否有配置正确的启动页。QMUI 也不会针对这种场景提供类似的 API。

好的，谢谢
