### ISSUE TITLE
QMUISearchController的searchBar没有挡住状态栏

### ISSUE THREAD

**Issue by hkjin** [Tencent/QMUI_iOS#610]
**Bug 表现**
问题的具体描述
搜索框进入编辑时，状态栏是一个黑色半透明遮罩，内容向上滑动时，内容会显示在状态栏上

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![IMG_BC931DFCD446-1](https://user-images.githubusercontent.com/17734586/58622000-3cce4a80-82fd-11e9-884b-5327b4a80558.jpeg)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现
正常情况下，搜索框应该盖住状态栏

**其他信息**
 - 设备:iPhone
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: Xcode 10.2.1
 - QMUI 版本: 3..1.9

**Comment by MoLice** [comment]
请贴出具体代码

**Comment by hkjin** [comment]
> 请贴出具体代码

使用的就是QMUICommonTableViewController，不知道与FDFullscreenPopGesture有没有关系

`override func viewDidLoad() {
        super.viewDidLoad()
        title = "邀请好友"
        // 显示搜索框
        shouldShowSearchBar = true
        // 搜索框的颜色
        searchBar.backgroundImage = UIImage(color: UIColor.white)
        // 返回按钮
        useBackBarButtonItem()
        tableView.backgroundColor = UIColor(rgb: 0xF5F7F9)
        tableView.separatorStyle = .none
        searchController.tableView.backgroundColor = UIColor(rgb: 0xF5F7F9)
        searchController.tableView.separatorStyle = .none
        
        tableView.register(JOINIMInviteUserViewCell.self, forCellReuseIdentifier: "JOINIMInviteUserViewCell")
        searchController.tableView.register(JOINIMInviteUserViewCell.self, forCellReuseIdentifier: "JOINIMInviteUserViewCell")
        if group_id == nil {
            if group != nil {
                group_id = group!.group_id
            }
        }
        (btnConfirm.rx.tap)
            .throttle(kjButtonActionSpace, latest: false, scheduler: MainScheduler.instance)
            .subscribe(onNext: {
                [weak self] in
                // 确定邀请进群
                self?.invite()
            }).disposed(by: dispose)
        
        // 获取好友列表
        getUserFriends()
    }`

`/// 搜索
    override func searchController(_ searchController: QMUISearchController!, updateResultsForSearch searchString: String!) {
        guard searchString.isEmpty == false else {
            searchArray.removeAll()
            searchController.tableView.reloadData()
            return
        }
        let data = (dataArray as NSArray).filtered(using: NSPredicate(format: "name like[cd] '*\(searchString!)*'"))
        searchArray.removeAll()
        if data.count > 0 {
            searchArray.append(contentsOf: (data as! Array<PersonalModel>))
        }
        searchController.tableView.reloadData()
    }
    
    override func willPresent(_ searchController: QMUISearchController!) {
        setNeedsStatusBarAppearanceUpdate()
    }
    
    override func willDismiss(_ searchController: QMUISearchController!) {
        setNeedsStatusBarAppearanceUpdate()
    }`

**Comment by MoLice** [comment]
看不出来是什么问题，可以尝试换种设置背景图的方式，例如 [UISearchBar.m:388-389](https://github.com/Tencent/QMUI_iOS/blob/master/QMUIKit/UIKitExtensions/UISearchBar%2BQMUI.m#L388-L389) 的写法。

或者提供一份有问题的 Demo。

**Comment by hkjin** [comment]
> 看不出来是什么问题，可以尝试换种设置背景图的方式，例如 [UISearchBar.m:388-389](https://github.com/Tencent/QMUI_iOS/blob/master/QMUIKit/UIKitExtensions/UISearchBar%2BQMUI.m#L388-L389) 的写法。
> 
> 或者提供一份有问题的 Demo。

找到问题了，是因为edgesForExtendedLayout = UIRectEdgeNone导致的。。

**Comment by Goallying** [comment]
我也有这个问题，edgesForExtendedLayout 没有设置。。。
