### ISSUE TITLE
QMUIButton布局出bug（UICollectionView中）

### ISSUE THREAD

**Issue by JarvisHot** [Tencent/QMUI_iOS#612]
**Bug 表现**
QMUIButton title显示不全

**截图**
![位置错乱图片](https://user-images.githubusercontent.com/14191613/58793497-d319ad80-8628-11e9-9954-2736d9cddc46.jpg)

**如何重现**
1. 在collectionCell上XIb拖一个QMUIbutton或者代码创建一个，自动布局，文字就会显示不完

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [模拟器iPhone xr]
 - iOS 版本: [iOS 12.2]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by WinHand** [comment]
同样遇到

**Comment by ziecho** [comment]
该问题满足以下条件可重现：
1、在 UICollectionViewCell / UITableViewCell 中使用 AutoLayout 对 QMUIButton  进行布局
2、第一次设置了 Titlte 后再次设置一个比之前更长的 Title

比如
```objc
- (__kindof UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    QDCollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"QDCollectionViewCell" forIndexPath:indexPath];
    [cell.btn setTitle:@"12345" forState:UIControlStateNormal];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [cell.btn setTitle:@"12345678" forState:UIControlStateNormal];
    });
    return cell;
}
```

导致这个问题的是因为满足上述条件时，系统调用 QMUIButton  layoutSubview  布局时，触发了 [self imageView] 进而 触发 -[UIView layoutBelowIfNeeded] 方法更新 Bounds 触发第二次 layoutSubview 调用，在这次 layout 里，bounds 已被更新为正确的值，在这次 layout 后 label 的宽度可以被正常设置，但是在这次 layout 之后，返回到第一次的调用栈，QMUI 仍然以旧的 bounds 继续布局导致了这个 label 的宽度没有被正确设置（仍然是之前的宽度），请等待我们的修复。

在我们发布新版本之前，你可以在设置 title 之后手动对 button 调用一次 sizeToFit 暂时解决该问题。

```objc
    [cell.btn setTitle:@"title" forState:UIControlStateNormal];
    [cell.btn sizeToFit];
```

**Comment by jiasongs** [comment]
此问题目前还是存在，且调用`[cell.btn sizeToFit]`后，在iOS10系统下cell.btn的高度也不正确了 @MoLice

**Comment by MoLice** [comment]
#1051
