### ISSUE TITLE
QMUI搜索取消在iOS 13必现崩溃

### ISSUE THREAD

**Issue by horsley** [Tencent/QMUI_iOS#614]
在方法fixDismissingAnimation中

[<UISearchBar > valueForUndefinedKey:]: this class is not key value coding-compliant for the key background.

**Comment by MoLice** [comment]
iOS 13 的适配正在进行中，近期会有一个 beta Release 出来（因为 iOS 13 本来就是 beta）。

**Comment by MoLice** [comment]
#617
