### ISSUE TITLE
[iOS 13] All bugs in iOS 13

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#615]
1. ✅#616 `[UITabBarItem (QMUI) qmui_imageViewInTabBarButton:]` can not find the right `UIImageView`.
1. ✅#617 Access to ivar is prohibited.
1. ✅#618 `UITabBar.shadowImage` not working.
1. ✅#619 `NavBarTintColor` not working.
1. ✅#620 `UIButton` not showing complete title with Bold Text enabled.
1. ✅#622 `UISearchBar (QMUI).qmui_textFieldMargins` not working.
1. ✅#628 `_UINavigationBarContentView ` change properties will cause a crash
1. ✅#650 Keyboard Notification's `endFrame` get wrong value
1. ✅#651 first keyboard bouncing will trigger statusBar orientation notification
1. ✅#659 UIMenuController's window changed in iOS 13
1. ✅#672 Set foregroundColor by UITabBarItemStateAppearance.titleTextAttributes not working.
1. ✅#673 UITabBar layout is broken on iOS 13.0 Beta 5.
1. ✅#693 UIButton as accessory view in UITableViewCell has wrong frame.

**Comment by echo2046** [comment]
UITabBar.shadowImage not working.这个bug是还没有解决是吧

**Comment by MoLice** [comment]
@echo2046 这个暂时没有解决方式，内部版本里，对于 iOS 13 下我们改为使用新的 `UITabBar.standardAppearance.shadowColor` 实现，iOS 12 及以下依然使用旧版的 `UITabBar.shadowImage`。

**Comment by lengain** [comment]
UIView (QMUI_Layout) +load方法中

> OverrideImplementation([UIView class], @selector(setFrame:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void))

里报

> *** Assertion failure in -[_UITableViewHeaderFooterContentView _headerFooterView], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3899.13.13/UITableViewHeaderFooterView.m:202

**Comment by MoLice** [comment]
为了保证阅读效率，@lengain 请新建 issue 提问题，这里的评论我将会删掉。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本兼容 iOS 13。
