### ISSUE TITLE
[iOS 13] UITabBar.shadowImage not working

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#618]

**Comment by MoLice** [comment]
iOS 13 Beta 7 实测，不管 `UITabBar` 是否设置了 `backgroundImage`，直接对 `UITabBar.shadowImage` 赋值是无效的，目前已知的方式只能通过 iOS 13 新提供的 `UITabBar.standardAppearance.shadowImage` 或 `UITabBar.standardAppearance.shadowColor` 来设置分隔线。

目前 QMUI 内部版本已经针对 iOS 13 和非 iOS 13 区分了配置表里 `TabBarShadowImageColor` 不同的实现方式，等新版发布即可。至于非配置表的使用场景（也即直接在业务代码里修改某个 tabBar 对象的 shadowImage），只能自行区分 iOS 版本去实现。

**Comment by fero2004** [comment]
![2A927245-BD68-4FB3-B90A-5528B3896CD9](https://user-images.githubusercontent.com/5326843/63510333-e4c86e00-c510-11e9-9c28-18e54e0034f4.png)
以上关键代码ios13可以隐藏shadowImage @MoLice

**Comment by MoLice** [comment]
@fero2004 问题不在于隐藏 shadowImage 哦，在于设置了 shadowImage 后没有生效，依然显示了系统默认的灰色分隔线。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
