### ISSUE TITLE
[iOS 13] UIButton not showing complete title with Bold Text enabled

### ISSUE THREAD

**Issue by ziecho** [Tencent/QMUI_iOS#620]
sample code:

```objc
UIButton *button = [[UIButton alloc] initWithFrame:CGRectMake(100, 100, 0, 0)];
button.backgroundColor = [UIColor redColor];
button.titleLabel.font = UIFontMake(13);
[button setImage:UIImageMake(@"icon_nav_about") forState:UIControlStateNormal];
[button setTitle:@"QMUIKit" forState:UIControlStateNormal];
[button sizeToFit];
[self.view addSubview:button];
```
Bold Text enabled:
![image](https://user-images.githubusercontent.com/16473618/59349609-a3ffec00-8d4c-11e9-9da2-5ba91624ded0.png)

Bold Text disabled:
![image](https://user-images.githubusercontent.com/16473618/59349571-8a5ea480-8d4c-11e9-9c94-355c148c722f.png)

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/commit/2f8dc48b1503836a82fce626583008796214857a
