### ISSUE TITLE
QMUILabel 开启 canPerformCopyAction 并设置背景色后，menu 消失后 label 的背景色也丢失了

### ISSUE THREAD

**Issue by iizvv** [Tencent/QMUI_iOS#623]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![Snip20190615_3](https://user-images.githubusercontent.com/15830996/59545431-a03cb700-8f50-11e9-8310-1959933bc72e.png)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现
![image](https://user-images.githubusercontent.com/15830996/59545449-d37f4600-8f50-11e9-87d9-a1fd3e00a012.png)

**其他信息**
 - 设备: [模拟器iPhone Xs]
 - iOS 版本: [iOS 12.2]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by MoLice** [comment]
下个版本将会修复该问题，在此之前请尝试先设置背景色再开启 `canPerformCopyAction`。
