### ISSUE TITLE
QMUITextView设置首行缩进，placeholderLabel也会首行缩进

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#624]
**Bug 表现**
QMUITextView设置首行缩进，placeholderLabel也会首行缩进

**截图**
![1560782986272](https://user-images.githubusercontent.com/22904757/59613854-3a1f8200-9152-11e9-8454-94a684b856f7.jpg)
查看源码发现：
![1560783042127](https://user-images.githubusercontent.com/22904757/59613945-5d4a3180-9152-11e9-8f25-780ec5ce5780.jpg)
设置placeholder时会把typingAttributes所有属性都设置上

**预期的表现**
placeholderLabel能够正常显示，不应该进行首行缩进

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 12.1]
 - Xcode 版本: [Xcode 10.1]
 - QMUI 版本: [3.1.9]

**Comment by MoLice** [comment]
这本来就是需求如此，placeholder 的样式是应该和真正的文本样式一致的，包括首行缩进，毕竟当你设置了首行缩进时，光标也是从缩进后的位置开始的，所以 QMUI 目前的处理是正确的。

![image](https://user-images.githubusercontent.com/1190261/59766577-16d01080-92d3-11e9-8964-9b0c43dfc98e.png)

如果仍需要修改，请覆盖 QMUI 的代码即可（不管是业务侧覆盖，还是继承重写 setPlaceholder）。
