### ISSUE TITLE
demo 里弹出框键盘文字布局出错了

### ISSUE THREAD

**Issue by Mujiete** [Tencent/QMUI_iOS#625]
**Bug 表现**
横屏下，弹出框的文字出现了错误，demo里发现

**截图**
![Simulator Screen Shot - iPhone 6s - 2019-06-18 at 09 38 00](https://user-images.githubusercontent.com/15193083/59647221-f60d9b00-91ac-11e9-8ba2-48642d46fb9f.png)
![Simulator Screen Shot - iPhone 6s - 2019-06-18 at 09 43 12](https://user-images.githubusercontent.com/15193083/59647370-85b34980-91ad-11e9-919d-f33453e19e88.png)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、横版，6s]
 - iOS 版本: [iOS 12.2]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]

**Comment by MoLice** [comment]
demo 里这个地方的布局没有考虑横屏，已修复，等新版本发布。

**Comment by MoLice** [comment]
已发布 [4.0.0-beta](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0-beta) 修复该问题。
