### ISSUE TITLE
QMUIMoreOperationController的contentEdgeMargin建议设计为UIEdgeInsets

### ISSUE THREAD

**Issue by provswin** [Tencent/QMUI_iOS#626]
**现存问题或期望目标**
我们在使用QMUIMoreOperationController时，因为设计师要求面板的各边距都有各自的值，不过现在在QMUIMoreOperationController中contentEdgeMargin是个CGFloat，这导致其中的QMUIModalPresentationViewController的contentViewMargins在UIEdgeInsetsMake时，上下左右始终都只能是等边距的一个效果。

期望能将contentEdgeMargin改为UIEdgeInsets类型的，可灵活控制上下左右边距

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/commit/c6ff2b2835fd22d797f69a888a0352f99f18c35a

下个版本将会带上。
