### ISSUE TITLE
键盘隐藏时，qmui_keyboardManager并不调用keyboardDidHideWithUserInfo:和keyboardDidChangeFrameWithUserInfo:代理方法

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#627]
**Bug 表现**
键盘隐藏时，TextField或TextView的qmui_keyboardManager并不调用keyboardDidHideWithUserInfo:和keyboardDidChangeFrameWithUserInfo:代理方法。
因为此时 QMUIKeyboardManager的currentResponder为nil，同时targetResponderValues.count > 0，shouldReceiveHideNotification方法返回了NO。
从而导致键盘收回时，qmui_keyboardDidHideNotificationBlock和qmui_keyboardDidChangeFrameNotificationBlock并不触发。
单独使用 QMUIKeyboardManager 时好像是没有这个问题的，只有集成在TextField或TextView中的QMUIKeyboardManager有问题。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.2.1]

**Comment by zhoon** [comment]
已修复，请留意下个版本更新。
