### ISSUE TITLE
[iOS 13] _UINavigationBarContentView change properties will cause a crash

### ISSUE THREAD

**Issue by zhoon** [Tencent/QMUI_iOS#628]
**Bug 表现**
修改 UINavigation 的私有 View `_UINavigationBarContentView ` 的属性会导致 crash

**截图**
![img](https://user-images.githubusercontent.com/2041356/59667688-b9ac6000-91e9-11e9-80f6-101e834eb4e5.png)

**其他信息**
 - iOS 版本: [iOS 13 beta2]
 - Xcode 版本: [Xcode 11 beta2]

**Comment by zhoon** [comment]
目前 QMUI 里面需要通过修改`_UINavigationBarContentView `的 directionalLayoutMargins 属性来设置自定义返回按钮的位置，以前是通过 hook `layoutSubviews` 然后设置 directionalLayoutMargins，所以在 iOS beta2 会导致上面的 crash。

目前临时的解决方案是去掉原本的 hook，改为 hook `UIView` directionalLayoutMargins 的 getter 方法，具体操作是下面的截图，有其他解决方案也欢迎跟我们留言。

![img2](https://user-images.githubusercontent.com/2041356/59668511-3724a000-91eb-11e9-8d9a-cbc381a688bf.png)

**Comment by mrsunx** [comment]
请问有swift的解决方案么

**Comment by jyuuchinen** [comment]
请问这种改法审核可以通过吗？

**Comment by MoLice** [comment]
> 请问这种改法审核可以通过吗？

@jyuuchinen 可以

**Comment by ywh-nova** [comment]
这个闪退问题好像又出现了
<img width="708" alt="屏幕快照 2019-09-21 下午5 56 13" src="https://user-images.githubusercontent.com/16153361/65371745-65f25c80-dc99-11e9-9d06-9d9e82b39b4f.png">
<img width="766" alt="屏幕快照 2019-09-21 下午5 50 13" src="https://user-images.githubusercontent.com/16153361/65371748-6db20100-dc99-11e9-9d63-7a98b3d5dd31.png">

iOS 版本13.0
Xcode版本11.0

**Comment by dalishenaly** [comment]
![Uploading image.png…]()

Assertion failure in -[_UINavigationBarContentView setDirectionalLayoutMargins:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.22.15/_UINavigationBarContentView.m:708

**Comment by dalishenaly** [comment]
Xocde 11
iOS 13
QMUIKit 升级到4.0.0-beta 同样会出现这个问题

**Comment by MoLice** [comment]
4.0.0-beta 版本里并不存在 `directionalLayoutMargins` 的代码，理论上不可能再出现这个问题，请先自行排查，例如 clean 项目，如仍有问题，请新建 issue 并提供 Demo 以供测试。

![image](https://user-images.githubusercontent.com/1190261/65688855-60808200-e09e-11e9-8124-74d2e25eb207.png)

**Comment by shushulele** [comment]
con't solve my question!!!

**Comment by shushulele** [comment]
你们都不报错吗？源码照搬进去，根本跑不起来！！！

**Comment by shushulele** [comment]
<img width="732" alt="截屏2019-10-12下午6 56 25" src="https://user-images.githubusercontent.com/7588029/66700368-0b8d6e80-ed22-11e9-9e02-6ff8b4738b7a.png">

**Comment by MoLice** [comment]
@shushulele 你是基于 QMUI 的哪个版本去修改？

**Comment by shushulele** [comment]
@MoLice 基于2.9.3，刚刚升级到4.0.0，已经解决了，谢谢

**Comment by MoLice** [comment]
这么大的版本号变化，不仅你复制的那段代码改了，连 OverrideImplementation 这个函数的实现也已经改了，所以你直接复制过去，运行不起来是很正常的，QMUI 通常也不会处理因不规范使用而引发的问题。

**Comment by AgoniNemo** [comment]
```
Xode 12
iOS 9.0
pod 'QMUIKit','3.2.1'
```
以上环境crash

不是很想改源码 ，能不能更新下3.2.1的版本？

**Comment by MoLice** [comment]
> ```
> Xode 12
> iOS 9.0
> pod 'QMUIKit','3.2.1'
> ```
> 
> 以上环境crash
> 
> 不是很想改源码 ，能不能更新下3.2.1的版本？

项目是开源的，请自行处理。
