### ISSUE TITLE
特定情况下 pop 手势返回过程中，上个界面 NavigationBar 被隐藏

### ISSUE THREAD

**Issue by ziecho** [Tencent/QMUI_iOS#629]
**Bug 表现**
从QDNavigationBarScrollingAnimatorViewController 返回到上个界面的过程中，NavigationBar 被隐藏

**截图**
![WX20190619-145945](https://user-images.githubusercontent.com/16473618/59743523-ec665f00-92a2-11e9-91aa-e1603306c226.png)

**如何重现**
1. 进入 QDNavigationBarScrollingAnimatorViewController，滚动一段距离至导航栏显示为蓝色
2. 触发 pop 手势，并释放取消  pop 手势
3. 滚动到顶部，此时导航栏显示为透明
4. 再次触发 pop 手势上个界面导航栏被隐藏

**预期的表现**
不影响上个界面的导航栏

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [3.2.1]

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
