### ISSUE TITLE
从QMUI2.xx升级到3.1.8报错

### ISSUE THREAD

**Issue by tangbing** [Tencent/QMUI_iOS#630]
**Bug 表现**
问题的具体描述

从QMUI2.xx升级到3.1.8报错：项目报错

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

<img width="607" alt="image" src="https://user-images.githubusercontent.com/11678386/59750059-c8aa1580-92b0-11e9-87f3-93c46dc3ffd9.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/11678386/59750295-2d657000-92b1-11e9-9373-03385b101e20.png">

<img width="1157" alt="QQ20190619-163632@2x" src="https://user-images.githubusercontent.com/11678386/59749925-8254b680-92b0-11e9-9726-ed4ca374d259.png">

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.1.8]

**Comment by MoLice** [comment]
QMUI 更新频繁，每个版本更新均带有较多接口、类的命名变动，适配方法也有写在 Release Note 里了，请参照 https://github.com/Tencent/QMUI_iOS/releases 。

更新前先阅读 Release Note 知悉更新必做的操作、避免大跨度的版本变动，这是使用每个开源框架的基本常识。
