### ISSUE TITLE
[UIAlertController supportedInterfaceOrientations] was invoked recursively

### ISSUE THREAD

**Issue by iamlion** [Tencent/QMUI_iOS#632]
**Bug 表现**
在“QMUITabBarViewController”这个控制器上弹出一个系统的“UIAlertController”，控制台开始打印错误信息“ERROR: -[UIAlertController supportedInterfaceOrientations] was invoked recursively! Instead of using presentingViewController = <QMUITabBarViewController: 0x10180ae00>”，打印差不多10次，App并没有崩溃。

UIAlertController 会调用 [parentViewController supportedInterfaceOrientations] 的方法，按照修复代码的逻辑，应该会形成递归调用。

**截图**
复现代码：
<img src="https://images-cdn.shimo.im/MplnpF9dkIYchsjp/image.png__thumbnail" />
错误信息：
<img src="https://images-cdn.shimo.im/oZqYiEKIapg8Atxy__thumbnail" />

**如何重现**
1. 创建一个QMUITabBarViewController为window的rootViewController
2. 大约5秒后弹出一个 UIAlertController，即可复现错误

**预期的表现**
控制台应该无明显错误信息提示

**其他信息**
 - 设备: iPhone 真机
 - iOS 版本: iOS 12.3.1
 - Xcode 版本: Xcode 10.13.6
 - QMUI 版本: 3.2.1

**Comment by passerbyloo** [comment]
@MoLice should also override the `UIAlertController (supportedInterfaceOrientations)`

I try below code can fix the warning
```
@implementation UIAlertController (supportedInterfaceOrientations)

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskAll;
}

@end
```

**Comment by MoLice** [comment]
曾经在[这个 issue](https://github.com/Tencent/QMUI_iOS/issues/502) 里改过，避免了 crash，然而当初没有留意到 log，已修复，等新版本发布。

**Comment by MoLice** [comment]
已发布 [4.0.0-beta](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0-beta) 修复该问题。
