### ISSUE TITLE
NavigationBarHeight、TabBarHeight、ToolBarHeight 在某些设备下不准确

### ISSUE THREAD

**Issue by ziecho** [Tencent/QMUI_iOS#633]
目前测试异常的设备有：

```objc
非全面屏 iPad, iOS 11 
QMUI TabBarHeight  50 vs System TabBarHeight 49
QMUI ToolBarHeight 50 vs System ToolBarHeight 44

全面屏  iPad 
QMUI NavigationBarHeight 50 vs System NavigationBarHeigh 44 

iPhone XS Max，横屏
QMUI TabBarHeight 53 vs System TabBarHeight 70
QMUI ToolBarHeight 83 vs System ToolBarHeight 65
```

**Comment by ziecho** [comment]
这里整理下系统常见 UI 控件在各个系统、设备下的高度规则

**safeAreaInsetsBottom**
iPhone 竖屏 34
iPhone 横屏 21
iPad 20

**StatusBarHeight**
非全面屏 iPhone 20
全面屏 iPhone  44
非全面屏 iPad 20
全面屏 iPad  24

**NavigationBarHeight**
iPhone 竖屏 44
iPhone 横屏 Regular  44  or Compact 32
iPad  iOS >=12 ? 50 : 44 

**TabBarHeight**
非全面屏 iPhone 竖屏    49
非全面屏 iPhone 横屏   49 
全面屏 iPhone 竖屏   49   + safeAreaBottom = 83
全面屏 iPhone 横屏  (Regular  49  or Compact  32)  + safeAreaBottom
非全面屏 iPad iOS >= 12 ? 50 : 49
全面屏 iPad 为 45 + safeAreaBottom = 65 （横竖屏一致）

ToolBarHeight
非全面屏iPhone 竖屏 非全面屏 44
非全面屏iPhone 横屏  非全面屏 Regular 44 or Compact 32
全面屏 iPhone 竖屏  44 + safeAreaBottom
全面屏 iPhone 横屏   (Regular 44 or Compact 32) + safeAreaBottom
非全面屏  iPad  iOS >=12 ? 50 : 44
全面屏     iPad   45 + 20 = 65

**Comment by MoLice** [comment]
已发布 [4.0.0-beta](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0-beta) 修复该问题。
