### ISSUE TITLE
YBImageBrowser会导致页面侧滑失效，点击返回按钮无动画

### ISSUE THREAD

**Issue by hkjin** [Tencent/QMUI_iOS#634]
**Bug 表现**
侧滑手势使用forceEnableInteractivePopGestureRecognizer reture true
在使用YBImageBrowser浏览图片后，会导致手势侧滑失效，并且点击返回按钮，没有动画，底部的tabbar也会看到黑色，透明导航返回还会出现，黑色导航块的问题。
使用的是  QMUICommonViewController 和 QMUICommonTableViewController
tabbar使用的是  QMUITabBarViewController

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 12.1.4]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by hkjin** [comment]
应该说YBImageBrowser会让QMUI的所有效果消失。不管是导航的处理，还是tabbar的处理，页面的跳转，都会出现问题。

**Comment by MoLice** [comment]
请提供 demo。
