### ISSUE TITLE
两个QMUITip层叠一起且错位

### ISSUE THREAD

**Issue by SuAdrenine** [Tencent/QMUI_iOS#637]
**Bug 表现**
有个递归的网络请求，请求成功使用QMUITip显示success信息，出现两个QMUITip层叠一起

**截图**

<img width="712" alt="D83144B3-712D-4DFF-A4FE-703945CFEB38" src="https://user-images.githubusercontent.com/13587388/60079277-2aaac500-9760-11e9-9f8a-bbdf1a382ab5.png">

<img width="699" alt="FB52225D-2532-479C-B0A5-B615F89C7624" src="https://user-images.githubusercontent.com/13587388/60079298-3a2a0e00-9760-11e9-9ebb-22099cbbfdff.png">

**如何重现**
1. 串行的网络请求，成功之后显示QMUITips成功提示，并开始下一个请求，且成功也显示成功提示

**预期的表现**
只有一个QMUITip实例，或者上面的实例能挡住下面的实例，且俩实例都正常显示

**其他信息**
 - 设备: iPhoneXR
 - iOS 版本: [iOS 12.3]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by zhoon** [comment]
同时存在两个 QMUITips 是你需求的预期表现？tips是半透明的，如果两个叠在一起可能会看到下面的tips把？除非设置为全透明？但是如果是全透明，那么下面那个tips也没必要显示？第二个要显示的时候，直接hideAllTips就好了。

--------------------
两个Tiops同时存在的时候有一个会错位，我看看能不能重现。

**Comment by zhoon** [comment]
@SuAdrenine 简单试了一下弹两个 Tips，并没有出现你那个问题，能否提供一个简单的 demo 给我调试？

或者确认一下你的 Tips 是不是在主线程弹出来的？如果是子线程可能会有问题哦。

**Comment by SuAdrenine** [comment]
@zhoon 预期是不会像图1中那样，让用户看到左上角有一个对勾且中间也有一个勾，而是应该像正常一样，只在中间出现，不管你有几个实例，但是用户同一时间看到的应该只有一个，图一是左上角显示一个，中间显示一个，这是不合理的预期，工程里面出现的，没有demo，tips是在主线程调用的，不是在子线程

**Comment by zhoon** [comment]
@SuAdrenine 或者你贴一些会出现问题可运行的代码片段，我按你的描述弹两个 tips 是不会出现这个问题的。

**Comment by MoLice** [comment]
> @zhoon 预期是不会像图1中那样，让用户看到左上角有一个对勾且中间也有一个勾，而是应该像正常一样，只在中间出现，不管你有几个实例，但是用户同一时间看到的应该只有一个，图一是左上角显示一个，中间显示一个，这是不合理的预期，工程里面出现的，没有demo，tips是在主线程调用的，不是在子线程

@SuAdrenine 明白你说的错误场景是什么表现，现在的关键是，需要有个能复现问题的代码，否则是无法查出来什么原因的，请提供 Demo。

**Comment by Vanson** [comment]
@SuAdrenine 再展示后一个Tips前不是需要调用[QMUITips hideAllTips];隐藏前一个Tips么？

**Comment by SuAdrenine** [comment]
@Vanson 好吧，那就是我没隐藏的问题
