### ISSUE TITLE
QMUIModalPresentationViewController当contentView使用Autolayout布局

### ISSUE THREAD

**Issue by SmallMX** [Tencent/QMUI_iOS#638]
**Bug 表现**
问题的具体描述
QMUIModalPresentationViewController当contentView使用Autolayout布局，设置layoutBlock从底部向上弹出，在点击背景收回时，弹窗会瞬间弹到顶部
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
将Demo中layoutBlock模式下的contentView使用Autolayout布局

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]

**Comment by MoLice** [comment]
`layoutBlock` 里设置 `contentView` 的 `frame` 时需要用 `qmui_frameApplyTransform` 修改 `frame`，因为内部会对 `contentView` 使用 transform。

![image](https://user-images.githubusercontent.com/1190261/62864563-a11a7b00-bd3e-11e9-92e6-16b50342437d.png)

![image](https://user-images.githubusercontent.com/1190261/62864602-c27b6700-bd3e-11e9-8908-005266b9f447.png)

如果你使用 Autolayout 的方式去布局 contentView，无法使用 `qmui_frameApplyTransform` 的话，目前暂时是没办法解决这个问题的。

或者可以提供一个 Demo 或示例代码我们看看。

**Comment by lztbwlkj** [comment]
不知兼不兼容[https://github.com/zhenglibao/FlexLib](FlexLib)这种布局
