### ISSUE TITLE
- (void)copyString:(id)sender  建议将 QMUILabel 中的这个方法添加到.h文件中

### ISSUE THREAD

**Issue by azureplus** [Tencent/QMUI_iOS#640]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。
- (void)copyString:(id)sender  建议将 QMUILabel 中的这个方法添加到.h文件中
方便我们中做这个的扩展

**Comment by zhoon** [comment]
具体说明一下使用场景。
QMUILabel 里面有个额 didCopyBlock，应该可以做一些扩展了。

**Comment by azureplus** [comment]
用这个方式也可以满足我的需求了，
