### ISSUE TITLE
能否增加 apple music vc 的展示方式

### ISSUE THREAD

**Issue by azureplus** [Tencent/QMUI_iOS#641]
能否增加 apple music vc 的展示方式

**Comment by zhoon** [comment]
能否说详细一点具体怎样的展示方式？或者截图看一下。

**Comment by azureplus** [comment]
> 能否说详细一点具体怎样的展示方式？或者截图看一下。
类似这种，这种方式应该非常流行了，如果咱们的QMUI 也支持，就不用导入其他框架了，谢谢
![IMG_5E094D3EACF7-1](https://user-images.githubusercontent.com/9008164/60345319-57bed800-99eb-11e9-86d8-676f81b35a14.jpeg)

**Comment by zhoon** [comment]
iOS 13 现在系统 present vc 默认就是这种方式了，你可以体验体验。
