### ISSUE TITLE
在tabbar的子控制器中使用customNavigationBarTransitionKey 无效，

### ISSUE THREAD

**Issue by xhjss** [Tencent/QMUI_iOS#642]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]

**Comment by ziecho** [comment]
建议提供相关 Demo

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
