### ISSUE TITLE
iOS 13 使用QMUISearchController点击搜索框crash

### ISSUE THREAD

**Issue by xx752690102** [Tencent/QMUI_iOS#643]
iOS 13 使用QMUICommonTableViewController集成的QMUICommonTableViewController
问题一：
 点击搜索框crash
问题二：
将searchbar设置成导航栏的titleView 显示成了一条线
问题一截图：
![image](https://user-images.githubusercontent.com/13724801/60315538-7eecb980-9999-11e9-9f18-a98b02322fb8.png)
![image](https://user-images.githubusercontent.com/13724801/60315548-87dd8b00-9999-11e9-8e23-a67b6cd61a87.png)

问题二截图：
![image](https://user-images.githubusercontent.com/13724801/60315491-5bc20a00-9999-11e9-9824-44dfd951228e.png)

 - 设备:iPhoneX
 - iOS 版本: iOS 13
 - Xcode 版本: Xcode 11.0 BETA
 - QMUI 版本: 3.2.1

**Comment by ziecho** [comment]
问题一：已经解决，如果你是 pod 引入，建议等待我们发布版本，或者参考 [UISearchBar+QMUI.m](https://github.com/Tencent/QMUI_iOS/blob/a2952b9a0cf04803d60c474f7576b629c0acc55d/QMUIKit/UIKitExtensions/UISearchBar%2BQMUI.m) 手动修改。
问题二：测试无法复现你的情况，建议提供相关 Demo 或者代码：
![image](https://user-images.githubusercontent.com/16473618/60893462-8c584c80-a293-11e9-9f58-3f3e659ebb8a.png)

**Comment by xx752690102** [comment]
你好，定位到问题所在了。设置如下代码，会导致问题二出现，
  self.searchBar.qmui_textField.background = [UIImage imageWithColor:UIColorMakeWithHex(@"#A792EF")];

**Comment by MoLice** [comment]
> 你好，定位到问题所在了。设置如下代码，会导致问题二出现，
> self.searchBar.qmui_textField.background = [UIImage imageWithColor:UIColorMakeWithHex(@"#A792EF")];

这个问题与 QMUI 无关，阅读 UISearchBar.h 头文件即可知道，UISearchBar 的输入框背景有专门的方法去设置：`setSearchFieldBackgroundImage:forState:`。自己通过获取内部的 `textField` 去修改 `background` 图片后出现非预期的效果，这本身就是符合预期的。

```Objective-C
[searchController.searchBar setSearchFieldBackgroundImage:[UIImage qmui_imageWithColor:UIColorRed size:CGSizeMake(36, 36) cornerRadius:0] forState:UIControlStateNormal];
```

**Comment by MoLice** [comment]
已发布 [4.0.0-beta](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0-beta) 修复该问题。
