### ISSUE TITLE
iOS 13 Attempt to mutate immutable object with deleteCharactersInRange:  CoreFoundation + 1223152

### ISSUE THREAD

**Issue by JarvisHot** [Tencent/QMUI_iOS#644]
**Bug 表现**
闪退

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
app插线真机调试的时候不崩溃，手动启动的时候崩溃在这个地方，删除QMUIKit 不报这个错误，查了很多资料，有可能是重写的 description 方法引起的，麻烦定位一下

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone6sPlus]
 - iOS 版本: [iOS 13]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by ziecho** [comment]
这个问题已经在 [supports iOS 13](https://github.com/Tencent/QMUI_iOS/commit/a2952b9a0cf04803d60c474f7576b629c0acc55d) 这个 commit 解决，目前还未正式发布 QMUI 新版本，如果你是 pod 引入，请手动完成以下代码修改：

![image](https://user-images.githubusercontent.com/16473618/60891848-b0665e80-a290-11e9-8ee5-1ac1279eb0b1.png)

**Comment by MoLice** [comment]
已发布 [4.0.0-beta](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0-beta) 修复该问题。
