### ISSUE TITLE
使用hidesBottomBarWhenPushedInitially会导致Tabbar不显示

### ISSUE THREAD

**Issue by hkjin** [Tencent/QMUI_iOS#648]
**Bug 表现**
问题的具体描述

场景：IM在另一个手机登录，该手机需要自动回到首页并弹出登录页面，登陆后，QMUITabBarViewController的tabbar再也不显示了，就算是切换到二级页面，再返回显示一下就又消失了。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码
在 class JOINTabBarViewController: QMUITabBarViewController 的viewDidLoad中
`QMUIConfiguration.sharedInstance()?.hidesBottomBarWhenPushedInitially = true`
控制器设置：
![image](https://user-images.githubusercontent.com/17734586/60781227-16a98f00-a174-11e9-9dfe-52e9b2bdb568.png)
退出到首页的代码：
![image](https://user-images.githubusercontent.com/17734586/60781427-fdeda900-a174-11e9-91db-889ffc2a72f3.png)

手机显示错误的效果：
![IMG_0105](https://user-images.githubusercontent.com/17734586/60781461-2f667480-a175-11e9-80ee-532913b71deb.jpg)

**预期的表现**
正常显示tabbar

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 12.1.4]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by hkjin** [comment]
效果gif:
[https://share.weiyun.com/5h89UyN](url)

**Comment by MoLice** [comment]
请将问题描述剥离掉业务信息，单纯只用代码的方式去描述你的问题，或者直接提供一个可复现问题的 Demo 后重新 open issue。目前的描述无法让我们有效排查问题。
