### ISSUE TITLE
尝试让一个处于非 keyWindow 上的 QMUITextField becomeFirstResponder

### ISSUE THREAD

**Issue by nenseso** [Tencent/QMUI_iOS#649]
**Bug 表现**
为alertController添加一个textField报警告
                let alertC = QMUIAlertController(title: "Creat New Playlist", message: "Input your new playlist name.", preferredStyle: .alert)
                alertC.addTextField(configurationHandler: nil)
                let textFiled = alertC.textFields!.first!
                textFiled.placeholder = "Input"
                alertC.addAction(QMUIAlertAction(title: "Cancel", style: .cancel, handler: nil))
                alertC.addAction(QMUIAlertAction(title: "OK", style: .default, handler: { (_, _) in
                }))
                alertC.showWith(animated: true)

QMUISymbolicUIViewBecomeFirstResponderWithoutKeyWindow]:360 | QMUILogLevelWarn | UIView (QMUI) | 尝试让一个处于非 keyWindow 上的 QMUITextField becomeFirstResponder，可能导致界面显示异常，请添加 'QMUISymbolicUIViewBecomeFirstResponderWithoutKeyWindow' 的 Symbolic Breakpoint **以捕捉此类信息**
经测试在官方的Demo上仍旧有此报错信息
        QMUIAlertAction *action1 = [QMUIAlertAction actionWithTitle:@"取消" style:QMUIAlertActionStyleCancel handler:NULL];
        QMUIAlertAction *action2 = [QMUIAlertAction actionWithTitle:@"删除" style:QMUIAlertActionStyleDestructive handler:NULL];
        QMUIAlertController *alertController = [QMUIAlertController alertControllerWithTitle:@"确定删除？" message:@"删除后将无法恢复，请慎重考虑" preferredStyle:QMUIAlertControllerStyleAlert];
        [alertController addAction:action1];
        [alertController addAction:action2];
        // 添加textField
        [alertController addTextFieldWithConfigurationHandler:nil];
        [alertController showWithAnimated:YES];

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
