### ISSUE TITLE
[iOS 13] iPad 分屏的时候，键盘 endFrame 错误

### ISSUE THREAD

**Issue by zhoon** [Tencent/QMUI_iOS#650]
**Bug 表现**
iOS 13 iPad 分屏的时候，如果目标 APP 处于分屏的右边，那么当收到键盘通知的时候，endFrame 的 x 是偏移的而不是 0，但是 width 确是整个键盘的宽度，目前还不清楚是系统的 BUG 还是故意这样做，想不到这样做的理由，所以等后面的 beta 版本再观察观察。

**导致的问题**
因为 x 是偏移的所以导致 QMUIKeyboardManager 里面某些场景通过 height 或者 heightInView: 获取到的高度是错误的。

**临时修复**
对于上面所说的情况，目前临时通过修改 x 的值来修复，如下图：
![image](https://user-images.githubusercontent.com/2041356/60807933-a32a7080-a1b9-11e9-8181-226c6af9c4ed.png)

**其他信息**
 - 设备: [iPad 分屏]
 - iOS 版本: [iOS 13]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [3.2.1]

**Comment by zhoon** [comment]
此问题 iOS 13 beta 4 依然存在

**Comment by MoLice** [comment]
已发布 [4.0.0-beta](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0-beta) 修复该问题。
