### ISSUE TITLE
[iOS 13] 第一次弹起键盘的时候，会收到 UIApplicationWillChangeStatusBarOrientationNotification 通知

### ISSUE THREAD

**Issue by zhoon** [Tencent/QMUI_iOS#651]
**Bug 表现**
在 iOS 13 beta 版本中，我们发现只要是打开 APP 并且第一次弹起键盘的时候，系统会发出 `UIApplicationWillChangeStatusBarOrientationNotification` 和 `UIApplicationDidChangeStatusBarOrientationNotification` 通知，目前暂不确定这是系统的 feature 还是 bug。

另外，`UIApplicationWillChangeStatusBarOrientationNotification` 和 `UIApplicationDidChangeStatusBarOrientationNotification` 等系列接口在 iOS 13 已经被移除了，系统建议使用 `viewWillTransitionToSize:withTransitionCoordinator:` 来代替。

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [3.2.1]

**Comment by zhoon** [comment]
键盘的 window 在初始化之后 setRootViewControoler 的时候会去 update rotation，这个过程会发送  `UIApplicationWillChangeStatusBarOrientationNotification` 和 `UIApplicationDidChangeStatusBarOrientationNotification` 通知，之所以只有第一次会，是因为全局的键盘只初始化一次，即使后面看不到，window 的对象还是存在的，只是看不见而已。

另外，我们自己的 window 初始化是不会触发这个行为的，目前只发现键盘的那个 window 会。

**Comment by zhoon** [comment]
此问题在 iOS 13 beta 4 依然存在

**Comment by MoLice** [comment]
已发布 [4.0.0-beta](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0-beta) 修复该问题。
