### ISSUE TITLE
iOS 13 tabbar不显示未选中状态颜色

### ISSUE THREAD

**Issue by Karthus1110** [Tencent/QMUI_iOS#653]
**Bug 表现**
设置了QMUICMI.tabBarTintColor = kCommonBlackColor; 以后不显示未选中状态下的图标颜色

**截图**
![image](https://user-images.githubusercontent.com/13864988/60952229-75fecf00-a32d-11e9-8125-39d1bd19aed6.png)
![image](https://user-images.githubusercontent.com/13864988/60952256-831bbe00-a32d-11e9-8d24-112279c4eef1.png)

**如何重现**
1. ...
2. ...

**预期的表现**
以下是在iOS12下表现正常
![FullSizeRender](https://user-images.githubusercontent.com/13864988/60952489-f1608080-a32d-11e9-96cc-58dec0e37cdf.jpg)

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: iOS 13
 - Xcode 版本: Xcode 11 beta 2
 - QMUI 版本: 最新

**Comment by fanyuecheng** [comment]
barTintColor 是 bar's background.你这个不该是自备unselected的image吗？==！

**Comment by MoLice** [comment]
这是 iOS 13 UITabBarItem.image.renderingMode 的差异导致的，同样都是 `UIImageRenderingModeAutomatic`，在 iOS 12 及以前，UITabBarItem 会将图片以 `UIImageRenderingModeAlwaysTemplate` 去渲染，所以就算你的图片颜色是黑色，实际展示出来的未选中的状态，依然是灰色（这个灰色由 UITabBar 控制）。但在 iOS 13，UITabBarItem 会将图片以 `UIImageRenderingModeAlwaysOriginal` 去显示，所以你看到的后两个图片是黑色，是因为你的图片本来就是黑色，它只是展示了原图。

于是可以知道，解决方法就是两个：
1. 要么你把三张图的原图都改为灰色。
2. 要么你在设置图片时，用 `[image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate]`。

**Comment by Karthus1110** [comment]
两个方法都没有效果..我的图片设置如下，有selected状态和normal状态图片，我全部改为灰色的normal图片和修改渲染模式都没有效果
![image](https://user-images.githubusercontent.com/13864988/61206851-2dc51f80-a726-11e9-91d2-ed02290ba296.png)

**Comment by MoLice** [comment]
请提供 Demo。

**Comment by Karthus1110** [comment]
同时设置了selectedImage和normalImage的情况下，将两个图片的渲染模式都改为UIImageRenderingModeAlwaysOriginal即可，感谢解惑

**Comment by xieweilyg** [comment]
> 同时设置了selectedImage和normalImage的情况下，将两个图片的渲染模式都改为UIImageRenderingModeAlwaysOriginal即可，感谢解惑

iOS13上这个切图没有填充就显示正常了；你可以检查一下切图，应该是有个白色的填充才会这样的~
