### ISSUE TITLE
导航转场时，返回按钮文字的颜色改变

### ISSUE THREAD

**Issue by RomanticEncounter** [Tencent/QMUI_iOS#654]
**Bug 表现**
问题的具体描述
配置表开启
`QMUICMI.needsBackBarButtonItemTitle = YES;`
导航栏`navigationBarTintColor`颜色由浅转深，返回按钮的文字会立刻设置为深色

**截图**
![image](https://user-images.githubusercontent.com/16411177/61040696-add84600-a403-11e9-82a7-17fb67c25221.png)

**如何重现**
1. 配置表中开启`QMUICMI.needsBackBarButtonItemTitle = YES;` 当前viewController的`navigationBarTintColor`设置为浅色，下跳ViewController的`navigationBarTintColor`设置为深色（例如：黑色）
`- (UIColor *)navigationBarTintColor {
    return UIColorBlack;
}`
2. 点击跳转即可复现，返回按钮颜色更改可以根据指示器颜色更改效果保持一致

**预期的表现**
正常情况下，返回按钮颜色更改和指示器颜色更改效果保持一致

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by zhoon** [comment]
确实有这个问题，想想怎么改

**Comment by ziecho** [comment]
这个问题出现在 iOS 11 之后，下个版本我们会兼容。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
