### ISSUE TITLE
隐藏导航栏

### ISSUE THREAD

**Issue by hzw87383197** [Tencent/QMUI_iOS#655]
![image](https://user-images.githubusercontent.com/23348895/61200118-fd27ba80-a712-11e9-83ac-e7dc7267b55e.png)

从A控制器到B控制器,想再B控制器隐藏导航栏,可是不成,还是现实导航栏

**Comment by hzw87383197** [comment]
已经写了这2个方法,也在走了这2个方法,但是就是还能显示

**Comment by MoLice** [comment]
给你提供几个排查的思路：
1. 如果你提的问题，在别的地方（例如官方 Demo）正常，但就在你的这里不正常，那请提供一份 Demo，不然换做是你收到这个问题，按目前提供的信息量，你是不是也无从查起？
2. QMUI 是开源的，搜索一下源码就能知道这个方法如果要生效，它应该是被谁调用，一路查过去就能知道是哪里出问题。
![image](https://user-images.githubusercontent.com/1190261/61203489-1170b500-a71d-11e9-9a13-30d7e224c9c3.png)
3. UINavigationBar 显示与否的本质就是 hidden 属性的值，而根据 UIKit 提供的接口，只有两种方式可以控制导航栏的 hidden：`[UINavigationBar setHidden:NO]`、[UINavigationController setNavigationBarHidden:NO]`，于是直接重写这两个方法，或者利用 QMUI 提供的 swizzle 工具去重写，就能知道最终被谁修改了。
![image](https://user-images.githubusercontent.com/1190261/61203617-788e6980-a71d-11e9-9010-0c7bbd4ffc8a.png)

**Comment by hzw87383197** [comment]
谢谢,大神提点,我尝试按照您的方法进行排查

**Comment by hzw87383197** [comment]
谢谢,大神提点,我尝试按照您的方法进行排查

**Comment by hzw87383197** [comment]
# pod 'FDFullscreenPopGesture' 
终于找到了,这段话留给下一个小伙伴吧,如果同时导入了FDFullscreenPopGesture这个库,那么会与QMUIKit冲突,导致QMUIKit无效,需要把FDFullscreenPopGesture注释掉

**Comment by MoLice** [comment]
#275

**Comment by ZYHB** [comment]
> # pod 'FDFullscreenPopGesture'
> 
> 终于找到了,这段话留给下一个小伙伴吧,如果同时导入了FDFullscreenPopGesture这个库,那么会与QMUIKit冲突,导致QMUIKit无效,需要把FDFullscreenPopGesture注释掉
的确是这个原因。
