### ISSUE TITLE
'UIView+QMUITheme.h' file not found

### ISSUE THREAD

**Issue by azureplus** [Tencent/QMUI_iOS#656]
#ifndef QMUITheme_h
#define QMUITheme_h

#import "QMUIThemeManager.h"
#import "UIColor+QMUITheme.h"
#import "UIView+QMUITheme.h"

#endif /* QMUITheme_h */

carthage 导入的包，就出现了这个问题

需要注释掉 这个 #import "UIView+QMUITheme.h" 才可以

**Comment by zhoon** [comment]
开发版，暂未支持好
