### ISSUE TITLE
官网进不去了？？

### ISSUE THREAD

**Issue by KitsGithub** [Tencent/QMUI_iOS#657]
**Bug 表现**
https://qmuiteam.com/ios 无法访问啊

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="694" alt="企业微信截图_a1aa6ca2-0ded-4901-8faa-73fc77863874" src="https://user-images.githubusercontent.com/20672619/61365197-e2dc1100-a8b9-11e9-9609-01812266ce40.png">

**预期的表现**
能正常打开

**其他信息**
 - 设备: iMac
 - 版本: [iOS 10.14.5]

**Comment by MoLice** [comment]
已回复，感谢反馈。
