### ISSUE TITLE
[iOS 13] UIMenuController's window changed in iOS 13

### ISSUE THREAD

**Issue by zhoon** [Tencent/QMUI_iOS#659]
**Bug 表现**
iOS 12 及以前的版本，系统 keyboard 和 UIMenuController 是各自有一个 UITextEffectsWindow 来承载，并且 UIMenuController 所在的 UITextEffectsWindow 的 windowLevel 为 2100，如下图：

![image](https://user-images.githubusercontent.com/2041356/61522739-886fbb80-aa45-11e9-8049-fcf70d822685.png)

但是在 iOS 13 中，发现 UIMenuController 并没有单独持有一个 UITextEffectsWindow 了，而是与 keyboard 共用一个 UITextEffectsWindow，键盘没出现时的 windowLevel 为 10，键盘出现后 windowLevel 为 1，都远低于原本的 2100，所以当其他 window 的 level 比 1 或者 10 高，UIMenuController 就会被挡住。

![image](https://user-images.githubusercontent.com/2041356/61522893-e00e2700-aa45-11e9-9202-ee2f6ec26c5e.png)

![image](https://user-images.githubusercontent.com/2041356/61522900-e2708100-aa45-11e9-8b50-9422f5e297b0.png)

**预期的表现**
如果真的要跟 keyboard 共用一个 UITextEffectsWindow，那应该在显示 UIMenuController 的时候，把 windowLevel 改成 2100 或者其他比较大的数值，否则很容易被盖住。

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13 beta 4]
 - Xcode 版本: [Xcode 11 beta 4]
 - QMUI 版本: [3.2.1]

**Comment by zhoon** [comment]
进一步发现，只有当界面存在键盘的同时，显示 UIMenuController 的时候才会去修改所在 UITextEffectsWindow 的 windowLevel，修改的值为当前弹起键盘所在 view.window 的 windowLevel + 1，所以这个 BUG 的范围缩小到如果当前界面没有键盘，那么 UIMenuController 所在的 window 的 windowLevel 就是错的。

**Comment by zhoon** [comment]
目前的解决方案是 hook UIMenuController 的 sharedMenuController 方法，然后会在里面注册 menu 显示和隐藏的通知，然后在显示通知里面去判断如果当前没有键盘显示，并且找到当前 isFristResponder 所在的那个 window 的 windowLevel 加上 1 并且赋值给 UIMenuController 所在的 window，隐藏 menu 的通知里面再恢复。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
