### ISSUE TITLE
UINavigationBar(QMUINavigationButton)强制修改 contentView边界崩溃

### ISSUE THREAD

**Issue by UXIUME** [Tencent/QMUI_iOS#661]
**Bug 表现**
项目打不开就崩溃了

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="1135" alt="WX20190722-171744@2x" src="https://user-images.githubusercontent.com/38536031/61621040-af77f880-aca4-11e9-9e08-8c4fab86766b.png">

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [3.x.x]最新版本

**Comment by MoLice** [comment]
重复issue，请参考 #628，更新 4.0.0-beta 版本即可修复。
