### ISSUE TITLE
QMUIModalPresentationViewController 类里layoutBlock 是如何改变弹出视图的大小的，我不知道这是不是一个bug，如我我理解错了，sorry

### ISSUE THREAD

**Issue by huofuyan** [Tencent/QMUI_iOS#662]
**Bug 表现**
当用window 弹出视图时，使用layoutBlock 无法更改弹出视图的frame 

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]

**Comment by MoLice** [comment]
当你遇到与预期不符的表现时，首先请阅读注释，然后查看 QMUI Demo 的写法，如果仍有问题，请贴出你的具体代码或提供 Demo，不然单纯依靠目前的信息，是无法查出问题的。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
