### ISSUE TITLE
QMUIMutipleDelegates 无法正确响应 conformsToProtocol:

### ISSUE THREAD

**Issue by xhjss** [Tencent/QMUI_iOS#663]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]

**Comment by MoLice** [comment]
请尊重开源框架维护者的效率，如果与第三方框架有兼容问题，至少应该贴出具体的报错信息或代码，或者 Demo，我们才能去判断是否有需要去兼容它。不然我们是不可能会去自己接入一个 CHTCollectionViewWaterfallLayout 再去寻找你说的”提示“到底是什么提示。

**Comment by xhjss** [comment]
[test.zip](https://github.com/Tencent/QMUI_iOS/files/3417486/test.zip)
你好，看看demo

**Comment by xhjss** [comment]
还有就是，如果协议没实现问题解决了，还有个就是把header的高度打开，也会崩溃

**Comment by MoLice** [comment]
命中没有实现协议的断言的问题，是 QMUIMultipleDelegates 的问题，下个版本将会修复，在此之前可将以下代码添加到 QMUIMultipleDelegates 的实现里：

```Objective-C
- (BOOL)isKindOfClass:(Class)aClass {
    BOOL result = [super isKindOfClass:aClass];
    if (result) return YES;
    
    NSPointerArray *delegates = [self.delegates copy];
    for (id delegate in delegates) {
        if ([delegate isKindOfClass:aClass]) return YES;
    }
    
    return NO;
}

- (BOOL)isMemberOfClass:(Class)aClass {
    BOOL result = [super isMemberOfClass:aClass];
    if (result) return YES;
    
    NSPointerArray *delegates = [self.delegates copy];
    for (id delegate in delegates) {
        if ([delegate isMemberOfClass:aClass]) return YES;
    }
    
    return NO;
}

- (BOOL)conformsToProtocol:(Protocol *)aProtocol {
    BOOL result = [super conformsToProtocol:aProtocol];
    if (result) return YES;
    
    NSPointerArray *delegates = [self.delegates copy];
    for (id delegate in delegates) {
        if ([delegate conformsToProtocol:aProtocol]) return YES;
    }
    
    return NO;
}
```

至于打开 Demo 里的 `collectionView:layout:heightForHeaderInSection:` 后会 crash，这不是 QMUI 的问题，请自行排查。

**Comment by xhjss** [comment]
好的，谢谢
---原始邮件---
发件人:"MoLice"<notifications@github.com>;
发送时间:2019年7月22日(星期一) 晚上10:35
收件人:"Tencent/QMUI_iOS"<QMUI_iOS@noreply.github.com>;
抄送人:"xhjss"<250154804@qq.com>;"Author"<author@noreply.github.com>;
主题:Re: [Tencent/QMUI_iOS] QMUIMutipleDelegates 无法正确响应 conformsToProtocol: (#663)


命中没有实现协议的断言的问题，是 QMUIMultipleDelegates 的问题，下个版本将会修复，在此之前可将以下代码添加到 QMUIMultipleDelegates 的实现里：
 - (BOOL)isKindOfClass:(Class)aClass {     BOOL result = [super isKindOfClass:aClass];     if (result) return YES;          NSPointerArray *delegates = [self.delegates copy];     for (id delegate in delegates) {         if ([delegate isKindOfClass:aClass]) return YES;     }          return NO; } - (BOOL)isMemberOfClass:(Class)aClass {     BOOL result = [super isMemberOfClass:aClass];     if (result) return YES;          NSPointerArray *delegates = [self.delegates copy];     for (id delegate in delegates) {         if ([delegate isMemberOfClass:aClass]) return YES;     }          return NO; } - (BOOL)conformsToProtocol:(Protocol *)aProtocol {     BOOL result = [super conformsToProtocol:aProtocol];     if (result) return YES;          NSPointerArray *delegates = [self.delegates copy];     for (id delegate in delegates) {         if ([delegate conformsToProtocol:aProtocol]) return YES;     }          return NO; }
 
至于打开 Demo 里的 collectionView:layout:heightForHeaderInSection: 后会 crash，这不是 QMUI 的问题，请自行排查。
 
&mdash;

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
