### ISSUE TITLE
QMUISearchController setActive键盘不弹出

### ISSUE THREAD

**Issue by Steven-Yung** [Tencent/QMUI_iOS#664]
**Bug 表现**

当QMUIsearchController设置了launchView时，setactive键盘没有弹出来,如果不设置launchView，键盘能正常弹出

PS:在你们自己的demo中也是这样，所以应该不是我的其他代码引发的问题

**截图**
![1563802872346](https://user-images.githubusercontent.com/8358206/61637134-933a8280-acc9-11e9-841f-ee838a0903b9.jpg)
![1563802917614](https://user-images.githubusercontent.com/8358206/61637165-9f264480-acc9-11e9-9963-0ab00b29eba7.jpg)

**如何重现**

在你们的demo里QDSearchViewController.m的viewDidLoad最后一行加上`self.mySearchController.active = YES;`或者`[self.mySearchController setActive:YES animated:YES];`即可重现

**预期的表现**
正常情况下，应该是能正常弹出键盘，同时显示launchView

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 12.1]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by MoLice** [comment]
实测不管有没有设置 launchView，也不管是 QMUISearchController 或是系统原生的 UISearchController，`setActive:YES` 均无法自动升起键盘，因为搜索框并没有聚焦，QMUI 的表现与系统保持一致即可。

如果与我们的测试结果有出入，请提供 Demo 或者录屏以供进一步排查。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
