### ISSUE TITLE
CALayer (QMUI) 导致了 CPU过高的问题

### ISSUE THREAD

**Issue by azureplus** [Tencent/QMUI_iOS#668]
@implementation CALayer (QMUI)

QMUISynthesizeFloatProperty(qmui_speedBeforePause, setQmui_speedBeforePause)
QMUISynthesizeCGFloatProperty(qmui_originCornerRadius, setQmui_originCornerRadius)

导致了这个方法一直在调用
```
    override open func viewWillLayoutSubviews(){
        super.viewWillLayoutSubviews()
    }
    
    override open func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
    }
```

**Comment by azureplus** [comment]
怎么能够避免这个问题的出现

**Comment by MoLice** [comment]
你说的“导致了这个方法一直在调用”是指什么导致了？

建议提供 Demo 方便我们查看。

**Comment by azureplus** [comment]
![IMG_6694](https://user-images.githubusercontent.com/9008164/61859508-d29be580-aefa-11e9-967b-7d0dbb7be85d.JPG)
还有这个问题，更新了组件后，CPU就平稳下来了，只有4-8%，用这个组件，CPU就非常高了

**Comment by azureplus** [comment]
困惑中。。。。

**Comment by MoLice** [comment]
QMUIMarqueeLabel 的 CPU 占用率问题后续会优化。
