### ISSUE TITLE
关于动态颜色赋值的问题

### ISSUE THREAD

**Issue by fakeros** [Tencent/QMUI_iOS#670]
![Untitled](https://user-images.githubusercontent.com/7323942/62009450-ed3bbc00-b191-11e9-8eae-c80e3fd48a2d.png)

想请教一下，在调用view.backgroundColor = backgroundColor;的时候，是如何进入到
[QMUIThemeColor CGColor]里的？

**Comment by MoLice** [comment]
从左边堆栈就可以看出是系统的 _setBackgroundColor 触发了 CGColor 的调用。

**Comment by fakeros** [comment]
不好意思 可能是我的表述有问题，我想问的是在调用view.backgroundColor = backgroundColor的时候，是如何最终触发QDThemeManager里面的那个block的 
![屏幕快照 2019-07-29 上午10 12 32](https://user-images.githubusercontent.com/7323942/62017536-a974a100-b1e9-11e9-8f96-fa15730e739a.png)
这个动态色值的block是只能通过系统调用[QMUIThemeColor CGColor]来触发吗？谢谢

**Comment by MoLice** [comment]
你的理解没错，是这样。
