### ISSUE TITLE
动态颜色赋值的一个疑惑

### ISSUE THREAD

**Issue by fakeros** [Tencent/QMUI_iOS#671]
![62009450-ed3bbc00-b191-11e9-8eae-c80e3fd48a2d](https://user-images.githubusercontent.com/7323942/62019239-8c8f9c00-b1f0-11e9-8eda-50dcd60c96f7.png)

![屏幕快照 2019-07-29 上午10 12 32](https://user-images.githubusercontent.com/7323942/62019242-96b19a80-b1f0-11e9-80e5-2ac68724e2d7.png)

不好意思 可能是我的表述有问题，我想问的是在调用view.backgroundColor = backgroundColor的时候，是如何最终触发QDThemeManager里面的那个block的。
这个动态色值的block是只能通过系统调用[QMUIThemeColor CGColor]来触发吗，还是哪里有做过方法交换？谢谢

**Comment by MoLice** [comment]
QMUIThemeColor 的思路是，它作为一个 UIColor 对象，把系统可能会用到的任何方法都实现一遍，至于系统在什么时候会用到什么方法，由系统决定，我们不干预，也无需干预。
