### ISSUE TITLE
[iOS 13] Set foregroundColor by UITabBarItemStateAppearance.titleTextAttributes not working

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#672]
**Bug 表现**

iOS 13 新增 `UITabBarAppearance` 专门用于设置 UITabBar 的样式，而 `tabBarItem` 的文字样式由 `tabBar.standardAppearance.stackedLayoutAppearance.normal.titleTextAttributes` 控制，然而发现通过 `titleTextAttributes` 修改 `NSForegroundColorAttributeName` 不生效，如果修改 `NSFontAttributeName` 是可以生效的。

**截图**

![image](https://user-images.githubusercontent.com/1190261/62109634-42d1af00-b2df-11e9-9160-a3888611260a.png)

**如何重现**

[TestTabBar.zip](https://github.com/Tencent/QMUI_iOS/files/3445647/TestTabBar.zip)

**预期的表现**

选中 item 的文字颜色应该和图标颜色相同，都是红色。

**其他信息**
 - 设备: [模拟器]
 - iOS 版本: [iOS 13.0 beta 6]
 - Xcode 版本: [Xcode 11.0 beta 5]

**Comment by MoLice** [comment]
系统在 iOS 13 Beta 7 已修复该问题。

**Comment by jyuuchinen** [comment]
给UITabBarItem的normal设置颜色的逻辑变成了选中时其他item的颜色，有遇到吗？

**Comment by zisulu** [comment]
可是我测试设置NSFontAttributeName虽然生效，但是UITabBarButtonLabel的frame并没有撑开，文字无法显示完整，请问是否有遇到这个问题 @MoLice

**Comment by zisulu** [comment]
我在设置NSFontAttributeName确实生效了，但是UITabBarButtonLabel的frame没有撑开，导致文字显示不全，请问是否遇到过这个问题 @MoLice

**Comment by MoLice** [comment]
@zisulu 没有遇到过

**Comment by zisulu** [comment]
这里是我在这个demo上修改的
[TestTabBar 2.zip](https://github.com/Tencent/QMUI_iOS/files/3663010/TestTabBar.2.zip)
这里是运行结果
![Uploading IMG_4512.PNG…]()

**Comment by zisulu** [comment]
> @zisulu 没有遇到过

我提供了可复现的demo

**Comment by MoLice** [comment]
@zisulu  UITabBar 是否会保证这么大的字号下依然能正常显示 item title，这取决于 UITabBar 的实现，官方并没有提到这一点，所以出现 UI 异常也不能说是有 bug。建议自行寻找是否有变通的方法。

**Comment by zisulu** [comment]
> @zisulu UITabBar 是否会保证这么大的字号下依然能正常显示 item title，这取决于 UITabBar 的实现，官方并没有提到这一点，所以出现 UI 异常也不能说是有 bug。建议自行寻找是否有变通的方法。

在iOS 12以及之前是可以正常显示的，纯文本的tabBar还是有需求的，我通过在tabbar的layouSubViews里面对UITabBarButtonLabel进行sizeToFit解决了。但是觉得怪怪的，所以来请教一下。打扰了。

**Comment by eliashsu** [comment]
> > @zisulu UITabBar 是否会保证这么大的字号下依然能正常显示 item title，这取决于 UITabBar 的实现，官方并没有提到这一点，所以出现 UI 异常也不能说是有 bug。建议自行寻找是否有变通的方法。
> 
> 旧的API是可以正常显示的，只有新的API会有这个情况，纯文本的tabBar还是有需求的，我通过在tabbar的layouSubViews里面对UITabBarButtonLabel进行sizeToFit解决了。但是觉得怪怪的，所以来请教一下。打扰了。

我也遇到了显示不全的问题，更新到 4.0.0 版本后，虽然图标显示正常，但是未选中的文本显示“...”， 显示不全，选中的又正常，中间只是从 4.0.0 beta 升级到 4.0.0 正式版，并没有改动过任何代码~

**Comment by MoLice** [comment]
> > > @zisulu UITabBar 是否会保证这么大的字号下依然能正常显示 item title，这取决于 UITabBar 的实现，官方并没有提到这一点，所以出现 UI 异常也不能说是有 bug。建议自行寻找是否有变通的方法。
> > 
> > 
> > 旧的API是可以正常显示的，只有新的API会有这个情况，纯文本的tabBar还是有需求的，我通过在tabbar的layouSubViews里面对UITabBarButtonLabel进行sizeToFit解决了。但是觉得怪怪的，所以来请教一下。打扰了。
> 
> 我也遇到了显示不全的问题，更新到 4.0.0 版本后，虽然图标显示正常，但是未选中的文本显示“...”， 显示不全，选中的又正常，中间只是从 4.0.0 beta 升级到 4.0.0 正式版，并没有改动过任何代码~

@eliashsu 4.0.0 相对 4.0.0-beta 的差异是在 iOS 13 里将设置 UITabBar 样式的代码换成了 iOS 13 新提供的 API，出现这样的问题是因为系统的新 API 在这种场景下有问题，这个是非预期的，可以先按照 @zisulu 说的方式处理。

**Comment by eliashsu** [comment]
配置表里我设置了 QMUICMI.tabBarItemTitleFont = UIFontMake(11)，置 nil 之后正常了

**Comment by eliashsu** [comment]
> > > > @zisulu UITabBar 是否会保证这么大的字号下依然能正常显示 item title，这取决于 UITabBar 的实现，官方并没有提到这一点，所以出现 UI 异常也不能说是有 bug。建议自行寻找是否有变通的方法。
> > > 
> > > 
> > > 旧的API是可以正常显示的，只有新的API会有这个情况，纯文本的tabBar还是有需求的，我通过在tabbar的layouSubViews里面对UITabBarButtonLabel进行sizeToFit解决了。但是觉得怪怪的，所以来请教一下。打扰了。
> > 
> > 
> > 我也遇到了显示不全的问题，更新到 4.0.0 版本后，虽然图标显示正常，但是未选中的文本显示“...”， 显示不全，选中的又正常，中间只是从 4.0.0 beta 升级到 4.0.0 正式版，并没有改动过任何代码~
> 
> @eliashsu 4.0.0 相对 4.0.0-beta 的差异是在 iOS 13 里将设置 UITabBar 样式的代码换成了 iOS 13 新提供的 API，出现这样的问题是因为系统的新 API 在这种场景下有问题，这个是非预期的，可以先按照 @zisulu 说的方式处理。

配置表里我设置了 QMUICMI.tabBarItemTitleFont = UIFontMake(11)，置 nil 之后正常了

**Comment by MoLice** [comment]
@zisulu @eliashsu UITabBarItem 文字截断的问题参照 https://github.com/Tencent/QMUI_iOS/issues/740#issuecomment-536522789
