### ISSUE TITLE
xcode Version 10.3

### ISSUE THREAD

**Issue by hzw87383197** [Tencent/QMUI_iOS#675]
![image](https://user-images.githubusercontent.com/23348895/62441746-ee6b7b00-b787-11e9-997c-74d26600e078.png)

xcode Version 10.3 
出现图上问题,导致无法编译

**Comment by hhp286687164** [comment]
> ![image](https://user-images.githubusercontent.com/23348895/62441746-ee6b7b00-b787-11e9-997c-74d26600e078.png)
> 
> xcode Version 10.3
> 出现图上问题,导致无法编译

执行以下命令就可以修复：

 sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService

sudo xcode-select -s  /Applications/Xcode.app/Contents/Developer

若还不行再执行下

xcrun simctl erase all
