### ISSUE TITLE
ios12  动态赋值图片会崩溃，ios13正常

### ISSUE THREAD

**Issue by fakeros** [Tencent/QMUI_iOS#676]
<img width="1135" alt="reliao_img_1565064098147" src="https://user-images.githubusercontent.com/7323942/62510586-1f0feb00-b842-11e9-88b4-007ea7e4058a.png">
<img width="1121" alt="reliao_img_1565064105345" src="https://user-images.githubusercontent.com/7323942/62510587-1f0feb00-b842-11e9-8302-74e8ce63d29a.png">

我把demo中染色卡顿的那个方法替换成不卡顿的那个 然后把那个用来缓存的image注释掉，发现进入页面崩溃，是在ios13以下，必须要用一个变量来存这个动态生成的图片吗？

**Comment by MoLice** [comment]
这个会在 iOS 10、12 下 crash，其他版本没问题。

首先应该知悉，在一个 UIImageView 展示一张 image 的过程中，themeProvider 会被调用多次，而如果你把缓存代码去掉，就会导致 themeProvider 每次返回的 image 是不同的实例（虽然这些 image 视觉上看长得一样），一次渲染过程中使用多个不同的实例可能会在系统层面产生各种各样的问题，属于未定义行为。

这种场景 QMUITheme 暂不兼容，请自行保证返回同一个实例。

另外从性能的角度考虑，也不应该每次都返回一个新的实例，虽然你用 `qmui_imageWithTintColor:` 在你目前的设备下觉得不影响性能，但在其他设备上、或者低版本 iOS 上就不一定了。
