### ISSUE TITLE
QMUIPopupContainerView 加在UIScrollView

### ISSUE THREAD

**Issue by friendsheeps** [Tencent/QMUI_iOS#679]
**Bug 表现**
在scrollView上有若干个button，popupContainerView的sourceView指向button，需求将popupContainerView添加在这个scrollView上希望跟随滑动，现在功能基本实现，出现一个小bug，就是popupContainerView的三角箭头会停留在原地，不跟随滑动。

![01](https://user-images.githubusercontent.com/13128046/62997922-5d3d8800-be9c-11e9-9b71-4c015d93bc8f.jpeg)
![02](https://user-images.githubusercontent.com/13128046/62997924-60d10f00-be9c-11e9-963d-2c575c1ec274.jpeg)
![03](https://user-images.githubusercontent.com/13128046/62997926-63336900-be9c-11e9-95fe-538a1e0bfba0.jpeg)

 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
请给出 Demo 或相关代码

**Comment by friendsheeps** [comment]
[demo.zip](https://github.com/Tencent/QMUI_iOS/files/3504053/demo.zip)

**Comment by friendsheeps** [comment]
[demo.zip](https://github.com/Tencent/QMUI_iOS/files/3504057/demo.zip)

**Comment by MoLice** [comment]
下个版本将会修复这个问题，在此之前可按照以下截图的左边去修改代码（修改完记得 clean project）保证生效。

![image](https://user-images.githubusercontent.com/1190261/63170652-54031580-c06c-11e9-848b-b37652123297.png)

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
