### ISSUE TITLE
侧滑手势滑到一半再取消手势，出现的两个问题

### ISSUE THREAD

**Issue by hkjin** [Tencent/QMUI_iOS#680]
**Bug 表现**
问题的具体描述

**截图**
[QMUI问题1.mov.zip](https://github.com/Tencent/QMUI_iOS/files/3529080/QMUI.1.mov.zip)
[QMUI问题2.mov.zip](https://github.com/Tencent/QMUI_iOS/files/3529083/QMUI.2.mov.zip)

**如何重现**
两个问题：
1、在带有QMUISearchController的QMUICommonTableViewController中，激活搜索框，然后侧滑不到一半再取消侧滑，退出搜索状态，搜索框会出现在导航栏下面，退出页面再进入到这个带有搜索框的页面进入搜索状态时，会出现顶部黑块的问题；

2、在带有QMUISearchController的QMUICommonTableViewController中，进入搜索状态，在搜索框中随便输入，点击搜索结果页中的按钮push到其他页面(OneViewController)，在这个页面(OneViewController)中返回手势侧滑一半再取消后，在(OneViewController)再push到下个页面时，会出现QMUISearchController的搜索页面，接下来只要不退出带有QMUISearchController的控制器，不管是PUSH还是POP都会先展示QMUISearchController再展示正常的页面

**预期的表现**
1、导航栏不应该受影响
2、不应该出现搜索页面

**其他信息**
 - 设备: [模拟器、iPhone]
 - iOS 版本: [iOS 12.3.1]
 - Xcode 版本: [Xcode 10.3]
 - QMUI 版本: [3.2.1]

**demo**
[QMUIDemo](https://github.com/Tencent/QMUI_iOS/files/3529024/QMUIDemo.2.zip)

**Comment by ziecho** [comment]
问题一：
你在 JOINBaseTableController.swift 中将 extendedLayoutIncludesOpaqueBars 改成了 false，
而 QMUICommonTableViewController 默认的布局是基于 extendedLayoutIncludesOpaqueBars 为 YES 的情况下，所以删掉这句话就好了。

**Comment by ziecho** [comment]
问题二：这是 UIKit 系统内部的错误，复现条件如下：
当有一个 TableViewController A，A 的 seachBar 被激活且 searchResultsController 正在显示的情况下，A.navigationController push 一个新的 viewController B，B 用 pop 手势返回到一半松手放弃返回，此时 B 再 push 一个新的 viewController 时，会看到 searchResultsController 的内容。

原因分析：
在 pop 并取消时，系统没有考虑这个“取消”的操作，默认认为你已经 pop 到上一个界面了，这会导致下次 push 的时候，把 searchResultsController 的 view 展示在转场过程中，QMUI 已针对这个情况做修复，请关注近期发布的 QMUI 4.0 正式版。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复第二个问题。
