### ISSUE TITLE
CUIThemeStore: No theme registered

### ISSUE THREAD

**Issue by kingctan** [Tencent/QMUI_iOS#682]
**Bug 表现**
配置好后，运行APP，界面上只有第一个TAB有图片和文字显示，其它的都是空白的。
控制台报错：
···
[framework] CUIThemeStore: No theme registered with id=0
···

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: 最新版

**Comment by MoLice** [comment]
这个是 Xcode 的问题，与 QMUI 无关，可参考 Google 搜索结果尝试。

https://www.google.com/search?q=CUIThemeStore%3A+No+theme+registered&oq=CUIThemeStore%3A+No+theme+registered&aqs=chrome..69i57j69i58j69i61.686j0j7&sourceid=chrome&ie=UTF-8
