### ISSUE TITLE
无法屏蔽 QMUI 配置表设置的 navigationBar 样式对 MFMailComposeViewController 的影响

### ISSUE THREAD

**Issue by insist159** [Tencent/QMUI_iOS#683]
我使用配置文件配置导航颜色，但是影响了一些系统提供的功能页面，比如说ABPeoplePickerNavigationController 等等

**Comment by MoLice** [comment]
影响到系统所有 navigationBar 的原因是因为 QMUI 配置表里的 `navBarXxx` 系列属性是通过 `UINavigationBar.appearance.xxx = xxx` 的方式来设置的（源码请查看 QMUIConfiguration.m），但由于系统只提供了 `appearanceWhenContainedInInstancesOfClasses:` 来限定在某些 class 里才让 appearance 生效，却没提供类似 appearanceWhen**NotContained**InXxx 的方法，所以我们无法单独屏蔽对某些系统 class 的 navigationBar 的影响。

建议这种情况可以手动在业务项目里添加以下代码将指定系统的 class 的 navigationBar 样式重置回来：
```Objective-C
UINavigationBar *barInABPeople = [UINavigationBar appearanceWhenContainedInInstancesOfClasses:@[[ABPeoplePickerNavigationController class]];
barInABPeople.tintColor = nil;
barInABPeople.barTintColor = nil;
barInABPeople.xxx = xxx;
...
```

**Comment by insist159** [comment]
好像不行啊

**Comment by insist159** [comment]
还有一点，我是用生成图片的方式用于导航背景

**Comment by MoLice** [comment]
生成图片没关系的，也可以。是否能提供一个 Demo 看看？

**Comment by insist159** [comment]
@MoLice 
[QMUIDemo.zip](https://github.com/Tencent/QMUI_iOS/files/3574336/QMUIDemo.zip)  
Demo已奉上

**Comment by insist159** [comment]
@MoLice

**Comment by insist159** [comment]
@ziecho

**Comment by insist159** [comment]
@MoLice

**Comment by insist159** [comment]
@MoLice

**Comment by MoLice** [comment]
这个 Demo 里有两个问题，一个是 QMUI 配置表的样式如何不影响系统其他框架的样式，另一个是 navigationBarTintColor 不生效。

后者是 QMUI 的 bug，由 #692 跟进，这里不详述。

前者是符合 QMUI 的设计预期的，也即整个 App 里样式都是统一的，不管调起的界面是属于系统的还是业务的，而如果业务项目需要更改这个规则也是可以的。但目前看来即便我们重置了 `appearanceWhenContainedInInstancesOfClasses:@[MFMailComposeViewController.class]` 的样式，MFMailComposeViewController 里的 navigationBar 依然走了默认的 appearance，，目前暂未找到优雅的方式解决这个问题，建议可以在 present 邮件界面前直接修改 `UINavigationBar.appearance.barTintColor/tintColor/xxx`，在退出邮件界面后恢复业务项目自己的 appearance 值。

后续我们再看如何优雅解决这个问题。

**Comment by insist159** [comment]
@MoLice 好的 感谢

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
