### ISSUE TITLE
QMUINavigationTitleView手势返回时会抖动

### ISSUE THREAD

**Issue by fero2004** [Tencent/QMUI_iOS#686]
**Bug 表现**
问题的具体描述

当设置了navigationItem.leftBarButtonItem的时候,并且标题超长的情况下,手势返回上一个界面, QMUINavigationTitleView会突然跳到navbar的中间

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![29757E8D-581A-4B06-80BA-1FAA5DD1F427](https://user-images.githubusercontent.com/5326843/64065716-94a18800-cc43-11e9-94a7-bdfb49ac7615.png)

**如何重现**
1. 设置navigationItem.leftBarButtonItem,self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"1" style:UIBarButtonItemStyleDone target:nil action:nil];
2. 设置 self.title = @"感知系统的手势返回感知系统的手势返回感知系统的手势返回感知系统的手势返回感知系统的手势返回感知系统的手势返回感知系统的手势返回感知系统的手势返回感知系统的手势返回";
3.手势返回上一个界面

**预期的表现**
正常手势返回的时候,不会突然跳动

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [3.x.x]

**Comment by fero2004** [comment]
暂时找到一个在ios13可以使用的方法,不使用leftBarButtonItem,用backIndicatorImage作为返回
```
 self.navigationController?.navigationBar.backIndicatorImage = UIImage.init(named: "nav_back")!.withRenderingMode(UIImage.RenderingMode.alwaysOriginal)
 self.navigationController?.navigationBar.backIndicatorTransitionMaskImage = UIImage.init(named: "nav_back")!.withRenderingMode(UIImage.RenderingMode.alwaysOriginal)
```

**Comment by MoLice** [comment]
系统本身就有这个问题，与 QMUI 无关，我们会尝试看如何修复，但优先级可能不高，此 issue 先关闭，后续如果有优化系统的这个表现，我们会再追加评论。

以下是空项目测试的截图，以及测试 Demo 下载。

<img src="https://user-images.githubusercontent.com/1190261/64153861-4fa76c80-ce62-11e9-89b3-624d35db3a83.png" width="400" />

[TestTitleView.zip](https://github.com/Tencent/QMUI_iOS/files/3568375/TestTitleView.zip)

如果你的 leftBarButtonItem 本来就是为了做返回按钮，应该用 backIndicatorImage（或者配置表里的 `NavBarBackIndicatorImage` 设置项），不应该用 leftBarButtonItem，用系统的返回按钮也可以省去强制打开手势返回的操作。
