### ISSUE TITLE
无法在导航栏顶部的titleview定义searchbar高度

### ISSUE THREAD

**Issue by chenfengfeng** [Tencent/QMUI_iOS#688]
**Bug 表现**
创建QMUISearchController并且设置好search bar后，调用约束
searchController.searchBar.heightAnchor.constraint(equalToConstant: 44).isActive = true
然而在点击search bar后会创建一个QMUICustomSearchController，里面的search bar高度又被还原了，找不到哪里可以修改激活后的searchbar可以重新设置高度
创建代码
`if let searchController = QMUISearchController(contentsViewController: controller) {
            searchController.searchBar.qmui_usedAsTableHeaderView = false
            searchController.hidesNavigationBarDuringPresentation = false
            searchController.searchBar.tintColor = UIColor(named: .theme)
            searchController.searchBar.placeholder = "search"
            searchController.setActive(false, animated: false)
            controller.navigationItem.titleView = searchController.searchBar
            if #available(iOS 11.0, *) {
                searchController.searchBar.heightAnchor.constraint(equalToConstant: 44).isActive = true
            }
}`

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.x.x]

**Comment by MoLice** [comment]
QMUI 里对 searchBar 的布局和大小没有限定，都是以系统默认的表现为准，我们也没有去专门测试过修改 searchBar 的大小会有什么样的表现，这暂不包含在我们的考虑的范围内。

searchBar 的高度受多方的影响，包括但不限于你设置的背景图大小、系统本身默认的 layout 调整等，你可以用 UIView (QMUI_Block) 里提供的 `qmui_frameWillChangeBlock`、`qmui_frameDidChangeBlock` 去看是谁在什么时候改了 searchBar 的 frame，自行排查。按目前提供的信息暂时无法确定原因。

**Comment by chenfengfeng** [comment]
@MoLice 非常感谢～已经解决了，虽然感觉有点暴力，但是能解决问题才是重点
贴上解决的代码
```swift
if #available(iOS 11.0, *) {
                searchController.searchBar.heightAnchor.constraint(equalToConstant: 44).isActive = true
                searchController.searchBar.qmui_frameWillChangeBlock = { (v,r)->CGRect in
                    var rect = r
                    rect.size = CGSize(width: rect.width, height: 44)
                    return rect
                }
            }
```
