### ISSUE TITLE
引用三方库“TABAnimated“，同时使用QMUINavigationBarScrollingAnimator会崩溃

### ISSUE THREAD

**Issue by youeri3** [Tencent/QMUI_iOS#689]
**Bug 表现**
问题的具体描述
 引用三方库“TABAnimated“，同时使用QMUINavigationBarScrollingAnimator，来控制导航栏的透明度，会引起崩溃

控制台信息-------
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSMethodSignature signatureWithObjCTypes:]: type signature is empty.'
控制台信息-------

全局断点，断在QMUIMultipleDelegates中的第65行
NSMethodSignature *result = [super methodSignatureForSelector:aSelector];

**如何重现**
1. 同时集成 TABAnimated 和QMUI  
2. 在控制器中的tableview使用TABAnimated骨架屏动画，并使用QMUINavigationBarScrollingAnimator类来管理导航栏透明度，关联控制器中的tableView. 调用
TABAnimated 的结束动画操作。就会复现
**预期的表现**
正常情况下，应该是什么表现
正常reload
**其他信息**
 - 设备: [模拟器]
 - iOS 版本: [iOS 12.4]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [3.2.1]

**Comment by MoLice** [comment]
为了提高问题解决的效率，此类问题建议直接提供一个 Demo 项目，提供 Demo 后我们将会重新 reopen 该 issue。
