### ISSUE TITLE
   调用 [self.navigationController setViewControllers:viewControllers animated:animated] 闪退

### ISSUE THREAD

**Issue by xx752690102** [Tencent/QMUI_iOS#690]
**Bug 表现**
   调用 [self.navigationController setViewControllers:viewControllers animated:animated]; 闪退

**截图**
![image](https://user-images.githubusercontent.com/13724801/64224650-eb8cb300-cf0a-11e9-8a33-54ea5f6cb2bd.png)
![image](https://user-images.githubusercontent.com/13724801/64224656-f0e9fd80-cf0a-11e9-9ac6-bad35eec0b10.png)

**如何重现**
1.减少 viewControllers 数量
2.调用 [self.navigationController setViewControllers:viewControllers animated:animated]

**预期的表现**
可以正常调用
**其他信息**
 - 设备: iPhone X
 - iOS 版本: [iOS 12.1.2]
 - Xcode 版本: [Xcode 10.2.1]
 - QMUI 版本: [4.0.0-beta]

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/64234526-1ede3a80-cf29-11e9-95e2-ffe8826e40ed.png)

Xcode 控制台给出的信息已经很明确了，你尝试把同一个 viewController 实例重复放到 viewControllers 里。
