### ISSUE TITLE
建议QMUIPopupContainerView 可以设置显示在sourceView的左边或者右边

### ISSUE THREAD

**Issue by YuanJiaShuai** [Tencent/QMUI_iOS#691]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。
![image](https://user-images.githubusercontent.com/14836047/64239908-a761d880-cf33-11e9-8286-978081c8b9c9.png)

**Comment by azureplus** [comment]
原来也有这个需求了

**Comment by MoLice** [comment]
已发布 [4.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.0) 提供支持，可下载最新的 QMUI Demo 查看示例。
