### ISSUE TITLE
present 一个 QMUINavigationController 时，rootViewController 的 navigationBarTintColor 无效

### ISSUE THREAD

**Issue by insist159** [Tencent/QMUI_iOS#692]
**重现步骤**
1. 初始化一个 QMUINavigationController，并设置一个 viewController 作为 rootViewController。
1. 为 rootViewController 添加 navigationItem.leftBarButtonItem/rightBarButtonItem。
1. 在 rootViewController 里实现 navigationBarTintColor，返回 UIColorRed。
1. present 第1步里的 navController，会发现第2步里添加的按钮颜色并非红色。

注意，必须为 UIModalPresentationFullScreen 才有问题，如果在 iOS 13 下测试，注意要显示指定为这个 style。

**Comment by MoLice** [comment]
navigationBar.tintColor 是在 [UINavigationController+NavigationBarTransition.m:309-311](https://github.com/Tencent/QMUI_iOS/blob/master/QMUIKit/QMUIComponents/NavigationBarTransition/UINavigationController%2BNavigationBarTransition.m#L309-L311) 里设置的，但在一个 UINavigationController 被 present 时，`qmui_animateAlongsideTransition:completion:` 方法里的 animation block 并不会被调用，导致 rootViewController 的 tintColor 逻辑失效。

已修复该问题，请等待新版本发布。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
