### ISSUE TITLE
[iOS13.1 Beta2] UINavigationBar(QMUINavigationButton) load 崩溃

### ISSUE THREAD

**Issue by hkjin** [Tencent/QMUI_iOS#694]
**Bug 表现**
应用启动就崩溃

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="678" alt="WechatIMG67" src="https://user-images.githubusercontent.com/17734586/64403826-91c3ee80-d0ac-11e9-9cd8-43643b78a30e.png">

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 13.1 Beta2]
 - Xcode 版本: [Xcode 11.0 Beta]
 - QMUI 版本: [4.0.00]

**Comment by MoLice** [comment]
目测与 #628 是相同的，这个问题在 QMUI 4.0.0-beta 版本已经修复了，请确认你的代码是否最新版。

另外也可贴出 crash 后 Xcode 控制台的报错信息。
