### ISSUE TITLE
Iphone XR （12.4版本）启动需要15秒

### ISSUE THREAD

**Issue by Jas67810** [Tencent/QMUI_iOS#695]
**Bug 表现**
下载 QMUI_iOS-master 工程，直接编译运行工程。发现需要等到15-20s以上，才能进入主界面（直接扫描appstore下载的demo没有这个问题）然后在 main.m 的main()函数中，增加Log。发现20s之后，才开始运行 main()函数。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
直接编译运行

**预期的表现**
能快速进行主界面

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 12.4]
 - Xcode 版本: [Xcode 10.2]
 - QMUI 版本: [3.x.x]

**Comment by Jas67810** [comment]
使用IphoneX(12.4)的机器，未发现该问题

**Comment by TheLittleBoy** [comment]
Xcode bug吧，试试最新版的Xcode 。

**Comment by MoLice** [comment]
没有重现该问题，建议提供更详细的信息，例如控制台输出的信息，或者卡顿时正在执行的函数（可以在控制台点暂停）。

**Comment by kuiZhang98** [comment]
与楼主同样的问题卡在启动页面。XR.  版本IOS13

**Comment by TheLittleBoy** [comment]
当时可以复现，不止卡15秒这么简单，而是一直进不去！ 后来重启xcode，重启模拟器 就好使了。

**Comment by MoLice** [comment]
因没有详细信息提供，该 issue 关闭，有进一步的信息提供后再 reopen。

**Comment by moruiwei2** [comment]
我线上的版本,也出现这个问题,少数用户反馈会卡死在启动页
