### ISSUE TITLE
QMUITabBarViewController角标和红点位置错乱

### ISSUE THREAD

**Issue by hkjin** [Tencent/QMUI_iOS#697]
**Bug 表现**
问题的具体描述
在启动应用时，QMUITabBarViewController上的角标和红点位置会不对

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

<img width="438" alt="WeChat06634a1eb37250869926a8ad802f5f7a" src="https://user-images.githubusercontent.com/17734586/64529303-293f7080-d33d-11e9-8a7f-dc9f33fdad40.png">

![代码截图](https://user-images.githubusercontent.com/17734586/64529389-5c81ff80-d33d-11e9-891d-917a06f03760.png)

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11.0 Beta6]
 - QMUI 版本: [4.0.0]

**Comment by hkjin** [comment]
当点击后，就恢复正常了。。

**Comment by MoLice** [comment]
这个问题在 iOS 13.0 beta 1 里首先出现，我们为其增加了一些适配代码，后来在某个 beta 版本里又被系统修复，于是我们把代码去掉了，而现在 iOS 13.1 中又出现了...QMUI 下个版本将会把这部分的兼容重新加上。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
