### ISSUE TITLE
继承自QMUICommonViewController的控制中如何修改EmptyView的按钮上文字颜色?

### ISSUE THREAD

**Issue by MQL9011** [Tencent/QMUI_iOS#698]
```
    self.emptyView.actionButtonTitleColor = [UIColor redColor];
```
这么写了之后我调用

```
    [self showEmptyViewWithText:@"加载中" detailText:@"" buttonTitle:@"取消" buttonAction:nil];

```
但是button上文字颜色还是没变呀

**Comment by MoLice** [comment]
QMUICommonViewController 里的 emptyView 是在 showEmptyView 里才被初始化的，所以猜测你调用 `self.emptyView.actionButtonTitleColor = [UIColor redColor];` 时 emptyView 为 nil，所以没有效果。

这里确实有使用上的困惑，我们会再考虑如何修改，可关注后续的版本更新日志，在此之前你可以尝试把那两句代码的顺序调换一下。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
