### ISSUE TITLE
你好，我有个问题，关于2.x是否还更新

### ISSUE THREAD

**Issue by Wbqqqq** [Tencent/QMUI_iOS#699]
一直装的是2.9.3,因为公司用户量庞大，还是有少量用户用着ios8.x的手机，包括公司其中的一台测试机也是iphone5 ios8.2
今天在适配ios13的时候发现崩溃问题，看了一圈issue基本知道了问题，所以想问一下2.x的版本能否出个新分支继续更新，否则的话
我可能会面临几个选择😢，一个就是放弃ios8.x的用户，或者放弃QMUI_iOS，前者省力但不一定通得过公司决策，第二个虽然麻烦，因为目前确实用到库的很多组件，不是不可，但确实要替换和修改工作量确实很大，所以还是想先来问问是否有这方面打算或者有些别的什么建议😢。。。

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11.0]
 - QMUI 版本: [2.9.3]

**Comment by TheLittleBoy** [comment]
我们公司也是从今年开始决定放弃iOS 8用户的！用户量实在是太少了，6年前的手机才有可能安装iOS 8，并且是6年来从未升级过系统。

**Comment by Wbqqqq** [comment]
我们8.x接近每天还有100多的新增用户，对公司来说转换下来也是一笔客观收入。

**Comment by TheLittleBoy** [comment]
看来你需要自己维护后续更新啦！

**Comment by Wbqqqq** [comment]
哎，就想来问问官方的回应，要是不更新也死心了

**Comment by TheLittleBoy** [comment]
官方正在忙着适配iOS 13哦

**Comment by MoLice** [comment]
不会针对 iOS 8 继续适配，这部分的工作只能自行处理了。

**Comment by Wbqqqq** [comment]
gei it
