### ISSUE TITLE
presentViewController 状态下更新 Theme 可能存在异常

### ISSUE THREAD

**Issue by ziecho** [Tencent/QMUI_iOS#700]
**Bug 表现**

presentViewController 状态下更新 Theme 可能存在异常

**截图** 

![image](https://user-images.githubusercontent.com/16473618/65167738-b4271600-da75-11e9-8965-a3ce9a121e39.png)

**如何重现**

QMUI Demo 在 QMUISearchController 激活搜索框，此时为 presentViewController 状态，此时改变主题，返回到主界面后发现一些样式并没有被修改

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.·]
 - Xcode 版本: [Xcode 11.0]
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
