### ISSUE TITLE
QMUIPopupMenuView中的QMUILabel，长按出现的复制

### ISSUE THREAD

**Issue by azureplus** [Tencent/QMUI_iOS#701]
采用window模式显示，组件里头添加QMUILabel，长按出现的复制，在QMUIPopupMenuView下

**Comment by azureplus** [comment]
- (void)setMenuVisible:(BOOL)menuVisible API_DEPRECATED("Use showMenuFromView:rect: or hideMenuFromView: instead.", ios(3.0, 13.0));
- (void)setMenuVisible:(BOOL)menuVisible animated:(BOOL)animated API_DEPRECATED("Use showMenuFromView:rect: or hideMenuFromView: instead.", ios(3.0, 13.0));

- (void)setTargetRect:(CGRect)targetRect inView:(UIView *)targetView API_DEPRECATED("Use showMenuFromView:rect: instead.", ios(3.0, 13.0));

- (void)showMenuFromView:(UIView *)targetView rect:(CGRect)targetRect API_AVAILABLE(ios(13.0));
- (void)hideMenuFromView:(UIView *)targetView API_AVAILABLE(ios(13.0));
- (void)hideMenu API_AVAILABLE(ios(13.0));

**Comment by MoLice** [comment]
Xcode 11，iOS 13 下测试，并没有出现你说的情况，请提供具体代码或者 Demo。

截图中可看到 menu 在 popup window 之上。
![image](https://user-images.githubusercontent.com/1190261/65226086-da41ca00-daf8-11e9-9f7b-a62e93b91f24.png)

**Comment by azureplus** [comment]
在demo中插入这个代码，就可以复现，测试环境为iPad Pro10.5 PadOS 13.1 beta4
```
 QMUILabel *_textLabel = [[QMUILabel alloc] init];
    _textLabel.canPerformCopyAction = YES;
    _textLabel.font = UIFontMake(14);
    _textLabel.textColor = UIColor.blackColor;
    _textLabel.numberOfLines = 0;
    _textLabel.text = @"QMUILabel";
    _textLabel.canPerformCopyAction = YES;
    [self.popupWithCustomView.contentView addSubview:_textLabel];
    _textLabel.frame = CGRectMake(60, 100, 100, 40);
```
    // 在 UIBarButtonItem 上显示
    self.popupAtBarButtonItem = [[QMUIPopupMenuView alloc] init];
    self.popupAtBarButtonItem.automaticallyHidesWhenUserTap = YES;// 点击空白地方消失浮层
    self.popupAtBarButtonItem.maximumWidth = 180;

**Comment by azureplus** [comment]
> 在demo中插入这个代码，就可以复现，测试环境为iPad Pro10.5 PadOS 13.1 beta4
> 
> ```
>  QMUILabel *_textLabel = [[QMUILabel alloc] init];
>     _textLabel.canPerformCopyAction = YES;
>     _textLabel.font = UIFontMake(14);
>     _textLabel.textColor = UIColor.blackColor;
>     _textLabel.numberOfLines = 0;
>     _textLabel.text = @"QMUILabel";
>     _textLabel.canPerformCopyAction = YES;
>     [self.popupWithCustomView.contentView addSubview:_textLabel];
>     _textLabel.frame = CGRectMake(60, 100, 100, 40);
> ```
> 
> ```
> // 在 UIBarButtonItem 上显示
> self.popupAtBarButtonItem = [[QMUIPopupMenuView alloc] init];
> self.popupAtBarButtonItem.automaticallyHidesWhenUserTap = YES;// 点击空白地方消失浮层
> self.popupAtBarButtonItem.maximumWidth = 180; 
> ```

估计是系统bug，没法解决了

**Comment by azureplus** [comment]
![IMG_D50EB7CA88EC-1](https://user-images.githubusercontent.com/9008164/65230062-cf3e6800-daff-11e9-9570-5057e2a1a0f3.jpeg)
显示效果图

**Comment by azureplus** [comment]
> Xcode 11，iOS 13 下测试，并没有出现你说的情况，请提供具体代码或者 Demo。
> 
> 截图中可看到 menu 在 popup window 之上。
> ![image](https://user-images.githubusercontent.com/1190261/65226086-da41ca00-daf8-11e9-9f7b-a62e93b91f24.png)

你的label在顶端，看不出啊

**Comment by MoLice** [comment]
Xcode 11 GM2, iPad Pro 10.5，相同的代码，也依然没出现你说的情况，或者你可以提供一个 Demo。
![image](https://user-images.githubusercontent.com/1190261/65241614-8ba32880-db16-11e9-8518-992997a2bdab.png)

**Comment by azureplus** [comment]
Version 11.0 (11A420a)，你的Xcode跟我的不一样啊，估计是这个Xcode原因。
我的代码 


`//
//  QDPopupContainerViewController.m
//  qmuidemo
//
//  Created by QMUI Team on 15/12/17.
//  Copyright © 2015年 QMUI Team. All rights reserved.
//

#import "QDPopupContainerViewController.h"

@interface QDPopupContainerView : QMUIPopupContainerView

@property(nonatomic, strong) QMUIEmotionInputManager *emotionInputManager;
@end

@implementation QDPopupContainerView

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        self.contentEdgeInsets = UIEdgeInsetsZero;
        self.emotionInputManager = [[QMUIEmotionInputManager alloc] init];
        self.emotionInputManager.emotionView.emotions = [QDUIHelper qmuiEmotions];
        self.emotionInputManager.emotionView.sendButton.hidden = YES;
        [self.contentView addSubview:self.emotionInputManager.emotionView];
        
        
        QMUILabel *_textLabel = [[QMUILabel alloc] init];
        _textLabel.canPerformCopyAction = YES;
        _textLabel.font = UIFontMake(14);
        _textLabel.textColor = UIColor.blackColor;
        _textLabel.numberOfLines = 0;
        _textLabel.text = @"QMUILabel";
        _textLabel.canPerformCopyAction = YES;
        [_textLabel sizeToFit];
        _textLabel.frame = CGRectMake(60, 100, 100, 40);
        [self.contentView addSubview:_textLabel];
    }
    return self;
}

- (CGSize)sizeThatFitsInContentView:(CGSize)size {
    return CGSizeMake(300, 232);
}

- (void)layoutSubviews {
    [super layoutSubviews];
    // 所有布局都参照 contentView
    self.emotionInputManager.emotionView.frame = self.contentView.bounds;
}

@end

@interface QDPopupContainerViewController ()

@property(nonatomic, strong) QMUIButton *button1;
@property(nonatomic, strong) QMUIPopupContainerView *popupByAddSubview;
@property(nonatomic, strong) QMUIButton *button2;
@property(nonatomic, strong) QMUIPopupMenuView *popupByWindow;
@property(nonatomic, strong) QMUIButton *button3;
@property(nonatomic, strong) QDPopupContainerView *popupWithCustomView;
@property(nonatomic, strong) CALayer *separatorLayer1;
@property(nonatomic, strong) CALayer *separatorLayer2;
@property(nonatomic, strong) QMUIPopupMenuView *popupAtBarButtonItem;
@end

@implementation QDPopupContainerViewController

- (void)initSubviews {
    [super initSubviews];
    
    __weak __typeof(self)weakSelf = self;
    
    self.separatorLayer1 = [CALayer layer];
    [self.separatorLayer1 qmui_removeDefaultAnimations];
    self.separatorLayer1.backgroundColor = UIColorSeparator.CGColor;
    [self.view.layer addSublayer:self.separatorLayer1];
    
    self.separatorLayer2 = [CALayer layer];
    [self.separatorLayer2 qmui_removeDefaultAnimations];
    self.separatorLayer2.backgroundColor = UIColorSeparator.CGColor;
    [self.view.layer addSublayer:self.separatorLayer2];
    
    self.button1 = [QDUIHelper generateLightBorderedButton];
    [self.button1 addTarget:self action:@selector(handleButtonEvent:) forControlEvents:UIControlEventTouchUpInside];
    [self.button1 setTitle:@"显示默认浮层" forState:UIControlStateNormal];
    [self.view addSubview:self.button1];
    
    // 使用方法 1，以 addSubview: 的形式显示到界面上
    self.popupByAddSubview = [[QMUIPopupContainerView alloc] init];
    self.popupByAddSubview.imageView.image = [[UIImageMake(@"icon_emotion") qmui_imageResizedInLimitedSize:CGSizeMake(24, 24) resizingMode:QMUIImageResizingModeScaleToFill] qmui_imageWithTintColor:UIColor.qd_tintColor];
    self.popupByAddSubview.textLabel.text = @"默认自带 imageView、textLabel，可展示简单的内容";
    self.popupByAddSubview.imageEdgeInsets = UIEdgeInsetsMake(0, 0, 0, 8);
    self.popupByAddSubview.didHideBlock = ^(BOOL hidesByUserTap) {
        [weakSelf.button1 setTitle:@"显示默认浮层" forState:UIControlStateNormal];
    };
    self.popupByAddSubview.sourceView = self.button1;// 相对于 button1 布局
    // 使用方法 1 时，显示浮层前需要先手动隐藏浮层，并自行添加到目标 UIView 上
//    self.popupByAddSubview.hidden = YES;
//    [self.view addSubview:self.popupByAddSubview];
    
    
    
    self.button2 = [QDUIHelper generateLightBorderedButton];
    [self.button2 addTarget:self action:@selector(handleButtonEvent:) forControlEvents:UIControlEventTouchUpInside];
    [self.button2 setTitle:@"显示菜单浮层" forState:UIControlStateNormal];
//    [self.view addSubview:self.button2];
    
    // 使用方法 2，以 UIWindow 的形式显示到界面上，这种无需默认隐藏，也无需 add 到某个 UIView 上
    self.popupByWindow = [[QMUIPopupMenuView alloc] init];
    self.popupByWindow.automaticallyHidesWhenUserTap = YES;// 点击空白地方消失浮层
    self.popupByWindow.maskViewBackgroundColor = UIColorMaskWhite;// 使用方法 2 并且打开了 automaticallyHidesWhenUserTap 的情况下，可以修改背景遮罩的颜色
    self.popupByWindow.shouldShowItemSeparator = YES;
    self.popupByWindow.itemConfigurationHandler = ^(QMUIPopupMenuView *aMenuView, QMUIPopupMenuButtonItem *aItem, NSInteger section, NSInteger index) {
        // 利用 itemConfigurationHandler 批量设置所有 item 的样式
        aItem.button.highlightedBackgroundColor = [UIColor.qd_tintColor colorWithAlphaComponent:.2];
    };
    self.popupByWindow.items = @[[QMUIPopupMenuButtonItem itemWithImage:[UIImageMake(@"icon_tabbar_uikit") imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate] title:@"QMUIKit" handler:^(QMUIPopupMenuButtonItem *aItem) {
        [aItem.menuView hideWithAnimated:YES];
    }],
                                 [QMUIPopupMenuButtonItem itemWithImage:[UIImageMake(@"icon_tabbar_component") imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate] title:@"Components" handler:^(QMUIPopupMenuButtonItem *aItem) {
                                     [aItem.menuView hideWithAnimated:YES];
                                 }],
                                 [QMUIPopupMenuButtonItem itemWithImage:[UIImageMake(@"icon_tabbar_lab") imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate] title:@"Lab" handler:^(QMUIPopupMenuButtonItem *aItem) {
                                     [aItem.menuView hideWithAnimated:YES];
                                 }]];
    self.popupByWindow.didHideBlock = ^(BOOL hidesByUserTap) {
        [weakSelf.button2 setTitle:@"显示菜单浮层" forState:UIControlStateNormal];
    };
    self.popupByWindow.sourceView = self.button2;// 相对于 button2 布局
    
    
    
    self.button3 = [QDUIHelper generateLightBorderedButton];
    [self.button3 addTarget:self action:@selector(handleButtonEvent:) forControlEvents:UIControlEventTouchUpInside];
    [self.button3 setTitle:@"显示自定义浮层" forState:UIControlStateNormal];
    [self.view addSubview:self.button3];
    
    self.popupWithCustomView = [[QDPopupContainerView alloc] init];
    self.popupWithCustomView.preferLayoutDirection = QMUIPopupContainerViewLayoutDirectionBelow;// 默认在目标的下方，如果目标下方空间不够，会尝试放到目标上方。若上方空间也不够，则缩小自身的高度。
    self.popupWithCustomView.didHideBlock = ^(BOOL hidesByUserTap) {
        [weakSelf.button3 setTitle:@"显示自定义浮层" forState:UIControlStateNormal];
    };
    
    QMUILabel *_textLabel = [[QMUILabel alloc] init];
    _textLabel.canPerformCopyAction = YES;
    _textLabel.font = UIFontMake(14);
    _textLabel.textColor = UIColor.blackColor;
    _textLabel.numberOfLines = 0;
    _textLabel.text = @"QMUILabel";
    _textLabel.canPerformCopyAction = YES;
    _textLabel.frame = CGRectMake(60, 100, 100, 40);
//    [self.popupWithCustomView.contentView addSubview:_textLabel];
    // 在 UIBarButtonItem 上显示
    self.popupAtBarButtonItem = [[QMUIPopupMenuView alloc] init];
    self.popupAtBarButtonItem.automaticallyHidesWhenUserTap = YES;// 点击空白地方消失浮层
    self.popupAtBarButtonItem.maximumWidth = 180;
    self.popupAtBarButtonItem.shouldShowItemSeparator = YES;
    self.popupAtBarButtonItem.items = @[[QMUIPopupMenuButtonItem itemWithImage:[UIImageMake(@"icon_tabbar_uikit") imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate] title:@"QMUIKit" handler:NULL],
                              [QMUIPopupMenuButtonItem itemWithImage:[UIImageMake(@"icon_tabbar_component") imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate] title:@"Components" handler:NULL],
                              [QMUIPopupMenuButtonItem itemWithImage:[UIImageMake(@"icon_tabbar_lab") imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate] title:@"Lab" handler:NULL]];
}

- (void)setupNavigationItems {
    [super setupNavigationItems];
    self.navigationItem.rightBarButtonItem = [UIBarButtonItem qmui_itemWithImage:UIImageMake(@"icon_nav_about") target:self action:@selector(handleRightBarButtonItemEvent)];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    
    // popupView3 使用方法 2 显示，并且没有打开 automaticallyHidesWhenUserTap，则需要手动隐藏
    if (self.popupWithCustomView.isShowing) {
        [self.popupWithCustomView hideWithAnimated:animated];
    }
}

- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    CGFloat minY = self.qmui_navigationBarMaxYInViewCoordinator;
    CGFloat viewportHeight = CGRectGetHeight(self.view.bounds) - minY;
    CGFloat sectionHeight = viewportHeight / 3.0;
    
    self.popupByAddSubview.safetyMarginsOfSuperview = UIEdgeInsetsSetTop(self.popupByAddSubview.safetyMarginsOfSuperview, self.qmui_navigationBarMaxYInViewCoordinator + 10);
    self.button1.frame = CGRectSetXY(self.button1.frame, CGFloatGetCenter(CGRectGetWidth(self.view.bounds), CGRectGetWidth(self.button1.frame)), minY + (sectionHeight - CGRectGetHeight(self.button1.frame)) / 2.0);
    
    self.separatorLayer1.frame = CGRectFlatMake(0, minY + sectionHeight, CGRectGetWidth(self.view.bounds), PixelOne);
    
    self.button2.frame = CGRectSetY(self.button1.frame, CGRectGetMaxY(self.button1.frame) + sectionHeight - CGRectGetHeight(self.button2.frame));
    
    self.separatorLayer2.frame = CGRectSetY(self.separatorLayer1.frame, minY + sectionHeight * 2.0);
    
    self.button3.frame = CGRectSetY(self.button1.frame, CGRectGetMaxY(self.button2.frame) + sectionHeight - CGRectGetHeight(self.button3.frame));
    self.popupWithCustomView.sourceRect = [self.button3 convertRect:self.button3.bounds toView:nil];// 将 button3 的坐标转换到相对于 UIWindow 的坐标系里，然后再传给浮层布局
}

- (void)handleButtonEvent:(QMUIButton *)button {
    if (button == self.button1) {
        if (self.popupByAddSubview.isShowing) {
            [self.popupByAddSubview hideWithAnimated:YES];
            [self.button1 setTitle:@"显示默认浮层" forState:UIControlStateNormal];
        } else {
            [self.popupByAddSubview showWithAnimated:YES];
            [self.button1 setTitle:@"隐藏默认浮层" forState:UIControlStateNormal];
        }
        return;
    }
    
    if (button == self.button2) {
        [self.popupByWindow showWithAnimated:YES];
        [self.button2 setTitle:@"隐藏菜单浮层" forState:UIControlStateNormal];
        return;
    }
    
    if (button == self.button3) {
        if (self.popupWithCustomView.isShowing) {
            [self.popupWithCustomView hideWithAnimated:YES];
        } else {
            [self.popupWithCustomView showWithAnimated:YES];
            [self.button3 setTitle:@"隐藏自定义浮层" forState:UIControlStateNormal];
        }
        return;
    }
}

- (void)handleRightBarButtonItemEvent {
    if (self.popupAtBarButtonItem.isShowing) {
        [self.popupAtBarButtonItem hideWithAnimated:YES];
    } else {
        // 相对于右上角的按钮布局
        self.popupAtBarButtonItem.sourceBarItem = self.navigationItem.rightBarButtonItem;
        [self.popupAtBarButtonItem showWithAnimated:YES];
    }
}

@end
`

**Comment by MoLice** [comment]
依然没问题？

![image](https://user-images.githubusercontent.com/1190261/65255371-5572a280-db30-11e9-8cd9-2d275eed3825.png)

**Comment by MoLice** [comment]
@azureplus 原来是在 #659 里已兼容这个问题，所以内部版本的 QMUIDemo 跑起来没问题，等新版本发布即可。

**Comment by azureplus** [comment]
iOS 正式版也有这个问题哦。

**Comment by MoLice** [comment]
对，因为这是系统的问题，目前 QMUI 4.0.0-beta 的版本里还没包含对其的兼容代码，4.0.0 正式版会带上。

**Comment by azureplus** [comment]
解决方法1：  self.popupWindow.windowLevel = self.previousKeyWindow.windowLevel + 1;

**Comment by azureplus** [comment]
UITextEffectsWindow 这个的level才10，造成了复制显示位于popupWindow了

**Comment by MoLice** [comment]
windowLevel是直接原因，但过低的level会让popup遇到别的问题。如果你的业务项目可以这样修改那没问题。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本修复该问题。
