### ISSUE TITLE
[iOS 13] 关于Dark Mode 的问题

### ISSUE THREAD

**Issue by friendsheeps** [Tencent/QMUI_iOS#703]
**Bug 表现**
手机升级到了iOS 13.0，选择Dark Mode 后 APP自动响应了 Dark 模式

**截图**
![WechatIMG187](https://user-images.githubusercontent.com/13128046/65367150-bea50380-dc5f-11e9-8bb4-b3633f37cece.jpeg)
这是APP的TabBar，另外其他部分如StatusBar和背景色都变成了Dark Mode。

**预期的表现**
Demo中respondsSystemStyleAutomatically这个属性默认是NO，意思是不响应Dark Mode 切换，目前我在代码中没有做任何其他操作，因为短期不做Dark Mode的适配，所以请问我改如何操作才能让APP不跟随系统切换Dark Mode。

**其他信息**
 - 设备: iPhone
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.0-beta]

**Comment by MQL9011** [comment]
@friendsheeps   我也遇到了这个问题, 请问有解决吗

**Comment by friendsheeps** [comment]
> @friendsheeps 我也遇到了这个问题, 请问有解决吗

在info.plist里加User Interface Style ：Light 强制不用Dark模式就行了
