### ISSUE TITLE
iOS13.0  QMUINavigationButton 崩溃

### ISSUE THREAD

**Issue by coderTong** [Tencent/QMUI_iOS#706]
**Bug 表现**
问题的具体描述

**截图**
![bug](https://user-images.githubusercontent.com/16377258/65385803-54768680-dd65-11e9-9356-ddd3a7ab8049.jpg)

```objc

// 强制修改 contentView 的 directionalLayoutMargins.leading，在使用自定义返回按钮时减小 8
        if (@available(iOS 11, *)) {
            ExtendImplementationOfVoidMethodWithoutArguments([UINavigationBar class], @selector(layoutSubviews), ^(UINavigationBar *selfObject) {
                UIView *contentView = selfObject.qmui_contentView;
                if (contentView) {
                    NSDirectionalEdgeInsets value = contentView.directionalLayoutMargins;
                    value.leading = value.trailing - (selfObject.qmui_customizingBackBarButtonItem ? 8 : 0);
                    contentView.directionalLayoutMargins = value;
                }
            });
        }

```

**如何重现**
1. 一触发就崩溃 

**其他信息**
 - 设备: [模拟器]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11.0]
 - QMUI 版本: [QMUIKit 3.2.1 ]

**Comment by li1275031244** [comment]
4.0.0版本已修复这个问题

**Comment by coderTong** [comment]
@li1275031244 无法通过pod 安装4.0.0

**Comment by lechie** [comment]
> @li1275031244 无法通过pod 安装4.0.0

pod 'QMUIKit', '~> 4.0.0-beta'

正式发行后再把beta字样去掉

**Comment by coderTong** [comment]
@lechie ok 谢谢

**Comment by chenxing890** [comment]
升级成   4.0.0-beta  之后并没有解决问题.   还是报错

Assertion failure in -[_UINavigationBarContentView setDirectionalLayoutMargins:],

**Comment by iOkay** [comment]
same issue using 4.0.0-beta.

**Comment by MoLice** [comment]
@iOkay 4.0.0-beta 里已不存在 `directionalLayoutMargins =` 的代码，理论上不可能还有问题，可提供 Demo 后新建 issue 我们跟进，这个 issue 关闭了。
