### ISSUE TITLE
iOS13使用原生的UIImagePickerController页面卡死

### ISSUE THREAD

**Issue by Dacilia** [Tencent/QMUI_iOS#707]
**Bug 表现**
iOS13使用原生的UIImagePickerController显示Main Thread Checker: UI API called on a background thread: -[UIImageView image]
PID: 2655, TID: 679898, Thread name: (none), Queue name: com.apple.photos.plcropoverlay.save, QoS: 25   
并且界面卡死
**截图**
![2691569172781_ pic_hd](https://user-images.githubusercontent.com/16497552/65392062-fe283880-dda2-11e9-8328-b87a0ce2828d.jpg)
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![2701569174072_ pic_hd](https://user-images.githubusercontent.com/16497552/65392080-40ea1080-dda3-11e9-8853-3d3de02fc2ce.jpg)
**如何重现**
1.调用原生相机并且设置picker.allowsEditing = YES<重点代码>
```ios
UIImagePickerController*picker = [[UIImagePickerController alloc] init];
    picker.allowsEditing = YES;
    picker.delegate = self;
    picker.sourceType = UIImagePickerControllerSourceTypeCamera;
    [self presentViewController:picker animated:YES completion:nil];
```
**预期的表现**
正常情况下，应该是什么表现
不应该出现非主线程
**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11.0]
 - QMUI 版本: [4.0.0-beta]

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/65413753-b0541480-de24-11e9-946d-1c5d8498e224.png)

由截图可见，系统自身确实在非主线程调用了这些报错的 API，但只要我们的代码 swizzle 了这些 API，就会触发主线程的检测，如果不 swizzle 就不会触发，所以猜测应该是主线程检测的机制里有屏蔽了系统自己的使用场景。

所以这个情况其实并不会产生什么问题（因为是系统这么用，而不是 QMUI 这么用，只不过 QMUI swizzle 了这些代码所以暴露出这些问题而已），可以忽略，Release 模式下不会开启 Main Thread Checker，也就不会有卡顿产生。

**Comment by Dacilia** [comment]
你好 我切换到Release模式了   但是这个系统非主线程提示依旧存在哦 并且系统didFinishPickingMediaWithInfo方法也没有执行呢 （就是无法拿到编辑后的图片资源，我换了另一个没有继承QMUI 的项目则没有这个问题）
![2711569242172_ pic_hd](https://user-images.githubusercontent.com/16497552/65426002-ea7fdf00-de41-11e9-8004-65049767e8f2.jpg)
![2721569242201_ pic_hd](https://user-images.githubusercontent.com/16497552/65426005-ece23900-de41-11e9-860d-7d9479c90ee3.jpg)

**Comment by MoLice** [comment]
不好意思，说错了，只要你用 Xcode build 起来的 App，Main Thread Checker 都会自动运行，与 Debug/Release 无关，所以应该是 build 起来后 kill 掉，再手动从桌面点开 App，这时候 Main Thread Checker 才不会运行，就不会看到卡顿。

![image](https://user-images.githubusercontent.com/1190261/65427949-07b6ac80-de46-11e9-93c7-96815c1537a8.png)


至于 delegate 不被执行的问题我再看看。

**Comment by Dacilia** [comment]
嗯嗯 我就是利用QMUIConsole来显示控制台 的确按照你说的操作是不会卡顿了 但是代理方法不执行 麻烦你了 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MoLice"<notifications@github.com&gt;; 
发送时间: 2019年9月23日(星期一) 晚上9:06
收件人: "Tencent/QMUI_iOS"<QMUI_iOS@noreply.github.com&gt;; 
抄送: "粉肠蒸腊肉"<1257249648@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Tencent/QMUI_iOS] iOS13使用原生的UIImagePickerController页面卡死 (#707)




不好意思，说错了，只要你用 Xcode build 起来的 App，Main Thread Checker 都会自动运行，与 Debug/Release 无关，所以应该是 build 起来后 kill 掉，再手动从桌面点开 App，这时候 Main Thread Checker 才不会运行，就不会看到卡顿。
 

 
至于 delegate 不被执行的问题我再看看。

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/65428405-ea361280-de46-11e9-8d70-6408d6ec113c.png)

我用你的代码尝试了是可以调用的哦，只不过需要等到卡顿过去之后才会走到这里。

**Comment by Dacilia** [comment]
您好 确实是我的代码失误导致代理没有执行的 同时也感谢您对于我问题的重现以及测试，谢谢您了，由于我的失误给您带来的不便之处,敬请见谅 &nbsp;同时也衷心祝愿QMUI越来越好 嘻嘻 我已经把项目通过QMUI重构了 所以以后难免会有所打扰




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MoLice"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月23日(星期一) 晚上9:13
收件人:&nbsp;"Tencent/QMUI_iOS"<QMUI_iOS@noreply.github.com&gt;;
抄送:&nbsp;"粉肠蒸腊肉"<1257249648@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/QMUI_iOS] iOS13使用原生的UIImagePickerController页面卡死 (#707)





 
我用你的代码尝试了是可以调用的哦，只不过需要等到卡顿过去之后才会走到这里。

**Comment by MoLice** [comment]
不客气

**Comment by mustard22** [comment]
我也遇到了这问题（感觉代码没问题） 就是不走拍照后的代理方法

**Comment by xiaoyaoyouzi163com** [comment]
意思是可以不管 然后这个卡顿的现象 在实际上不会出现？
