### ISSUE TITLE
iOS 13适配 KVC QMUISearchController

### ISSUE THREAD

**Issue by ChinaJson** [Tencent/QMUI_iOS#708]
**Bug 表现**
具体怎么引起的,使用 QMUISearchController 后造成的奔溃

**截图**
<img width="1680" alt="屏幕快照 2019-09-23 上午10 30 59" src="https://user-images.githubusercontent.com/34496479/65399179-c98d9e80-dded-11e9-9f55-02ea401a56a2.png">

**如何重现**
1. 使用 QMUISearchController 搜索功能
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.0-beta]

**Comment by MoLice** [comment]
控制台有信息输出，请截图

**Comment by ChinaJson** [comment]
![屏幕快照 2019-09-23 下午2 54 15](https://user-images.githubusercontent.com/34496479/65406405-08355000-de12-11e9-8acb-34e3e76be682.png)

**Comment by ChinaJson** [comment]
![屏幕快照 2019-09-23 下午2 56 41](https://user-images.githubusercontent.com/34496479/65406501-5e09f800-de12-11e9-9702-1c047b10c8bd.png)

**Comment by MoLice** [comment]
请提供 Demo 看看

**Comment by ChinaJson** [comment]
已解决,自身处理searchBar背景颜色时直接把视图给删除了导致的崩溃,希望后续可以出一个自定义UISearchBar样式的接口

**Comment by MoLice** [comment]
@ChinaJson 这不是一个有效的 suggest，因为“自定义 UISearchBar 样式”是一个过于宽泛的表达，应该明确表达出具体是哪些样式要自定义但现在 UIKit、QMUI 的实现不方便。

如果只是背景颜色，UIKit 目前已经有 `barTintColor`、`setBackgroundImage:forBarPosition:barMetrics:`，而 QMUI 层面也在配置表里提供了 `SearchBarBackgroundImage`、`SearchBarBottomBorderColor`，从个人角度来看，我认为这已足够方便，并不需要动到 UISearchBar 内部的视图。

**Comment by ChinaJson** [comment]
好的，知道了，感谢你的贡献
---原始邮件---
发件人:"MoLice"<notifications@github.com>
发送时间:2019年9月27日 星期五 下午4:28
收件人:"Tencent/QMUI_iOS"<QMUI_iOS@noreply.github.com>
抄送:"ChinaJson"<1595371165@qq.com>;"Mention"<mention@noreply.github.com>
主题:Re: [Tencent/QMUI_iOS] iOS 13适配 KVC QMUISearchController (#708)

@ChinaJson这不是一个有效的 suggest，因为“自定义 UISearchBar 样式”是一个过于宽泛的表达，应该明确表达出具体是哪些样式要自定义但现在 UIKit、QMUI 的实现不方便。

如果只是背景颜色，UIKit 目前已经有barTintColor、setBackgroundImage:forBarPosition:barMetrics:，而 QMUI 层面也在配置表里提供了SearchBarBackgroundImage、SearchBarBottomBorderColor，从个人角度来看，我认为这已足够方便，并不需要动到 UISearchBar 内部的视图。

&mdash;
