### ISSUE TITLE
升级新版Xcode11后报错 无法通过编译

### ISSUE THREAD

**Issue by nanayashiki1215** [Tencent/QMUI_iOS#709]
**Bug 表现**
升级最新版Xcode11后报错 无法通过编译

**截图**
<img width="301" alt="image" src="https://user-images.githubusercontent.com/13127951/65403123-09ac4b80-de05-11e9-9510-28da47219ba6.png">

<img width="797" alt="image" src="https://user-images.githubusercontent.com/13127951/65403150-352f3600-de05-11e9-86e6-c2c61be8996d.png">

QMUIKit3.2.1

**Comment by MoLice** [comment]
旧版本不保证在 Xcode 11 下有正常表现，请使用最新版本。

**Comment by nanayashiki1215** [comment]
emmm,升级4.0.0后问题依然存在

**Comment by Double-Shuai** [comment]
我也遇到同样问题

**Comment by MoLice** [comment]
@nanayashiki1215 是否可以提供 Demo 看看？

**Comment by Double-Shuai** [comment]
> @nanayashiki1215 是否可以提供 Demo 看看？

我可以提供Demo，怎么发给您

**Comment by MoLice** [comment]
@Double-Shuai 直接打包 zip 丢到评论框里就可以上传了

**Comment by nanayashiki1215** [comment]
> > @nanayashiki1215 是否可以提供 Demo 看看？
> 
> 我可以提供Demo，怎么发给您

**Comment by MoLice** [comment]
@nanayashiki1215 Close 表示已经解决了？

**Comment by nanayashiki1215** [comment]
没有解决，不小心手滑了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: MoLice <notifications@github.com&gt;
发送时间: 2019年9月23日 16:34
收件人: Tencent/QMUI_iOS <QMUI_iOS@noreply.github.com&gt;
抄送: panhong <381500590@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[Tencent/QMUI_iOS] 升级新版Xcode11后报错 无法通过编译 (#709)




@nanayashiki1215 Close 表示已经解决了？

**Comment by nanayashiki1215** [comment]
@Double-Shuai 这个问题你解决了吗？

**Comment by Zhaoxinak** [comment]
怎么pod 4.0.0 beta 版本啊？

**Comment by nanayashiki1215** [comment]
@Zhaoxinak 我是直接下载代码作为子项目，然而现在发现4.0.0的Demo改了非常多的东西。。。

**Comment by nanayashiki1215** [comment]
@MoLice 无法上传大于10M的文件Demo，请问是否有其他方式能上传？

**Comment by MoLice** [comment]
@nanayashiki1215 你可以自己创建一个仓库传上去，再把地址贴过来

**Comment by nanayashiki1215** [comment]
@MoLice 自己尝试修复了几次，但还是一直报这个莫名的错误，现在用Xcode10.3或者10.2都可以运行编译，但就是Xcode11编译会报错，非常奇怪，而且无论3.2.1或者4.0.0的版本都是同样的问题，请查阅：https://github.com/nanayashiki1215/testQMUIDemo.git

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/65577509-8165ac00-dfa6-11e9-80c0-880012eeac83.png)

@nanayashiki1215 提供的 Demo 本身代码就有问题，无法编译，请先处理业务本身的问题。

另外这个 Demo 里使用的 QMUI 版本是 3.1.2，本身就不支持 Xcode 11，没有排查的意义，请提供一个引入 4.0.0-beta 版本的 Demo。

**Comment by nanayashiki1215** [comment]
@MoLice 好的，我删除了其他的依赖，您这边再试试看？因为现在本身问题就是运行不起来
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/13127951/65579921-49149c80-dfab-11e9-8d9b-4ad6c989183a.png">

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/65584691-d9ef7600-dfb3-11e9-957f-9cbe0d9086df.png)

@nanayashiki1215 确定你的项目里包含了 QMUI 的代码？我 clone 下来是不存在 QMUI 的。开源不易，时间宝贵，请自行排查。

**Comment by nanayashiki1215** [comment]
好吧
