### ISSUE TITLE
iOS13 Xcode11 运行崩溃

### ISSUE THREAD

**Issue by Merlini93** [Tencent/QMUI_iOS#710]
**Bug 表现**
1.新增属性adjustScrollIndicatorInsetsByContentInsetAdjustment和ignoreKVCAccessProhibited设置报错，直接崩溃。

2."QMUINavigationButton 607行block报错，直接崩溃。

以上报错均使用4.0.0beta版出现

**截图**
<img width="1127" alt="屏幕快照 2019-09-23 15 23 34" src="https://user-images.githubusercontent.com/11328707/65407882-79770200-de16-11e9-8f47-06d7a35a2b7e.png">
<img width="1116" alt="屏幕快照 2019-09-23 15 23 15" src="https://user-images.githubusercontent.com/11328707/65407909-8a277800-de16-11e9-905b-20f4609f8615.png">
<img width="1406" alt="屏幕快照 2019-09-23 15 21 57" src="https://user-images.githubusercontent.com/11328707/65407911-8c89d200-de16-11e9-9d07-2639546f3045.png">

**如何重现**
pod install后运行项目即报错，编译不报错

**其他信息**
 - 设备: 模拟器IPhone 11Pro max
 - iOS 版本: [iOS 13.0正式版]
 - Xcode 版本: [Xcode 11.0正式版]
 - QMUI 版本: [4.0.0-beta]

**Comment by MoLice** [comment]
有 clean 后尝试吗？

**Comment by Merlini93** [comment]
> 有 clean 后尝试吗？

Clean后运行成功，关闭问题
