### ISSUE TITLE
使用 GrowingIO 导致的启动死循环

### ISSUE THREAD

**Issue by MrHanbing** [Tencent/QMUI_iOS#712]
![企业微信截图_aed4d476-9afd-4104-97e1-11eb9cb664ec](https://user-images.githubusercontent.com/14346668/65427283-89a5d600-de44-11e9-9b46-c99645df26e1.png)
![企业微信截图_c631f080-8ed4-4ad1-bf57-2122372ba7ef](https://user-images.githubusercontent.com/14346668/65427298-988c8880-de44-11e9-961e-e9b65140f622.png)

**如何重现**
1. ...
2. ...

**其他信息**
 - 设备: iPhone
 - iOS 版本: iOS 13.]
 - Xcode 版本: [Xcode 11
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
死循环的问题，需要提供 Demo 才能排查。

**Comment by MrHanbing** [comment]
Demo  https://github.com/MrHanbing/QMUIDemo

**Comment by MrHanbing** [comment]
![企业微信截图_309642ac-c860-44fa-b3d9-14dc19fad27e](https://user-images.githubusercontent.com/14346668/65479624-c6171780-dec0-11e9-9f73-8d48d143b7cd.png)
注掉这段代码 就可以

**Comment by MrHanbing** [comment]
@MoLice  我们的两个项目 都遇到了这个问题，请问该怎么解决呢

**Comment by MrHanbing** [comment]
+ (void)initialize {
  static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
       [self appearance];
   });
}

都是崩在这个位置

**Comment by MoLice** [comment]
正在看，稍等

**Comment by MoLice** [comment]
请参考 #174，这不属于 QMUI 的问题。

**Comment by YXMo** [comment]
GrowingIO给出了解决方案，OC项目 在main函数里调用  [Growing setAspectMode:GrowingAspectModeDynamicSwizzling];

swift项目在appdelegate里这样处理就不会崩溃了 ：
 override init() {

         super.init()

           Growing.setAspectMode(GrowingAspectMode.dynamicSwizzling)
     }

**Comment by MoLice** [comment]
@YXMo 请问有官方处理方案的链接吗？

**Comment by YXMo** [comment]
@MoLice 没有的，这是我提工单后他们回复我的

**Comment by MoLice** [comment]
@YXMo 好的，那我在其他 GrowingIO 的 issue 里引用你的 comment 即可，感谢告知！
