### ISSUE TITLE
升级到4.0.0-beta后报错

### ISSUE THREAD

**Issue by huxq-coder** [Tencent/QMUI_iOS#713]
**Bug 表现**
Use of undeclared identifier 'DynamicPreferredValueForIPad'
 Expanded from macro 'PreferredValueForiPhone'

**截图**
![Snip20190923_1](https://user-images.githubusercontent.com/16077043/65429053-143c0480-de48-11e9-9350-86315b216d57.png)
![Snip20190923_2](https://user-images.githubusercontent.com/16077043/65429085-274ed480-de48-11e9-92c7-5d75bdbc6765.png)

**如何重现**
1. 编译报错

**其他信息**
 - 设备: [iPhone X]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.0-beta]

**Comment by MoLice** [comment]
clean 试过了吗？

**Comment by MoLice** [comment]
在 QMUI 代码里能搜到 DynamicPreferredValueForIPad 关键词吗？

**Comment by huxq-coder** [comment]
可以搜到的，


![1569289308324](https://user-images.githubusercontent.com/16077043/65474822-c529ba00-deaf-11e9-95f7-723b23c0e55b.jpg)

**Comment by MoLice** [comment]
能否提供Demo以供调试？

**Comment by huxq-coder** [comment]
感谢大佬的回复，问题解决了。
在使用PreferredValueForiPhone的类中，只引入了部分QMUI的头文件，4.0.0的DynamicPreferredValueForIPad是另一个类中声明的，未引入其头文件导致这个错误。

**Comment by MoLice** [comment]
这…不应该了…
