### ISSUE TITLE
升级4.0.0，无法引用相关类的问题

### ISSUE THREAD

**Issue by nanayashiki1215** [Tencent/QMUI_iOS#714]
**Bug 表现**
通过直接下载项目代码，使用动态库的形式植入，现在能引用<QMUIKit/QMUIKit.h>，但是却无法找到QMUICommonViewController，并已在Header Search Paths中配置了路径.

**截图**
<img width="791" alt="image" src="https://user-images.githubusercontent.com/13127951/65476195-af6ac380-deb4-11e9-860f-af2fd4676a0c.png">
<img width="615" alt="image" src="https://user-images.githubusercontent.com/13127951/65476282-fbb60380-deb4-11e9-8d1a-d45a440bfbfc.png">

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 12]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
这种问题建议提供Demo排查

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
