### ISSUE TITLE
13.0的系统，黑暗模式下有bug

### ISSUE THREAD

**Issue by insist159** [Tencent/QMUI_iOS#718]
**Bug 表现**
问题的具体描述
13.0的系统，黑暗模式下很多在配置文件里设置的都不起作用

**其他信息**
 - 设备: [iPhone、iPad]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
开源项目维护不易，“很多”意味着什么，请具体指出，节省时间。

**Comment by insist159** [comment]
@MoLice 解决了，强制把app的overrideUserInterfaceStyle模式改为UIUserInterfaceStyleLight 就行了，可能是黑暗模式为自主改变一些系统控件的颜色，导致我的配置文件可能会不起作用
