### ISSUE TITLE
storyboard中，tableview 使用static cell时，使用QMUICommonTableViewController作为基类报错

### ISSUE THREAD

**Issue by afxyubang** [Tencent/QMUI_iOS#720]
**Bug 表现**
storyboard中，tableview的content设置为static cell时，使用QMUICommonTableViewController作为view controller 的基类，xcode提示‘Static table views are only valid when embedded in UITableViewController instances’

**截图**
![image](https://user-images.githubusercontent.com/3362657/65563408-11dac700-df7c-11e9-9735-db8fb2158b85.png)

**预期的表现**
可以使用其他替换类

**其他信息**
 - 设备: 
 - iOS 版本: [iOS 13]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [QMUI 4.0.0，最新版本]

**Comment by MoLice** [comment]
重复 issue，请参考 #442。
