### ISSUE TITLE
Xcode 11下出现崩溃

### ISSUE THREAD

**Issue by Leopard92** [Tencent/QMUI_iOS#721]
<img width="1183" alt="屏幕快照 2019-09-25 上午10 57 41" src="https://user-images.githubusercontent.com/21326450/65565838-b280b500-df83-11e9-93fb-d61825684dbb.png">

**Comment by JXUnx1** [comment]
同遇到，更新了4.0.0。且将QMUICMI.ignoreKVCAccessProhibited = YES;   仍然在placeholder相关类别中崩溃。

**Comment by Leopard92** [comment]
> 同遇到，更新了4.0.0。且将QMUICMI.ignoreKVCAccessProhibited = YES; 仍然在placeholder相关类别中崩溃。

为什么我设置ignoreKVCAccessProhibited就在这句话这里崩溃了，我只能注释掉

**Comment by MoLice** [comment]
请提供 Demo 以供排查

**Comment by Leopard92** [comment]
> 请提供 Demo 以供排查

解决了，我把库移除重新添加，重新配置配置表就没有问题了
