### ISSUE TITLE
xcode 11下 iOS 13崩溃

### ISSUE THREAD

**Issue by yangxiutao** [Tencent/QMUI_iOS#723]
**Bug 表现**
xcode 11下 iOS 13崩溃，无法进入app

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/14293378/65649965-4cefff80-e03b-11e9-931a-28638d4b4b16.png)

**其他信息**
 - 设备: iPhone XS
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [3.2.1]

**Comment by fanjinhao** [comment]
我也是这样的错误

**Comment by foermo4-hao** [comment]
升级到4.0.0-bate 就好了

**Comment by fanjinhao** [comment]
嗯 我刚试了 问题解决了

**Comment by MoLice** [comment]
提issue前请先搜索是否已有相同issue，用 directionalLayoutMargins 至少能搜出来三四个…？？？
