### ISSUE TITLE
iOS 13 UITableView 配合 QMUIKeyboardManager 时出现的异常现象

### ISSUE THREAD

**Issue by codingiran** [Tencent/QMUI_iOS#725]
**Bug 表现**

使用 QMUITextView 自带的 QMUIKeyboardManager 来进行输入框的自动适应键盘升降，iOS 13 以下版本一切正常
升级到 iOS 13 之后发现一旦通过 UITableView 的 reloadRowsAtIndexPaths 方法进行刷新后，UITableView 的 setContentOffset 第一次会失效，详见 Demo.zip 里的代码
不确定这个问题是 QMUI 的问题 亦或 UIKit 自身的问题

**复现 Demo**

https://pan.baidu.com/s/1_j_mf2OQsm1daGmzWBLDuQ

**如何重现**

Demo 直接复现
[https://images.gitee.com/uploads/images/2019/0926/113942_ffde75ac_1986385.png](参考图片)

**其他信息**

 - 设备: iOS 13 +（真机 & 模拟器）
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.0.0-beta]

**Comment by MoLice** [comment]
这是 UIKit 系统的 bug，你可以看下方的 Demo，已经把 QMUI 去掉了，依然是有问题的。

[QMUIKeyboardManagerDemo 2.zip](https://github.com/Tencent/QMUI_iOS/files/3720726/QMUIKeyboardManagerDemo.2.zip)

有个规避方式，就是只要你的列表 contentSize.height 大于 tableView 可视区域的高度 + 键盘升起的高度（也即保证你把列表往上滚之后，底部依然有足够的空间）就不会有这个问题，你可以试试把 numberOfRows 改为 4，就不会有问题了。

这个我们暂时不处理。
