### ISSUE TITLE
判断机型的bug

### ISSUE THREAD

**Issue by friendsheeps** [Tencent/QMUI_iOS#726]
**Bug 表现**
用QMUICommonDefines里的宏判断机型在用iPhone11和iPhone 11Pro Max就会报错，因为QMUIHelper里判断机型使用了设备的Identifier，iPhone 11和iPhone 11Pro Max还没添加

**预期的表现**
一般用到机型是作UI适配，能不能通过SCREEN_WIDTH的宽度来区分或是加上这两个机型的判断，另外iOS13已经正式推送，请问什么时候可以发布正式版？

**其他信息**
 - 设备: [iPhone11]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.0-beta]

**Comment by MoLice** [comment]
master里已经加入identifier，会跟随新版本发布。新版本计划在本周内。

**Comment by MoLice** [comment]
已发布 [4.0.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0) 版本补充完整机型判断。
