### ISSUE TITLE
模态跳转带有NavigationController的崩溃

### ISSUE THREAD

**Issue by 2487464453** [Tencent/QMUI_iOS#727]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Client error attempting to change layout margins of a private view'
<img width="837" alt="image" src="https://user-images.githubusercontent.com/33675806/65671319-9e1ee400-e079-11e9-89fc-8cd79ce49533.png">

代码如下
LoginViewController * ctr = [[LoginViewController alloc] init];
    [self presentViewController:[[BaseNavigationController alloc] initWithRootViewController:ctr] animated:NO completion:nil];

**Comment by 2487464453** [comment]
系统:Xcode 11 运行在模拟器11 pro-13.0上

**Comment by MoLice** [comment]
重复 issue #628。
