### ISSUE TITLE
更新了Xcode 11后报错

### ISSUE THREAD

**Issue by wangmuge** [Tencent/QMUI_iOS#728]
2019-09-26 17:08:46.705870+0800 nookprint factory[15634:20924277] *** Assertion failure in -[_UINavigationBarContentView setDirectionalLayoutMargins:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3899.13.13/_UINavigationBarContentView.m:708
2019-09-26 17:08:46.749931+0800 nookprint factory[15634:20924277] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Client error attempting to change layout margins of a private view'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23b98958 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff255eb6f5 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff4681c298 -[_UINavigationBarContentView setDirectionalLayoutMargins:] + 203
	5   QMUIKit                             0x0000000106e10b6a __45+[UINavigationBar(QMUINavigationButton) load]_block_invoke_6 + 394
	6   QMUIKit                             0x0000000106e1175d __ExtendImplementationOfVoidMethodWithoutArguments_block_invoke_2 + 157
	7   QMUIKit                             0x0000000106e15e6d -[UINavigationBar(TitleView) titleView_navigationBarLayoutSubviews] + 1821
	8   UIKitCore                           0x00007fff47636722 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
	9   QMUIKit                             0x0000000106d2dd31 -[UIView(QMUI_CornerRadius) QMUICornerRadius_layoutSublayersOfLayer:] + 97
	10  QMUIKit                             0x0000000106ea5a21 -[UIView(QMUI_Border) QMUIBorder_layoutSublayersOfLayer:] + 97
	11  UIKitCore                           0x00007fff467eaf99 -[UINavigationBar layoutSublayersOfLayer:] + 248
	12  QuartzCore                          0x00007fff2b030ef9 -[CALayer layoutSublayers] + 255
	13  QuartzCore                          0x00007fff2b0358ff _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 517
	14  UIKitCore                           0x00007fff47621a35 -[UIView(Hierarchy) layoutBelowIfNeeded] + 980
	15  UIKitCore                           0x00007fff46a5055c -[UINavigationController _positionNavigationBarHidden:edge:initialOffset:] + 880
	16  UIKitCore                           0x00007fff46a507e0 -[UINavigationController _positionNavigationBarHidden:edge:] + 388
	17  UIKitCore                           0x00007fff46a5ac74 -[UINavigationController _updateBarsForCurrentInterfaceOrientationAndForceBarLayout:] + 145
	18  UIKitCore                           0x00007fff46b05081 -[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:] + 218
	19  UIKitCore                           0x00007fff46a57ccd -[UINavigationController viewDidMoveToWindow:shouldAppearOrDisappear:] + 69
	20  UIKitCore                           0x00007fff4762d085 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1402
	21  UIKitCore                           0x00007fff4762cdd3 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 712
	22  UIKitCore                           0x00007fff47620483 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 151
	23  UIKitCore                           0x00007fff47620373 -[UIView(Hierarchy) _postMovedFromSuperview:] + 753
	24  UIKitCore                           0x00007fff4762fb45 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1718
	25  QMUIKit                             0x0000000106e6bfd1 __28+[UIBarItem(QMUIBadge) load]_block_invoke_3 + 897
	26  QMUIKit                             0x0000000106ea3e6b -[UIView(QMUI) qmuiview_addSubview:] + 619
	27  UIKitCore                           0x00007fff46b24566 -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 3698
	28  UIKitCore                           0x00007fff46b2c49e ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 54
	29  UIKitCore                           0x00007fff46c41ece +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] + 99
	30  UIKitCore                           0x00007fff46b2c432 ___UIViewControllerTransitioningRunCustomTransition_block_invoke.645 + 180
	31  UIKitCore                           0x00007fff47628751 +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 175
	32  UIKitCore                           0x00007fff46b2c2b8 _UIViewControllerTransitioningRunCustomTransition + 553
	33  UIKitCore                           0x00007fff46a0fccb __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.452 + 2632
	34  UIKitCore                           0x00007fff46a1548f +[UIPresentationController _scheduleTransition:] + 79
	35  UIKitCore                           0x00007fff46a0f01b -[UIPresentationController runTransitionForCurrentState] + 1692
	36  UIKitCore                           0x00007fff46a0c64e -[UIPresentationController _presentWithAnimationController:interactionController:target:didEndSelector:] + 1060
	37  UIKitCore                           0x00007fff47199c46 -[UIWindow addRootViewControllerViewIfPossible] + 391
	38  UIKitCore                           0x00007fff4719920b -[UIWindow _updateLayerOrderingAndSetLayerHidden:actionBlock:] + 232
	39  UIKitCore                           0x00007fff4719a2c9 -[UIWindow _setHidden:forced:] + 362
	40  UIKitCore                           0x00007fff471ad46d -[UIWindow _mainQueue_makeKeyAndVisible] + 42
	41  UIKitCore                           0x00007fff4715b3c2 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 4199
	42  UIKitCore                           0x00007fff47160c05 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1281
	43  UIKitCore                           0x00007fff468b58b1 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
	44  UIKitCore                           0x00007fff46d96cd5 _UIScenePerformActionsWithLifecycleActionMask + 83
	45  UIKitCore                           0x00007fff468b63c3 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	46  UIKitCore                           0x00007fff468b5e84 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 474
	47  UIKitCore                           0x00007fff468b61f3 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 821
	48  UIKitCore                           0x00007fff468b5a85 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	49  UIKitCore                           0x00007fff468b9e70 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2 + 159
	50  UIKitCore                           0x00007fff46cbdf8b +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 865
	51  UIKitCore                           0x00007fff46db51cf _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	52  UIKitCore                           0x00007fff468b9b9e __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 153
	53  UIKitCore                           0x00007fff46db50d2 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 84
	54  UIKitCore                           0x00007fff468b9a0c -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 381
	55  UIKitCore                           0x00007fff46717c96 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 657
	56  UIKitCore                           0x00007fff4671681b -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
	57  UIKitCore                           0x00007fff467179c0 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 210
	58  UIKitCore                           0x00007fff4715f262 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 535
	59  UIKitCore                           0x00007fff46cdf774 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	60  FrontBoardServices                  0x00007fff362e1d43 -[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 442
	61  FrontBoardServices                  0x00007fff3630a00c __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
	62  FrontBoardServices                  0x00007fff362ecd21 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
	63  FrontBoardServices                  0x00007fff36309c9d __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
	64  libdispatch.dylib                   0x0000000107fc9d64 _dispatch_client_callout + 8
	65  libdispatch.dylib                   0x0000000107fcccd5 _dispatch_block_invoke_direct + 300
	66  FrontBoardServices                  0x00007fff3633108a __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	67  FrontBoardServices                  0x00007fff36330d78 -[FBSSerialQueue _queue_performNextIfPossible] + 441
	68  FrontBoardServices                  0x00007fff36331287 -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	69  CoreFoundation                      0x00007fff23afbac1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	70  CoreFoundation                      0x00007fff23afb9ec __CFRunLoopDoSource0 + 76
	71  CoreFoundation                      0x00007fff23afb1c4 __CFRunLoopDoSources0 + 180
	72  CoreFoundation                      0x00007fff23af5ecf __CFRunLoopRun + 1263
	73  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	74  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	75  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	76  nookprint factory                   0x000000010540b3ab main + 75
	77  libdyld.dylib                       0x00007fff5123bcf5 start + 1
	78  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by MoLice** [comment]
随手一搜，多个重复，请养成良好的开源项目提 issue 习惯。该问题参考 #628，升级新版本。

https://github.com/Tencent/QMUI_iOS/issues?utf8=%E2%9C%93&q=setDirectionalLayoutMargins

![image](https://user-images.githubusercontent.com/1190261/65677108-9a905a80-e083-11e9-9068-00205b655fea.png)
