### ISSUE TITLE
_UINavigationBarContentView setDirectionalLayoutMargins 崩溃

### ISSUE THREAD

**Issue by Gosling-Dong** [Tencent/QMUI_iOS#729]
**Bug 表现**
启动就崩溃

// 强制修改 contentView 的 directionalLayoutMargins.leading，在使用自定义返回按钮时减小 8
        if (@available(iOS 11, *)) {
            ExtendImplementationOfVoidMethodWithoutArguments([UINavigationBar class], @selector(layoutSubviews), ^(UINavigationBar *selfObject) {
                UIView *contentView = selfObject.qmui_contentView;
                if (contentView) {
                    NSDirectionalEdgeInsets value = contentView.directionalLayoutMargins;
                    value.leading = value.trailing - (selfObject.qmui_customizingBackBarButtonItem ? 8 : 0);
                    contentView.directionalLayoutMargins = value;
                }
            }

**其他信息**
真机-iOS13 Xcode11

**Comment by MoLice** [comment]
随手一搜，都是重复 issue，请养成良好的开源项目提 issue 习惯，提之前先搜索。
https://github.com/Tencent/QMUI_iOS/issues?utf8=%E2%9C%93&q=directionalLayoutMargins

![image](https://user-images.githubusercontent.com/1190261/65681847-505fa700-e08c-11e9-9e4b-d16623239f71.png)

这个问题请参考 #628，升级版本。
