### ISSUE TITLE
iOS13环境下QMUIBadge数字显示位置不准确

### ISSUE THREAD

**Issue by Dacilia** [Tencent/QMUI_iOS#730]
**Bug 表现**
问题的具体描述
iOS13环境下QMUIBadge数字显示位置不准确
**截图**
![2781569511363_ pic](https://user-images.githubusercontent.com/16497552/65702123-0c34cc80-e0b5-11e9-9616-dfbc9c5a4591.jpg)

**如何重现**
1. 打开QMUIDemo 点击components->点击QMUIBadge就可以看到99+的显示位置不准确
2. ...

**预期的表现**
应该显示在Components的右上方

**其他信息**
 - 设备: iPhone
 - iOS 版本: [iOS 13]
 - Xcode 版本: [Xcode 11.]
 - QMUI 版本: [4.00-beta]

**Comment by Dacilia** [comment]
iphonex

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/697#issuecomment-533105960

请参考这个
