### ISSUE TITLE
导航栏返回崩溃

### ISSUE THREAD

**Issue by wangkai4090** [Tencent/QMUI_iOS#731]
**Bug 表现**
点击导航栏返回按钮崩溃

<img width="1531" alt="WX20190927-114324@2x" src="https://user-images.githubusercontent.com/45187987/65740873-ce6b8e80-e11c-11e9-9cf2-45db04634e88.png">
<img width="795" alt="WX20190927-114415@2x" src="https://user-images.githubusercontent.com/45187987/65740892-db887d80-e11c-11e9-9ed1-3c2579e40644.png">

**其他信息**
 - 设备: ### [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: ### [4.0.0-beta]

**Comment by MoLice** [comment]
从控制台的信息来看，或许应该看 JXBaseNaviController 里的 _popNavigationBar:item: 方法？

**Comment by wangkai4090** [comment]
不是那个方法，是进入了第一个图的那段代码后崩溃的

**Comment by wangkai4090** [comment]
只有iOS13崩溃的

**Comment by MoLice** [comment]
请提供Demo并说明操作步骤

**Comment by MoLice** [comment]
该issue因不活跃而被关闭。
