### ISSUE TITLE
QMUIViewControllerVisibleState注释错位

### ISSUE THREAD

**Issue by bluerainxty** [Tencent/QMUI_iOS#733]
![企业微信截图_41a63371-8988-491a-b3b7-b968a9ef592a](https://user-images.githubusercontent.com/13965551/65758408-a5aebd80-e14b-11e9-8638-9c2f62837ad3.png)
这里由/// 注释的本意应该是前面的枚举，但实际上是作用于了下一行的枚举

**Comment by MoLice** [comment]
有点意思，改了，下个版本带上。
