### ISSUE TITLE
无法隐藏UINavigationBar.shadowImage

### ISSUE THREAD

**Issue by jhchenchong** [Tencent/QMUI_iOS#735]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
？

**Comment by jhchenchong** [comment]
刚刚仔细看过代码了 新版本的隐藏UINavigationBar的shadowImage需要配合NavBarShadowImageColor这个使用才能生效。不好意思。

**Comment by YSYou1234** [comment]
同样遇到了这个问题，发现就是release说明里的“如何适配新版”中里漏了这一个配置表的中NavBarShadowImageColor的设置。建议有空补上。

**Comment by MoLice** [comment]
@YSYou1234 看了一下确实是，感谢提醒，已修改：

![image](https://user-images.githubusercontent.com/1190261/66830726-c323ba00-ef88-11e9-81cd-be2a4768904b.png)
