### ISSUE TITLE
自定义返回按钮点击返回或滑动返回，返回按钮重叠

### ISSUE THREAD

**Issue by Steven-Yung** [Tencent/QMUI_iOS#737]
**Bug 表现**
自定义返回按钮点击返回或滑动返回，返回过程中按钮出现重影

**截图**
![WechatIMG29362](https://user-images.githubusercontent.com/8358206/65824850-005a2d80-e2a2-11e9-890b-a4af75acbf1c.png)

**如何重现**
1. UIBarButtonItem *item = [UIBarButtonItem qmui_backItemWithTarget:self action:@selector(handleBackButtonEvent:)];
   self.navigationItem.leftBarButtonItem = item;
2. 点击返回按钮或滑动返回

**预期的表现**
返回过程中无重影现象

**其他信息**
 - 设备: iPhone
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [3.2.1]

**Comment by TheLittleBoy** [comment]
建议你试试最新的4.0.0版本

**Comment by MoLice** [comment]
这是已知问题，待解决。

**Comment by MoLice** [comment]
已发布 [4.0.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.1) 修复 iOS 12 及以下的问题，iOS 13 某些场景下依然可能有问题，这个后续版本再修复。
