### ISSUE TITLE
Xcode 11下报错*** Assertion failure in -[_UINavigationBarContentView setDirectionalLayoutMargins:]

### ISSUE THREAD

**Issue by CoderXXLee** [Tencent/QMUI_iOS#738]
**Bug 表现**
*** Assertion failure in -[_UINavigationBarContentView setDirectionalLayoutMargins:]

**截图**

**Comment by MoLice** [comment]
这已经是两个版本前就修复的问题了，提issue前请先搜索已有issue，有七八个重复issue。

**Comment by CoderXXLee** [comment]
> 这已经是两个版本前就修复的问题了，提issue前请先搜索已有issue，有七八个重复issue。

收到
