### ISSUE TITLE
iOS 13 通过 UITabBarAppearance 为 tabBarItem 设置字号大于10时，item 的文字被截断

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#740]
**Bug 表现**
配置表里面设置TabBarItemTitleFont
TabBarItemTitleFont系统默认字体是font-family: ".SFUI-Medium"; font-weight: normal; font-style: normal; font-size: 10.00pt
当TabBarItemTitleFont 字号>10时， UITabBarButtonLabel文字显示不全

**截图**
![D805855A-1051-48EE-8098-C9CF1A836435](https://user-images.githubusercontent.com/34535969/65848947-e3455d80-e37a-11e9-9389-4d70606434a4.png)

**如何重现**
QMUICMI.tabBarItemTitleFont = [UIFont systemFontOfSize:12];  

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11.0]
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
这是苹果的bug，我们再看如何处理。

**Comment by bluerainxty** [comment]
我也发现了这个问题，不指定字体就没问题

**Comment by MoLice** [comment]
系统 bug，重现的 Demo 如下：
[TestTabBarItemFont.zip](https://github.com/Tencent/QMUI_iOS/files/3670706/TestTabBarItemFont.zip)

QMUI 内部版本已对此做兼容，下个版本会带上，在此之前可以将以下代码添加到本地 QMUI 的 UITabBar+QMUI.m `+load` 方法中。

```Objective-C
if (@available(iOS 13.0, *)) {
    OverrideImplementation(NSClassFromString(@"UITabBarButtonLabel"), @selector(setAttributedText:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP (^originalIMPProvider)(void)) {
        return ^(UILabel *selfObject, NSAttributedString *firstArgv) {
            
            // call super
            void (*originSelectorIMP)(id, SEL, NSAttributedString *);
            originSelectorIMP = (void (*)(id, SEL, NSAttributedString *))originalIMPProvider();
            originSelectorIMP(selfObject, originCMD, firstArgv);
            
            CGFloat fontSize = selfObject.font.pointSize;
            if (fontSize > 10) {
                [selfObject sizeToFit];
            }
        };
    });
}
```

**Comment by MoLice** [comment]
已发布 [4.0.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.1) 修复该系统问题。
