### ISSUE TITLE
苹果不接受使用UIWebView APIs 的包

### ISSUE THREAD

**Issue by bluerainxty** [Tencent/QMUI_iOS#741]
![企业微信截图_e1577db4-ad46-4dbf-906b-821b165c879f](https://user-images.githubusercontent.com/13965551/65854338-f6fabf00-e38e-11e9-893a-3f68feb95615.png)

**Comment by MoLice** [comment]
是的，然后…？

**Comment by bluerainxty** [comment]
> 是的，然后…？

QMUIKit里有使用UIWebView，在UIView+QMUI.m的第458行

**Comment by MoLice** [comment]
这里可以直接去掉 UIWebView.class，下个版本带上

**Comment by MoLice** [comment]
已发布 [4.0.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.1) 修复该问题。
