### ISSUE TITLE
QMUINavigationButton iOS13.1.1崩溃

### ISSUE THREAD

**Issue by chuzhaozhi** [Tencent/QMUI_iOS#742]
**Bug 表现**
启动app直接崩溃

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/18342190/65856602-ac7c4100-e394-11e9-83b7-1d2d4452f2e1.png)
![image](https://user-images.githubusercontent.com/18342190/65856611-b2722200-e394-11e9-934a-79b102d4ede7.png)

**如何重现**
iOS13.1.1系统，集成Qmui

**预期的表现**
不会奔溃

**其他信息**
 - 设备: iPhone 6s Plus
 - iOS 版本: iOS13.1.1
 - Xcode 版本:Xcode 11
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
这是第十个重复issue了吧，提issue前，麻烦节省双方生命，先搜一搜，directionalLayoutMargins？

参考#628，修复距今两个版本了。
