### ISSUE TITLE
Xcode 11 cocoapods集成 4.0.0问题

### ISSUE THREAD

**Issue by coldmn3** [Tencent/QMUI_iOS#744]
**Bug 表现**
使用Xcode 11集成 4.0.0 及 4.0.0-beta版本时 运行会报错
[framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'QMUI.QMUIResources'

**预期的表现**
普通使用没有问题，但是集成主题代码时会崩溃

**其他信息**
 - 设备: iPhone 7
 - iOS 版本: iOS 13.1
 - Xcode 版本: Xcode 11
 - QMUI 版本: 4.0.0

**Comment by MoLice** [comment]
是否可以提供一个 Demo 我们看看？
