### ISSUE TITLE
QMUIDialogViewController确定按钮，hide之后再次show 按钮颜色会变回默认的淡蓝色

### ISSUE THREAD

**Issue by xiaoyaoyouzi163com** [Tencent/QMUI_iOS#751]
**Bug 表现**
问题的具体描述
QMUIDialogViewController确定按钮，hide之后再次show 按钮颜色会变回默认的淡蓝色
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

![1111](https://user-images.githubusercontent.com/18432248/66448219-72412c80-ea83-11e9-8085-6c279911388c.png)
![2222](https://user-images.githubusercontent.com/18432248/66448221-72d9c300-ea83-11e9-86a9-f1eff93b38e6.png)

**如何重现**
代码：
self.header?.enterPriceClick = {[weak self] in
            
            self?.diag?.show()
        }
        let cateArr = [
            ["id":"1","name":"￥10"],
            ["id":"2","name":"￥20"],
            ["id":"3","name":"￥30"],
            ["id":"4","name":"￥40"],
            ["id":"5","name":"￥50"],
            ["id":"6","name":"￥60"],
            ["id":"7","name":"￥70"],
            ["id":"8","name":"￥80"],
            ["id":"9","name":"￥90"],
            ["id":"10","name":"￥100"],
            ["id":"11","name":"￥110"],
            ["id":"12","name":"￥120"],
            ["id":"13","name":"￥200"],
        ]
        let container = ZDTipsContainerView.init()
        container.cateArr = cateArr
        container.selectId = "1"
        weak var tempContainer = container
        let diag = QMUIDialogViewController.init()
        diag.title = "请选择课程价格"
        diag.contentView = container
        diag.buttonBackgroundColor = UIColor.init(hexString: "#E83828")
        diag.buttonTitleAttributes = [NSAttributedString.Key.foregroundColor:UIColor.init(hex: "#FFFFFF")!]
        diag.addSubmitButton(withText: "确定") {[weak self] (diag0) in
            guard let item = tempContainer?.selectItem else{
                return
            }
            SVProgressHUD.showInfo(withStatus: item["name"])
            self?.header?.priceLabel?.text = item["name"]
            diag0.hide()
            
        }
        self.diag = diag
**预期的表现**
颜色不变化
**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11.0]
 - QMUI 版本: [4.0.0]

**Comment by xiaoyaoyouzi163com** [comment]
刚刚升级到了4.0.0 问题依然存在

**Comment by MoLice** [comment]
# 问题原因

这个问题是因为 QMUIDialogViewController 底部的 cancelButton、submitButton 在初始化时都被指定了 `adjustsTitleTintColorAutomatically = YES`：

![image](https://user-images.githubusercontent.com/1190261/66554229-2f647f00-eb7f-11e9-9142-e9327bba0b67.png)

一旦一个 QMUIButton.adjustsTitleTintColorAutomatically = YES，意味着它的文字颜色会自动跟随 tintColor 的变化而变化，在 QMUIButton 被 add 到 window 上时，它的 tintColor 就会自动设置一遍。所以当你 hide 后再重新 show，触发了 `QMUIButton.adjustsTitleTintColorAutomatically`，导致按钮文字颜色被重置为 button 的 tintColor，而 QMUIButton 默认的 tintColor 是配置表的 `ButtonTintColor`：

![image](https://user-images.githubusercontent.com/1190261/66554366-70f52a00-eb7f-11e9-946f-1ae06a8f07ec.png)

在 QMUI Demo 里， 它的值刚好和 `QMUIDialogViewController.buttonTitleAttributes[NSForegroundColorAttributeName]` 的值相同，都是蓝色，于是看起来就像是恢复了 QMUIDialogViewController 默认的按钮颜色一样。

QMUIDialogViewController 初始化按钮时的这句 `adjustsTitleTintColorAutomatically = YES` 其实是错误的，当初这么写的想法是希望你在配置表里修改 `ButtonTintColor` 时，dialog 的按钮颜色也可以自动变，但其实 dialog 的按钮颜色已经有特定的 property 去控制了（也即 buttonTitleAttributes），所以不应该再添加 `adjustsTitleTintColorAutomatically`。

# 解决方法

内部版本里已经将 `adjustsTitleTintColorAutomatically = YES` 删掉，等新版发布即可，你也可以这样修改自己本地的 QMUI 代码。

如果不想修改本地 QMUI 代码，也可以在你贴出来的那段 dialog 代码里加上：
```Objective-C
diag.addSubmitButton(...)
// 添加完 button 后，手动修改为 false
diag.submitButton.adjustsTitleTintColorAutomatically = false
```

**Comment by MoLice** [comment]
已发布 [4.0.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.1) 修复该问题。

**Comment by xiaoyaoyouzi163com** [comment]
今天才过来看到，非常感谢
