### ISSUE TITLE
Xcode 11开启Mac支持后编译报错

### ISSUE THREAD

**Issue by 0x10000** [Tencent/QMUI_iOS#752]
**Bug 表现**
Xcode 11开启Mac支持后编译报错

**截图**
<img width="851" alt="WX20191009-123145@2x" src="https://user-images.githubusercontent.com/10739191/66451869-db7b6c80-ea90-11e9-8609-9bac7fe48398.png">

**Comment by MoLice** [comment]
QMUI 4.0.0 目前并不支持勾选 Mac，后续是否有支持，请关注每个版本的 Release Note。
