### ISSUE TITLE
+ (UIColor *)qmui_colorWithHexString:(NSString *)hexString此方法希望可以增加alpha参数

### ISSUE THREAD

**Issue by ZhangTonghai** [Tencent/QMUI_iOS#753]
如题，希望可以增加alpha，目前实现上默认了rrggbb这种方式alpha为1。
多谢！

**Comment by MoLice** [comment]
请查看注释....

![image](https://user-images.githubusercontent.com/1190261/66466449-50609d80-eab5-11e9-85a6-9c1d76f7ba66.png)

**Comment by ZhangTonghai** [comment]
多谢回复。
看过注释了，因为拼接在hexstring上略麻烦才提的。

**Comment by MoLice** [comment]
那你期望的使用语法是什么？

**Comment by ZhangTonghai** [comment]
> 那你期望的使用语法是什么？

希望alpha的作为方该法的一个参数，浮点数类型，好比
+ (UIColor *)qmui_colorWithHexString:(NSString *)hexString alpha:(CGFloat)alpha
主要是我们的设计图中颜色和透明度是两个独立的值，经常会有类似0.85这样的透明度，所以使用这个扩展方法时有注意没有透明度的参数，后来看了实现和注释也看到了如何支持透明度，个人觉得使用一个单独的参数来指定alpha更方便和直观一点点。

**Comment by MoLice** [comment]
从 API 设计的角度来看，你期望的语法融合了两种颜色的表达方式，并不是很标准，不适合在 QMUI 里提供。你可以直接自己加个 Category，在里面直接调用 `[[UIColor qmui_colorWithHexString:xxx] colorWithAlphaComponent:] 就好了。
