### ISSUE TITLE
iOS13下，初始化设置NavigationBar，引发崩溃

### ISSUE THREAD

**Issue by CoderChenJun** [Tencent/QMUI_iOS#755]
**Bug 表现**
问题的具体描述
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/20350701/66530447-70867000-eb3a-11e9-8dd4-daa8567b4921.png">

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/20350701/66530465-7f6d2280-eb3a-11e9-9b67-6c08adf9e757.png">

**如何重现**
https://www.jianshu.com/p/f6455cb0bb68

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: iPhone X
 - iOS 版本: [iOS 13.1.2]
 - Xcode 版本: [Xcode 11.0]
 - QMUI 版本: [3.1.9]

**Comment by haohaoyin** [comment]
坐等更新

**Comment by MoLice** [comment]
这是第 7 个重复 issue

![image](https://user-images.githubusercontent.com/1190261/66547508-f8d43780-eb71-11e9-95b6-6071c199c938.png)
