### ISSUE TITLE
配置表感觉太复杂了

### ISSUE THREAD

**Issue by coldmn3** [Tencent/QMUI_iOS#756]
配置表感觉太massive,太复杂了，版本升级也经常需要修改，一不小心就会出错。是否考虑内置主题等方式。用户通过代码修改想要修改的属性，毕竟大部分默认属性是不会改的。

**Comment by MoLice** [comment]
这个问题里有几点：
1. 升级版本经常需要修改：
    升级版本时为什么配置表需要修改，是因为配置表对应的那些功能在这个版本里发生了变动，因此不管用不用配置表，只要某些功能在这个版本里发生了变动，你都需要修改。但有一个取巧的方式，你可以继承官方的配置表模板，自己搞一个子类，这样你可以只在子类里写你用到的配置项，你不关心的配置项就不需要出现在子类里，版本升级时你用官方模板直接覆盖你的父类就可以了，具体可以参考 QMUIDemo 5 套主题里除了 Default 外的其他主题。

2. 通过代码修改想要修改的属性：
    配置表本来就是“用户通过代码修改想要的属性”的方式，只是把常用的修改点都陈列到一起了。配置表设计的目的是”常用的改动，不管是什么，都到配置表里改一改就能生效，避免了到处找代码的麻烦“，而如果按你说的方式去做，就失去了配置表最开始的目的。不用配置表的话，还可以有什么方式能做到既满足这个目的又方便用户自定义呢？

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
