### ISSUE TITLE
在App-Extension里使用QMUIKit时遇到的问题

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#757]
在App-Extension里使用QMUIKit时，需要关闭
<img width="382" alt="图片" src="https://user-images.githubusercontent.com/22904757/66618667-806e8480-ec0c-11e9-8a49-8f8e97c2f9cd.png">
每次Pod时，需要去设置一遍，能否在代码里规避这一项？
比如说 [[[NSBundle mainBundle] bundlePath] hasSuffix:@".appex"]  检测到存在扩展时不使用相关API

**Comment by MoLice** [comment]
适配 App-Extension 这个改动有点大，暂时应该不会处理
