### ISSUE TITLE
[QMUIHelper visibleViewController] 在使用了 UIWindowSceneDelegate 的项目中无法使用

### ISSUE THREAD

**Issue by MQL9011** [Tencent/QMUI_iOS#759]
**Bug 表现**
xcode11, Swift工程
QMUIHelper visibleViewController方法在xcode11新工程下崩溃
猜测可能是因为xcode11新工程引入了SceneDelegate,导致rootWindow持有者已经不是AppDelegate了.

**截图**
![image](https://user-images.githubusercontent.com/11871158/66696463-c99f0100-ecfe-11e9-8784-0bd2fadfb478.png)

![image](https://user-images.githubusercontent.com/11871158/66696494-14b91400-ecff-11e9-9f00-6409e6b92f48.png)

**如何重现**
用xcode11新建个新swift工程, 执行下
```
QMUIHelper.visibleViewController()
```

**其他信息**
 - iOS 版本: [iOS 13]
 - Xcode 版本: [Xcode 11.1]
 - QMUI 版本: [4.0.0]

**Comment by derekhuangxu** [comment]
遇到了同一个问题，期望能早点解决。辛苦！

**Comment by MoLice** [comment]
UIScene 问题统一由 #766 跟进。
