### ISSUE TITLE
QMUITableViewCell的imageView.frame在Xcode11运行后位置偏左了

### ISSUE THREAD

**Issue by YJPizazz** [Tencent/QMUI_iOS#760]
**Bug 表现**
在Xcode11的环境下，QMUITableViewCell的imageView.frame不对，整体偏左了。
使用QMUI的演示Demo，在Xcode11（左图）和Xcode10（右图）效果如下：

**截图**
<img width="851" alt="WX20191012-165006@2x" src="https://user-images.githubusercontent.com/16317734/66698405-61f1b180-ed10-11e9-86b0-860c511e8916.png">

**如何重现**
分别使用Xcode11和Xcode10跑QMUI的演示Demo即可，然后对比一下效果
（其实图片也不一样了）

**预期的表现**
QMUITableViewCell的imageView.frame保持一致

**其他信息**
 - 设备: [iPhone X]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11.1 和 Xcode 10.3]
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
请使用系统的 UITableViewCell 看是否也是有差异？

**Comment by YJPizazz** [comment]
系统的 UITableViewCell 能正常显示的，我改了qmui示例代码来验证的。
[https://github.com/QMUI/QMUIDemo_iOS](https://github.com/QMUI/QMUIDemo_iOS)

你可以试一下，把QDTableViewCellInsetsViewController中的QMUITableViewCell改成UITableViewCell，然后对比一下效果。

**Comment by MoLice** [comment]
等新版本发布即可，在此之前你可以先在本地把 QMUITableViewCell.m 里的 layoutMargins 方法删掉。

**Comment by friendsheeps** [comment]
删掉layoutMargins，带imageView的cell样式正常了，但是没有imageView，textLabel的位置还是会向左偏移，UITableViewCell和QMUITableViewCell都会，能不能提供一个属性来自己设置一下左边距？

**Comment by MoLice** [comment]
@friendsheeps 如果是 UITableViewCell 在不同 iOS 版本也有不一样的展现的话，由于调整系统的 contentView 内部布局成本比较大，容易出问题，这个我们暂时不处理，建议可以业务自行重写 subclass 去调整 layoutMargins 或者 layoutSubviews。
