### ISSUE TITLE
iOS 13 之前 为了实现 TabBarItemImageColorSelected 功能，忘记重写 initWithCoder 方法

### ISSUE THREAD

**Issue by Jonas-o** [Tencent/QMUI_iOS#763]
**Bug 表现**
iOS 之前的系统，如果 tabBarController 是通过 storyboard 创建的时候，TabBarItemImageColorSelected 的设置不起作用

**截图**
![image](https://user-images.githubusercontent.com/31504742/66718479-04945800-ee17-11e9-95b2-bad5d8fcd314.png)

**其他信息**
 - iOS 版本: [iOS 13 之前]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
这是符合预期的，当你使用 xib，配置表就不应该去覆盖你的值，因为你应该在 xib 里自己去修改，这本来也是 xib 的使用方式。

从技术上 QMUI 是可以判断从 xib 加载完后，如果某个颜色依然是 system tintColor，就简单地认为“你没有在 xib 里自定义过”，于是 QMUI 就用配置表的值去覆盖 xib 的值。但这是有问题的，万一你在 xib 里就是想用 system tintColor，那就会被错误地覆盖。

使用 xib 就无法很好地用代码的形式去统一管理 color，但这个本身就是 xib 的特性，所以在这个场景下 QMUI 的处理是正确的。
