### ISSUE TITLE
UIImage+QMUITheme 在 Xcode 10 下编译失败

### ISSUE THREAD

**Issue by FantasticSkyBaby** [Tencent/QMUI_iOS#764]
**Bug 表现**
JENKINS 打包报错

**截图**

** ARCHIVE FAILED **
The following build commands failed:
	CompileC /Users//Library/Developer/Xcode/DerivedData/ios-bwbcdqcxmaleojfrqhrwrsxpxanz/Build/Intermediates.noindex/ArchiveIntermediates/ios/IntermediateBuildFilesPath/QMUIKit.build/Debug-iphoneos/QMUIKit.build/Objects-normal/armv7/UIImage+QMUITheme.o /Users/mac/JENKINS/workspace/iOS-Mobile/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
项目构建失败 😢 😢 😢

Mobile/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:275:4: error: expected a type
- (UIImageConfiguration *)configuration {
   ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:279:38: error: expected a type
- (UIImage *)imageWithConfiguration:(UIImageConfiguration *)configuration {
                                     ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:283:4: error: expected a type
- (UIImageSymbolConfiguration *)symbolConfiguration {
   ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:287:50: error: expected a type
- (UIImage *)imageByApplyingSymbolConfiguration:(UIImageSymbolConfiguration *)configuration {
                                                 ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:172:31: error: property 'isSymbolImage' not found on object of type 'UIImage *'
    return self.qmui_rawImage.isSymbolImage;
                              ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:260:31: error: property 'baselineOffsetFromBottom' not found on object of type 'UIImage *'
    return self.qmui_rawImage.baselineOffsetFromBottom;
                              ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:264:31: error: property 'hasBaseline' not found on object of type 'UIImage *'
    return self.qmui_rawImage.hasBaseline;
                              ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:268:32: error: no visible @interface for 'UIImage' declares the selector 'imageWithBaselineOffsetFromBottom:'
    return [self.qmui_rawImage imageWithBaselineOffsetFromBottom:baselineOffset];
            ~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:272:31: error: property 'imageWithoutBaseline' not found on object of type 'UIImage *'
    return self.qmui_rawImage.imageWithoutBaseline;
                              ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:276:31: error: property 'configuration' not found on object of type 'UIImage *'
    return self.qmui_rawImage.configuration;
                              ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:280:32: error: no visible @interface for 'UIImage' declares the selector 'imageWithConfiguration:'
    return [self.qmui_rawImage imageWithConfiguration:configuration];
            ~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:284:31: error: property 'symbolConfiguration' not found on object of type 'UIImage *'
    return self.qmui_rawImage.symbolConfiguration;
                              ^
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:288:32: error: no visible @interface for 'UIImage' declares the selector 'imageByApplyingSymbolConfiguration:'
    return [self.qmui_rawImage imageByApplyingSymbolConfiguration:configuration];
            ~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:292:32: error: no visible @interface for 'UIImage' declares the selector 'imageWithTintColor:'
    return [self.qmui_rawImage imageWithTintColor:color];
            ~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~
/Users/mac/JENKINS/workspace/IOS/Pods/QMUIKit/QMUIKit/QMUIComponents/QMUITheme/UIImage+QMUITheme.m:296:32: error: no visible @interface for 'UIImage' declares the selector 'imageWithTintColor:renderingMode:'
    return [self.qmui_rawImage imageWithTintColor:color renderingMode:renderingMode];
            ~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15 errors generated.

**其他信息**
 - 设备: 
 - iOS 版本: 
 - Xcode 版本: [Xcode 10]
 - QMUI 版本: [4.0.2]

**Comment by FantasticSkyBaby** [comment]
回滚使用4.0.0版本正常

**Comment by MoLice** [comment]
需要用 Xcode 11 编译，如果用 Xcode 10 及以下，请手动在 QMUI 源码里给这些报错的代码加上：

```Objective-C

#ifdef IOS13_SDK_ALLOWED

// 这里是你报错的那堆方法
xxxx

#endif
```

**Comment by FantasticSkyBaby** [comment]
这个打包机上xcode版本固定，pod都是会更新的 不好手动操作，你们那边能否加上这个宏判断

**Comment by MoLice** [comment]
下个版本会补上这些宏判断，但近一周内暂时不会发布，你可以本地修改，到时候直接让 pod 覆盖你的本地代码即可。

**Comment by MoLice** [comment]
4.0.3 已加上保护

**Comment by FantasticSkyBaby** [comment]
@MoLice 貌似新版4.0.3 UIWindow+QMUI 在xcode10打包里面有一样的问题

![image](https://user-images.githubusercontent.com/14800057/68201783-66eb0d80-fffd-11e9-8c15-6356689e998a.png)

**Comment by MoLice** [comment]
确实，建议升级到 Xcode11 ，开发团队目前已找不到一台装有 Xcode 10 的机器了

**Comment by FantasticSkyBaby** [comment]
我找了个10编译了一下QMUI_demo 四个地方报错

![1501573025250_ pic](https://user-images.githubusercontent.com/14800057/68277432-25fd0280-00aa-11ea-972b-0707d12d7674.jpg)
<img width="1221" alt="WeChat8b71aba5d6509be423fac3d508939707" src="https://user-images.githubusercontent.com/14800057/68277553-62c8f980-00aa-11ea-8665-29ff4bdf0ffc.png">

<img width="1111" alt="WeChate44c486b2f62bf8e49d8176f20deefd4" src="https://user-images.githubusercontent.com/14800057/68277525-5775ce00-00aa-11ea-8f8a-06c4defa56dd.png">

<img width="1191" alt="WeChat7681a555acb5ab1c72e52dbbdf48d44e" src="https://user-images.githubusercontent.com/14800057/68277571-6f4d5200-00aa-11ea-9a13-0a700cf88556.png">

**Comment by FantasticSkyBaby** [comment]
也就是iOS13 特有的 windowScene 属性还需要判断下

**Comment by MoLice** [comment]
> 需要用 Xcode 11 编译，如果用 Xcode 10 及以下，请手动在 QMUI 源码里给这些报错的代码加上：
> 
> ```objc
> #ifdef IOS13_SDK_ALLOWED
> 
> // 这里是你报错的那堆方法
> xxxx
> 
> #endif
> ```

@FantasticSkyBaby

**Comment by FantasticSkyBaby** [comment]
好的，我这边用4.0版本
