### ISSUE TITLE
iOS 13 下 QMUIDialogViewController 设置标题颜色失效的问题

### ISSUE THREAD

**Issue by codingiran** [Tencent/QMUI_iOS#768]
**Bug 表现**

在 iOS 13 下，设置 `QMUIDialogViewController` 的标题颜色 `titleLabelTextColor` 后，一旦 `hide` 后再进行 `show` ，设置的标题颜色将失效

**截图**

将标题颜色设置为 **白色**，**初次**弹出表现正常，消失后**再次弹出**时被覆盖，表现如图：
![Bug 截图](https://user-images.githubusercontent.com/11780294/66797127-6a2e3480-ef3c-11e9-92a0-67a619ba9867.png)

**如何重现**

1. Demo 直接复现
2. Demo 如下:
[QMUIDialogTextFieldViewControllerDemo.zip](https://github.com/Tencent/QMUI_iOS/files/3727232/QMUIDialogTextFieldViewControllerDemo.zip)

**可能原因**

简单对比 iOS 13 以及 iOS 12 下各自的表现，可以发现，iOS 12 下再次 `show `的时候不会触发 `QMUINavigationTitleView` 的 `tintColorDidChange` 方法；而 iOS 13 下，每次 `show` 都会进入 `tintColorDidChange` 并将 `titleLabel` 和 `subtitleLabel` 的 `textColor` 覆盖成 `QMUINavigationTitleView.tintColor`: 

[相关代码位置](https://github.com/Tencent/QMUI_iOS/blob/fffddc9bcab20375af1dfa2dd8c040985f7f6603/QMUIKit/QMUIComponents/QMUINavigationTitleView.m#L648)

```objc
- (void)tintColorDidChange {
    [super tintColorDidChange];
    
    UIColor *color = self.tintColor;
    self.titleLabel.textColor = color;
    self.subtitleLabel.textColor = color;
    self.loadingView.color = color;
}
```

**其他信息**
 - 设备: 模拟器、iPhone、iPad
 - iOS 版本: iOS 13.0+
 - Xcode 版本: Xcode 11.1
 - QMUI 版本: 4.0.2

**Comment by MoLice** [comment]
已发布 [4.0.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.3) 修复该问题。
