### ISSUE TITLE
4.0.2 build 不通过

### ISSUE THREAD

**Issue by crazyyuan** [Tencent/QMUI_iOS#769]
4.0.0可以编译通过，4.0.2编译通不过。

![image](https://user-images.githubusercontent.com/1342404/66806721-d0c24b00-ef5a-11e9-8d37-b4886cdf2e73.png)

 - 设备: 模拟器iPhone Xr
 - [iOS 12.x
 - Xcode 10.3
 - QMUI 版本: 4.0.2

**Comment by MoLice** [comment]
#764
