### ISSUE TITLE
UISearchBar 以 tableHeaderView 的方式在iOS11以上版本出现的问题

### ISSUE THREAD

**Issue by WOHANGO** [Tencent/QMUI_iOS#770]
**Bug 表现**
暂时不知道原因，关于在QMUIDemo_ios中“QDSearchViewController.h”的“，经测试，在self.mySearchController.searchBar.qmui_usedAsTableHeaderView = YES;”，iPhoneX(ios11.0.1)下，不执行这段代码还是可以正常使用。
但在我所在的项目中，执行“self.mySearchController.searchBar.qmui_usedAsTableHeaderView = YES;”，会导致搜索输入框上移，返回时闪动；不执行反而正常。项目中的viewController是继承QMUICommonTableViewController 。
所以是否考虑去除“qmui_usedAsTableHeaderView”方法。

**截图**
[https://wuzihang99.oss-cn-shenzhen.aliyuncs.com/bug.png](url)

**其他信息**
 - 设备: [模拟器、iPhone]
 - iOS 版本: [iOS 11.0以上]
 - Xcode 版本: [Xcode 11.1]
 - QMUI 版本: [4.0.1]

**Comment by WOHANGO** [comment]
https://wuzihang99.oss-cn-shenzhen.aliyuncs.com/bug.png

**Comment by MoLice** [comment]
以下在 QDSearchViewController 里 将 `qmui_usedAsTableHeaderView = YES` 这句话注释掉后在 iOS 11 下的录屏，可以明显看到升起、降下时，searchBar 都有抖动（虽然注释或不注释掉，你关心的那个 searchBar 跑上去的问题确实没区别），这就是 `qmui_usedAsTableHeaderView` 这个属性在 iOS 11 下的作用。
[searchBar.mov.zip](https://github.com/Tencent/QMUI_iOS/files/3728504/searchBar.mov.zip)

至于你的项目里为什么会出现这个问题，建议你用排除变量法，对比与 QDSearchViewController 的区别，从而定位出到底是什么引发的问题。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
