### ISSUE TITLE
QMUIModalPresentationViewController 如何与键盘交互

### ISSUE THREAD

**Issue by peterios2016** [Tencent/QMUI_iOS#772]
**Bug 表现**
使用QMUIModalPresentationViewController时，如果自定义的contentView里有输入框，即使没有被键盘遮挡，也会错误判断输入框的位置从而把整个view“顶”上去，昨天以为是IQKeyboardManager的问题，结果去掉了之后还是会出现，请看demo
[Test.zip](https://github.com/Tencent/QMUI_iOS/files/3732212/Test.zip)

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
不明白你说的错误的现象是什么？以下是 Demo 运行后的截图，一切看起来都很正常？

![image](https://user-images.githubusercontent.com/1190261/66901983-6bda2400-f032-11e9-8e2d-78a59fa7b65d.png)

![image](https://user-images.githubusercontent.com/1190261/66901994-709ed800-f032-11e9-91df-95c736fa26c0.png)

**Comment by peterios2016** [comment]
白色的view位置出现偏移了啊，输入框的位置很明显是不会被键盘遮挡的，可还是出现偏移，是为什么呢

**Comment by MoLice** [comment]
这是一个通用的浮层控件，不是一个**专门为了放输入框**的浮层控件，所以控件**默认**（也可以自定义）会保证浮层不被键盘遮挡，而你的这个场景明显是会被键盘挡住的，这就是为什么浮层会在键盘升起时向上移动。
![image](https://user-images.githubusercontent.com/1190261/66902521-616c5a00-f033-11e9-8144-4e16972ddc5e.png)

至于“只要浮层里的输入框没有被键盘挡住，浮层就不用移动”，这是你的业务需求，不是浮层组件应该自动帮你考虑的事情，因为触发键盘升起的原因也不仅仅只是浮层里的输入框，还可能是浮层外的，甚至是 iPad 分屏下其他 App 触发的键盘升起。

你的这个业务需求，QMUIModalPresentationViewController 目前是完全能满足的，头文件的注释、QMUI Demo 里的示例代码，都有完全契合你需求的说明和展示，不清楚你使用这个组件前是否有自行阅读过？

![image](https://user-images.githubusercontent.com/1190261/66902900-10a93100-f034-11e9-87fd-6ca2b0e19cd1.png)

<img src="https://user-images.githubusercontent.com/1190261/66902953-29b1e200-f034-11e9-8ab8-c943ff73aae6.png" width="500" />

**Comment by peterios2016** [comment]
看完你们的demo和你提到的那三个方法后，我仍然不知道要如何调整。
你的demo和注释都提到建议有输入框的时候立刻调用becomeFirstResponder，可业务上就是不需要立刻弹出来，因为业务上还有其他的手动选择的选项，直接弹键盘感觉比较突兀。如果不调用becomeFirstResponder，我看不出要如何使用layoutblock，如果你愿意的话，可以直接在demo里进行修改然后再发出来，这样也方便其他有类似需求的开发者。
另外我觉得可以新增一个属性，可以从头到尾都切断与键盘的关联，默认可以是关闭的。

**Comment by MoLice** [comment]
基于目前的注释详细程度和 Demo 示例代码，我们认为没有必要进一步去解释 QMUIModalPresentationViewController 以及它所提供的那 3 个方法应该如何使用，请自行理解。

至于你提的 `becomeFirstResponder` 的问题，你的业务场景与是否 `becomeFirstResponder` 没有关系，我们可以不用谈论这一点。

> 另外我觉得可以新增一个属性，可以从头到尾都切断与键盘的关联，默认可以是关闭的。

关于这个建议暂不采纳，目前用那3个方法已完全足够满足这个需求，也不麻烦，layoutBlock 里为 contentView 计算布局时不要考虑 keyboardHeight 参数即可。
