### ISSUE TITLE
QMUIKit 又出现大量警告 

### ISSUE THREAD

**Issue by 592424188** [Tencent/QMUI_iOS#773]
**Bug 表现**
就是报很多重复定义的警告。
都是Duplicate definition of category 'QMUI' on interface 'NSObject'这种

![WX20191016-115910](https://user-images.githubusercontent.com/22266959/66887281-032c8080-f00d-11e9-9f65-5db7444a9639.png)

这个是我pod 的设置
![WX20191016-115957](https://user-images.githubusercontent.com/22266959/66887293-10496f80-f00d-11e9-9e92-ac3c855ab9a7.png)

 - 设备:  7
 - Xcode 版本: [Xcode 10.1]
 - QMUI 版本: [4.0.0]

**Comment by MoLice** [comment]
无法重现，请提供 Demo 以供排查。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
