### ISSUE TITLE
QMUINavigationController 缺少对 initWithNavigationBarClass:toolbarClass: 的支持

### ISSUE THREAD

**Issue by boyxu** [Tencent/QMUI_iOS#774]
**Bug 表现**
当需要自定义 toolbar 或者 navigationBar时，需要调用 `- (instancetype)initWithNavigationBarClass:(nullable Class)navigationBarClass toolbarClass:(nullable Class)toolbarClass`，发现当基于 `QMUINavigationController` 时，自定义的toolbar不会被系统调用初始化，而当改为 `UINavigationController` 时一切正常。
我尝试自定义一个直接继承自 `UINavigationController` 的子类时，调用改方法是有效的，现在不确定 `QMUINavigationController` 哪里的代码引起了该问题。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器]
 - iOS 版本: [iOS 12.x]
 - Xcode 版本: [Xcode 10.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
请展示你说的“自定义的toolbar不会被系统调用初始化”的相关代码

**Comment by boyxu** [comment]
我重新写了个demo，专门验证这个问题，结果都是正常的。但在实际的项目里却不行。实际的项目里还引入了其他的一些框架，不知道是不是冲突造成的，调试也没发现什么。另外在xcode11 下，貌似是正常的，很是奇怪。我再跟踪跟踪这个问题看看。

**Comment by MoLice** [comment]
好的，当你确认问题所在后，需要的时候请 reopen 这个 issue，目前暂时关闭。
