### ISSUE TITLE
xcode10.3 pod更新之后，报了UIImageConfiguration错误，导致项目无法运行

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#775]
**Bug 表现**
问题的具体描述
xcode10.3 pod更新之后，在UIImage+QMUITheme.m文件中报了UIImageConfiguration错误，导致项目无法运行

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/16254669/66913191-bd8ca980-f046-11e9-9699-0436fe309a02.png)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.4]
 - Xcode 版本: [Xcode 10.3]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
重复 #764
