### ISSUE TITLE
ios13框架引起xib加载崩溃?

### ISSUE THREAD

**Issue by SilenceLove** [Tencent/QMUI_iOS#778]
**Bug 表现**
初始化xib时崩溃，代码、日志截图如下
只有在ios13上才出现

**截图**
![image](https://user-images.githubusercontent.com/18083149/67083082-16864a00-f1cd-11e9-999c-84fc909c2028.png)
![image](https://user-images.githubusercontent.com/18083149/67083307-8399df80-f1cd-11e9-8714-249581da9d24.png)

**如何重现** 

**预期的表现**
希望正常

**其他信息**
 - 设备: [模拟器]
 - iOS 版本: [iOS 13.0]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
目前提供的信息尚不足以判断问题的原因是什么，建议提供一个可复现的 Demo 以供调试。

**Comment by SilenceLove** [comment]
[test.zip](https://github.com/Tencent/QMUI_iOS/files/3743441/test.zip)
![image](https://user-images.githubusercontent.com/18083149/67087572-c364c500-f1d5-11e9-9afe-efed53398f2d.png)
点击按钮ji就崩溃

**Comment by SilenceLove** [comment]
新建的项目，麻烦看一下。项目已上传

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/67257938-e5559480-f4c0-11e9-9c00-704cd700a278.png)

你的 viewController 都没有被正确 init 就调用实例方法 showXxx，出问题是必然的，跟你有没有用 QMUI 没有关系，下次遇到这种问题，麻烦自行确定是 QMUI 的问题后再提 issue。
