### ISSUE TITLE
您好，我想通过框架的api获取里面的图片资源，比如右箭头TableViewCellDisclosureIndicatorImage，发现无法获取到图片

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#780]
**现存问题或期望目标**
您好，我想通过框架的api获取里面的图片资源，比如右箭头TableViewCellDisclosureIndicatorImage，发现无法获取到图片，是不是框架里面没有这些图片资源

**Comment by MoLice** [comment]
`TableViewCellDisclosureIndicatorImage` 是配置表提供的宏，需要依赖配置表正确运行时才可以使用，至于配置表的使用方法，请查看官网 [开始使用](https://qmuiteam.com/ios/get-started/)。

至于配置表正确运行后，通过 `TableViewCellDisclosureIndicatorImage` 获取到的图片取决于你自己在配置表里为 `TableViewCellDisclosureIndicatorImage` 设置的值，QMUI 默认并不会给这个配置项赋值，默认值为 `nil`。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
