### ISSUE TITLE
自定义导航栏转场后，手势 pop 无法被 shouldPopViewControllerByBackButtonOrPopGesture 拦截

### ISSUE THREAD

**Issue by codingiran** [Tencent/QMUI_iOS#781]
**Bug 表现**

有两个控制器 A 与 B，在 A 中自定义导航栏转场：
```objc
- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = @"控制器A";
    self.navigationController.delegate = self;
}
...

- (id<UIViewControllerAnimatedTransitioning>)navigationController:(UINavigationController *)navigationController animationControllerForOperation:(UINavigationControllerOperation)operation fromViewController:(UIViewController *)fromVC toViewController:(UIViewController *)toVC
{
    // 自定义转场
    return nil;
}

```
此时 push 到 控制器 B，从 B 无法通过手势 pop 回 A，这是系统行为

通过在控制器 B 内设置手势代理来解决无法手势返回的问题:
```objc
- (void)viewDidLoad
{
    [super viewDidLoad];
     self.title = @"控制器B";
     self.navigationController.interactivePopGestureRecognizer.delegate = self;
}
```

此时发现 QMUI 拦截 pop 的方法`- (BOOL)shouldPopViewControllerByBackButtonOrPopGesture:(BOOL)byPopGesture` 在**点击返回按钮时表现正常，但手势 pop 无法拦截**

**如何重现**

1. Demo 直接复现
2. [点击下载Demo](https://github.com/Tencent/QMUI_iOS/files/3753689/PopDemo.zip)

**预期的表现**

希望自定义转场和 pop 拦截同时正常

**其他信息**

 - 设备: [模拟器、iPhone]
 - iOS 版本: [iOS 13.1.3]
 - Xcode 版本: [Xcode 11.1]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
当你自定义转场后手势返回失效时，建议通过 `forceEnableInteractivePopGestureRecognizer` 来解决，因为 QMUI 里会修改 `navigationController.interactivePopGestureRecognizer.delegate`，而你将其指向自己的 viewController 会导致 QMUI 的某些功能失效。

**Comment by codingiran** [comment]
> 当你自定义转场后手势返回失效时，建议通过 `forceEnableInteractivePopGestureRecognizer` 来解决，因为 QMUI 里会修改 `navigationController.interactivePopGestureRecognizer.delegate`，而你将其指向自己的 viewController 会导致 QMUI 的某些功能失效。

感谢！还有一个问题：
B 可以通过 `forceEnableInteractivePopGestureRecognizer ` 来解决手势返回，那后续 B 还会 push 到 C，C push D，D push 到 E.... 是必须 在 C、D、E.. 内全部都写上 `forceEnableInteractivePopGestureRecognizer` 吗？

**Comment by codingiran** [comment]
@MoLice 
一旦 A 控制器由于自定义转场导致手势返回失效后，貌似所有 A 所在导航栏堆栈内的全部控制器都必须使用 `forceEnableInteractivePopGestureRecognizer ` 来获得手势返回，所有 Controller 加一遍重复代码先不说，有些通过 router push 的或者直接通过 `push UIViewController.new` 出来的控制器就没办法添加`forceEnableInteractivePopGestureRecognizer `。请教一下有没有更加好的方法或者有什么 trick ？

**Comment by codingiran** [comment]
在 A 转场的代理方法内尝试解决了:
```objc
/// 转场动画
- (id<UIViewControllerAnimatedTransitioning>)navigationController:(UINavigationController *)navigationController animationControllerForOperation:(UINavigationControllerOperation)operation fromViewController:(UIViewController *)fromVC toViewController:(UIViewController *)toVC
{
    // @see UIViewController + WEForceEnableInteractivePopGestureRecognizer
    toVC.alwaysForceEnableInteractivePopGestureRecognizerInNavigationStack = YES;

    ....
}
```

添加了一个分类：

```objc
@interface UIViewController (WEForceEnableInteractivePopGestureRecognizer)

@property(nonatomic, assign) BOOL alwaysForceEnableInteractivePopGestureRecognizerInNavigationStack;

@end

@implementation UIViewController (WEForceEnableInteractivePopGestureRecognizer)

QMUISynthesizeBOOLProperty(alwaysForceEnableInteractivePopGestureRecognizerInNavigationStack, setAlwaysForceEnableInteractivePopGestureRecognizerInNavigationStack)

- (BOOL)forceEnableInteractivePopGestureRecognizer
{
    return self.alwaysForceEnableInteractivePopGestureRecognizerInNavigationStack;
}

@end
```

**Comment by MoLice** [comment]
> 一旦 A 控制器由于自定义转场导致手势返回失效后，貌似所有 A 所在导航栏堆栈内的全部控制器都必须使用 forceEnableInteractivePopGestureRecognizer 来获得手势返回

确实有这个问题，目前 QMUI 没有提供正式的方案去解决，你的 Category 实现思路个人认为是相对优雅的。
