### ISSUE TITLE
pod导入QMUIKit后，自定义navigationcontroller中，设置interactivePopGestureRecognizer无效

### ISSUE THREAD

**Issue by ZTXBEST** [Tencent/QMUI_iOS#783]
**Bug 表现**
pod导入QMUIKit后，自定义UINavigationController中，设置interactivePopGestureRecognizer.delegate，gestureRecognizerShouldBegin方法不会调用。

**其他信息**

 - iOS 版本: iOS13
 - Xcode 版本:Xcode11

**Comment by zhegexiazhi** [comment]
同问

**Comment by ZTXBEST** [comment]
> 同问

我目前的解决方法是在baseVC里加了forceEnableInteractivePopGestureRecognizer方法，现在是解决了这个问题

**Comment by MoLice** [comment]
在 UINavigationController (QMUI) Category 里，我们在 UINavigationController 的 viewDidLoad 时修改了 `interactivePopGestureRecognizer.delegate` 的值，猜测你自己指定 delegate 的时机可能比 viewDidLoad 晚，所以导致这个问题。
![image](https://user-images.githubusercontent.com/1190261/67742312-b0b08280-fa56-11e9-989b-e2e5dc332acf.png)

建议：
在自己的 UINavigationController 里，viewDidLoad 或更晚的时机中去修改 `interactivePopGestureRecognizer.delegate` 的值。

其他：
`QMUINavigationControllerDelegate` 里的很多功能都依赖于对 `interactivePopGestureRecognizer.delegate` 的值的修改，所以如果你自己改了 delegate，可能会导致别的功能失效，请知悉。

如果只是因为系统的手势返回失效了，可以参考 @ZTXBEST 的说法，而不一定需要去改到 `interactivePopGestureRecognizer.delegate`。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
