### ISSUE TITLE
为什么在工程切换前后台时候，皮肤会自动切换

### ISSUE THREAD

**Issue by XX-chu** [Tencent/QMUI_iOS#784]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。

**Comment by MoLice** [comment]
如果你使用 QMUITheme，在 iOS 13 下设置了 `identifierForTrait` 并将 `respondsSystemStyleAutomatically` 置为 YES 的情况下，当你的 App 选中的 theme 为 Light 而手机的 Dark Mode 又是开启的状态，那么在前后台切换时，由于 `respondsSystemStyleAutomatically` 的作用，你的 App theme 会被自动设置为 Dark Mode 对应的 theme，这是符合预期的。

除此之外没有别的情况下会自动切换主题，如果有，就是 bug。如果明确是 bug，请详细说明你的代码和场景，目前提供的信息是不足以定位问题的。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
