### ISSUE TITLE
UIImage+QMUITheme运行报错

### ISSUE THREAD

**Issue by Daisy-Dream** [Tencent/QMUI_iOS#785]
**Bug 表现**
最新的包拉取下来UIImage+QMUITheme类报错

**截图**
<img width="264" alt="屏幕快照 2019-10-23 下午5 19 06" src="https://user-images.githubusercontent.com/13704577/67378096-4bbdde00-f5b9-11e9-837a-1f9334ae8682.png">
<img width="810" alt="屏幕快照 2019-10-23 下午5 19 13" src="https://user-images.githubusercontent.com/13704577/67378107-50829200-f5b9-11e9-80ae-02d83a3110c3.png">

**Comment by MoLice** [comment]
#764
