### ISSUE TITLE
使用xib的控制器作为TabBarController的子控制器时，push到下一个控制器，TabBar没有隐藏，其他用纯代码写的已隐藏，配置文件配置了属性hidesBottomBarWhenPushedInitially为YES

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#786]
**Bug 表现**
问题的具体描述
使用xib的控制器作为TabBarController的子控制器时，push到下一个控制器，TabBar没有隐藏，其他用纯代码写的已隐藏，配置文件配置了属性hidesBottomBarWhenPushedInitially为YES

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. 假设配置类已正常添加，配置属性hidesBottomBarWhenPushedInitially为YES
2.  新建一个带XIB，继承自QMUICommonViewController的控制器类，例如TestController
3. 创建TestController对象，并设置TestController的hidesBottomBarWhenPushed为NO，并添加到QMUITabBarViewController控制器上
4. 在TestController创建一个按钮，绑定事件push到下一个控制器

**预期的表现**
正常情况下，应该是什么表现
push到下一个控制器时，TabBar隐藏起来

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by LYluyu** [comment]
@MoLice 您好，被push的那个vc，确实不是`QMUICommonViewController` 的 subclass。

**Comment by MoLice** [comment]
那没有办法，你可以搜一下“HidesBottomBarWhenPushedInitially”，它只有在 QMUICommonViewController 里才有被用到。
