### ISSUE TITLE
是否可以为QMUIMoreOperationController的顶部添加一个标题view或者label

### ISSUE THREAD

**Issue by pcccccc** [Tencent/QMUI_iOS#787]
使用版本:4.0.2
需求：是否可以为QMUIMoreOperationController的顶部添加一个标题view或者label
![93B5E353-D5FA-41B2-B945-3FE2D9FB4009](https://user-images.githubusercontent.com/13974510/67464134-681f5080-f675-11e9-8fcd-8416a998d679.png)

**Comment by pcccccc** [comment]
感谢，之前加载了self.view上但是没有效果

**Comment by helloWotu** [comment]
> 目前不可以，后续会加上，在此之前你可以：
> 
> 1. 继承 QMUIMoreOperationController，写一个子类
> 2. 子类里将 self.contentPaddings.top 加高到足以容纳你的 headerView（也即“分享到”）
> 3. 创建 headerView，add 到 self.contentView 上，自己写布局将其放到 contentView 的顶部

请问继承QMUIMoreOperationController需要重写什么方法么，为什么我一继承就调用的时候就崩溃了

**Comment by MoLice** [comment]
@helloWotu 贴出 crash 时的堆栈、控制台 log
