### ISSUE TITLE
emptyView 加载gif 显示出错

### ISSUE THREAD

**Issue by MrHanbing** [Tencent/QMUI_iOS#789]
[self showEmptyViewWithImage:[UIImage qmui_animatedImageNamed:@"loading.gif" scale:0] text:@"加载中..." detailText:nil buttonTitle:nil buttonAction:nil];
![875a25fe-b9a0-4c37-a185-d24e2968adf0](https://user-images.githubusercontent.com/14346668/67562377-2fed4000-f751-11e9-9c3e-ebda401834a3.jpg)

 - iOS 版本: [iOS 13]
 - Xcode 版本: [Xcode 11]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
你提供的截图没看出来有什么问题，在 QD 里测试也没问题，请补充更多信息再 reopen issue。

![image](https://user-images.githubusercontent.com/1190261/67747450-af398700-fa63-11e9-9c0c-99cadf1d31b0.png)

![image](https://user-images.githubusercontent.com/1190261/67747408-97620300-fa63-11e9-8c5d-9ad2af5c198b.png)
