### ISSUE TITLE
修改QDMultipleDelegatesViewController.m中self.textField.delegate = self.textField;无响应

### ISSUE THREAD

**Issue by hbxfnsm** [Tencent/QMUI_iOS#790]
@interface TestTextField : UITextField<UITextFieldDelegate>
@end

@implementation TestTextField
- (void)textFieldDidBeginEditing:(UITextField *)textField {
    NSLog(@"textFieldDidBeginEditing");
}
@end

// 修改为自定义textField
@property(nonatomic, strong) TestTextField *textField;

// 只保留代理为自己
    self.textField.delegate = self.textField;
//    self.textField.delegate = self.delegator1;
//    self.textField.delegate = self.delegator2;

触发代理时候无响应

问题分析:
QMUIMultipleDelegates.m
- (BOOL)respondsToSelector:(SEL)aSelector;
当开启多代理且代理只有自身时返回为NO

**Comment by hbxfnsm** [comment]
@interface TestTextField : UITextField<UITextFieldDelegate>
@end

@implementation TestTextField
- (void)textFieldDidBeginEditing:(UITextField *)textField {
    NSLog(@"textFieldDidBeginEditing");
}
@end

补充下TestTextField是实现了UITextFieldDelegate，漏写了

**Comment by MoLice** [comment]
`QMUIMultipleDelegates` 不支持 `self.delegate = self` 的写法，会引发死循环，有这种需求的场景建议在 `self` 内部创建一个对象专门用于 delegate 的响应，参考 `_QMUITextViewDelegator`，下个版本也会增加相应注释用于明确这种情况。
