### ISSUE TITLE
-[QMUIThemeColor _highContrastDynamicColor]: unrecognized selector sent to instance....

### ISSUE THREAD

**Issue by jhchenchong** [Tencent/QMUI_iOS#791]
**Bug 表现**
线上App启动崩溃。Bugly统计到的崩溃日志。本地环境暂时没有复现。
**其他信息**
 - 设备:iPhone Xs Max
 - iOS 版本:13.1.3 
 - QMUI 版本:4.0.2

**Comment by MoLice** [comment]
这个 crash 需要手机开启“辅助功能-显示与文字大小-增强对比度”后才出现。

<img src="https://user-images.githubusercontent.com/1190261/67746577-a9db3d00-fa61-11e9-9e4c-3bcc81022852.png" width="450" />

根本原因在于这种场景里，系统会去尝试调用 dynamic color 的 `-(UIColor *) _highContrastDynamicColor` 方法，但 `QMUIThemeColor` 并没有实现这个，所以出现了“unrecognized selector sent to instance”的 crash，新版本将会修复这个问题，在此之前你可以修改本地的 QMUIKit，增加以下代码：

```Objective-C
@implementation QMUIThemeColor

- (UIColor *)_highContrastDynamicColor {
    return self;
}

@end
```

**Comment by MoLice** [comment]
已发布 [4.0.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.3) 修复该问题。
