### ISSUE TITLE
ios13暗黑模式QMUIDialogSelectionViewController的items无法显示

### ISSUE THREAD

**Issue by yongshideweiyi** [Tencent/QMUI_iOS#792]
**其他信息**
 - 设备: [iPhone7]
 - iOS 版本: [iOS 13.1.3]
 - Xcode 版本: [Xcode 11.1]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
什么叫无法显示？

**Comment by yongshideweiyi** [comment]
> 什么叫无法显示？
代码如下：
`    QMUIDialogSelectionViewController *dialogViewController = [[QMUIDialogSelectionViewController alloc] init];
    dialogViewController.title = @"拍照分享";
    dialogViewController.items = strList;
    //    - (void)addCancelButtonWithText:(NSString *)buttonText block:(void (^)(__kindof QMUIDialogViewController *aDialogViewController))block
    [dialogViewController addCancelButtonWithText:@"取消" block:^(__kindof QMUIDialogViewController *aDialogViewController) {

    }];
    dialogViewController.cellForItemBlock = ^(QMUIDialogSelectionViewController *aDialogViewController, QMUITableViewCell *cell, NSUInteger itemIndex) {
        cell.accessoryType = UITableViewCellAccessoryNone;// 移除点击时默认加上右边的checkbox
    };
    dialogViewController.heightForItemBlock = ^CGFloat (QMUIDialogSelectionViewController *aDialogViewController, NSUInteger itemIndex) {
        return 54;// 修改默认的行高，默认为 TableViewCellNormalHeight
    };
    dialogViewController.didSelectItemBlock = ^(QMUIDialogSelectionViewController *aDialogViewController, NSUInteger itemIndex) {

        [weakSelf.progressWebView stringByEvaluatingJavaScriptFromString:[[listInfo objectAtIndex:itemIndex] objectForKey:@"clickFunc"]];

        [aDialogViewController hide];
    };
    [dialogViewController show];`
items文字正常情况是黑色，
![图片](https://user-images.githubusercontent.com/22723439/67734181-50601780-fa3b-11e9-8367-ee026a832069.png)

将手机调到暗黑模式之后，然后在App中用代码禁用暗黑模式
#if defined(__IPHONE_13_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_13_0
    if(@available(iOS 13.0,*)){
        self.window.overrideUserInterfaceStyle = UIUserInterfaceStyleLight;
    }
    #endif
弹框items文字颜色变成了白色，但是暗黑模式的弹框背景依然是白色，导致文字显示不出来！
![图片](https://user-images.githubusercontent.com/22723439/67734271-8bfae180-fa3b-11e9-8037-609b70fdfbf4.png)

**Comment by MoLice** [comment]
`QMUIDialogViewController` 是借助 `QMUIModalPresentationViewController` 来显示的，而 `QMUIModalPresentationViewController` 内部是通过 `UIWindow` 的方式显示的（内部有个 class 叫 `QMUIModalPresentationWindow`），所以请确认你是否有同时设置 `UIApplication.sharedApplication.delegate.window` 和 `QMUIModalPresentationWindow` 的 `overrideUserInterfaceStyle`？

如果要设置 `QMUIModalPresentationWindow` 的 `overrideUserInterfaceStyle`，可将以下代码添加到你的项目里：

```Objective-C
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        ExtendImplementationOfNonVoidMethodWithSingleArgument([QMUIModalPresentationWindow class], @selector(initWithFrame:), CGRect, QMUIModalPresentationWindow *, ^QMUIModalPresentationWindow *(QMUIModalPresentationWindow *selfObject, CGRect firstArgv, QMUIModalPresentationWindow *originReturnValue) {
            #if defined(__IPHONE_13_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_13_0
            if (@available(iOS 13.0,*)) {
                selfObject.overrideUserInterfaceStyle = UIUserInterfaceStyleLight;
            }
            #endif
            return originReturnValue;
        });
    });
}
```

**Comment by yongshideweiyi** [comment]
> `QMUIDialogViewController` 是借助 `QMUIModalPresentationViewController` 来显示的，而 `QMUIModalPresentationViewController` 内部是通过 `UIWindow` 的方式显示的（内部有个 class 叫 `QMUIModalPresentationWindow`），所以请确认你是否有同时设置 `UIApplication.sharedApplication.delegate.window` 和 `QMUIModalPresentationWindow` 的 `overrideUserInterfaceStyle`？
> 
> 如果要设置 `QMUIModalPresentationWindow` 的 `overrideUserInterfaceStyle`，可将以下代码添加到你的项目里：
> 
> ```objc
> + (void)load {
>     static dispatch_once_t onceToken;
>     dispatch_once(&onceToken, ^{
>         ExtendImplementationOfNonVoidMethodWithSingleArgument([QMUIModalPresentationWindow class], @selector(initWithFrame:), CGRect, QMUIModalPresentationWindow *, ^QMUIModalPresentationWindow *(QMUIModalPresentationWindow *selfObject, CGRect firstArgv, QMUIModalPresentationWindow *originReturnValue) {
>             #if defined(__IPHONE_13_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_13_0
>             if (@available(iOS 13.0,*)) {
>                 selfObject.overrideUserInterfaceStyle = UIUserInterfaceStyleLight;
>             }
>             #endif
>             return originReturnValue;
>         });
>     });
> }
> ```

添加如上代码之后，问题已修复，谢谢！！
