### ISSUE TITLE
QMUIKit 更新到4.0.2 与CYLTabBarController最新版本冲突

### ISSUE THREAD

**Issue by jianjianhao** [Tencent/QMUI_iOS#793]
目前发现tabbar选中状态下的文字属性不生效

**Comment by pcccccc** [comment]
是因为iOS13的问题吧，不是因为QMUI的问题i

**Comment by jianjianhao** [comment]
那要怎么解决

**Comment by fanyuecheng** [comment]
难道是这个？
https://github.com/Tencent/QMUI_iOS/issues/740
不过这个4.0.2已经修复了啊

**Comment by MoLice** [comment]
@jianjianhao 更新前的 QMUI 版本是多少？

**Comment by jianjianhao** [comment]
4.0.2

**Comment by jianjianhao** [comment]
问题找到了，

**Comment by jianjianhao** [comment]
NSMutableDictionary *normalAttrs = [NSMutableDictionary dictionary];
    normalAttrs[NSForegroundColorAttributeName] = [UIColor greenColor];
    
    NSMutableDictionary *selectedAttrs = [NSMutableDictionary dictionary];
    selectedAttrs[NSForegroundColorAttributeName] = [UIColor redColor];
    
    UITabBarItem *tabBar = [UITabBarItem appearance];
    [tabBar setTitleTextAttributes:normalAttrs forState:UIControlStateNormal];
    [tabBar setTitleTextAttributes:selectedAttrs forState:UIControlStateSelected];
使用系统的也会触发

**Comment by jianjianhao** [comment]
@pcccccc  具体是什么情况就不知道了

**Comment by MoLice** [comment]
QMUI 4.0.0 Release Note 里有相关说明，更新版本请注意阅读更新日志。

![image](https://user-images.githubusercontent.com/1190261/67742584-71cefc80-fa57-11e9-908b-c83a060d5874.png)
