### ISSUE TITLE
是否有直接显示状态栏的案例

### ISSUE THREAD

**Issue by XavierLost** [Tencent/QMUI_iOS#794]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。
在大屏刘海手机上,很多应用只显示状态栏(少数派,爱奇艺),类似safari滚动导航栏缩小功能.
![07AAF96A0D7A5C81EF8B9605F4306A40](https://user-images.githubusercontent.com/24632295/67756815-a5b91a80-fa75-11e9-8cdb-69d647d7abc6.JPG)
![C5ADCE76094A3C8B68A310178E642662](https://user-images.githubusercontent.com/24632295/67756846-b6699080-fa75-11e9-926f-55bbeb2ab398.JPG)

少数派
![A603D57CC2BB9E2C9129F592E6EC833B](https://user-images.githubusercontent.com/24632295/67756690-67bbf680-fa75-11e9-966f-736be8f2575a.JPG)

**Comment by MoLice** [comment]
Safari 的用系统方式即可实现，爱奇艺没用过，看截图也就是滚动时隐藏导航栏而已？直接用 UIScrollView 的 delegate 就行？或者你参考 Demo 的 QMUIScrollAnimator。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
