### ISSUE TITLE
Xcode11，iOS13，输入框切换崩溃，下图，在线等

### ISSUE THREAD

**Issue by shenlulu1016** [Tencent/QMUI_iOS#795]
![D0797F4344264BAAD2C0035FC4AA4AA2](https://user-images.githubusercontent.com/9317141/67928482-1a1ac780-fbf6-11e9-9401-5a892d76b0d1.png)
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
根据截图的信息，QMUI 只是 swizzle 了 becomeFirstResponder 这个方法，卡在这里不一定跟 QMUI 有关系，看控制台的信息里有：

![image](https://user-images.githubusercontent.com/1190261/67932323-a335fc80-fbfe-11e9-93e9-6b5214b4deca.png)

建议检查哪里对 UIColor 对象调用了 floatValue 方法。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
