### ISSUE TITLE
您好,您在QMUIConfiguration 里面忘记设置tabBarItemTitleSelectedFont,所以就导致如果使用您的配置表,在IOS 13下,无论外面怎么设置TabBarSelectedFont都不起作用

### ISSUE THREAD

**Issue by dawanzi** [Tencent/QMUI_iOS#796]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/67932038-1ee37980-fbfe-11e9-8f28-4795465ccf79.png)

试了貌似没问题？

```Objective-C
UITabBarAppearance *appearance = self.tabBarController.tabBar.standardAppearance;
[appearance qmui_applyItemAppearanceWithBlock:^(UITabBarItemAppearance * _Nonnull itemAppearance) {
    NSMutableDictionary<NSAttributedStringKey, id> *attributes = itemAppearance.selected.titleTextAttributes.mutableCopy;
    attributes[NSFontAttributeName] = UIFontBoldMake(11);
    itemAppearance.selected.titleTextAttributes = attributes.copy;
}];
```

**Comment by dawanzi** [comment]
您好,问题没有解决,在你们的demo里,按照您这样设置,发现还是有问题,我设置选中字体是14,当时开始进来时,默认选中的那个tababr的字体并没有变,除非手动选中了,才会字体大小变了!

![1](https://user-images.githubusercontent.com/13412888/68014828-874c5c80-fccb-11e9-81ee-596cc84c6c5f.jpeg)
![2](https://user-images.githubusercontent.com/13412888/68014877-a945df00-fccb-11e9-9eb8-dca08f050cb7.jpeg)

**Comment by MoLice** [comment]
上面的代码片段只是举例子用，为了证明这个问题从业务的角度去解决就可以了，具体的时机需要你根据业务场景自己选择，上面的示例时机当时随意用了 `viewDidAppear`，此时 tabBar 已经显示完毕了，所以修改了样式后没有刷新，你可以选一个更早的时机，例如以 QD 为例，以 appearance 的方式去修改，将代码放在 `-[QDCommonUI renderGlobalAppearance]` 里：

```Objective-C

@implementation QDCommonUI

+ (void)renderGlobalAppearances {
    if (@available(iOS 13.0, *)) {
        UITabBarAppearance *appearance = UITabBar.appearance.standardAppearance;
        [appearance qmui_applyItemAppearanceWithBlock:^(UITabBarItemAppearance * _Nonnull itemAppearance) {
            NSMutableDictionary<NSAttributedStringKey, id> *attributes = itemAppearance.selected.titleTextAttributes.mutableCopy;
            attributes[NSFontAttributeName] = UIFontBoldMake(11);
            itemAppearance.selected.titleTextAttributes = attributes.copy;
        }];
        UITabBar.appearance.standardAppearance = appearance;
    }
}

@end

```

![image](https://user-images.githubusercontent.com/1190261/68016273-2f175980-fccf-11e9-843c-d3c746fee378.png)

**Comment by dawanzi** [comment]
太感谢了,果然是我调用时机不对,现在解决了,谢谢您了!
