### ISSUE TITLE
导航栏手势侧滑一半，然后取消返回，并未pop当前控制器，但是接下来想push到一个新界面的时候，确无法成功

### ISSUE THREAD

**Issue by wcb133** [Tencent/QMUI_iOS#798]
**Bug 表现**
如题

**如何重现**
1. 侧滑返回到一半，然后取消，也就是不pop当前控制器，然后点击当前控制器的一个按钮进行push另一个控制器，就会发现无法push，错误提示：“上一次界面切换的动画尚未结束就试图进行新的 push 操作，为了避免产生 bug，拦截了这次 push。“

**预期的表现**
希望能push到新界面

**Comment by MoLice** [comment]
项目里引入了什么第三方框架？

**Comment by wcb133** [comment]
override func viewWillDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
    }
在当前控制器重写了这个方法并且调用了父类的该方法就会出现该问题

**Comment by MoLice** [comment]
...

这本来就是错误的操作，不出错才是有问题的吧

**Comment by wcb133** [comment]
。。。。。。，不好意思，写错了
