### ISSUE TITLE
更新Xcode11.2后Xib使用UITextView 出现bug

### ISSUE THREAD

**Issue by kuiZhang98** [Tencent/QMUI_iOS#799]
**Bug 表现**
只有xib使用TextView出现崩溃，IOS-13.2正常。使用代码创建也没问题
  
**如何重现**
1. 测试过系统IOS-13.1 和 IOS-12 都有该问题
2. 应该是除了IOS13.2都会崩溃
**截图**
<img width="1626" alt="WechatIMG1273" src="https://user-images.githubusercontent.com/34617635/68001245-4427c480-fc9e-11e9-8dd5-d7f7d64b2526.png">
<img width="1626" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/34617635/68001254-4be76900-fc9e-11e9-8b9c-c31d60f002d2.png">

**其他信息**
 - 设备: [iPhone、iPad]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11.2]
 - QMUI 版本: [4.0.2]

**Comment by XX-chu** [comment]
我这边也出现这个问题了，这个问题有解决吗？

**Comment by kuiZhang98** [comment]
> 我这边也出现这个问题了，这个问题有解决吗？
貌似发现这个问题与QMUI无关。是xcode的bug

**Comment by codingiran** [comment]
确认是 Xcode 11.2 的 bug，建议回滚到 11.1 坐等修复
[参考链接](https://stackoverflow.com/questions/58657087/after-upgrading-to-xcode-11-2-from-xcode-11-1-app-crashes-due-to-uitextlayoutv)
