### ISSUE TITLE
UIFont(QMUI) 在 iOS 13 下无法获取到正确的 Light 字体

### ISSUE THREAD

**Issue by MQL9011** [Tencent/QMUI_iOS#802]
**Bug 表现**
导致控制台输出一条警告.
![image](https://user-images.githubusercontent.com/11871158/68101160-2741fa00-ff07-11e9-8242-00f7254500d3.png)

把字体名修改下就行了.希望能在后续版本中更新.
```
+ (UIFont *)qmui_lightSystemFontOfSize:(CGFloat)fontSize {
    return [UIFont fontWithName:@"SFUIText-Light" size:fontSize];
}
```

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11.1]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
系统默认字体在 iOS 12 及以前是”.SFUIText“，iOS 13 开始变成”.SFUI“，加上 `UIFont (QMUI)` 之前的实现有 bug，导致 iOS 13 下无法获取正确的字体，该 bug 已修复，下个版本会带上，在此之前建议修改本地的”UIFont+QMUI.m“文件，将以下两个方法的实现替换掉：

```Objective-C
@implementation UIFont (QMUI)

+ (UIFont *)qmui_lightSystemFontOfSize:(CGFloat)fontSize {
    return [UIFont systemFontOfSize:fontSize weight:UIFontWeightLight];
}

+ (UIFont *)qmui_systemFontOfSize:(CGFloat)size weight:(QMUIFontWeight)weight italic:(BOOL)italic {
    UIFont *font = nil;
    font = [UIFont systemFontOfSize:size weight:weight == QMUIFontWeightLight ? UIFontWeightLight : (weight == QMUIFontWeightBold ? UIFontWeightSemibold : UIFontWeightRegular)];
    if (!italic) {
        return font;
    }
    
    UIFontDescriptor *fontDescriptor = font.fontDescriptor;
    UIFontDescriptorSymbolicTraits trait = fontDescriptor.symbolicTraits;
    trait |= UIFontDescriptorTraitItalic;
    fontDescriptor = [fontDescriptor fontDescriptorWithSymbolicTraits:trait];
    font = [UIFont fontWithDescriptor:fontDescriptor size:0];
    return font;
}

@end
```

对应地，QMUI Demo 里的”QMUIKit->UIFont+QMUI“界面也增加了更完整的展示。

<img src="https://user-images.githubusercontent.com/1190261/68107360-975c7a00-ff1f-11e9-9b73-30492be27394.png" width="450" />

**Comment by MoLice** [comment]
已发布 [4.0.4](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.4) 修复该问题。
