### ISSUE TITLE
Xcode10下面编译问题

### ISSUE THREAD

**Issue by LYMelody** [Tencent/QMUI_iOS#805]
**Bug 表现**
Xcode10 下面编译不过

**截图**
![image](https://user-images.githubusercontent.com/12960002/68200257-74eb5f00-fffa-11e9-94ee-a9ca63a88bea.png)

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [模拟器iPhone8]
 - iOS 版本: [iOS 11.4]
 - Xcode 版本: [Xcode 10.3]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
建议更新 Xcode 版本，Xcode 11 已经发布好几个月了

**Comment by LYMelody** [comment]
> 建议更新 Xcode 版本，Xcode 11 已经发布好几个月了

主要是打包机上的Xcode暂时还没有升级，目前的不是所有的App都适配了iOS13，还处在一个过渡期😃。试了下在Xcode 11下是OK的，所以只能升级了吗。🙃

**Comment by MoLice** [comment]
你可以自己修改源码，加上 `#ifdef IOS13_SDK_ALLOWED` 的判断
