### ISSUE TITLE
在Xcode 11.2运行下UIView+QMUI.m下会崩溃，在11.1版本的xcode则不会崩溃

### ISSUE THREAD

**Issue by dongzs0907** [Tencent/QMUI_iOS#806]
**Bug 表现**
在项目页面中暂时没有使用到该库，在某一个页面定义了自定义UITextView跳转到该页面就会崩溃在UIView+QMUI.m  475行。  经测试在11.1的xcode没有问题，一旦在11.2的编辑器上就会出现这个问题

**截图**
<img width="1204" alt="1" src="https://user-images.githubusercontent.com/22338972/68284174-ef2de900-00b7-11ea-85aa-034aa650247f.png">
<img width="660" alt="2" src="https://user-images.githubusercontent.com/22338972/68284258-1a183d00-00b8-11ea-847b-8d04a53a79c2.png">

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 12.2]
 - Xcode 版本: [Xcode 11.2]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/799#issuecomment-549218259

![image](https://user-images.githubusercontent.com/1190261/68308197-67f86980-00e7-11ea-8ac5-9cbe1a50a2cc.png)

![image](https://user-images.githubusercontent.com/1190261/68308237-7b0b3980-00e7-11ea-97dc-3320faf75ebc.png)
