### ISSUE TITLE
通过pod 'QMUIKit' 方式使用，为什么版本一直还是3.2.1的，最新的版本没有

### ISSUE THREAD

**Issue by Mandyhold** [Tencent/QMUI_iOS#808]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
pod 'QMUIKit' 

**预期的表现**
修复iOS13闪退，
**其他信息**
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]

**Comment by MoLice** [comment]
这是 pod 使用范畴的问题，你可以先了解一下 pod 常规的用法。你描述的这种场景，猜测是本地pod库没有更新，可以执行pod update
