### ISSUE TITLE
升级到4.0.3，加了self.window.overrideUserInterfaceStyle = UIUserInterfaceStyleLight 闪退

### ISSUE THREAD

**Issue by xiafb** [Tencent/QMUI_iOS#809]
**Bug 表现**
问题的具体描述
为了不支持暗黑模式，加了self.window.overrideUserInterfaceStyle = UIUserInterfaceStyleLight这段代码，但是升级到4.0.3后，闪退

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![截屏2019-11-08下午12 21 44](https://user-images.githubusercontent.com/5442499/68449526-6e3f3080-0222-11ea-8927-e68047c226e9.png)

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.0.3]

**Comment by JerryDream007** [comment]
我也遇到相同问题了，只要设置overrideUserInterfaceStyle就会崩到这里，有什么解决办法吗

**Comment by MoLice** [comment]
同 #898，已修复，等 4.2.1 发布。

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
