### ISSUE TITLE
Tabbar 选中时的图片为纯色,设置图片renderModel 无效

### ISSUE THREAD

**Issue by ChinaJson** [Tencent/QMUI_iOS#811]
**Bug 表现**
问题的具体描述

**截图**
![WechatIMG2537](https://user-images.githubusercontent.com/34496479/68490583-3c5eb600-0284-11ea-8fcb-3668bffc2fe7.jpeg)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
确认一下你的 iOS 版本是 13.0 以上，并且这张图的 renderingMode 为 `UIImageRenderingModeAlwaysOriginal`？

**Comment by ChinaJson** [comment]
ios 版本13.2 renderingMode 各个模式都设置了 始终是显示的tabBart.tintColor 的纯色图片

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/69238336-b2dbac00-0bd2-11ea-8a31-03a198deaa60.png)

![image](https://user-images.githubusercontent.com/1190261/69238371-c850d600-0bd2-11ea-8bd1-5a5135e3afd0.png)

QMUI Demo 里测试并没有发现该问题，请检查自己的业务代码，或者提供一个可复现的 Demo。
