### ISSUE TITLE
QMUIMarqueeLabel 无法显示内容

### ISSUE THREAD

**Issue by lczalh** [Tencent/QMUI_iOS#812]
**Bug 表现**
QMUIMarqueeLabel 在swift没有qmui_initWithFont: textColor:方法
使用QMUIMarqueeLabel(frame: CGRect(x: 0, y: playerImageView.frame.size.height, width: cz_getScreenWidth, height: cz_getFitSize(30)))
创建并添加文字和背景但是一直是透明的。没有任何内容显示

**其他信息**
 - 设备: [例如模拟器、iPhone]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.2]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
透明是因为 `QMUIMarqueeLabel` 里在某些情况下，self.layer.mask 没有被正确布局，导致 label 处于一个 size(0, 0) 的遮罩下，就看不到内容了，下个版本会修复，在此之前可按照下方截图修改本地的代码：
![image](https://user-images.githubusercontent.com/1190261/69155212-41412680-0b1c-11ea-9c78-702978ebab19.png)

至于没有 `qmui_initWithFont: textColor:`，具体是？这个方法是 `UILabel(QMUI)` 里提供的，`QMUIMarqueeLabel` 继承自 `UILabel`，是会带有这个方法的。

**Comment by MoLice** [comment]
已发布 [4.0.4](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.4) 修复该问题。
