### ISSUE TITLE
iOS13以下应用内切换主题后TabBar图片颜色不跟随主题变化

### ISSUE THREAD

**Issue by evanzhou1989** [Tencent/QMUI_iOS#813]
**Bug 表现**
iOS12中在应用内切换theme，设置的tabBarItemImageColor并没有跟随theme改变

**截图**
<img width="1164" alt="屏幕快照 2019-11-10 下午2 26 56" src="https://user-images.githubusercontent.com/6427544/68540063-f8c09500-03c6-11ea-900f-e2d19202162c.png">
![Simulator Screen Shot - iPhone 8 Plus - 2019-11-10 at 14 26 46](https://user-images.githubusercontent.com/6427544/68540065-fc541c00-03c6-11ea-8e0c-c1ecae73c702.png)

**如何重现**
在QMUIDemo_iOS中QMUIConfigurationTemplateDark设置QMUICMI.tabBarItemImageColor， 然后应用切换Theme到Dark

**预期的表现**
应用内切换theme后tabbar item的图片颜色应该跟随设置的tabBarItemImageColor

**其他信息**
 - iOS 版本: iOS13以下
 - QMUI 版本: [4.0.3]

**Comment by evanzhou1989** [comment]
简单看了下可能部分原因是在UITabBar+QMUI.m中强行指定original影响的，参考下图~
<img width="1129" alt="屏幕快照 2019-11-10 下午2 41 07" src="https://user-images.githubusercontent.com/6427544/68540208-cb74e680-03c8-11ea-8968-2adbf9240e20.png">
<img width="1134" alt="屏幕快照 2019-11-10 下午2 44 45" src="https://user-images.githubusercontent.com/6427544/68540209-cc0d7d00-03c8-11ea-9f5c-0c3167722bbb.png">

**Comment by LYluyu** [comment]
我今天升级了之后也遇到了这个问题，在4.0.0的时候，没有这个问题的。

**Comment by LYluyu** [comment]
@evanzhou1989 请问一下你们最后是增加图片资源来解决吗？

**Comment by evanzhou1989** [comment]
> @evanzhou1989 请问一下你们最后是增加图片资源来解决吗？

没有，这应该算是库的Bug。

**Comment by MoLice** [comment]
这个是 QMUI 的 bug。

在 4.0.2 版本里为了修复 #736 的 bug，我们对 `UITabBar (QMUI)` 进行了修改，具体 commit diff 可点击查看 https://github.com/Tencent/QMUI_iOS/commit/3fa84db4a80c273b82a728b1c521e0428e328b7e#diff-250f11f1283ff2af409ffc265f61c475 。也正是因为该 commit，引发了本 issue 的问题。

下个版本会修复该问题。

**Comment by MoLice** [comment]
已发布 [4.0.4](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.4) 修复该问题。
