### ISSUE TITLE
-[UINavigationController setViewControllers:] 情况下 NeedsBackBarButtonItemTitle 不生效

### ISSUE THREAD

**Issue by chenfengfeng** [Tencent/QMUI_iOS#814]
**Bug 表现**
切换语言需要重新加载rootViewController，这边的框架结构是以tabbar为主，有4个导航控制器分别控制每个控制器。
切换语言重新加载了控制器，就会出现问题：
```swift
 let main = Main.instantiateInitialViewController() as! FFTabBarController
 main.selectedIndex = 2
 let setting  = My.instantiateViewController(withIdentifier: "SettingController")
let language = My.instantiateViewController(withIdentifier: "LanguageController")
let nav = main.selectedViewController as! FFNavigationController
var vcs = nav.viewControllers
vcs.append(setting)
vcs.append(language)
DispatchQueue.main.async {
        UIApplication.shared.keyWindow?.rootViewController = main
         nav.viewControllers = vcs
}
```
FFTabBarController继承QMUINavigationController，已经设置了needsBackBarButtonItemTitle = false

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下是不会显示返回的文字显示

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 12]
 - Xcode 版本: [Xcode 11.2]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
配置表 `NeedsBackBarButtonItemTitle` 对 `-[UINavigationController setViewControllers:]` 不生效，这个 bug 在下个版本会修复。

**Comment by MoLice** [comment]
已发布 [4.0.4](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.4) 修复该问题。
