### ISSUE TITLE
无法更换或自定义QMUINavigationTitleView中AccessoryTypeView

### ISSUE THREAD

**Issue by RomanticEncounter** [Tencent/QMUI_iOS#815]
只提供了QMUINavigationTitleViewAccessoryTypeDisclosureIndicator 的枚举类型，使用的都是QMUI默认的Indicator图片，无法更换或自定义AccessoryTypeView的图片和动画效果

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/68652646-e11f1300-0564-11ea-8385-691482105fc9.png)
