### ISSUE TITLE
iOS  iPhone   13.1.2   会崩溃

### ISSUE THREAD

**Issue by SongZhaoJie** [Tencent/QMUI_iOS#817]
iOS  iPhone   13.1.2   会崩溃
<img width="1198" alt="截屏2019-11-13下午11 03 15" src="https://user-images.githubusercontent.com/29090582/68775902-27aa6580-066a-11ea-800e-a3fa6b6d2184.png">

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/68831106-86aebf80-06e8-11ea-957b-75b67094e631.png)

![image](https://user-images.githubusercontent.com/1190261/68831233-bcec3f00-06e8-11ea-9e1b-b469a59a5310.png)

#628
