### ISSUE TITLE
引入后项目中所有UIButton 都会无效

### ISSUE THREAD

**Issue by gzw521886** [Tencent/QMUI_iOS#819]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
该 issue 因不包含有效信息而被关闭，请补充详细信息再 reopen。
