### ISSUE TITLE
iOS13.1.2系统 已经更新到最新的版本4.0.3还是崩溃

### ISSUE THREAD

**Issue by hzw0407** [Tencent/QMUI_iOS#821]
**Bug 表现**
启动崩溃

**截图**
![1573897511616](https://user-images.githubusercontent.com/25050158/68991368-12674e00-0899-11ea-8a59-f712d0e6c562.jpg)

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.1.2]
 - Xcode 版本: [Xcode 11.2.1]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
项目里已不存在这个代码，Clean Project？
