### ISSUE TITLE
关于NavigationBar分割线的问题

### ISSUE THREAD

**Issue by friendsheeps** [Tencent/QMUI_iOS#823]
**Bug 表现**
无意中发现相同的设置在iOS11之后NavigationBar分割线不显示，iOS11之前显示

**截图**
<img width="1024" alt="截屏2019-11-18下午1 11 39" src="https://user-images.githubusercontent.com/13128046/69026283-56776180-0a05-11ea-8b26-1029ce851fef.png">
 这是QMUIConfigurationTemplate.m中的设置

**如何重现**

![iOS10 3 1](https://user-images.githubusercontent.com/13128046/69026476-f634ef80-0a05-11ea-8a4d-728a8f4e27e2.png)
![iOS11 4](https://user-images.githubusercontent.com/13128046/69026478-f9c87680-0a05-11ea-9bd8-1dae3ae62102.png)
![iOS12 2](https://user-images.githubusercontent.com/13128046/69026565-62175800-0a06-11ea-803d-3f7d130c1930.png)

三张图分别用模拟器截的10.3.1、11.4、12.2系统
iOS11之后的系统导航栏分割线不显示，iOS11之前的系统导航栏分割线显示

**预期的表现**
希望分割线都不显示，虽然现在iOS10及以前的用户可能很少，但项目要求最低是iOS10，而且很想弄清楚出现这种问题的原因。

**其他信息**
 - 设备: [模拟器]
 - iOS 版本: [iOS 10.3.1、iOS 11.4、iOS 12.2]
 - Xcode 版本: [Xcode 11.2.1]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
UINavigationBar.shadowImage 对 `UIImage.new` 在不同 iOS 版本下的表现差异本来就是如此，系统问题。要隐藏分隔线请参考 QMUI Demo，用 `UIColor.clearColor`。

![image](https://user-images.githubusercontent.com/1190261/69029512-1e295080-0a10-11ea-8647-dfc54bc4905a.png)
