### ISSUE TITLE
iOS13.1.2启动崩溃

### ISSUE THREAD

**Issue by hzw0407** [Tencent/QMUI_iOS#824]
<img width="480" alt="图片" src="https://user-images.githubusercontent.com/25050158/69033210-6862ff80-0a19-11ea-9fbb-71e9c22043e1.png">

崩溃在这个地方
<img width="848" alt="图片" src="https://user-images.githubusercontent.com/25050158/69033248-89c3eb80-0a19-11ea-92d7-63b666da0a43.png">

**Comment by MoLice** [comment]
截图的 QMUI 这个代码只是 swizzle，这个没关系，请检查自己的业务代码。

**Comment by hzw0407** [comment]
> 截图的 QMUI 这个代码只是 swizzle，这个没关系，请检查自己的业务代码。

但是在iOS12系统的手机上是没问题的 同样的机型

**Comment by MoLice** [comment]
> > 截图的 QMUI 这个代码只是 swizzle，这个没关系，请检查自己的业务代码。
> 
> 但是在iOS12系统的手机上是没问题的 同样的机型

这个并不能证明就是 QMUI 代码引起的，因为你的业务也可能在不同的 iOS 版本里有不一样的逻辑，或者由于系统本身的差异，相同的代码也可能出现不同的表现。

要证明跟 QMUI 这个方法无关很简单，你直接把这段注释掉然后 Clean Project 再尝试就能发现继续 crash 在别的地方了。
