### ISSUE TITLE
qmui pod引入后  ios13版本 自动给tabbar加了一个UIVisualEffectBackdropView元素 ,怎么移除

### ISSUE THREAD

**Issue by caicaicaich** [Tencent/QMUI_iOS#826]
预期结果: 没有pod qmui

![屏幕快照 2019-11-20 下午7.56.14.png](https://i.loli.net/2019/11/20/ExUqsB6S4Ju3Qfr.png)

实际结果: 
![屏幕快照 2019-11-20 下午7.52.02.png](https://i.loli.net/2019/11/20/KSVPLn1CbqkhZ6X.png)

**Comment by MoLice** [comment]
这应该是因为 QMUI 在 iOS 13 下使用系统新的 [UITabBar.standardAppearance](https://developer.apple.com/documentation/uikit/uitabbar/3198046-standardappearance) 接口来设置样式。（没测试过，只是提供思路）你可以尝试为 UITabBar 设置透明的背景图，或者直接将磨砂移除：
```Objective-C
tabBar.standardAppearance.backgroundImage = [UIImage qmui_imageWithColor:UIColor.clearColor];
tabBar.standardAppearance.backgroundEffect = nil;
```

**Comment by caicaicaich** [comment]
恩,想到了应该是tabbar 的Appearance 设置的问题,没细去尝试,确实是backgroundEffect设置为nil,就不显示了
