### ISSUE TITLE
WKWebView runJavaScriptAlertPanelWithMessage回调crash

### ISSUE THREAD

**Issue by R1n0-w** [Tencent/QMUI_iOS#827]
**Bug 表现**
自建一个基于WKWebView的vc,实现WKUIDelegate代理的runJavaScriptAlertPanelWithMessage方法时发生crash,最后crash停留在NSObject+QMUI.m内的+ (void)load方法。

**截图**
![image](https://user-images.githubusercontent.com/44944693/69302604-1f978a80-0c55-11ea-9ca9-c9abd445948e.png)
![image](https://user-images.githubusercontent.com/44944693/69302613-245c3e80-0c55-11ea-8a89-d15a0cb01ef2.png)

**如何重现**
建立基于WKWebView的vc,实现WKUIDelegate代理的runJavaScriptAlertPanelWithMessage方法,web执行alert方法

**预期的表现**
正常弹出alert而不crash

**其他信息**
 - 设备: iPhone
 - iOS 版本: 13.0
 - Xcode 版本: 11.2.1
 - QMUI 版本: 4.0.3

**Comment by MoLice** [comment]
那只是个 swizzle，具体原因你看 crash 时的控制台报错，按提示去检查你的业务代码即可。
