### ISSUE TITLE
QMUIScrollAnimator 绑定后奔溃

### ISSUE THREAD

**Issue by SwiftBMan** [Tencent/QMUI_iOS#828]
**Bug 表现**
绑定自己的tableView 奔溃

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
这样的 issue 换做你自己来查问题，你能查吗？
