### ISSUE TITLE
QMUITips  tips.userInteractionEnabled

### ISSUE THREAD

**Issue by azureplus** [Tencent/QMUI_iOS#829]
**现存问题或期望目标**
对于功能的建议，请说明具体的场景，现在的代码为什么无法实现需求。
对于代码设计方面的建议，请说明目前的问题所在。
QMUITips 弹窗 不影响其他 UI问题

+ (QMUITips *)createTipsToView:(UIView *)view {
    QMUITips *tips = [[QMUITips alloc] initWithView:view];
    tips.userInteractionEnabled = NO;
    [view addSubview:tips];
    tips.removeFromSuperViewWhenHide = YES;
    return tips;
}

**Comment by azureplus** [comment]
-(instancetype)initWithButton:(QMUIButton *)button{
    if (self = [super init]) {
        self.height = -1;
        _button = button;
        [self.button addTarget:self action:@selector(handleButtonEvent:) forControlEvents:UIControlEventTouchUpInside];
        [self addSubview:self.button];
        
        [self updateAppearanceForMenuButtonItem];
    }
    return self;
}
+ (instancetype)itemWithButton:(nullable QMUIButton *)button handler:(nullable void (^)(QMUIPopupMenuButtonItem *aItem))handler;
{
    QMUIPopupMenuButtonItem *item = [[QMUIPopupMenuButtonItem alloc] initWithButton:button];
    item.handler = handler;
    return item;
}

**Comment by azureplus** [comment]
建议新增 MaterialComponents 点击效果

**Comment by MoLice** [comment]
MaterialComponents 点击效果是指？

**Comment by MoLice** [comment]
至于主 issue，想要表达的是什么事情？

**Comment by azureplus** [comment]
> MaterialComponents 点击效果是指？

按钮点击后有 ripple效果, 同安卓的哦

**Comment by azureplus** [comment]
tips.userInteractionEnabled  其他没有无法响应点击效果

**Comment by azureplus** [comment]
tips.userInteractionEnabled  其他没有无法响应点击效果

**Comment by MoLice** [comment]
> > MaterialComponents 点击效果是指？
> 
> 按钮点击后有 ripple效果, 同安卓的哦

这个不是通用需求，不会加到 QMUI 里，可以用其他库实现。




> tips.userInteractionEnabled 其他没有无法响应点击效果

如果用 `tips.userInteractionEnabled = NO` 可以让背后的界面支持点击，只是 tip 内部不支持点击。如果想要 tips 内部和背后界面同时支持点击，目前只能通过重写 tips.qmui_hitTestBlock 来实现。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
