### ISSUE TITLE
iOS 13 下 UISearchBar.qmui_placeholderColor 在某些时机下设置时无效

### ISSUE THREAD

**Issue by JaminZhou** [Tencent/QMUI_iOS#830]
iOS13 UISearchBar的searchTextField.attributedPlaceholder 现在是无解吗？设置NSForegroundColor没有用

**Comment by MoLice** [comment]
iOS 13 下系统的 UISearchBar.textField.attributedPlaceholder 机制有些变化，导致某些场景修改 placeholder 无效，我们再看看怎么解决。在此之前你可以尝试把 placeholderColor 的修改时机延后到 viewWillAppear: 或者 viewDidAppear: 后。

**Comment by MoLice** [comment]
在新版本发布之前，可以先将以下代码添加到 UISearchBar+QMUI.m 的 +load 方法内：
```Objective-C
if (@available(iOS 13.0, *)) {
    ExtendImplementationOfVoidMethodWithoutArguments([UISearchBar class], @selector(didMoveToWindow), ^(UISearchBar *selfObject) {
        if (selfObject.qmui_placeholderColor) {
            selfObject.placeholder = selfObject.placeholder;
        }
    });
}
```

**Comment by JaminZhou** [comment]
> 在新版本发布之前，可以先将以下代码添加到 UISearchBar+QMUI.m 的 +load 方法内：
> 
> ```objc
> if (@available(iOS 13.0, *)) {
>     ExtendImplementationOfVoidMethodWithoutArguments([UISearchBar class], @selector(didMoveToWindow), ^(UISearchBar *selfObject) {
>         if (selfObject.qmui_placeholderColor) {
>             selfObject.placeholder = selfObject.placeholder;
>         }
>     });
> }
> ```

感谢！

**Comment by MoLice** [comment]
已发布 [4.0.4](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.4) 修复该问题。
