### ISSUE TITLE
您好，请问一下关于不等高cell时，为何我写的先调用sizeThatFits，再调用layoutSubviews，而demo是先调用layoutSubviews，再调用sizeThatFits

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#832]
**Bug 表现**
问题的具体描述
您好，请问一下关于不等高cell时，为何我写的先调用sizeThatFits，再调用layoutSubviews，而demo是先调用layoutSubviews，再调用sizeThatFits，从而导致要计算两次高度。好郁闷啊。

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
从 tableView/collectionView 的角度，正确顺序应该是要渲染某个 indexPath 的 cell 前先调用它的 sizeThatFits:（这一步不需要你主动调用），得知这个 cell 的 size 后，把它放在正确的位置，并设置它的 size。而因为设置了 size，导致 cell 内部的 layoutSubviews 被触发（这一步也不需要你主动触发），完成内部的布局，整个流程到此结束。

所以我不确定你说“你写的先调用 sizeThatFits”，是不是意味着这两步你都人工干预了？如果人工干预了，那出了问题就要看你干预的代码是怎么写的。如果不人工干预，系统是会自己确保正确的顺序的。
