### ISSUE TITLE
QMUIModalPresentationViewController 在自定义了 layoutBlock 但没自定义 showingAnimation 时有布局问题

### ISSUE THREAD

**Issue by whatsbug** [Tencent/QMUI_iOS#834]
**Bug 表现**
如果用'showInView'的方式弹出QMUIModalPresentationViewController控制器，当push到下一个控制器然后返回时，QMUIModalPresentationViewController布局异常。

**截图**
![Kapture 2019-11-26 at 11 20 08](https://user-images.githubusercontent.com/7418617/69597456-01f56700-1041-11ea-9ae4-e9e703e5de5e.gif)

**如何重现**
请参考demo：https://github.com/whatsbug/Demo4QMUI

**其他信息**
 - Xcode 版本: [Xcode 10.3]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
[issue.mov.zip](https://github.com/Tencent/QMUI_iOS/files/3890789/issue.mov.zip)

用你的 Demo 测试并没有发现问题，iOS 13.1 iPhone 11 Pro Max

**Comment by MoLice** [comment]
没留意到你的录屏里是 12.x 的模拟器，与 iOS 版本有关的问题请明确写出来，issue 模板里也有让提供设备信息，但你删掉了。

**Comment by whatsbug** [comment]
因为gif里面有iOS版本信息了，所以我就删了。请问什么情况，我用模拟器iPhone XR(12.4)、iPhone 6(11.0.1)测试都有同样问题。

**Comment by MoLice** [comment]
这里对自定义了 layoutBlock 但没自定义 showingAnimation 的处理有 bug，下个版本会修复，在此之前你可以先在业务里手动写 showingAnimation，示例代码如下：

```Objective-C
self.modalViewControllerForAddSubview.showingAnimation = ^(UIView * _Nullable dimmingView, CGRect containerBounds, CGFloat keyboardHeight, CGRect contentViewFrame, void (^ _Nonnull completion)(BOOL)) {
    dimmingView.alpha = 0;
    contentView.frame = CGRectSetY(contentView.frame, CGRectGetHeight(containerBounds));
    [UIView animateWithDuration:.25 delay:0 options:QMUIViewAnimationOptionsCurveOut animations:^{
        dimmingView.alpha = 1;
        contentView.frame = contentViewFrame;
    } completion:completion];
};
```

**Comment by MoLice** [comment]
已修复。
