### ISSUE TITLE
您好，关于log输出，如何关闭？

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#835]
**Bug 表现**
问题的具体描述
请问这个图标如何关闭？
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/16254669/69608007-6cb69a80-1061-11ea-8c23-bf79d0574188.png)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/69611163-2e70a980-1068-11ea-9c10-36a5bb464c10.png)

![image](https://user-images.githubusercontent.com/1190261/69611260-5a8c2a80-1068-11ea-88c3-81fe83f29642.png)
