### ISSUE TITLE
emptyView 加载数据完成刷新的时候会回弹一下

### ISSUE THREAD

**Issue by xhjss** [Tencent/QMUI_iOS#837]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

emptyView 加载数据完成刷新的时候会回弹一下 看压缩文件
[1574930188480757.mp4.zip](https://github.com/Tencent/QMUI_iOS/files/3900660/1574930188480757.mp4.zip)

**Comment by MoLice** [comment]
bug 表现看到了，相关代码呢？没有代码的情况下，只能提供几个调试思路你看看：
1. 跳动是 QMUIEmptyView 的高度发生变化导致的，还是 QMUIEmptyView 高度没变但内部 layoutSubviews 时某些计算的值发生变化导致的？
2. 排查一下是否是受 contentInset 的影响。
3. 对你觉得布局有问题的 view，通过 qmui_frameWillChangeBlock 去监听什么时候被设置了错误的值即可，所有的非预期布局问题都可以通过这个思路去解决。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭

**Comment by runcong1989** [comment]
是不是可以在layoutEmptyView 进行如下处理,判断contentinset变更是否与MJ头部高度一致,强行变为0
if (tableView.mj_header && tableView.mj_header.frame.size.height == insets.top) {
        
        insets.top = 0;
    }
