### ISSUE TITLE
pod引入qmui之后,tabbaritem  设置 titlepositionadjustment 失效

### ISSUE THREAD

**Issue by caicaicaich** [Tencent/QMUI_iOS#840]
**Bug 表现**
使用qmui,作为ui框架,使以前设置的 titlepositionadjustment  失效

**截图**
预期结果:
![Desktop_no](https://user-images.githubusercontent.com/30227183/69928789-be46a580-14f7-11ea-8e15-03359fac6faf.jpg)
pod add qmui之后结果: 无其他pod,无其他tabbar 分类
![Jietu20191202-112939](https://user-images.githubusercontent.com/30227183/69928863-f64de880-14f7-11ea-8342-8c983d702b0c.jpg)

**Comment by MoLice** [comment]
iOS 13 针对 UINavigationBar、UITabBar 新增了 UIBarAppearance 的方式去设置 bar 的样式，同时也引入了一些 bug，导致某些场景下用 iOS 12 及以前的方式去设置 tabBar 样式会失效（例如 #618 #672），因此 QMUI 在 iOS 13 下会使用新的接口，在 iOS 12 下会使用旧的接口，而新旧接口是不兼容的，换句话说，iOS 13 下如果你使用 UIBarAppearance 的方式去设置样式，就会导致旧接口失效，猜测你的 titlePositionAdjustment 失效也是这个原因。你可以尝试区分 iOS 版本，例如：

```Objective-C
if (@available(iOS 13.0, *)) {
    [self.tabBar.standardAppearance qmui_applyItemAppearanceWithBlock:^(UITabBarItemAppearance * _Nonnull itemAppearance) {
        itemAppearance.normal.titlePositionAdjustment = UIOffsetMake(0, -12);
    }];
} else {
    vc1.tabBarItem.titlePositionAdjustment = UIOffsetMake(0, -12);
}
```

**Comment by caicaicaich** [comment]
非常感谢,这样设置是有效的,我的**预期结果**和**实际结果**的截图,都是在iphone 11模拟器,ios 版本 13.1 上跑的,提完这个问题后,由于时间原因,我就先让ui帮我把image和title切到一张图上,不设置title先临时解决.

**Comment by RenChuanChuan** [comment]
mark
