### ISSUE TITLE
QMUICommonTableViewController在viewDidLayoutSubviews中使用Masonry约束TableView无效

### ISSUE THREAD

**Issue by WOHANGO** [Tencent/QMUI_iOS#843]
**Bug 表现**
QMUICommonTableViewController在viewDidLayoutSubviews中使用Masonry的mas_makeConstraints约束TableView无效，只能在layoutTableView中约束，因为我是使用QMUI_iOS_Templates创建模板，所以很多时候会忽略layoutTableView的存在。这个能否优化一下？

**其他信息**
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11.1]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
按道理你在 `viewDidLayoutSubviews` 里写约束没用的话，在 `layoutTableView` 里写应该也是没用的，因为对于子类而言，父类里的这两个方法的时机是一样的，都晚于子类的逻辑。除非你在 `layoutTableView` 里写约束时，没有调用 super？如果没有调用 super，那跟你把约束写在哪里是没关系的，关键在于你屏蔽了父类里对 tableView 的布局逻辑。如果是这种情况，那么屏蔽 super 来令约束生效是合理的实现方法，请放心使用。

至于经常容易遗忘 layoutTableView，这确实是个问题，与是否通过 template 创建文件无关。非约束的话，一般情况下就算不知道 layoutTableView 存在也没关系的，只是用约束时就会有“需要屏蔽 super”的问题，这个我们后续再看怎么优化，目前暂时没有好想法。

**Comment by WOHANGO** [comment]
明白，谢谢提醒，确实忘记调用super导致layoutTableView约束有效
