### ISSUE TITLE
UIView+QMUI 出现崩溃

### ISSUE THREAD

**Issue by CoderMaurice** [Tencent/QMUI_iOS#871]
**Bug 表现**

我有一个view，重写了Frame的get方法

```
- (CGRect)frame
{
    __block CGRect frame;
    CGAffineTransformIdentityBlock(self, ^{
        frame = [super frame];
    });
    return frame;
}
```
```
// 临时还原transform状态以获取正确的frame
void CGAffineTransformIdentityBlock(UIView *view, void (^block)(void)) {
    //1：记录当前transform状态
    CGAffineTransform lastTransform = view.transform;
    //2：还原transform，保证获取的frame是正确的frame
    view.transform = CGAffineTransformIdentity;
    //3：操作frame
    block();
    //4：设置回还原之前的transform状态
    view.transform = lastTransform;
}
```

会在UIView+QMUI.m的第[796行](https://github.com/Tencent/QMUI_iOS/blob/521eb0835bf8131860ad71de27d64dd69eabd21e/QMUIKit/UIKitExtensions/UIView%2BQMUI.m#L796)无限循环

不知道是否有办法解决呢

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by jiasongs** [comment]
transform的setter方法调用了frame的get方法，你重写的frame的get方法里又调用了transform的setter方法，导致了无限循环，你可以使用- (CGRect)xx_frame，换一个名字

**Comment by CoderMaurice** [comment]
主要是功能比较复杂牵扯到很多方面
如果换一个名字的话怕改的不完整引出bug

**Comment by jiasongs** [comment]
> 主要是功能比较复杂牵扯到很多方面
> 如果换一个名字的话怕改的不完整引出bug

这样的话只能等维护者修改源码了
不过还是不建议直接重写Frame的get方法，可能会产生副作用

**Comment by CoderMaurice** [comment]
@jiasongs 谢谢老哥
