### ISSUE TITLE
QMUICMI.tabBarShadowImageColor 10.3.3无效

### ISSUE THREAD

**Issue by deanli08** [Tencent/QMUI_iOS#875]
**Bug 表现**
QMUICMI.tabBarShadowImageColor 10.3.3无效

**截图**
设置了 QMUICMI.tabBarShadowImageColor = UIColorClear 在ios 10.3.3 还是会显示默认黑色分割线

**预期的表现**
设置了 QMUICMI.tabBarShadowImageColor = UIColorClear 不显示

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 10.3.3]
 - Xcode 版本: [Xcode 11.]
 - QMUI 版本: [4.0.3]

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/70599198-8b06c380-1c27-11ea-9e03-329eede37661.png)

没发现你说的问题？
