### ISSUE TITLE
XCode10的问题

### ISSUE THREAD

**Issue by ysyuan24** [Tencent/QMUI_iOS#878]
您好！Xcode10 没有UIWindowScene相关属性，如果不升级11，请问该如何处理比较合适？

**Comment by MoLice** [comment]
请在代码里搜索 `IOS13_SDK_ALLOWED` 的使用，参考它，把源码里 Xcode 10 无法编译的地方都包上即可。

**Comment by ysyuan24** [comment]
好的，感谢！
因为使用CocoaPods安装的，不希望改动源码。如果可以，希望由您那边能把这块地方修改了。谢谢！

**Comment by MoLice** [comment]
目前对 iOS 13 新增的 API 的使用量激增，逐个加保护不现实，而 Xcode 11 已发布半年，苹果也即将强制要求使用 Xcode 10，所以建议你自行修改源码，QMUI 将不再作检查。
