### ISSUE TITLE
Xcode 11 支持了分屏模式，原先拿window的方式可能会造成crash

### ISSUE THREAD

**Issue by SupermanChao** [Tencent/QMUI_iOS#879]
**Bug 表现**
支持分屏模式的APP通过 UIApplication.sharedApplication.delegate.window 拿当前window会有问题

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. Xcode 11 创建默认工程
2. [UIViewController visibleViewController];

**预期的表现**
正常情况下，应该是什么表现

**其他信息**

**Comment by MoLice** [comment]
重复 issue #766
