### ISSUE TITLE
xcode 11 TextField 连续点击崩溃.

### ISSUE THREAD

**Issue by ench44** [Tencent/QMUI_iOS#880]
**Bug 表现**
问题的具体描述
专门测试了一下,建立了一个新的空项目, 在main storyboard里面, 只拖放了一个textfiedl, 如果没有pod install qmuikit, 怎么点击都没事, 安装后,连续点几下就崩溃. 我一个项目整个都用的QMUI. 我找了一下网上的说法,我猜测是你们访问了运行时访问了textfield的私有变量导致的. 求你们火速解决此问题....要不然我的项目根本没法提交审核.

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. 新建空项目. 在main storyboard里面放一个textfield, 这是怎么点击都没问题, 安装QMUIKit后.运行期来连续点两三下就崩了,不管是模拟器还是真机都一样.

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [模拟器、iPhone 10 max]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by ench44** [comment]
可以抓紧改么.真的特别急....

**Comment by jiasongs** [comment]
你是用的xcode 11.2 ?

**Comment by ench44** [comment]
@jiasongs Version 11.2.1 (11B500)

**Comment by ench44** [comment]
@jiasongs 求帮助....万分感谢

**Comment by jiasongs** [comment]
应该是iOS13多窗口导致的问题。
问题在`UIMenuController+QMUI.h 102行`
<img width="1051" alt="图片" src="https://user-images.githubusercontent.com/22904757/70761693-16e43100-1d89-11ea-9652-88418fa33d82.png">
等维护者修复吧，这样的地方有不少
#766

**Comment by cuihangfei** [comment]
-[NSInvocation getArgument:atIndex:]: index (0) out of bounds [-1, -1]点击textFiled 报这个错误 崩溃。哪位大神指导

**Comment by ench44** [comment]
请问这个问题啥时候能修复啊...我要提交代码审核啊....全面崩溃中...

**Comment by MoLice** [comment]
这种类型的代码在 QMUI 里还很多，需要等全面适配 UIWindowScene 后才能完美解决，如果你只是想修复这个场景，避免 crash，那你可以先注释掉 UIMenuController+QMUI.m 里与 window 相关的代码。

**Comment by ench44** [comment]
@MoLice 太感谢了. 我先试试看.

**Comment by ench44** [comment]
@MoLice 大神, 不看不知道, 一看全是与window相关的...注释了就跑不起了...求帮助. 真的特别急.实在不行我只能用笨方法先忍痛去除框架了...愁死我了.

**Comment by MoLice** [comment]
为什么会跑不起来？
![image](https://user-images.githubusercontent.com/1190261/71076885-667b9000-21c1-11ea-8c72-1c9d353a7fdb.png)

**Comment by ench44** [comment]
@MoLice 我把你图中的这两个方法里你注释的我都注释了.但是跑起来.长按还是崩. 一样的错误信息. textView 也一样

**Comment by MoLice** [comment]
崩溃都是因为 UIApplication.sharedApplication.windows 或 window，你把遇到的地方都注释就可以了，但可能会引发其他问题。使用 UIWindowScene 的项目目前不建议使用 QMUI。

**Comment by ench44** [comment]
听到你这消息, 我绝望了. 我得把整个项目都换掉. 郁闷的要死 @MoLice

**Comment by MoLice** [comment]
因为 UIWindowScene 本来就是个大工程，不是改几句代码就可以适配完成的，QMUI 的组件很多，而且要考虑到几千个项目的使用场景，这里的工作量和设计思路不是单纯改一个项目的业务代码那么简单的，这也是为什么 iOS 13 推出后 QMUITheme 很快就发布了但对 UIWindowScene 的支持迟迟还没做完。因为框架没适配导致业务项目无法使用 UIWindowScene 这确实也很难接受，但目前的开发进展也是能做到的最快的了，我们的业余时间也不多。

个人建议如果你着急兼容，又无法移除 QMUI，那可以在业务项目里只处理你们用到的组件，因为 QMUI 有几十个组件，并非每个项目都用到所有的组件，可能你们只需要处理其中两三个，让它能正常使用不 crash，就足够了，这样的时间投入可能比等待 QMUI 全部兼容完或者移除 QMUI 要来得快一点。有些适配也很简单，无非就是换一下获取 window 的方式。不管 QMUI 是否适配完，业务项目的开发人员都应该对 UIWindowScene 的改动和使用方式熟悉，你应该分清楚这里的工作量到底是在于代码改动还是在于学习。

**Comment by ench44** [comment]
@MoLice 好的. 非常感谢.

**Comment by MoLice** [comment]
UIScene 问题由 #766 统一跟进。
