### ISSUE TITLE
QMUIImagePreviewViewController通过手势退出预览时的位置不正确

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#882]
**Bug 表现**
当通过单击退出预览时，设置imagePreviewViewController.sourceImageView即可实现此功能。
但是通过手势拖拽的话，如何设置呢？

**截图**
![Dec-17-2019 12-27-09](https://user-images.githubusercontent.com/34535969/70964893-9abf5580-20c8-11ea-8ab8-c30f80a6fc3f.gif)

截图的代码
[QDImagePreviewViewController2.m.zip](https://github.com/Tencent/QMUI_iOS/files/3971449/QDImagePreviewViewController2.m.zip)

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 13.2.2]
 - Xcode 版本: [Xcode 11.2.1]
 - QMUI 版本: [4.0.4]

**Comment by fanyuecheng** [comment]
哦 解决了 
``` 
- (void)imagePreviewView:(QMUIImagePreviewView *)imagePreviewView didScrollToIndex:(NSUInteger)index {
    __weak __typeof(self)weakSelf = self;
    self.imagePreviewViewController.sourceImageView = ^UIView *{
        return [weakSelf.floatLayoutView viewWithTag:index + 1000];
    };
}
 
```

**Comment by MoLice** [comment]
这里的例子确实比较简单，后续改成九宫格展示

**Comment by MoLice** [comment]
已更新 Demo：https://github.com/QMUI/QMUIDemo_iOS/commit/dfaf86161402c2e644f1c3c115655c42e9255ef1
