### ISSUE TITLE
UILabel设置qmui_lineHeight后，文字不居中

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#883]
**现存问题或期望目标**
UILabel设置qmui_lineHeight后，文字不居中
<img width="480" alt="图片" src="https://user-images.githubusercontent.com/22904757/71060252-ec86df00-219f-11ea-8e87-09ef557cf9af.png">
显示效果，如下图所示：
<img width="639" alt="图片" src="https://user-images.githubusercontent.com/22904757/71060207-daa53c00-219f-11ea-8cfb-dbe8034b23f5.png">
解决方案：
目前我是这样解决的这个问题
<img width="1024" alt="图片" src="https://user-images.githubusercontent.com/22904757/71060325-21933180-21a0-11ea-9136-b88be4b72c57.png">

**Comment by jiasongs** [comment]
可以hookUILabel的这两个方法，替换成自己的实现。

**Comment by MoLice** [comment]
设置了行高后，sizeToFit 的 label，文字偏下，这是 UILabel 设计如此，QMUI 不打算对此做默认的调整（因为大部分人的预期是与系统原生保持一致，这里改了 lineHeight 就只改 lineHeight，baseline 如果有需求，QMUI 会再开一个 qmui_baseline 的属性，而不是在 lineHeight 里默认改了 baseline），因此如果需要调整文字在垂直方向上的位置，目前需要自行修改 NSBaselineOffsetAttributeName。
