### ISSUE TITLE
QMUILabel在某种情况下莫名的显示右侧border

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#887]
**Bug 表现**
在项目里突然发现一个莫名其妙的bug，在xs max 设备（包括模拟器）下会出现（暂未发现其他设备），QMUILabel未设置任何qmui_border等属性，但是会显示右侧border。
我也不确定是不是QMUI引起的，或是系统bug，因为UILabel也会这样。
当不给label设置text，或不给label设置backgroundColor（或设置透明色），就不会出现这个问题。

**截图**
![截图](https://user-images.githubusercontent.com/34535969/71402434-cfeb1b00-2667-11ea-8e78-7593d09bf835.png)

```  
QMUILabel *label = [[QMUILabel alloc] init];  
label.backgroundColor = UIColorWhite;  
label.text = @"";  
label.frame = CGRectMake(80, 20, SIDE_MENU_WIDTH - 140, 40);  

```  
完整代码在这，拉入qmui demo中即可
[QDModalPresentationViewController.m.zip](https://github.com/Tencent/QMUI_iOS/files/3997668/QDModalPresentationViewController.m.zip)

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone Xs Max]
 - iOS 版本: [iOS 13.3]
 - Xcode 版本: [Xcode 11.3]
 - QMUI 版本: [4.0.4]

**Comment by whatsbug** [comment]
你这个问题跟框架没关系，估计是像素不对齐导致的哦

**Comment by fanyuecheng** [comment]
那何解？

**Comment by whatsbug** [comment]
如果真的是设置控件frame时像素没对齐的话，你只需要保证frame里面的值是整数就行

**Comment by whatsbug** [comment]
请问是不是像素没对齐导致的？

**Comment by MoLice** [comment]
如果需要像素对齐，用 CGRectFlatMake、CGRectSetXY 系列都可以，搜索源码的 flat() 函数。
