### ISSUE TITLE
QMUITableViewCell.m  代码bug

### ISSUE THREAD

**Issue by Libogold** [Tencent/QMUI_iOS#888]
**Bug 表现**
问题的具体描述
QMUITableViewCell.m 第103行到112行
if (hasCustomTextLabelEdgeInsets) {
            **textLabelFrame.origin.x += self.textLabelEdgeInsets.left - self._imageEdgeInsets_.right;**
            textLabelFrame.origin.y += self.textLabelEdgeInsets.top - self.textLabelEdgeInsets.bottom;
            textLabelFrame.size.width = fmin(CGRectGetWidth(textLabelFrame), CGRectGetWidth(self.contentView.bounds) - CGRectGetMinX(textLabelFrame));
        }
        if (hasCustomDetailLabelEdgeInsets) {
            **detailTextLabelFrame.origin.x += self.detailTextLabelEdgeInsets.left - self._detailTextLabelEdgeInsets_.right;**
            detailTextLabelFrame.origin.y += self.detailTextLabelEdgeInsets.top - self.detailTextLabelEdgeInsets.bottom;
            detailTextLabelFrame.size.width = fmin(CGRectGetWidth(detailTextLabelFrame), CGRectGetWidth(self.contentView.bounds) - CGRectGetMinX(detailTextLabelFrame));
        }
加粗代码中的斜体bug，
个人认为detailTextLabelFrame.origin.x += self.detailTextLabelEdgeInsets.left - self.detailTextLabelEdgeInsets.right;
应该是detailTextLabelFrame.origin.x += self.detailTextLabelEdgeInsets.left - self.imageEdgeInsets.right;
不然会导致同时设置了 cell.detailTextLabelEdgeInsets = UIEdgeInsetsMake(0, 30, 0, 95); 的左右边距后detailTextLabel超出视图。
但是 接着又发现设置了右边距没有效果，detailTextLabel宽度是没有减去edge.right,不知是故意忽略右边距还是什么

**Comment by MoLice** [comment]
这里错误的是第一行加粗，应该是手误，因为这里包在 if (hasCustomTextLabelEdgeInsets) 内，所以用到的变量都是 self.textLabelEdgeInsets 相关的，不应该用到 imageEdgeInsets。

至于你提的同时设置 left/right，按目前的实现逻辑来看，不太建议这种做法，实际上 left/right 是互斥的，建议只设置一个。
而设置 inset 后宽度并没有减掉 inset，这也可以认为是 inset 系列属性的缺陷。

QMUITableViewCell 的 布局有点混乱，也不支持 self-sizing，后续可能会重构，这些问题留待重构时一并解决，4.2.1 新版本将仅会把第一行加粗的 imageEdgeInsets 换成 textLabelEdgeInsets。

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
