### ISSUE TITLE
QMUIDialogSelectionViewController 无法设置 textLabel 居中

### ISSUE THREAD

**Issue by Istroot** [Tencent/QMUI_iOS#890]
**Bug 表现**
QMUIDialogSelectionViewController 无法设置 textLabel 居中，我在 cellForItemBlock 内重新布局 textLabel 后，每次点击 cell 都会 reloadData，导致设置 textLabel 布局失效。(可能是系统的问题，但我没时间去测...)
```
// 在 ⬇️ 方法内，每次都会 reloadData
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
....
....
[tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationFade];

```

「我目前解决方法是」
我现在是在 cellForItemBlock 内为 cell 添加个自定义的 label，隐藏了 textLabel。
**截图**
![IMG_0477](https://user-images.githubusercontent.com/28040561/71438342-59feb680-2730-11ea-9797-21d6438b90b7.PNG)

**如何重现**
```
        aDialogViewController cellForItemBlock = { (aDialogViewController, cell, itemIndex) -> Void in
            print(cell)
            cell.textLabel?.snp.remakeConstraints({ (make) in
                make.edges.equalToSuperview()
            })
}
```
**预期的表现**
cellForItemBlock 内对 textLabel 布局后，点击 cell 不影响 textLabel 布局。

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
每一个 item 都是一个 QMUITableViewCell，而 QMUITableViewCell 的 textLabel 宽度是包裹内容的，布局上居左，你需要文字居中就需要让 textLabel 宽度撑满列表，并且设置文字居中，而布局都是在 cell 的 layoutSubviews 里，要重写布局可以使用 `UIView(QMUI) qmui_layoutSubviewsBlock`，示例代码如下：

```Objective-C
dialogViewController.cellForItemBlock = ^(QMUIDialogSelectionViewController *aDialogViewController, QMUITableViewCell *cell, NSUInteger itemIndex) {
    cell.textLabel.textAlignment = NSTextAlignmentCenter;
    cell.qmui_layoutSubviewsBlock = ^(QMUITableViewCell * _Nonnull aCell) {
        aCell.textLabel.qmui_extendToRight = aCell.contentView.qmui_width - aCell.textLabel.qmui_left;
    };
};
```

**Comment by Istroot** [comment]
谢谢你们的回复！你们回复的速度简直光速哇
