### ISSUE TITLE
同一个导航栏如何在不同的页面设置不同的按钮颜色

### ISSUE THREAD

**Issue by peterios2016** [Tencent/QMUI_iOS#891]
**现存问题或期望目标**
我知道可以在配置表里修改QMUICMI.navBarTintColor，但是目前有个需求，一级界面导航栏的按钮要蓝色的，但是二级或更多层的界面需要换成黑色,请问如何处理

**Comment by MoLice** [comment]
<img src="https://user-images.githubusercontent.com/1190261/71478728-0d98a100-282c-11ea-9766-8beadccef296.png" width="440" />

<img src="https://user-images.githubusercontent.com/1190261/71478742-20ab7100-282c-11ea-83ae-01c9b59031c3.png" width="440" />
