### ISSUE TITLE
导航栏侧手势滑返回中导航栏颜色

### ISSUE THREAD

**Issue by wq469775163** [Tencent/QMUI_iOS#894]
怎么修改 导航栏侧手势滑返回中导航栏颜色

**Comment by MoLice** [comment]
不明白你的意思是什么，那就在侧滑返回时去修改即可？

**Comment by wq469775163** [comment]
![IMG_0808](https://user-images.githubusercontent.com/13330455/71614310-dfc5aa80-2be5-11ea-962a-a390b3f8da69.PNG)
正常界面展示如上。
当我手势滑返回中过程中，界面变成如下：
![IMG_0809](https://user-images.githubusercontent.com/13330455/71614363-274c3680-2be6-11ea-9d24-c5922f3bccdc.jpg)
麻烦问下，在贵司框架下需怎么修改？或有没有解决思路。非常感谢

**Comment by MoLice** [comment]
搜索配置表里的“AutomaticCustomNavigationBarTransitionStyle”，把它打开即可。

**Comment by wq469775163** [comment]
好的。感谢
