### ISSUE TITLE
[UITabBar appearance].translucent设置失效

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#896]
链接: https://pan.baidu.com/s/1WkRfyebunmE9iejp9P-qEA 提取码: ijjh

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/71655765-77a4cf00-2d73-11ea-8101-cac211e04fd7.png)

系统的属性声明里本来就没有带 `UI_APPEARANCE_SELECTOR` 标志，不应该在 appearance 里使用，就算生效也是不恰当的使用方式。
