### ISSUE TITLE
QMUIPieProgressView 在以动画的形式修改 progress 过程中 borderInset 失效

### ISSUE THREAD

**Issue by liuzhaozhen** [Tencent/QMUI_iOS#900]
**Bug 表现**
pieProgres预设边距后,转动过程中间距消失,等到停止后才重新显示.
**截图**

**如何重现**
1. Demo中把QDPieProgressViewController的代码修改为
- (void)handleSliderTouchUpInside:(UISlider *)slider {
    [self.progressView2 setProgress:slider.value animated:YES];
}

2. 活动进度条时progressView2转动时没有了边距,停下来的时候重新显示边距(默认有边距).

**预期的表现**
转动时应该有边距

**其他信息**
所有设备

**Comment by MoLice** [comment]
”边距“是什么？相关的代码呢？或者截图示例一下边距的变化

**Comment by liuzhaozhen** [comment]
步骤:
1 https://liuzztest-1252954877.cos.ap-beijing.myqcloud.com/test/IMG_20200107_154608.jpg
2 https://liuzztest-1252954877.cos.ap-beijing.myqcloud.com/test/IMG_20200107_154556.jpg
3 http://liuzztest-1252954877.cos.ap-beijing.myqcloud.com/test/IMG_20200107_154517.jpg

**Comment by liuzhaozhen** [comment]
转动前  转动中  转动后

**Comment by MoLice** [comment]
遇到这种问题请用精准的表达方式，应该说“borderInset“而不要用”边距“这种模棱两可的词汇，提高沟通效率。

**Comment by MoLice** [comment]
新版本会修复该问题，在此之前可以修改本地 QMUI 的代码，在 `@implementation QMUIPieProgressLayer` 里加上”@dynamic borderInset;“

**Comment by liuzhaozhen** [comment]
收到,后续表达用属性名.

**Comment by MoLice** [comment]
已发布 [4.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.0) 修复该问题。
