### ISSUE TITLE
建议增加主题的颜色定义

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#904]
建议：
// 用于文本
textUnevenColor			// 深浅色
textLightenColor		        // 浅色
textColor				// 普通色
textDarkenColor			// 深色
textFurvousColor		        // 暗黑色
// 用于分割线
separatorUnevenColor
separatorLightenColor
separatorColor
separatorDarkenColor
separatorFurvousColor

**Comment by codingiran** [comment]
这个参考 Demo 里的 QDThemeManager 和 自定义 的QMUIConfigurationTemplate、QMUIConfigurationTemplateDark...， 配上自定义的颜色就行了

**Comment by MoLice** [comment]
这业务处理就行了，越多通用的定义越不通用，业务的需求千奇百怪。
