### ISSUE TITLE
QMUICommonTableViewController 在某些条件下 viewDidLoad 被提前唤起的问题

### ISSUE THREAD

**Issue by codingiran** [Tencent/QMUI_iOS#906]
**Bug 表现**

偶然发现，一个`vc` 的`viewDidLoad`中获取的 `self.navigationController == nil`，初步排查可以确认，此`vc`应该有正确的被加到导航栏栈里，且在 `viewWillAppear`内获取的 `self.navigationController != nil`.
后将怀疑点转到此`vc` 所继承的`QMUICommonTableViewController`，经过排查，可能为如下的原因：

```objc
@implementation ViewControllerB //  instance of QMUICommonTableViewController

- (instancetype)initWithStyle:(UITableViewStyle)style
{
    if (self = [super initWithStyle:style]) {

        self.textView = [[QMUITextView alloc] init];
        
        // 下面两行是触发问题的关键：
        self.textView.delegate = self;
        self.textView.contentInset = UIEdgeInsetsMake(0, 3, 0, 0);

       // 注意: 此时并没有将 self.textView add 到 self.view
    }
    return self;
}

/*
问题可能出在 给 textView 设置 contentInset 时，会触发 textView.delegate 的 'scrollViewDidChangeAdjustedContentInset:'方法
在 QMUICommonTableViewController 的'scrollViewDidChangeAdjustedContentInset'方法内，访问了 self.tableView
而 tableView 的 getter 方法内又 '[self loadViewIfNeeded]'，因此导致 viewDidLoad 被『提前』唤起
*/

- (void)viewDidLoad
{
    [super viewDidLoad];
    self.view.backgroundColor = UIColor.whiteColor;
    
    if (!self.navigationController) {
        // 在 viewDidLoad 异常的无法获取 self.navigationController
        // 说明 viewDidLoad 被『提前创建了』
        NSLog(@"=====");
    }
}

@end
```

**如何重现**

[附件 Demo 直接复现](https://github.com/Tencent/QMUI_iOS/files/4075448/dddddd.zip)

**预期的表现**

正常情况下，`viewDidLoad`方法内应该可以获取到 `self.navigationController`，除非`viewDidLoad`被『提前』唤起

**可能的原因**

问题可能出在 给 `textView` 设置 `contentInset` 时，会触发 `textView.delegate` 的 `scrollViewDidChangeAdjustedContentInset:`方法
在 `QMUICommonTableViewController` 的`scrollViewDidChangeAdjustedContentInset`方法内，访问了 `self.tableView`
而 `tableView` 的 `getter` 方法又调用了`[self loadViewIfNeeded]`，因此导致 `viewDidLoad` 被『提前』唤起

**其他信息**
 - 设备: All
 - iOS 版本: [iOS 11+]
 - Xcode 版本: [Xcode 11.3]
 - QMUI 版本: [4.0.4]

**Comment by MoLice** [comment]
下个版本会修复该问题，在此之前请修改本地的 QMUI 代码：

```Objective-C
- (void)scrollViewDidChangeAdjustedContentInset:(UIScrollView *)scrollView {
    if (self.viewLoaded && scrollView != self.tableView) {
        return;
    }
    [self handleTableViewContentInsetChangeEvent];
}
```

**Comment by MoLice** [comment]
已发布 [4.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.0) 修复该问题。
