### ISSUE TITLE
QMUI有使UIImageView支持gif动图的功能吗

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#908]
我通过[UIImage qmui_animatedImageNamed:@"page_loading" scale:2]方法拿到gif，直接赋值给UIImageView无效，必须将其qmui_smoothAnimation设置为NO才有效，但是qmui_smoothAnimation的描述是：系统原生的方式在 UIImageView 被放在 UIScrollView 内时会卡顿，默认为YES

**Comment by MoLice** [comment]
Demo 可以而你不可以，或者按文档来操作却出问题，说明要么是图片有什么特殊的，要么是业务代码有什么特殊的，不管是业务的问题还是 QMUI 的 bug，都需要你提供更详细的信息才能进一步调试，不然以目前的 issue 描述是无法得到妥善解决的。这是一个通用的提 issue 的思路。

建议提供可复现的 Demo。

**Comment by tospery** [comment]
谢谢，是图片问题。
