### ISSUE TITLE
gif的qmui_smoothAnimation问题

### ISSUE THREAD

**Issue by tospery** [Tencent/QMUI_iOS#909]
示例：
链接: https://pan.baidu.com/s/1YGnvK5HhKGmvdbA3maZPlg 提取码: gbxu

**Comment by MoLice** [comment]
Demo 里使用了“DZNEmptyDataSet”这个项目，该项目使用 constraints 进行布局，由于对 constraints 不熟悉，目前仅知道开启了 `qmui_smoothAnimation` 后图片无法显示的问题在于 `UIImageView` 的 `size` 为 0，但为什么为 0，为什么关闭了 `qmui_smoothAnimation` 就没问题，暂时不清楚，后续再排查，在此之前可以先修改 `UIScrollView+EmptyDataSet.m` 源码，增加一句 `sizeToFit` 主动刷新 imageView 的 size，注意修改源码后需要 Clean Project 才能生效。

```objc
if ([image respondsToSelector:@selector(imageWithRenderingMode:)]) {
    view.imageView.image = [image imageWithRenderingMode:renderingMode];
    view.imageView.tintColor = imageTintColor;
    [view.imageView sizeToFit]; // 增加这一句
}
```
