### ISSUE TITLE
QMUIDialogSelectionViewController在iOS13.3下，不能正常弹出

### ISSUE THREAD

**Issue by fenghun777** [Tencent/QMUI_iOS#911]
**Bug 表现**
在模拟器iOS13.3上不显示弹框，iOS11.3可以正常显示

**截图**
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/21209738/74022179-f24ab500-49d7-11ea-8f4a-0d1f00baabd3.png">

**如何重现**
 使用cocopod集成qmuikit之后，直接在控制器使用这段代码
https://github.com/fenghun777/ZyQMUIKit.git 这是我集成的一个demo

**预期的表现**
正常情况下，应该都能显示弹框

**其他信息**
 - 模拟器、iPhone
 - iOS 版本: [iOS 13.3]
 - Xcode 版本: [Xcode 11.3.1]
 - QMUI 版本: [4.0.4]

**Comment by MoLice** [comment]
请提供一个可复现的 Demo 以供排查

**Comment by fenghun777** [comment]
https://github.com/fenghun777/ZyQMUIKit.git  这是我集成的一个demo
![image](https://user-images.githubusercontent.com/21209738/74581432-4b26d880-4fea-11ea-9dfd-67a3bcb13658.png)

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/74823395-966e1d80-5341-11ea-9d62-351dd735d3b3.png)

你的 QMUI 版本是 2.9.3？这个版本太老，早就已经不维护了，也不保证在 iOS 13 下的表现。
