### ISSUE TITLE
StatusbarStyleLightInitially 注释有误

### ISSUE THREAD

**Issue by fabcz** [Tencent/QMUI_iOS#914]
#define StatusbarStyleLightInitially                    [QMUICMI statusbarStyleLightInitially]      // 默认的状态栏内容是否使用白色，默认为NO，也即黑色

在 iOS 13 以前  UIStatusBarStyleDefault 状态栏内容的颜色固定是黑色的，而在 iOS 13 UIStatusBarStyleDefault 会根据 user interface style 来决定状态栏的颜色

**Comment by MoLice** [comment]
已发布 [4.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.0) 修复该问题。
