### ISSUE TITLE
QMUITips 显示时长问题

### ISSUE THREAD

**Issue by Libogold** [Tencent/QMUI_iOS#915]
在一个页面，有如下代码
[QMUITips showWithText:@"删除成功"];
[self.navigationController popViewControllerAnimated:YES];
这样的话 QMUITips 几乎立刻消失并返回到前一个页面，导致用户无法看清提示。
现在我希望 QMUITips 正常显示1.5秒，同时页面也返回。
请问如何使用。

**Comment by MoLice** [comment]
使用你的代码在 QMUI Demo 中测试并无异常：
![image](https://user-images.githubusercontent.com/1190261/75166227-864da800-575e-11ea-817b-9597bde5cd4c.png)

以下是录屏：
[QMUITips Demo.mov.zip](https://github.com/Tencent/QMUI_iOS/files/4245326/QMUITips.Demo.mov.zip)

如有疑问请补充进一步的信息或者提供可复现的 Demo。
