### ISSUE TITLE
以 Dark 主题启动后切换为 Default，QMUITextField 的文字颜色错误

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#916]
**Bug 表现**
在主题页面手动切换主题后（非系统的切换主题），QMUITextField，QMUITextView的textColor没有变化，导致在Light主题中显示白色，会看不清楚，并且状态栏颜色也没有随之变化

**截图**
<img width="412" alt="图片" src="https://user-images.githubusercontent.com/22904757/75203396-ee28e080-57a8-11ea-83ad-00c4f13c47b5.png">

**如何重现**
1、打开QMUIDemo工程，点击到主题切换页面
2、随便选一个明亮的主题即可重现

**预期的表现**
需要一个全局设置QMUITextField，QMUITextView textColor属性的配置。
状态栏已在BaseVC中如下设置：
<img width="414" alt="图片" src="https://user-images.githubusercontent.com/22904757/75203896-60e68b80-57aa-11ea-9b3b-aaddb9856090.png">

**其他信息**
 - 设备: 模拟器
 - iOS 版本: [iOS 13.3]
 - Xcode 版本: [Xcode 11.3]
 - QMUI 版本: [4.0.4]

**Comment by MoLice** [comment]
<img src="https://user-images.githubusercontent.com/1190261/75254335-308b0580-581b-11ea-9318-84fe49b2966c.png" width="400" />

<img src="https://user-images.githubusercontent.com/1190261/75254299-21a45300-581b-11ea-875b-d2748f616e3f.png" width="400" />

QMUI Demo 中并没有出现你说的情况，请提供更详细的信息或者一个可复现的  Demo。

**Comment by jiasongs** [comment]
好的，明天上班后提供下DEMO

**Comment by jiasongs** [comment]
[_QMUIDemo_iOS-master 3.zip](https://github.com/Tencent/QMUI_iOS/files/4254862/_QMUIDemo_iOS-master.3.zip)
前置条件：
1、设置自动响应iOS 13系统样式
2、保证系统是Dark模式下进入Demo
操作顺序：
1、打开App进入《QMUITheme》设置页面
2、选择《Default》Theme
3、打开《QMUITextField》页面输入文字即可复现

**Comment by MoLice** [comment]
这个问题同样存在于官方的 QMUI Demo 中，issue 一开始没有说明准确的操作路径，导致测试时没发现问题。后续会修复，谢谢指出！

**Comment by jiasongs** [comment]
收到，建议可以在配置模板中配置QMUITextField和QMUITextView的textColor

**Comment by MoLice** [comment]
> 收到，建议可以在配置模板中配置QMUITextField和QMUITextView的textColor

已在配置表增加 `TextFieldTextColor` 配置项，请关注后续版本更新。
