### ISSUE TITLE
建议QMUICommonTableViewController可自定义TableView的类(继承自QMUITableView)

### ISSUE THREAD

**Issue by DevWhan** [Tencent/QMUI_iOS#917]
QMUICommonTableViewController作为项目中TableViewController基类通过其暴露api的可以满足需求
但是无法自定义TableView的类,  这个 个人觉得有点限制, 项目里自定义一个QMUITableView子类去实现一些符合项目中的东西我觉得是很正常并且常见的
既然基类QMUICommonTableViewController是定义为通用的继承类, 那么其tableView我建议也是可以自定义扩展的
但现在实现方案只能是复写initTableView 并不调用super来实现, 这样无法保证super中的逻辑会同步
所以建议将initTableView中实例化QMUITableView独立出来并且暴露给子类可以复写 返回QMUITableView子类

**Comment by MoLice** [comment]
[4.2.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.0) 开始支持直接在 viewDidLoad 里用 self.tableView = xxx（不要求一定是 QMUITableView 的子类）。
