### ISSUE TITLE
基于QMUIModalPresentationViewController实现的各组件关闭时的警告和连续操作崩溃闪退问题

### ISSUE THREAD

**Issue by qcasxy** [Tencent/QMUI_iOS#918]
**Bug 表现**
在QMUIDemo中运行QMUIDialogViewController、QMUIAlertController、QMUIMoreOperationController和QMUIModalPresentationViewController组件，能够正常打开无任何异常，但是在关闭组件时Xcode控制台会打印如下警告：
2020-03-06 03:09:45.535221+0800 qmuidemo[8346:3995507] Unbalanced calls to begin/end appearance transitions for <QMUIModalPresentationViewController: 0x124931e00>
superclass:				UIViewController
title:					(null)
view:					<UIView: 0x123d3f5b0; frame = (0 0; 414 736); autoresize = W+H; layer = <CALayer: 0x2826f6ae0>>.

并且在多次重复打开关闭这些组件后程序必然会崩溃闪退。
连续较快速重复一般5次以内必定崩溃，连续正常速度重复一般10次左右崩溃，重复速度越快越容易崩溃。
关于这个问题网上普遍说法是“一个动画没有执行结束，下一个动画就开始了。”但是关闭动画后执行以上操作问题依旧存在，已经影响正常使用希望可以今早得到解决。

#758 

**截图**
![image](https://user-images.githubusercontent.com/14816550/76019529-d3026180-5f5c-11ea-87e9-ee69605c7b60.png)
![image](https://user-images.githubusercontent.com/14816550/76022670-8883e380-5f62-11ea-97b7-a0aca42cc806.png)
![image](https://user-images.githubusercontent.com/14816550/76020960-5e7cf200-5f5f-11ea-8066-fec59e025b27.png)
![image](https://user-images.githubusercontent.com/14816550/76019552-dac20600-5f5c-11ea-9478-220944796dd7.png)

**如何重现**
1、在QMUIDemo中打开任意基于QMUIModalPresentationViewController实现的组件；
2、打开后关闭组件，在每次关闭组件时控制台打印警告信息；
3、连续多次重复步骤2，程序崩溃闪退。

**预期的表现**
1、关闭窗口控制菜不出现警告。
2、连续多次重复操作不会崩溃。

**其他信息**
 - 设备: iPhone 6sp
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
试了好像没出现你说的情况？录屏如下：
[快速打开关闭.mov.zip](https://github.com/Tencent/QMUI_iOS/files/4297410/mov.zip)

**Comment by qcasxy** [comment]
> 试了好像没出现你说的情况？录屏如下：
> [快速打开关闭.mov.zip](https://github.com/Tencent/QMUI_iOS/files/4297410/mov.zip)

不好意思，可能是因为我这边系统是iOS 13.4 Developer Beta版，今天借了个正式版系统的手机看了确实不会崩溃，但警告还是存在

**Comment by MoLice** [comment]
出现的 warning 参考你引用的 #758，后续有进展会在那 issue 里更新，此 issue 关闭。
