### ISSUE TITLE
Controller多次调用viewWillDisappear和viewWillAppear

### ISSUE THREAD

**Issue by CoderMaurice** [Tencent/QMUI_iOS#921]
**Bug 表现**
我在collectionView中做了一个可以选中的cell(就是选中加一层蒙版)
在反复选择的过程中 controller会反复出现viewWillDisappear 和 viewWillAppear
我已经排查了代码中的圆角和边框
同样的cell内容，tableViewCell没有关系，collectionViewCell就会有这个问题
不知道这个出现的原因是什么
**截图**

![image](https://user-images.githubusercontent.com/22311615/76274166-d0846c80-62ba-11ea-9ed3-7319fcb6e643.png)

**其他信息**
 - 设备: iPhone6P
 - iOS 版本: iOS 12.3
 - Xcode 版本: Xcode 11.3.1
 - QMUI 版本: 4.0.4

**Comment by MoLice** [comment]
这个 issue 提供的信息太欠缺了，例如你的 `EBFileManagerController` 和 collectionView、collectionViewCell 是什么关系？以目前的信息是无法理解到问题是什么的。

**Comment by CoderMaurice** [comment]
谢谢回复
写了个demo测试了下发现跟FDFullscreenPopGesture有关
禁用了FDFullscreenPopGesture暂时没有问题了
