### ISSUE TITLE
QMUINavigationController有bug

### ISSUE THREAD

**Issue by WFNeIn** [Tencent/QMUI_iOS#925]
if (self.isViewControllerTransiting || !viewController) {
        QMUILogWarn(NSStringFromClass(self.class), @"%@, 上一次界面切换的动画尚未结束就试图进行新的 push 操作，为了避免产生 bug，拦截了这次 push。\n%s, isViewControllerTransiting = %@, viewController = %@, self.viewControllers = %@", NSStringFromClass(self.class),  __func__, StringFromBOOL(self.isViewControllerTransiting), viewController, self.viewControllers);
        return;
    }
    
    // 增加一个 presentedViewController 作为判断条件是因为这个 issue：https://github.com/Tencent/QMUI_iOS/issues/261
    if (!self.presentedViewController && animated) {
        self.isViewControllerTransiting = YES;
    }

这一段代码会导致正常的push事件被拦截

**预期的表现**
push到下一个页面

**其他信息**
 - 设备: iPhoneSE, 
 - iOS 版本: 12.3.1
 - Xcode 版本: 10.2
 - QMUI 版本: 4.0.0

**Comment by MoLice** [comment]
这个保护措施是有意义的，注释里也有说明针对的场景以及具体的 issue，你如果不需要这种保护，可以把代码注释掉 Clean Project 试试。
