### ISSUE TITLE
希望支持左右方式显示

### ISSUE THREAD

**Issue by azureplus** [Tencent/QMUI_iOS#927]
typedef NS_ENUM(NSUInteger, QMUIPopupContainerViewLayoutDirection) {
    QMUIPopupContainerViewLayoutDirectionAbove,
    QMUIPopupContainerViewLayoutDirectionBelow,
    QMUIPopupContainerViewLayoutDirectionLeft,
    QMUIPopupContainerViewLayoutDirectionRight,
};

**Comment by MoLice** [comment]
该问题由 #691 跟进。
