### ISSUE TITLE
只要导库就会改变tabbar的字体大小，以及文字不居中

### ISSUE THREAD

**Issue by helloWotu** [Tencent/QMUI_iOS#929]
**Bug 表现**
本来设置的是12号字体，但是一旦导库哪怕什么都不做，就会变成10号字体，而且也不居中显示了
![image](https://user-images.githubusercontent.com/30145778/77153171-49ae6b80-6ad4-11ea-91a8-5c9fe55cf6f2.png)

**截图**
![image](https://user-images.githubusercontent.com/30145778/77153073-1370ec00-6ad4-11ea-9898-786e64a55a96.png)

**其他信息**
 - 设备: [iPhone XS Max]
 - iOS 版本: [iOS 13.3]
 - Xcode 版本: [Xcode 11.3.1]
 - QMUI 版本: [4.0.4]

**Comment by MoLice** [comment]
iOS 13 系统新增了 `UITabBarAppearance` 用于控制 `UITabBar` 的样式，原有的方式已废弃，而这个新 API 的特点是，如果你项目里从来没主动使用过它，则项目依然可以正常使用旧的 API 去设置外观（只是某些情况下有 bug 而已），但如果你的项目里用过一次 `UITabBarAppearance`，那么旧的 API 就会失效。为了保证最佳的体验，也为了与系统推荐方式对齐，QMUI 在 iOS 13 下使用新的 `UITabBarAppearance` 设置外观，这就是为什么当你引入 QMUI 后项目原有的旧 API 失效。

目前有两种方式解决你的问题：
1. 将你项目里原本设置 tabBar 外观的代码都做一下 iOS 系统版本区分，如下截图：
![image](https://user-images.githubusercontent.com/1190261/77162906-f8a87280-6ae7-11ea-8a88-b90720ce8342.png)

2. **[推荐]** 使用 QMUI 的配置表统一管理项目的外观，去掉项目里对 `UITabBar` 外观修改的代码，改为在配置表里设置值。配置表的使用方式参考 [官网-如何使用配置表](https://qmuiteam.com/ios/get-started/) 或者 [QMUI Demo](https://github.com/QMUI/QMUIDemo_iOS)。
