### ISSUE TITLE
与 DoraemonKit 冲突引发 dispatch_once 死锁

### ISSUE THREAD

**Issue by xiwuxisheng** [Tencent/QMUI_iOS#930]
**Bug 表现**
集成Doraemonkit框架后，QMUIModalPresentationViewController无法初始化，会进行闪退

**截图**
![WechatIMG2](https://user-images.githubusercontent.com/18434083/77311573-52ed4180-6d3b-11ea-88ac-ca064902924c.jpeg)

**如何重现**
1.pod集成
pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0beta3', :configurations => ['Debug']
    pod 'DoraemonKit/WithWeex', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0beta3', :configurations => ['Debug']
    pod 'DoraemonKit/WithLoad', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0beta3', :configurations => ['Debug']
2.QMUIModalPresentationViewController *presentVC = [[QMUIModalPresentationViewController alloc] init]; 执行就会直接闪退

**预期的表现**
正常情况是QMUIModalPresentationViewController初始化正常

**其他信息**
 - 设备: iPhone 8
 - iOS 版本: iOS 13.3.1
 - Xcode 版本: Xcode 11.3
 - QMUI 版本: 4.0.4

**Comment by MoLice** [comment]
该问题为 DoraemonKit 在特定场景下的 bug，已提交 [issue](https://github.com/didi/DoraemonKit/issues/416) 到该仓库，具体原因、解决进度请到 DoraemonKit 查看。

同时 QMUI 内部会更换相关代码的实现方式，以避免该问题的出现，预计本周发版本时带上，注意留意 issue 进展。

**Comment by MoLice** [comment]
已发布 [4.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.0) 修复该问题。
