### ISSUE TITLE
您好，请问我想在QMUIStaticTableView中的某个cell上右边添加一个图片，如何去自定义这个cell

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#931]
您好，请问我想在QMUIStaticTableView中的某个cell上右边添加一个图片，如何去自定义这个cell，自定义后如何去获取QMUIStaticTableViewCellData中的数据呢？

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/77401229-84bbe200-6de7-11ea-8bd0-5520e534a0be.png)

可以利用 `QMUIStaticTableViewCellData.cellForRowBlock` 属性去自定义某一个 cell，至于如何放一个图片在右边，有很多种方法，最简单的方法是直接用系统提供的 `accessoryView` 属性。
