### ISSUE TITLE
qmui_shouldShowDebugColor 请问这个API是否可以开启全局模式

### ISSUE THREAD

**Issue by pcccccc** [Tencent/QMUI_iOS#932]
尝试了一下在keyWindow上添加，但是并不能达到目标效果。

**Comment by MoLice** [comment]
这个功能用得比较少，后续也不考虑再为它增强功能了，因为这种需求已经有更好的工具代替，例如 [LookIn](https://lookin.work/)。当初在工具不是很完善的情况下才增加了这个能力方便查看界面的层级、布局关系，现在都用 LookIn 即可。
