### ISSUE TITLE
iOS13下，导航栏分割线隐藏后无法重新显示的问题

### ISSUE THREAD

**Issue by linzhesheng** [Tencent/QMUI_iOS#936]
**Bug 表现**
iOS13下， 实现 - (nullable UIImage *)navigationBarShadowImage 隐藏本控制器的导航栏分割线，之后push的所有控制器导航栏分割线都隐藏了，且无法通过实现 - (nullable UIImage *)navigationBarShadowImage 重新显示出来；其他系统正常。

**如何重现**
1. 在本控制器实现  - (nullable UIImage *)navigationBarShadowImage，返回 UIImage.new。
2.push一个新控制器，新控制器导航栏分割线隐藏了。

**其他信息**
 - 设备: iPhoneXR
 - iOS 版本: 13.3
 - Xcode 版本: 11.2.1
 - QMUI 版本: 4.0.4

**Comment by MoLice** [comment]
项目有使用配置表吗？有的话 `NavBarShadowImage` 的值设置为什么了？

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
