### ISSUE TITLE
凡是继承了使用QMUIAppearance的组件，qmui_applyAppearance并不能生效

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#937]
**Bug 表现**
凡是继承了使用QMUIAppearance的组件，qmui_applyAppearance并不能生效

**截图**
`appearance`设置如下图所示：
![图片](https://user-images.githubusercontent.com/22904757/77823567-08066c00-7137-11ea-8ed5-5f7fa5822644.png)
`[self qmui_applyAppearance]`后如下图所示：
![图片](https://user-images.githubusercontent.com/22904757/77823610-587dc980-7137-11ea-8dc0-405b74c6b1ed.png)
![图片](https://user-images.githubusercontent.com/22904757/77823613-629fc800-7137-11ea-9764-0d0ef96e2ab7.png)

**如何重现**
1. 继承任意使用QMUIAppearance的组件，例如继承QMUIModalPresentationViewController，名为QDUIModalViewController
2. 正常使用QDUIModalViewController
3. 可在`[self qmui_applyAppearance]`执行之后断点调试查看

**预期的表现**
使用QMUIAppearance组件的子类也可以正常设置全局样式

**其他信息**
 - 设备: iPhone
 - iOS 版本: iOS 13.3
 - Xcode 版本: Xcode 11.3
 - QMUI 版本: 4.1.0

**Comment by jiasongs** [comment]
临时写了个急救方案：
![图片](https://user-images.githubusercontent.com/22904757/77824105-f9ba4f00-713a-11ea-9f44-e7b5038972f1.png)
希望能够尽快修复此问题

**Comment by jiasongs** [comment]
[NSObject+RMFixQMUIAppearnace.zip](https://github.com/Tencent/QMUI_iOS/files/4397267/NSObject%2BRMFixQMUIAppearnace.zip)

**Comment by jiasongs** [comment]
以上实现虽然能解决Bug，但是会引申出两个问题：
1、会遍历当前类的所有父类，造成无用的消耗
2、若子类也调用了`qmui_applyAppearance`，会重复执行多次样式配置。例如QDUIModalViewController执行一次`qmui_applyAppearance`，QDUIModalViewController的父类也执行了一次`qmui_applyAppearance`，那么会重复进行多次样式配置。

**Comment by fanyuecheng** [comment]
QMUIImagePreviewViewController，打断点 + (void)initialize 根本没走，导致QMUIImagePreviewViewController.appearance.backgroundColor = nil，背景色是白色的，而不是UIColorBlack。
好像是因为用pod的原因？

**Comment by MoLice** [comment]
已发布 [4.1.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.1) 修复该问题。
