### ISSUE TITLE
qmui_grayImage 对 scale > 1 的图片处理后内容错误

### ISSUE THREAD

**Issue by Lee0820** [Tencent/QMUI_iOS#938]
[icon_tabbar_navigation_button@2x.png.zip](https://github.com/Tencent/QMUI_iOS/files/4398627/icon_tabbar_navigation_button%402x.png.zip)
将这张图使用 `qmui_grayImage` 处理后图片内容被以 scale = 1 的方式渲染出来了。

<img src="https://user-images.githubusercontent.com/11679563/77895351-37d58100-72a9-11ea-821e-70941326cd18.png" width="380" />

另外 GIF 图要如何使用 `qmui_grayImage` 处理？

**Comment by Lee0820** [comment]
发现有的图片没问题，有的图文处理完变成四分之一左上角的图了，这是什么情况

**Comment by MoLice** [comment]
这个 issue 看不懂在说什么问题，请重新整理表达再打开。

**Comment by Lee0820** [comment]
您可以把我上传的这张图放到demo里测试下qmui_grayImage这个方法，
![Uploading 27ACBBC2DC257E66FB00B9E5C68353F2.png…]()
[icon_app_version_header@2x.png.zip](https://github.com/Tencent/QMUI_iOS/files/4401750/icon_app_version_header%402x.png.zip)

**Comment by MoLice** [comment]
这是 `qmui_grayImage` 的 bug，下个版本会修复。

GIF 图不适用于 `UIImage (QMUI)` 里的方法，需要自行拆分帧图片处理完再封装成 GIF。

**Comment by Lee0820** [comment]
目前有什么现成的解决方案吗，因为现在急用这个方法 ～ ～

**Comment by Lee0820** [comment]
@MoLice

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/77897688-96502e80-72ac-11ea-961b-a5bf51f4b8d6.png)

可以先修改源码，把方法末尾的这里改为 `[grayImage drawInRect:CGRectMakeWithSize(grayImage.size)];`。

**Comment by Lee0820** [comment]
好的谢谢

**Comment by MoLice** [comment]
已发布 [4.1.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.1) 修复该问题。
