### ISSUE TITLE
"configureNavBarShadowImage"是否存在逻辑上的Bug

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#939]
**Bug 表现**
只设置navBarShadowImage的情况下，navBarShadowImageColor为nil，configureNavBarShadowImage没有配置成功

**截图**
<img width="1103" alt="图片" src="https://user-images.githubusercontent.com/22904757/77869130-01c7db00-7270-11ea-8701-e1c6c232d00d.png">
由截图所知，configureNavBarShadowImage里如果没有设置navBarShadowImageColor时，_navBarShadowImage将会变为nil

**如何重现**
1. 只设置navBarShadowImage，navBarShadowImageColor为nil

**预期的表现**
navBarShadowImage，navBarShadowImageColor均可生效

**其他信息**
 - 设备: iPhone
 - iOS 版本: iOS 13.2
 - Xcode 版本: Xcode 11.2
 - QMUI 版本: 4.1.0

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/77886978-5e40ef80-729c-11ea-9d3a-c97df71844f8.png)

配置表的说明里有解释了这两个属性里起主导作用的是 color，当 color 为 nil 时 image 也会被置为 nil，目的就是为了截图里第二个红框那句。

不过这里确实有点不合理，按目前的 API 设计，如果我想要显示 `NavBarShadowImage` 的原图，不想它被 `NavBarShadowImageColor` 影响，那么我应该这么做：
```objc
QMUICMI.navBarShadowImage = [image imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal]; // 指定 renderingMode，避免被 color 影响
QMUICMI.navBarShadowImageColor = UIColorClear; // 这里要保证非 nil
```
这样有两个问题：
1. 配置表里并没有说明应该指定 `NavBarShadowImage` 的 renderingMode，使用者需要自己看源码才知道。
2. 当我这样写的时候，其实 `NavBarShadowImageColor` 是没有任何存在的意义的，因为需求上我已经不需要关心 color 了，但我依然需要配置它，因为逻辑上它需要非 nil 才能让 image 生效，这不符合预期。

综上，issue 里提的代码没有逻辑问题，但这个设计是有问题。下个版本会调整为如下策略：
1. 如果 image 和 color 均为 nil，则使用系统默认的。
1. 如果 image 不为 nil，color 为 nil，则使用 image 原图。
1. 如果 image 不为 nil，color 不为 nil：
    1. 如果 image.renderingMode 为 `UIImageRenderingModeAlwaysOriginal`，则使用原图，忽略 color 的存在。
    1. 如果 image.renderingMode 不为 `UIImageRenderingModeAlwaysOriginal`，则 image 将会被设置为 color 指定的颜色。
1. 如果 image 为 nil，color 不为 nil，则会创建一张 1px 高的图片，将其设置为 color 指定的颜色，然后设置给 navigationBar。

在新策略的情况下，列举几种常见场景的代码设置方式：
1. 如果想修改系统默认的 shadowImage 颜色，则：
    ```objc
    QMUICMI.navBarShadowImage = nil;
    QMUICMI.navBarShadowImageColor = xxx;
    ```
1. 如果想用自己的图片（颜色、内容、大小可能都和系统默认的不同）作为 shadowImage，则：
    ```objc
    QMUICMI.navBarShadowImage = xxx;
    QMUICMI.navBarShadowImageColor = nil;
    ```
1. 如果想去掉 shadowImage，则：
    ```objc
    QMUICMI.navBarShadowImage = nil;
    QMUICMI.navBarShadowImageColor = UIColorClear;
    ```
    或：
    ```objc
    QMUICMI.navBarShadowImage =UIImage.new;
    QMUICMI.navBarShadowImageColor = nil;
    ```

你可以看看对新策略是否有新的建议。

**Comment by jiasongs** [comment]
> ![image](https://user-images.githubusercontent.com/1190261/77886978-5e40ef80-729c-11ea-9d3a-c97df71844f8.png)
> 
> 配置表的说明里有解释了这两个属性里起主导作用的是 color，当 color 为 nil 时 image 也会被置为 nil，目的就是为了截图里第二个红框那句。
> 
> 不过这里确实有点不合理，按目前的 API 设计，如果我想要显示 `NavBarShadowImage` 的原图，不想它被 `NavBarShadowImageColor` 影响，那么我应该这么做：
> 
> ```objc
> QMUICMI.navBarShadowImage = [image imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal]; // 指定 renderingMode，避免被 color 影响
> QMUICMI.navBarShadowImageColor = UIColorClear; // 这里要保证非 nil
> ```
> 
> 这样有两个问题：
> 
>     1. 配置表里并没有说明应该指定 `NavBarShadowImage` 的 renderingMode，使用者需要自己看源码才知道。
> 
>     2. 当我这样写的时候，其实 `NavBarShadowImageColor` 是没有任何存在的意义的，因为需求上我已经不需要关心 color 了，但我依然需要配置它，因为逻辑上它需要非 nil 才能让 image 生效，这不符合预期。
> 
> 
> 综上，issue 里提的代码没有逻辑问题，但这个设计是有问题。下个版本会调整为如下策略：
> 
>     1. 如果 image 和 color 均为 nil，则使用系统默认的。
> 
>     2. 如果 image 不为 nil，color 为 nil，则使用 image 原图。
> 
>     3. 如果 image 不为 nil，color 不为 nil：
>        
>        1. 如果 image.renderingMode 为 `UIImageRenderingModeAlwaysOriginal`，则使用原图，忽略 color 的存在。
>        2. 如果 image.renderingMode 不为 `UIImageRenderingModeAlwaysOriginal`，则 image 将会被设置为 color 指定的颜色。
> 
>     4. 如果 image 为 nil，color 不为 nil，则会创建一张 1px 高的图片，将其设置为 color 指定的颜色，然后设置给 navigationBar。
> 
> 
> 在新策略的情况下，列举几种常见场景的代码设置方式：
> 
>     1. 如果想修改系统默认的 shadowImage 颜色，则：
>        ```objc
>        QMUICMI.navBarShadowImage = nil;
>        QMUICMI.navBarShadowImageColor = xxx;
>        ```
> 
>     2. 如果想用自己的图片（颜色、内容、大小可能都和系统默认的不同）作为 shadowImage，则：
>        ```objc
>        QMUICMI.navBarShadowImage = xxx;
>        QMUICMI.navBarShadowImageColor = nil;
>        ```
> 
>     3. 如果想去掉 shadowImage，则：
>        ```objc
>        QMUICMI.navBarShadowImage = nil;
>        QMUICMI.navBarShadowImageColor = UIColorClear;
>        ```
>        
>        
>        或：
>        ```objc
>        QMUICMI.navBarShadowImage =UIImage.new;
>        QMUICMI.navBarShadowImageColor = nil;
>        ```
> 
> 
> 你可以看看对新策略是否有新的建议。

新策略已经考虑很全面了 👍

**Comment by jiasongs** [comment]
新策略已经考虑很全面了 👍

**Comment by MoLice** [comment]
已发布 [4.1.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.1) 优化该问题。

**Comment by RomanticEncounter** [comment]
版本： 4.1.1 
运行设备： 模拟器13.4

当配置表设置如下
```
配置：1
QMUICMI.navBarShadowImage = xxxx;
QMUICMI.navBarShadowImageColor = UIColorClear;
```

```
配置：2（此配置无问题）
QMUICMI.navBarShadowImage = xxxx;
QMUICMI.navBarShadowImageColor = nil;
```

使用配置1时
导航和UITableView之间的shadowimage会出现tableview的背景色，模态弹出新建Nav，页面也是同样带`searchControl`的会有此类问题，其他页面正常显示，这个问题不知道算不算的上Bug，设置`navBarShadowImageColor`为`nil`，则其他此类页面显示正常

searchBar未开始编辑
![未开始编辑](https://user-images.githubusercontent.com/16411177/78960758-99a3af80-7b21-11ea-950e-1522d2b0c079.png)
结束search编辑
![结束searchBar编辑](https://user-images.githubusercontent.com/16411177/78960793-b50eba80-7b21-11ea-898b-c210baa55c57.png)

tableview无其他特殊设置
`
_tableView.tableHeaderView = self.searchController.searchBar;
`

searchControl 设置如下
```objc
- (UISearchController *)searchController {
    if (!_searchController) {
        VPAddressBookSearchResultsViewController *resultsViewController = [[VPAddressBookSearchResultsViewController alloc]init];
        _searchController = [[UISearchController alloc] initWithSearchResultsController:resultsViewController];
        _searchController.searchResultsUpdater = resultsViewController;
        _searchController.searchBar.placeholder = @"搜索";
        [_searchController.searchBar setImage:UIImageMake(@"public_gray_search")
                             forSearchBarIcon:UISearchBarIconSearch state:UIControlStateNormal];
        _searchController.searchBar.backgroundImage = [UIImageMake(@"public_navigation_backgroud_bottom") resizableImageWithCapInsets:UIEdgeInsetsZero resizingMode:UIImageResizingModeStretch];
        _searchController.searchBar.barTintColor = UIColorLightGreen;
        _searchController.searchBar.tintColor = UIColorWhite;
        _searchController.searchBar.qmui_textField.backgroundColor = UIColorWhite;
        _searchController.searchBar.enablesReturnKeyAutomatically = YES;
        _searchController.hidesNavigationBarDuringPresentation = YES;
        if (@available(iOS 9.1, *)) {
            _searchController.obscuresBackgroundDuringPresentation = YES;
        }
        _searchController.delegate = self;
        _searchController.searchBar.qmui_usedAsTableHeaderView = YES;
    }
    return _searchController;
}
```

**Comment by MoLice** [comment]
@RomanticEncounter 请问 `navBarShadowImage` 用的图片是什么，可以发个 zip 包上来吗？或者如果是用代码生成的，请贴出它的代码。

**Comment by RomanticEncounter** [comment]
> @RomanticEncounter 请问 `navBarShadowImage` 用的图片是什么，可以发个 zip 包上来吗？或者如果是用代码生成的，请贴出它的代码。

配置表代码：
```objc
QMUICMI.navBarBackgroundImage = [UIImageMake(@"root_navigation_backgroud") resizableImageWithCapInsets:UIEdgeInsetsZero resizingMode:UIImageResizingModeStretch];                                        
    QMUICMI.navBarShadowImage = [UIImageMake(@"root_navigation_shadow") resizableImageWithCapInsets:UIEdgeInsetsZero resizingMode:UIImageResizingModeStretch];
QMUICMI.navBarShadowImageColor = UIColorClear;    
```

[navBar和searchBar文件.zip](https://github.com/Tencent/QMUI_iOS/files/4461119/navigation_and_searchBar.zip)

**Comment by MoLice** [comment]
@RomanticEncounter 经测试，这是另一个问题，系统的“bug”，具体新开 issue 讨论 #950。
