### ISSUE TITLE
qmui_grayImage把图片置灰的方法问题 #938

### ISSUE THREAD

**Issue by Lee0820** [Tencent/QMUI_iOS#940]
qmui_grayImage 这个方法，我用这个图片直接在demo里测试
![27ACBBC2DC257E66FB00B9E5C68353F2](https://user-images.githubusercontent.com/11679563/77895351-37d58100-72a9-11ea-821e-70941326cd18.png)
[icon_app_version_header@2x.png.zip](https://github.com/Tencent/QMUI_iOS/files/4401781/icon_app_version_header%402x.png.zip)

**Comment by MoLice** [comment]
#938
