### ISSUE TITLE
在有 sectionIndexTitles和searchBar 的页面searcherBar显示上不左右对其

### ISSUE THREAD

**Issue by Libogold** [Tencent/QMUI_iOS#941]
**Bug 表现**
由于右边有字母索引，导致searchbar 左右两边的间距不同。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
在demo中NSObject+QMUI  -> 搜nso -> 任意NSOederSet 

**预期的表现**
希望提供方法，能够左右间距显示上相同。
<img width="349" alt="屏幕快照 2020-03-31 11 23 58" src="https://user-images.githubusercontent.com/20291011/77984064-26d94e00-7343-11ea-8fe0-a21b3bd7e2e0.png">

**Comment by MoLice** [comment]
iOS 系统本身就是这样的。
