### ISSUE TITLE
UIView+QMUI 中的分类方法导致 UIImagePickerController  allowsEditing = YES 第一次拍照并选择图片报线程异常警告

### ISSUE THREAD

**Issue by xixisplit** [Tencent/QMUI_iOS#942]
**Bug 表现**
问题的具体描述
UIImagePickerController  allowsEditing = YES 第一次拍照 选择图片线程警告
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView isDescendantOfView:]
PID: 3211, TID: 559920, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   QMUILabelBugTest                    0x0000000100d9771c -[UIView(QMUI) hasSharedAncestorViewWithView:] + 132
5   QMUILabelBugTest                    0x0000000100d97be4 -[UIView(QMUI) alertConvertValueWithView:] + 104
6   QMUILabelBugTest                    0x0000000100d95c6c __20+[UIView(QMUI) load]_block_invoke_2.314 + 124
7   PhotoLibrary                        0x00000001a92886a4 <redacted> + 264
8   AssetsLibraryServices               0x00000001a39138bc <redacted> + 36
9   libdispatch.dylib                   0x0000000101453840 _dispatch_call_block_and_release + 24
10  libdispatch.dylib                   0x0000000101454de4 _dispatch_client_callout + 16
11  libdispatch.dylib                   0x0000000101457cac _dispatch_queue_override_invoke + 888
12  libdispatch.dylib                   0x00000001014661f8 _dispatch_root_queue_drain + 376
13  libdispatch.dylib                   0x0000000101466be4 _dispatch_worker_thread2 + 156
14  libsystem_pthread.dylib             0x0000000195bd2190 _pthread_wqthread + 472
15  libsystem_pthread.dylib             0x0000000195bd4d00 start_wqthread + 4
2020-03-31 15:00:31.397802+0800 QMUILabelBugTest[3211:559920] [reports] Main Thread Checker: UI API called on a background thread: -[UIView isDescendantOfView:]
PID: 3211, TID: 559920, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   QMUILabelBugTest                    0x0000000100d9771c -[UIView(QMUI) hasSharedAncestorViewWithView:] + 132
5   QMUILabelBugTest                    0x0000000100d97be4 -[UIView(QMUI) alertConvertValueWithView:] + 104
6   QMUILabelBugTest                    0x0000000100d95c6c __20+[UIView(QMUI) load]_block_invoke_2.314 + 124
7   PhotoLibrary                        0x00000001a92886a4 <redacted> + 264
8   AssetsLibraryServices               0x00000001a39138bc <redacted> + 36
9   libdispatch.dylib                   0x0000000101453840 _dispatch_call_block_and_release + 24
10  libdispatch.dylib                   0x0000000101454de4 _dispatch_client_callout + 16
11  libdispatch.dylib                   0x0000000101457cac _dispatch_queue_override_invoke + 888
12  libdispatch.dylib                   0x00000001014661f8 _dispatch_root_queue_drain + 376
13  libdispatch.dylib                   0x0000000101466be4 _dispatch_worker_thread2 + 156
14  libsystem_pthread.dylib             0x0000000195bd2190 _pthread_wqthread + 472
15  libsystem_pthread.dylib             0x0000000195bd4d00 start_wqthread + 4
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView superview]
PID: 3211, TID: 559920, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   QMUILabelBugTest                    0x0000000100d97744 -[UIView(QMUI) hasSharedAncestorViewWithView:] + 172
5   QMUILabelBugTest                    0x0000000100d97be4 -[UIView(QMUI) alertConvertValueWithView:] + 104
6   QMUILabelBugTest                    0x0000000100d95c6c __20+[UIView(QMUI) load]_block_invoke_2.314 + 124
7   PhotoLibrary                        0x00000001a92886a4 <redacted> + 264
8   AssetsLibraryServices               0x00000001a39138bc <redacted> + 36
9   libdispatch.dylib                   0x0000000101453840 _dispatch_call_block_and_release + 24
10  libdispatch.dylib                   0x0000000101454de4 _dispatch_client_callout + 16
11  libdispatch.dylib                   0x0000000101457cac _dispatch_queue_override_invoke + 888
12  libdispatch.dylib                   0x00000001014661f8 _dispatch_root_queue_drain + 376
13  libdispatch.dylib                   0x0000000101466be4 _dispatch_worker_thread2 + 156
14  libsystem_pthread.dylib             0x0000000195bd2190 _pthread_wqthread + 472
15  libsystem_pthread.dylib             0x0000000195bd4d00 start_wqthread + 4
2020-03-31 15:00:48.929185+0800 QMUILabelBugTest[3211:559920] [reports] Main Thread Checker: UI API called on a background thread: -[UIView superview]
PID: 3211, TID: 559920, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   QMUILabelBugTest                    0x0000000100d97744 -[UIView(QMUI) hasSharedAncestorViewWithView:] + 172
5   QMUILabelBugTest                    0x0000000100d97be4 -[UIView(QMUI) alertConvertValueWithView:] + 104
6   QMUILabelBugTest                    0x0000000100d95c6c __20+[UIView(QMUI) load]_block_invoke_2.314 + 124
7   PhotoLibrary                        0x00000001a92886a4 <redacted> + 264
8   AssetsLibraryServices               0x00000001a39138bc <redacted> + 36
9   libdispatch.dylib                   0x0000000101453840 _dispatch_call_block_and_release + 24
10  libdispatch.dylib                   0x0000000101454de4 _dispatch_client_callout + 16
11  libdispatch.dylib                   0x0000000101457cac _dispatch_queue_override_invoke + 888
12  libdispatch.dylib                   0x00000001014661f8 _dispatch_root_queue_drain + 376
13  libdispatch.dylib                   0x0000000101466be4 _dispatch_worker_thread2 + 156
14  libsystem_pthread.dylib             0x0000000195bd2190 _pthread_wqthread + 472
15  libsystem_pthread.dylib             0x0000000195bd4d00 start_wqthread + 4
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView convertRect:fromView:]
PID: 3211, TID: 559920, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   QMUILabelBugTest                    0x0000000100d95cb4 __20+[UIView(QMUI) load]_block_invoke_2.314 + 196
5   PhotoLibrary                        0x00000001a92886a4 <redacted> + 264
6   AssetsLibraryServices               0x00000001a39138bc <redacted> + 36
7   libdispatch.dylib                   0x0000000101453840 _dispatch_call_block_and_release + 24
8   libdispatch.dylib                   0x0000000101454de4 _dispatch_client_callout + 16
9   libdispatch.dylib                   0x0000000101457cac _dispatch_queue_override_invoke + 888
10  libdispatch.dylib                   0x00000001014661f8 _dispatch_root_queue_drain + 376
11  libdispatch.dylib                   0x0000000101466be4 _dispatch_worker_thread2 + 156
12  libsystem_pthread.dylib             0x0000000195bd2190 _pthread_wqthread + 472
13  libsystem_pthread.dylib             0x0000000195bd4d00 start_wqthread + 4
2020-03-31 15:00:49.040366+0800 QMUILabelBugTest[3211:559920] [reports] Main Thread Checker: UI API called on a background thread: -[UIView convertRect:fromView:]
PID: 3211, TID: 559920, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   QMUILabelBugTest                    0x0000000100d95cb4 __20+[UIView(QMUI) load]_block_invoke_2.314 + 196
5   PhotoLibrary                        0x00000001a92886a4 <redacted> + 264
6   AssetsLibraryServices               0x00000001a39138bc <redacted> + 36
7   libdispatch.dylib                   0x0000000101453840 _dispatch_call_block_and_release + 24
8   libdispatch.dylib                   0x0000000101454de4 _dispatch_client_callout + 16
9   libdispatch.dylib                   0x0000000101457cac _dispatch_queue_override_invoke + 888
10  libdispatch.dylib                   0x00000001014661f8 _dispatch_root_queue_drain + 376
11  libdispatch.dylib                   0x0000000101466be4 _dispatch_worker_thread2 + 156
12  libsystem_pthread.dylib             0x0000000195bd2190 _pthread_wqthread + 472
13  libsystem_pthread.dylib             0x0000000195bd4d00 start_wqthread + 4
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIImageView image]
PID: 3211, TID: 559920, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   QMUILabelBugTest                    0x0000000100d622e0 __25+[UIImageView(QMUI) load]_block_invoke_2.66 + 204
5   PhotoLibrary                        0x00000001a9278660 <redacted> + 28
6   PhotoLibrary                        0x00000001a927c9a4 <redacted> + 132
7   PhotoLibrary                        0x00000001a927d034 <redacted> + 184
8   PhotoLibrary                        0x00000001a92886bc <redacted> + 288
9   AssetsLibraryServices               0x00000001a39138bc <redacted> + 36
10  libdispatch.dylib                   0x0000000101453840 _dispatch_call_block_and_release + 24
11  libdispatch.dylib                   0x0000000101454de4 _dispatch_client_callout + 16
12  libdispatch.dylib                   0x0000000101457cac _dispatch_queue_override_invoke + 888
13  libdispatch.dylib                   0x00000001014661f8 _dispatch_root_queue_drain + 376
14  libdispatch.dylib                   0x0000000101466be4 _dispatch_worker_thread2 + 156
15  libsystem_pthread.dylib             0x0000000195bd2190 _pthread_wqthread + 472
16  libsystem_pthread.dylib             0x0000000195bd4d00 start_wqthread + 4
2020-03-31 15:00:49.223388+0800 QMUILabelBugTest[3211:559920] [reports] Main Thread Checker: UI API called on a background thread: -[UIImageView image]
PID: 3211, TID: 559920, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   QMUILabelBugTest                    0x0000000100d622e0 __25+[UIImageView(QMUI) load]_block_invoke_2.66 + 204
5   PhotoLibrary                        0x00000001a9278660 <redacted> + 28
6   PhotoLibrary                        0x00000001a927c9a4 <redacted> + 132
7   PhotoLibrary                        0x00000001a927d034 <redacted> + 184
8   PhotoLibrary                        0x00000001a92886bc <redacted> + 288
9   AssetsLibraryServices               0x00000001a39138bc <redacted> + 36
10  libdispatch.dylib                   0x0000000101453840 _dispatch_call_block_and_release + 24
11  libdispatch.dylib                   0x0000000101454de4 _dispatch_client_callout + 16
12  libdispatch.dylib                   0x0000000101457cac _dispatch_queue_override_invoke + 888
13  libdispatch.dylib                   0x00000001014661f8 _dispatch_root_queue_drain + 376
14  libdispatch.dylib                   0x0000000101466be4 _dispatch_worker_thread2 + 156
15  libsystem_pthread.dylib             0x0000000195bd2190 _pthread_wqthread + 472
16  libsystem_pthread.dylib             0x0000000195bd4d00 start_wqthread + 4

**如何重现**
1. ... 在新建空项目中导入 QMUIKit 框架
2. ... 在控制器中实现以下代码
@interface ViewController ()
@property (nonatomic, strong) UIImageView *imageView;
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = UIColor.whiteColor;
    UIImageView *image = [[UIImageView alloc] initWithFrame:self.view.bounds];
    self.imageView = image;
    [self.view addSubview:image];
    UIButton *btn = [[UIButton alloc] initWithFrame:(CGRectMake(100, 100, 100, 50))];
    [self.view addSubview:btn];
    [btn setTitle:@"相机" forState:(UIControlStateNormal)];
    [btn setTitleColor:UIColor.blueColor forState:(UIControlStateNormal)];
    [btn addTarget:self action:@selector(imagepicker) forControlEvents:(UIControlEventTouchUpInside)];
}
-(void)imagepicker{
    dispatch_async(dispatch_get_main_queue(), ^{
        UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init];
        imagePicker.delegate = self;
        imagePicker.allowsEditing = YES;
        if ([UIImagePickerController isSourceTypeAvailable:UIImagePickerControllerSourceTypeCamera]) {
            imagePicker.sourceType = UIImagePickerControllerSourceTypeCamera;
        }
        [self presentViewController:imagePicker animated:YES completion:nil];
        
    });
}

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info
{
    
    UIImage *image = info[UIImagePickerControllerEditedImage];
    UIImage *orgimage = info[UIImagePickerControllerOriginalImage];
        if (image == nil) {
            self.imageView.image = orgimage;
        }else{
            self.imageView.image = image;
        }
    [picker dismissViewControllerAnimated:YES completion:nil];
}

- (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker
{
    [picker dismissViewControllerAnimated:YES completion:nil];
}
@end

3.点击按钮打开相机并拍照.选择图片之后.线程会卡顿,并控制台警告

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iphone5S]
 - iOS 版本: [iOS 12]
 - Xcode 版本: [Xcode 11.1]
 - QMUI 版本: [4.0.4]

**Comment by xixisplit** [comment]
不好意思.提交之后才看到之前的答复了..

**Comment by MoLice** [comment]
参考 #707
