### ISSUE TITLE
QMUIAppearance.h' file not found。从4.0.0升级到4.0.4的bug

### ISSUE THREAD

**Issue by zymjjobs** [Tencent/QMUI_iOS#943]
**Bug 表现**
问题的具体描述

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
QMUIAppearance 是 4.1.0 才加入的，你确定你升级的版本号是 4.0.4？

另外关于编译失败的，至少应该提供类似你是怎么引入的、用 pod 的话 Podfile 是怎么写的，之类的信息，单纯这样一个 issue 换做是你你要怎么排查...

**Comment by zzzzzpppp** [comment]
新项目，直接 pod 'QMUIKit' .

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/78690064-934ae300-7929-11ea-87ad-35e17d974661.png)

直接打开项目里的 QMUIKit.h 查看实际版本号，pod 有它自己的本地更新策略，你的仓库不一定是最新的。

**Comment by MoLice** [comment]
参考 #948
