### ISSUE TITLE
怎么才可以控制iPhone竖屏 iPad横屏呢? is_iPad似乎并没有起到作用

### ISSUE THREAD

**Issue by wangyicheng0827** [Tencent/QMUI_iOS#944]
QMUI 已经提供了**详尽的注释文档**，以及**完整的示例项目 [QMUI Demo](https://github.com/QMUI/QMUI_iOS_Demo)**，当你遇到某些功能不知道怎么使用，或者想知道 QMUI 是否有提供某些功能时，请先查看注释文档或者 Demo，找不到了再提 issue。若提的 issue 已有明确注释或示例的，**可能会被直接关闭或得不到及时的回复**，请知悉。

**Comment by MoLice** [comment]
iPad 本身就没有这个能力。
