### ISSUE TITLE
UIViewController设置qmui_preferredStatusBarStyleBlock无效

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#947]
**Bug 表现**
若一TestViewController内部实现方法：  
```  
- (UIStatusBarStyle)preferredStatusBarStyle {
    return UIStatusBarStyleDefault;
}  
```  
则当使用qmui_preferredStatusBarStyleBlock时，block并不生效  
```  
TestViewController *viewController = [[TestViewController alloc] init];
viewController.qmui_preferredStatusBarStyleBlock = ^UIStatusBarStyle{
    return UIStatusBarStyleLightContent;
};
[self.navigationController pushViewController:viewController animated:YES];  
``` 

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone]
 - iOS 版本: [iOS 13.4]
 - Xcode 版本: [Xcode 11.4]
 - QMUI 版本: [4.1.1]

**Comment by MoLice** [comment]
`qmui_preferredStatusBarStyleBlock` 这一系列的属性本身就是设计来给那些无法重写系统方法的场景，既然你已经重写了，那么你重写的逻辑自然是优先级最高的。如果你既想要重写系统方法，又要使用 `qmui_preferredStatusBarStyleBlock`，那建议在 `-preferredStatusBarStyle` 里返回当前 `qmui_preferredStatusBarStyleBlock` 的值。
