### ISSUE TITLE
'QMUIAppearance.h' file not found

### ISSUE THREAD

**Issue by a694101751** [Tencent/QMUI_iOS#948]
pod 'QMUIKit' 后 static NSString * const QMUI_VERSION = @"4.1.1"; 编译报错 找不到 QMUIAppearance 该文件
<img width="383" alt="WechatIMG1" src="https://user-images.githubusercontent.com/13847283/78759332-0ac45500-79b2-11ea-8f3e-8c53bcad64af.png">
<img width="831" alt="WechatIMG2" src="https://user-images.githubusercontent.com/13847283/78759336-0b5ceb80-79b2-11ea-8f9d-c9e469bb2757.png">

**Comment by a694101751** [comment]
<img width="1094" alt="WechatIMG3" src="https://user-images.githubusercontent.com/13847283/78759406-27f92380-79b2-11ea-8475-73ec09fd7683.png">

**Comment by MoLice** [comment]
测试并没有问题，以下是测试用的空项目。
[TestPods.zip](https://github.com/Tencent/QMUI_iOS/files/4449127/TestPods.zip)

Podfile 文件：
```
target 'TestPods' do
    use_frameworks!
    pod 'QMUIKit'
end
```

请自行检查，如仍有问题，请提供可复现的 Demo。

**Comment by a694101751** [comment]
已经解决了，本地 CocoaPods 版本低的原因，不好意思

**Comment by MoLice** [comment]
> 测试并没有问题，以下是测试用的空项目。
> [TestPods.zip](https://github.com/Tencent/QMUI_iOS/files/4449127/TestPods.zip)
> 
> Podfile 文件：
> 
> ```
> target 'TestPods' do
>     use_frameworks!
>     pod 'QMUIKit'
> end
> ```
> 
> 请自行检查，如仍有问题，请提供可复现的 Demo。

参考 #953 才是正确原因。
