### ISSUE TITLE
[UIKit Bug] 当 UISearchController.searchBar 作为 tableHeaderView 使用时，顶部可能出现 1px 的间隙导致露出背景色

### ISSUE THREAD

**Issue by MoLice** [Tencent/QMUI_iOS#950]
**如何重现**
1. 使用一张透明图片（例如 `UIImage.new`）作为 `UINavigationBar.shadowImage`，避免导航栏分隔线挡住 searchBar 导致无法观察到 bug 现象。
1. 为了便于观察，可以把 searchBar 的背景图设置为纯色，但这一步非必须，可以保持系统默认的外观。
1. 创建一个 `UITableViewController` 界面，初始化一个 `UISearchController` 并将它的 `searchBar` 属性赋值给 `tableView.tableHeaderView`。为了便于观察，可将 `tableView.backgroundColor` 设置为显眼的颜色。
1. 进入该列表界面，可看到一开始 `searchBar` 和 `navigationBar` 是贴合在一起的。
1. 上下滚动列表，会触发 `searchBar` 重新布局，当列表停止滚动后可以看到 `searchBar` 顶部出现一个 1px 的间隙。

**截图**
<img src="https://user-images.githubusercontent.com/1190261/79111977-206dbc00-7db0-11ea-971d-01bf02a86ee5.png" width="333" />

<img src="https://user-images.githubusercontent.com/1190261/79112082-5e6ae000-7db0-11ea-979e-c8a87bf562a0.png" width="333" />

<img src="https://user-images.githubusercontent.com/1190261/79111941-151a9080-7db0-11ea-90fa-579755fad1be.png" width="333" />

**测试 Demo**
[TestSearchBar.zip](https://github.com/Tencent/QMUI_iOS/files/4469073/TestSearchBar.zip)

**注意**
如果直接初始化一个 `UISearchBar` 并赋值给 `tableHeaderView`，则不会出现该问题。

**其他信息**
 - 设备: [All]
 - iOS 版本: [iOS All]
 - Xcode 版本: [Xcode 11.4]

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/79112769-ee5d5980-7db1-11ea-8c60-a5e139193929.png)

断点观察到在滚动列表时，`UISearchController` 内部确实有一套机制去根据 `UIScrollView` 的滚动动作调整 `UISearchBar` 内部的 `maskView` 布局，但不清楚这样调整的目的是什么。目前暂时通过 swizzle `- [UISearchBar _setMaskBounds:]` 来屏蔽这种调整，下个版本会给出对应的接口。

**Comment by RomanticEncounter** [comment]
**Bug 表现**
searchControl导致navBar的关联性问题，滑动`UITableView`会触发`UINavigationController(LargeTitleCompatibility)` 的`swizzle `方法

```objc
self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
    [self.view addSubview:self.tableView];
    if (@available(iOS 11.0, *)) {
        self.navigationItem.searchController = self.searchController;
    } else {
        // Fallback on earlier versions
       // 设置为HeaderView则不会出现此问题
        self.tableView.tableHeaderView = self.searchController.searchBar;
    }
```

**截图**

第一次进来
![首次进入的效果](https://user-images.githubusercontent.com/16411177/79291709-ee6c6f00-7f01-11ea-89f9-07ca3326feda.png)

滑动后的效果
![滑动后的效果](https://user-images.githubusercontent.com/16411177/79291632-ba914980-7f01-11ea-9e7a-6367e5792f17.png)

![scrollView滑动时代码](https://user-images.githubusercontent.com/16411177/79291488-60908400-7f01-11ea-8511-b6b1df3720a0.png)

**Comment by ziecho** [comment]
> **Bug 表现**
> searchControl导致navBar的关联性问题
> 
> iOS 11及以上系统，滑动`UITableView`会出现`LargeTitle`动画效果
> 
> ```objc
> self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
>     [self.view addSubview:self.tableView];
>     if (@available(iOS 11.0, *)) {
>         self.navigationItem.searchController = self.searchController;
>     } else {
>         // Fallback on earlier versions
>        // 设置为HeaderView则不会出现此问题
>         self.tableView.tableHeaderView = self.searchController.searchBar;
>     }
> ```
> 
> **截图**
> 
> 第一次进来
> ![首次进入的效果](https://user-images.githubusercontent.com/16411177/79291709-ee6c6f00-7f01-11ea-89f9-07ca3326feda.png)
> 
> 滑动后的效果
> ![滑动后的效果](https://user-images.githubusercontent.com/16411177/79291632-ba914980-7f01-11ea-9e7a-6367e5792f17.png)
> 
> 触发`UINavigationController(LargeTitleCompatibility)` 的`swizzle `方法
> ![scrollView滑动时代码](https://user-images.githubusercontent.com/16411177/79291488-60908400-7f01-11ea-8511-b6b1df3720a0.png)

你是指 navigationBar 变透明了吗，这个是 iOS 11 设置了 navigationItem.searchController 后的系统默认特性，和 QMUI 无关，如果你不需要这个特性请写上
```objc
self.navigationItem.hidesSearchBarWhenScrolling = NO;
```

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。
