### ISSUE TITLE
真机运行崩溃 iOS13.3.1

### ISSUE THREAD

**Issue by TheFlyingChicken** [Tencent/QMUI_iOS#951]
**Bug 表现**
dyld: Library not loaded: @rpath/QMUIKit.framework/QMUIKit
  Referenced from: /private/var/containers/Bundle/Application/33D42046-EC1D-4F58-BBC7-B36B97FF462B/*.app/*
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/33D42046-EC1D-4F58-BBC7-B36B97FF462B/*.app/Frameworks/QMUIKit.framework/QMUIKit: code signature invalid for '/private/var/containers/Bundle/Application/33D42046-EC1D-4F58-BBC7-B36B97FF462B/*.app/Frameworks/QMUIKit.framework/QMUIKit'

	/private/var/containers/Bundle/Application/33D42046-EC1D-4F58-BBC7-B36B97FF462B/*.app/Frameworks/QMUIKit.framework/QMUIKit: stat() failed with errno=25

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [iPhoneX]
 - iOS 版本: [iOS 13.3.1]
 - Xcode 版本: [Xcode 11.4]
 - QMUI 版本: [4.0.4]

**Comment by MoLice** [comment]
请尝试通过 Google 解决 https://www.google.com/search?q=code+signature+invalid+for&oq=code+signature+invalid+for&aqs=chrome..69i57j0l7.305j0j7&sourceid=chrome&ie=UTF-8

![image](https://user-images.githubusercontent.com/1190261/79121979-30de6080-7dc9-11ea-94e3-bb94da7786b2.png)
