### ISSUE TITLE
- (BOOL)shouldPopViewControllerByBackButtonOrPopGesture:(BOOL)byPopGesture   这个方法参数bug

### ISSUE THREAD

**Issue by iphone5s** [Tencent/QMUI_iOS#952]
**Bug 表现**
问题的具体描述
- (BOOL)shouldPopViewControllerByBackButtonOrPopGesture:(BOOL)byPopGesture 
此方法的参数byPopGesture  表示是否是右滑
正常情况下， 
右滑返回 byPopGesture 是YES
点返回按钮byPopGesture 是NO

bug  禁止右滑返回
先 右滑一次  这个时候 byPopGesture 是YES  返回NO 
然后点击返回按钮 这个值传的还是 YES 这个时候应该是YES 才对
  
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
下个版本会更换实现方式以修复该问题，在此之前如有需要，可以将以下文件替换掉你本地的 Pod 版本临时修复。
[UINavigationController+QMUI.m.zip](https://github.com/Tencent/QMUI_iOS/files/4481735/UINavigationController%2BQMUI.m.zip)

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。
