### ISSUE TITLE
4.0.4版本的podspec文件配置错误导致'QMUIAppearance.h' file not found编译错误

### ISSUE THREAD

**Issue by xia0m1ng** [Tencent/QMUI_iOS#953]
**Bug 表现**
如果cocoapods没有缓存4.0.4版本，那么重新安装4.0.4版本会出现'QMUIAppearance.h' file not    found编译错误。
#943 #948 都是这个原因引起的。之所以作者没有复现，应该是因为作者的cocoapods缓存了4.0.4版本，没有重新拉取。

**如何重现**
1.  执行 `pod cache clean 'QMUIKit' --all`， 删除本地QMUIKit缓存
2.  新建项目，并指定pod为 `pod 'QMUIKit',  '4.0.4'`
3. 执行 `pod install`
4. 编译项目

**原因分析**
查看[4.0.4版本的podspec](https://github.com/CocoaPods/Specs/blob/68275dc9b7ca15a35d2924725b846020a4b19bc5/Specs/8/1/5/QMUIKit/4.0.4/QMUIKit.podspec.json#L11-L14)可以发现4.0.4版本指定的source是master分支而不是特定的tag。所以cocoapods每次拉取4.0.4版本，都是拉取的最新的master分支，导致与4.0.4版本声明的源文件不匹配，出现编译错误。

**临时解决方法**
通过 `pod 'QMUIKit', :git => 'https://github.com/Tencent/QMUI_iOS.git', :tag => '4.0.4'` 安装4.0.4版本

**Comment by MoLice** [comment]
原来如此，当时发布的时候手抖改错了，抱歉

**Comment by Nsir15** [comment]
我也遇到了这个问题，2020年5月1日。还是用了你这个办法才跑起来的。看来这个问题还没很好修复

**Comment by MoLice** [comment]
4.0.4 版本暂且按照本 issue 的方式处理，建议更新到最新的 4.1.2 版本。
