### ISSUE TITLE
QMUITableViewCell initForTableView初始化方法 导致 cell 无法被正常销毁

### ISSUE THREAD

**Issue by xixisplit** [Tencent/QMUI_iOS#956]
**Bug 表现**
问题的具体描述
使用 initForTableView 方式初始化 cell reloadData 之后.原有的 cell 不会被销毁.重叠在 tableview 上
使用     QMUITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:QMUITableViewCell.description];
    if (!cell) {
        cell  = [[QMUITableViewCell alloc] initWithStyle:(UITableViewCellStyleDefault) reuseIdentifier:QMUITableViewCell.description];
    } 
的方式初始化就不会有此问题
这样会不会造成多余的内存开销

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
这个是 lookin 里面看到的视图层级
<img width="988" alt="image" src="https://user-images.githubusercontent.com/17351286/79831075-4fe87e00-83d9-11ea-8d32-8f4da375c852.png">

**如何重现**
1. 将以下代码放入一个空白控制器中即可

@interface ViewController ()
@property (nonatomic, strong) QMUITableView *tableView;
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = UIColor.whiteColor;
    
    QMUITableView *tableView = [[QMUITableView alloc] initWithFrame:(CGRectZero) style:(UITableViewStyleGrouped)];
    self.tableView = tableView;
    tableView.delegate = self;
    tableView.dataSource = self;
    
    [self.view addSubview:tableView];
    [tableView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.view);
    }];
}

-(void)viewDidAppear:(BOOL)animated{
    [super viewDidAppear:animated];

    [self.tableView reloadData];
}

-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{
    return 3;
}
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath{
    QMUITableViewCell *cell = [[QMUITableViewCell alloc] initForTableView:tableView withReuseIdentifier:[NSString stringWithFormat:@"QMUITableViewCell.description%@",indexPath.description]];
    cell.textLabel.text = @"2342342";
    return cell;
}
@end

**预期的表现**
正常情况下，reloaddata 之后.不应出现多余的 cell 在 tableview 的视图中.虽然已经被隐藏

**其他信息**
 - 设备: [模拟器]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11.1]
 - QMUI 版本: [4.0.4]

**Comment by fanyuecheng** [comment]
在`tableView :cellForRowAtIndexPath: `里面返回cell就没有你这样写的。你是写法错误了。
要么事先```[tableView registerClass: QMUITableViewCell.class  forCellReuseIdentifier:@"cell"]```
然后```QMUITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell" forIndexPath:indexPath];```  
要么直在代理里面  
```  
static NSString *kCellIdentifer = @"cell";   
QMUITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kCellIdentifer]; 
 
if (!cell) {  
cell = [[QMUIAlbumTableViewCell alloc] initForTableView:tableView UITableViewCellStyleDefault reuseIdentifier:kCellIdentifer];  
}  
```

**Comment by xixisplit** [comment]
> 在`tableView :cellForRowAtIndexPath: `里面返回cell就没有你这样写的。你是写法错误了。
> 或者事先`[tableView registerClass: QMUITableViewCell.class forCellReuseIdentifier:@"cell"]`
> 然后`QMUITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell" forIndexPath:indexPath];`
> 要么直在代理里面
> 
> ```
> static NSString *kCellIdentifer = @"cell";   
> QMUITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kCellIdentifer]; 
>  
> if (!cell) {  
> cell = [[QMUITableViewCell alloc] initForTableView:tableView UITableViewCellStyleDefault reuseIdentifier:kCellIdentifer];  
> }  
> ```

多谢.因为这是一个静态页面才没有 if(!cell)来写的,平时超过一屏的都是 if(!cell)来写的.看来不能偷懒
