### ISSUE TITLE
两个导航背景图片颜色不一样 手势返回出现这样的问题

### ISSUE THREAD

**Issue by Fly-Sunshine-J** [Tencent/QMUI_iOS#959]
![Simulator Screen Shot - iPhone 8 - 2020-04-24 at 08 59 09](https://user-images.githubusercontent.com/17582854/80163839-f9ae5180-8609-11ea-9f5a-560e331dcec5.png)
![Simulator Screen Shot - iPhone 8 - 2020-04-24 at 08 59 11](https://user-images.githubusercontent.com/17582854/80163843-fc10ab80-8609-11ea-8050-250441e2bfa7.png)
![Simulator Screen Shot - iPhone 8 - 2020-04-24 at 08 59 19](https://user-images.githubusercontent.com/17582854/80163844-fd41d880-8609-11ea-9e82-2326f52d787d.png)

两个导航栏背景颜色不同意，手势返回造成这种现象怎么处理

**Comment by MoLice** [comment]
“这种现象”是指？

**Comment by Fly-Sunshine-J** [comment]
> “这种现象”是指？

颜色突变成后面ViewController的颜色了
