### ISSUE TITLE
使用QMUINavigationController后，可以继续使用系统默认的导航条样式吗 

### ISSUE THREAD

**Issue by github641** [Tencent/QMUI_iOS#960]
QMUI 已经提供了**详尽的注释文档**，以及**完整的示例项目 [QMUI Demo](https://github.com/QMUI/QMUI_iOS_Demo)**，当你遇到某些功能不知道怎么使用，或者想知道 QMUI 是否有提供某些功能时，请先查看注释文档或者 Demo，找不到了再提 issue。若提的 issue 已有明确注释或示例的，**可能会被直接关闭或得不到及时的回复**，请知悉。

### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`11.3`
- [x] QMUI iOS 版本：`4.0.0`

### 具体问题描述 ###
使用了QMUINavigationController，看了demo中各种主题的切换，效果都很好。目前是想让app处于某个主题下，比如“Pink Rose”，然后保留系统的导航条样式，找了好久也没有发现要怎么设置才能做到，也不知道哪里可以获得咨询和帮助，在这里发个issue请教下。

在QMUIConfigurationTemplate设置 QMUICMI.navBarBackgroundImage为白色，或者是nil都不是系统的bar样式,而且切换时，有闪动的灰黑色过渡动画。

#### 问题截图 ####

![截屏2020-04-23 下午4 23 32](https://user-images.githubusercontent.com/11991492/80076446-cc689180-857e-11ea-8310-62c0bb377b70.png)

**Comment by github641** [comment]
发现将naviBar设置为默认样式，push和pop第一个层级时，导航条的右侧会有，闪动的灰黑色过渡动画，后面的层级就不会出现了。
附上录屏：
![Jietu20200426-091740-HD](https://user-images.githubusercontent.com/11991492/80294790-d2d55400-879e-11ea-8993-86c3a9db4249.gif)

**Comment by fanyuecheng** [comment]
当前的controller实现QMUINavigationControllerAppearanceDelegate
`- (UIImage *)navigationBarBackgroundImage` 并返回nil
`- (UIImage *)navigationBarShadowImage` 并返回nil
这样就是系统默认的样子了
另外还有代理方法修改title颜色，返回按钮的颜色，自己看吧

**Comment by MoLice** [comment]
重复 issue，参考 https://github.com/QMUI/QMUIDemo_iOS/issues/49#event-3277660534
