### ISSUE TITLE
可以给QMUIHelper中的deviceName添加下iPhone 12,8的信息吗

### ISSUE THREAD

**Issue by pcccccc** [Tencent/QMUI_iOS#961]
**现存问题或期望目标**
可以给QMUIHelper中的deviceName添加下iPhone 12,8的信息吗
QMUI版本：4.1.1

**Comment by codingiran** [comment]
@pcccccc  补充一下：iPhone12,8 应该是之前发布的 iPhone SE (2nd generation)

**Comment by MoLice** [comment]
下个版本会添加

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。
