### ISSUE TITLE
侧滑时，导航栏偶尔会带有back字或者上一级的title

### ISSUE THREAD

**Issue by passol1988** [Tencent/QMUI_iOS#962]
`self.navigationController.navigationBar.topItem.title = @"";
    [self.navigationItem.backBarButtonItem setTitle:@""];
    self.navigationController.navigationBar.backItem.title = @"";`
侧滑一部分又取消，导航栏偶尔带有back字，也清不掉，不知道哪里出来的

**Comment by fanyuecheng** [comment]
看看QMUINavigationControllerAppearanceDelegate的这个方法
```  
// 设置系统返回按钮title，如果返回nil则使用系统默认的返回按钮标题。当实现了这个方法时，会无视配置表 NeedsBackBarButtonItemTitle 的值  
-(nullable NSString *)backBarButtonItemTitleWithPreviousViewController:(nullable UIViewController *)viewController;  
```
