### ISSUE TITLE
您好，我使用QMUIGridView是，使用QMUIViewSelfSizingHeight来确定高度出现了CALayer position contains NaN

### ISSUE THREAD

**Issue by LYluyu** [Tencent/QMUI_iOS#964]
**Bug 表现**
问题的具体描述

1. 创建gridView并添加到vc的view上（gridView子控件是有网络请求数据来确定的）
2. 创建控件A并添加到vc的view上，于gridView同级，并且控件A的位置需要依赖gridView的位置。
3. 在viewDidLayoutSubviews布局gridView和控件A的位置。
4. gridView的位置高度使用了QMUIViewSelfSizingHeight来确定。
5. 在布局了gridView之后，布局控件A时使用了CGRectGetMaxY(gridView.frame)出现了CALayer position contains NaN

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
那此时 gridView 的 frame 是什么值？

**Comment by LYluyu** [comment]
![image](https://user-images.githubusercontent.com/16254669/80434596-c2eb7a80-892c-11ea-9d5f-16b491056346.png)

**Comment by MoLice** [comment]
那应该要先看你的 gridView 为什么 y 是 NaN？这个跟 QMUIViewSelfSizingHeight 是没关系的吧

**Comment by LYluyu** [comment]
![image](https://user-images.githubusercontent.com/16254669/80568485-ad0faf80-8a29-11ea-8ad7-80fd45fc3fbf.png)
![image](https://user-images.githubusercontent.com/16254669/80568665-0546b180-8a2a-11ea-82db-7554a594f744.png)
第一张图是我通过sizeThatFits计算出高度再赋值给gridView的高度，这样子是正常的，但是如果我直接通过QMUIViewSelfSizingHeight来赋值给gridView，就出现了这个情况

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/80722650-2f839680-8b32-11ea-96a5-241a0a86fc7e.png)
第一张图里你 sizeThatFits 计算出来的 height 就已经错了，`-10`，只不过 UIView 在 `setFrame:` 里会处理负值的情况，导致看起来好像是正常的。
请先检查为什么得到 height = -10

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
