### ISSUE TITLE
shouldPopViewControllerByBackButtonOrPopGesture这个方法在点击返回按钮时才触发，侧滑返回不触发了

### ISSUE THREAD

**Issue by JFPURE** [Tencent/QMUI_iOS#966]
**Bug 表现**
问题的具体描述
版本更新至4.1.1，shouldPopViewControllerByBackButtonOrPopGesture这个方法在点击返回按钮时才触发，侧滑返回不触发了，请看看是咋回事？

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. shouldPopViewControllerByBackButtonOrPopGesture这个方法在点击返回按钮时才触发，侧滑返回不触发了

**预期的表现**
正常情况下，应该是在点击返回按钮时或者侧滑返回都触发 shouldPopViewControllerByBackButtonOrPopGesture这个方法

**其他信息**
 - 设备: 真机 iPhone XS Max
 - iOS 版本: iOS 13.4
 - Xcode 版本: Xcode 11.4.1
 - QMUI 版本: 4.1.1

**Comment by MoLice** [comment]
没遇到这种情况，请查看是否有第三方 framework 产生了冲突，或者搜索已有 issue，或者提供可复现的 Demo。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。

**Comment by HYJFromQc** [comment]
demo 里面 滑动返回都没用 ，4.1.3

**Comment by MoLice** [comment]
> demo 里面 滑动返回都没用 ，4.1.3

4.1.3 在 iOS 13 上测试过无法重现，有什么操作路径吗？

**Comment by HYJFromQc** [comment]
> > demo 里面 滑动返回都没用 ，4.1.3
> 
> @HYJFromQc 4.1.3 在 iOS 13 上测试过无法重现，有什么操作路径吗？

和上面老哥应该是一样的问题，就是demo，13.4以上 刘海屏 模拟器  不能滑动返回，任何push地方都不能

**Comment by MoLice** [comment]
已经回应过了，直接在 https://github.com/QMUI/QMUIDemo_iOS 下载代码并在 iPhone 11 Pro Max 13.5.1 上测试过 **无法重现**，所以目前 issue 提供的信息没有帮助。

[手势返回.mov.zip](https://github.com/Tencent/QMUI_iOS/files/4804558/mov.zip)
