### ISSUE TITLE
关于的Mac Catalyst的建议

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#967]
**现存问题或期望目标**
Mac Catalyst会有部分代码编译不过，可以先用宏来屏蔽掉，使用者就不用改动Pod源代码了
<img width="682" alt="图片" src="https://user-images.githubusercontent.com/22904757/80332577-c8d65280-887d-11ea-8ebb-614f79667b40.png">

**Comment by MoLice** [comment]
好的，除了这里还有别的地方吗？方便的话可以贴一下，具体这个截图的方法已经没人使用，下个版本会删掉。

**Comment by jiasongs** [comment]
> 好的，除了这里还有别的地方吗？方便的话可以贴一下，具体这个截图的方法已经没人使用，下个版本会删掉。

只有这一处地方编译不过

**Comment by MoLice** [comment]
好的，你可以先自行处理，等新版本发布会告知。

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。
