### ISSUE TITLE
在Appdelegate开始进行日志打印，但是调用[QMUIConsole show]不显示日志小图标视图

### ISSUE THREAD

**Issue by snake406635029** [Tencent/QMUI_iOS#968]
QMUI 已经提供了**详尽的注释文档**，以及**完整的示例项目 [QMUI Demo](https://github.com/QMUI/QMUI_iOS_Demo)**，当你遇到某些功能不知道怎么使用，或者想知道 QMUI 是否有提供某些功能时，请先查看注释文档或者 Demo，找不到了再提 issue。若提的 issue 已有明确注释或示例的，**可能会被直接关闭或得不到及时的回复**，请知悉。

经过调试发现是 QMUIConsole.m 中 87行
`if (!console.consoleWindow.hidden)  return;`
应该修改为
```
if (!console.consoleWindow.hidden) {
            [console.consoleWindow makeKeyAndVisible];
            return;
}
```
才能展示

**Comment by MoLice** [comment]
这是因为 QMUIConsole 内部用的 UIWindow.windowLevel = 0，而 AppDelegate 的主 window 的 windowLevel 一般也是默认的0，所以只要 AppDelegate 的主 window 比 QMUIConsole 的 window 更晚显示，就会盖住 QMUIConsole window，导致看不到。
目前你可以先修改 QMUIConsole.m 末尾的 `initConsoleWindowIfNeeded` 方法，给 window 赋值一个 windowLevel = 1，新版本我们再解决这种场景下的问题。

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。
