### ISSUE TITLE
swift设置QMUITextField的placeholderColor问题

### ISSUE THREAD

**Issue by developerjet** [Tencent/QMUI_iOS#969]
**Bug 表现**
swift设置QMUITextField的placeholderColor后，在对QMUITextField输入框的值设置更改的时候（如点击加减按钮使输入框的值发生改变），会导致卡住线程，内存消耗严重，最后导致crash；

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
![image](https://user-images.githubusercontent.com/18006470/80553651-3361cc80-89fd-11ea-852c-33d12d9bc9a4.png)

**预期的表现**
希望能后解决线程卡住问题

**其他信息**
 - 设备: [iPhone8Plus]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11.4.1]
 - QMUI 版本: [6.0]

**Comment by MoLice** [comment]
建议提供一份可复现的 Demo
