### ISSUE TITLE
QMUITextView与三方库ReactiveObjC结合使用时会循环调用的问题

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#970]
**Bug 表现**
QMUITextView与ReactiveObjC结合使用时会循环调用的问题

**截图**
<img width="1524" alt="图片" src="https://user-images.githubusercontent.com/22904757/80665171-5195fe00-8acb-11ea-9b7a-a0d4c1c6ec5f.png">
<img width="351" alt="图片" src="https://user-images.githubusercontent.com/22904757/80665223-725e5380-8acb-11ea-82f7-95d156c9d6e8.png">

**如何重现**
1. 引入'ReactiveObjC', '~> 3.1.1'，创建一个QMUITextView
2. 如下图所示，加一个监听者
<img width="676" alt="图片" src="https://user-images.githubusercontent.com/22904757/80665316-b18ca480-8acb-11ea-98cc-3f457b6e6f10.png">
3.输入文字即可重现

**预期的表现**
两者可以正常使用

**其他信息**
 - 设备: 模拟器 11 Pro
 - iOS 版本: iOS 13.4
 - Xcode 版本: Xcode 11.4.1
 - QMUI 版本: 4.1.1

**Comment by MoLice** [comment]
这是 `QMUIMultipleDelegates` 与 RAC 冲突引发死循环导致的，`QMUITextView` 默认开启了 `QMUIMultipleDelegates`，而我们在代码里执行 `textView.rac_textSignal` 时，RAC 内部会有如下逻辑（其中 `self` 也即当前的 `QMUITextView`）：
![image](https://user-images.githubusercontent.com/1190261/80891910-b767cd00-8cf9-11ea-9cba-c508c2237978.png)

如截图注释所说，这段代码的最终效果是 `QMUIMultipleDelegates` 容器里增加了一个 `RACDelegateProxy` 的对象。

当我们键入文本到 `QMUITextView` 时，系统会询问 `-[UITextViewDelegate textView:shouldChangeTextInRange:replacementText:]`，此时就会走到 `-[QMUIMultipleDelegates forwardInvocation:]` 内，按顺序遍历一遍 delegates，当遍历到 `RACDelegateProxy` 时，由于 `RACDelegateProxy` 的实现也是消息转发，它会做一些自己的事情后，直接把 `NSInvocation` 重新转给 `QMUITextView.delegate`：
![image](https://user-images.githubusercontent.com/1190261/80892045-aec3c680-8cfa-11ea-8284-b8081f86ff2e.png)

在这个场景里就是转给 `QMUIMultipleDelegates`，而 `QMUIMultipleDelegates` 又会重新走一遍上述的逻辑，把 `NSInvocation` 重新转发给 `RACDelegateProxy`，从而引发死循环。

目前先用简单的方式处理了这种情况，你可以下载 [QMUIMultipleDelegates.m](https://github.com/Tencent/QMUI_iOS/files/4568928/QMUIMultipleDelegates.m.zip) 并替换你本地的 QMUI 同名文件，Clean Project 后尝试，应该就没问题了。是否有更优雅的方式解决，我们还在继续看，也欢迎社区提供思路。

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。

**Comment by chen-shuang-lin** [comment]
更新4.2.3后，此问题再次出现

**Comment by MoLice** [comment]
@chen-shuang-lin 请提供 Demo。

**Comment by chen-shuang-lin** [comment]
<img width="773" alt="WX20210617-092548@2x" src="https://user-images.githubusercontent.com/24601327/122316243-17492380-cf4e-11eb-9de9-c80d53877f1d.png">
<img width="1131" alt="WX20210617-092620@2x" src="https://user-images.githubusercontent.com/24601327/122316257-2039f500-cf4e-11eb-8a79-c7bc578137a9.png">
@MoLice 一启动就会崩溃，Demo已提供
[Demo.zip](https://github.com/Tencent/QMUI_iOS/files/6666717/Demo.zip)

**Comment by 19aneng** [comment]
挺急的，+1

**Comment by MoLice** [comment]
@19aneng 已发布 [4.3.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.3.0) 修复该问题。
