### ISSUE TITLE
tableCaheHeight 无法删除缓存高度的问题

### ISSUE THREAD

**Issue by inoryshu** [Tencent/QMUI_iOS#974]
**Bug 表现**
<img width="1328" alt="WeChata75cdc3ebec880ff5ca446b1d4fa68b0" src="https://user-images.githubusercontent.com/16499387/80914037-93e56680-8d7b-11ea-9948-3837dbcf2c7d.png">
<img width="1328" alt="WeChata75cdc3ebec880ff5ca446b1d4fa68b0" src="https://user-images.githubusercontent.com/16499387/80914049-a790cd00-8d7b-11ea-9c9e-b1bb4021a3dd.png">
截图中的删除对应key缓存高度的操作压根就没用作用，正如第一个截图说的那样，qmui_invalidateHeightForKey传入的key没有任何用处。

**截图**
<img width="692" alt="WeChat7c69bafa70736f719f23d8243c4771a9" src="https://user-images.githubusercontent.com/16499387/80914084-f9395780-8d7b-11ea-8d44-26332c6214e3.png">
实际上我想删除的是key为69的高度缓存，然后此时传入的key 是414
![image](https://user-images.githubusercontent.com/16499387/80914138-3867a880-8d7c-11ea-9d4a-91bf18a94385.png)
此时多了一个key 为6的高度缓存。

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.3.1]
 - Xcode 版本: [Xcode 11.4.1]
 - QMUI 版本: [4.1.1]

**Comment by MoLice** [comment]
下个版本会修复，在此之前可以自行修改源码，类似：
```objc
- (void)qmui_invalidateHeightForKey:(id<NSCopying>)aKey {
    xxx
    [obj invalidateHeightForKey:aKey];
}
```

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。
