### ISSUE TITLE
QMUIAlertController  在 iOS 9.  上点击 不显示，并且界面卡死

### ISSUE THREAD

**Issue by MrHanbing** [Tencent/QMUI_iOS#975]
**Bug 表现**
QMUIAlertController  在iOS9 上 点击无反应。并且界面卡死
1. 点击。在QMUIDemo 上的alert 中的第一个cell "显示一个alert弹窗" 就能复现

**预期的表现**
在我们的项目中出现这个问题，运行官方demo。出现一样的问题

**其他信息**
 - 设备: 6P
 - iOS 版本: iOS 9.3.2
 - Xcode 版本: 11.3
 - QMUI 版本: 4.1.1

**Comment by MoLice** [comment]
该问题是 4.1.0 新增的 `QMUIAppearance` 引发的，在 iOS 9 下调用 `qmui_applyAppearance` 会触发 `loadView`，导致 `viewDidLoad` 比 `init` 更早执行，引发一些时序上的问题，下个版本会修复，在此之前你可以将以下文件替换本地 QMUI 同名文件临时解决：[QMUIAlertController.m](https://github.com/Tencent/QMUI_iOS/files/4586107/QMUIAlertController.m.zip)。

**Comment by MoLice** [comment]
已发布 [4.1.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.2) 修复该问题。
