### ISSUE TITLE
删除列表section 崩溃

### ISSUE THREAD

**Issue by lengqingfeng** [Tencent/QMUI_iOS#977]
**Bug 表现**
删除列表section 时候总是执行到 
[self qmuiTableCache_deleteSections:sections withRowAnimation:animation];
这个代码导致崩溃

**截图**

<img width="415" alt="截屏2020-05-06 下午2 46 27" src="https://user-images.githubusercontent.com/4401182/81147461-f07b9800-8fac-11ea-885b-5e63115dd249.png">

#
https://wx2.sinaimg.cn/mw690/b383e575ly1geiqc2g1n5j20n20bin9p.jpg

**如何重现**
1. ...
2. ...

**预期的表现**
删除cell列表

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.1]
 - Xcode 版本: [Xcode 11.4.1]
 - QMUI 版本: [4.1.1]

**Comment by MoLice** [comment]
图片无法查看，请直接贴图到 GitHub 上，不要用外链。

**Comment by lengqingfeng** [comment]
已更新，如何解决。

**Comment by MoLice** [comment]
issue 只展示了调用堆栈，按当前提供的信息暂无法定位问题所在。QMUI 里这个方法是 swizzle 了系统的方法，所以只要系统的 `deleteSections:withRowAnimation:` 方法被调用，该方法就会被调用，所以 QMUI 该方法被调用并不能证明是该方法出了问题。建议提供 crash 时的 Xcode 控制台信息，或者提供一份可复现的 Demo，按经验来看，一般你遇到的这种问题都是业务问题，与 QMUI 无关。

**Comment by jiasongs** [comment]
没更新数据源吧
