### ISSUE TITLE
QMUIImagePickerPreviewViewController的backButton & checkboxButton 点击无效

### ISSUE THREAD

**Issue by fanyuecheng** [Tencent/QMUI_iOS#978]
**Bug 表现**
 
QMUIImagePickerPreviewViewController的backButton & checkboxButton 点击无效

**如何重现**
运行QMUIDemo即可
topToolBarView被imagePreviewView覆盖了

![7FED9CE1-23B4-4784-B219-06297B3C1993](https://user-images.githubusercontent.com/34535969/81268857-140d1400-907b-11ea-80e7-e9f7a0fe2892.png)

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [模拟器 iPhone11pro]
 - iOS 版本: [iOS 13.4]
 - Xcode 版本: [Xcode 11.4.1]
 - QMUI 版本: [4.1.2]

**Comment by MoLice** [comment]
这是 4.1.2 引入的 bug，会尽快发版本修复，在此之前可以先修改本地的 `QMUIImagePreviewViewController.m` 文件，把里面的 `viewDidLoad` 方法改为 `initSubviews`，注意 super 的调用也要跟着改。

**Comment by MoLice** [comment]
已发布 [4.1.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.3) 修复该问题。
