### ISSUE TITLE
v4.1.2版本横屏时全面屏设备TableView ContentView超过了Safe Area

### ISSUE THREAD

**Issue by evanzhou1989** [Tencent/QMUI_iOS#980]
**Bug 表现**
v4.1.2版本横屏时全面屏设备TableView ContentView超过了Safe Area

**截图**
![Screen Shot 2020-05-07 at 6 50 21 PM](https://user-images.githubusercontent.com/6427544/81286470-b1744200-9093-11ea-9d73-9b306427f4d4.png)

**如何重现**
附件Demo:
[Demo.zip](https://github.com/Tencent/QMUI_iOS/files/4592517/Demo.zip)

**预期的表现**
下面截图是v4.1.1的表现，我想应该是正常的，因为和系统的表现是一致的。
![Screen Shot 2020-05-07 at 6 52 23 PM](https://user-images.githubusercontent.com/6427544/81286655-fa2bfb00-9093-11ea-9d3c-c51cfbe5c1f1.png)

**Comment by evanzhou1989** [comment]
shouldFixTabBarSafeAreaInsetsBug引起的问题

**Comment by MoLice** [comment]
已发布 [4.1.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.3) 修复该问题。
