### ISSUE TITLE
shouldFixTabBarSafeAreaInsetsBug 导致某些结构的 UIScrollView 页面出现 inset 错误的问题

### ISSUE THREAD

**Issue by codingiran** [Tencent/QMUI_iOS#981]
**Bug 表现**
配置表开启 `QMUICMI.shouldFixTabBarSafeAreaInsetsBug = YES;  `后参见动图：
![演示动图](https://user-images.githubusercontent.com/11780294/81363401-d4473a80-9115-11ea-8f6c-f80adb9d6843.gif)

**如何重现**
 下方 Demo 复现（只引入 QMUIKit 和 Lookin）
[shouldFixTabBarSafeAreaInsetsBug.zip](https://github.com/Tencent/QMUI_iOS/files/4596660/shouldFixTabBarSafeAreaInsetsBug.zip)

**预期的表现**
正常情况下，应该不出现 inset 的跳动

**其他信息**
 - 设备: iPhone XR
 - iOS 版本: iOS 13.4.1
 - Xcode 版本: Xcode 11.4.1
 - QMUI 版本: 4.1.2

**Comment by MoLice** [comment]
已发布 [4.1.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.1.3) 修复该问题。
