### ISSUE TITLE
V4.1.2 QMUIModalPresentationViewController 调用hideWithAnimated无法关闭

### ISSUE THREAD

**Issue by tanranran** [Tencent/QMUI_iOS#983]
**Bug 表现**
问题的具体描述
升级到4.1.2 QMUIModalPresentationViewController 调用hideWithAnimated无法关闭
降级到4.1.1之前r 调用hideWithAnimated可以关闭

看了下4.1.2的修订记录+调试，发现在hideWithAnimated中新增了if (self.visible) return;，而self.visible=YES 时的赋值似乎有问题

**截图**

**如何重现**
`
UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 300, 208)];
    contentView.backgroundColor = UIColor.qd_backgroundColorLighten;
    contentView.layer.cornerRadius = 6;
QMUIModalPresentationViewController *modalViewController = [[QMUIModalPresentationViewController alloc] init];
    [modalViewController.view addSubview:contentView];
    [modalViewController showWithAnimated:YES completion:nil];
[modalViewController hideWithAnimated:NO completion:nil];

`

**预期的表现**
调用hideWithAnimated可以关闭

**其他信息**
 - 设备:[iPhone]
 - iOS 版本: [iOS 13.4]
 - Xcode 版本: [Xcode 11.4]
 - QMUI 版本: [4.1.2]

**Comment by peterios2016** [comment]
如果用4.1.3也会出现是吗

**Comment by MoLice** [comment]
已发布 [4.2.1](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.1) 修复该问题。
