### ISSUE TITLE
'CALayer+QMUIViewAnimation.h' file not found

### ISSUE THREAD

**Issue by ZenonHuang** [Tencent/QMUI_iOS#984]
**Bug 表现**
编译无法通过

**问题提示**
QMUIVisualEffectView.m 上显示：
'CALayer+QMUIViewAnimation.h' file not found

**如何重现**
1. Pod 使用 QUMI :   pod 'QMUIKit'
2. 进行编译

**预期的表现**
正常不应该缺少 CALayer+QMUIViewAnimation.h 文件

**其他信息**

 - QMUI 版本:  QMUIKit (4.0.4)

**Comment by MoLice** [comment]
#953
