### ISSUE TITLE
DGActivityIndicatorView 框架引起的内存爆增

### ISSUE THREAD

**Issue by insist159** [Tencent/QMUI_iOS#985]
**Bug 表现**
问题的具体描述
在QMUI_IOS的demo中使用 <DGActivityIndicatorView> 这个框架会内存爆增导致闪退
我新建一个工程使用pod导入qmui框架 ，然后使用该框架不会有问题，然后在官方的demo里不知道qmuiuikit是设置了哪种属性下会触发DGActivityIndicatorView layoutSubviews 的一个死循环

DGActivityIndicatorView 在github上搜索就可以
**截图**

qmuidemo[1622:326076] [ServicesDaemonManager] interruptionHandler is called. -[FontServicesDaemonManager connection]_block_invoke
Message from debugger: Terminated due to memory issue

**如何重现**
在QMUI_IOS的demol里任何的view上使用:

DGActivityIndicatorView *activityIndicatorView = [[DGActivityIndicatorView alloc] initWithType:DGActivityIndicatorAnimationTypeDoubleBounce tintColor:[UIColor whiteColor] size:20.0f];
    activityIndicatorView.frame = CGRectMake(100, 100, 50.0f, 50.0f);
    [self.view addSubview:activityIndicatorView];
    [activityIndicatorView startAnimating];

**预期的表现**
正常情况下，应该是什么表现:

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.4]
 - Xcode 版本: [Xcode 11.2.1]
 - QMUI 版本: [4.1.1]

**Comment by insist159** [comment]
@MoLice

**Comment by MoLice** [comment]
遇到第三方库相关的问题，请自行集成一个 Demo 后发到 issue 内以便及时处理。

**Comment by insist159** [comment]
好的，稍后我会抽空弄一个demo出来。请不要关闭该 issue

**Comment by iWolfSex** [comment]
怎么解决的？我集成ijk播放视频时也遇到了类似的问题。
