### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions for

### ISSUE THREAD

**Issue by biaoxiaoa** [Tencent/QMUI_iOS#990]
**Bug 表现**
使用QMUIDialogTextFieldViewController点击【取消】、【确定】按钮后，控制台都会输出：Unbalanced calls to begin/end appearance transitions for <QMUIModalPresentationViewController:XXXXXX>

**其他信息**
 - 设备: [例如模拟器、iPhone Xs Max]
 - iOS 版本: [iOS 13.4.1]
 - Xcode 版本: [Xcode 11.4]
 - QMUI 版本: [4.1.1]

**Comment by codingiran** [comment]
see [#758](https://github.com/Tencent/QMUI_iOS/issues/758)
