### ISSUE TITLE
请问：该库是否提供按钮渐变色、各个方向独立圆角功能呢？

### ISSUE THREAD

**Issue by TML007** [Tencent/QMUI_iOS#991]
QMUI 已经提供了**详尽的注释文档**，以及**完整的示例项目 [QMUI Demo](https://github.com/QMUI/QMUI_iOS_Demo)**，当你遇到某些功能不知道怎么使用，或者想知道 QMUI 是否有提供某些功能时，请先查看注释文档或者 Demo，找不到了再提 issue。若提的 issue 已有明确注释或示例的，**可能会被直接关闭或得不到及时的回复**，请知悉。

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/81903332-39a69a00-95f4-11ea-908e-2802cefc6d3e.png)

![image](https://user-images.githubusercontent.com/1190261/81903491-69ee3880-95f4-11ea-94c0-5c1492710604.png)

QMUI 已经提供了详尽的文档，各个方向独立圆角这些都在文档里有写，简单查询即可。

渐变色不具备较高的通用性，QMUI 没提供现成的，需要业务自行实现。
