### ISSUE TITLE
您好！我只引入部分内容，但却与另一个库RTRootNavigationController冲突、使得手势返回没效果。

### ISSUE THREAD

**Issue by TML007** [Tencent/QMUI_iOS#992]
**Bug 表现**
问题的具体描述
哪怕我使用您库中的方法：- (BOOL)forceEnableInteractivePopGestureRecognizer;- (BOOL)shouldPopViewControllerByBackButtonOrPopGesture:(BOOL)byPopGesture 都没有效果。在我移除QMUI库后手势正常。我估计是UINavigationController+QMUI 有影响。不知道你们能否将QMUICore也分开配置
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="716" alt="image" src="https://user-images.githubusercontent.com/19261542/82015572-a2078100-96b1-11ea-8f61-0948753162d9.png">

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by TML007** [comment]
[QMUIDemo.zip](https://github.com/Tencent/QMUI_iOS/files/4632521/QMUIDemo.zip)
这是demo

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/82540636-e7302500-9b81-11ea-8a67-131ba5d64793.png)
RTRootNavigationController 内部会把手势的 delegate 指向自己，而 UINavigationController+QMUI 也做了相同的事情，这本身不冲突。
不过在 UINavigationController+QMUI 里，我们额外实现了 `_gestureRecognizer:shouldReceiveEvent:` 这个私有方法，在该方法里结合系统原本的手势返回 delegate 的值来决定是否允许返回，由于你使用了 RTRootNavigationController，它默认会通过给 `leftBarButtonItem` 设置一个按钮，从而把返回按钮改为一个自定义的，而系统的默认行为是当你的 `leftBarButtonItem` 不为空时禁用手势返回，这也是为什么 QMUI 专门提供方法 `forceEnableInteractivePopGestureRecognizer` 来让你可以重新开启手势返回。

![image](https://user-images.githubusercontent.com/1190261/82541046-6f162f00-9b82-11ea-82b3-042ea8c5121c.png)

然而由于 RTRootNavigationController 会给每一个 viewControllers 都包一层 RTContainerController，所以你在自己的 `QMUIButtonViewController` 里实现任何方法，外部都是感知不到的，因为外部拿到的都是 `RTContainerController`，所以 `forceEnableInteractivePopGestureRecognizer` 也无法使用。

目前的临时处理方法有几个，你可以自行选择：
1. 把 QMUINavigationController+QMUI 里的 `_gestureRecognizer:shouldReceiveEvent:` 方法注释掉。
2. 为 RTRootNavigationController 增加 `_gestureRecognizer:shouldReceiveEvent:` 方法并返回 YES。
3. 不要同时使用这两个库。

**Comment by TML007** [comment]
谢谢回复和提供解决方案,问题得以解决。🙏
