### ISSUE TITLE
出现了子线程调用UI的问题，看上去是在QMUI_Border分类的Load方法里开始的

### ISSUE THREAD

**Issue by derekhuangxu** [Tencent/QMUI_iOS#993]
**Bug 表现**
出现了子线程调用UI的问题。

**截图**
<img width="894" alt="截屏2020-05-16 17 26 26" src="https://user-images.githubusercontent.com/12634684/82116214-9ba10400-979a-11ea-9454-5bef3684b5ab.png">

**如何重现**
目前为止暂时没有复现流程。

**预期的表现**
不会出现了子线程调用UI的问题。

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.1.2以上版本]
 - Xcode 版本: [Xcode 11.4.1]
 - QMUI 版本: [4.0.2]

**Comment by MoLice** [comment]
主要看是谁触发了这些方法，如果是业务触发的，则检查业务为什么会触发。如果是系统触发的看能否贴一些还原后的堆栈看看。

**Comment by derekhuangxu** [comment]
> 主要看是谁触发了这些方法，如果是业务触发的，则检查业务为什么会触发。如果是系统触发的看能否贴一些还原后的堆栈看看。这个问题的关键还是在于谁触发的，而不是有没有 swizzle 这些方法。

![截屏2020-05-19 09 35 37](https://user-images.githubusercontent.com/12634684/82275072-65d76780-99b4-11ea-9764-c437fd31f5a8.png)
这是还原后的堆栈信息，看上去是在main函数启动之后遭遇的crash

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/82298806-3e4dc280-99e7-11ea-85da-b3030a4f3ec0.png)

关键应该是这里，某个地方触发了某个 `CALayer` 的 `layoutSublayers` 方法（该方法在子线程调用不会触发 MainThreadChecker），而这个  `CALayer` 可能是某个 `UIView` 内置的 layer，所以 layer.delegate 指向某个 `UIView`，于是就触发了 `- [UIView layoutSublayersOfLayer:]`，这个方法会触发 MainThreadChecker 警告，不管这个 `layoutSublayersOfLayer:` 内部的实现是什么。

所以建议排查为什么会有截图里那个 `[CALayer layoutSublayers]` 出现。

**Comment by MoLice** [comment]
该 issue 因不活跃而被关闭。
