### ISSUE TITLE
展示两条不同的导航栏，寻求更好的过渡动画。

### ISSUE THREAD

**Issue by Scr1pVanNe** [Tencent/QMUI_iOS#994]
我将Demo中QDChangeNavBarStyleViewController的导航Title修改成短字符串后，发现返回手势的导航过渡动画有异样，未找到相关Issue，请求帮助。

**长标题情况**

![Jietu20200518-101206-HD](https://user-images.githubusercontent.com/30721832/82168226-d9b03c00-98f0-11ea-9213-4f18de44bd47.gif)

**短标题情况**

![Jietu20200518-101358-HD](https://user-images.githubusercontent.com/30721832/82168242-e46ad100-98f0-11ea-8b0d-4a268139bf2f.gif)

**Comment by MoLice** [comment]
系统对于自定义 titleView 的情况，默认行为就是如此，你可以新建一个空项目，用以下代码测试：
```objc
- (void)viewDidLoad {
    [super viewDidLoad];
    UILabel *label = UILabel.new;
    label.textColor = UIColor.blackColor;
    label.backgroundColor = [UIColor.redColor colorWithAlphaComponent:.3];
    label.text = @"ABC";
    [label sizeToFit];
    self.navigationItem.titleView = label;
}
```

短期内 QMUI 不会优化这个表现，业务可以选择将 QMUI 添加的自定义 titleView 去掉，只需要重写 `-[QMUICommonViewController didInitialize]`，在里面执行 `self.navigationItem.titleView = nil;` 即可。

**Comment by Scr1pVanNe** [comment]
谢谢。
