### ISSUE TITLE
UINavigationController+QMUI.m文件在load里面替换了interactivePopGestureRecognizer.delegate

### ISSUE THREAD

**Issue by CodeSlaveZhang** [Tencent/QMUI_iOS#996]
**Bug 表现**
iOS 12.4.1 iPhone8  当viewcontrollers.count==1的时候继续手势返回，下次pop就卡死了。
问题的具体描述
具体出现的原因不详，但是
UINavigationController+QMUI.m文件在load里面替换了interactivePopGestureRecognizer.delegate。
但是originGestureDelegateKey 又是nil导致系统的delegate没有保存。

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. ...
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 13.x]
 - Xcode 版本: [Xcode 11.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
正常情况下并不会出现在 viewControllers.count == 1 时还能继续手势返回的情况，所以请提供一个 Demo 以供排查。

**Comment by CodeSlaveZhang** [comment]
这边也只是在iOS13.4.1 iPhone8上偶现。你们也可以在这个系统的手机上试试。
目前我这边的解决方案就是重写手势功能，屏蔽掉qmui的手势。





------------------ 原始邮件 ------------------
发件人: MoLice <notifications@github.com&gt;
发送时间: 2020年5月18日 22:58
收件人: Tencent/QMUI_iOS <QMUI_iOS@noreply.github.com&gt;
抄送: CodeSlaveZhang <283548208@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/QMUI_iOS] UINavigationController+QMUI.m文件在load里面替换了interactivePopGestureRecognizer.delegate (#996)

**Comment by MoLice** [comment]
必然是引入一些其他的库或者业务代码存在一些问题才会出现这种情况的，不提供 Demo 的情况下尝试没有意义，这些代码已经经过多个版本的线上检测，没出现过这种问题。
你可以先按你的方法处理，如有 Demo 可以复现，再打开本 issue。

**Comment by wenhhh** [comment]
iOS 13.4+ 确实会出现问题，复现方式为在QMUINavigationController.rootViewController页面进行手势返回。
附上SO上提及的修复方法：https://stackoverflow.com/a/38042863
