### ISSUE TITLE
qmui_hasCustomizedKeyboardAppearance的赋值有些问题

### ISSUE THREAD

**Issue by jiasongs** [Tencent/QMUI_iOS#997]
**Bug 表现**
聚焦一个UITextView或UITextField，切换到后台再进入到前台时，就会导致keyboardAppearance设置不正确，请看如下操作视频

**截图**
[RPReplay_Final1589880938.mov.zip](https://github.com/Tencent/QMUI_iOS/files/4649531/RPReplay_Final1589880938.mov.zip)

**如何重现**
1.  手机不要打开Dark模式
2. 打开QMUIDemo，找到QMUITextView示例界面
3. 将QMUITextView聚焦，切换到后台，等一会，再切换到前台即可重现

**预期的表现**
正常情况下，qmui_hasCustomizedKeyboardAppearance应该是业务调用时才设置为true

**其他信息**
 - 设备: iPhone
 - iOS 版本: 13.4.1
 - Xcode 版本: Xcode 11.4.1
 - QMUI 版本: 4.1.3

**Comment by MoLice** [comment]
下个版本会修复，在此之前可以先用以下文件替换本地的 QMUI 同名文件。
[keyboardAppearance.zip](https://github.com/Tencent/QMUI_iOS/files/4652489/keyboardAppearance.zip)

**Comment by MoLice** [comment]
已发布 [4.2.0](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.0) 修复该问题。
