### ISSUE TITLE
QMUITextView 输入时文字抖动

### ISSUE THREAD

**Issue by SwiftBMan** [Tencent/QMUI_iOS#999]
**Bug 表现**
QMUITextView 输入一行后，第一行自动会向上移动一小段距离？

**如何重现**
输入一行后 ，换行的时候

**预期的表现**
正常情况下，不动才对

**Comment by MoLice** [comment]
已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 修复该问题。
